### ISSUE TITLE
Raspberry is still using public DNS servers

### ISSUE THREAD

**Issue by darootler** [home-assistant/supervisor#1316]
Home Assistant release with the issue:
hassos: "2.11"
homeassistant: 0.99.2
machine: raspberrypi3
supervisor: "188"

Operating environment (Hass.io/Docker/Windows/etc.):
Hass.io

Component/platform:
DNS

Description of problem:
The raspberry is still using 1.1.1.1 and 9.9.9.9 as DNS servers:

![image](https://user-images.githubusercontent.com/11849583/65836971-31168300-e2f3-11e9-860d-3f5938c4ed7c.png)

I already set the dns server with the following command:

![image](https://user-images.githubusercontent.com/11849583/65409175-4ff2b200-dde7-11e9-981a-34cd803cb3c1.png)

**Comment by Diaoul** [comment]
It looks like [there](https://github.com/home-assistant/hassio/issues/1232) [are](https://github.com/home-assistant/hassio/issues/1251) [multiple](https://github.com/home-assistant/hassio/pull/1262) [issues](https://github.com/home-assistant/hassio/issues/1239) on this topic.

I've read the code a bit and it seems there is no way to override those settings and have CoreDNS **not** use public DNS servers.
Indeed the [`DNS_SERVERS`](https://github.com/home-assistant/hassio/blob/master/hassio/const.py#L35) configuration [is used no matter what](https://github.com/home-assistant/hassio/blob/master/hassio/dns.py#L221).

Please put *local control and privacy first* :smile: :muscle:

**Comment by jsiemek** [comment]
The commands to overwrite DNS settings are:

hassio dns options --servers dns://192.168.90.1
hassio dns restart

**Comment by darootler** [comment]
> The commands to overwrite DNS settings are:
> 
> hassio dns options --servers dns://192.168.90.1
> hassio dns restart

As i already mentioned above this command does not really work.

Regards
Richard

**Comment by bart1970** [comment]
I have the same experience that it doesn't work. See also:
https://community.home-assistant.io/t/working-of-dns-in-container/150857

**Comment by matt-FFFFFF** [comment]
I also have this issue, the ```corefile``` generated by the supervisor does not prefer the admin-defined servers implemented using the ```--servers dns://w.x.y.z```.

In my case the order of servers is DHCP -> 1.1.1.1 -> AdminDefined -> 9.9.9.9

This seems a very strange way of doing things. A better way would perhaps be:

Admin defined -> DHCP -> 1.1.1.1 -> 9.9.9.9

**Comment by matt-FFFFFF** [comment]
The above PR prioritises admin defined DNS servers over DHCP and fallback. Hopefully this will be accepted.

**Comment by mkArtak** [comment]
> The above PR prioritises admin defined DNS servers over DHCP and fallback. Hopefully this will be accepted.

Hi @matt-FFFFFF. I'm also facing this issue and wondering how can I fix this. Am running HassIO on a Raspberry PI. How can I configure the admin defined DNS servers?

**Comment by pvizeli** [comment]
@mkArtak he uses the system DNS or the manual setup DNS. If this is not working (the DNS server did not respond because of a wrong setup) he moves over to the docker default settings 8.8.8.8 or our predefined list with 1.1.1.1

**Comment by Diaoul** [comment]
Honestly I would prefer hassio crashing with DNS error than using some hardcoded DNS as a fallback without my permission. If my DNS is not setup correctly, my apps don't work and this is what I would expect. Is there a good reason to not stick to the OS defined DNS setup and enforce some fallbacks? I can't think of other apps having such behavior, even [Firefox allows to opt-out](https://support.mozilla.org/en-US/kb/firefox-dns-over-https).

Even with "sane" fallbacks such as 1.1.1.1 and 9.9.9.9 that say they respect privacy, this could lead to serious privacy leaks. It uses default dns protocol and not DNS over TLS in the corefile. And maybe I don't want my traffic to them.

I understand there is a balance between privacy and ease of use, and that you don't want bug reports from people having their DNS misconfigured. However I think hiding the real problem by compromising on privacy isn't the good way. I'd rather have an error message that links to a how-to-configure-dns-for-noobs or an opt-in popup to accept those fallbacks.
I have no idea how to make those error show up in a user friendly fashion though.

Thoughts?

**Comment by mkArtak** [comment]
> @mkArtak he uses the system DNS or the manual setup DNS. If this is not working (the DNS server did not respond because of a wrong setup) he moves over to the docker default settings 8.8.8.8 or our predefined list with 1.1.1.1

Thanks @pvizeli. I'm actually trying to figure out how to configure my router as the DNS server. Do you know whether this is possible?

**Comment by mkArtak** [comment]
> > @mkArtak he uses the system DNS or the manual setup DNS. If this is not working (the DNS server did not respond because of a wrong setup) he moves over to the docker default settings 8.8.8.8 or our predefined list with 1.1.1.1
> 
> Thanks @pvizeli. I'm actually trying to figure out how to configure my router as the DNS server. Do you know whether this is possible?

I've solved after some investigation, by modifing the `/etc/resolve.conf` file and added my router IP address as well as public DNS records.

**Comment by jschwalbe** [comment]
@mkArtak which `resolve.conf` did you edit? On the host OS?

Despite 
```
bash-5.0# ha dns info
host: 172.30.32.3
latest_version: "1"
locals:
- dns://192.168.25.81
servers:
- dns://192.168.25.81
version: "1"
```

I'm still seeing DNS requests going to 1.1.1.1.

@pvizeli if you want to use my machine to debug, I'm happy to let you in. Contact me?

**Comment by mkArtak** [comment]
> @mkArtak which resolve.conf did you edit? On the host OS?

This one: `/etc/resolve.conf`

**Comment by pvizeli** [comment]
@jschwalbe the correct firewall setup if you want block DNS is to forward it to your preferred DNS. Many products have a fallback i.e. docker itself. If you run docker with default settings like 95% of persons do, it will use Google DNS as a fallback, hardcoded in that codebase.

The reason is simple, CoreDNS is set up to try your DNS server (in this case 192.168.25.81), but if they don't respond (to slow) or if he detects issues like loops, he fallback to our trust of DNS servers. To be fair, since most user use the default settings, he use the trust DNS server of docker before he go over to use our fallback.

**Comment by jschwalbe** [comment]
> You can see that like a sign, if CoreDNS don't like you DNS setup and use the fallback, you should maybe stop to use a custom DNS setup. I know it's simple to setup such a DNS server but to run that correctly inside a Network can be an issue.

@pvizeli Thanks for that! I've determined that Core DNS simply doesn't have the ability to connect to the AdGuard DNS server (via HA plugin, running on the same machine but in a different docker image). If I point CoreDNS to a different server on my network, everything works as expected (and I see all the etc.local lookup requests getting sent to it). I suppose this is either a bug with HA or a bug with docker. My solution until this can be fully identified and fixed will be to run AdGuard on a _separate_ machine, which is too bad, but apparently necessary.
