### ISSUE TITLE
Hassio can't update Home Assistant access token!

### ISSUE THREAD

**Issue by rourke750** [home-assistant/supervisor#1377]
**Home Assistant release with the issue:** 0.101.3

**Operating environment (HassOS/Generic):** Debian 9.

**Supervisor logs:**

19-11-18 13:15:29 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:15:29 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-11-18 13:20:35 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:20:35 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-11-18 13:25:40 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:25:40 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-11-18 13:30:45 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:30:45 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-11-18 13:35:50 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:35:50 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-11-18 13:40:55 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:40:55 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-11-18 13:46:00 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:46:00 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-11-18 13:51:05 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:51:05 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-11-18 13:54:13 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-11-18 13:55:51 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:55:51 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request services/switch/toggle
19-11-18 13:56:10 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:56:10 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request states/binary_sensor.snapshots_stale
19-11-18 13:57:20 ERROR (MainThread) [hassio.homeassistant] Can't update Home Assistant access token!
19-11-18 13:57:20 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request services/switch/toggle
19-11-18 14:00:49 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh

**Description of problem:**

For the past few releases I noticed the Dassio stopped working.  When I decided to fix it I noticed that every time I pressed a button it would return with a 502 error and hassio would report that it couldnt update Home Assistant access token and that there was an authentication error.  I noticed that this also occured with other addons that attempted to communicate with homeassistant over the ha proxy.

I believe it might have something to do with my system users but I attempted to delete them and have them be regenerated but that did not fix the problem.

**Comment by joggs** [comment]
I had the same problem and the problem was that my system user had been banned, so i cleared the ip_bans file in the config dir and restarted hass ( 2 times )
