### ISSUE TITLE
Homeassistant update fails to pull "too many levels of symlinks"

### ISSUE THREAD

**Issue by devanl** [home-assistant/supervisor#1383]
**Home Assistant release with the issue:**
N/A (0.101.2)

**Operating environment (HassOS/Generic):**
Generic (Raspbian Buster) on pi 3B boot from USB

> REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
> homeassistant/armv7-addon-configurator     3.7                 430b25c45506        2 days ago          137MB
> homeassistant/armv7-addon-ssh              7.0                 3f2050ad01fe        7 days ago          79.7MB
> homeassistant/raspberrypi3-homeassistant   0.101.2             d97309165d11        3 weeks ago         972MB
> homeassistant/armv7-hassio-supervisor      192                 d5ed4af8d296        4 weeks ago         209MB
> homeassistant/armv7-hassio-supervisor      latest              d5ed4af8d296        4 weeks ago         209MB
> homeassistant/armv7-addon-mariadb          1.3                 78502c361a7f        7 weeks ago         163MB
> homeassistant/armv7-addon-mosquitto        5.1                 c8d3757b5e04        2 months ago        27.6MB
> homeassistant/armv7-hassio-dns             1                   1b24f5e32994        3 months ago        51.8MB
> 

**Supervisor logs:**

> 19-11-25 19:01:38 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
> 19-11-25 19:08:18 INFO (MainThread) [hassio.host.info] Update local host information
> 19-11-25 19:08:18 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
> 19-11-25 19:08:19 INFO (MainThread) [hassio.host.services] Update service information
> 19-11-25 19:08:19 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
> 19-11-25 19:08:19 INFO (MainThread) [hassio.host.network] Update local network DNS information
> 19-11-25 19:08:19 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
> 19-11-25 19:14:13 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.102.2
> 19-11-25 19:14:13 INFO (SyncWorker_16) [hassio.docker.interface] Update image homeassistant/raspberrypi3-homeassistant:0.101.2 to homeassistant/raspberrypi3-homeassistant:0.102.2
> 19-11-25 19:14:13 INFO (SyncWorker_16) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.102.2.
> 19-11-25 19:15:04 ERROR (SyncWorker_16) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.102.2 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi3-homeassistant:0.102.2: No such image: homeassistant/raspberrypi3-homeassistant:0.102.2").
> 19-11-25 19:15:04 WARNING (MainThread) [hassio.homeassistant] Update Home Assistant image fails

**Description of problem:**
Hass.io fails to update from dashboard.
Manual pull of image fails as well...

> ~ $ docker pull homeassistant/raspberrypi3-homeassistant
> Using default tag: latest
> latest: Pulling from homeassistant/raspberrypi3-homeassistant
> 33b18ff7f9b7: Already exists
> 1f4eba7913e4: Already exists
> 4b7876757797: Already exists
> 025d5ca8b1d3: Already exists
> f4085647b184: Already exists
> ba7f8a38f0e4: Already exists
> b2e5de686b38: Already exists
> 63e3f6d3be64: Already exists
> b47de80f44d0: Already exists
> 803529260f21: Already exists
> 3a9122242f39: Already exists
> 403538b6b17b: Already exists
> 5baaaaa75e10: Already exists
> a538d4ee7dc7: Already exists
> f629db3e8592: Already exists
> 888b0e3aa4ca: Extracting [==================================================>]     266B/266B
> 88920fc2d5b3: Download complete
> 7ed05956e800: Download complete
> 1c18622079d2: Download complete
> 0b8407eb6248: Download complete
> d81f9cc98008: Download complete
> 65ba6f946a7e: Download complete
> 119825fff10f: Download complete
> failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/49d9525b2de022b525e77edbed661be53911693d0c0c2f7d08b4936d206fdcd1/merged: too many levels of symbolic links
>

**Comment by pvizeli** [comment]
`hassio su repair`

However, we modify HassOS to run more docker layers / images. It could be that you reach out what is possible with raspbian.

**Comment by Krandelbord** [comment]
Now I have recent version of home-assistant from home-assistant-os and when I do 
supervisor update I get "too many levels of symbolic links"
