### ISSUE TITLE
No mapping for /backup, so core components cannot access that folder

### ISSUE THREAD

**Issue by metbril** [home-assistant/supervisor#1398]
**Home Assistant release with the issue:**

0.103.0

**Operating environment (HassOS/Generic):**

HassOS

**Supervisor logs:**

**Description of problem:**

The `/backup` folder cannot be whitelisted and hence cannot be used with the folder watcher.

This is an old issue from a now archived repo, that still has not yet been resolved:

https://github.com/home-assistant/hassio-build/issues/129

## Use case
I hope this can be resolved, so I can use this to build an automation that signals the creation of a new snapshot (and take appropriate action).

One intended automation creates a schedules/timed full backup using the `hassio.snapshot_full` service. 
Then another automation is triggered when a new snapshot is created in the /backup folder. This uses the Dropbox Sync addon to sync it with the `hassio.addon_stdin` service. 

https://github.com/danielwelch/hassio-dropbox-sync

The current workaround is, to have the first automation do a forced delay that is too long and then run the Dropbox sync when we guess the snapshot is done. Not so nice.

**Comment by frenck** [comment]
It is simply not exposed, not sure if that would be a good idea in general though...

**Comment by metbril** [comment]
Could you explain a little why you think it isn't?

**Comment by metbril** [comment]
Perhaps @pvizeli could give this issue some love?

**Comment by nicoolaro** [comment]
i would also like to request this, so that we can backup snapshots to remote location via shell/automation.

currently i am editing docker json config but thats not a long term solution, not sure which security concerns are there to not exposed Backup folder.
It would save a lot of headache..

**Comment by pvizeli** [comment]
Access to backup folder is realy not a good idea and only a quick. However, I accept all PR they send a event to the Core over an API from that integration after a snapshot is created. Feel free to implement this so that you can automate your use case.

**Comment by nicoolaro** [comment]
> Access to backup folder is realy not a good idea and only a quirk. However, I accept all PR they send a event to the Core over an API from that integration after a snapshot is created. Feel free to implement this so that you can automate your use case.

Unfortunately i dont quite understand how that works or what that even means. I'll let someone smarter do that if there someone willing.
Thank you for the clarification!
