### ISSUE TITLE
Error updating to HassOS 3

### ISSUE THREAD

**Issue by sebastian-tennant** [home-assistant/supervisor#1402]
**Home Assistant release with the issue:**
Home Assistant 0.103.0

**Operating environment (HassOS/Generic):**
HassOS 2.12
Supervisor v192
Virtual Machine (ESX) 

**Supervisor logs:**
```
19-12-17 22:40:09 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-12-17 22:40:09 INFO (MainThread) [hassio.api.proxy] WebSocket access from core_almond
19-12-17 22:40:09 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
19-12-17 22:40:12 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-12-17 22:47:18 INFO (MainThread) [hassio.hassos] Fetch OTA update from https://github.com/home-assistant/hassos/releases/download/3.7/hassos_ova-3.7.raucb
19-12-17 22:47:32 INFO (MainThread) [hassio.hassos] OTA update is downloaded on /data/tmp/hassos-3.7.raucb
19-12-17 22:47:32 INFO (MainThread) [hassio.utils.gdbus] Call de.pengutronix.rauc.Installer.Install on /
19-12-17 22:47:32 INFO (MainThread) [hassio.utils.gdbus] Start dbus monitor on de.pengutronix.rauc
19-12-17 22:47:33 INFO (MainThread) [hassio.utils.gdbus] Stop dbus monitor on de.pengutronix.rauc
19-12-17 22:47:33 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 147, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 39, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/hassos.py", line 44, in update
    await asyncio.shield(self.sys_hassos.update(version))
  File "/usr/src/hassio/hassio/hassos.py", line 177, in update
    rauc_status = await self.sys_dbus.get_properties()
AttributeError: 'DBusManager' object has no attribute 'get_properties'
```

**Description of problem:**

When attempting to update to the latest version of HassOS, I encounter the error as above. 
This occurs when trying to initiate the upgrade via the (web)UI by going to Hass.io > System > Update

**Comment by pvizeli** [comment]
I created a PR that the error will be reported correct. However it fails. Could be that the system time of VM is wrong?

**Comment by sebastian-tennant** [comment]
> Could be that the system time of VM is wrong?

Both the hypervisor and the VM are correct down to the second. I don't know of the best way to show proof of this, sorry.

**Comment by pvizeli** [comment]
what is the output of `rauc info` after fail update?

**Comment by sebastian-tennant** [comment]
> what is the output of `rauc info` after fail update?

Thanks for the assistance. Is there additional information I should be passing this command? It says:
```
# rauc info
A file name must be provided 
```

**Comment by pergolafabio** [comment]
i had same issue
on cold boot, its indeed UTC , but if i do a restart of HA, not reboot, my timezone is correct
when i did update again, it succeeded

**Comment by pvizeli** [comment]
Sorry, `rauc status`

**Comment by sebastian-tennant** [comment]
> i had same issue
> on cold boot, its indeed UTC , but if i do a restart of HA, not reboot, my timezone is correct
> when i did update again, it succeeded

I've tried various combinations of this (rebooting whole VM, just supervisor, just HA, etc) but to no avail :( 

> Sorry, `rauc status`

Ah! Attached output 
<img width="817" alt="Screen Shot 2019-12-19 at 8 06 28 am" src="https://user-images.githubusercontent.com/29113210/71125349-acbf0680-2236-11ea-9d24-c7cda03b86b9.png">

**Comment by pergolafabio** [comment]
No idea, it worked for me on second attempt after restart HA

**Comment by jensihnow** [comment]
Same here, tired rebooting VM and so on. Still getting this error and unable to update. I'm also running on ESX, currently on HassOS 2.12 but supervisor 193.
