### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by elsbrock** [home-assistant/supervisor#1405]
Since https://github.com/home-assistant/hassio-supervisor/issues/355 was closed, I would like to open another issue to ask for proper IPv6 support.

I am no expert on HASS itself but am operating a separate Docker host with IPv6 enabled via `macvlan` network plugin, so this is definitely possible.

In my opinion IPv6 not a nerd topic anymore and software should really try to support it. There are many use cases for it; many consumer ISPs provision NATted IPv4 endpoints while providing full IPv6 connectivity. Mobile network providers have also started providing IPv6 connectivity to mobile equipment. It is just natural HASS should support it.

What is needed to make this happen? How could the end-user experience look like so that this is a seamless experience for single-/dual-stack users?

**Comment by Thyreal** [comment]
Since about two weeks i switched to a different network vendor, since then i am not able to get Hass.io to function anymore. An ipv6 support is, as fare as i am concerned, necessary to get it back up and running. I really like the way the system is build but i just can't get the ipv6 zo work. Witch renders in completely useless to me. 
Has anyone an idea of how to get the dual stack ipv6 and ipv4 working??

**Comment by pvizeli** [comment]
We need wait (I think) 1-2 year until IPv6 support land on docker with NAT6 and virtual IPv6 stacks or provider give a range to all users to routing sub network range for virtual networks (but that will be never happens because the routing ranges are not bigger as the ipv4 addresses).

**Comment by pvizeli** [comment]
If you need additional help with this template please refer to https://www.home-assistant.io/help/reporting_issues/
Make sure you are running the latest version of Home Assistant before reporting an issue: https://github.com/home-assistant/home-assistant/releases
Do not report issues for components here, plaese refer to https://github.com/home-assistant/home-assistant/issues
This is for bugs only. Feature and enhancement requests should go in our community forum: https://community.home-assistant.io/c/feature-requests
Provide as many details as possible. Paste logs, configuration sample and code into the backticks. Do not delete any text from this template!
If you have a problem with a Add-on, make a issue on there repository.

**Comment by peter-dolkens** [comment]
> Can this issue be re-opened?

This issue is already being tracked in #2133
