### ISSUE TITLE
Coredns eating cpu and memory

### ISSUE THREAD

**Issue by vandalon** [home-assistant/supervisor#1409]
**Home Assistant release with the issue:**
Frontend version: 20191204.1
Home Assistant 0.103.4

**Operating environment (HassOS/Generic):**
➜  hassio hassos info
board: rpi4-64
version: "3.7"
version_cli: "15"
version_cli_latest: "15"
version_latest: "3.7"

**Supervisor logs:**
➜  hassio su logs
19-12-30 22:28:00 INFO (MainThread) [hassio.api.security] /supervisor/logs access from a0d7b954_ssh

**Description of problem:**

hassos / coredns is using 100-200% cpu a lot of the time (not constant, but ofter) and consumes up to 500MB of memory.

**Comment by vandalon** [comment]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/3370317/71626451-8bbec400-2bed-11ea-96a9-796687549ef2.png">

**Comment by pvizeli** [comment]
can you post the output of `hassio dns stats`?
