### ISSUE TITLE
DWD attributes

### ISSUE THREAD

**Issue by dimafemabo** [home-assistant/supervisor#1464]
**Home Assistant release with the issue:** 0.93.1

**Operating environment (HassOS/Generic):** 
raspberry pi3+ 
docker container
arch | armv7l
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.3

**Supervisor logs:** n/a

**Description of problem:**
I added the DWD warning sensors.

I have a value template as follow:
>  - platform: template
    sensors: 
      warnung_1:
        friendly_name: Warnung 1
        value_template: "{{ state_attr('sensor.wetterwarnung_em_1_current_warning_level', 'warning_1_headline') }}. Hinweis {{ state_attr('sensor.wetterwarnung_em_1_current_warning_level', 'warning_1_description') }} {{- '\n' -}} Anweisung {{ state_attr('sensor.wetterwarnung_em_1_current_warning_level', 'warning_1_instruction') }} {{- '\n' -}} Gültig bis zum {{ states('sensor.wetter_warnung_1_ende') }}. Klicken auf unteres Element um mehr zu sehen!"

` - platform: template
    sensors: 
      warnung_1:
        friendly_name: Warnung 1
        value_template: "{{ state_attr('sensor.wetterwarnung_em_1_current_warning_level', 'warning_1_headline') }}. Hinweis {{ state_attr('sensor.wetterwarnung_em_1_current_warning_level', 'warning_1_description') }} {{- '\n' -}} Anweisung {{ state_attr('sensor.wetterwarnung_em_1_current_warning_level', 'warning_1_instruction') }} {{- '\n' -}} Gültig bis zum {{ states('sensor.wetter_warnung_1_ende') }}. Klicken auf unteres Element um mehr zu sehen!"
` 

The above code in template-dev(editor) returns the correct results and shows the warning number 1 and a full text as I expected it to be.
However, when I use the sensor in a lovelace card it returns:
Warnung 1: Unbekannt (unknown)
If I click on the relevant sensor, all is good and it shows me the attributes correctly.

The attributes I am using are mentioned by the sensor:

> 

>attribution: 
Data provided by DWD region_name: xxxx region_state: BW last_update: 2020-01-30T17:06:41+01:00
warning_count: 1
warning_1_name: SCHWERE STURMBÖEN
warning_1_level: 3
warning_1_type: 1
warning_1_headline: Amtliche WARNUNG vor SCHWEREN STURMBÖEN
warning_1_description: Es treten oberhalb 1000 m schwere Sturmböen mit Geschwindigkeiten zwischen 80 km/h (22m/s, 44kn, Bft 9) und 95 km/h (26m/s, 51kn, Bft 10) aus südwestlicher Richtung auf. In exponierten Lagen muss mit orkanartigen Böen bis 105 km/h (29m/s, 56kn, Bft 11) gerechnet werden.
warning_1_instruction: ACHTUNG! Hinweis auf mögliche Gefahren: Vereinzelt können zum Beispiel Bäume entwurzelt und Dächer beschädigt werden. Achten Sie besonders auf herabstürzende Äste, Dachziegel oder Gegenstände.
warning_1_start: 2020-01-30T16:00:00+01:00
warning_1_end: 2020-01-31T10:00:00+01:00
friendly_name: wetterwarnung em 1
Current Warning Level icon: mdi:close-octagon-outline`

After playing around with the sensors attributes I discovered the following:
In the DWD weather attributes, if there is anything after the “warning_1_description:”
such as in the example before, it returns an error as described.
Also in cases where I templated the above as 1 single template.

Playing with the configuration I just had a warning where there was only the “warning_1_description” and nothing following, so no “warning_1_instruction” and then the description shows up. No error message created.

So this is the first time I submitted an eror report and please be kind with me, in case I posted to much, to little or the wrong format, I am not really sure how I post and paste the information in your needed format.

**Comment by frenck** [comment]
Hi there @dimafemabo!

Thanks for opening up an issue, however, this is the issue tracker for the Home Assistant Supervisor, your issue seems to be with an integration of the Home Assistant Core.

Please report issues with the Home Assistant Core here:

<https://github.com/home-assistant/home-assistant/>

Thanks! 👍
