### ISSUE TITLE
Hassio will only 'half' load

### ISSUE THREAD

**Issue by lancelon** [home-assistant/supervisor#1470]
```
System Health
arch	armv7l
dev	false
docker	true
hassio	true
os_name	Linux
python_version	3.7.6
timezone	Europe/London
version	0.104.3
virtualenv	false
Lovelace
mode	storage
resources	16
views	9
```

Strongly suspect I have an SD card on the way out here. Hassio sort of loads, but none of the hassio addons load. I can get to any page of the front end (so long as I access it locally, not via duckdns) but I can't open the hass.io page itself. Which is a pain because SSH and Samba aren't working and I need those to get my data off... Any ideas? I've tried homeassistant check but it didn't seem to check anything apart from my config file which is fine.

When checking the supervisor logs, I get

`aiohttp.server error handling request` and if I wait a bit longer "key error zigbee2mqtt"

If I type 'addons' (in an attempt to purge zigbee2mqtt!!)  I get `unexpected response`

Thanks

**Comment by pvizeli** [comment]
hmm. `hassio su logs` did not return anything. What is with `hassio su repair`?
