### ISSUE TITLE
Exit Code 128 while trying to update HassOS

### ISSUE THREAD

**Issue by kreisklasse** [home-assistant/supervisor#1482]
**Home Assistant release with the issue:**
0.104.2

**Operating environment (HassOS/Generic):**
Supervisor 195 / HassOS 3.8

**Hardware HassOS is running**
Odroid C2 with 8GB eMMC module

**AddOns installed**
AdGuard-Home / Configurator / WireGuard / Zerotier One / chrony

**Description of problem:**
I did a fresh install, which gave me Supervisor 195 / HassOS 3.8 a while ago.
Since that HassOS does not update HassOS/Supervisor/HomeAssistant/AddOns.
According to logs it cant resolve _github.com_ anymore.
But i use the AdGuard-AddOn in my network and everthing works perfect with resolving DNS-requests.

I also switched off all addon's and restarted the Odroid, but the same errors still occur.

Some others seem to have the same problem:
https://community.home-assistant.io/t/updater-problem-exit-code-128-could-not-resolve-host-github-com/165391

**Home-Assistant-Logs**
empty

**Supervisor logs:**

> 20-02-06 06:08:17 INFO (MainThread) [hassio.host.info] Update local host information
20-02-06 06:08:17 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-02-06 06:08:17 INFO (MainThread) [hassio.host.services] Update service information
20-02-06 06:08:17 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-02-06 06:08:17 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-02-06 06:08:17 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-02-06 07:28:17 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-02-06 07:28:22 WARNING (MainThread) [hassio.updater] Can't fetch versions from https://version.home-assistant.io/stable.json: Cannot connect to host version.home-assistant.io:443 ssl:None [Try again]
20-02-06 08:14:57 INFO (MainThread) [hassio.host.info] Update local host information
20-02-06 08:14:57 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-02-06 08:14:57 INFO (MainThread) [hassio.host.services] Update service information
20-02-06 08:14:57 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-02-06 08:14:57 INFO (MainThread) [hassio.host.network] Update local network DNS information
20-02-06 08:14:57 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-02-06 08:28:17 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-02-06 08:28:17 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-02-06 08:28:22 ERROR (MainThread) [hassio.store.git] Can't update https://github.com/home-assistant/hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/home-assistant/hassio-addons/': Could not resolve host: github.com'.
20-02-06 08:28:22 ERROR (MainThread) [hassio.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/hassio-addons/repository/': Could not resolve host: github.com'.
20-02-06 08:28:22 INFO (MainThread) [hassio.store] Load add-ons from store: 63 all - 0 new - 0 remove

**Comment by pvizeli** [comment]
We should try to use our internal dns server on supervisor too fix custom DNS setup.

@kreisklasse try to set 8.8.8.8 on the network config of HassOS. Sounds like a DNS loop.

**Comment by kreisklasse** [comment]
> @kreisklasse try to set 8.8.8.8 on the network config of HassOS. Sounds like a DNS loop.

Ok, first i did not know how to do that,
but then i installed the SSH-Addon and ssh'd into the odroid. Hope that was the easy way.

`hassio dns info`
showed 

```
~ $ hassio dns info
host: 172.30.32.3
latest_version: "1"
locals:
- dns://192.168.1.42
- dns://fd00::3a10:d5ff:fe91:d336
servers: []
version: "1"
```
the locals DNS server-IPs is an old DNS-server which is not used by me anymore.

then:
`hassio dns options --servers dns://8.8.8.8 --servers dns://46.182.19.48`

```
~ $ hassio dns info
host: 172.30.32.3
latest_version: "1"
locals:
- dns://192.168.1.42
- dns://fd00::3a10:d5ff:fe91:d336
servers:
- dns://8.8.8.8
- dns://46.182.19.48
version: "1"
```

even after i rebooted the odroid, it still has the local dns server in the info and the failure message still apear.

How can i delete the local server ?

**Comment by JSchoeck** [comment]
I have the same problem, which keeps me from updating Supervisor to a more recent version (still using Pi Hole):
`$ hassio dns info
host: 172.30.32.3
latest_version: "1"
locals:
- dns://192.168.178.29
- dns://fd00::a8bf:2a23:2699:aebc
servers:
- dns://8.8.8.8
- dns://1.1.1.1
version: "1"
`

`ERROR (MainThread) [hassio.store.git] Can't update https://github.com/danielwelch/hassio-addons repo: Cmd('git') failed due to: exit code(128)`
