### ISSUE TITLE
The state/usage of network-manager component

### ISSUE THREAD

**Issue by andygrunwald** [home-assistant/supervisor#1488]
**Home Assistant release with the issue:**

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/Berlin
version | 0.105.1
virtualenv | false

**Operating environment (HassOS/Generic):**
Hass.io on an Intel Nuc computer - Self-installed - Debian buster

**Supervisor logs:**
```
20-02-06 16:37:03 INFO (MainThread) [__main__] Initialize Hass.io setup
20-02-06 16:37:03 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 199
20-02-06 16:37:03 INFO (SyncWorker_0) [hassio.docker.supervisor] Connect Supervisor to Hass.io Network
20-02-06 16:37:04 INFO (SyncWorker_0) [hassio.docker.interface] Cleanup images: ['homeassistant/amd64-hassio-supervisor:198']
20-02-06 16:37:04 INFO (MainThread) [__main__] Setup HassIO
20-02-06 16:37:04 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-02-06 16:37:04 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1

20-02-06 16:37:04 WARNING (MainThread) [hassio.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
20-02-06 16:37:04 WARNING (MainThread) [hassio.dbus.nmi_dns] No DnsManager support on the host. Local DNS functions have been disabled.**

20-02-06 16:37:04 INFO (MainThread) [hassio.host.info] Update local host information
20-02-06 16:37:04 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-02-06 16:37:04 INFO (MainThread) [hassio.host.services] Update service information
20-02-06 16:37:04 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-02-06 16:37:04 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-02-06 16:37:04 INFO (MainThread) [hassio.host.services] Reload local service hassio-apparmor.service
20-02-06 16:37:04 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-02-06 16:37:04 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 1
20-02-06 16:37:04 INFO (MainThread) [hassio.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-02-06 16:37:04 INFO (SyncWorker_4) [hassio.docker.interface] Restart homeassistant/amd64-hassio-dns
20-02-06 16:37:05 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/intel-nuc-homeassistant with version 0.105.0
20-02-06 16:37:05 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-02-06 16:37:05 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
20-02-06 16:37:05 INFO (MainThread) [hassio.store] Load add-ons from store: 62 all - 62 new - 0 remove
[...]
```

**Description of problem:**
My Problem was stated in https://github.com/hassio-addons/addon-pi-hole/issues/116 (%hassio_dns%` variable is not replaced in `/data/pihole/dns-servers.conf`).

There @sinclairpaul wrote
> What OS do you run?, I still believe you likely have something that is blocking connections on the docker network which will cause far more issues in the future.

We dug a bit deeper and the topic of `network-manager` came up. I don't have this component installed yet. This might create the log

```
20-02-06 16:37:04 WARNING (MainThread) [hassio.dbus.nmi_dns] No DnsManager support on the host. Local DNS functions have been disabled.
```

Based on this message, I found https://github.com/home-assistant/hassio-installer/issues/43, then a PR that it NetworkManager is not optional anymore (see https://github.com/home-assistant/hassio-installer/pull/36). To be honest, I don't really understand why NetworkManager is needed, what it is used for and if it is now required or optional.

The doc is saying (in a Warning field)
> Without the NetworkManager, you will be not able to control your host network setup over the UI.

The [README](https://github.com/home-assistant/hassio-installer) of the hassio-installer writes;
> Important: Don't only install NetworkManager, you need also use it on your system.

additionally marks the network-manager package as optional in the requirements.
Also from the _important_ note, it is not clear that I need to install it.

Sadly, the PR https://github.com/home-assistant/hassio-installer/pull/36 doesn't explain why this is needed.

Don't get me wrong, I am not complaining. I just try to understand the following questions:

- Why does hass.io need network-manager?
- Which explicit responsibility has this component towards hass.io? (or even more in detail: Which calls are executed from hass.io towards network manager)?
- Is it now optional or required? (different sources, say different things)
- Does the system work with (yes it does, but partially) or what implications does it have?

I am open to extending the documentation in several locations, but it is a bit hard for me to do this without the context.
It would be cool to provide the source code part which interacts with the network manager or issues that explain why this is needed, required or more context in this direction.

**Comment by pvizeli** [comment]
The home Assistant is a full-featured system. I work on a dbus integration for NetworkManager to control/exchange network information from host to supervisor into the Home Assistant ecosystem.

However, it's theoretical not limited to NetworkManager. If someone other will maintain and add support for other network management system like systemd is free to join into development.

The Network Manager is not a strict requirement but some functionality will be lost. Currently, the DNS is not fully working and instead, we can query the DNS server on the network directly we have a lot more layers between what end up with issues.
