### ISSUE TITLE
Resolving issues with DNS server on the same machine distributed over DHCP

### ISSUE THREAD

**Issue by niklaswa** [home-assistant/supervisor#1489]
**Home Assistant Core release with the issue:** > 104.3

**Home Assistant release with the issue:** >= 198

**Operating environment (HassOS/Generic):** Home Assistant (Hassio) Docker Install on Raspbian

**Supervisor logs:**
```
20-02-07 08:24:50 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-02-07 08:24:55 WARNING (MainThread) [hassio.updater] Can't fetch versions from https://version.home-assistant.io/stable.json: Cannot connect to host version.home-assistant.io:443 ssl:None [Try again]`
20-02-07 08:16:07 ERROR (MainThread) [hassio.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/hassio-addons/repository/': Could not resolve host: github.com'.
```

hassio_supervisor:
```
➜  ~ cat /etc/resolv.conf 
search local.hass.io
nameserver 172.30.32.3
```

hassio_dns:
```
bash-5.0# cat /etc/resolv.conf
search fritz.box
nameserver 127.0.0.11
options ndots:0
```

**Description of problem:**
- Home Assistant (Hassio) can't update the Home Assistant Core version, Home Assistant Addons
- Hosts can't be reached via DNS
- I've AdGuard as a Home Assistant Addon installed and distributed over my router's DHCP server. Everything else is working fine, Home Assistant Core itself and other devices in my network can use the AdGuards DNS server just fine

After removing the Raspberry's IP from the router's DHCP server (DNS server IP) and restarting the machine, it can resolve the urls again

**Comment by mihalski** [comment]
I concur with this. Have been having the same problem since trying to update to 103.0.

Name resolution works in home assistant core and home assistant OS but not in supervisor or dns.

**Comment by niklaswa** [comment]
So apparently you have to set an external DNS server manually in that situation as stated [here](https://github.com/hassio-addons/addon-adguard-home#installation).
I still don't get why, because I wanted to use AdGuard on the Pi itself too, but ok. 😄

**Comment by mihalski** [comment]
I don’t use pithole or adguard at the moment.

**Comment by pvizeli** [comment]
I need the output of `hassio dns log` and `hassio dns info`

> nameserver 172.30.32.3

Did you have modify the supervisor container?

**Comment by niklaswa** [comment]
So with setting the ipv4.dns via nmcli manually, it did work fine.

But I've reset it back to the default value (with `remove ipv4.dns`) and rebooted to get the logs in the non-working state:

```
➜  ~ docker info
Server:
 Containers: 28
  Running: 20
  Paused: 0
  Stopped: 8
 Images: 32
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
 Kernel Version: 4.19.93-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.814GiB

➜  ~ hassio dns info 
host: 172.30.32.3
latest_version: "1"
locals:
- dns://192.168.178.92
- dns://fd00::464e:6dff:feb4:2c3f
servers: []
version: "1"

➜  ~ hassio dns logs 
2020-02-08T17:35:36.614+01:00 [INFO] 172.30.32.1:43570 - 33218 "AAAA IN api.twitter.com. udp 33 false 512" NOERROR qr,rd,ra 119 0.020536815s
2020-02-08T17:35:38.602+01:00 [INFO] 172.30.33.8:56361 - 3964 "A IN github.com. udp 28 false 512" NOERROR qr,rd,ra 54 0.019801791s
2020-02-08T17:35:38.970+01:00 [INFO] 172.30.33.8:57992 - 8813 "A IN avatars3.githubusercontent.com. udp 48 false 512" NOERROR qr,rd,ra 261 0.020746052s
2020-02-08T17:35:42.591+01:00 [INFO] 172.30.32.1:48594 - 55011 "AAAA IN hassio.local.hass.io. udp 38 false 512" NOERROR qr,aa,rd 38 0.000227848s
2020-02-08T17:35:42.592+01:00 [INFO] 172.30.32.1:37286 - 41066 "A IN hassio.local.hass.io. udp 38 false 512" NOERROR qr,aa,rd 74 0.000197589s
```

**Comment by ENT108** [comment]
Check your system routing maybe.

**Comment by pdubost** [comment]
Are you using an Eero router? If so, then disable Security+.
That way the local detected DNS server will be the actual server (e.g. 1.1.1.1), not the 192.168.4.1 gateway.

**Comment by pvizeli** [comment]
We "fix" the issue with Eero. They response wrong to the AAAA query (maybe someone needs to tell that company how IPv6 works with IPv4, but in that case, they should not produce network equipment. Our internal DNS solution bypass eero in that case to provide a working system.
