### ISSUE TITLE
hassio dns resolves via outside servers

### ISSUE THREAD

**Issue by nickprotop** [home-assistant/supervisor#1499]
Home Assistant 0.105.2
Raspbian/hassio (on pi 3b+)
Supervisor: 200

Hello, the hassio dns docker image resolves names via outside servers regardless my settings (i have already set it up with hassio dns options --servers. This is a problem when you have a split dns (like me) and you want the addons to refer to your installation by name rather than ip.

**Comment by frenck** [comment]
Yes, that is correct.
However, you should not be using "external" hostnames for "internal" communications.

All add-ons can be reached via: `<repo slug>-<add-on slug>` as a hostname format. For example: `core-mariadb` or `core-mosquitto`.

This way, communication never leaves your device even, since it leverages an internal network for communication.

**Comment by nickprotop** [comment]
Thanks for your answer.

So, it's a feature, not an issue :) But, i have to say that using "external" hostnames for "internal" traffic, maybe isn't the best thing to do, but there are some "edge" situtations where it is very convenience.

If I add the "external" hostname in the hosts file in /usr/share/hassio/dns works as I want. But this file is cleaned after every reboot. Is there any way to "bypass" it or inject manual entries into this file? But without modifying the addon itself? Maybe, can we have this behaviour as a feature?

**Comment by pvizeli** [comment]
Sure, feel free to implement this on supervisor with API and backend 👍

**Comment by nickprotop** [comment]
Ok, but my python experience is a little below zero. Anyway, review the code and think that can do it. I only have a couple of questions. First, is it a good idea a conf file, like dns.conf, called hosts.conf, containing the manual host entries to be added when the dns object is initialized? Also, is it better to have a configuration into hassio gui?
