### ISSUE TITLE
Unable to update to supervisor / 404 Client Error: Not Found

### ISSUE THREAD

**Issue by cubilon** [home-assistant/supervisor#1506]
## The problem
Unable to update Supervisor to version 200

## Environment
HASSIO

- Home Assistant release with the issue: 0.105.x
- Last working Home Assistant release (if known): n.a.
- Operating environment (Hass.io/Docker/Windows/etc.): HASSIO

## Problem-relevant `configuration.yaml`
n.a.

## Traceback/Error logs
from logs:

`Can't install homeassistant/armv7-hassio-supervisor:200 -> 404 Client Error: Not Found ("no such image: homeassistant/armv7-hassio-supervisor:200: No such image: homeassistant/armv7-hassio-supervisor:200").`

**Comment by frenck** [comment]
This is going to sound weird (and we should improve on this), however, a 404 usually means there is not enough disk space available to complete the operation.

**Comment by cubilon** [comment]
can't be. it'a near-fresh install on a 16gb microSD.

**Comment by SuperSpe** [comment]
same problem here. cannot update. hassio updates normally.

df -h shows:
```
Filesystem                Size      Used Available Use% Mounted on
overlay                   6.6G      2.5G      3.7G  40% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                   462.0M         0    462.0M   0% /sys/fs/cgroup
shm                      64.0M     64.0K     63.9M   0% /dev/shm
/dev/root                93.8M     93.8M         0 100% /sbin/docker-init
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /config
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /share
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /addons
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /backup
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /data
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /ssl
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /etc/asound.conf
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /etc/hostname
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /etc/resolv.conf
/dev/mmcblk0p8            6.6G      2.5G      3.7G  40% /etc/hosts
tmpfs                   462.0M    608.0K    461.4M   0% /run/dbus
tmpfs                   462.0M         0    462.0M   0% /proc/asound
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/latency_stats
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                   462.0M         0    462.0M   0% /sys/firmware

```

**Comment by pvizeli** [comment]
> same problem here. cannot update. hassio updates normally.

You can't update but updates going normally? Please describe this a bit more.

**Comment by KC-inDomus** [comment]
When you update to a new Home Assistant Core versione everything goes fine; when you try to update supervisor from 199 to 200 you always get 

 `ERROR (SyncWorker_17) [hassio.docker.interface] Can't install homeassistant/armv7-hassio-supervisor:200 -> 404 Client Error: Not Found ("no suc`

**Comment by pvizeli** [comment]
Please try to update to 201

**Comment by KC-inDomus** [comment]
tried, same thing.

`20-02-18 15:30:48 ERROR (SyncWorker_3) [hassio.docker.interface] Can't install homeassistant/armv7-hassio-supervisor:201 -> 404 Client Error: Not Found ("no such image: homeassistant/armv7-hassio-supervisor:201: No such image: homeassistant/armv7-hassio-supervisor:201").
20-02-18 15:30:48 ERROR (MainThread) [hassio.supervisor] Update of Hass.io fails!`

**Comment by pvizeli** [comment]
okay, I think that is a region problem on your country with local docker hub image storage. In which country do you life?

**Comment by SuperSpe** [comment]
same with the 201. hassio and ha updates normally.
I live in italy.

**Comment by pvizeli** [comment]
@SuperSpe I don't understand, if you have the same error message as the other people, Hassio aka Supervisor did not update but you said again he does update normally?

**Comment by pvizeli** [comment]
Ah, I have an idea. Go into terminal and enter:
`hassio su repair`

Fix that the issue?

**Comment by SuperSpe** [comment]
> @SuperSpe I don't understand, if you have the same error message as the other people, Hassio aka Supervisor did not update but you said again he does update normally? Can you show me the log so that I can understand what you means please.

with hassio I meant HAOS, damn that name convention. So Home Assistant can updates, OS  updates,  Supervisor is the only thing that does not update.
Imma trying the repair solution

**Comment by SuperSpe** [comment]
> Ah, I have an idea. Go into terminal and enter:
> `ha su repair`
> 
> Fix that the issue?

You mean 
_hassio_ su repair

**Comment by frenck** [comment]
that is the same command (old version, if you update your CLI's/Add-ons it will be as specified by pvizeli)

**Comment by SuperSpe** [comment]
I am on the last version of all packages excluding supervisor, and the only command that works is hassio su repair, but this not solve the problem.

**Comment by stevseag** [comment]
I have the same problem from Belgium,... if my support will be helpfull,...

**Comment by jeepotvin** [comment]
I was having the same issue. Just stumble across a post on the [hassio community](https://community.home-assistant.io/t/cannot-connect-to-host-version-home-assistant-io-443/170436/3) and apparently someone posted a solution about changing a settings regarding the Pi-Hole plugin (for those of you who may have it, like I did).

And it worked!

**Comment by HerkDriver** [comment]
I have same problem with 201 also.

20-02-22 09:55:18 ERROR (SyncWorker_11) [hassio.docker.interface] Can't install homeassistant/armv7-hassio-supervisor:201 -> 404 Client Error: Not Found ("no such image: homeassistant/armv7-hassio-supervisor:201: No such image: homeassistant/armv7-hassio-supervisor:201").

I do not have the Pi-Hole plugin. Pi is connected via Ethernet.  All other updates are ok.

**Comment by SuperSpe** [comment]
I have pihole instaled on my network (on another pi). Try to disable, no success. I also change the dns of the hass.io to 8.8.8.8, no result at all.
always 404

**Comment by Ludestru** [comment]
I was stuck with Home Assistant 0.105.x and Hassio 200.
The supervisor was no longer offering any update.

I tried : `hassio supervisor update --version=201`.

He started processing, then I lost the connection to the console and the supervisor.
When I recovered the connection 1-2 minutes later, the problem was fixed and I was able to update hassio and home assistant normally.

**Comment by SuperSpe** [comment]
tried that too. 
nein!

**Comment by stevseag** [comment]
Same problem with this solution,... :'(

**Comment by msmith1114** [comment]
Same issue here, brand new install on a 32gb card. I am unable to update from 201 to 208 supervisor. Have tried every suggestion above with no luck.

**Comment by HunterDG** [comment]
If this is indeed a disk space issue, perhaps a more descriptive error message (both on the supervisor updater GUI and logs) would be useful?  404 seems to indicate dockerhub connectivity issues, may lead to false concerns about pi-hole/adguard/dns configuration (see previous comments in this issue and elsewhere)

Also perhaps a method for recovering some space used by the [history](https://www.home-assistant.io/integrations/history/)/[recorder](https://www.home-assistant.io/integrations/recorder/) integrations after-the-fact?

Maybe even include [systemmonitor](https://www.home-assistant.io/integrations/systemmonitor)/[DB size sensor](https://github.com/robmarkcole/HASS-filesize-sensor) in `default_config`?

<img width="1504" alt="Screen Shot 2020-03-20 at 6 38 08 PM" src="https://user-images.githubusercontent.com/38483996/77215501-035c0b00-6ada-11ea-99f4-485f0b49420a.png">

**Comment by frenck** [comment]
> If this is indeed a disk space issue, perhaps a more descriptive error message (both on the supervisor updater GUI and logs) would be useful? 404 seems to indicate dockerhub connectivity issues

We agree, there is an issue open for that, however, it is the documented behavior by Docker as well (which is throwing this error message).

**Comment by magostinelli** [comment]
Try the download manually the image:
docker pull homeassistant/raspberrypi4-homeassistant:0.107.7

For example, this give me the error: 
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/cf7d66980d33c962fd2f859133d097897219d3e71ec4788e2c3a17f5155242d1/merged: too many levels of symbolic links

**Comment by dennisgranasen** [comment]
> Try the download manually the image:
> docker pull homeassistant/raspberrypi4-homeassistant:0.107.7
> 
> For example, this give me the error:
> failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/cf7d66980d33c962fd2f859133d097897219d3e71ec4788e2c3a17f5155242d1/merged: too many levels of symbolic links

Same issue, same results. Running homeassistant on a fresh rpi3 using "manual install" method (https://www.home-assistant.io/docs/installation/raspberry-pi/). Doesn't work with any version after 209.

**Comment by magostinelli** [comment]
I confirm that I did the same manual install as you.

If you try do pull the last dev image, I don't have this kind of error, very strange.

**Comment by younesetre** [comment]
same probleme Unable to update to supervisor / 404 Client Error from 214 to 217

**Comment by jonare77** [comment]
I also have this problem. Initial install of supervisor was 214 not able to upgrade to any newer version.

`20-04-25 07:47:21 INFO (SyncWorker_14) [supervisor.docker.interface] Pull image homeassistant/armv7-hassio-supervisor tag 219.
20-04-25 07:47:54 ERROR (SyncWorker_14) [supervisor.docker.interface] Can't install homeassistant/armv7-hassio-supervisor:219 -> 404 Client Error: Not Found ("no such image: homeassistant/armv7-hassio-supervisor:219: No such image: homeassistant/armv7-hassio-supervisor:219").
20-04-25 07:47:54 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor fails!
20-04-25 07:47:54 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Tasks._update_supervisor() done, defined at /usr/src/supervisor/supervisor/tasks.py:135> exception=SupervisorUpdateError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/tasks.py", line 146, in _update_supervisor
    await self.sys_supervisor.update()
  File "/usr/src/supervisor/supervisor/supervisor.py", line 121, in update
    raise SupervisorUpdateError() from None
supervisor.exceptions.SupervisorUpdateError`

My geolocation is Norway.

**Comment by larcher** [comment]
I found https://github.com/synesthesiam/rhasspy/issues/176 -- different project, but similar issue with Docker on RPi4.  Final comment there says the problem goes away with the latest docker (19.03.7, build 7141c19).  Maybe some problem with certain Docker versions on Raspbery Pi ? 

`docker version` on my fresh install of Home Assistant OS (version 3.13, supervisor 219) says it has Docker 19.03.5 .. how do I update to a newer version? 😀

**Comment by pvizeli** [comment]
Not all people can write dockerfile. Some use for every command a new layer which end up in a image with 40 or 50 layers. That is too much for a small system. Synesthesiam is someone they do that. The solution would be to not use add-ons which do many layers because the author did not understand docker.

**Comment by OmgImAlexis** [comment]
Bad bot.

**Comment by rursache** [comment]
still having this issue and i'm on 242. i cannot upgrade to 243 or 244. i have enough space left: https://github.com/home-assistant/supervisor/issues/2066

**Comment by lancelon** [comment]
I seem to have this issue....tried (and failed) to upgrade, got the 404 error (had loads of space on the SD card) and now the installation [is completely borked](https://community.home-assistant.io/t/rebooted-host-now-ha-wont-boot/278010/1)

**Comment by rursache** [comment]
> I seem to have this issue....tried (and failed) to upgrade, got the 404 error (had loads of space on the SD card) and now the installation [is completely borked](https://community.home-assistant.io/t/rebooted-host-now-ha-wont-boot/278010/1)

try https://github.com/home-assistant/supervisor/issues/2066#issuecomment-746050553

**Comment by lancelon** [comment]
Thank you for the tip. I tried @dangel666's tip. Steps 1 & 2 work fine but then on step 3 it says `error: version 2021.01.7 is already in use.`
Then if I do a reboot I get some random error. 

At this stage is my best bet just to reimage an SD card and try to restore a snapshot from there? I'm concerned there's something somehow in one of my snapshots that will corrupt even the fresh install...but I don't know why it would, apart from not updating to the latest version, my setup was working fine - day after day.

**Comment by ron-k** [comment]
> This is going to sound weird (and we should improve on this), however, a 404 usually means there is not enough disk space available to complete the operation.

You just ended my hours-long investigation.
