### ISSUE TITLE
Upgrade to 0.105.4: Supervisor does not run in Privileged mode.

### ISSUE THREAD

**Issue by Tamadite** [home-assistant/supervisor#1514]
## The problem
After upgrade to 0.105.4 I get error message: `ERROR (MainThread) [hassio.supervisor] Supervisor does not run in Privileged mode. Hassio runs with limited functionality!`
A consequence of this, I guess, is that I cannot get zigbee2mqtt to add devices to the db.

## Environment
HassOS 3.10
Supervisor Version 200
Home Assistant 0.105.4

- Home Assistant release with the issue: not sure because I have a release gap. I experience this problem first now. No problems like this before. This upgrade I did required HassOS upgrade and HA upgrade.
- Last working Home Assistant release (if known): don't really know.
- Operating environment (Hass.io/Docker/Windows/etc.): Hass.io
- Integration causing this issue: not sure but a possible consequence of this limited functionality is that despite having _zigbee2mqtt_ to successfully pair devices, devices do not get added to the db.
- Link to integration documentation on our website: 

## Traceback/Error logs
starting version 3.2.9
18-12-21 18:54:04 INFO (MainThread) [__main__] Initialize Hass.io setup
18-12-21 18:54:04 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/armhf-hassio-supervisor with version 200
18-12-21 18:54:04 ERROR (MainThread) [hassio.supervisor] Supervisor does not run in Privileged mode. Hassio runs with limited functionality!
18-12-21 18:54:04 INFO (MainThread) [__main__] Setup HassIO
18-12-21 18:54:05 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1

## Additional information
When I look look at file hostconfig.json I find: `"Privileged":false`

**Comment by frenck** [comment]
So at first glance, I think you are running Home Assistant Supervised (previously Hass.io on a custom OS, e.g., Ubuntu/Debian).

If that is the case, you need to run the installer again to address this:

<home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host>

**Comment by Tamadite** [comment]
This is what I have:
`# cat os-release 
NAME=HassOS
VERSION="3.10 (RaspberryPi 3)"
ID=hassos
VERSION_ID=3.10
PRETTY_NAME="HassOS 3.10"
CPE_NAME=cpe:2.3:o:home_assistant:hassos:3.10:*:production:*:*:*:rpi3:*
HOME_URL=https://hass.io/
VARIANT="HassOS RaspberryPi 3"
VARIANT_ID=rpi3`
Would it help executing `ha core update --version=0.105.4` or do I need to go down to the HassOS and re-install it?

**Comment by Tamadite** [comment]
I have unsuccessfully tried changing the privilege flag on file _hostcconfig.json_ to "true" but unfortunately I need to bring down the docker; doing so it takes the system down, even if I do it directly from the console (no ssh).

**Comment by Tamadite** [comment]
The problem got solved with the upgrade to HA 0.105.5 and HassOS 3.11
