### ISSUE TITLE
Enhancement: Upload snapshot for restoring or migrating

### ISSUE THREAD

**Issue by borpin** [home-assistant/supervisor#1515]
**Home Assistant release with the issue:**

All

**Operating environment (HassOS/Generic):**

Any

**Supervisor logs:**

NA

**Description of problem:**

When trying to migrate a Home Assistant (HassIO generic) instance to a new server, it would be really useful to be able to upload a snapshot to the new instance from the Web UI.

This would also help where a user wants to revert back to a previous snapshot stored remotely.

Even better would be an option to upload a snapshot from the initial 'create a user' screen.

The workaround is to create a snapshot (so the backup folder is created) temporarily install the samba share add-on and upload to the backup folder, then install that.

**Comment by pvizeli** [comment]
> This is for bugs only. Feature and enhancement requests should go in our community forum: https://community.home-assistant.io/c/feature-requests

If you want implement this and need a guideline, let the issue open and we can start a discusion how do you can implement this over all layers. Otherwise please close the issue

**Comment by borpin** [comment]
https://community.home-assistant.io/t/upload-snapshot-for-restoring-or-migrating/172801
