### ISSUE TITLE
supervisor doesn't restart after update to 205. 

### ISSUE THREAD

**Issue by vajonam** [home-assistant/supervisor#1550]
**Home Assistant release with the issue: 0.106.2**

**Operating environment (HassOS/Generic): Generic/docker **

**Supervisor logs:**

```
execlineb: fatal: unable to exec /bin/importas: Permission denied
```

**Description of problem:**

The new 205 container wont restart the only thing in docker logs hassio_supervisor logs is that above line. 

it seems to quick as soon as its launched. 

```
docker ps -a 
```

```
6075e1001ceb        homeassistant/amd64-hassio-supervisor            "/init"                  6 seconds ago       Exited (126) 2 seconds ago                                                                                      hassio_supervisor
```

Only way to recover is the change the updater.json back to stable and 201 and restart the hassio service

```
sudo systemctl stop hassio-supervisor.service                 

{
  "channel": "stable",
  "hassio": "201",
  "homeassistant": "0.106.2",
  "dns": "1"
}%

sudo systemctl start hassio-supervisor.service                 
```

**Comment by pvizeli** [comment]
Look like an old supervisor system script. Please run the installer again, he just update the systemd files

**Comment by vajonam** [comment]
> Look like an old supervisor system script. Please run the installer again, he just update the systemd files

Thanks manually updated the systemd files.

**Comment by Megachip** [comment]
Happens after Autoupdate on hassos... there is no  installer :/

**Comment by Megachip** [comment]
> Happens after Autoupdate on hassos... there is no installer :/

Seems supervisor updated from.162 to 163 :/

**Comment by Megachip** [comment]
How to solve this issue on hassio?
