### ISSUE TITLE
Supervisor 206 breaks xiaomi integration

### ISSUE THREAD

**Issue by jodur** [home-assistant/supervisor#1553]
**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**

After upgrading to supervisor version 206 the xiaomi integration is broken. This is already confirmerd by several users!

[https://community.home-assistant.io/t/xiaomi-sensors-stopped-working-supervisor-206/175735](https://community.home-assistant.io/t/xiaomi-sensors-stopped-working-supervisor-206/175735)

[https://community.home-assistant.io/t/xiaomi-sensor-in-106-02/175752](https://community.home-assistant.io/t/xiaomi-sensor-in-106-02/175752)

**Comment by klaasnicolaas** [comment]
Is Supervisor still the problem? On the forum I read several reactions that it was HACS 😉

**Comment by jodur** [comment]
Supervisor is not the problem. Hacs was the problem
