### ISSUE TITLE
Supervisor not starting after update to 207

### ISSUE THREAD

**Issue by Alexxtheonly** [home-assistant/supervisor#1556]
**Operating environment (HassOS/Generic):**

Ubuntu 18.04  Supervisor 207

**Supervisor logs:**

Mar 03 15:30:58 hassio hassio-supervisor[7786]:     raise EnvironmentError('Could not create udev monitor')
Mar 03 15:30:58 hassio hassio-supervisor[7786]: OSError: Could not create udev monitor
Mar 03 15:30:58 hassio hassio-supervisor[7786]: 20-03-03 15:30:58 ERROR (MainThread) [asyncio] Unclosed client session
Mar 03 15:30:58 hassio hassio-supervisor[7786]: client_session: <aiohttp.client.ClientSession object at 0x7f3e87052bd0>
Mar 03 15:30:58 hassio hassio-supervisor[7786]: 20-03-03 15:30:58 ERROR (MainThread) [asyncio] Unclosed client session
Mar 03 15:30:58 hassio hassio-supervisor[7786]: client_session: <aiohttp.client.ClientSession object at 0x7f3e86e16150>
Mar 03 15:30:58 hassio hassio-supervisor[7786]: [cont-finish.d] executing container finish scripts...
Mar 03 15:30:58 hassio hassio-supervisor[7786]: [cont-finish.d] done.
Mar 03 15:30:58 hassio hassio-supervisor[7786]: [s6-finish] waiting for services.
Mar 03 15:30:58 hassio hassio-supervisor[7786]: [s6-finish] sending all processes the TERM signal.

**Description of problem:**
Supervisor doesn't start, see log above.

Just updated the supervisor to 207 via frontend, now it logs the `Could not create udev monitor` error

**Comment by jsiemek** [comment]
Hi,

As i saw your post, I pressed update to 207 with shaking hand .
Works on my side:
![SU 207](https://user-images.githubusercontent.com/36767404/75794173-b6093b00-5d70-11ea-90ec-6a997a254044.png)

**Comment by bratanon** [comment]
Same issue here. Running the generic installation on:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**Comment by Alexxtheonly** [comment]
I don't know what caused it, but after 
`docker pull homeassistant/amd64-hassio-supervisor:202`
`docker tag homeassistant/amd64-hassio-supervisor:202 homeassistant/amd64-hassio-supervisor:latest`
`systemctl stop hassio-supervisor.service`
`systemctl start hassio-supervisor.service`

It work's again. it even displays version 207 in the logs. So i guess the pull/tag did nothing, however stopping and starting of hassio-supervisor.service did not work before. ¯\\_(ツ)_/¯

**Comment by bratanon** [comment]
@Alexxtheonly: Nope, didn't work, same issue. :(

**Comment by Alexxtheonly** [comment]
I also started `systemctl start systemd-resolved` again in my journey of trial and error. Initially this was disabled because of pi-hole. If this also applies to you @bratanon, it may be worth trying.

**Comment by jkabradley** [comment]
Also having the same issue on Ubuntu 18.04 LTS, and tried the 4 commands above.  Also did not work for me.

**Comment by Kendobendo** [comment]
Same here. On Ubuntu 18.04.4 LTS.

**Comment by 1iveowl** [comment]
Same here on Ubuntu 19.10.

**Comment by kernehed** [comment]
Same here, I'm not even able to access hassio. 
I can only access the host. 

Host: Ubuntu 18.04,02 LTS.
Hassio: 0.106.4

**Comment by almostserious** [comment]
Same Problem here on Ubuntu as well. 18.04.3 LTS / 106.4

**Comment by schmurtzm** [comment]
Same here, resolved thanks to @Alexxtheonly  (Thank a lot, your commands save my afternoon ;)  )
https://github.com/home-assistant/supervisor/issues/1556#issuecomment-594034569

**Comment by bratanon** [comment]
So, for everyone on 18.04, this is how I manage to get it to work with help from @ludeeus .

You need to run the install scritp again.
`# curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s`

https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host

**Comment by Kendobendo** [comment]
> So, for everyone on 18.04, this is how I manage to get it to work with help from @ludeeus .
> 
> You need to run the install scritp again.
> `# curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s`
> 
> https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host

@ubuntu:~$ sudo curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s
ModemManager.service enabled
[Warning] ModemManager service is enabled. This might cause issue when using serial devices.
bash: line 133: /etc/hassio.json: Permission denied

@ubuntu:~$ sudo systemctl disable ModemManager.service
Removed /etc/systemd/system/multi-user.target.wants/ModemManager.service.
Removed /etc/systemd/system/dbus-org.freedesktop.ModemManager1.service.

@ubuntu:~$ sudo curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s
bash: line 133: /etc/hassio.json: Permission denied

Not sure what to do about that. It doesn't seem to work?

**Comment by ludeeus** [comment]
Go through all the steps for the (re-)installation <https://www.home-assistant.io/hassio/installation/#preparation>

Do not skip the `sudo -i`, or `systemctl disable ModemManager`

**Comment by 9zenith** [comment]
> So, for everyone on 18.04, this is how I manage to get it to work with help from @ludeeus .
> 
> You need to run the install scritp again.
> `# curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s`
> 
> https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host

This works for me!

**Comment by almostserious** [comment]
> Go through all the steps for the (re-)installation https://www.home-assistant.io/hassio/installation/#preparation
> 
> Do not skip the `sudo -i`, or `systemctl disable ModemManager`

Just did that, after successfully reinstalling:

> [Info] Install supervisor Docker container
> [Info] Install supervisor startup scripts
> [Info] Install AppArmor scripts
> [Info] Run Hass.io

The supervisor still does not start. It is active for maybe 2-3 seconds

**Comment by bratanon** [comment]
What does the logs say @almostserious ?

**Comment by Kendobendo** [comment]
`root@ubuntu:~# docker ps
CONTAINER ID        IMAGE                                   COMMAND             CREATED             STATUS              PORTS               NAMES
c4133bf73226        homeassistant/amd64-hassio-supervisor   "/init"             36 minutes ago      Up 2 seconds                            hassio_supervisor
root@ubuntu:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@ubuntu:~#
`

It seems to start for 2-3 seconds and then shuts down again. It cant start properly. Any suggestions would be helpful :)

**Comment by almostserious** [comment]
> What does the logs say @almostserious ?

Can you please tell me how to get to the log?

**Comment by ludeeus** [comment]
`docker logs -f hassio_supervisor`

**Comment by almostserious** [comment]
> `docker logs hassio_supervisor`

Thanks. Then i get the following error:

`OSError: Could not create udev monitor
`
```
 File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 41, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 61, in initialize_coresys
    coresys.hwmonitor = HwMonitor(coresys)
  File "/usr/src/supervisor/supervisor/hwmon.py", line 22, in __init__
    self.monitor = pyudev.Monitor.from_netlink(self.context)
  File "/usr/local/lib/python3.7/site-packages/pyudev/monitor.py", line 121, in from_netlink
    raise EnvironmentError('Could not create udev monitor')
OSError: Could not create udev monitor
20-03-03 17:24:24 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd7772d9b90>
20-03-03 17:24:24 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd777303e10>
[cont-finish.d] executing container finish scripts...

```

**Comment by Kendobendo** [comment]
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing...
starting version 3.2.9
[17:27:48] INFO: Update udev informations
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
20-03-03 17:27:48 INFO (MainThread) [__main__] Initialize Supervisor setup
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 41, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 61, in initialize_coresys
    coresys.hwmonitor = HwMonitor(coresys)
  File "/usr/src/supervisor/supervisor/hwmon.py", line 22, in __init__
    self.monitor = pyudev.Monitor.from_netlink(self.context)
  File "/usr/local/lib/python3.7/site-packages/pyudev/monitor.py", line 121, in from_netlink
    raise EnvironmentError('Could not create udev monitor')
OSError: Could not create udev monitor
**20-03-03 17:27:48 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4efb547b10>
20-03-03 17:27:48 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4efb572f90>**
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

My logs.

**Comment by Kendobendo** [comment]
@almostserious seems we got the exact same problem :)

**Comment by btuysser** [comment]
same here after following install instructions

**Comment by almostserious** [comment]
Ah... seems to be a problem because before that i already tagged release 206 as latest.
Doing this:

> docker pull homeassistant/amd64-hassio-supervisor:latest

> docker tag homeassistant/amd64-hassio-supervisor:latest homeassistant/amd64-hassio-supervisor:latest

and then doing again:

> # curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s

seems to have fixed it

**Comment by frenck** [comment]
This is probably caused by older startup scripts, which causes the Supervisor to have incorrect permissions. The permissions changed over a half year ago, your instance would have thrown warnings for that same time as well.

Running the install instructions from our website again will fix this issue.

<https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host>

Running the installer again, preserves data.

Generally the above-listed installer command "should" be enough. But as a general good practice, running the full set of instructions might uncover some "older" missing things.

**Comment by scstraus** [comment]
Any advice for those of us on Ubuntu 18.04 who have not yet made the upgrade to avoid or predict if we will have this issue? I don't see any glaring warnings in the log. Anyone know what message we should look for and in what log? Home assistant or supervisor?

**Comment by Kendobendo** [comment]
I got mine finally working too. I had to fix it slightly differently.



First:
> sudo -i
docker pull homeassistant/amd64-hassio-supervisor:latest

When I then tried:
> docker tag homeassistant/amd64-hassio-supervisor:latest homeassistant/amd64-hassio-supervisor:latest

I got this error:
> Error response from daemon: No such image: homeassistant/amd64-hassio-supervisor:latest

So instead:
docker tag homeassistant/amd64-hassio-supervisor:**207** homeassistant/amd64-hassio-supervisor:latest

And then, it worked:
> docker tag homeassistant/amd64-hassio-supervisor:latest homeassistant/amd64-hassio-supervisor:latest

And finally:

> systemctl disable ModemManager.service
> curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s
> 

For some reason latest / latest didn't work for me. I have to admit I'm not sure about most of this. So this is just my experience.

**Comment by Dawnes** [comment]
> I got mine finally working too. I had to fix it slightly differently.

Thank you so much. This worked for me as well. My installation was dead but now it's running again.

**Comment by slipx06** [comment]
This is not working. Followed the suggested steps and still getting this error

20-03-03 19:27:07 INFO (MainThread) [__main__] Initialize Supervisor setup
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 41, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 61, in initialize_coresys
    coresys.hwmonitor = HwMonitor(coresys)
  File "/usr/src/supervisor/supervisor/hwmon.py", line 22, in __init__
    self.monitor = pyudev.Monitor.from_netlink(self.context)
  File "/usr/local/lib/python3.7/site-packages/pyudev/monitor.py", line 121, in from_netlink
    raise EnvironmentError('Could not create udev monitor')
OSError: Could not create udev monitor
20-03-03 19:27:08 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fef07579690>
20-03-03 19:27:08 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fef07597f90>
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by slipx06** [comment]
> I don't know what caused it, but after
> `docker pull homeassistant/amd64-hassio-supervisor:202`
> `docker tag homeassistant/amd64-hassio-supervisor:202 homeassistant/amd64-hassio-supervisor:latest`
> `systemctl stop hassio-supervisor.service`
> `systemctl start hassio-supervisor.service`
> 
> It work's again. it even displays version 207 in the logs. So i guess the pull/tag did nothing, however stopping and starting of hassio-supervisor.service did not work before. ¯\_(ツ)_/¯
> 
> @bratanon can you try the four commands and see if it solves the issue for you?

This worked for me

**Comment by frenck** [comment]
Yes, but now your versioning is out of sync, you are running 202, but the system thinks you are running 207.

**Comment by jharder01** [comment]
@frenck As you recommended I ran through all installation steps again, however it didn't resolve the issue. I used the Docker method as a work-around (it's running fine now), however I understand this is just a band-aid. What would be the best long-term solution? You mentioned permissions issues previously, is it possible to manually fix these permissions? I took a disk image prior to the work-around and can roll back to the broken state at any point.

**Comment by slipx06** [comment]
> Yes, but now your versioning is out of sync, you are running 202, but the system thinks you are running 207.

Any ideas on how to fix this then? Running the installation script did not work

**Comment by mredone** [comment]
Same problem here!!!
Nothing help.

**Comment by cmlittle** [comment]
> > So, for everyone on 18.04, this is how I manage to get it to work with help from @ludeeus .
> > You need to run the install scritp again.
> > `# curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s`
> > https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host
> 
> @ubuntu:~$ sudo curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s
> ModemManager.service enabled
> [Warning] ModemManager service is enabled. This might cause issue when using serial devices.
> bash: line 133: /etc/hassio.json: Permission denied
> 
> @ubuntu:~$ sudo systemctl disable ModemManager.service
> Removed /etc/systemd/system/multi-user.target.wants/ModemManager.service.
> Removed /etc/systemd/system/dbus-org.freedesktop.ModemManager1.service.
> 
> @ubuntu:~$ sudo curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s
> bash: line 133: /etc/hassio.json: Permission denied
> 
> Not sure what to do about that. It doesn't seem to work?

I ran into the same problem. This is a permission issue. Try switching to root user (su root) and rerun `curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s`

**Comment by cmlittle** [comment]
> Ah... seems to be a problem because before that i already tagged release 206 as latest.
> Doing this:
> 
> > docker pull homeassistant/amd64-hassio-supervisor:latest
> 
> > docker tag homeassistant/amd64-hassio-supervisor:latest homeassistant/amd64-hassio-supervisor:latest
> 
> and then doing again:
> 
> > # curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s
> 
> seems to have fixed it

This solved my issue, but now I'm concerned about being "out of sync" with the Supervisor versions. Obviously I'd rather have my system up and running and worry about a fix later, but hopefully someone can suggest a long term fix to resolve this.

> > Yes, but now your versioning is out of sync, you are running 202, but the system thinks you are running 207.
> 
> I think it must have updated itself when I restarted the supervisor service
> 
> ```
> docker pull homeassistant/amd64-hassio-supervisor:207
> 207: Pulling from homeassistant/amd64-hassio-supervisor
> Digest: sha256:1dfaedd7c36f935b7dc184812fae1649bb1124a0bfa9e3edf9ca411bfa5804b7
> Status: Image is up to date for homeassistant/amd64-hassio-supervisor:207
> docker.io/homeassistant/amd64-hassio-supervisor:207
> ```
> 
> ```
> REPOSITORY                               TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
> homeassistant/amd64-hassio-supervisor    207                 sha256:1dfaedd7c36f935b7dc184812fae1649bb1124a0bfa9e3edf9ca411bfa5804b7   ff6b7ba44d13        35 hours ago        277MB
> homeassistant/amd64-hassio-supervisor    latest              sha256:1dfaedd7c36f935b7dc184812fae1649bb1124a0bfa9e3edf9ca411bfa5804b7   ff6b7ba44d13        35 hours ago        277MB
> ```
> 
> ![image](https://user-images.githubusercontent.com/7227275/75823612-bb837700-5daa-11ea-8c38-bb20caa52a1f.png)

I followed your instructions (thank you by the way) and I'm also showing that I'm running Supervisor 207, so hopefully we haven't tricked HA to thinking we're on 207 and not 202.  Regardless, I'm happy everything is working properly for now.

**Comment by JonnyKabisa** [comment]
I had to manually remove all the homeassistant containers from docker before running the install script. After that, it worked like a charm :)

**Comment by maxi1134** [comment]
I tried removing all of the Docker containers and running the script but Hassio_supervisor keep spitting that error? I am kinda freaking out as my whole house is now unusable due to Home-assistant not booting.

**Comment by cogneato** [comment]
@maxi1134 not only the script, but all the installation steps starting at `sudo -i` (important)
<https://www.home-assistant.io/hassio/installation/#preparation>
Then a reboot of the whole thing, most likely.

**Comment by tyfoon** [comment]
I'm also slightly panicking... I've done this years ago on an Intel NUC and never looked back but seem to have the same error/issue.

In all honesty I have no idea what I'm doing just following steps 1:1.

Just logging into my Ubuntu 18.04 NUC and running `sudo curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | sudo bash -s` did not do the trick. (I had to add sudo 2x has otherwise I would get permission errors) got:

[Info] Install supervisor Docker container
[Info] Install supervisor startup scripts
[Info] Install AppArmor scripts
[Info] Run Hass.io

But I did not come online.

What is now the best way to proceed? Somebody posted stopping or deleting some containters first before running the install script? Please post in NOOB language...

**Comment by 0xQSL** [comment]
> What is now the best way to proceed? Somebody posted stopping or deleting some containters first before running the install script? Please post in NOOB language...

I just did this:
```
login via ssh
sudo docker stop hassio_supervisor
sudo docker rm hassio_supervisor
run install again
```

**Comment by maxi1134** [comment]
I managed to get the script to run. But now I cannot find the install folder of Home-Assistant.

It used to be at /docker/homeass/homeassistant.

I tried looking at the script to see where it would be installed but no luck.

Anyone can head me to the right direction? I'd like to restore my configuration files.

**Comment by jsiemek** [comment]
$ docker ps
to find CintainreID of Homeassistan Container

$docker inspect -f '{{ .Mounts }}' containerid

To display mounts

Jarek

W dniu śr., 4.03.2020 o 21:17 maxi1134 <notifications@github.com>
napisał(a):

**Comment by wellsi** [comment]
Does https://github.com/home-assistant/supervisor/pull/1566 fix the issue or just print the new warning that I see. I get that there is a problem, but the 'run all steps' does not work.

**Comment by jsb5151** [comment]
Why is this issue closed?  208 still crashes on my system with similar errors, and "forcing" 206 seems to be the only way to get everything started.

**Comment by frenck** [comment]
@jsb5151 Because the original issue raised in here was resolved and reported working again by the issue author. Thanks.

**Comment by rockinglama** [comment]
in case anybody else is also unhappy about automatic supervisor updates, vote here:
https://community.home-assistant.io/t/supervisor-option-for-disabling-auto-updates/176334

**Comment by TEDSv** [comment]
Thanks guys! I deleted hass.io at all before find that topic. But with your help, everything works now for me :)

**Comment by mkotlarz** [comment]
THANKS EVERYONE!  This worked
I logged in via ssh
sudo docker container stop hassio_supervisor 
sudo docker container rm hassio_supervisor
sudo curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | sudo bash -s
sudo docker restart homeassistant

**Comment by sirs2k** [comment]
I'm on Hassio and I can't run any sudo commands...

What can I do to fix this problem?

**Comment by SteveRMann** [comment]
Why is this closed- it is an ongoing issue.

**Comment by biejay** [comment]
> This is not working. Followed the suggested steps and still getting this error
> 
> 20-03-03 19:27:07 INFO (MainThread) [**main**] Initialize Supervisor setup
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/usr/src/supervisor/supervisor/**main**.py", line 41, in
> coresys = loop.run_until_complete(bootstrap.initialize_coresys())
> File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
> File "/usr/src/supervisor/supervisor/bootstrap.py", line 61, in initialize_coresys
> coresys.hwmonitor = HwMonitor(coresys)
> File "/usr/src/supervisor/supervisor/hwmon.py", line 22, in **init**
> self.monitor = pyudev.Monitor.from_netlink(self.context)
> File "/usr/local/lib/python3.7/site-packages/pyudev/monitor.py", line 121, in from_netlink
> raise EnvironmentError('Could not create udev monitor')
> OSError: Could not create udev monitor
> 20-03-03 19:27:08 ERROR (MainThread) [asyncio] Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x7fef07579690>
> 20-03-03 19:27:08 ERROR (MainThread) [asyncio] Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x7fef07597f90>
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.

Got the same Errors but like @sirs2k  i am on Hassio, so can not get around with docker etc. 
Also Hassio just stops working out of nowhere and i can only get it up runnning again by a complete reboot of my pi.

**Comment by jankete** [comment]
I just followed all setup steps here: https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host

But I still cat use the supervisor page, getting "Unable to load the panel source: /api/hassio/app/entrypoint.js."

Anything else I can try?

**Comment by arnonel** [comment]
Same issue for me. This is tiring

**Comment by jankete** [comment]
I ended up with removing all homeassistant / hassio containers and images and rebuild them via install script. After that it worked again. For the future I excluded all these containers from being updated via watchdog.

**Comment by townsmcp** [comment]
I had the same from overnight - can't get into Configurator.
I have worked around this, hoping its more than a temp fix though, by  SSHing into the RPI on port 22222 and doing a restore from last backup:

**ha snapshot** -----> make a note of the slug id
**ha snapshot restore "2997e2ca"**

Seems to have worked so far however root cause probably still remains

**Comment by grigio** [comment]
Now it's 
curl -sL https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh | bash -s

**Comment by mkotlarz** [comment]
I'm sorry guys I wish I could help you more, im pretty terrible at this and I likely had done some other step that contributed it working that I just didn't know.  I had tried 100 things.  I will say I had gotten that panel error just prior to resolving the issue with my steps.  I might have updated all the docker images too, I just don't remember.

**Comment by pvizeli** [comment]
@SteveRMann this bug is fix in 208 since over a month. You need just reinstall the supervisor.

**Comment by randomlyalex** [comment]
> @SteveRMann this bug is fix in 208 since over a month. You need just reinstall the supervisor.

Interesting because I found this thread due to supervisor not restarting.

I've reinstalled supervisor, following: https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host

and i still have the same problem?

I've also manually deleted the image and container for supervisor, and rerun the scripts from the lin above, and neither have fixed this issue yet?

🤷‍♂️

**Comment by achaiah** [comment]
I'm going to share my fix for "Unable to load the panel source: /api/hassio/app/entrypoint.js." issue here in case it helps anyone. Just so you know the background, I was trying to move a previous instance of hass.io from an ubuntu 16.04 lxc container into an ubuntu 18.04 VM. Banged my head around for a few hours before figuring this out so here are my steps:

1 `sudo -i`
    - Make sure you have network-manager installed or install with `apt-get update && apt-get -y install network-manager`
2. `sudo systemctl stop hassio-supervisor.service`
3. `docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)`
    - You may also need to do `docker rmi $(docker images -a -q)` but I didn't have to
4. Move your files over from previous installation if you need to
5. `sudo systemctl start hassio-supervisor.service` - at this point everything started except homeassistant docker container itself (which you can check by running `docker ps`) so my final step was...
6. `reboot now`

This seemed to do everything needed to restart the containers with proper networking.

**Comment by donnievawter** [comment]
I am still not able to restart with the following log entry:
[16:15:49] INFO: Starting local supervisor watchdog...
21-10-30 16:15:50 INFO (MainThread) [__main__] Initializing Supervisor setup
21-10-30 16:15:50 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 41, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 92, in initialize_coresys
    initialize_system(coresys)
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 170, in initialize_system
    config.path_backup.mkdir()
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/data/backup'
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
donvawter@fahadeb:~$

**Comment by JonasKvarnstrom** [comment]
>  FileExistsError: [Errno 17] File exists: '/data/backup'

I just had the same problem.  I started Portainer and inspected the container to see that /data was mounted from /usr/share/hassio on my main system.  In /usr/share/hassio, I had a backup folder that was a *symlink* to another location, since the backups are quite large.  This turned out to be the problem; you can't mkdir() a path that already exists as a symlink (or a file or anything else).

To solve this I moved the entire /usr/share/hassio folder to another location so that I could move the backup folder into it, and created a symlink from /usr/share/hassio to the new location.  This led to Home Assistant showing the "onboarding" dialogs instead of starting up.  Maybe this also has a check for whether /usr/share/hassio is a folder, rather than whether it exists (possibly as a symlink).

So I moved everything back but moved the backups out of the backups folder, and created an empty /usr/share/hassio/backups folder.  Then Home Assistant seems to start correctly.
