### ISSUE TITLE
Watchdog found a problem with PulseAudio plugin!

### ISSUE THREAD

**Issue by oneteam2win** [home-assistant/supervisor#1557]
**Home Assistant release with the issue:**
0.104.3

**Operating environment (HassOS/Generic):**
Docker on Synology NAS

**Supervisor logs:**
20-03-03 23:13:17 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin!
20-03-03 23:13:17 INFO (MainThread) [supervisor.audio] Start Audio plugin
20-03-03 23:13:17 INFO (SyncWorker_1) [supervisor.docker.interface] Clean hassio_audio application
20-03-03 23:13:19 INFO (SyncWorker_1) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 8 - 172.30.32.4

**Description of problem:**
Since the automatic update to Supervisor version 207, on a Synology NAS with HA 0.104.3, I have been experiencing error entries every 20 seconds.
20-03-03 21:55:55 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin!

When I look at the docker on Synology NAS, it keeps trying 
"hassio_audio" and stopped again shortly after.
![image](https://user-images.githubusercontent.com/57256232/75829675-1dde7680-5daf-11ea-94d7-b34773e023af.png)
![image](https://user-images.githubusercontent.com/57256232/75829692-2a62cf00-5daf-11ea-902a-7a859eb9a004.png)

Maybe the following screenshot of the hassio_audio protocol is also helpful.
![image](https://user-images.githubusercontent.com/57256232/75825716-34340480-5da6-11ea-9603-600619fad4e8.png)

**Comment by oneteam2win** [comment]
Maybe the following screenshot of the hassio_audio protocol is also helpful.
![image](https://user-images.githubusercontent.com/57256232/75825716-34340480-5da6-11ea-9603-600619fad4e8.png)

**Comment by frenck** [comment]
Please note: Running Home Assistant (previously known as Hass.io) on a Synology NAS is not supported by us.

**Comment by oneteam2win** [comment]
Unfortunately the answer is not helpful and also not comprehensible.
I would understand if I actively upgrade to a version that might cause problems with my setup.
But I don't understand it if an automatic upgrade is done here without my intervention.
Its function by the way seems to lead to problems more often as I can see in this forum.

I am a big supporter of the "never touch a running system" principle.
Therefore I ask for a correction or for help on how to get back to the previous supervisor version and disable the automatic update.
Thanks a lot.

**Comment by frenck** [comment]
I think my answer was more than appropriate and comprehensive. You are running a Home Assistant Supervised setup on a system we don't support.

> I am a big supporter of the "never touch a running system" principle.

Which makes sense in this specific case, however, you are running this on a system it was not designed for.

Please refer to the community guide/topic or community package maintainer for reporting issues with this way of running things.

**Comment by oneteam2win** [comment]
It's really strange how you deal with people seeking help.
You interfere with a working environment by performing unsolicited automatic uopdates, only to explain that you are not helping because the environment is not supported.

**Comment by frenck** [comment]
> It's really strange how you deal with people seeking help.

We track issue here on GitHub, if you need help or support please use or Community Forum or Discord chat server.

> You interfere a working environment by performing unsolicited automatic updates

Sorry to hear you feel that way. However, if you had run this on a supported environment, it would not have been an issue. I see your point, but you are raising as the source of the issue, which it is not. The source of the issue is running it on an unsupported platform.

Again, I know there is a community thread on the forums about the Synology package stuff created by the community. That might be a quicker way to find a workaround/solution to your problem.

**Comment by UmbeMont** [comment]
Just to add my situation , same probem , docker rebooting hass audio.
I think got messy with the usb of zigbee2mqtt , seen as an audio device , or otherwise no clou why an update of supervisor crushed everything.
to help , please note if you add a folder in hass /audio /internal /states with some files HA restart. but the audio docker will continue rebooting,

**Comment by oneteam2win** [comment]
@Frenck. Thanks for the clarification.
I'm not a programmer, nor was I aware of the exact function of GitHub.
I'm just a dedicated user and I try to follow the guidelines.
After I was told in another forum that I should place the topic on GitHub, I followed that request.

**Comment by bilak** [comment]
you can look here home-assistant/audio#4

**Comment by UbhiTS** [comment]
I'm having the same issue on a Raspberry Pi 3B+ using HASSIO. Any resolution to this ? This is what I see in the logs :- 

20-07-07 21:39:09 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with PulseAudio plugin!
20-07-07 21:39:09 INFO (MainThread) [supervisor.plugins.audio] Start Audio plugin
20-07-07 21:39:09 INFO (SyncWorker_7) [supervisor.docker.interface] Clean hassio_audio application
20-07-07 21:39:11 ERROR (SyncWorker_7) [supervisor.docker] Can't start hassio_audio: 403 Client Error: Forbidden ("endpoint with name hassio_audio already exists in network hassio")
20-07-07 21:39:11 ERROR (MainThread) [supervisor.plugins.audio] Can't start Audio plugin
20-07-07 21:39:11 ERROR (MainThread) [supervisor.misc.tasks] Watchdog PulseAudio reanimation fails!

**Comment by balloob** [comment]
Please open a new issue.
