### ISSUE TITLE
/var/run/dbus/system_bus_socket not found

### ISSUE THREAD

**Issue by davidvirdeforshh** [home-assistant/supervisor#1561]
**Home Assistant release with the issue:**
0.106.2

**Operating environment (HassOS/Generic):**
Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

**Supervisor logs:**

`20-03-03 22:21:46 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-03 22:35:06 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-03 22:35:06 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-03 22:35:06 INFO (MainThread) [supervisor.host.services] Update service information
20-03-03 22:35:06 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-03 22:35:06 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-03 22:35:06 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-03 22:35:06 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-03-04 00:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/pschmitt/home-assistant-addons repository
20-03-04 00:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/m2hofi94/my-hassio-addons repository
20-03-04 00:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-03-04 00:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-03-04 00:21:46 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-04 00:21:51 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/pschmitt/home-assistant-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/pschmitt/home-assistant-addons/': Could not resolve host: github.com'.
20-03-04 00:21:51 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/m2hofi94/my-hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/m2hofi94/my-hassio-addons/': Could not resolve host: github.com'.
20-03-04 00:21:51 WARNING (MainThread) [supervisor.updater] Can't fetch versions from https://version.home-assistant.io/stable.json: Cannot connect to host version.home-assistant.io:443 ssl:None [Try again]
20-03-04 00:21:51 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/home-assistant/hassio-addons/': Could not resolve host: github.com'.
20-03-04 00:21:51 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/hassio-addons/repository/': Could not resolve host: github.com'.
20-03-04 00:21:51 INFO (MainThread) [supervisor.store] Load add-ons from store: 70 all - 0 new - 0 remove
20-03-04 00:41:46 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-04 00:41:46 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-04 00:41:46 INFO (MainThread) [supervisor.host.services] Update service information
20-03-04 00:41:46 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-04 00:41:46 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-04 00:41:46 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-04 00:41:46 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-03-04 02:10:06 INFO (MainThread) [supervisor.tasks] Found new CLI version
20-03-04 02:10:06 INFO (SyncWorker_5) [supervisor.docker.interface] Update image homeassistant/armv7-hassio-cli:None to homeassistant/armv7-hassio-cli:19
20-03-04 02:10:06 INFO (SyncWorker_5) [supervisor.docker.interface] Pull image homeassistant/armv7-hassio-cli tag 19.
20-03-04 02:10:12 INFO (SyncWorker_5) [supervisor.docker.interface] Tag image homeassistant/armv7-hassio-cli with version 19 as latest
20-03-04 02:21:46 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-04 02:48:26 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-04 02:48:26 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-04 02:48:26 INFO (MainThread) [supervisor.host.services] Update service information
20-03-04 02:48:26 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-04 02:48:26 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-04 02:48:26 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-04 02:48:26 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-03-04 03:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/m2hofi94/my-hassio-addons repository
20-03-04 03:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-03-04 03:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/pschmitt/home-assistant-addons repository
20-03-04 03:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-03-04 03:21:47 INFO (MainThread) [supervisor.store] Load add-ons from store: 70 all - 0 new - 0 remove
20-03-04 04:21:46 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-04 04:55:06 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-04 04:55:06 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-04 04:55:06 INFO (MainThread) [supervisor.host.services] Update service information
20-03-04 04:55:06 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-04 04:55:06 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-04 04:55:06 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-04 04:55:06 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-03-04 06:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/m2hofi94/my-hassio-addons repository
20-03-04 06:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-03-04 06:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/pschmitt/home-assistant-addons repository
20-03-04 06:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-03-04 06:21:46 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-04 06:21:51 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/m2hofi94/my-hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/m2hofi94/my-hassio-addons/': Could not resolve host: github.com'.
20-03-04 06:21:51 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/hassio-addons/repository/': Could not resolve host: github.com'.
20-03-04 06:21:51 WARNING (MainThread) [supervisor.updater] Can't fetch versions from https://version.home-assistant.io/stable.json: Cannot connect to host version.home-assistant.io:443 ssl:None [Try again]
20-03-04 06:21:51 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/pschmitt/home-assistant-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/pschmitt/home-assistant-addons/': Could not resolve host: github.com'.
20-03-04 06:21:51 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/home-assistant/hassio-addons/': Could not resolve host: github.com'.
20-03-04 06:21:51 INFO (MainThread) [supervisor.store] Load add-ons from store: 70 all - 0 new - 0 remove
20-03-04 07:01:46 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-04 07:01:46 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-04 07:01:46 INFO (MainThread) [supervisor.host.services] Update service information
20-03-04 07:01:46 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-04 07:01:46 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-04 07:01:46 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-04 07:01:46 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-03-04 08:21:46 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-04 09:08:26 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-04 09:08:26 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-04 09:08:26 INFO (MainThread) [supervisor.host.services] Update service information
20-03-04 09:08:26 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-04 09:08:26 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-04 09:08:26 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-04 09:08:26 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-03-04 09:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-03-04 09:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/m2hofi94/my-hassio-addons repository
20-03-04 09:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/pschmitt/home-assistant-addons repository
20-03-04 09:21:46 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-03-04 09:21:47 INFO (MainThread) [supervisor.store] Load add-ons from store: 70 all - 0 new - 0 remove
20-03-04 09:30:46 INFO (SyncWorker_8) [supervisor.docker.interface] Restart homeassistant/raspberrypi4-homeassistant
20-03-04 09:31:08 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance`

**Description of problem:**
While running addon [ha-plejd](https://github.com/klali/ha-plejd/) it fails to find file:
`/var/run/dbus/system_bus_socket`
From what I can see, it should be available since I found this
`-v /var/run/dbus:/var/run/dbus`
in
`/usr/sbin/hassio-supervisor`

First reported [here](https://github.com/klali/ha-plejd/issues/27).

**Comment by pvizeli** [comment]
Make sure you OS support FHS 3.0 - https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by pvizeli** [comment]
Try a full reboot with SU 208

**Comment by pvizeli** [comment]
We use https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard 3.0 - I think if the add-on will look to the right path, it should work, otherwise the add-on need create a simlink.
