### ISSUE TITLE
N2 - Pulse Audio failed to load cookie

### ISSUE THREAD

**Issue by kreisklasse** [home-assistant/supervisor#1562]
**Home Assistant release with the issue:**
System: HassOS 4.3  (aarch64 / odroid-n2)
Home Assistant Core: 0.106.4
Home Assistant Supervisor: 207

**Description of problem:**
From time to time log entry
"**Update PulseAudio information : Failed to load cookie file from cookie: No such file or directory**"
on Odroid N2.

I do not use any sound-Addons (Spotify,..) , so i dont know if this would have an effect on these addons.
It also shows no bad effect on my home-assistant beside the log entries.

System log:
20-03-04 10:26:27 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-04 10:26:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-04 10:26:27 INFO (MainThread) [supervisor.host.services] Update service information
20-03-04 10:26:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-04 10:26:27 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-04 10:26:27 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
**20-03-04 10:26:27 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory**

**Comment by GoSpursGoNL** [comment]
Since v207 I also see that message in my system log every couple of hours. RPi 3.

20-03-04 15:06:06 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by pvizeli** [comment]
That is no issue, just a log message

**Comment by kreisklasse** [comment]
@pvizeli 
Sorry to say that, but log entry

> Failed to load cookie file from cookie: No such file or directory

is back with Supervisor **213**,
was gone with 209.



**Home Assistant release with the issue:**
System: HassOS 4.4 (aarch64 / odroid-n2)
Home Assistant Core: 0.107.7
Home Assistant Supervisor: 213

Hass System-Log:
https://paste.debian.net/1137263/

**Comment by frenck** [comment]
@kreisklasse Please don't use issue which are closed for some time already.
Instead, create a new issue. Thanks 👍
