### ISSUE TITLE
Can't update from Supervisor 206 to 207

### ISSUE THREAD

**Issue by Jdemuren** [home-assistant/supervisor#1564]
**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

20-03-04 15:37:12 INFO (MainThread) [hassio.homeassistant] Home Assistant pip installation done
20-03-04 15:37:17 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
20-03-04 15:37:17 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.106.5
20-03-04 15:37:17 INFO (SyncWorker_11) [hassio.docker.interface] Cleanup images: ['homeassistant/raspberrypi4-homeassistant:0.106.4']
20-03-04 15:37:50 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
20-03-04 15:38:15 INFO (MainThread) [hassio.supervisor] Update Supervisor to version 207
20-03-04 15:38:15 INFO (SyncWorker_7) [hassio.docker.interface] Pull image homeassistant/armv7-hassio-supervisor tag 207.
20-03-04 15:38:23 ERROR (SyncWorker_7) [hassio.docker.interface] Can't install homeassistant/armv7-hassio-supervisor:207 -> 404 Client Error: Not Found ("no such image: homeassistant/armv7-hassio-supervisor:207: No such image: homeassistant/armv7-hassio-supervisor:207").
20-03-04 15:38:23 ERROR (MainThread) [hassio.supervisor] Update of Hass.io fails!

**Description of problem:**

I can't update the Supervisor from 206 to 207. Getting errors. Thanks

**Comment by pvizeli** [comment]
Diskspace issue?

**Comment by Jdemuren** [comment]
I have enough space (26.3GB available);

pi@raspberrypi:~ $ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
mmcblk0     179:0    0 28.9G  0 disk
├─mmcblk0p1 179:1    0  2.4G  0 part
├─mmcblk0p2 179:2    0    1K  0 part
├─mmcblk0p5 179:5    0   32M  0 part
├─mmcblk0p6 179:6    0  256M  0 part /boot
└─mmcblk0p7 179:7    0 26.3G  0 part /

**Comment by pvizeli** [comment]
Doublicate of: #1506
