### ISSUE TITLE
Home assistant fails to start after supervisor update

### ISSUE THREAD

**Issue by sh00t2kill** [home-assistant/supervisor#1571]
This originally started when upgrading to 207, however problem persists with 208

I have tried rm the supervisor container and reinstalling via the script, but to no avail.

Logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing...
[12:08:48] INFO: Update udev informations
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
20-03-05 12:08:51 INFO (MainThread) [__main__] Initialize Supervisor setup
20-03-05 12:08:52 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 208
20-03-05 12:08:52 INFO (MainThread) [__main__] Setup Supervisor
20-03-05 12:08:52 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-03-05 12:08:52 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
20-03-05 12:08:52 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
20-03-05 12:08:52 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
20-03-05 12:08:52 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-05 12:08:52 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-05 12:08:52 INFO (MainThread) [supervisor.host.services] Update service information
20-03-05 12:08:52 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-05 12:08:52 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-05 12:08:52 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-05 12:08:52 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-03-05 12:08:52 INFO (MainThread) [supervisor.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-03-05 12:08:52 INFO (MainThread) [supervisor.host.services] Reload local service hassio-apparmor.service
20-03-05 12:08:52 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-03-05 12:08:52 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 1
20-03-05 12:08:52 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-audio with version 8
20-03-05 12:08:52 INFO (SyncWorker_3) [supervisor.docker.interface] Restart homeassistant/amd64-hassio-dns
20-03-05 12:08:52 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-03-05 12:08:55 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to homeassistant/qemux86-64-homeassistant with version 0.106.2
20-03-05 12:08:55 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-03-05 12:08:55 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-03-05 12:08:55 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/0844df1a repository
20-03-05 12:08:55 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/806b11b5 repository
20-03-05 12:08:55 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/7ad98f9c repository
20-03-05 12:08:56 INFO (MainThread) [supervisor.store] Load add-ons from store: 69 all - 69 new - 0 remove
20-03-05 12:08:56 INFO (MainThread) [supervisor.addons] Found 13 installed add-ons
20-03-05 12:08:56 INFO (SyncWorker_5) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-duckdns with version 1.10
20-03-05 12:08:56 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to fixated/remote-backup-amd64 with version 0.3.2
20-03-05 12:08:56 INFO (SyncWorker_2) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-samba with version 9.0
20-03-05 12:08:56 INFO (SyncWorker_6) [supervisor.docker.interface] Attach to dwelch2101/zigbee2mqtt-amd64 with version 1.10.0
20-03-05 12:08:56 INFO (SyncWorker_8) [supervisor.docker.interface] Attach to hassioaddons/sonweb-amd64 with version 0.8.4
20-03-05 12:08:56 INFO (SyncWorker_3) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-ssh with version 8.1
20-03-05 12:08:56 INFO (SyncWorker_9) [supervisor.docker.interface] Attach to hassioaddons/portainer-amd64 with version 0.8.0
20-03-05 12:08:56 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to hassioaddons/zerotier-amd64 with version 0.5.1
20-03-05 12:08:56 INFO (SyncWorker_7) [supervisor.docker.interface] Attach to hassioaddons/appdaemon3-amd64 with version 5.0.1
20-03-05 12:08:56 INFO (SyncWorker_5) [supervisor.docker.interface] Attach to hassioaddons/log-viewer-amd64 with version 0.6.4
20-03-05 12:08:56 INFO (SyncWorker_4) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-check_config with version 3.1
20-03-05 12:08:56 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to carldebilly/zigbee2mqttassistant with version 172
20-03-05 12:08:56 INFO (SyncWorker_2) [supervisor.docker.interface] Attach to hassioaddons/node-red-amd64 with version 6.0.0
20-03-05 12:08:56 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-05 12:08:57 INFO (MainThread) [supervisor.snapshots] Found 3 snapshot files
20-03-05 12:08:57 INFO (MainThread) [supervisor.discovery] Load 0 messages
20-03-05 12:08:57 INFO (MainThread) [supervisor.ingress] Load 0 ingress session
20-03-05 12:08:57 INFO (MainThread) [supervisor.secrets] Load Home Assistant secrets: 16
20-03-05 12:08:57 INFO (MainThread) [__main__] Run Supervisor
20-03-05 12:08:57 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-03-05 12:08:57 INFO (MainThread) [supervisor.addons] Phase 'initialize' start 0 add-ons
20-03-05 12:08:57 INFO (MainThread) [supervisor.core] Supervisor reboot detected
20-03-05 12:08:57 INFO (MainThread) [supervisor.tasks] All core tasks are scheduled
20-03-05 12:08:57 INFO (MainThread) [supervisor.hwmon] Started Supervisor hardware monitor
20-03-05 12:08:57 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-03-05 12:08:57 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-05 12:08:57 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-05 12:08:57 INFO (MainThread) [supervisor.host.services] Update service information
20-03-05 12:08:57 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-05 12:08:57 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-05 12:08:57 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-05 12:08:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-03-05 12:08:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
20-03-05 12:08:59 ERROR (MainThread) [supervisor.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
20-03-05 12:09:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-03-05 12:09:00 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon3
20-03-05 12:09:00 ERROR (MainThread) [supervisor.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
20-03-05 12:09:04 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-03-05 12:09:04 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
20-03-05 12:09:04 ERROR (MainThread) [supervisor.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:8123 ssl:False [Connection refused].
```

**Comment by pvizeli** [comment]
try `ha core start`

**Comment by Anwen747** [comment]
I am having the same issue - was on Supervisor 207 when I tried to update to 0.106.5 from 0.105.5.  Supervisor is running but HA wont start.   Have done the reinstall procedure, rebooted many times.   ```ha core start``` does not work., gives 

```Processing... Done.

Error: Unknown Error, see logs```

Logs:
```
20-03-05 13:59:26 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-03-05 13:59:26 INFO (MainThread) [supervisor.audio] Start Audio plugin
20-03-05 13:59:26 INFO (SyncWorker_7) [supervisor.docker.interface] Clean hassio_dns application
20-03-05 13:59:26 INFO (SyncWorker_5) [supervisor.docker.interface] Clean hassio_audio application
20-03-05 13:59:28 INFO (SyncWorker_7) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1 - 172.30.32.3
20-03-05 13:59:28 INFO (SyncWorker_5) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 8 - 172.30.32.4
20-03-05 13:59:28 INFO (SyncWorker_2) [supervisor.docker.interface] Attach to homeassistant/intel-nuc-homeassistant with version 0.106.5
20-03-05 13:59:29 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/15ef4d2f repository
20-03-05 13:59:29 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/03d23610 repository
20-03-05 13:59:29 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-03-05 13:59:29 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/cebe7a76 repository
20-03-05 13:59:29 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-03-05 13:59:29 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/243ffc37 repository
20-03-05 13:59:29 INFO (MainThread) [supervisor.store] Load add-ons from store: 78 all - 78 new - 0 remove
20-03-05 13:59:29 INFO (MainThread) [supervisor.addons] Found 13 installed add-ons
20-03-05 13:59:29 INFO (SyncWorker_10) [supervisor.docker.interface] Attach to hassioaddons/sqlite-web-amd64 with version 2.2.0
20-03-05 13:59:29 INFO (SyncWorker_8) [supervisor.docker.interface] Attach to esphome/esphome-hassio-amd64 with version 1.13.6
20-03-05 13:59:29 INFO (SyncWorker_5) [supervisor.docker.interface] Attach to hassioaddons/ssh-amd64 with version 7.2.0
20-03-05 13:59:29 INFO (SyncWorker_10) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-check_config with version 3.1
20-03-05 13:59:29 INFO (SyncWorker_15) [supervisor.docker.interface] Attach to hassioaddons/vscode-amd64 with version 2.1.0
20-03-05 13:59:29 INFO (SyncWorker_3) [supervisor.docker.interface] Attach to poeschl/hassio-marytts-amd64 with version 5.2-3
20-03-05 13:59:29 INFO (SyncWorker_2) [supervisor.docker.interface] Attach to hassioaddons/adguard-amd64 with version 2.3.2
20-03-05 13:59:29 INFO (SyncWorker_4) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-mosquitto with version 5.1
20-03-05 13:59:29 INFO (SyncWorker_13) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-configurator with version 4.7
20-03-05 13:59:29 INFO (SyncWorker_9) [supervisor.docker.interface] Attach to hassioaddons/log-viewer-amd64 with version 0.8.0
20-03-05 13:59:29 INFO (SyncWorker_14) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-deconz with version 5.3
20-03-05 13:59:29 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to hassioaddons/portainer-amd64 with version 1.0.0
20-03-05 13:59:29 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to sabeechen/hassio-google-drive-backup-amd64 with version 0.100.0
20-03-05 13:59:29 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-03-05 13:59:29 INFO (MainThread) [supervisor.snapshots] Found 10 snapshot files
20-03-05 13:59:30 INFO (MainThread) [supervisor.discovery] Load 3 messages
20-03-05 13:59:30 INFO (MainThread) [supervisor.ingress] Load 1 ingress session
20-03-05 13:59:30 INFO (MainThread) [supervisor.secrets] Load Home Assistant secrets: 18
20-03-05 13:59:30 INFO (MainThread) [__main__] Run Supervisor
20-03-05 13:59:30 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-03-05 13:59:30 INFO (MainThread) [supervisor.addons] Phase 'initialize' start 0 add-ons
20-03-05 13:59:30 INFO (MainThread) [supervisor.addons] Phase 'system' start 3 add-ons
20-03-05 13:59:30 INFO (MainThread) [supervisor.secrets] Request secret vnc_password
20-03-05 13:59:31 INFO (SyncWorker_3) [supervisor.docker.addon] Start Docker add-on poeschl/hassio-marytts-amd64 with version 5.2-3
20-03-05 13:59:33 INFO (SyncWorker_17) [supervisor.docker.addon] Start Docker add-on homeassistant/amd64-addon-mosquitto with version 5.1
20-03-05 13:59:34 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
20-03-05 13:59:34 INFO (SyncWorker_19) [supervisor.docker.addon] Start Docker add-on homeassistant/amd64-addon-deconz with version 5.3
20-03-05 13:59:35 INFO (MainThread) [supervisor.auth] Auth request from core_mosquitto for admin
20-03-05 13:59:35 ERROR (MainThread) [supervisor.homeassistant] Error on call http://172.30.32.1:8123/api/: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
20-03-05 13:59:35 INFO (MainThread) [supervisor.auth] Home Assistant not running, check cache
20-03-05 13:59:35 INFO (MainThread) [supervisor.auth] Cache hit for admin
20-03-05 13:59:39 INFO (MainThread) [supervisor.addons] Phase 'services' start 5 add-ons
20-03-05 13:59:39 WARNING (MainThread) [supervisor.addons.validate] Unknown options ssl
20-03-05 13:59:39 WARNING (MainThread) [supervisor.addons.validate] Unknown options certfile
20-03-05 13:59:39 WARNING (MainThread) [supervisor.addons.validate] Unknown options keyfile
20-03-05 13:59:39 WARNING (MainThread) [supervisor.addons.validate] Unknown options keyfile
20-03-05 13:59:39 WARNING (MainThread) [supervisor.addons.validate] Unknown options disable_telemetry
20-03-05 13:59:39 WARNING (SyncWorker_18) [supervisor.docker.addon] Portainer run with disabled protected mode!
20-03-05 13:59:39 WARNING (MainThread) [supervisor.addons.validate] Unknown options web
20-03-05 13:59:40 INFO (SyncWorker_16) [supervisor.docker.addon] Start Docker add-on hassioaddons/adguard-amd64 with version 2.3.2
20-03-05 13:59:41 INFO (SyncWorker_11) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-amd64 with version 7.2.0
20-03-05 13:59:42 INFO (SyncWorker_1) [supervisor.docker.addon] Start Docker add-on hassioaddons/sqlite-web-amd64 with version 2.2.0
20-03-05 13:59:42 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_adguard
20-03-05 13:59:42 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-03-05 13:59:43 INFO (SyncWorker_18) [supervisor.docker.addon] Start Docker add-on hassioaddons/portainer-amd64 with version 1.0.0
20-03-05 13:59:43 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_sqlite-web
20-03-05 13:59:43 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on hassioaddons/vscode-amd64 with version 2.1.0
20-03-05 13:59:44 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_portainer
20-03-05 13:59:44 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_adguard
20-03-05 13:59:44 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_vscode
20-03-05 13:59:45 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_sqlite-web
20-03-05 13:59:48 ERROR (MainThread) [supervisor.homeassistant] Home Assistant can't write pulse/client.config: [Errno 21] Is a directory: '/data/tmp/homeassistant_pulse'
20-03-05 13:59:48 INFO (MainThread) [supervisor.addons] Phase 'application' start 4 add-ons
20-03-05 13:59:50 INFO (SyncWorker_5) [supervisor.docker.addon] Start Docker add-on esphome/esphome-hassio-amd64 with version 1.13.6
20-03-05 13:59:51 INFO (MainThread) [supervisor.api.security] /host/info access from 15ef4d2f_esphome
20-03-05 13:59:51 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on hassioaddons/log-viewer-amd64 with version 0.8.0
20-03-05 13:59:52 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_logviewer
20-03-05 13:59:52 INFO (SyncWorker_2) [supervisor.docker.addon] Start Docker add-on homeassistant/amd64-addon-configurator with version 4.7
20-03-05 13:59:53 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_logviewer
20-03-05 13:59:53 INFO (SyncWorker_10) [supervisor.docker.addon] Start Docker add-on sabeechen/hassio-google-drive-backup-amd64 with version 0.100.0
20-03-05 13:59:54 ERROR (MainThread) [supervisor.homeassistant] Error on call http://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
20-03-05 13:59:54 ERROR (MainThread) [supervisor.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/0a51e1f4/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/302b114f/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/33899ae1/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/0e11f2f9/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/9940166f/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/8e69ae9a/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/0755dde8/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/bbd64fdf/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/589dba32/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:54 INFO (MainThread) [supervisor.api.security] /snapshots/ebd83a99/info access from cebe7a76_hassio_google_drive_backup
20-03-05 13:59:58 INFO (MainThread) [supervisor.tasks] All core tasks are scheduled
20-03-05 13:59:58 INFO (MainThread) [supervisor.hwmon] Started Supervisor hardware monitor
20-03-05 13:59:58 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-03-05 13:59:58 INFO (MainThread) [supervisor.host.info] Update local host information
20-03-05 13:59:58 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-03-05 13:59:58 INFO (MainThread) [supervisor.host.services] Update service information
20-03-05 13:59:58 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-03-05 13:59:58 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-03-05 13:59:58 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-03-05 13:59:58 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-03-05 14:00:48 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from a0d7b954_ssh
20-03-05 14:00:59 ERROR (MainThread) [supervisor.homeassistant] Error on call http://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
20-03-05 14:00:59 ERROR (MainThread) [supervisor.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
20-03-05 14:01:54 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from a0d7b954_ssh
20-03-05 14:03:04 ERROR (MainThread) [supervisor.homeassistant] Error on call http://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
20-03-05 14:03:04 ERROR (MainThread) [supervisor.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
20-03-05 14:05:30 INFO (MainThread) [supervisor.auth] Auth request from core_mosquitto for admin
20-03-05 14:05:30 ERROR (MainThread) [supervisor.homeassistant] Error on call http://172.30.32.1:8123/api/: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
20-03-05 14:05:30 INFO (MainThread) [supervisor.auth] Home Assistant not running, check cache
20-03-05 14:05:30 INFO (MainThread) [supervisor.auth] Cache hit for admin
20-03-05 14:07:09 ERROR (MainThread) [supervisor.homeassistant] Error on call http://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
20-03-05 14:07:09 ERROR (MainThread) [supervisor.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
20-03-05 14:07:33 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from a0d7b954_ssh
20-03-05 14:10:37 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from a0d7b954_ss

```

**Comment by badboybeyer** [comment]
I have the same issue and result as @Anwen747 . I am running an OVA version of hassio from qemu.

**Comment by Anwen747** [comment]
Problem solved by deleting /data/tmp/homeassistant_pulse as discussed in [https://github.com/home-assistant/core/issues/32514](url).  However, the underlying issue with why this file is preventing HA startup needs to be corrected.
