### ISSUE TITLE
Provide better explanation why add-ons can't be installed

### ISSUE THREAD

**Issue by askask** [home-assistant/supervisor#1580]
**Home Assistant release with the issue:**
0.106.5

**Operating environment (HassOS/Generic):**
Supervisor version 209
HassOS 3.12

**Supervisor logs:**

N/A

**Description of problem:**
 In the add-on store, several add-ons are shown as not available with the message `This add-on is not available on your system.` It would be helpful if HA would show a more specific message, describing in which way the system is not compatible with the add-on.

**Comment by frenck** [comment]
It means it is not compatible with your CPU and operating system architecture...

**Comment by askask** [comment]
Thanks for clearing that up. It seems obvious but I wasn't sure whether it was because of that or a different reason like an incompatible software version, insufficient storage or some (mis)configuration...
