### ISSUE TITLE
Do not warn about using server_host option

### ISSUE THREAD

**Issue by GuerrillaTechnology** [home-assistant/supervisor#1581]
I am using Supervisor on a system with multiple IPs. 
By default supervisor binds to 0.0.0.0 , I need it so bind to only one IP, for example 1.2.3.4.
This can be done by changing **server_host** in .storage/http

Setting server_host to anything other then 0.0.0.0 triggers a warning, which engages safe mode and renders my setup inoperational. Until the introduction of safe mode, supervisor worked without any issues in this configuration

Supervisor should not activly prohibit binding to a specific IP as this is a valid use case.
If I am not allowed to not change the server_host config variable, it serves no purpose, should not exist and supervisor would not need to check if it is set to something else then the default value.

**Comment by pvizeli** [comment]
You are wrong, somethings will not work. We have our internal virtual network and Core needs to listen there.
