### ISSUE TITLE
Synology HassOS keeps reporting errors in the new supervisor version (due to the updated Pulse audio)

### ISSUE THREAD

**Issue by jyz0501** [home-assistant/supervisor#1582]
Ha：0.106.5
Supervisor：209

20-03-12 06:20:29 INFO (MainThread) [supervisor.audio] Start Audio plugin
20-03-12 06:20:29 INFO (SyncWorker_7) [supervisor.docker.interface] Clean hassio_audio application
20-03-12 06:20:39 INFO (SyncWorker_7) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 8 - 172.30.32.4
20-03-12 06:20:49 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin!
20-03-12 06:20:49 INFO (MainThread) [supervisor.audio] Start Audio plugin
20-03-12 06:20:49 INFO (SyncWorker_9) [supervisor.docker.interface] Clean hassio_audio application
20-03-12 06:20:55 INFO (SyncWorker_9) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 8 - 172.30.32.4
20-03-12 06:21:09 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin!
20-03-12 06:21:09 INFO (MainThread) [supervisor.audio] Start Audio plugin
20-03-12 06:21:09 INFO (SyncWorker_12) [supervisor.docker.interface] Clean hassio_audio application
20-03-12 06:21:17 INFO (SyncWorker_12) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 8 - 172.30.32.4
20-03-12 06:21:29 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin!
20-03-12 06:21:29 INFO (MainThread) [supervisor.audio] Start Audio plugin
20-03-12 06:21:29 INFO (SyncWorker_8) [supervisor.docker.interface] Clean hassio_audio application
20-03-12 06:21:41 INFO (SyncWorker_8) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 8 - 172.30.32.4
20-03-12 06:21:49 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin!
20-03-12 06:21:49 INFO (MainThread) [supervisor.audio] Start Audio plugin
20-03-12 06:21:49 INFO (SyncWorker_13) [supervisor.docker.interface] Clean hassio_audio application
20-03-12 06:21:57 INFO (SyncWorker_13) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 8 - 172.30.32.4
20-03-12 06:22:09 WARNING (MainThread) [supervisor.tasks] Watchdog found a problem with PulseAudio plugin!
20-03-12 06:22:09 INFO (MainThread) [supervisor.audio] Start Audio plugin
20-03-12 06:22:09 INFO (SyncWorker_4) [supervisor.docker.interface] Clean hassio_audio application
20-03-12 06:22:20 INFO (SyncWorker_4) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 8 - 172.30.32.4
20-03-12 06:22:33 INFO (SyncWorker_4) [supervisor.docker.interface] Clean addon_40817795_ledfx application

**Comment by jyz0501** [comment]
https://github.com/home-assistant/supervisor/pull/1555

**Comment by jyz0501** [comment]
https://github.com/home-assistant/audio/issues/6

**Comment by pvizeli** [comment]
Synology bare-metal installation are not supported. Please use the Virtual Appliance or ask the maintainer of the Synology installer to fix the issue.
