### ISSUE TITLE
Supervisor on Docker/Kubernetes

### ISSUE THREAD

**Issue by devfsalvadori** [home-assistant/supervisor#1587]
**Home Assistant release with the issue:**
 N/A

**Operating environment (HassOS/Generic):**

Raspberry PI4 - Kubernetes Rancher K3S 
**Supervisor logs:**

N/A

**Description of problem:**
Using helm to deploy pod as explained in the guide https://github.com/helm/charts/tree/master/stable/home-assistant I'm able to make HomeAssistant running also with configurator. But the supervisor is not present. 
In dockerhub page I find some images with -supervisor but I didn't find the right one for my environment. All arm images cause a pod fault and restarting indefinitely and obviously homehassistant is not reachable.
Which are the right image to run or the right way to make homeassistant running with all options 
mainly supervisor?

**Comment by frenck** [comment]
Running Home Assistant on Kubernetes is not supported, for more information see: #988 

If you are looking for these types of setups, we recommend using Home Assistant Core.

**Comment by devfsalvadori** [comment]
Ok but using the official image on homeassistant/home-assistant:latest on docker desktop I have the same problem. No supervisor. How to use supervisor on docker?

**Comment by jsiemek** [comment]
https://www.home-assistant.io/hassio/installation/

**Comment by frenck** [comment]
The supervisor is part Home Assistant as a complete system, not part if Home Assistant Core.

`homeassistant/home-assistant:latest` -> That is Home Assistant Core. Not the full ecosystem.
