### ISSUE TITLE
Running addons with --privileged

### ISSUE THREAD

**Issue by GabrielePicco** [home-assistant/supervisor#1588]
Hi,

I'm trying to create a [Wireguard client add-on](https://github.com/GabrielePicco/home-assistant-wireguard-client-addon) that require to updated some forwarding rules. Without running the container with --privileged i get the following error: `Setting key "net.ipv6.conf.default.forwarding": Read-only file system`. Any idea on how to solve it ?

I added in the configuration
  ```
"kernel_modules": true,
"full_access": true, 
```
but it is not equal to running the container with --privileged

Related issue: #201

**Comment by frenck** [comment]
You can't solve that.

Als you already found out in the issue linked.

**Comment by bigmoby** [comment]
> Hi,
> 
> I'm trying to create a [Wireguard client add-on](https://github.com/GabrielePicco/home-assistant-wireguard-client-addon) that require to updated some forwarding rules. Without running the container with --privileged i get the following error: `Setting key "net.ipv6.conf.default.forwarding": Read-only file system`. Any idea on how to solve it ?
> 
> I added in the configuration
> 
> ```
> "kernel_modules": true,
> "full_access": true, 
> ```
> 
> but it is not equal to running the container with --privileged
> 
> Related issue: #201

Hi @GabrielePicco if you want I suggest you to try with this add-on: https://github.com/bigmoby/addon-wireguard-client
and, if it will be useful for you, would be appreciated your support.

**Comment by frenck** [comment]
That add-on is dangerous, as it messages with the host network routing. I would not recommend that.

Furthermore, this issue has been closed for many many months already. Please don't dig up old issues. Thanks 👍
