### ISSUE TITLE
Audio not working after installing Hass.io in Docker

### ISSUE THREAD

**Issue by AmazedWolf900** [home-assistant/supervisor#1589]
Hello, I have problem with audio on my PC with Ubuntu after I installed Hassio in Docker. I found out that the hassio_supervisor container automaticily create another container called hassio_audio and this container is the problem. If I stop this container the audio start works normally, but after a while, the hassio_supervisor automaticily start the audio container again and the audio stop working.

I don’t need audio in Home Assistant, so how I can disable the hassio_audio container permanently?

**Comment by ioio85** [comment]
Same problem here on kubuntu 19.10. no audio on the machine and blocks the video too. I reinstall everything from scratch and Home assistant (hassio) .106.6. It took me a while to narrow it down this problem too. Removing hassio fix the problem.

**Comment by patmann03** [comment]
Also having this issue.  Stopping the hassio_audio container fixes the problem

**Comment by ioio85** [comment]
more info there: [#12](https://github.com/home-assistant/audio/issues/12)

**Comment by frenck** [comment]
The issue is tracked on the issue linked by @ioio85 above.
