### ISSUE TITLE
 Cannot have more than one secret value in an addon's config

### ISSUE THREAD

**Issue by axilleas** [home-assistant/supervisor#1590]
**Home Assistant release with the issue:**  0.106.6

**Operating environment (HassOS/Generic):** Docker

**Supervisor logs:** N/A (nothing related to this issue)

**Description of problem:**

Addons which support an array of values and also secrets is an option, cannot have more than one secrets defined in the array.

I tested with https://github.com/hassio-addons/addon-zerotier which supports having multiple networks.

I used the following:

```yaml
networks:
  - '!secret zerotier_net_one'
  - '!secret zerotier_net_two'
```

And it errors with:

```
Failed to save addon configuration, not a valid value for dictionary value @ data['options'].
Got {'networks': ['!secret zerotier_net_one', '!secret zerotier_net_two'], 'api_auth_token': ''}
```

**Comment by pvizeli** [comment]
List are not supported. There was a PR but the author never finish it.

**Comment by axilleas** [comment]
Found it https://github.com/home-assistant/supervisor/pull/1391. @pvizeli should I convert the issue to a feature request?

**Comment by pvizeli** [comment]
The point is, all developers have a full task list for this year. So if you don't want to implement this, it will not be implemented, also if you create a feature request. That means it is what it is until someone invests his time to change it.

**Comment by axilleas** [comment]
@pvizeli I hear you, thanks :) I don't have the knowledge to work on this unfortunately... I'd say at least let's leave this issue open so that it's easy to find.
