### ISSUE TITLE
[hassio] fatal: supervisor not listening on v0.107.6

### ISSUE THREAD

**Issue by rwlove** [home-assistant/supervisor#1596]
**Home Assistant release with the issue:**

0.107.6

**Operating environment (HassOS/Generic):**

Hassio container image

**Supervisor logs:**

N/A?

**Description of problem:**

Hassio fails to start with 0.107.6. It works fine with 0.106.2, but when I upgraded the base Hassio image it failed to start, giving me this message:

root@brain homeassistant]# docker run --rm services/homeassistant:v0.107.6 . 2>&1 | tee -a build.log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[22:40:31] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec .: Permission denied
[cmd] . exited 126
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by pvizeli** [comment]
> docker run --rm services/homeassistant:v0.107.6 . 

is not us

**Comment by rwlove** [comment]
> > docker run --rm services/homeassistant:v0.107.6 .
> 
> is not us

It is you. That's just the name of the derivative container that I use. It's Hassio with very few additions.

**Comment by pvizeli** [comment]
if your system can execute `ha core info` and `ha su info`, you can reopen the issue

**Comment by rwlove** [comment]
Is this right?

[root@brain homeassistant]# docker run -it docker.io/homeassistant/home-assistant:0.107.6 ha core info
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[14:51:25] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec ha: No such file or directory
[cmd] ha exited 127
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by rwlove** [comment]
Is the container image different than hassio? It looks like there's no 'ha' command...
