### ISSUE TITLE
N2 - "Failed to load cookie file from cookie" message again

### ISSUE THREAD

**Issue by kreisklasse** [home-assistant/supervisor#1612]
Sorry to say that, but log entry

    Failed to load cookie file from cookie: No such file or directory

seems to be back with Supervisor **213**,
which was gone with **209**. ( https://github.com/home-assistant/supervisor/issues/1562 )

_Home Assistant release with the issue:_
System: HassOS 4.4 (aarch64 / odroid-n2)
Home Assistant Core: 0.107.7
Home Assistant Supervisor: 213

_Hass System-Log:_
https://paste.debian.net/1137263/

**Comment by pvizeli** [comment]
Is no issue

**Comment by tomlut** [comment]
If it's not an issue stop generating errors about it then.
