### ISSUE TITLE
Incorrect permissions of /dev/ttyS* devices

### ISSUE THREAD

**Issue by DaAwesomeP** [home-assistant/supervisor#1614]
**Home Assistant release with the issue:**
0.107.5 (also was an issue with 0.106, seems unrelated to HA version)

**Operating environment (HassOS/Generic):**
HassOS 3.12 on Intel NUC-like device. `/dev/ttyS0` is a physical RS-232 port.
Supervisor 213

**Supervisor logs:**
There was nothing significant in the supervisor logs—started addons as normal. However, when the Nut addon tries to access `/dev/ttyS0`, it gives an error:
```
Unable to open /dev/ttyS0: Permission denied
  Current user id: nut (100)
Serial port owner: root (0)
Serial port group: audio (18)
     Mode of port: 0660
```
Running `ls -al /dev/ttyS*` confirms that the `ttyS*` ports are `root:audio 0600`. The same incorrect permissions apply to `/dev/serial/*/*` devices as well.

**Description of problem:**
Addons do not have permission to access `/dev/ttyS*` ports.

**Related issues:**
https://github.com/hassio-addons/addon-nut/issues/32 (issue that identifies the issue with the NUT addon)
https://github.com/hassio-addons/addon-nut/pull/33 (pull that provides a workaround by manually setting the permissions from the addon)

**Comment by DaAwesomeP** [comment]
I suppose a solution would be to either change the octal permissions to allow non-owner and non-group users to access the ports, or to create a `dialout` or similar group for addon users (and I suppose the audio user) to be added to for accessing serial ports.

**Comment by pvizeli** [comment]
It's docker, you should run the software as root not as nut.

Yes, you can run different user on docker but now starts the issues. The host did not know the user and device permissions going wrong or allow other users to become access which you not want. Next permissions going wrong on snapshot based on used uid and the new host.

Different user are nice if you self make all by your self and you know and resetup everything self on the new host. Currently until a central usermanagement is supported by posix/linux and containers to share such stuff, you should not really use it inside add-on if that is possible.
