### ISSUE TITLE
214 break my Zwave 

### ISSUE THREAD

**Issue by AngelofromTurin** [home-assistant/supervisor#1619]
**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**

Ha 107.7
HassOs 3.13
Upgrading From SV 213 to 214 i’d lost my zwave device ( again, thise was happened just when upgrade de Hassio version From 106 to 107.1 and 107.5...)

**Comment by pvizeli** [comment]
zwave is just ha core. The supervisor did not have any affect to the core. Please update to 0.107.6 or downgrade to 0.106.6 if you think that work better.

**Comment by AngelofromTurin** [comment]
Im sorry, but before upgrade the supervisor all work right ... 
thankyou

**Comment by pvizeli** [comment]
You can post to: https://github.com/home-assistant/core/issues/33096
