### ISSUE TITLE
How to recover supervisor

### ISSUE THREAD

**Issue by michalk-k** [home-assistant/supervisor#1621]
Hello guys
May I ask for help with recovering supervisor after recent problems ("unable to load panel source: /api/hassio/app/entrypoint.js")?

I don't know if I can afford hard restart of RPi or rather work out something else using ssh instead.
I tried 
```
ha su reload
ha su update
```
suggested somewhere else, but it ends up with:
```
➜  ~ ha su reload
Post http://supervisor/supervisor/reload: dial tcp 172.30.32.2:80: connect: connection refused
```

thanks in advance

**Comment by pvizeli** [comment]
you need pull the version of supervisor which you need and tag this as latest on your host. Otherwise it's not possible :(

**Comment by michalk-k** [comment]
would you like to be more precise?
I have no idea how to do that. I have ssh access via HA's SSH integration

**Comment by dereitz** [comment]
Same here, I'm at a loss how to do that.  Would downgrading even fix this issue?

**Comment by lordkev** [comment]
@frenck seems to have said in other related issues that this is not a supervisor problem and is due to old startup scripts. All I know is that my hassio installation (on Raspberry Pi) was humming along just fine until this update and now everything is broken all of a sudden.

When and how exactly were we supposed to have updated these startup scripts? How can those of us running hassio on RPi fix this issue?

**Comment by lordkev** [comment]
I have SSH access, but when I try to access the host via the login command I'm prompted for credentials I don't have. Seems with other examples I've seen when the login command is run it just brings up a shell for the host.

```
core-ssh:/etc# login
core-ssh.local.hass.io login: 
core-ssh.local.hass.io login: root
Login incorrect
core-ssh.local.hass.io login: 
Login timed out after 60 seconds
core-ssh:/etc# 
```

**Comment by lordkev** [comment]
Just an update. I ended up doing a dirty reboot by yanking power and that got me back up and running. Trying to update HassOS now...hopefully that will help in the future as it was very out of date (1.13).
