### ISSUE TITLE
Add-ons - cannot start them

### ISSUE THREAD

**Issue by beniek89** [home-assistant/supervisor#1624]
Hello , 

It's my first post , so i hope it well be all good.

Last few days i update hassio. Yesterday i saw that all add-ons dont work, and i cannot start them :/ 

I search in few places.
I try also downgrade docker and its also dont help. 
I found only that : 
Supervisor : 
Version | 214
Latest version | 214

Logs : 

20-04-02 18:15:31 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Addon.start() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:472> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 493, in start
    raise AddonsError() from None
supervisor.exceptions.AddonsError. 

Of course i can reinstall hassio, but i think its not good way. 
Ps. Hassio on docker.

**Comment by darrylb83** [comment]
I too am having this issue. Most recently, I stopped/disabled a few other dockers apps such as MariaDB, which was installed separately from HASS.io. This seems to have gotten me to another, but similar error. This suggestion was a suggestion on the Home Assistant community. New (similar) error:

Unable to load the panel source: /api/hassio/app/entrypoint.js.

This did start exactly like frenck. I had the install running only 48hrs before this occurred, and it happened sometime overnight, so I figured it was update related.

I am on version: 0.107.7
Frontend version: 20200318.1 - latest

I see the following in the logs:
Can't read panel info:
April 7, 2020, 8:30:51 AM – Hass.io (ERROR)
Can't read last version:
April 7, 2020, 8:30:51 AM – Hass.io (WARNING)

Hope this similar, but different info helps. Seems many others are having this issue on the community forums too. I have done a reinstall with my same config, same issue continued.
