### ISSUE TITLE
ADD-ON store not loading

### ISSUE THREAD

**Issue by gmcaesar** [home-assistant/supervisor#1639]
Home Assistant supervisor, ver 214
running on raspberry pi 3 with raspbian and docker

ADD-ON store is empty

**Supervisor logs:**
fatal: early EOF
fatal: index-pack failed
'.
20-04-07 18:53:17 ERROR (MainThread) [supervisor.store] Can't load from repository https://github.com/hassio-addons/repository
20-04-07 18:53:17 INFO (MainThread) [supervisor.store] Load add-ons from store: 0 all - 0 new - 0 remove
20-04-07 18:53:17 INFO (MainThread) [supervisor.addons] Found 0 installed add-ons

**Comment by pvizeli** [comment]
maybe something on the container is wrong, force a rebuid with `ha su update --version 213`

**Comment by gmcaesar** [comment]
did that and got this for the log on trying add-on store again

20-04-07 23:11:04 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/home-assistant/hassio-addons repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/home-assistant/hassio-addons /data/addons/core
  stderr: 'Cloning into '/data/addons/core'...
fatal: unable to access 'https://github.com/home-assistant/hassio-addons/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
'.
20-04-07 23:11:04 ERROR (MainThread) [supervisor.store] Can't load from repository core
20-04-07 23:11:04 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/hassio-addons/repository repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/hassio-addons/repository /data/addons/git/a0d7b954
  stderr: 'Cloning into '/data/addons/git/a0d7b954'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
error: RPC failed; curl 56 OpenSSL SSL_read: Connection reset by peer
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
'.
20-04-07 23:11:04 ERROR (MainThread) [supervisor.store] Can't load from repository https://github.com/hassio-addons/repository


still noting showing in the store

**Comment by pvizeli** [comment]
`error: RPC failed; curl 56 OpenSSL SSL_read: Connection reset by peer` firewall? time out of sync?

**Comment by gmcaesar** [comment]
no additional firewall, just my router, provided by Shaw (in BC, Canada if you don't know the name 👍 )  time seemed right on my end, not sure how to check it against the server.

**Comment by gmcaesar** [comment]
connected R pi to hard line and everything worked....
