### ISSUE TITLE
Missing add-ons from official add-on store

### ISSUE THREAD

**Issue by Hukuma1** [home-assistant/supervisor#1646]
**Home Assistant release with the issue:**

Home Assistant 0.108.0 with Supervisor 215

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.97-v7l+
python_version | 3.7.7
version | 0.108.0
virtualenv | false

**Operating environment (HassOS/Generic):**

RPi4 with Generic install

**Supervisor logs:**

**Description of problem:**
Ever since upgrade from v.106/213 certain add-ons completely missing from the store and not able to update them (since they're missing). Tried removing ADB add-on to try to reinstall it, only to not be able to find it in the store. So cannot install it at all now. Seems the addons with missing icons are affected. Note missing add-ons from list like Pi-Hole, Portainer, ADB.

![addons](https://user-images.githubusercontent.com/54511555/78817654-52ce8200-7988-11ea-9775-eab694e603e1.jpg)

![addons2](https://user-images.githubusercontent.com/54511555/78817886-b2c52880-7988-11ea-8d42-808e61e513a4.jpg)

![addons3](https://user-images.githubusercontent.com/54511555/78818108-fc157800-7988-11ea-9a44-2edbbbf12120.jpg)

**Comment by frenck** [comment]
Portainer isn't in the official add-on store. It is provided by the community add-ons repository. Looking at your screenshot, it has been removed from the store index.

You can add it again by adding the following repository:

`https://github.com/hassio-addons/repository`

**Comment by Hukuma1** [comment]
Ahh! Seems like an update killed the repo that was added before. Thank you! For anyone else having similar issues, re-add the repo.

**Comment by MrTh0m** [comment]
Hello,

I've the same issue with the Official add-ons. deConz and others intalled show a piece of puzzle.
core-2021.5.5
supervisor-2021.05.4
Home Assistant OS 5.13

**Comment by jacobthecoder** [comment]
Hi @frenck - I'm getting this error when trying to add the repository that you suggested:
<img width="599" alt="Home_Assistant" src="https://user-images.githubusercontent.com/22946743/164987409-af33b05d-37b5-4de3-a746-5a2459a077a2.png">

I too am trying to install the Portainer add-on but cannot find it.
