### ISSUE TITLE
Wifi only system will not fully start

### ISSUE THREAD

**Issue by ropeguru** [home-assistant/supervisor#1649]
So I have a situation right now where I need to run my HA Raspberry PI in a location where I cannot get an ethernet cable to.

I have installed HASS.IO from an image, have it up and running while on ethernet, configured wifi successfully, and can access the front end from either the wired or wireless IP.

After shutting down the PI and disconnecting the wired ethernet and powering on, supervisor starts but noting else does. I can ping the wireless IP but cannot connect to anything.

Access the PI via a console, I can login as root and get the "ha" prompt and start the core with "core start" and then access the front end. However, none of the other add-on containers are started.

Does supervisor explicitly wait for a wired connection before it will start any of he containers? If so, can this be modified so that it will start all the containers if wlan0 instead of eth0 is up and available?

**Comment by ropeguru** [comment]
This is the last entry in the supervisor log:

20-04-10 22:15:20 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance

**Comment by pvizeli** [comment]
That is a time issue. Your PI have/had the wrong time which prevent him to detect a reboot
