### ISSUE TITLE
Repetitive "invalid token" issues

### ISSUE THREAD

**Issue by jelmerkk** [home-assistant/supervisor#1653]
Since latest supervisor upgrade I constantly get shut out of supervisor. Logs show:
`20-04-11 09:53:09 ERROR (MainThread) [supervisor.api.security] Invalid token for access /app/entrypoint.js`

A rebuild of core with `ha core rebuild` temporarily fixes it, but will return later on. I have no clue what else to report that could help you/me track this down. 

arch: amd64
channel: stable
hassos: null
homeassistant: 0.108.2
hostname: adriaan
logging: info
machine: qemux86-64
supervisor: "214"
supported_arch:
- amd64
- i386
timezone: Europe/Amsterdam

**Comment by ludeeus** [comment]
Duplicate of #1576
