### ISSUE TITLE
Error adding custom repository: (OpenSSL SSL_read: Operation timed out)

### ISSUE THREAD

**Issue by NapalmCandy** [home-assistant/supervisor#1654]
Hi, when I try to add a new repository ( https://github.com/sabeechen/hassio-google-drive-backup ) it don't add. I was able to add it months ago, and most users I ask they can add until now without any problem.

The supervisor->system->log show that:

```
20-04-11 11:52:12 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-04-11 11:55:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-04-11 11:55:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-04-11 11:55:54 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/cebe7a76/repository.json: [Errno 2] No such file or directory: '/data/addons/git/cebe7a76/repository.json'
20-04-11 11:55:54 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/cebe7a76/repository.json
20-04-11 11:55:54 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-04-11 12:02:30 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
error: RPC failed; curl 56 OpenSSL SSL_read: Operation timed out
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
'.
20-04-11 12:02:30 ERROR (MainThread) [supervisor.store] Can't load from repository https://github.com/sabeechen/hassio-google-drive-backup
20-04-11 12:02:30 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
```

I am using home assistant 108.2 and supervisor 214, but it is a problem that I have a month ago, I updated homeassistan many times since this. I am running in a RaspberryPi4 in a docker raspbian.

Can you help me? 
Thanks.

**Comment by ludeeus** [comment]
This works for me, "Operation timed out" points to a network issue, try rebooting your host.

**Comment by NapalmCandy** [comment]
I had this problem since a month ago. I updated several times Home Assistant, it implies a lot of rebootings.

**Comment by ludeeus** [comment]
Try running `ha su repair`, then adding it again.

**Comment by NapalmCandy** [comment]
`ha su repair` do not found the order
`hassio su repair` do not found the order

**Comment by ludeeus** [comment]
> do not found the order

What do you mean with that?

Is this a HAOS installation or did you use the alternative generic Linux script to install?

**Comment by NapalmCandy** [comment]
I put the command on the Terminal (I am using Raspbian), after I installed Terminal & SSH add-on, and put the command there, it say Processing... Done.

And that is what say on the supervisor log

`20-04-12 08:23:52 INFO (MainThread) [supervisor.api.security] /supervisor/repair access from core_ssh
20-04-12 08:23:52 INFO (MainThread) [supervisor.core] Start repairing of Supervisor Environment
20-04-12 08:23:52 INFO (SyncWorker_18) [supervisor.docker] Prune stale containers
20-04-12 08:23:52 INFO (SyncWorker_18) [supervisor.docker] Prune stale images
20-04-12 08:23:56 INFO (SyncWorker_18) [supervisor.docker] Prune stale builds
20-04-12 08:23:56 INFO (SyncWorker_18) [supervisor.docker] Prune stale volumes
20-04-12 08:23:56 INFO (SyncWorker_18) [supervisor.docker] Prune stale networks
20-04-12 08:23:56 INFO (MainThread) [supervisor.plugins.cli] Repair HA cli 25
20-04-12 08:23:56 INFO (SyncWorker_12) [supervisor.docker.interface] Pull image homeassistant/armv7-hassio-cli tag 25.
20-04-12 08:23:58 INFO (SyncWorker_12) [supervisor.docker.interface] Tag image homeassistant/armv7-hassio-cli with version 25 as latest
20-04-12 08:23:58 INFO (MainThread) [supervisor.addons] Found 1 add-ons to repair
20-04-12 08:23:58 INFO (MainThread) [supervisor.addons] Start repair for add-on: core_deconz
20-04-12 08:23:58 INFO (SyncWorker_14) [supervisor.docker.interface] Pull image homeassistant/armhf-addon-deconz tag 5.3.2.
20-04-12 08:24:28 INFO (MainThread) [supervisor.supervisor] Repair Supervisor 216
20-04-12 08:24:28 INFO (MainThread) [supervisor.core] Finished repairing of Supervisor Environment
20-04-12 08:28:17 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-04-12 08:38:34 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
error: RPC failed; curl 56 OpenSSL SSL_read: Operation timed out
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
'.
20-04-12 08:38:34 ERROR (MainThread) [supervisor.store] Can't load from repository https://github.com/sabeechen/hassio-google-drive-backup
20-04-12 08:38:34 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove`

**Comment by ludeeus** [comment]
Run the installation process again.
https://www.home-assistant.io/hassio/installation/#preparation

**Comment by NapalmCandy** [comment]
It will delete my configuration?

**Comment by ludeeus** [comment]
no, but you should always take a snapshot and copy that off the device when making changes to your installation.

**Comment by NapalmCandy** [comment]
Again, same problem. Where I am supposed to put the commands? I put on the terminal.
```
pi@raspberrypi:~ $ sudo add-apt-repository universe
sudo: add-apt-repository: command not found
```

**Comment by pvizeli** [comment]
```
20-04-12 08:38:34 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
error: RPC failed; curl 56 OpenSSL SSL_read: Operation timed out
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
'.
```

I bet it's your firewall/modem. `Operation timed out` means someone/something hard drop the connection. Is also possible that it is an Kernel issue. Also possible but very odds, an Hardware issue.

**Comment by NapalmCandy** [comment]
Ok, I did it, but the problem is still same. When I try to add the repository:

```20-04-12 09:36:53 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-04-12 09:47:11 ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/sabeechen/hassio-google-drive-backup repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/sabeechen/hassio-google-drive-backup /data/addons/git/cebe7a76
  stderr: 'Cloning into '/data/addons/git/cebe7a76'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
error: RPC failed; curl 56 OpenSSL SSL_read: Operation timed out
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
'.
20-04-12 09:47:11 ERROR (MainThread) [supervisor.store] Can't load from repository https://github.com/sabeechen/hassio-google-drive-backup
20-04-12 09:47:11 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove```

**Comment by ludeeus** [comment]
Might be a firewall issue, or HW as @pvizeli said, try another SD card.

**Comment by NapalmCandy** [comment]
I have not a firewall, during this time lapse I do a reset factory to the ISP router (for other reasons) and do not solve the problem.

So, ok, I will try a new SD card
