### ISSUE TITLE
ERROR (MainThread) [supervisor.utils.gdbus] Can't parse '[[["dev-zram1.device", "/dev/zram1"....

### ISSUE THREAD

**Issue by ster1um** [home-assistant/supervisor#1657]
arch | aarch64
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 5.5.0-rc6-aml-s9xxx
python_version | 3.7.7
timezone | Europe/Rome
version | 0.108.3
virtualenv | false

I don't understand where is the error.

Link to pastebin log
https://pastebin.com/eYBPWbYQ

**Comment by Funcy-dcm** [comment]
I have the same error

**Comment by ifol** [comment]
same here, any way to troubleshoot and find out where the problem is?

**Comment by ifol** [comment]
It seems the JSON syntax is broken:

> Expecting ',' delimiter: line 1 column 25347 (char 25346)

I've put it into a JSON validator and this is the part that causes a problem:

`["rng-tools.service", "Add entropy to /dev/random "s pool a hardware RNG\", "loaded', "active", "running", "", "/org/freedesktop/systemd1/unit/rng_2dtools_2eservice", 0, "", "/"]`

You can see there is an unescaped " ("s) inside the second string but I've no idea where this JSON comes from or what causes it to have broken syntax so don't know where to fix.

**Comment by g5pw** [comment]
Apparently that string is in the description of the `rig-tools.service` systemD unit. You can find it (and maybe edit it) here `/lib/systemd/system/rng-tools.service`.

**Comment by KKnishev** [comment]
Yes, remove extra **'** in description and parsing working well:
Description=Add entropy to /dev/random 's pool a hardware RNG
