### ISSUE TITLE
Supervisor 214 not update to 217

### ISSUE THREAD

**Issue by martusi61** [home-assistant/supervisor#1658]
I have Home Assistant 108.3 with Supervisor 214 in the Docker container on Armbian S.O.

My error in log is:
20-04-13 07:38:41 ERROR (MainThread) [asyncio] Task was destroyed but it is pending!
task: <Task pending coro=<Core.start() running at /usr/src/supervisor/supervisor/core.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xffffb46992d0>()]>>
[cont-finish.d] executing container finish scripts

During the update of supervisor 214 to 217, after the pull I get an error that ends the script, then the supervisor restarts and starts the cycle again. I tried to delete container and image 214 by recreating the 217, but at the start of this I get errors on the "multicast" (????), the same with the 215. Before this update my home automation system worked perfectly!

**Comment by martusi61** [comment]
I have update, to HA 0.108.4 and Supervisor 217, but now i have the error:

20-04-16 01:49:29 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'
20-04-16 01:49:29 WARNING (MainThread) [supervisor.plugins.multicast] Error on install Multicast plugin. Retry in 30sec
20-04-16 01:49:59 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json

I tryed many things but no solution, i have my domotic system down!!!

**Comment by pvizeli** [comment]
> Can't process version data: 'aarch64'

Means, you system is wrong setup. If you feel that you want stay strong with a working system, take a supported Hardware and Image with our OS, and you don't need warry about this.

**Comment by martusi61** [comment]
I have been using the system for months, however I solved it, with a pull I added the aarch64 image of the multicast, at the restart of the Supervisor he himself created the container and now it works.  I just wonder why the pull isn't done automatically.

**Comment by jpoon** [comment]
Had to do the same. On upgrading to the latest supervisor, 

```
20-08-16 21:33:24 INFO (MainThread) [supervisor.plugins.multicast] No Multicast plugin Docker image homeassistant/armv7-hassio-multicast found.
20-08-16 21:33:24 INFO (MainThread) [supervisor.plugins.multicast] Setup Multicast plugin
20-08-16 21:33:24 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-08-16 21:33:24 WARNING (MainThread) [supervisor.updater] Can't process version data: 'null'
20-08-16 21:33:24 WARNING (MainThread) [supervisor.plugins.multicast] Error on install Multicast plugin. Retry in 30sec
```

Figured out what the current tags and versions are from https://version.home-assistant.io/stable.json, and pulled the respective docker images down manually.

```
docker pull homeassistant/armv7-hassio-multicast:2
```

and then restarted the supervisor container.
