### ISSUE TITLE
Can you fix flux_led please?

### ISSUE THREAD

**Issue by andymarden** [home-assistant/supervisor#1677]
Running 0.108.6 on docker on raspi 4. There is a known problem controlling magichome rgbw/rgbww controllers resulting in some bizarre behaviour. It was rolled back last year - I assume you have the latest version but the issues persist.

**Comment by frenck** [comment]
Hi there @andymarden! Thanks for opening an issue.

This is the issue tracker for the supervisor. If you have issues with a Home Assistant integration, please open an issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
