### ISSUE TITLE
Update to downgrade

### ISSUE THREAD

**Issue by djpremier** [home-assistant/supervisor#1681]
**Home Assistant release with the issue:**

0.109.0b1

**Operating environment (HassOS/Generic):**

Manjaro ARM (aarch64)

**Supervisor logs:**

**Description of problem:**
If you are in the beta channel and a version is released for the stable channel, the Supervisor displays the card to update to that version (which is "earlier" than the beta). And it is also possible to perform the update operation (which in this case is a downgrade).

![downgrade_hassio](https://user-images.githubusercontent.com/17091381/80257732-f8a41100-8657-11ea-9bbd-e7c576328c29.png)

**Comment by frenck** [comment]
Yes, this was expected.
Normally we don't ship new patch releases during the beta, however, this time there was an issue that needed a patch release.

A new beta has been tagged, so this should be resolved within 2 hours.
