### ISSUE TITLE
hassio_dns don't use adguard dns server

### ISSUE THREAD

**Issue by centralhardware** [home-assistant/supervisor#1683]
**Home Assistant release with the issue:**
0.108.9

**Operating environment (HassOS/Generic):**
hassio 219
ubuntu 20.04

**Description of problem:**
hassio dns is ignoring running adguard dns server. I try to restart hassio_dns and home assistant containers, but hassio_dns still accessing dns server unknown to me (tcpdump showed that used dns.google). I don't see no one request from locahost in adqurd home query log. the dns server for sure working, i use it as dns server in my local network and all work, but not for hassio.

**Comment by frenck** [comment]
The Home Assistant DNS server can be configured using the `ha dns` command, (`ha dns --help`).

This allows you to set your own upstream DNS servers for the internal DNS of Home Assistant.

Please note, if you are using the AdGuard add-on, this is not recommended. As the risks are the add-on is down/restarting/not-started yet when parts of the system already rely on it.

**Comment by centralhardware** [comment]
in, case adguard dns server. it was necessary to add 127.0.0.1 to the /etc/resolve.conf (hassio_dns load nameservers from this file and use as upstream dns server), but if i add this address via `ha dns options --servers dns://127.0.0.1`, loop detection will alert and roll back settings.

**Comment by frenck** [comment]
Yes, 127.0.0.1 via the DNS options will point to itself. The Home Assistant DNS server is an isolated container, pointing the Home Assistant DNS to 127.0.0.1 makes it point to itself, thus a loop.
