### ISSUE TITLE
Stuck figuring out proper hassio-builder command

### ISSUE THREAD

**Issue by RonSpawnson** [home-assistant/supervisor#1685]
I'm attempting to follow the README. The process in general makes sense (build image, tag it, and restart things). But I'm stuck on step 1: building. All the doc says is "You can use the builder to build your supervisor: https://github.com/home-assistant/hassio-builder". When I go to this link, I try to put forth a run command based on it's README, and it's not working.

Command I attempted:
```docker run --rm --privileged -v ~/.docker:/root/.docker -v /my_addon:/data homeassistant/armv7-builder --armv7 -t /data```

Output I see:
```
{...}
INFO: Runn addon build for: armv7
jq: error: Could not open file /data/config.json: No such file or directory
```

Any tips on how I can properly build supervisor with hassio-builder as per step 1 of README?

**Comment by pvizeli** [comment]
https://github.com/home-assistant/supervisor/blob/dev/azure-pipelines-release.yml
