### ISSUE TITLE
Refresh button missing

### ISSUE THREAD

**Issue by Oohcalme** [home-assistant/supervisor#1695]
**Home Assistant release with the issue:**
Home Assistant 0.109.3

**Operating environment (HassOS/Generic):**
HassOS

**Supervisor logs:**
no logs

**Description of problem:**
The Refresh icon has disappeared with the Supervisor 220.
I can't update the snapshots list or the addons list

Thanks for checking

**Comment by frenck** [comment]
This is a known issue and has been fixed in our frontend.
Closing this issue as the reported issue has been resolved on dev and will be in the next supervisor release.

For now, you can use `ha addons reload` in the terminal as a workaround.

**Comment by Oohcalme** [comment]
great thanks.
I tried to see if the issue was already discussed but I didn't find it.
I'll use the workaround thanks
