### ISSUE TITLE
Items missing on Addon page after upgrade to 109.6

### ISSUE THREAD

**Issue by nickidw** [home-assistant/supervisor#1713]
**Home Assistant release with the issue:**

109.6
**Operating environment (HassOS/Generic):**

HassOS on Rpi2

**Supervisor logs:**

**Description of problem:**
The Addon detail page (when clicking on an installed addon in Supervisor main page) no longer displays the back button arrow near the top left, as well as the green or orange icon indicating whether the addon is up to date or not. The area of the back button arrow is still clickable and the navigation works correctly.
![image](https://user-images.githubusercontent.com/12016514/81419020-ddec9480-914d-11ea-84ba-38113a789551.png)

**Comment by frenck** [comment]
Fixed in Supervisor 222, please update your Supervisor.
