### ISSUE TITLE
Random crashes. Error handling request.   -->   _calc_block_io

### ISSUE THREAD

**Issue by elcesar-github** [home-assistant/supervisor#1714]
**Home Assistant release with the issue:**
221

0.109.6

**Operating environment (HassOS/Generic):**

HASSIO completely update. Running in VirtualBox with a pass through for the CC2531 for zigbee2mqtt

**Supervisor logs:**

ERROR (MainThread) [aiohttp.server] Error handling request
[..] 
[..]
File "/usr/src/supervisor/supervisor/docker/stats.py", line 63, in _calc_block_io
   for stats in blkio["io_service_bytes_recursive"]:
TypeError: 'NoneType' object is not iterable

**Description of problem:**
I have been experiencing random reboots or hangs. Webinterface and ssh complete unresponsive (connection rejected)
 I managed to get the logs from the VirtualBox Console

**Comment by pvizeli** [comment]
I can guard the request but that solves not the issue. I see a possible solution, try to run OS 4.6 - or virtual box is not able to run the appliance stable on your host

**Comment by elcesar-github** [comment]
I have been running HASSIO on that machine for a couple months with no stability issues.  My first though, due to the  error message was that it was a bug in the supervisor. Other virtual machines or services on the hosts are not being affected as for now.

**Comment by pvizeli** [comment]
Can you update to OS 4.6 ?

**Comment by elcesar-github** [comment]
Sure. I can take snapshots on the VM so I'm willing to try anything that may also help on the development. I Just need to learn how, because it's not showing in the interface right now.  Current version running is 3.13 if that helps for anything.

**Comment by elcesar-github** [comment]
I have updated to OS 4.6. Seems much more stable and the kind of crash I experienced have not happened in the last 48 hours with the same configurations (Before it was about 2-3 times a day )

I would say that the issue is solved. Thanks

**Comment by frenck** [comment]
Great to hear! Thanks for letting us know @elcesar-github 👍
