### ISSUE TITLE
Lack of 'ndots' option prevents local hostname resolution.

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/supervisor#1715]
Two out of five containers cannot resolve local hostnames. Both containers lacks the `ndots` option in `/etc/resolv.conf`.

This negatively affects integrations that connect to local hosts by name. For example, the Emby integration fails to connect if the Emby server's hostname is used (but it works if the server's IP address is specified).

NOTE:
I don't know if this is the correct repo to post this Issue. The issue involves the configuration of name resolution in two containers (but neither of them is `hassio_supervisor`). If required, please forward this Issue to the correct repo or let me know where I should re-post it.

**Home Assistant release with the issue:**
 Home Assistant Supervised 0.109.6 (and all versions since I first installed 0.109.0).

**Operating environment (HassOS/Generic):**
 Ubuntu 18.04

**Supervisor logs:**

**Description of problem:**

Within the `homeassistant` and `hassio_multicast` containers, pinging a local hostname does not work (pinging by the host's IP address does work). The two containers fail to resolve local hostnames.

In contrast, these three containers know how to resolve local hostnames:
```shell
hassio_supervisor
hassio_dns
hassio_cli
```
The principal difference between the three successful containers and the two unsuccessful containers is that their `/etc/resolv.conf` file contains the `ndots` option:
```shell
options ndots:0
```
As an experiment, I added the option to `etc/resolv.conf` in the `homeassistant` container and it was immediately able to ping a local host by its name.
```shell
bash-5.0# ping io
PING io (192.168.1.5): 56 data bytes
64 bytes from 192.168.1.5: seq=0 ttl=128 time=0.541 ms
64 bytes from 192.168.1.5: seq=1 ttl=128 time=0.487 ms
64 bytes from 192.168.1.5: seq=2 ttl=128 time=0.625 ms
^C
--- io ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.487/0.551/0.625 ms
```
Additional information about how I discovered this issue can be found here:
https://community.home-assistant.io/t/emby-integration-unable-to-connect-to-server/193747/6?u=123

**Comment by pvizeli** [comment]
we support mdns or split dns, what you try to archive is not supported, please use Home Assistant Core.

**Comment by tdejneka** [comment]
> please use Home Assistant Core.

That is an unexpected response so I assume there must have been miscommunication of the issue.

I am using one of several integrations that connect to a local server. When configuring the integration, you can identify the local server by its hostname or IP address.

For example, here is the configuration for the Emby integration:
```yaml
media_player:
  - platform: emby
    host: io
    api_key: !secret emby_key
```
This fails to work when using Home Assistant Supervised because, from within the `homeassistant` container, the hostname `io` cannot be resolved to its local IP address. In other words, `ping io` does not work.

However, this does work:
`ping io.local`

It means it can only resolve _fully_-qualified names, like `io.local`, and not unqualified ones like just `io`. 

The way I "fixed" this is by adding `options ndots:0` to `/etc/resolv.conf` in the `homeassistant` container (just like it's done in the other three containers). Perhaps this is not the optimal solution but it does make Home Assistant Supervised behave like Home Assistant Core (venv or docker) and allows the user to specify an unqualified hostname.

Can you explain another way of getting Home Assistant Supervised to resolve unqualified hostnames?
