### ISSUE TITLE
Unable to install/update addons

### ISSUE THREAD

**Issue by Gooman-rus** [home-assistant/supervisor#1730]
**Home Assistant release with the issue:** 0.109.6

**Operating environment (HassOS/Generic):** HassOS, Raspberry Pi 3+ (32 bit)

**Supervisor logs:**

20-05-20 06:55:27 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/806b11b5_zigbee2mqttassistant
20-05-20 06:55:27 INFO (SyncWorker_6) [supervisor.docker.interface] Pull image carldebilly/zigbee2mqttassistant tag 0.3.157.
20-05-20 06:55:37 ERROR (SyncWorker_6) [supervisor.docker.interface] Can't install carldebilly/zigbee2mqttassistant:0.3.157 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.22.1:53: read udp 192.168.22.39:42858->192.168.22.1:53: i/o timeout").

20-05-20 06:56:29 INFO (SyncWorker_7) [supervisor.docker.interface] Update image homeassistant/armv7-addon-mariadb:1.3 to homeassistant/armv7-addon-mariadb:2.1.2
20-05-20 06:56:29 INFO (SyncWorker_7) [supervisor.docker.interface] Pull image homeassistant/armv7-addon-mariadb tag 2.1.2.
20-05-20 06:56:39 ERROR (SyncWorker_7) [supervisor.docker.interface] Can't install homeassistant/armv7-addon-mariadb:2.1.2 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.22.1:53: read udp 192.168.22.39:41267->192.168.22.1:53: i/o timeout").

**Description of problem:**
I'm trying to install or update addons (custom zigbee2mqtt-assistant and official MariaDB) and it is not installing/updating (see the errors in the logs).
Reinstalling addon does not solve the problem. Restarting hassio too.
192.168.22.1 - IP of my home router.
192.168.22.39 - IP of RaspberryPi with homeassistant.
I think that this problem affects all of the addons. I just don't want to uninstall them all to check this because I can't install them back.

**Comment by frenck** [comment]
This indicates a DNS issue with your network.
Do you have to installed AdGuard, Pi-hole or DNSMasq add-ons?

**Comment by Gooman-rus** [comment]
I have no any of these addons installed.

Text from the SSH terminal on raspberrypi with HA (DNS lookup is working):
```
~ $ ping google.com
PING google.com (216.58.204.142): 56 data bytes
64 bytes from 216.58.204.142: seq=0 ttl=51 time=87.380 ms
64 bytes from 216.58.204.142: seq=1 ttl=51 time=87.078 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 87.078/87.229/87.380 ms

~ $ ping registry-1.docker.io
PING registry-1.docker.io (3.211.199.249): 56 data bytes
^C
--- registry-1.docker.io ping statistics ---
25 packets transmitted, 0 packets received, 100% packet loss
```
I don't know if registry-1.docker.io can be pinged (maybe it is forbidden via their firewall).

**Comment by frenck** [comment]
Pinging is not the issue in your given logs, resolving is. Could you try a nslookup?

**Comment by Gooman-rus** [comment]
```
~ $ nslookup registry-1.docker.io
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   registry-1.docker.io
Address: 52.4.20.24
Name:   registry-1.docker.io
Address: 52.72.232.213
Name:   registry-1.docker.io
Address: 52.54.232.21
Name:   registry-1.docker.io
Address: 52.5.11.128
Name:   registry-1.docker.io
Address: 54.236.131.166
Name:   registry-1.docker.io
Address: 100.26.63.49
Name:   registry-1.docker.io
Address: 107.23.149.57
Name:   registry-1.docker.io
Address: 54.85.107.53

~ $ nslookup google.com
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   google.com
Address: 216.58.204.142
Name:   google.com
Address: 2a00:1450:4007:812::200e
```

**Comment by frenck** [comment]
That looks good, which is kinda expected, because, inside an add-on, it leverages the Home Assistant DNS service, which can fall back in case of problems. However, the host operating system cannot do that.

`192.168.22.1:53`, seems to be your router that didn't respond to the DNS query. I really hate to say this, but there is not much I can do to help with this, as in, it really seems a DNS issue on your network.

**Comment by Gooman-rus** [comment]
Disabling OpenVPN on my router during the addon update/install solved the problem. Very strange sutiation because I am using OpenVPN for more than 6 months.
