### ISSUE TITLE
home assistant supervisor not starting unable to open /init for reading: Permission denied

### ISSUE THREAD

**Issue by sepulworld** [home-assistant/supervisor#1748]
**Home Assistant release with the issue:**
homeassistant/amd64-hassio-supervisor    latest              cc95bc93e76b        17 hours ago        366MB
homeassistant/amd64-hassio-supervisor    224                 5e10a3f3e0eb        37 hours ago        366MB

**Operating environment (HassOS/Generic):**

Ubuntu 20.04

**Supervisor logs:**

May 24 04:01:26 mydomain systemd[1]: Starting Hass.io supervisor...
May 24 04:01:26 mydomain docker[212255]: hassio_supervisor
May 24 04:01:26 mydomain systemd[1]: Started Hass.io supervisor.
May 24 04:01:27 mydomain hassio-supervisor[212361]: execlineb: fatal: unable to open /init for reading: Permission denied

**Description of problem:**

Home Assistant Supervisor not starting

homeassistant/amd64-hassio-supervisor    latest              cc95bc93e76b        17 hours ago        366MB
homeassistant/amd64-hassio-supervisor    224                 5e10a3f3e0eb        37 hours ago        366MB

**Comment by sepulworld** [comment]
Im a beta user, looks like I'm using the latest Docker image. Perhaps there is a file permission issue with /init within the container that was recently changed?

**Comment by sepulworld** [comment]
I think I found the issue in `dmesg` It appears apparmor is blocking entrypoint script

```
[  105.750615] audit: type=1400 audit(1590294683.655:504): apparmor="DENIED" operation="open" profile="snap.docker.dockerd" name="/init" pid=21241 comm="init" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[  105.761139] audit: type=1400 audit(1590294683.667:505): apparmor="DENIED" operation="ptrace" profile="snap.docker.dockerd" pid=21276 comm="runc" requested_mask="read" denied_mask="read" peer="hassio-supervisor"
[  105.761204] audit: type=1400 audit(1590294683.667:506): apparmor="DENIED" operation="ptrace" profile="snap.docker.dockerd" pid=21276 comm="runc" requested_mask="read" denied_mask="read" peer="hassio-supervisor"
```

Not sure how to get around this yet.

**Comment by sepulworld** [comment]
This appears to be a problem with Snap's setup of Docker. Im going to remove Snap and go with Docker apt package.

**Comment by niemyjski** [comment]
I'm also running into this with snap on ubuntu 20 as of the latest supervisor update. @sepulworld can you please reopen this.

**Comment by frenck** [comment]
Running Docker snap is not going to work. You need Docker CE and install it according to the Docker.com website.

**Comment by sepulworld** [comment]
Yeah, this is a lame Ubuntu problem. Basically, during the OS install of the server if you ask to pre-install “Docker” it will do it through the Snap package manager and the Snap Docker packer is depreciated / no longer supported.  Best to install it via apt. ‘apt install docker.io’

**Comment by frenck** [comment]
`apt install docker.io` isn't correct either.

Please use Docker CE according to the instructions on the Docker.com website.

**Comment by sepulworld** [comment]
Good to know! Here is the link on their site for Ubuntu. 

https://docs.docker.com/engine/install/ubuntu/
