### ISSUE TITLE
supervisor thinks 0.110.4 is older than 0.110.3?

### ISSUE THREAD

**Issue by xcray** [home-assistant/supervisor#1760]
**Home Assistant release with the issue:**

0.110.4
**Operating environment (HassOS/Generic):**

hassos
**Supervisor logs:**

20-05-30 07:32:33 WARNING (MainThread) [supervisor.homeassistant] Version 0.110.3 is already installed
20-05-30 07:34:19 INFO (MainThread) [supervisor.homeassistant] Update Home Assistant to version 0.110.4
20-05-30 07:34:19 INFO (SyncWorker_8) [supervisor.docker.interface] Update image homeassistant/qemux86-64-homeassistant:0.110.3 to homeassistant/qemux86-64-homeassistant:0.110.4
20-05-30 07:34:19 INFO (SyncWorker_8) [supervisor.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.110.4.
20-05-30 07:35:33 ERROR (SyncWorker_8) [supervisor.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.110.4 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/homeassistant/qemux86-64-homeassistant/manifests/0.110.4: Get https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Fqemux86-64-homeassistant%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)").
20-05-30 07:35:33 WARNING (MainThread) [supervisor.homeassistant] Update Home Assistant image fails
20-05-30 07:38:05 INFO (SyncWorker_1) [supervisor.docker] Run command 'python3 -m homeassistant -c /config --script check_config' on homeassistant/qemux86-64-homeassistant
20-05-30 07:38:59 INFO (MainThread) [supervisor.homeassistant] Home Assistant config is valid
20-05-30 07:39:54 INFO (MainThread) [supervisor.homeassistant] Update Home Assistant to version 0.110.4
20-05-30 07:39:54 INFO (SyncWorker_0) [supervisor.docker.interface] Update image homeassistant/qemux86-64-homeassistant:0.110.3 to homeassistant/qemux86-64-homeassistant:0.110.4
20-05-30 07:39:54 INFO (SyncWorker_0) [supervisor.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.110.4.
20-05-30 07:41:07 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.110.4 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/homeassistant/qemux86-64-homeassistant/manifests/0.110.4: Get https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Fqemux86-64-homeassistant%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)").
20-05-30 07:41:07 WARNING (MainThread) [supervisor.homeassistant] Update Home Assistant image fails
20-05-30 07:42:01 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-05-30 07:48:31 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-05-30 08:11:35 INFO (MainThread) [supervisor.homeassistant] Update Home Assistant to version 0.110.4
20-05-30 08:11:35 INFO (SyncWorker_2) [supervisor.docker.interface] Update image homeassistant/qemux86-64-homeassistant:0.110.3 to homeassistant/qemux86-64-homeassistant:0.110.4
20-05-30 08:11:35 INFO (SyncWorker_2) [supervisor.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.110.4.
20-05-30 08:12:06 INFO (SyncWorker_2) [supervisor.docker.interface] Stop homeassistant application
20-05-30 08:12:14 INFO (SyncWorker_2) [supervisor.docker.interface] Clean homeassistant application
20-05-30 08:12:28 INFO (MainThread) [supervisor.homeassistant] Update pulse/client.config: /data/tmp/homeassistant_pulse
20-05-30 08:12:33 INFO (SyncWorker_0) [supervisor.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.110.4
20-05-30 08:13:18 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-05-30 08:13:18 INFO (MainThread) [supervisor.homeassistant] Successful run Home Assistant 0.110.4
20-05-30 08:13:18 INFO (SyncWorker_3) [supervisor.docker.interface] Cleanup images: ['homeassistant/qemux86-64-homeassistant:0.110.3']
20-05-30 08:14:38 INFO (SyncWorker_4) [supervisor.docker.interface] Restart homeassistant/qemux86-64-homeassistant
20-05-30 08:15:27 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance

**Description of problem:**
1. This morning, the updater sensor says new version of 0.110.4 is available already, but I can't see it on the dashboard.
2. Then I'd tried to download the image manually and force to update by cmd ha core update --version=0.110.4, it got success.
3. Then dashboard says there is a new verion 0.110.3, and ask me to "upgrade"

**Comment by frenck** [comment]
0.110.4 wasn't published for the Supervisor platform when you created this issue. I've just published it, so if you go to the supervisor panel -> system tab -> reload, that should do the trick.

**Comment by xcray** [comment]
Got it！
Thanks for your comment. @frenck
