### ISSUE TITLE
upgrade to supervisor 227 returns a error

### ISSUE THREAD

**Issue by elgrande007** [home-assistant/supervisor#1779]
**Home Assistant release with the issue:**
currently runing 226 want to upgrade to 227 returns a Error: Unknown Error, see logs

**Operating environment (HassOS/Generic):**

Hostname | homeassistant
-- | --
System | HassOS 4.8
Deployment | production

**Supervisor logs:**
```log
20-06-04 15:37:29 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install homeassistant/aarch64-hassio-supervisor:227 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)").
20-06-04 15:37:29 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor fails!
```

If I follow the url to the dokcer registry i get a: 
```
0 |  
code | "UNAUTHORIZED"
message | "authentication required"
detail | null
```

**Description of problem:**

**Comment by balloob** [comment]
That's probably a hiccup on Docker. Can you try again? And where in the world are you located? Docker sometimes has issues spreading the image over the CDN fast enough.

**Comment by elgrande007** [comment]
I tried a couple of times and it seems to be solved. so yeah I think I was to fast ;)
