### ISSUE TITLE
Update available Operating System 3.13 but its a downgrade (4.8 installed)

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [home-assistant/supervisor#1781]
**Home Assistant release with the issue:**
Home Assistant 0.110.4

**Operating environment (HassOS/Generic):**
HassOS 4.8
RaspberryPi 3B+

**Supervisor logs:**
20-06-04 13:33:55 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: de.pengutronix.rauc - /
20-06-04 13:33:55 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
20-06-04 13:33:55 INFO (MainThread) [supervisor.host.info] Update local host information
20-06-04 13:33:55 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-06-04 13:33:55 INFO (MainThread) [supervisor.host.services] Update service information
20-06-04 13:33:55 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-06-04 13:33:55 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-06-04 13:33:55 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-06-04 13:33:55 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-06-04 13:33:55 INFO (MainThread) [supervisor.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-06-04 13:33:55 INFO (MainThread) [supervisor.host.services] Reload local service hassos-apparmor.service
20-06-04 13:33:55 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-06-04 13:33:55 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/armv7-hassio-dns with version 9
20-06-04 13:33:56 INFO (MainThread) [supervisor.plugins.dns] Restart CoreDNS plugin
20-06-04 13:33:56 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-06-04 13:33:56 INFO (SyncWorker_3) [supervisor.docker.interface] Restart homeassistant/armv7-hassio-dns
20-06-04 13:34:01 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
20-06-04 13:34:01 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/armv7-hassio-audio with version 14
20-06-04 13:34:01 INFO (SyncWorker_2) [supervisor.docker.interface] Attach to homeassistant/armv7-hassio-cli with version 25
20-06-04 13:34:01 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/armv7-hassio-multicast with version 2
20-06-04 13:34:01 INFO (MainThread) [supervisor.plugins.multicast] Restart Multicast plugin
20-06-04 13:34:01 INFO (SyncWorker_12) [supervisor.docker.interface] Restart homeassistant/armv7-hassio-multicast
20-06-04 13:34:05 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-06-04 13:34:06 INFO (SyncWorker_3) [supervisor.docker.interface] Attach to homeassistant/raspberrypi3-homeassistant with version 0.110.4
20-06-04 13:34:06 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /
20-06-04 13:34:06 INFO (MainThread) [supervisor.hassos] Detect HassOS 4.8 / BootSlot A
20-06-04 13:34:07 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/kanboard/config.json: required key not provided @ data['arch']. Got None
20-06-04 13:34:07 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/mopidy_alpine/config.json: required key not provided @ data['arch']. Got None
20-06-04 13:34:07 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/snapcastserver/config.json: required key not provided @ data['arch']. Got None
20-06-04 13:34:07 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/nextcloud/config.json: required key not provided @ data['arch']. Got None
20-06-04 13:34:07 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-06-04 13:34:07 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/53caca22 repository
20-06-04 13:34:07 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-06-04 13:34:07 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/15ef4d2f repository
20-06-04 13:34:08 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/kanboard/config.json: required key not provided @ data['arch']. Got None
20-06-04 13:34:08 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/mopidy_alpine/config.json: required key not provided @ data['arch']. Got None
20-06-04 13:34:08 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/snapcastserver/config.json: required key not provided @ data['arch']. Got None
20-06-04 13:34:08 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/nextcloud/config.json: required key not provided @ data['arch']. Got None
20-06-04 13:34:08 INFO (MainThread) [supervisor.store] Load add-ons from store: 84 all - 84 new - 0 remove
20-06-04 13:34:08 INFO (MainThread) [supervisor.addons] Found 10 installed add-ons
20-06-04 13:34:08 INFO (SyncWorker_14) [supervisor.docker.interface] Attach to hassioaddons/adb-armv7 with version 0.6.2
20-06-04 13:34:08 INFO (SyncWorker_6) [supervisor.docker.interface] Attach to homeassistant/armv7-addon-configurator with version 5.0.0
20-06-04 13:34:08 INFO (SyncWorker_8) [supervisor.docker.interface] Attach to hassioaddons/sonweb-armv7 with version 0.11.0
20-06-04 13:34:08 INFO (SyncWorker_2) [supervisor.docker.interface] Attach to bestlibre/armv7-mopidy with version 0.2.7
20-06-04 13:34:08 INFO (SyncWorker_12) [supervisor.docker.interface] Attach to hassioaddons/appdaemon3-armv7 with version 5.0.1
20-06-04 13:34:08 INFO (SyncWorker_3) [supervisor.docker.interface] Attach to homeassistant/armv7-addon-mosquitto with version 5.1
20-06-04 13:34:08 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to homeassistant/armv7-addon-ssh with version 8.6.0
20-06-04 13:34:08 INFO (SyncWorker_5) [supervisor.docker.interface] Attach to bestlibre/armv7-caddy-proxy with version 1.0.4
20-06-04 13:34:08 INFO (SyncWorker_15) [supervisor.docker.interface] Attach to homeassistant/armv7-addon-samba with version 9.2.0
20-06-04 13:34:08 INFO (SyncWorker_11) [supervisor.docker.interface] Attach to esphome/esphome-hassio-armv7 with version 1.14.3
20-06-04 13:34:08 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files
20-06-04 13:34:08 INFO (MainThread) [supervisor.discovery] Load 1 messages
20-06-04 13:34:08 INFO (MainThread) [supervisor.ingress] Load 0 ingress session
20-06-04 13:34:08 INFO (MainThread) [supervisor.misc.secrets] Load Home Assistant secrets: 13
20-06-04 13:34:08 INFO (MainThread) [__main__] Run Supervisor
20-06-04 13:34:08 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-06-04 13:34:08 INFO (MainThread) [supervisor.utils.gdbus] Call de.pengutronix.rauc.Installer.Mark on /
20-06-04 13:34:08 INFO (MainThread) [supervisor.hassos] Rauc: A - marked slot kernel.0 as good
20-06-04 13:34:08 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' start 0 add-ons
20-06-04 13:34:08 INFO (MainThread) [supervisor.core] Supervisor reboot detected
20-06-04 13:34:08 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
20-06-04 13:34:08 INFO (MainThread) [supervisor.misc.hwmon] Started Supervisor hardware monitor
20-06-04 13:34:08 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-06-04 13:34:08 INFO (MainThread) [supervisor.host.info] Update local host information
20-06-04 13:34:08 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-06-04 13:34:08 INFO (MainThread) [supervisor.host.services] Update service information
20-06-04 13:34:08 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-06-04 13:34:09 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-06-04 13:34:09 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-06-04 13:34:09 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-06-04 13:34:09 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-06-04 13:34:09 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-06-04 13:34:09 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon3
20-06-04 13:34:09 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
20-06-04 14:04:12 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-06-04 14:34:13 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-06-04 15:04:15 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-06-04 15:34:08 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-06-04 15:34:15 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-06-04 15:40:48 INFO (MainThread) [supervisor.host.info] Update local host information
20-06-04 15:40:48 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-06-04 15:40:49 INFO (MainThread) [supervisor.host.services] Update service information
20-06-04 15:40:49 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-06-04 15:40:49 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-06-04 15:40:49 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-06-04 15:40:49 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-06-04 16:04:18 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-06-04 16:34:08 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-06-04 16:34:08 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/bestlibre/hassio-addons repository
20-06-04 16:34:08 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-06-04 16:34:08 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/hassio repository
20-06-04 16:34:10 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/kanboard/config.json: required key not provided @ data['arch']. Got None
20-06-04 16:34:10 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/mopidy_alpine/config.json: required key not provided @ data['arch']. Got None
20-06-04 16:34:10 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/snapcastserver/config.json: required key not provided @ data['arch']. Got None
20-06-04 16:34:10 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/nextcloud/config.json: required key not provided @ data['arch']. Got None
20-06-04 16:34:10 INFO (MainThread) [supervisor.store] Load add-ons from store: 84 all - 0 new - 0 remove
20-06-04 16:34:19 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token

**Description of problem:**
Supervisor Dashboard Shows:
"Update Available" 
Operating System 3.13
You are currently running version 4.8

**Comment by iyotee** [comment]
same here.

**Comment by tofuSCHNITZEL** [comment]
the issue is that (for whatever reason) 3.13 is present for rpi2 and rpi3 in
https://version.home-assistant.io/stable.json

**Comment by allanpersson** [comment]
Take a look at some of the other issues about the same "issue" here: https://github.com/home-assistant/operating-system/issues?q=is%3Aissue+is%3Aclosed

A downgrade is offered if a stable version is available and you are not part of the beta Channel 🙏

**Comment by tofuSCHNITZEL** [comment]
seems like an oversight to me since all other rpi plattforms got 4.8 and 4.9.

**Comment by tofuSCHNITZEL** [comment]
after digging through all of the issues that were just closed, I found one with a little bit more about the reason why some rpi plattforms were reverted to 3.13:

https://github.com/home-assistant/operating-system/issues/719
