### ISSUE TITLE
Ghost update 228 --> 227

### ISSUE THREAD

**Issue by PieBru** [home-assistant/supervisor#1789]
**Home Assistant release with the issue:** HassOS 4.10

```
arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant
os_name | Linux
os_version | 4.19.126-v8
python_version | 3.7.7
supervisor | 227
timezone | Europe/Rome
version | 0.111.1
virtualenv | false
```

BTW, the CLI command suggested in the issue template doesn't exist anymore, it should be `ha info` ;-)
```
 _    _                                         _     _              _
| |  | |                          /\           (_)   | |            | |
| |__| | ___  _ __ ___   ___     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_
|  __  |/ _ \| '_ ` _ \ / _ \   / /\ \ / __/ __| / __| __/ _` | '_ \| __|
| |  | | (_) | | | | | |  __/  / ____ \\__ \__ \ \__ \ || (_| | | | | |_
|_|  |_|\___/|_| |_| |_|\___| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|


Our command line:
$ ha help
➜  ~ hass --version
zsh: command not found: hass
➜  ~ 
➜  ~ ha info
arch: aarch64
channel: stable
docker: 19.03.8
hassos: "4.10"
homeassistant: 0.111.1
hostname: homeassistant
logging: info
machine: raspberrypi4-64
supervisor: "227"
supported_arch:
- aarch64
- armv7
- armhf
timezone: Europe/Rome
```

**Operating environment (HassOS/Generic):** HassOS

**Supervisor logs:** Lost

**Description of problem:**
Yesterday HassOS offered to update 227 to 228, and I did it.
Today it suggests to roll-back 228 to 227, as shown on the screenshots below.
Thank you for this awesome project!!!
Piero

![Screenshot from 2020-06-13 17-34-06](https://user-images.githubusercontent.com/6537434/84573096-c03eca80-ad9e-11ea-97f8-2b91d7f6172c.png)
![Screenshot from 2020-06-13 17-34-29](https://user-images.githubusercontent.com/6537434/84573099-c765d880-ad9e-11ea-95db-e038de944ca4.png)

**Comment by netcookies** [comment]
same issue here.

**Comment by mkanet** [comment]
Im still having this issue.  It keeps asking me to upgrade from Version 227 to 228 then back to 227.  Which version is the right version?

**Comment by blamaz** [comment]
I'm having the same issue

**Comment by mkanet** [comment]
I guess we'll have to wait for version 229 to stop this upgrade/downgrade loop.

**Comment by PieBru** [comment]
@mkanet Yes, but it may happen again until it will be resolved, or at least understood and bypassed.

When it happens to us (users), it would be useful to narrow it down and help the devs to reproduce it, thus saving their precious debug time.
Unfortunately, I'm not able to reproduce it now on my server :-(
