### ISSUE TITLE
Upgrading from homeassistant:0.111.0 to homeassistant:0.111.2 and failed

### ISSUE THREAD

**Issue by Caguillo** [home-assistant/supervisor#1790]
System INFO:
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant
os_name | Linux
os_version | 5.4.44
python_version | 3.7.7
supervisor | 227
timezone | Asia/Dubai
version | 0.111.0
virtualenv | false

**Description of problem:**

I am upgrading from homeassistant:0.111.0 to homeassistant:0.111.2 and failed.
the Logs are as follows.

20-06-14 04:33:11 INFO (SyncWorker_2) [supervisor.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.111.2.
20-06-14 04:38:30 ERROR (SyncWorker_2) [supervisor.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.111.2 -> 404 Client Error: Not Found ("no such image: homeassistant/qemux86-64-homeassistant:0.111.2: **No such image: homeassistant/qemux86-64-homeassistant:0.111.2").**
20-06-14 04:38:30 WARNING (MainThread) [supervisor.homeassistant] Update Home Assistant image fails
20-06-14 04:42:10 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token

**Comment by balloob** [comment]
Check your disk space.
