### ISSUE TITLE
Help me. Error on install CoreDNS plugin

### ISSUE THREAD

**Issue by levinetit** [home-assistant/supervisor#1794]
Hi

I encountered a problem when installing home assistant - supervisor installer, on a centos 8 docker - CE, the error is "WARNING (MainThread) [supervisor.plugins.dns] Error on install CoreDNS plugin. Retry in 30sec".

What would be the problem?

Help me.

**Comment by pvizeli** [comment]
Please read the specification of Supervisord: https://github.com/home-assistant/architecture/pull/394/files

**Comment by ENT108** [comment]
Check your system routing maybe.
