### ISSUE TITLE
WARNING (MainThread) [supervisor.addons.validate] Unknown options

### ISSUE THREAD

**Issue by MPJK77** [home-assistant/supervisor#1797]
At this moment I am on Hassio 0.111.4
I have these warnings for a very long time now but everything seems to work well?
What can be the problem? Where should I look or what do I need to correct?

20-06-18 21:37:55 WARNING (MainThread) [supervisor.addons.validate] Unknown options username
20-06-18 21:37:55 WARNING (MainThread) [supervisor.addons.validate] Unknown options password
20-06-18 21:37:55 WARNING (MainThread) [supervisor.addons.validate] Unknown options ssl
20-06-18 21:37:55 WARNING (MainThread) [supervisor.addons.validate] Unknown options certfile
20-06-18 21:37:55 WARNING (MainThread) [supervisor.addons.validate] Unknown options keyfile
20-06-18 21:37:55 WARNING (MainThread) [supervisor.addons.validate] Unknown options allowed_networks
20-06-18 21:37:55 WARNING (MainThread) [supervisor.addons.validate] Unknown options banned_ips
20-06-18 21:37:55 WARNING (MainThread) [supervisor.addons.validate] Unknown options banlimit
20-06-18 21:37:55 WARNING (MainThread) [supervisor.addons.validate] Unknown options notify_service

_Originally posted by @MPJK77 in https://github.com/home-assistant/supervisor/issues/908#issuecomment-646322308_

**Comment by frenck** [comment]
Hi there @MPJK77,

It means one of the add-ons has options configured that don't exist anymore.
Currently, the best way to find out, is browser through your add-ons and check their configurations if those configuration keys are set in there.'

I know this is daunting. An improvement for these error messages (to include the offending add-on) is expected to be available soon.

**Comment by MPJK77** [comment]
Hi @frenck ,

Thank you for your reply.
In my case it was the configurator add-on wich was causing the warning.
Solved it with your guiding, thank you for the great work you are doing!
