### ISSUE TITLE
Config ffmpeg camera?!

### ISSUE THREAD

**Issue by PcOnline2004** [home-assistant/supervisor#1806]
**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**

Hi there. I did config out my ffmpeg cameras and NVR. But some work, some did not works (same kind of camera). Could you please let me know what's wrong? The error logs as below. Thanks:

```
File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 5] I/O error: 'rtsp://192.168.1.9:554@user=admin_password=PASSWORD_channel=16_stream=0.sdp?real_stream'
```

**Comment by PcOnline2004** [comment]
One more camera error:

Fetch snapshot image failed from NVT, falling back to FFmpeg; No connection adapters were found for 'rtsp://192.168.1.24:554/user=admin_password=4HxdVFJ3_channel=0_stream=0.sdp?real_stream'

**Comment by frenck** [comment]
Hi there @PcOnline2004, thanks for opening an issue.

However, this is the issue tracker for the Supervisor, I guess (not entirely sure), your issue relies with the Home Assistant Core. This is not part of the Supervisor for sure.

If you want to report an issue with the Home Assistant Core integration, please file an issue here:

<https://github.com/home-assistant/core/issues>

Please note, we use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

In such a case, you are more likely to get the answer you are looking for in those places

Thanks! 👍
