### ISSUE TITLE
Allow the shm-size to be configured for an add-on

### ISSUE THREAD

**Issue by knobunc** [home-assistant/supervisor#1807]
**Home Assistant release with the issue:**

0.111.4

**Operating environment (HassOS/Generic):**

n/a

**Supervisor logs:**

n/a

**Description of problem:**

The Frigate add-on needs more than the default 64M of shared memory.  There is an issue for it at https://github.com/mories76/ha-addon-frigate/issues/4

The docker setting is at https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources

Ideally, it would be possible for the user to configure an shm size if the add-on requests that capability.  For Frigate, the tuning would depend on the number of cameras and the resolution used.

At the very least we should allow the add-on to change the shm setting.

**Comment by pvizeli** [comment]
You can write up an RFC and if they is approved, implement the soution 👍
