### ISSUE TITLE
"Protection mode is disabled" hard readable since Supervisor 228

### ISSUE THREAD

**Issue by casperklein** [home-assistant/supervisor#1813]
**Home Assistant release with the issue:**

0.111.4, but also with latest 0.112.2. I think HA version does not matter.

**Operating environment (HassOS/Generic):**

Homeassistant OS

**Supervisor logs:**

**Description of problem:**
When disabling an addon's protection mode in supervisor < 228 it looks like this:
![protectionmode-227](https://user-images.githubusercontent.com/590174/86522270-ae12f200-be5b-11ea-86e9-73bdcc549ecd.PNG)

After updating to 228 it looks like this:
![protectionmode](https://user-images.githubusercontent.com/590174/86522288-dc90cd00-be5b-11ea-8cd3-0f407ebb1708.PNG)

**Workaround / cross check:**
Downgrading Supervisor to 227 fixes the issue

    ha supervisor update --version 227

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/6263, will be in 229 :)

**Comment by pvizeli** [comment]
228 fix an big issue with snapshots which was more important to fix as to wait for the UI fix

**Comment by casperklein** [comment]
Thank you both for the fast replys and clarification!

One last question, maybe releated. I've running HA as a virtual machine (amd64). When I revert to my last snapshot (with supervisor 227) and start the VM without internet connection, I see version 227 as expected.
However, with internet connection enabled, Supervisor is updated on startup to 229 ([which isn't released yet?](https://version.home-assistant.io/stable.json))

![229](https://user-images.githubusercontent.com/590174/86530743-b26ef780-bebb-11ea-82de-fe4b309ab113.png)
![229-2](https://user-images.githubusercontent.com/590174/86530745-b4d15180-bebb-11ea-8342-20cd29e5f060.PNG)

The good thing with that version from the future is, I can confirm, 229 fixed my initial issue 👍

**Comment by pvizeli** [comment]
That is a bug in OS 4.10 which is fix on new 4.11 released yesterday
