### ISSUE TITLE
Updates not found, while available in stable.json

### ISSUE THREAD

**Issue by ebogaard** [home-assistant/supervisor#1821]
## The problem
Home Assistant doesn't find any new updates, unless I restart HAss.
I can see the new version in https://version.home-assistant.io/stable.json, but my HAssOS install doesn't pick this up. Even after hours or days.
Only when restarting HAss, I get notified of the new version and can install this without any problem.

## Environment

```
arch | x86_64
chassis | vm
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.50
python_version | 3.7.7
supervisor | 228
timezone | Europe/Amsterdam
version | 0.112.3
virtualenv | false
```

- Home Assistant Core release with the issue: 0.112.x (but had this before on 0.111.x and probably 0.110.x as well)
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): 
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment]
If you go to the Supervisor panel -> System tab and use the reload button, does it work? Anything in the logs at that point?

**Comment by ebogaard** [comment]
The button turns invisible for a moment, then goes back to the old state.
In the browser network log, I can see a POST, then a number of GETs. But in the screen nothing changes as far as I can see.
The supervisor-log doesn't show new rows, even after a refresh of the log.

**Comment by ebogaard** [comment]
This seems to be fixed in supervisor 229:
1. I get updates announced automatically
2. When I click the reload-button, in the logs I can see the stable.json being fetched.

I'll close this issue
