### ISSUE TITLE
Supervisor 228 update issue on RPi 4

### ISSUE THREAD

**Issue by BorisHruby** [home-assistant/supervisor#1823]
0.112.4

Raspberry Pi 4

arch | armv7l
-- | --
chassis |  
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | Raspbian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.19.118-v7l+
python_version | 3.7.7
supervisor | 227
timezone | Europe/Bratislava
version | 0.112.4
virtualenv | false

**Supervisor logs:**

20-07-11 15:50:07 INFO (MainThread) [supervisor.discovery] Load 0 messages
20-07-11 15:50:07 INFO (MainThread) [supervisor.ingress] Load 0 ingress session
20-07-11 15:50:07 INFO (MainThread) [supervisor.misc.secrets] Load Home Assistant secrets: 1
20-07-11 15:50:07 INFO (MainThread) [__main__] Run Supervisor
20-07-11 15:50:07 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-07-11 15:50:07 WARNING (MainThread) [supervisor.core] Ignore Supervisor updates!
20-07-11 15:50:07 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' start 0 add-ons
20-07-11 15:50:07 INFO (MainThread) [supervisor.core] Supervisor reboot detected
20-07-11 15:50:07 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
20-07-11 15:50:07 INFO (MainThread) [supervisor.misc.hwmon] Started Supervisor hardware monitor
20-07-11 15:50:07 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-07-11 15:50:07 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-11 15:50:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-11 15:50:07 INFO (MainThread) [supervisor.host.services] Update service information
20-07-11 15:50:07 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-11 15:50:07 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-11 15:55:42 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-11 15:56:01 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 228
20-07-11 15:56:01 INFO (SyncWorker_11) [supervisor.docker.interface] Pull image homeassistant/armv7-hassio-supervisor tag 228.
20-07-11 15:56:28 INFO (MainThread) [supervisor.supervisor] Fetch AppArmor profile https://version.home-assistant.io/apparmor.txt
20-07-11 15:56:29 INFO (MainThread) [supervisor.host.apparmor] Add or Update AppArmor profile: hassio-supervisor
20-07-11 15:56:34 INFO (MainThread) [__main__] Stopping Supervisor
20-07-11 15:56:34 INFO (MainThread) [supervisor.misc.hwmon] Stop Supervisor hardware monitor
20-07-11 15:56:34 INFO (MainThread) [supervisor.api] Stop API on 172.30.32.2
20-07-11 15:56:34 INFO (MainThread) [supervisor.misc.forwarder] Stop DNS forwarding
20-07-11 15:56:34 INFO (MainThread) [supervisor.core] Supervisor is down
20-07-11 15:56:34 INFO (MainThread) [__main__] Close Supervisor
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[15:56:40] INFO: Update udev informations
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
20-07-11 15:56:42 INFO (MainThread) [supervisor.bootstrap] Use the old homeassistant repository for machine extraction
20-07-11 15:56:42 INFO (MainThread) [__main__] Initialize Supervisor setup
20-07-11 15:56:43 INFO (MainThread) [supervisor.bootstrap] Setup coresys for machine: raspberrypi4
20-07-11 15:56:43 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attach to Supervisor homeassistant/armv7-hassio-supervisor with version 227
20-07-11 15:56:43 INFO (SyncWorker_0) [supervisor.docker.interface] Cleanup images: ['homeassistant/armv7-hassio-supervisor:228']
20-07-11 15:56:44 CRITICAL (MainThread) [supervisor.core] Update of Supervisor fails!
20-07-11 15:56:44 ERROR (MainThread) [supervisor.docker] Docker logging driver json-file is not supported!
20-07-11 15:56:44 CRITICAL (MainThread) [supervisor.core] System running in a unhealthy state. Please update you OS or software!
20-07-11 15:56:44 INFO (MainThread) [__main__] Setup Supervisor
20-07-11 15:56:44 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-07-11 15:56:44 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
20-07-11 15:56:44 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
20-07-11 15:56:44 WARNING (MainThread) [supervisor.dbus.nmi_dns] No DnsManager support on the host. Local DNS functions have been disabled.
20-07-11 15:56:44 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-11 15:56:44 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-11 15:56:44 INFO (MainThread) [supervisor.host.services] Update service information
20-07-11 15:56:44 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-11 15:56:44 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-07-11 15:56:44 INFO (MainThread) [supervisor.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-07-11 15:56:44 INFO (MainThread) [supervisor.host.apparmor] AppArmor is not enabled on host
20-07-11 15:56:44 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/armv7-hassio-dns with version 9
20-07-11 15:56:45 INFO (MainThread) [supervisor.plugins.dns] Restart CoreDNS plugin
20-07-11 15:56:45 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-07-11 15:56:45 INFO (SyncWorker_3) [supervisor.docker.interface] Restart homeassistant/armv7-hassio-dns
20-07-11 15:56:50 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
20-07-11 15:56:50 INFO (SyncWorker_6) [supervisor.docker.interface] Attach to homeassistant/armv7-hassio-audio with version 14
20-07-11 15:56:50 INFO (SyncWorker_8) [supervisor.docker.interface] Attach to homeassistant/armv7-hassio-cli with version 25
20-07-11 15:56:50 INFO (SyncWorker_10) [supervisor.docker.interface] Attach to homeassistant/armv7-hassio-multicast with version 2
20-07-11 15:56:50 INFO (MainThread) [supervisor.plugins.multicast] Restart Multicast plugin
20-07-11 15:56:50 INFO (SyncWorker_4) [supervisor.docker.interface] Restart homeassistant/armv7-hassio-multicast
20-07-11 15:56:55 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-11 15:56:55 INFO (SyncWorker_13) [supervisor.docker.interface] Attach to homeassistant/raspberrypi4-homeassistant with version 0.112.4
20-07-11 15:56:55 WARNING (MainThread) [supervisor.hassos] No Home Assistant Operating System found!
20-07-11 15:56:55 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-07-11 15:56:55 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-07-11 15:56:55 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 65 new - 0 remove
20-07-11 15:56:55 INFO (MainThread) [supervisor.addons] Found 3 installed add-ons
20-07-11 15:56:55 INFO (SyncWorker_16) [supervisor.docker.interface] Attach to homeassistant/armv7-addon-samba with version 9.2.0
20-07-11 15:56:55 INFO (SyncWorker_18) [supervisor.docker.interface] Attach to hassioaddons/grafana-armv7 with version 5.1.1
20-07-11 15:56:55 INFO (SyncWorker_17) [supervisor.docker.interface] Attach to hassioaddons/node-red-armv7 with version 6.3.0
20-07-11 15:56:55 INFO (MainThread) [supervisor.snapshots] Found 0 snapshot files
20-07-11 15:56:55 INFO (MainThread) [supervisor.discovery] Load 0 messages
20-07-11 15:56:55 INFO (MainThread) [supervisor.ingress] Load 0 ingress session
20-07-11 15:56:55 INFO (MainThread) [supervisor.misc.secrets] Load Home Assistant secrets: 1
20-07-11 15:56:55 INFO (MainThread) [__main__] Run Supervisor
20-07-11 15:56:55 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-07-11 15:56:55 WARNING (MainThread) [supervisor.core] Ignore Supervisor updates!
20-07-11 15:56:55 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' start 0 add-ons
20-07-11 15:56:55 INFO (MainThread) [supervisor.core] Supervisor reboot detected
20-07-11 15:56:55 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
20-07-11 15:56:55 INFO (MainThread) [supervisor.misc.hwmon] Started Supervisor hardware monitor
20-07-11 15:56:55 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-07-11 15:56:55 INFO (MainThread) [supervisor.host.info] Update local host information
20-07-11 15:56:55 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-07-11 15:56:55 INFO (MainThread) [supervisor.host.services] Update service information
20-07-11 15:56:55 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-07-11 15:56:55 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information

Can't update to the newest supervisor version (228).

**Comment by solidssss** [comment]
I got the same problem

**Comment by pvizeli** [comment]
System is not supported: https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#supported-operating-system-system-dependencies-and-versions
