### ISSUE TITLE
endpoint with name addon_a0d7b954_nodered already exists in network host

### ISSUE THREAD

**Issue by Quemola** [home-assistant/supervisor#1827]
After installing update of Node-Red in home assistant I get:
"endpoint with name addon_a0d7b954_nodered already exists in network".
I have un installed Node-Red from home assistant but still get the same problem.

20-07-14 09:36:11 INFO (SyncWorker_15) [supervisor.docker.interface] Clean addon_a0d7b954_nodered application
20-07-14 09:37:01 ERROR (SyncWorker_15) [supervisor.docker] Can't start addon_a0d7b954_nodered: 403 Client Error: Forbidden ("endpoint with name addon_a0d7b954_nodered already exists in network host")

And i cant finde "addon_a0d7b954_nodered" on the network in "Portainer".

Im new to this.
Hope some one are willing to help me whit this.
Thanks.

**Comment by pvizeli** [comment]
`ha su repair` fix the docker issues

**Comment by Quemola** [comment]
Thanks for your help.
