### ISSUE TITLE
Suggestion: Enable direct fixed IP setting in hassio or add instructions for fixed IP setting in documentation and note that this is a solution for problems after power failure

### ISSUE THREAD

**Issue by FrenkK** [home-assistant/supervisor#1841]
## The problem

Fixed IP setting is unnecessarily convoluted (see https://community.home-assistant.io/t/how-to-set-a-static-ip-on-hass-io-hassos/75680). Please add a setting to enable a fixed IP to the Supervisor host settings or at least add the documentation for for the procedure in the link above to the official docs. In either case, documentation should show that problems after a power failure might be solved using a fixed IP.

There are two reasons for this:
1. Some people want to use a fixed IP. Currently this is convoluted to do and hard to find info on.
2. I think most of the reported issues with hassio on Raspberry Pi not being accessible after power failure are due to the fact that routers are slow to start up, but they are usually the way DHCP is done in a normal home network. What happens: After a power failure, both the router and hassio instance on a Raspberry Pi start up in parallel. The Pi asks for a DHCP response before the router is ready to give it. This causes the Pi to set a default IP address and consequently, you can't access it via the usual network address. This is almost sure to be the reason because the problem ALWAYS resolves itself after turning the PI off and on again. Looking at the forums, this has frustrated a lot of people.

## Environment

- Home Assistant Core release with the issue: at least since 0.100
- Last working Home Assistant Core release (if known): Not known
- Operating environment (OS/Container/Supervised/Core): hassOS 4.11/Supervisor 288/0.102.3
- Integration causing this issue: N/A, OS related
- Link to integration documentation on our website: see above

## Problem-relevant `configuration.yaml`

```yaml
N/A
```

## Traceback/Error logs

```txt
N/A
```

**Comment by pvizeli** [comment]
This is for bugs only. Feature and enhancement requests should go in our community forum: https://community.home-assistant.io/c/feature-requests

**Comment by FrenkK** [comment]
This could be classed as a bug, so many people have the problem with startup after power failure due to DHCP unavailability.
But I added a feature request as well.
