### ISSUE TITLE
Supervisor memory usage keeps growing untill Home Assistant server crashes

### ISSUE THREAD

**Issue by phaeton82** [home-assistant/supervisor#1850]
**Home Assistant release with the issue:**
Home Assistant 0.112.4

**Operating environment (HassOS/Generic):**
arch | x86_64
chassis | desktop
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | Ubuntu 18.04.4 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.15.0-111-generic
python_version | 3.7.7
supervisor | 229
timezone | Europe/Amsterdam
version | 0.112.4
virtualenv | false

**Supervisor logs:**

**Description of problem:**
My supervisor seems to keep eating memory. See the glances screenshot below:
![glances](https://user-images.githubusercontent.com/5897362/88090519-fdf8f500-cb8d-11ea-861a-4a5ddfc6b1ab.png)

I tried disabling a lot of addons, this doesnt work. I want to rule out integrations, but with integrations moving to the interface instead of the YAML I don’t know how to disable them temporarily.

This is a dump from py-spy:
![profile](https://user-images.githubusercontent.com/5897362/88090558-0b15e400-cb8e-11ea-951f-8cf7c6cb8b53.png)

But I dont have any idea how to help you debug this. Please let me know if you need more information.

**Comment by pvizeli** [comment]
![image](https://user-images.githubusercontent.com/15338540/88288834-9c06cf80-ccf4-11ea-8820-e4be8d927b13.png)

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/88289267-4979e300-ccf5-11ea-80d4-43a9a7de715e.png)

Uptime of 6 days as well

![image](https://user-images.githubusercontent.com/195327/88289436-82b25300-ccf5-11ea-984a-f5682d460799.png)

**Comment by jjok** [comment]
From https://community.home-assistant.io/t/memory-leak/209905/14

>YES! I’ve been experiencing this same problem for the last few weeks. The memory use builds to around 90%, the load suddenly goes from around 0.2 to between 30 and 60 and the whole system becomes unresponsive.
I’ve been disabling random things, but haven’t isolated the issue yet.

> I started experiencing these problems not long after changing over to use MySQL instead of the default SQLite, and booting from SSD, so I was wondering if was related to one of those.
I don’t think I made any other changes around the time that the problems started.

I'm using the same Raspberry Pi 3A that I've been using for the last 18 months.

**Comment by jjok** [comment]
![ha1](https://user-images.githubusercontent.com/777648/88467014-4ab03900-ceca-11ea-8cad-5078ef6afe21.jpg)
![ha2](https://user-images.githubusercontent.com/777648/88467015-4b48cf80-ceca-11ea-9bd9-27b610cdcb12.jpg)

These are from today. I wasn't even in the house when it started going crazy at 10am.
It did the same at 4am the other night.
You can see that I switched it off at the wall for a bit this afternoon (when the load hit 60!), then started it up and disabled the MQTT add-on, then installing the latest version (0.113.1). The last little memory drop is where I deleted a load of my config and restarted.
You can see that it's still rising in a worrying fashion. I'm pretty sure that the memory graph used to always be completely flat.

**Comment by pvizeli** [comment]
@jjok I disable your comments because the supervisor is not the core. If you want talk in that group, provide the stats from `ha su stats`

**Comment by phaeton82** [comment]
An update: after a few crashes I reverted back to an older backup. Issues still there. Fully reinstalled Home Assistant and reverted back only restoring data (not selecting the top option). Now the issue has been gone for a day.

**Comment by pvizeli** [comment]
It's an issue with enabled debug mode. With new supervisor, we moved to a new debug integration.
