### ISSUE TITLE
Supervisor update issue / 500 Server Error

### ISSUE THREAD

**Issue by no0ner** [home-assistant/supervisor#1853]
**Home Assistant release with the issue:**
0.112.4

**Operating environment (HassOS/Generic):**
HassOS 4.11

**Supervisor logs:**
```
20-07-24 07:24:44 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-24 07:24:50 INFO (MainThread) [supervisor.api.security] /supervisor/update access from core_ssh
20-07-24 07:24:50 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 229
20-07-24 07:24:50 INFO (SyncWorker_3) [supervisor.docker.interface] Pull image homeassistant/armv7-hassio-supervisor tag 229.
20-07-24 07:25:06 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install homeassistant/armv7-hassio-supervisor:229 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/homeassistant/armv7-hassio-supervisor/manifests/229: Get https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Farmv7-hassio-supervisor%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)").
20-07-24 07:25:06 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor fails!
```

**Description of problem:**
I am trying to update the supervisor from 228 to 229 for a few days now but can't get it to work and don't know where to start looking for a solution. As far as I remember I didn't change anything except for the HassOS 4.11 update. Any ideas?

**Comment by timbuchwaldt** [comment]
+1 from my side.

I see ```20-07-27 11:09:00 ERROR (SyncWorker_2) [supervisor.docker.interface] Can't install homeassistant/armhf-addon-deconz:6.1.2 -> 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/homeassistant/armhf-addon-deconz/manifests/6.1.2: Get https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Farmhf-addon-deconz%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)").``` and similar issues on all operations regarding pulling of images.

I tried using the console to repair things (`hassos su repair`), this leads to even more issues: it seems to try to re-pull images of my extensions, runs into the aforementioned issues and then just outright deletes the add-on.
I also checked DNS, reset to using only public DNS servers and the like, to no avail. While pulling the hassos images fails every time i was able to pull the alpine image.

**Comment by pvizeli** [comment]
`Client.Timeout exceeded while awaiting headers`

That is no DNS issue. Sounds like a firewall or other kind of a blocking web filter.

**Comment by timbuchwaldt** [comment]
This issue persists with a fresh OS image trying to install. I have no blocking filters (except for DNS, which was part of the setup which I wiped to reinstall) and the exact HTTP call (auth.docker.io) works on other machines in the network.

**Comment by no0ner** [comment]
I just tried `curl "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Farmv7-hassio-supervisor%3Apull&service=registry.docker.io"` from within the terminal add-on inside homeassistant and it's working fine. Makes it even less understandable for me.

**Comment by timbuchwaldt** [comment]
During reinstall it tries to pull the landingpage container and fails with the same issues.

Just for further debugging: I'm behind a 1gbit/s Cable link, connected directly to my router. No shenanigans with networking or anything and a rock-solid connection.

**Comment by timbuchwaldt** [comment]
More news: It's a network-thing. But: It seems to be in  my providers network - Vodafone/Unitymedia in NRW/Cologne.
Switch my router to use the LTE fallback via Telekom: 0 Issues, it just works (TM).

**Comment by no0ner** [comment]
Okay, it's UM/VF NRW for me as well. I'll close this issue.

**Comment by SublimePotato** [comment]
Can confirm it's the provider (Hamburg/Vodafone 1gbit cable).
Did you guys (@timbuchwaldt, @no0ner) contact Vodafone? I would but to me it's not clear what exactly is the problem since the network call itself works from other devices.

**Comment by no0ner** [comment]
> Can confirm it's the provider (Hamburg/Vodafone 1gbit cable).
> Did you guys (@timbuchwaldt, @no0ner) contact Vodafone? I would but to me it's not clear what exactly is the problem since the network call itself works from other devices.

It seems it's not a Vodafone issue but an issue with the latest beta/labor firmware on the FritzBox 6660. If you disable hardware acceleration in the "hidden" support settings it starts working again. @timbuchwaldt wanted to open a support ticket at AVM - dunno if he did already.

**Comment by timbuchwaldt** [comment]
I sent feedback to AVM via Labor Firmware Feedback, so far nothing came back from that.

**Comment by mrestorff** [comment]
Can confirm it is an issue on the FrizBox 6591 Cable as well, running beta firmware 07.19-80492. Disabling hardware acceleration in http://fritz.box/support.lua fixes the issue as well. However, I can not recommend running in this mode during normal operation.

**Comment by gomble** [comment]
> I sent feedback to AVM via Labor Firmware Feedback, so far nothing came back from that.

Did they reply?

**Comment by no0ner** [comment]
The issue seems to be fixed with the latest Labor Update released yesterday!

**Comment by gomble** [comment]
Are you sure? i installed it 5 minutes ago and did to try to update my homeassistant supervisor and got the same error.

**Comment by no0ner** [comment]
At least another android app which wasn't working for me with hardware acceleration enabled now does. So I thought the issue has been fixed in general. Haven't had a homeassistant update yet.

**Comment by gomble** [comment]
Okay after a restart of my homeassistant it installed Supervisor 231 automatically. It seems to work 👍

**Comment by timbuchwaldt** [comment]
What @no0ner says, fixed with latest update.
