### ISSUE TITLE
Supervisor not showing update available for core until full host restart

### ISSUE THREAD

**Issue by schildgenb** [home-assistant/supervisor#1855]
**Home Assistant release with the issue:**

0.113.0
**Operating environment (HassOS/Generic):**

Virtual Box HassOS 4.11
**Supervisor logs:**

Do not see any error messages or what to copy to show the issue.

**Description of problem:**
In the Dashboard it does not show an update is available for Core. I believe this stopped working a month ago and thought maybe it would have resolved itself. Only when I reboot the host system will it then show an update is available. I apologize that I do not have much to provide as I have looked and do not see any errors. I may not be looking in the right place or posting the issue in the right area as well. Let me know what I can provide and I will get it for you. Again the log for Supervisor does not show any errors that I can see.

**Comment by ludeeus** [comment]
It checks for updates on a schedule, it checks every 2h.
You can manually trigger a check by reloading the supervisor from supervisor -> system(Or like you do now)
