### ISSUE TITLE
Wrong update available

### ISSUE THREAD

**Issue by badblocks** [home-assistant/supervisor#1865]
**Home Assistant release with the issue:**

0.113.3

**Operating environment (HassOS/Generic):**

HassOS 5.0 64bit (preliminary release)
Supervisor 229

**Supervisor logs:**

**Description of problem:**
This should not be possible; 4.11 is older then 5.0
![Screen Shot 08-03-20 at 10 59 AM](https://user-images.githubusercontent.com/33039388/89165916-8c4f7c80-d579-11ea-87f1-fbd0ff3be8df.PNG)

**Comment by ludeeus** [comment]
It only checks if there is a difference in the value (installed != available).
It checks this against the channel you are on

- https://version.home-assistant.io/stable.json
- https://version.home-assistant.io/beta.json
- https://version.home-assistant.io/dev.json

If the installed version, differs from available version in the channel you are in, it will offer an update to get the newest version in that channel.

**Comment by badblocks** [comment]
Ok, thank for clarifying.
