### ISSUE TITLE
DoT DNS traffic to Cloudflair

### ISSUE THREAD

**Issue by tescophil** [home-assistant/supervisor#1877]
## The problem
I'm seeing regular (9/min) DoT DNS requests to 1.1.1.1 and 1.0.0.1 coming from my Home Asssitant instance

## Environment
Raspberry Pi 3B+
HassOS 4.110
Home Assistant 0.113.3
Supervisor 229

I have installed the following Ad-ons:

AdGuardHome
Check Home Assistant configuration
Duck DNS
File editor
Hass.io Google Drive Backup
Terminal & SSH

- Home Assistant Core release with the issue: 
- Last working Home Assistant Core release (if known): Unknown
- Operating environment (OS/Container/Supervised/Core): HassOS 4.11
- Integration causing this issue: Unknown / poss AdGuard Home
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`
```
~ $ ha dns info
host: 172.30.32.3
locals:
- dns://192.168.10.1
servers: []
version: "9"
version_latest: "9"
~ $ 
```

## Traceback/Error logs
No error logs`

## Additional information
If the core of HA is not doing this, then the only addon which I thought may be responsible is AdGuard Home, however my AdGuard Home is not setup to use upstream DoT and the servers 1.1.1.1 and 1.0.0.1 do not appear anywhere in the config.

I'm now blocking external 853 requests, so my router logs are full of this:

![Screenshot from 2020-08-07 11-05-05](https://user-images.githubusercontent.com/59442445/89635479-f0867f00-d89e-11ea-90db-b9b3a1e6ff16.png)

**Comment by tescophil** [comment]
I updated to HassOS 4.12 yesterday and no longer see the 853 requests in my logs...

**Comment by pvizeli** [comment]
The 853 is from our supervisor as a fallback if the user have messed up the DNS on his network. More details with `ha dns info`

**Comment by tescophil** [comment]
OK, then what is screwed up about my DNS config ? (because I would suggest absolutely nothing...)
```
~ $ ha dns info
host: 172.30.32.3
locals:
- dns://192.168.10.1
servers: []
version: "9"
version_latest: "9"
~ $
```

**Comment by tescophil** [comment]
@pvizeli  I would like to re-open this issue as a bug, because my DNS setup is working perfectly well, yet I see constant DoT requests to Cloudflair coming from the supervisor (which are blocked by by firewall)

**Comment by scottycs19** [comment]
I am having this issue as well

**Comment by evarsanyi** [comment]
I would also like to get this fixed, the firewall logs getting flushed out is annoying but I can work around that -- but IMO the system should not be trying to override my settings (maybe I don't want to use cloudflare for a reason). My DNS works fine as configured.

Now I'm worried about what other sorts of backdoor traps this project has put in that won't be as easy to detect.
