### ISSUE TITLE
Unable to update to 231

### ISSUE THREAD

**Issue by renecloosterman** [home-assistant/supervisor#1895]
**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**
20-08-12 02:25:11 ERROR (SyncWorker_2) [supervisor.docker.interface] Can't install homeassistant/amd64-hassio-supervisor:231 -> 404 Client Error: Not Found ("no such image: homeassistant/amd64-hassio-supervisor:231: No such image: homeassistant/amd64-hassio-supervisor:231").
20-08-12 02:25:11 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor fails!
20-08-12 02:25:11 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-474530' coro=<Tasks._update_supervisor() done, defined at /usr/src/supervisor/supervisor/misc/tasks.py:155> exception=SupervisorUpdateError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 166, in _update_supervisor
    await self.sys_supervisor.update()
  File "/usr/src/supervisor/supervisor/supervisor.py", line 126, in update
    raise SupervisorUpdateError() from None
supervisor.exceptions.SupervisorUpdateError
20-08-12 02:35:09 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-08-12 02:35:09 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-08-12 02:35:09 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-08-12 02:35:10 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/sabeechen/hassio-google-drive-backup repo: Cmd('git') failed due to: exit code(1)
  cmdline: git reset --hard origin/master
  stderr: 'error: update_ref failed for ref 'HEAD': cannot lock ref 'HEAD': Unable to create '/data/addons/git/cebe7a76/.git/refs/heads/master.lock': No space left on device'.

**Description of problem:**

Unable to update, see logs ;-)

**Comment by ludeeus** [comment]
Generally, a 404 error tells that you do not have enough space left on the device.

> No space left on device

Your log is also saying this as well, you need to clear some space before you can do the update.
Closing this as this is not an issue with the supervisor.

If you need help with the cleanup, join [discord](https://discord.gg/c5DvZ4e) or the [forums](https://community.home-assistant.io/) for support with that :)

**Comment by renecloosterman** [comment]
How stupid of me not to see ;-) , thx
