### ISSUE TITLE
403 Errors from an addon against the Supervisor API

### ISSUE THREAD

**Issue by sabeechen** [home-assistant/supervisor#1930]
I'm the author of [an addon that backs up snapshots to Google Drive](https://github.com/sabeechen/hassio-google-drive-backup).  One of my users [notified me of an issue](https://github.com/sabeechen/hassio-google-drive-backup/issues/221) where the addon can't run because it gets 403 errors when attempting to access Supervisor API.  Here is an abridged version of the 
supervisor log that they posted in the original issue:
```
20-08-15 17:36:44 ERROR (MainThread) [supervisor.api.security] Invalid token for access /addons/self/info
20-08-15 17:39:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-08-15 17:39:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-08-15 17:39:07 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-08-15 17:39:08 INFO (MainThread) [supervisor.store] Load add-ons from store: 67 all - 0 new - 0 remove
20-08-15 17:41:31 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 17:46:41 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 17:51:51 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 17:57:01 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 18:02:11 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 18:07:21 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 18:12:31 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 18:17:41 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 18:22:51 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 18:28:01 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 18:33:11 WARNING (MainThread) [supervisor.api.proxy] Unknown Home Assistant API access!
20-08-15 18:36:45 ERROR (MainThread) [supervisor.api.security] Invalid token for access /addons/self/info
```
I'm pretty sure the failed /addons/self/info is from my addon, and I'd presume the failed HA proxy messages are form it as well (my addon uses both).  What the addon gets back is an HTTP 403:
```
08-14 16:36:39 DEBUG [backup.ha.hasource] Failed to connect to supervisor
08-14 16:36:39 DEBUG [backup.ha.hasource]
addon/backup/ha/hasource.py:280 (_refreshInfo)
addon/backup/ha/harequests.py:25 (wrap_and_call)
addon/backup/ha/harequests.py:96 (selfInfo)
addon/backup/ha/harequests.py:25 (wrap_and_call)
addon/backup/ha/harequests.py:183 (_getHassioData)
addon/backup/ha/harequests.py:148 (_validateHassioReply)
/site-packages/aiohttp/client_reqrep.py:941 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://hassio/addons/self/info')
```

I've seen this come up from other users in the past, though I've never been able to reproduce it on my machines, sometimes right after updating and sometimes apparently randomly.  Some combination of restarting HA, restarting the supervisor, restarting the host, or reinstalling the addon has previously resolved it.  This is my first time making an issue for it.

The addon is always including the `X-HASSIO-KEY` header for Supervisor endpoints and `'Authorization': 'Bearer` for HA endpoints populated with `HASSIO_TOKEN` env variable, but because most of my users aren't having problems I'm skeptical that its something I'm doing.

I'll ask the user encountering this to post their HassOS and HA version here in case it helps.

(Edited because I clicked submit too early)

**Home Assistant release with the issue:**
To be provided

**Operating environment (HassOS/Generic):**
To be provided

**Comment by kuroi8989** [comment]
Hi! I'm one of said users. I am running on a Raspberry Pi 4. Home Assistant 0.114.0. HassOS 4.12

**Comment by pvizeli** [comment]
`Unknown Home Assistant API access!`

You using the wrong access token

**Comment by sabeechen** [comment]
I'll start using bearer universally, but could that be whats causing this?  I haven't seen that error come up from any other users (maybe I missed it?).

I'll ask the user if they run portainer.

Side note: is there a changelog or something smiilar where I can stay up-to-date with changes in the supervisor addon API?

**Comment by sabeechen** [comment]
The user isn't running portainer or using anything else that touches Docker.

**Comment by pvizeli** [comment]
Please enable the Crash reports on such systems. If we can catch the error, we can fix it.

**Comment by sabeechen** [comment]
Can you point me toward something that explains how to set up crash reports?  I'm unfamiliar with this feature, is it something in the supervisor?
Note: Nothing seems to be crashing, the supervisor and addon are both catching the exception.

**Comment by pvizeli** [comment]
https://twitter.com/pvizeli/status/1293939694330314754?s=19
