### ISSUE TITLE
Ubuntu 18.04.5 LTS unsupported installation for supervisor

### ISSUE THREAD

**Issue by oscarpuigcerver** [home-assistant/supervisor#1949]
**Home Assistant release with the issue:**
Supervisior version: from 234
Hassio version on docker: from 0.114.2

**Operating environment (HassOS/Generic):**
Host OS: Ubuntu 18.04.5 LTS

**Supervisor logs:**
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[12:00:13] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
20-08-19 12:00:15 INFO (MainThread) [supervisor.bootstrap] Use the old homeassistant repository for machine extraction
20-08-19 12:00:15 INFO (MainThread) [__main__] Initialize Supervisor setup
20-08-19 12:00:15 INFO (MainThread) [supervisor.bootstrap] Initialize Supervisor Sentry
20-08-19 12:00:15 INFO (MainThread) [supervisor.bootstrap] Setup coresys for machine: intel-nuc
20-08-19 12:00:15 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 235
20-08-19 12:00:15 INFO (SyncWorker_0) [supervisor.docker.supervisor] Connect Supervisor to hassio Network
20-08-19 12:00:15 INFO (SyncWorker_0) [supervisor.docker.interface] Cleanup images: ['homeassistant/amd64-hassio-supervisor:234']
20-08-19 12:00:15 ERROR (MainThread) [supervisor.docker] Docker logging driver json-file is not supported!
20-08-19 12:00:15 INFO (MainThread) [__main__] Setup Supervisor
20-08-19 12:00:15 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-08-19 12:00:15 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
20-08-19 12:00:15 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
20-08-19 12:00:15 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
20-08-19 12:00:15 INFO (MainThread) [supervisor.host.info] Update local host information
20-08-19 12:00:15 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-08-19 12:00:15 INFO (MainThread) [supervisor.host.services] Update service information
20-08-19 12:00:15 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-08-19 12:00:16 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-08-19 12:00:16 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-08-19 12:00:16 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-08-19 12:00:16 INFO (MainThread) [supervisor.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-08-19 12:00:16 INFO (MainThread) [supervisor.host.services] Reload local service hassio-apparmor.service
20-08-19 12:00:16 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-08-19 12:00:16 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 9
20-08-19 12:00:16 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-08-19 12:00:16 INFO (MainThread) [supervisor.plugins.dns] Restart CoreDNS plugin
20-08-19 12:00:16 INFO (SyncWorker_0) [supervisor.docker.interface] Restart homeassistant/amd64-hassio-dns
20-08-19 12:00:20 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
20-08-19 12:00:20 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-audio with version 17
20-08-19 12:00:20 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-cli with version 25
20-08-19 12:00:20 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-multicast with version 2
20-08-19 12:00:20 INFO (MainThread) [supervisor.plugins.multicast] Restart Multicast plugin
20-08-19 12:00:20 INFO (SyncWorker_0) [supervisor.docker.interface] Restart homeassistant/amd64-hassio-multicast
20-08-19 12:00:24 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-08-19 12:00:24 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/intel-nuc-homeassistant with version 0.114.2
20-08-19 12:00:24 INFO (MainThread) [supervisor.hassos] No Home Assistant Operating System found
20-08-19 12:00:24 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-08-19 12:00:24 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/7ad98f9c repository
20-08-19 12:00:24 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-08-19 12:00:24 INFO (MainThread) [supervisor.store] Load add-ons from store: 68 all - 68 new - 0 remove
20-08-19 12:00:24 INFO (MainThread) [supervisor.addons] Found 7 installed add-ons
20-08-19 12:00:24 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-check_config with version 3.4.0
20-08-19 12:00:24 INFO (SyncWorker_3) [supervisor.docker.interface] Attach to hassioaddons/appdaemon-amd64 with version 0.2.6
20-08-19 12:00:24 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-duckdns with version 1.12.1
20-08-19 12:00:24 INFO (SyncWorker_2) [supervisor.docker.interface] Attach to hassioaddons/vscode-amd64 with version 2.4.0
20-08-19 12:00:24 INFO (SyncWorker_4) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-mosquitto with version 5.1
20-08-19 12:00:24 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to dwelch2101/zigbee2mqtt-amd64 with version 1.14.3
20-08-19 12:00:24 INFO (SyncWorker_5) [supervisor.docker.interface] Attach to hassioaddons/wireguard-amd64 with version 0.3.2
20-08-19 12:00:24 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files
20-08-19 12:00:24 INFO (MainThread) [supervisor.discovery] Load 1 messages
20-08-19 12:00:24 INFO (MainThread) [supervisor.ingress] Load 0 ingress session
20-08-19 12:00:24 INFO (MainThread) [supervisor.misc.secrets] Load Home Assistant secrets: 23
**20-08-19 12:00:24 ERROR (MainThread) [supervisor.core] Detected unsupported OS: Ubuntu 18.04.5 LTS**
20-08-19 12:00:24 INFO (MainThread) [__main__] Run Supervisor
20-08-19 12:00:24 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
**20-08-19 12:00:24 CRITICAL (MainThread) [supervisor.core] System running in a unsupported environment!**
20-08-19 12:00:25 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' start 0 add-ons
20-08-19 12:00:25 INFO (MainThread) [supervisor.core] Supervisor reboot detected
20-08-19 12:00:25 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
**20-08-19 12:00:25 CRITICAL (MainThread) [supervisor.misc.hwmon] Not privileged to run udev monitor!**
20-08-19 12:00:25 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-08-19 12:00:25 INFO (MainThread) [supervisor.host.info] Update local host information
20-08-19 12:00:25 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-08-19 12:00:25 INFO (MainThread) [supervisor.host.services] Update service information
20-08-19 12:00:25 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-08-19 12:00:25 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-08-19 12:00:25 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-08-19 12:00:25 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-08-19 12:00:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-08-19 12:00:25 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
20-08-19 12:00:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
20-08-19 12:00:28 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-08-19 12:00:28 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon
20-08-19 12:00:28 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running

**Description of problem:**
If I am not wrong, since I updated the Ubuntu system last week (`sudo apt-get update && apt-get upgrade`) coinciding with the update of the supervisor version 234, it appears the message in the supervisor information page the following message:
`You are running an unsupported installation`
![info](https://user-images.githubusercontent.com/10966007/90635170-2295ca80-e229-11ea-80c2-8bd925f19134.jpg)

All seems to be working fine but this message leaves me worried.

Thanks for your work!

**Comment by pvizeli** [comment]
https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md

Look like ubuntu don't work:
`20-08-19 12:00:25 CRITICAL (MainThread) [supervisor.misc.hwmon] Not privileged to run udev monitor!`

Until someone fix that, it's not a supported system.

**Comment by jsiemek** [comment]
I had exactly same entries in my log after nearly each supervisor upgrade. 

Simple: 
$ sudo systemctl restart hassio-supervisor.service 
fix the problem.

**Comment by pvizeli** [comment]
> fix the problem.

that is not called fixed. The issue still exists on next container recreating :P
