### ISSUE TITLE
DHCP log level

### ISSUE THREAD

**Issue by MisfitPunisher** [home-assistant/supervisor#1951]
**Home Assistant release with the issue:**
        Home Assistant 0.114.2

**Operating environment (HassOS/Generic):**
HassOS 4.12

**Description of problem:**

Hi friends!

I'm using the home assistant DHCP add-on. It works fine, perfect!
I would like to get some more information on the log file, because the default log level is not pretty extensive.

How can get more info on the DHCP log? (like date/time of each event?).

Thank you all!

**Comment by ludeeus** [comment]
Hi @MisfitPunisher :wave:

This is the issue tracker for the supervisor, you are asking about features in an add-on (not related to this repository).

To request features for a core addon (from the home-assistant/hassio-addons repository), please use the [Feature request section on the forum](https://community.home-assistant.io/c/feature-requests/13) thanks :+1:
