### ISSUE TITLE
RFC: healthy assistant

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/supervisor#1964]
## Context

Initially it was the idea to create a health plugin. But with the sentry, we achieve already the goal with getting logs if the supervisor fails on start. Also, the installation OS/Supervisord has script local they try to make the supervisor healthy or keep it alive. For sure, we need to integrate Sentry also to these scripts to get information if they have an issue. We can't make a plugin which try to archive the same mechanics they should (and do) run local.

But we have one open point which the current architecture, not can addressing, also not with the local Sentry installation. This kind of error leads the user with an error alone which doesn't help the users and also not us if they report it. So we need to make it possible to get the early boot log of the supervisor.

With the Sentry on Supervisor, we were able to fix almost all unexcepted errors during the startup, and also a health plugin would not able to fix the issues for starting the Supervisor again. To allow doing somethings if things fails is also somethings which we need archive on the OS.

## Decision

We replace the idea of the healthy monitor (which almost absolute with the sentry on supervisor and OS/install).

We spin up a plugin monitor with is allowed to read the journal of the local supervisor service and make this available over `/logs` and later `/stream`. The landing page nginx routing internal to the monitor and allow user to get the logs what is going on in the background and the CLI allow also to see this log if the supervisor is not answering.

## Future

A WebSocket stream to see real-time logs on landing page

**Comment by balloob** [comment]
Should we just call it `logging` instead of `health` ? 

I think that it's a good idea to provide a backup to get the logs in case the supervisor is no longer responding.

**Comment by pvizeli** [comment]
Yeah, is also in ClickUp. I would call it `monitor` aka `plugin/monitor` because it monitors the supervisor's service and maybe can also do some proactive send logs on an issue and his task is to monitor the supervisor and assistant on the OS/installer. The origin `health plugin` is died and replace with Sentry and this monitor - active bug fix on OS/SU.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/plugin-observare

After https://github.com/home-assistant/supervisor/pull/2027 which is the best solution to actively protect the Supervisor from deadlock, we need the only plugin to observe the supervisor and allow access to the supervisor logs maybe future some minimal reanimate functions if they are really needed after 2027

**Comment by pvizeli** [comment]
Archived
