### ISSUE TITLE
Failed to load cookie file from cookie: No such file or directory

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/supervisor#1980]
**Home Assistant release with the issue:**

114.3
**Operating environment (HassOS/Generic):**

HassOS 4.12
**Supervisor logs:**

```
20-08-27 01:16:34 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
```

**Description of problem:**
ever recurring error in the supervisor log. No idea where this is coming from. I don't use any Audio related hardware/settings in the config.

**Comment by pvizeli** [comment]
It's not a bug, just a message

**Comment by Mariusthvdb** [comment]
ok, a message, but a recurring one, without any way to solve it? Why is it there, and how can it be prevented.
