### ISSUE TITLE
no update proposed after 235

### ISSUE THREAD

**Issue by Nessy1970** [home-assistant/supervisor#2004]
**Home Assistant release with the issue:**
arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.8.3
supervisor | 235
timezone | Europe/Paris
version | 0.114.4
virtualenv | false

**Operating environment (HassOS/Generic):**
HassOS 4.12

**Supervisor logs:**
20-09-02 22:19:30 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-02 22:42:09 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-02 22:49:33 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-02 23:19:36 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-02 23:42:10 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-02 23:49:39 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-02 23:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-09-02 23:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-09-02 23:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-09-02 23:50:54 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-09-02 23:50:56 INFO (MainThread) [supervisor.store] Load add-ons from store: 67 all - 0 new - 0 remove
20-09-03 00:10:56 INFO (MainThread) [supervisor.host.info] Update local host information
20-09-03 00:10:56 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-09-03 00:10:57 INFO (MainThread) [supervisor.host.services] Update service information
20-09-03 00:10:57 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-09-03 00:10:57 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-09-03 00:10:57 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-09-03 00:10:58 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-09-03 00:19:42 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 00:42:11 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-03 00:49:46 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 01:19:48 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 01:42:12 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-03 01:49:51 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 01:50:54 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-09-03 02:17:36 INFO (MainThread) [supervisor.host.info] Update local host information
20-09-03 02:17:36 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-09-03 02:17:37 INFO (MainThread) [supervisor.host.services] Update service information
20-09-03 02:17:37 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-09-03 02:17:38 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-09-03 02:17:38 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-09-03 02:17:38 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-09-03 02:19:54 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 02:42:13 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-03 02:49:57 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 02:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-09-03 02:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-09-03 02:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-09-03 02:50:56 INFO (MainThread) [supervisor.store] Load add-ons from store: 67 all - 0 new - 0 remove
20-09-03 03:20:00 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 03:42:14 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-03 03:50:05 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 03:50:54 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-09-03 04:20:07 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 04:24:16 INFO (MainThread) [supervisor.host.info] Update local host information
20-09-03 04:24:16 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-09-03 04:24:17 INFO (MainThread) [supervisor.host.services] Update service information
20-09-03 04:24:17 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-09-03 04:24:18 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-09-03 04:24:18 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-09-03 04:24:18 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-09-03 04:42:15 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-03 04:50:14 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 05:20:16 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 05:42:16 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-03 05:50:18 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 05:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-09-03 05:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-09-03 05:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-09-03 05:50:54 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-09-03 05:50:56 INFO (MainThread) [supervisor.store] Load add-ons from store: 67 all - 0 new - 0 remove
20-09-03 06:20:22 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 06:30:56 INFO (MainThread) [supervisor.host.info] Update local host information
20-09-03 06:30:56 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-09-03 06:30:57 INFO (MainThread) [supervisor.host.services] Update service information
20-09-03 06:30:57 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-09-03 06:30:58 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-09-03 06:30:58 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-09-03 06:30:58 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-09-03 06:42:17 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-03 06:50:27 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 07:20:33 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 07:42:17 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-03 07:50:37 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 07:50:54 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-09-03 08:05:04 INFO (SyncWorker_4) [supervisor.docker.interface] Restart homeassistant/raspberrypi3-homeassistant
20-09-03 08:06:07 INFO (MainThread) [supervisor.homeassistant] Wait until Home Assistant is ready
20-09-03 08:13:59 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-09-03 08:20:42 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 08:27:21 INFO (SyncWorker_0) [supervisor.docker.interface] Restart homeassistant/raspberrypi3-homeassistant
20-09-03 08:28:23 INFO (MainThread) [supervisor.homeassistant] Wait until Home Assistant is ready
20-09-03 08:36:08 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-09-03 08:37:36 INFO (MainThread) [supervisor.host.info] Update local host information
20-09-03 08:37:36 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-09-03 08:37:37 INFO (MainThread) [supervisor.host.services] Update service information
20-09-03 08:37:37 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-09-03 08:37:38 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-09-03 08:37:38 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-09-03 08:37:38 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory
20-09-03 08:42:18 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-09-03 08:50:51 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-09-03 08:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
20-09-03 08:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-09-03 08:50:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-09-03 08:50:58 INFO (MainThread) [supervisor.store] Load add-ons from store: 67 all - 0 new - 0 remove

**Description of problem:**
no update of the supervisor proposed for several days, while versions 236, 237, 238 are available.
Here is the result by typing: https://version.home-assistant.io/stable.json

{
  "channel": "stable",
  "supervisor": "235",
  "homeassistant": {
    "default": "0.114.4",
    "qemux86": "0.114.4",
    "qemux86-64": "0.114.4",
    "qemuarm": "0.114.4",
    "qemuarm-64": "0.114.4",
    "intel-nuc": "0.114.4",
    "raspberrypi": "0.114.4",
    "raspberrypi2": "0.114.4",
    "raspberrypi3": "0.114.4",
    "raspberrypi3-64": "0.114.4",
    "raspberrypi4": "0.114.4",
    "raspberrypi4-64": "0.114.4",
    "tinker": "0.114.4",
    "odroid-c2": "0.114.4",
    "odroid-n2": "0.114.4",
    "odroid-xu": "0.114.4"
  },
  "hassos": {
    "ova": "4.12",
    "rpi": "4.12",
    "rpi0-w": "4.12",
    "rpi2": "4.12",
    "rpi3": "4.12",
    "rpi3-64": "4.12",
    "rpi4": "4.12",
    "rpi4-64": "4.12",
    "tinker": "4.12",
    "odroid-c2": "4.12",
    "odroid-n2": "4.12",
    "odroid-xu4": "4.12",
    "intel-nuc": "4.12"
  },
  "hassos-cli": "19",
  "cli": "25",
  "dns": "9",
  "audio": "17",
  "multicast": "3",
  "picture": {
    "core": "homeassistant / {machine} -homeassistant",
    "supervisor": "homeassistant / {arch} -hassio-supervisor",
    "cli": "homeassistant / {arch} -hassio-cli",
    "audio": "homeassistant / {arch} -hassio-audio",
    "dns": "homeassistant / {arch} -hassio-dns",
    "multicast": "homeassistant / {arch} -hassio-multicast"
  }
}

It turns out that the last stable version is 235, is this the reason for the blocking of updates?

**Comment by frenck** [comment]
> while versions 236, 237, 238 are available.

Those are not declared stable. 236, 237 are declared not suitable for stable release, 238 is currently in beta testing.
