### ISSUE TITLE
Unable to download large snapshots on 32bit arm flatforms

### ISSUE THREAD

**Issue by sabeechen** [home-assistant/supervisor#2047]
**Home Assistant release with the issue:**

Home Assistant 0.114.4

**Operating environment (HassOS/Generic):**

HassOS 4.13

**Supervisor logs:**

```bash
20-09-12 17:28:38 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
20-09-12 17:28:46 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
20-09-12 17:28:58 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 73945d7b
20-09-12 17:29:09 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
20-09-12 17:29:13 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
20-09-12 17:30:00 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
20-09-12 17:30:04 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
20-09-12 17:30:12 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
20-09-12 17:30:32 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
20-09-12 17:31:00 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
```

**Description of problem:**
I'm unable to download larger snapshots from the supervisor on 32-bit arm platforms.   A 1 GB snapshots downloads fine, but a 2GB snapshot fails.

Minimal Steps to Reproduce:
- Download and install the latest installation image for the pi2 https://github.com/home-assistant/operating-system/releases/download/4.13/hassos_rpi2-4.13.img.gz 
- Install the Samba addon and add a 2GB file to the /config folder. I generated such a file with:
  ```bash
   dd if=/dev/urandom of=1GB.bin bs=64M count=32 iflag=fullblock
   ```
- Create a snapshot from `Supervisor` > `Snapshots` > `CREATE`
- Attempt to download the new snapshot, and chrome reports "Failed - Network Error" 
![image](https://user-images.githubusercontent.com/21026774/93002020-db7dbb00-f4f0-11ea-9b90-d9528aa4d9e5.png).  Nothing shows up in chrome's network tab.

I noticed this problem because users [reported seeing it with my addon](https://github.com/sabeechen/hassio-google-drive-backup/issues/251), the same issue occurs when using the [/snapshot/download ](https://github.com/home-assistant/supervisor/blob/dev/API.md#snapshot) addon api method (I'm guessing this and the browser download use the same path internally).
I managed to reproduce this on a 32-bit raspberry pi 2 (its the hardware I have on hand) but I've had users report it happen on a Pi3B and pi4 as well when using the 32 bit image.  I've been trying to narrow this problem down for a while, for a long time I thought it was a problem in my addon until I noticed it also happens when trying to download a snapshot through the supervisor's web ui.  Here is everything I've learned about it:
- I'm unable to get it to happen using the 64 bit pi4 image, which is why I suspect this only affects the 32 bit images.
- I haven't had any reports of users running into this outside of the 32 bit images.
- Smaller snapshots (1GB and less) download fine, larger ones (2GB) fail.
- The supervisor logs that a snapshot download was attempted, but does not log any errors:
  ```
   20-09-12 17:30:04 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 8d0f4a81
   ```
- It doesn't seem to matter if create the snapshot in the supervisor or upload it into /backup from another supervisor, the bigger snapshot fails to download either way.
- For these larger snapshots, the /api/snapshots method returns HTTP 200 and whats looks like the appropriate headers, but then the connection is closed immedietaly before sending any snapshot bytes.   Here is the pattern of request start/end one of my users saw (this is based on reporting from aiohttp's [Client Tracing](https://docs.aiohttp.org/en/stable/client_advanced.html#aiohttp-client-tracing)):
  ```
  08-28 09:46:42 TRACE [backup.tracing_session] Request started: GET http://hassio/snapshots/<redacted>/download
  08-28 09:46:42 TRACE [backup.tracing_session]   sent headers:
  08-28 09:46:42 TRACE [backup.tracing_session]     Authorization: <redacted>
  08-28 09:46:42 TRACE [backup.tracing_session] Request ending: GET http://hassio/snapshots/<redacted>/download
  08-28 09:46:42 TRACE [backup.tracing_session]   status: 200
  08-28 09:46:42 TRACE [backup.tracing_session]   received headers:
  08-28 09:46:42 TRACE [backup.tracing_session]     Content-Type: application/tar
  08-28 09:46:42 TRACE [backup.tracing_session]     Last-Modified: Sat, 22 Aug 2020 23:34:44 GMT
  08-28 09:46:42 TRACE [backup.tracing_session]     Content-Length: 2676981760
  08-28 09:46:42 TRACE [backup.tracing_session]     Accept-Ranges: bytes
  08-28 09:46:42 TRACE [backup.tracing_session]     Date: Fri, 28 Aug 2020 07:46:42 GMT
  08-28 09:46:42 TRACE [backup.tracing_session]     Server: Python/3.8 aiohttp/3.6.2
   ```

**Comment by sabeechen** [comment]
I've looked into this a little bit, and only just now made the connection that 2GB is 1024 * 1024 * 1024 * 2 = 2^31, or otherwise close to the maximum size of a signed 32 bit integer.
Getting the supervisor to create a snapshot of a specific size is surprisingly tricky because they're compressed, but I've verified that a snapshot of 2048Mb fails to download and one of 1974MB works fine.


So my guess is that somewhere something doesn't like having a file size that doesn't fit into a 32 bit int.  That would explain why this only seems to happen on 32bit platforms.

The way the supervisor serves a snapshot is pretty straightforward and does not even make reference to a snapshot's size:
```python
    async def download(self, request):
        """Download a snapshot file."""
        snapshot = self._extract_snapshot(request)

        _LOGGER.info("Downloading snapshot %s", snapshot.slug)
        response = web.FileResponse(snapshot.tarfile)
        response.content_type = CONTENT_TYPE_TAR
        response.headers[
            CONTENT_DISPOSITION
        ] = f"attachment; filename={RE_SLUGIFY_NAME.sub('_', snapshot.name)}.tar"
        return response
```

So, I'm guessing the problem is actually in aiohttp.   Python integers can be arbitrarily large in a platform independent way, but maybe there is some C code involved down the chain somewhere thats failing?  Maybe an OS call?

I need help from someone who knows more about how the supervisor.

**Comment by ludeeus** [comment]
Can you retry that with the current dev version of the supervisor (2020.10.dev2605)?

**Comment by sabeechen** [comment]
Can you point me toward something that explains how to install the dev version?  I found [this](https://github.com/home-assistant/supervisor#development) but I am not a competent supervisor dev and find myself rather confounded by how all build chains and environments work together.

**Comment by ludeeus** [comment]
These 3 commands should get you there :)

```
ha su options -c dev
ha su reload
ha su upgrade
```

**Comment by sabeechen** [comment]
Ah thank you, that has undoubtedly saved me a great deal of time.  I was able to upgrade to 2020.10.dev2605
![image](https://user-images.githubusercontent.com/21026774/97236433-beecc800-17aa-11eb-85b6-a9a7fe484331.png)

Unfortunately the problem persists, same behavior as before.

**Comment by ludeeus** [comment]
That sucks, reason I wanted you to try is that aiohttp was bumped in the supervisor earlier today.

**Comment by sabeechen** [comment]
It was worth a shot.  Any other ideas?  I'm willing to try anything I can do.  I get *a lot* of bug reports in my addon about this because it makes very visible use of the snapshot API.

**Comment by ludeeus** [comment]
Can you try using `curl` with the `-v` arg?
<https://developers.home-assistant.io/docs/api/supervisor/examples>

**Comment by ludeeus** [comment]
I'm able to reproduce it

This is the issue:
> OverflowError: Python int too large to convert to C ssize_t

**Comment by sabeechen** [comment]
Awesome, thank you guys for taking a look.  Wouldn't have suspected the problem was that far down the stack.

I'm not sure what the supervisor's release cycle is like, is there a way to know when this will be in a release?

**Comment by ludeeus** [comment]
It's now released to the beta channel @sabeechen (2020.10.1)

**Comment by sabeechen** [comment]
It looks like this issue has popped up again with HA verison 2023.6.0 and supervisor version 2023.06.1 (32 bit)

It symptomatically looks the same, the supervisor prints this error this error when serving a backup over 2GB.
```
 File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 458, in _handle_request
   reset = await self.finish_response(request, resp, start_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 611, in finish_response
   await prepare_meth(request)
 File "/usr/local/lib/python3.11/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
   return await self._sendfile(request, fobj, offset, count)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
   await loop.sendfile(transport, fobj, offset, count)
 File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1185, in sendfile
   return await self._sendfile_native(transport, file,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 725, in _sendfile_native
   return await self.sock_sendfile(transp._sock, file, offset, count,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/asyncio/base_events.py", line 881, in sock_sendfile
   return await self._sock_sendfile_native(sock, file,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 373, in _sock_sendfile_native
   return await fut
          ^^^^^^^^^
 File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 395, in _sock_sendfile_native_impl
   sent = os.sendfile(fd, fileno, offset, blocksize)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C ssize_t
```

For context one of my users initially reported it [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/857).  I'd guess its related to the recent python version update.

**Comment by sabeechen** [comment]
I've filed [a new issue](https://github.com/home-assistant/supervisor/issues/4375) for the new error, since I can't re-open this one.
