### ISSUE TITLE
Cannot update supervisor (243 and 244) - RPi4

### ISSUE THREAD

**Issue by rursache** [home-assistant/supervisor#2066]
hey guys,

i've just upgraded from RPi3 to RPi4 and i had to move hass as well. i also switched from a 16gb card to a 32gb one. i did a full backup on pi3, installed hass on the 32gb card, put it in rpi4, updated my static dhcp in router to match the rpi4 and everything is working fine (after snapshot restore) but i cannot update to supervisor 243

```
20-09-15 09:58:39 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 243

20-09-15 09:58:39 INFO (SyncWorker_3) [supervisor.docker.interface] Pull image homeassistant/armv7-hassio-supervisor tag 243.

20-09-15 09:59:18 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install homeassistant/armv7-hassio-supervisor:243 -> 404 Client Error: Not Found ("no such image: homeassistant/armv7-hassio-supervisor:243: No such image: homeassistant/armv7-hassio-supervisor:243").

20-09-15 09:59:18 INFO (SyncWorker_3) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 23.7 GiB

20-09-15 09:59:18 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed!
```

any clue? i have enough space, i can install addons and everything else works fine

same issue with supervisor 244

thanks

**Comment by rursache** [comment]
more logs from supervisor:

```
file "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: homeassistant/armv7-hassio-supervisor:244: No such image: homeassistant/armv7-hassio-supervisor:244")
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/supervisor.py", line 112, in update
    await self.instance.install(
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/interface.py", line 111, in _install
    raise DockerAPIError() from err
supervisor.exceptions.DockerAPIError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 138, in _update_supervisor
    await self.sys_supervisor.update()
  File "/usr/src/supervisor/supervisor/supervisor.py", line 120, in update
    raise SupervisorUpdateError() from err
supervisor.exceptions.SupervisorUpdateError
```

**Comment by ludeeus** [comment]
You might have an issue in the overlay, run `ha supervisor repair`

**Comment by keyute** [comment]
is there a proper solution to this? i am currently experiencing this error as well. 

`20-11-06 03:21:34 ERROR (SyncWorker_4) [supervisor.docker.interface] Can't install homeassistant/amd64-hassio-supervisor:2020.11.0 -> 404 Client Error: Not Found ("no such image: homeassistant/amd64-hassio-supervisor:2020.11.0: No such image: homeassistant/amd64-hassio-supervisor:2020.11.0").
20-11-06 03:21:34 INFO (SyncWorker_4) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 24.9 GiB
20-11-06 03:21:34 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed!`

**Comment by rursache** [comment]
i only managed to fix this by making a backup, a clean install on a formatted sd card and then restore from backup. very weird and annoying tho

**Comment by dangel666** [comment]
@keyute  and others - I found that the following healed this (i've just updated hassio to 5.8 from 5.2):

1. ssh in
2. run "ha supervisor repair" ->wait
3. run "ha supervisor update" -> wait a while for it to restart and it should be on the latest build and all is well 👍

**Comment by lancelon** [comment]
Any ideas if [re-imaging an SD card then restoring a snapshot](https://github.com/home-assistant/supervisor/issues/1506#issuecomment-774731371) is my best bet if I'm experiencing some kind of weird bug?
