### ISSUE TITLE
Add-on: update while restart result in disaster

### ISSUE THREAD

**Issue by jrbenito** [home-assistant/supervisor#2084]
**Home Assistant release with the issue:**
0.115.5

**Operating environment (HassOS/Generic):**
HassOS 4.13

**Supervisor logs:**

```
20-10-01 16:49:23 INFO (SyncWorker_4) [supervisor.docker.interface] Stop addon_a0d7b954_influxdb application
20-10-01 16:49:25 ERROR (MainThread) [supervisor.utils] Can't execute update while a task is in progress
20-10-01 16:49:25 ERROR (MainThread) [supervisor.utils] Can't execute cleanup while a task is in progress
20-10-01 16:49:25 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_influxdb' successfully updated
20-10-01 16:49:25 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_influxdb already running!
20-10-01 16:49:28 INFO (SyncWorker_4) [supervisor.docker.interface] Clean addon_a0d7b954_influxdb application
20-10-01 16:49:28 ERROR (SyncWorker_5) [supervisor.docker] Image hassioaddons/influxdb-amd64 not exists for addon_a0d7b954_influxdb
20-10-01 16:49:33 ERROR (SyncWorker_3) [supervisor.docker] Image hassioaddons/influxdb-amd64 not exists for addon_a0d7b954_influxdb
20-10-01 16:49:37 ERROR (SyncWorker_1) [supervisor.docker] Image hassioaddons/influxdb-amd64 not exists for addon_a0d7b954_influxdb
20-10-01 16:49:40 ERROR (SyncWorker_5) [supervisor.docker] Image hassioaddons/influxdb-amd64 not exists for addon_a0d7b954_influxdb
20-10-01 16:49:51 ERROR (SyncWorker_3) [supervisor.docker] Image hassioaddons/influxdb-amd64 not exists for addon_a0d7b954_influxdb
```
And after reboot, core says:

`20-10-01 16:55:31 ERROR (SyncWorker_0) [supervisor.docker] Image hassioaddons/influxdb-amd64 not exists for addon_a0d7b954_influxdb`

**Description of problem:**

I had InfluxDb add one running, I pressed `restart` option in the UI. While it was restarting, I accidentally hit `update`. As result, there were no image from influxDb, supervisor lost track of it and I rebooted the system. After reboot it was still missing. So I issued a `supervisor repair` command. It deleted all references to my InfluxDB and I had to reinstall it, but every data was gone. I lost my databases. (sure, I do have backup)

I do believe that this race condition need to be avoided. I did it by mistake, but this might happen o others.

**Comment by ludeeus** [comment]
Restarting Home Assistant (which you do with the restart button) does not affect the supervisor or Add-ons.
Are you sure that is what you were doing?

**Comment by jrbenito** [comment]
Hi,

> Restarting Home Assistant (which you do with the restart button) does not affect the supervisor or Add-ons.
> Are you sure that is what you were doing?

I believe I was not clear, sorry.

I was in the supervisor screen, clicked on InfluxDB add on and issue a restart (clicked on restart link of the InfluxDB add on). This was with purpose, I wanted InfluxDB to restart. However, while it was still restarting, I accidentally hit the update button (of the InfluxDB add on) and, there was an update available. The restart process seems to had stop in the middle and immediately HA says it was upgraded. 

At this point, the InfluxDB was stopped. Try to start it presents an error box saying "There was an error starting...", logs show:
` 20-10-01 16:55:31 ERROR (SyncWorker_0) [supervisor.docker] Image hassioaddons/influxdb-amd64 not exists for addon_a0d7b954_influxdb`

hence I tried reboot the machine, in my mind, something in the middle of the update had failed and a reboot could help. No look! Still same error message. So I hit uninstall button (infludDB), and reinstall. (*here I think that I lost everything, I believe that uninstall also remove volume of the influxdb).

So, yes, I am sure that is what I was doing.

Thanks a lot for you help.

**Comment by ludeeus** [comment]
Oh, so you updated the add-on while it was restarting the same add-on, that gives something that should be reproducible :+1: 

You are correct that a uninstall will remove the data directory and every other reference to it.
