### ISSUE TITLE
Possible discrepancy in /etc/hosts and /etc/hostname

### ISSUE THREAD

**Issue by bettio** [home-assistant/supervisor#2085]
**Home Assistant release with the issue:**
4.13

**Operating environment (HassOS/Generic):**
HassOS

**Description of problem:**

I was checking the content of the overlay filesystem and I realized that while `/etc/hostname` was set to `myhostname`, `/etc/hosts` was still:
```
127.0.0.1       localhost
127.0.1.1       homeassistant
```

Usual behavior on Linux systems is having a similar `/etc/hosts` (assuming `myhostname` is the new hostname):
```
127.0.0.1       localhost
127.0.1.1       myhostname
```

I'm not sure if it is a real bug, however this is quite different from the usual behavior and I have no idea if it actually causes problems.

Feel free to close this issue if it is an intended behavior and thanks for all your amazing work.

**Comment by ludeeus** [comment]
It does not matter as we use the [CoreDNS](https://github.com/home-assistant/plugin-dns) plugin to resolve the names and not the file on your host :+1:
