### ISSUE TITLE
Add-on doesn't does not start anymore

### ISSUE THREAD

**Issue by monpelaud** [home-assistant/supervisor#2087]
**Home Assistant release with the issue:**
- Frontend -> Configuration -> Info
arch: armv7
channel: stable
docker: 19.03.11
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "4.13"
homeassistant: 0.115.6
hostname: hassio
logging: info
machine: raspberrypi3
operating_system: HassOS 4.13
supervisor: "245"
supported: true
supported_arch:
- armv7
- armhf
timezone: Europe/Paris

**Supervisor logs:**
ERROR (SyncWorker_4) [supervisor.docker] Image hassioaddons/motioneye not exists for addon_a0d7b954_motioneye

**Description of problem:**
Hi,
I'm using Hassio and since upgrade Home Assistant to 0.115.6 Motioneye Add-on does not start anymore.
Error message in system log:
ERROR (SyncWorker_4) [supervisor.docker] Image hassioaddons/motioneye not exists for addon_a0d7b954_motioneye

Thanks for your help.

Best regards

**Comment by ludeeus** [comment]
Run `ha su repair`

**Comment by monpelaud** [comment]
Wow, that is quick support!
This solved my problem.
Thank you very much.
