### ISSUE TITLE
Feature request: Editable snapshot name

### ISSUE THREAD

**Issue by uphillbattle** [home-assistant/supervisor#2098]
**Home Assistant release with the issue:**

All

**Operating environment (HassOS/Generic):**

Debian 10

**Supervisor logs:**

N/A

**Description of problem:**
I run an automated daily (nightly, actually) snapshot and the snapshots are automatically named "Automated Backup YYYY-MM-DD". I keep deleting the ones that I don't want to save for a longer period, but the ones that I keep for a while I would love to rename so that I can easily see which is which. AFAIK, there is no way to rename the snapshots, but I would love it if there was.

![image](https://user-images.githubusercontent.com/15340540/95170589-fe7c5180-07b4-11eb-9f1d-276db29331a7.png)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
