### ISSUE TITLE
Snapshots: allow to write a description

### ISSUE THREAD

**Issue by jrial** [home-assistant/supervisor#2104]
This is a feature request, so I dispensed with the bug template. Sometimes I make a lot of snapshots in the same day while incrementally improving my setup, and it would be nice if I could write a little description text for each snapshot. There could be a box in the create snapshots part of the UI for text entry, it would then display at the bottom of each snapshot for which such text as entered, and it could be editable in the modal that opens when you click the snapshot.

**Comment by pvizeli** [comment]
- This is for bugs only. Feature and enhancement requests should go in our community forum: https://community.home-assistant.io/c/feature-requests

**Comment by jrial** [comment]
Sorry, I was unaware. Thanks for pointing me in the right direction.
