### ISSUE TITLE
Logging Driver Journald / Unsupported Installation

### ISSUE THREAD

**Issue by davidh2k** [home-assistant/supervisor#2134]
According to https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md it is expected to have the default logging driver configured to journald. 

It's possible to set this per container individually, rather than changing this daemon wide:

https://docs.docker.com/config/containers/logging/configure/

That would eliminate one trigger for the unsupported installation warning, which could be avoided by the supervisor itself.

Greetings
David

**Comment by pvizeli** [comment]
Per definition, only supported are system which only runs supervisor.
