### ISSUE TITLE
[supervisor.utils.gdbus] Can't parse when updating service information.

### ISSUE THREAD

**Issue by LucidityCrash** [home-assistant/supervisor#2151]
**Home Assistant release with the issue:**

arch | x86_64
-- | --
chassis | desktop
dev | false
docker | true
docker_version | 19.03.13
hassio | true
host_os | Ubuntu 20.04.1 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 5.4.0-51-generic
python_version | 3.8.5
supervisor | 250
timezone | Europe/London
version | 0.116.4
virtualenv | false

**Operating environment (HassOS/Generic):**
Generic - ubuntu 20.04.1 LTS
Docker version 19.03.13, build 4484c46d9d

**Supervisor logs:**
Attached as quite long
[supervisor_log.txt](https://github.com/home-assistant/supervisor/files/5406874/supervisor_log.txt)

**Description of problem:**
During startup of Supervisor Container the logs show : 
20-10-20 04:52:02 INFO (MainThread) [supervisor.host.services] Updating service information
20-10-20 04:52:02 ERROR (MainThread) [supervisor.utils.gdbus] Can't parse '.....' - Expecting ',' delimiter: line 1 column 47541 (char 47540)

this is around this section : 
["rng-tools.service", "Add entropy to /dev/random "s pool a hardware RNG\", "loaded', "active", "running", "", "/org/freedesktop/systemd1/unit/rng_2dtools_2eservice", 0, "", "/"]

systemctl status rng-tools.service
● rng-tools.service - Add entropy to /dev/random 's pool a hardware RNG
     Loaded: loaded (/lib/systemd/system/rng-tools.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-10-14 09:00:48 BST; 5 days ago
   Main PID: 1250 (rngd)
      Tasks: 1 (limit: 28540)
     Memory: 320.0K
     CGroup: /system.slice/rng-tools.service
             └─1250 /usr/sbin/rngd -r /dev/hwrng -f

Oct 14 09:00:48 minerva systemd[1]: Started Add entropy to /dev/random 's pool a hardware RNG.

Looks like it is having issues with the ' in the status of rng-tools.

**Comment by pvizeli** [comment]
`Ubuntu 20.04.1 LTS` is not supported. Feel free to make a PR to fix that, but we do not track such issue
