### ISSUE TITLE
Funny log message

### ISSUE THREAD

**Issue by PieBru** [home-assistant/supervisor#2184]
**Home Assistant release with the issue:**
 0.116

**Operating environment (HassOS/Generic):**
 HassOS 4.15 (all updated, no updates pending)

**Supervisor logs:**
 N/A

**Description of problem:** Failed to get supervisor logs... see supervisor logs.

![HASS_Screenshot from 2020-10-28 09-40-36](https://user-images.githubusercontent.com/6537434/97413009-95df4b00-1902-11eb-9798-081d4ecc5179.png)

**Comment by pvizeli** [comment]
http://MY_IP:4357

We need the logs from that website

**Comment by ludeeus** [comment]
Can you run `ha su logs`?

**Comment by PieBru** [comment]
@ludeeus When it happens the SSH addon doesn't start.

I'm trying to reproduce that funny message, which may lead to a more serious startup sequence problem.
I'm not sure, but it may be related to LAN/internet availability at HASS startup time.
It's on my RV (camper-van) server, a Raspi4 4GB with HassOS booted from SD and `hassos-data` partition on SSD, but recently I saw the same log message on my home server.
My RV internet connectivity is through a list of wifi devices (android tethering or other WLAN), all accessed by the main OpenWrt router thenks to the TravelMate addon.
When I apply power to the whole enchilada, the now blazing fast Hass sometimes starts before the OpenWrt and/or the external WLAN provider.

Any hint on how I can help narrow down this issue?
Piero

**Comment by ludeeus** [comment]
Not really, we need the logs from that page, or that command.
In the console/network tab of the developer-tools in your browser, do you get any errors there?

**Comment by PieBru** [comment]
Sorry, I didn't reproduce the same problem since then, but as it appears
occasionally I will try to get the above logs.
I think it's a time-dependent problem during HassOS boot.
As far as I remember, ssh and other addons did not start, so I wasn't able
to access the system via ssh.
I will report back when it will occur again.
Thank you.

**Comment by pvizeli** [comment]
> I didn't reproduce the same problem
Will be fix in future
