### ISSUE TITLE
Seeing a lot of "No valid ingress session" errors with 0.117.0b6, sometimes resulting in a popup with "Unable to load the panel source: /api/hassio/app/entrypoint.js."

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/supervisor#2185]
**Home Assistant release with the issue:**

0.117.0b6, HassOS 4.15, Supervisor 2020.10.0

**Operating environment (HassOS/Generic):**

HassOS in a KVM

**Supervisor logs:**

```text
20-10-28 16:34:33 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:35:15 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:35:57 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:36:39 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:37:21 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:38:03 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:38:45 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:38:58 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:39:27 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:39:40 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:40:09 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:40:22 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:40:51 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:41:03 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:41:27 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from a0d7b954_ssh
```

This bit is from the latest occurrence:

```text
20-10-28 16:54:51 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:55:25 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-10-28 16:55:33 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session a33a198fc8d5a8c8051ab4a75c5ad59ba26a1445b45c2c1214b32b0f55bab79b849a90af6c41792abc2d63da36cd987b075d699fb5d7b8856e562c8a756f6aea
20-10-28 16:55:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
20-10-28 16:56:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-10-28 16:56:01 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
20-10-28 16:56:01 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

I also periodically see these in the HA log:

```text
2020-10-28 09:40:55 ERROR (MainThread) [homeassistant.components.hassio.http] Client error on api supervisor/info request 
2020-10-28 09:42:19 ERROR (MainThread) [homeassistant.components.hassio.http] Client error on api app/entrypoint.js request 
```

**Description of problem:**

Somewhere in the 0.117 beta cycle accessing the Supervisor page has become flaky and unreliable.  Sometimes clicking on the Supervisor sidebar icon results in several seconds of delay before the Dashboard comes up, and often it never comes up (just a black screen).  Refreshing the page sometimes makes the Dashboard appear, sometimes I get an "Unable to load the panel source: /api/hassio/app/entrypoint.js." popup, and sometimes it just stays at a black screen.  Going back to the "Overview" Lovelace page and back into Supervisor may or may not allow me to get to the Supervisor page (same failure possibilities as before).  When it fails, I always get a "No valid ingress session" in the logs, as shown above.  It happens on both mobile and desktop, and both with and without going through my reverse proxy - I can reproduce it just going straight to http://192.168.1.169:8123/hassio/dashboard, for instance.

Restarting HA or restarting the KVM doesn't appear to have an effect on the problem.  Neither does clearing the cache or logging out of HA and logging back in.  The problem persists throughout.

I realize that HassOS, Supervisor, and HA have different release timelines, so I don't know exactly where the problem showed up.  It was certainly more reliable a few weeks ago.

**Comment by JamoDevNich** [comment]
I had a similar issue pop up - ingress addons were saying "no valid ingress session" in the logs, and refused to load with a 401 unauthorised error. My supervisor version is 2020.11.0  

Somehow this doesn't happen when using HTTPS...?  

You could try with HTTPS and see if the error goes away. It'd be nice if we knew the underlying issue though or at least how to identify it  

**Pictures:**  

![Image showing ingress not working on HTTP](https://i.imgur.com/rEq8hYR.png) ![Image showing ingress working perfectly on HTTPS](https://i.imgur.com/Clmm6D3.png)

**Logs:**  
```
20-11-04 16:43:48 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
20-11-04 16:46:51 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
```

**Comment by balloob** [comment]
Does this happen only in Firefox or also in other browsers?

**Comment by rccoleman** [comment]
I only use Chrome on Mac and Windows and Safari webview on iOS. Still getting a lots and lots of them with 0.117.3.

**Comment by balloob** [comment]
I wonder if it was the VS Code update no longer making regular Rest requests but instead relying on just the websocket, and so the session is invalidated. It was [updated 20 days ago](https://github.com/hassio-addons/addon-vscode/releases). Can you reproduce it with other add-ons?

**Comment by rccoleman** [comment]
I closed the VSCode tabs on the two machines that I typically use and I haven't see any sign of the logs, so I think it is related to that addon.  I'll open a tab for that and see if they come back.

**Comment by rccoleman** [comment]
Nothing so far.  Maybe just closing the tab and reopening it helped clear something out that wasn't affected by control/shift reload.

**Comment by rccoleman** [comment]
And now I'm getting them again.  Is there an easy way to track down which browser instance corresponds to the ingress session?  I can find the tokens in the Application/Local Storage section of the browser tools and I don't see the token that I see in the logs, but it may be completely unrelated.

**Comment by balloob** [comment]
No, but I should have a fix here https://github.com/home-assistant/frontend/pull/7610

**Comment by rccoleman** [comment]
Fantastic, thanks!
