### ISSUE TITLE
Feature Request: Snapshot complete event

### ISSUE THREAD

**Issue by smiller171** [home-assistant/supervisor#2193]
Bumping #1062 and #839 since those were both closed as stale.

Would really like an event to be fired when a system snapshot is complete so that any automations for moving that snapshot to offsite backup can be triggered.

**Comment by ludeeus** [comment]
For feature requests please use the [forum section for feature requests](https://community.home-assistant.io/c/feature-requests/13), thanks :+1:

**Comment by smiller171** [comment]
Personally, I think that's a _terrible_ policy...
