### ISSUE TITLE
External link problem, can not open link

### ISSUE THREAD

**Issue by anglrus** [home-assistant/supervisor#2196]
**Home Assistant release with the issue:**

arch | x86_64
chassis |  
dev | false
docker | true
docker_version | 18.09.8
hassio | true
host_os |  
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 3.10.102
python_version | 3.8.6
supervisor | 2020.10.0
timezone | Europe/Moscow
version | 0.117.1
virtualenv | false

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**

I can open 192.168.1.5:8123.
I can't open https://...duckdns.org:8123

Probably problem in Network manager. I tries to install but can't do it. Please could you give step by step instruction to fix.

**Comment by ludeeus** [comment]
Hi @anglrus :wave: 

This is the issue tracker for the supervisor, not a channel to help you set up external access.
Try reaching out on the [forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e), thanks :+1:
