### ISSUE TITLE
Backup Role Missing? (Invalid token for access /host/info)

### ISSUE THREAD

**Issue by ikifar2012** [home-assistant/supervisor#2201]
### Describe the issue
This error displays on any addon using the backup hassio_role
```
parse error: Expected string key before ':' at line 1, column 4
[03:51:39] ERROR: Unknown HTTP error occured
```
With the supervisor logs stating:
```
20-10-31 03:51:38 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on local/amd64-addon-remote_backup with version 4.3.6
20-10-31 03:51:39 WARNING (MainThread) [supervisor.api.security] /host/info no role for local_remote_backup
20-10-31 03:51:39 ERROR (MainThread) [supervisor.api.security] Invalid token for access /host/info
```

### Steps to reproduce

Add this to the config.json of any addon 
```json
  "hassio_api": true,
  "hassio_role": "backup",
```

### Environment details

- **Operating System:**: Debian Buster
- **Supervisor version:**: 2020.10.0
- **Home Assistant version**: 0.117.1

### Supervisor logs

See Above

</details>

**Comment by pvizeli** [comment]
They can use `/info` which add-ons have access.

**Comment by ikifar2012** [comment]
So then why am I getting this error?
