### ISSUE TITLE
Restore from snapshot on SSD

### ISSUE THREAD

**Issue by brianlane** [home-assistant/supervisor#2224]
## The problem
I restored from a snapshot onto a SSD no SD card on a RPi4 but now I can't update from 0.110.3 to 0.117.4

I get this error:

20-11-05 06:17:06 INFO (SyncWorker_1) [supervisor.docker.interface] Updating image homeassistant/raspberrypi4-64-homeassistant:0.110.3 to homeassistant/raspberrypi4-64-homeassistant:0.117.4
20-11-05 06:17:06 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image homeassistant/raspberrypi4-64-homeassistant with tag 0.117.4.
20-11-05 06:17:23 ERROR (SyncWorker_1) [supervisor.docker.interface] Can’t install homeassistant/raspberrypi4-64-homeassistant:0.117.4 -> 404 Client Error: Not Found (“no such image: homeassistant/raspberrypi4-64-homeassistant:0.117.4: No such image: homeassistant/raspberrypi4-64-homeassistant:0.117.4”).
20-11-05 06:17:23 INFO (SyncWorker_1) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 204.5 GiB
20-11-05 06:17:23 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed

I know this means there is not enough space however there is 204 gbs available?

## Environment

- Home Assistant Core release with the issue: 0.110.3
- Last working Home Assistant Core release (if known): 0.110.3
- Operating environment (OS/Container/Supervised/Core): OS
- Integration causing this issue: Home Assistant Core
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

I update through the Lovelace UI and it errors out then loses connection. I have to do a hard reboot then start with ha start with keyboard hooked up to RPi4.

## Traceback/Error logs

```txt

```
no such image homeassistant/qemux86-64-homeassistant 0.110 4

**Comment by ludeeus** [comment]
Run `ha su repair` and try again when that completes.

**Comment by brianlane** [comment]
Thank you!

**Comment by brianlane** [comment]
I updated my software to 0.117.5 and now HA won’t start and getting same error.

![96EA7457-F3E5-41BB-B95C-2D979370FA37](https://user-images.githubusercontent.com/16847592/98428020-e2422d80-205c-11eb-8325-9644ef424597.jpeg)

**Comment by brianlane** [comment]
I reverted here is the code:

`20-11-07 01:14:11 INFO (MainThread) [supervisor.core] Starting repair of Supervisor Environment
20-11-07 01:14:11 INFO (SyncWorker_3) [supervisor.docker] Prune stale containers
20-11-07 01:14:11 INFO (SyncWorker_3) [supervisor.docker] Prune stale images
20-11-07 01:14:14 INFO (SyncWorker_3) [supervisor.docker] Prune stale builds
20-11-07 01:14:14 INFO (SyncWorker_3) [supervisor.docker] Prune stale volumes
20-11-07 01:14:14 INFO (SyncWorker_3) [supervisor.docker] Prune stale networks
20-11-07 01:14:14 INFO (SyncWorker_3) [supervisor.docker] Fix stale container on hassio network
20-11-07 01:14:14 INFO (SyncWorker_3) [supervisor.docker] Fix stale container on host network
20-11-07 01:14:14 INFO (MainThread) [supervisor.addons] Found 3 add-ons to repair
20-11-07 01:14:14 INFO (MainThread) [supervisor.addons] Repairing for add-on: a0d7b954_ssh
20-11-07 01:14:14 INFO (SyncWorker_7) [supervisor.docker.interface] Downloading docker image hassioaddons/ssh-aarch64 with tag 7.7.0.
20-11-07 01:14:54 INFO (MainThread) [supervisor.addons] Repairing for add-on: core_check_config
20-11-07 01:14:54 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-check_config with tag 3.6.0.
20-11-07 01:15:25 INFO (MainThread) [supervisor.addons] Repairing for add-on: cebe7a76_hassio_google_drive_backup
20-11-07 01:15:25 INFO (SyncWorker_7) [supervisor.docker.interface] Downloading docker image sabeechen/hassio-google-drive-backup-aarch64 with tag 0.102.0.
20-11-07 01:15:26 INFO (MainThread) [supervisor.homeassistant.core] Repair Home Assistant 0.117.5
20-11-07 01:15:26 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image homeassistant/raspberrypi4-64-homeassistant with tag 0.117.5.
20-11-07 01:15:30 ERROR (SyncWorker_4) [supervisor.docker.interface] Can't install homeassistant/raspberrypi4-64-homeassistant:0.117.5 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi4-64-homeassistant:0.117.5: No such image: homeassistant/raspberrypi4-64-homeassistant:0.117.5").
20-11-07 01:15:30 INFO (SyncWorker_4) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 203.5 GiB
20-11-07 01:15:30 ERROR (MainThread) [supervisor.homeassistant.core] Repairing of Home Assistant failed
20-11-07 01:15:30 INFO (MainThread) [supervisor.supervisor] Repairing Supervisor 2020.11.0
20-11-07 01:15:30 INFO (MainThread) [supervisor.core] Finished repair of Supervisor Environment
20-11-07 01:17:32 INFO (MainThread) [supervisor.homeassistant] Update pulse/client.config: /data/tmp/homeassistant_pulse
20-11-07 01:17:32 ERROR (SyncWorker_1) [supervisor.docker] Image homeassistant/raspberrypi4-64-homeassistant not exists for homeassistant
20-11-07 01:17:57 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 0.117.5
20-11-07 01:17:57 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image homeassistant/raspberrypi4-64-homeassistant:0.117.5 to homeassistant/raspberrypi4-64-homeassistant:0.117.5
20-11-07 01:17:57 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image homeassistant/raspberrypi4-64-homeassistant with tag 0.117.5.
20-11-07 01:18:01 ERROR (SyncWorker_5) [supervisor.docker.interface] Can't install homeassistant/raspberrypi4-64-homeassistant:0.117.5 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi4-64-homeassistant:0.117.5: No such image: homeassistant/raspberrypi4-64-homeassistant:0.117.5").
20-11-07 01:18:01 INFO (SyncWorker_5) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 203.5 GiB
20-11-07 01:18:01 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed
20-11-07 01:41:12 INFO (MainThread) [supervisor.homeassistant] Update pulse/client.config: /data/tmp/homeassistant_pulse
20-11-07 01:41:12 ERROR (SyncWorker_7) [supervisor.docker] Image homeassistant/raspberrypi4-64-homeassistant not exists for homeassistant
20-11-07 02:05:11 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-11-07 02:22:45 INFO (MainThread) [supervisor.core] Starting repair of Supervisor Environment
20-11-07 02:22:45 INFO (SyncWorker_6) [supervisor.docker] Prune stale containers
20-11-07 02:22:45 INFO (SyncWorker_6) [supervisor.docker] Prune stale images
20-11-07 02:22:48 INFO (SyncWorker_6) [supervisor.docker] Prune stale builds
20-11-07 02:22:48 INFO (SyncWorker_6) [supervisor.docker] Prune stale volumes
20-11-07 02:22:48 INFO (SyncWorker_6) [supervisor.docker] Prune stale networks
20-11-07 02:22:48 INFO (SyncWorker_6) [supervisor.docker] Fix stale container on hassio network
20-11-07 02:22:48 INFO (SyncWorker_6) [supervisor.docker] Fix stale container on host network
20-11-07 02:22:48 INFO (MainThread) [supervisor.addons] Found 3 add-ons to repair
20-11-07 02:22:48 INFO (MainThread) [supervisor.addons] Repairing for add-on: a0d7b954_ssh
20-11-07 02:22:48 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image hassioaddons/ssh-aarch64 with tag 7.7.0.
20-11-07 02:23:30 INFO (MainThread) [supervisor.addons] Repairing for add-on: core_check_config
20-11-07 02:23:30 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-check_config with tag 3.6.0.
20-11-07 02:24:02 INFO (MainThread) [supervisor.addons] Repairing for add-on: cebe7a76_hassio_google_drive_backup
20-11-07 02:24:02 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image sabeechen/hassio-google-drive-backup-aarch64 with tag 0.102.0.
20-11-07 02:24:03 INFO (MainThread) [supervisor.homeassistant.core] Repair Home Assistant 0.117.5
20-11-07 02:24:03 INFO (SyncWorker_7) [supervisor.docker.interface] Downloading docker image homeassistant/raspberrypi4-64-homeassistant with tag 0.117.5.
20-11-07 02:24:06 ERROR (SyncWorker_7) [supervisor.docker.interface] Can't install homeassistant/raspberrypi4-64-homeassistant:0.117.5 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi4-64-homeassistant:0.117.5: No such image: homeassistant/raspberrypi4-64-homeassistant:0.117.5").
20-11-07 02:24:06 INFO (SyncWorker_7) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 203.5 GiB
20-11-07 02:24:06 ERROR (MainThread) [supervisor.homeassistant.core] Repairing of Home Assistant failed
20-11-07 02:24:06 INFO (MainThread) [supervisor.supervisor] Repairing Supervisor 2020.11.0
20-11-07 02:24:07 INFO (MainThread) [supervisor.core] Finished repair of Supervisor Environment
20-11-07 03:05:12 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
20-11-07 03:05:12 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-11-07 03:11:52 INFO (MainThread) [supervisor.host.info] Updating local host information
20-11-07 03:11:52 INFO (MainThread) [supervisor.host.services] Updating service information
20-11-07 03:11:52 INFO (MainThread) [supervisor.host.network] Updating local network information
20-11-07 03:11:53 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
20-11-07 03:32:13 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 0.117.4`

**Comment by brianlane** [comment]
ha su repair doesn't work now that I reverted and try to update to 0.117.5 

`20-11-07 21:04:57 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image homeassistant/raspberrypi4-64-homeassistant with tag 0.117.5.
20-11-07 21:05:00 ERROR (SyncWorker_2) [supervisor.docker.interface] Can't install homeassistant/raspberrypi4-64-homeassistant:0.117.5 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi4-64-homeassistant:0.117.5: No such image: homeassistant/raspberrypi4-64-homeassistant:0.117.5").
20-11-07 21:05:00 INFO (SyncWorker_2) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 202.7 GiB
20-11-07 21:05:00 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed`

**Comment by brianlane** [comment]
It errors with the Directory block failed checksum and this warning:
EXT4-fs warning (device sda8): ext4_dirent_csum_verify:368: inode #5507602: comm dockerd: No space for directory leaf checksum. Please run e2fsck -D

**Comment by brianlane** [comment]
I ran that from the command line but it's not recognized by Home Assistant.

**Comment by Megasultan** [comment]
Hi Brianlane,

Did you ever resolve this issue?
I'm running into it now.
Flashing a Hassio 5.6 image to an 1TBSSD.
When i run the install sometimes the initial instal works but when i try to add any add-ons i see the same 404 error message.

Regards

**Comment by brianlane** [comment]
No solid solution. I would update and revert if the error occurred but I’m currently on the latest software without any issues.

**Comment by Megasultan** [comment]
Ok cool, thank you for the quick response. 
So are you running HA on an SSD? I'm running an old  version of HA on an ad card. And I'm looking to  move up the versions and move to booting from SSD. I read that the best way to do this was to update the boot driver on my pi4b and then flash hassio development 5.6 to ssd. Everything seem to be working but the I ran in to this issue. If you are booting from SSD how did you do it?

**Comment by brianlane** [comment]
Yeah I’m running HA from a rpi4 boot from ssd. You will need to update the boot driver, but I just followed the most popular guide online on how to do it. Good luck

**Comment by johntdyer** [comment]
I think I'm having the same problem

**Comment by brianlane** [comment]
Did you try the things mentioned above?

**Comment by Megasultan** [comment]
Hey 
I reflashed an image.
Which this time I managed to get to the HA set up screen.
I loaded a snapshot which and the ssh terminal 
I tried to install another add-on and hit the same issue.
I then logged on ssh ran ran this command.
ha su repair
And that seemed to fix everything.

**Comment by brianlane** [comment]
Seems hard to replicate unfortunately
