### ISSUE TITLE
Local add-on: Connection reset by peer

### ISSUE THREAD

**Issue by gimi87** [home-assistant/supervisor#2284]
### Describe the issue

Hello. I've an issue with the local add-on.
My local addon is using ASP.NET Core 3.1 based image to run. I tested everything on my QNAP's Docker and it is working. Images are downloaded and container is working fine. But on the Home Assistant instance i have following window:
![local_addon1](https://user-images.githubusercontent.com/22730088/99910955-7ebd2e80-2cf1-11eb-9537-1642ece15922.png)

Can you help me solve it?

### Steps to reproduce

1. Create a new ASP.NET Core 3.1 project
2. Provide 'config.json' file into root folder
3. Copy the project into Home Assistant 'addons' folder
4. Reload local addons and try to install it

### Enviroment details

- **Operating System:**: HassOS 4.17 (RPi 3B)
- **Supervisor version:**: 2020.11.0
- **Home Assistant version**: 0.118.2

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
20-11-22 17:30:50 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
20-11-22 17:30:55 INFO (SyncWorker_0) [supervisor.docker.addon] Starting build for local/armv7-addon-TestMe:0.2
20-11-22 17:30:55 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build local/armv7-addon-TestMe:0.2: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

</details>

**Comment by pvizeli** [comment]
Look like an build issue. Please build it with our build tools and push it to an docker hub
