### ISSUE TITLE
No root bash shell from console or port 22222

### ISSUE THREAD

**Issue by backcountrymountains** [home-assistant/supervisor#2285]
## The problem
I can't get a root shell either from the console directly by trying to login with root, or by ssh-ing in on port 22222. I need to manually install a dependency but I have no access to Hassio.

## Environment
```
System Health

Home Assistant Core Integration

version: 0.118.2
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.19.104
arch: x86_64
timezone: America/Denver

Hass.io

host_os: HassOS 3.11
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.5
disk_total: 9.1 GB
disk_used: 5.2 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.2.0), FTP (3.1.0), Mosquitto broker (5.1), RPC Shutdown (2.2), File editor (5.0.0), Log Viewer (0.9.1), zigbee2mqttassistant (0.3.147), SSH & Web Terminal (7.7.0), Terminal & SSH (8.9.1), Duck DNS (1.12.4), MariaDB (2.2.1), ESPHome (1.14.4), Portainer (1.0.0)

Lovelace

dashboards: 3
mode: yaml
views: 10
resources: 10
```
- Home Assistant Core release with the issue: 118.2
- Last working Home Assistant Core release (if known): 114
- Operating environment (OS/Container/Supervised/Core): Hassio VM, see above

## Traceback/Error logs

```
login as: root
Authenticating with public key "rsa-key-20190209"
Passphrase for key "rsa-key-20190209":
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

That's all I get in putty and it's the same with a keyboard at the console, no shell, just those lines. I'm not sure what I broke.

## Additional information

Is this the right place for this issue?

Thanks.

**Comment by frenck** [comment]
I've transferred this issue to the Supervisor. It is probably not right either, as it might be CLI or OS related as well. However, it is closer to where it needs to be, compared to the Core issue tracker.

As for you original reason to access that console:

>  I need to manually install a dependency

You probably won't get the system access you think you get using that route. What dependency are you trying to install?

**Comment by agners** [comment]
Is maybe HassOS 3.11 with the rather recent Supervisor the problem? Haven't tried that combination...

**Comment by pvizeli** [comment]
Please update our OS
