### ISSUE TITLE
"Supervisor is not privileged" even though it is

### ISSUE THREAD

**Issue by jo-me** [home-assistant/supervisor#2343]
### Describe the issue

Supervisor panel suddenly reports that my system is unhealthy due to "Supervisor is not privileged"

When I check the supervisor container it says that it is:
![image](https://user-images.githubusercontent.com/10351272/101192881-055ffd00-365c-11eb-9194-ce4d19a636ea.png)

### Steps to reproduce

1. ...
2. ...
3. ...

### Enviroment details

- **Operating System:**: xxx
```
ha host info
chassis: desktop
cpe: ""
deployment: ""
disk_free: 18.8
disk_total: 62.3
disk_used: 40.2
features:
- reboot
- shutdown
- services
- network
- hostname
hostname: adloko
kernel: 5.4.0-53-generic
operating_system: Ubuntu 18.04.5 LTS
```

- **Supervisor version:**: xxx

```
arch: amd64
channel: stable
debug: false
debug_block: false
diagnostics: null
healthy: false
ip_address: 172.30.32.2
logging: info
supported: false
timezone: Europe/Berlin
update_available: false
version: 2020.12.2
version_latest: 2020.12.2
wait_boot: 5
```

- **Home Assistant version**: xxx
```
arch: amd64
channel: stable
docker: 19.03.13
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 0.118.4
hostname: adloko
logging: info
machine: qemux86-64
operating_system: Ubuntu 18.04.5 LTS
supervisor: 2020.12.2
supported: false
supported_arch:
- amd64
- i386
timezone: Europe/Berlin
```

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```

20-12-04 16:43:40 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-04 16:43:57 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files

20-12-04 16:48:15 WARNING (MainThread) [supervisor.jobs] 'AddonManager.install' blocked from execution, system is not healthy

```

</details>

**Comment by jo-me** [comment]
I followed the hint behind the "not privileged" notice and ran the script again.
Did not change anything.

**Comment by jo-me** [comment]
Restart seems to fix it for now

Also see https://community.home-assistant.io/t/unable-to-update-supervisor-not-privileged/251511

**Comment by ludeeus** [comment]
There are to types of "privileged", the one that is added when the container is created, and access to HW monitoring, the first is solved by running the installation script, the other is solved buy updating and rebooting the host OS

**Comment by jo-me** [comment]
So when does it happen that this gets lost? 
When the supervisor container is updated without rebooting the system?

**Comment by derrick011** [comment]
@ludeeus 
When I rerun the script it will not resolve the problem.

The problem started after installing version 2020.12.6 of Supervisor.
Tried running the script and waited several hours than rebooted the OS and still same error.

Please reopen and address the problem because we cannot update HA anymore. So no new core updates nor Supervised Apps i.e. VCS. Updates

**Comment by frenck** [comment]
The issue has been raised for an unsupported system. If you have a supported system that causes this, please raise a new issue. Thanks 👍

**Comment by jerkovicl** [comment]
Error is showing up if host os is Ubuntu 20.04.1 aswell

**Comment by SamJongenelen** [comment]
Same here, Ubuntu 20 host. After clean boot things are running well. Next day this message occurs and indeed cannot update

**Comment by olskar** [comment]
Same issue here on Ubuntu 20. Is this a sneaky way to "get rid" of unsupported installations? :)

**Comment by matthew73210** [comment]
Just chipping in, on debian 10. Which I beleive to be a supported system. Has the same issue.

**Comment by frenck** [comment]
>  Is this a sneaky way to "get rid" of unsupported installations? :)

Is it not, udev hardware monitoring fails in most cases, which is an issue. This warning should have been in your logs for months already.


@matthew73210 Please raise a new issue if you have a supported system, with as many details as possible.

**Comment by jo-me** [comment]
So, whenever a supervisor update arrives the system becomes automatically unhealthy now for "unsupported" systems?

I found HA multiple times in the last week or so with all addons suddenly disabled and no hint why I could not update one (update button just flashed red with no indication why). Only then I went to look for issues elsewhere. There could be at least some kind of notification when the system gets flagged as unhealthy when it was previously ok.

I know that I'm running an unsupported installation but the spontaneous nature of supervisor updates are real liability to system stability. Installing them at any time leaves you at risk of breaking peoples systems (see introduction of DNS features) . 
It is ok if things have breaking changes, occasional bugs, or have additional hoops to jump through in case of unsupported systems, but those "fixing periods" need to be plannable. I don't want to worry every morning whether things broke overnight. I want to move updates to weekends when I can spend the time.

So, the solution would be quite simple: **There should be an option to opt-out of automatic supervisor updates.**

**Comment by jazzmonger** [comment]
Why is this issue closed when the problem remains for so many of us?  I'm on Supervisor Version 2020.12.6 and have resorted to the jobs.json fix. It's the only way to get around this annoying problem...

Jeff

**Comment by SamJongenelen** [comment]
I've updated my ubuntu host, now we wait for the supervisor update..
Clean boot and update when it comes 👍

**Comment by frenck** [comment]
I'm locking down this issue. Ubuntu is not supported, if you need help with unsupported systems, you can try the community forum.
