### ISSUE TITLE
TypeError: 'NoneType' object is not iterable in _calc_block_io for stats in blkio["io_service_bytes_recursive"]

### ISSUE THREAD

**Issue by gitolicious** [home-assistant/supervisor#2350]
### Describe the issue

Error messages are flooding my supervisor log. I am not 100% sure what they are related to but am suspecting the System Metrics view as that's not fully working for me (only showing disk usage).

```
20-12-05 18:01:07 ERROR (MainThread) [aiohttp.server] Error handling request
[...]
File "/usr/src/supervisor/supervisor/docker/stats.py", line 62, in _calc_block_io
    for stats in blkio["io_service_bytes_recursive"]:
TypeError: 'NoneType' object is not iterable
```
Full log: see below
Offending line:

https://github.com/home-assistant/supervisor/blob/4ff9da68ef5b9ba902b7a51ea1c9527df00bc19f/supervisor/docker/stats.py#L62

![image](https://user-images.githubusercontent.com/26963495/101260246-d9fa1280-372e-11eb-8328-55ab63576cb2.png)

### Steps to reproduce

1. Run current HomeAssistant and Supervisor on environment as stated below
2. Observe supervisor log

### Enviroment details

- **Operating System:**: Debian GNU/Linux 10 (buster), DietPi on Odroid N2
- **Supervisor version:**: 2020.12.6
- **Home Assistant version**: 0.118.5

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
20-12-05 18:02:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 133, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 195, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 60, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/homeassistant.py", line 122, in stats
    stats = await self.sys_homeassistant.core.stats()
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 305, in stats
    return await self.instance.stats()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/interface.py", line 476, in _stats
    return DockerStats(stats)
  File "/usr/src/supervisor/supervisor/docker/stats.py", line 36, in __init__
    self._calc_block_io(stats["blkio_stats"])
  File "/usr/src/supervisor/supervisor/docker/stats.py", line 62, in _calc_block_io
    for stats in blkio["io_service_bytes_recursive"]:
TypeError: 'NoneType' object is not iterable
```

</details>

**Comment by pvizeli** [comment]
Please add the information `ha info`

**Comment by pvizeli** [comment]
Please enable the reported issue and reproduce the issue. It will send a report to us and we will fix the issue. Thanks

**Comment by 0n3man** [comment]
I get this exact same exception.  I'm running HA version 2020.12.7 under a supervise install  on an odriod N2.  Any suggestion on how to resolve this? 

ha info provides:
channel: stable
docker: 20.10.1
features:
- reboot
- shutdown
- services
- hostname
hassos: null
homeassistant: 2020.12.1
hostname: odroid
logging: info
machine: odroid-n2
operating_system: Ubuntu 18.04.5 LTS
supervisor: 2020.12.7
supported: false
supported_arch:
- aarch64
- armv7
- armhf
timezone: America/New_York

**Comment by gitolicious** [comment]
No progress on my end. What I recognized: the timestamp of the error coincides with the time I am pressing the _Refresh_ button on the supervisor system logs. Not sure if this is always true.

**Comment by 0n3man** [comment]
Based on your comment I did some testing.  Turns out for me the message is generated every time I refresh the Supervisor->System tab page.  No other page generates the message. The refresh of just the supervisor log does not result in the error being generated.  You previously mentioned that your "System Metrics" only shows "Used Space", which is the same for me.  Seems possible that it could be tied with the failure related to access the system metrics.  I'll see if I can create a bug report.

**Comment by 0n3man** [comment]
Actually it appears I'm not allow to file a bug because I'm running Ubuntu 18.04, which is built off Debian Buster, but it's not Debian.  Hard to believe the most widely utilize linux distro isn't supported.  Maybe Pascal can help out.

**Comment by 0n3man** [comment]
Looking through the code there is no question that the issue happens when the system tries gather the metrics information.  While block IO isn't displayed on the screen the code attempts to pull the number of reads and writes, which throws the exception.

**Comment by 0n3man** [comment]
This is may be useful running "docker stats" show:
CONTAINER ID   NAME                CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O   PIDS
924399110d63   hassio_multicast    0.02%     2.371MiB / 1.822GiB   0.13%     0B / 0B           0B / 0B     4
c04e1990f7b0   hassio_cli          0.00%     2.09MiB / 1.822GiB    0.11%     1.22MB / 0B       0B / 0B     5
4fff9be18372   hassio_audio        0.01%     9.133MiB / 1.822GiB   0.49%     1.22MB / 0B       0B / 0B     6
975c3f2b45ba   hassio_dns          0.07%     12.86MiB / 1.822GiB   0.69%     1.16MB / 86.3kB   0B / 0B     17
99e049f8da4d   homeassistant       4.72%     198.7MiB / 1.822GiB   10.65%    0B / 0B           0B / 0B     37
e45c069cce81   hassio_supervisor   0.00%     78.33MiB / 1.822GiB   4.20%     1.5MB / 1.87MB    0B / 0B     16
1d9d00d77ae9   hassio_observer     0.00%     5.086MiB / 1.822GiB   0.27%     1.24MB / 12.8kB   0B / 0B     8

So all block I/O is reported as zero.  
"docker info" shows:
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

So maybe my kernel is missing something related to reporting block I/O.

**Comment by 0n3man** [comment]
Rebuilding the kernel with CONFIG_BLK_CGROUP=y made blk IO information available to supervisor removing the exception.  I suggest the developers catch the exception in stats.py and log the fact that CONFIG_BLK_CGROUP isn't enabled while allowing successful completion of the Supervise->System.

**Comment by gitolicious** [comment]
Interesting insight, thanks a lot for digging into it! I will cross-check on my end after the holidays.
I am running Debian, so my installation is showing _supported: true_ and I can verify the bug on supported systems.

**Comment by gitolicious** [comment]
I can confirm the missing `BLOCK I/O` information, even though I am not seeing any warnings about it in `docker info`.

```
# docker stats | head -n 1 && docker stats | grep hassio
CONTAINER ID        NAME                               CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
8cebb6fc8ed8        hassio_multicast                   0.22%               2.266MiB / 1.823GiB   0.12%               0B / 0B             0B / 0B             4
59148c0cc6bf        hassio_cli                         0.04%               2.125MiB / 1.823GiB   0.11%               370kB / 0B          0B / 0B             5
b9205c52269b        hassio_audio                       1.05%               35.22MiB / 1.823GiB   1.89%               370kB / 0B          0B / 0B             8
94ab7612c909        hassio_dns                         0.61%               14.11MiB / 1.823GiB   0.76%               498kB / 275kB       0B / 0B             15
d14ec645fda4        hassio_supervisor                  4.33%               116MiB / 1.823GiB     6.21%               4.12MB / 932kB      0B / 0B             19
153a5eea1ef2        hassio_observer                    0.05%               6.77MiB / 1.823GiB    0.36%               376kB / 1.49kB      0B / 0B             8
```

```
# docker info
[...]
 Kernel Version: 4.9.241-arm64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 1.823GiB
[...]
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by gitolicious** [comment]
This is fixed for me in the latest release. I can see CPU and RAM usage of Core and Supervisor, error log messages are gone.
How about the others?
