### ISSUE TITLE
HomeAssistant Core Container does not allow hot-plugging USB serial devices

### ISSUE THREAD

**Issue by Adminiuga** [home-assistant/supervisor#2358]
I'm not positive whether this belongs here, to Home Assistant OS or anywhere else.
The problem: Plugging in a USB serial device, while home assistant container is running, does not make serial port available (for ZHA integration), not until the Home Assistant container is restarted. It is enough to just restart the HomeAssistant container. Restarting the super visor does not help and restarting the host is an overkill.

I have experienced this on Pi3B+ with earlier versions and was able to reproduce with:
- HassOS 4.19
- Supervisor 2020.12.6
- Home Assistant 1.0.0.b3
Running on Virtual Box

---

@Adminiuga The problem described in this case; is that the list of serial ports is not updating / stays empty after plugging in the device (while Home Assistant is running).

_Originally posted by @frenck in https://github.com/home-assistant/home-assistant.io/pull/15829#discussion_r539521196_

**Comment by Adminiuga** [comment]
Here's HassOS console:
1. Plugging in USB (capturing USB in VirtualBox) while HomeAssistant container is running
![image](https://user-images.githubusercontent.com/5826160/101696482-2baedf80-3a44-11eb-8b74-cdafa18b0ad4.png)

2. No ports are available inside HA Container
![image](https://user-images.githubusercontent.com/5826160/101696540-43866380-3a44-11eb-8d63-d008f4b8b35b.png)

3. Reconnecting USB, still no ports inside container
![image](https://user-images.githubusercontent.com/5826160/101696591-55680680-3a44-11eb-8d3e-d90d27f2c308.png)

4. `lsusb` output inside HA container
![image](https://user-images.githubusercontent.com/5826160/101696629-63b62280-3a44-11eb-9b8d-0bad3fbbe8f0.png)

5. Hardware reported by the supervisor
![image](https://user-images.githubusercontent.com/5826160/101696671-73356b80-3a44-11eb-8a6f-460044e4e1be.png)

Restarting HA Container makes the USB serial ports available to HA instance
![image](https://user-images.githubusercontent.com/5826160/101696862-c14a6f00-3a44-11eb-96b8-9b7cd1a5193c.png)


However, if you unplug USB, restart HA container and then plug USB back into the host, ports are not available. In other words, for the serial ports to be there, the USB stick must be plugged in, before the HA container is started.

**Comment by pvizeli** [comment]
This is correct. Next year (I think Q2 - Q3) we add a feature which aims at a functionality like that.

**Comment by Adminiuga** [comment]
Ok, since this is working as designed and therefore not a bug, I'm gonna close this.

**Comment by pvizeli** [comment]
Yeah, it's docker. We integrate cgroup rules which could allow using such sticks like hot&plug. Do you have an installation which we can ask for a test?

**Comment by Adminiuga** [comment]
Since the virtual box image behave exactly the same, i could easily test it on a virtual box and if successful retest on a RPi3B+.
