### ISSUE TITLE
Host System: IPv6 disabled makes Supervisor unable to save

### ISSUE THREAD

**Issue by andriej** [home-assistant/supervisor#2364]
### Describe the issue

While editing the `Host System` network details in Network settings Supervisor menu (i.e. changing DNS address in IPv4 connection), while having IPv6 Disabled, makes it unable to save the data.

Starting point (after edit of IPv4, leaving IPv6 disabled as it was):
![image](https://user-images.githubusercontent.com/6303489/102031327-eda01b80-3db5-11eb-954b-3803959bb40a.png)
after clicking 'Save':
![image](https://user-images.githubusercontent.com/6303489/102031338-f7c21a00-3db5-11eb-89c5-f6213d06df97.png)
(translated: ipv6.method: property is invalid)

### Steps to reproduce

1. Go to Supervisor -> System -> host System
2. Change anything but have IPv6 disabled 
3. Try to save

### Enviroment details

- **Operating System:**: Debian 10 Supervised / no issues reported by Supervisor
- **Supervisor version:**: 2020.12.6
- **Home Assistant version**: 2020.12.0

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
20-12-14 01:42:05 ERROR (MainThread) [supervisor.host.network] Can't update config on enp2s0: Error: GDBus.Error:org.freedesktop.NetworkManager.Settings.Connection.InvalidProperty: ipv6.method: właściwość jest nieprawidłowa

```

</details>

### System Information

<details>
<summary>System Information</summary>

```
arch: amd64
channel: stable
docker: 19.03.14
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 2020.12.0
hostname: brix
logging: info
machine: qemux86-64
operating_system: Debian GNU/Linux 10 (buster)
supervisor: 2020.12.6
supported: true
supported_arch:
- amd64
- i386
timezone: Europe/Warsaw


```

</details>

**Comment by pvizeli** [comment]
Look like Debian NetworkManager doesn't support disabling ipv6 only local-link. So I think we can try to aim this

**Comment by andriej** [comment]
Just FYI: still valid in `2021.02.5`

**Comment by burntoc** [comment]
So this is an issue to me as well....Debian 10 install

**Comment by sveip** [comment]
If anyone is stuck on this, you can just enable DHCP or static for IPv6 and you should be able to save even if you don't use IPv6.

**Comment by andriej** [comment]
Just FYI (missed the stale bot) - still valid in 2021.8.x / supervisor-2021.06.8
