### ISSUE TITLE
Update v5.6 to v5.7/5.8 not possible, errors out. (Intel NUC)

### ISSUE THREAD

**Issue by dreimer1986** [home-assistant/supervisor#2368]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [X] Intel NUC (or compatible)
- [ ] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [ ] Fresh installation of release x.y
- [X] Updated from version 5.5
- Additional information (if accessible):

Version | 2020.12.0
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 5.4.80
CPU Architecture | x86_64
Timezone | Europe/Berlin

**Supervisor logs:**

```
time="2020-12-14T14:04:23+01:00" level=debug msg="Adding homedir to searchpath" homedir=/root
time="2020-12-14T14:04:23+01:00" level=info msg="No configfile found"
time="2020-12-14T14:04:23+01:00" level=debug msg="Debug flags" apiToken=cb3603e1f765e57198d0b2b88c1803657e11160d29ed914adf7a3881958312f4a29c23f8d7222c2c69f23c8baf1ab0d2d79f5cee4037e1b7 cfgFile= endpoint=supervisor logLevel=debug noProgress=false rawJSON=false
time="2020-12-14T14:04:23+01:00" level=debug msg="os update" args="[]"
time="2020-12-14T14:04:23+01:00" level=debug msg="[GenerateURI]" base=supervisor command=update section=os
time="2020-12-14T14:04:23+01:00" level=debug msg="[GenerateURI] Result" uri="http://supervisor/os/update" url="http://supervisor/os/update" url(string)="http://supervisor/os/update"
time="2020-12-14T14:04:23+01:00" level=debug msg="Request body" body="map[version:5.8]"
time="2020-12-14T14:04:50+01:00" level=debug msg=Response body="{\"result\": \"error\", \"message\": \"Expecting ',' delimiter: line 1 column 117 (char 116)\"}" fields.time=26.825997527s headers="map[Content-Length:[87] Content-Type:[application/json; charset=utf-8] Date:[Mon, 14 Dec 2020 13:04:50 GMT] Server:[Python/3.8 aiohttp/3.7.3]]" received-at="2020-12-14 14:04:50.777305697 +0100 CET m=+26.827876635" request="&{POST http://supervisor/os/update HTTP/1.1 1 1 map[Accept:[application/json] Authorization:[Bearer cb3603e1f765e57198d0b2b88c1803657e11160d29ed914adf7a3881958312f4a29c23f8d7222c2c69f23c8baf1ab0d2d79f5cee4037e1b7] Content-Type:[application/json] User-Agent:[go-resty/2.3.0 (https://github.com/go-resty/resty)]] {} 0x741300 17 [] false supervisor map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc000022148}" status="400 Bad Request" statuscode=400
Error: Expecting ',' delimiter: line 1 column 117 (char 116)
```
```
20-12-14 13:03:37 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-14 13:04:23 INFO (MainThread) [supervisor.api.security] /os/update access from a0d7b954_ssh
20-12-14 13:04:23 INFO (MainThread) [supervisor.hassos] Fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/5.8/hassos_intel-nuc-5.8.raucb
20-12-14 13:04:50 INFO (MainThread) [supervisor.hassos] OTA update is downloaded on /data/tmp/hassos-5.8.raucb
20-12-14 13:04:50 INFO (MainThread) [supervisor.utils.gdbus] Starting dbus monitor on de.pengutronix.rauc
20-12-14 13:04:50 INFO (MainThread) [supervisor.utils.gdbus] Stopping dbus monitor on de.pengutronix.rauc
20-12-14 13:04:50 ERROR (MainThread) [supervisor.utils.gdbus] Can't parse '[{"Operation": "idle", "LastError": "Installation error: Failed marking slot kernel.0 non-bootable: Failed marking "kernel.0" as bad: Failed to run barebox-state: Child process exited with code 1", "Progress": [100, "Installing failed.", 1], "Compatible": "hassos-intel-nuc", "Variant": "", "BootSlot": "B"}]
': '({'Operation': <'idle'>, 'LastError': <"Installation error: Failed marking slot kernel.0 non-bootable: Failed marking 'kernel.0' as bad: Failed to run barebox-state: Child process exited with code 1">, 'Progress': <(100, 'Installing failed.', 1)>, 'Compatible': <'hassos-intel-nuc'>, 'Variant': <''>, 'BootSlot': <'B'>},)
' - Expecting ',' delimiter: line 1 column 117 (char 116)
```

**Journal logs:**

**Kernel logs:**

**Description of problem:**

I am on HassOS 5.6 (Intel NUC) right now. I tried updating to 5.7 and now to 5.8 and always get this error. I rebooted x times, I tried x^3 times and it's not bypassable. Any way to fix that?

**Comment by dreimer1986** [comment]
As this was transferred to Supervisor, small addition:
Supervisor: 2020.12.6

**Comment by thecode** [comment]
I have the same error on OVA (QEMU hypervisor)

Few addtions:
I'm using dev channel on this system to there were many non released versions both of OS and supervisor.

Current OS: 5.6
Supervisor: 2020.12.dev1506

**Comment by dreimer1986** [comment]
No clue if that's your doing out there or not... I had to reboot the OS because it now lamented of being unhealthy (after a error 504 on another download try) and supervisor reboot alone did not fix it. When it woke back up I was in Boot slot A aka OS version 5.5. I tried the update from there and.... now I am on version 5.8 O_o So in theory my bug is fixed somehow. Lets see what you say about that and if @thecode has a similar experience ^^

**Comment by thecode** [comment]
> No clue if that's your doing out there or not... I had to reboot the OS because it now lamented of being unhealthy (after a error 504 on another download try) and supervisor reboot alone did not fix it. When it woke back up I was in Boot slot A aka OS version 5.5. I tried the update from there and.... now I am on version 5.8 O_o So in theory my bug is fixed somehow. Lets see what you say about that and if @thecode has a similar experience ^^

I had to repeat the proccess above twice to get to 5.5. From there upgrade to 5.8 succeeded. Thanks for the tip

**Comment by roysjosh** [comment]
I was able to go directly from 5.6 to 5.8 via `os update --version 5.8` after creating a missing directory:
`mkdir /var/lock
`
This missing directory was causing barebox-state to abort immediately.

**Comment by roysjosh** [comment]
See https://github.com/home-assistant/operating-system/issues/1037

**Comment by spakka** [comment]
> I was able to go directly from 5.6 to 5.8 via `os update --version 5.8` after creating a missing directory:
> `mkdir /var/lock `
> This missing directory was causing barebox-state to abort immediately.

This fixed it for me also, thanks!

**Comment by pvizeli** [comment]
Fixed on OS
