### ISSUE TITLE
When installation is unsupported, list what requirement is missing in details

### ISSUE THREAD

**Issue by wojciechczyz** [home-assistant/supervisor#2374]
When Supervisor thinks OS in not fully supported, I wish we would see what exact requirement is missing.
This seems to be my case, I have Debian 10 buster as a base, yet I see dreaded:

You are running an unsupported installation.  Learn more

Then I can see:

You are running an unsupported installation
Below is a list of issues found with your installation, click on the links to learn how you can resolve the issues. 

Operating System

But no details are given. I would like to see what exactly is missing or  better said what supervisor thinks is missing.

**Comment by frenck** [comment]
Could you provide the outputs of:

```bash
ha info
ha resolution info
```

**Comment by wojciechczyz** [comment]
Sorry for delay:
On my host:

bash-5.0# ha
bash: ha: command not found

I have it installed on OMV5 (installed in turn on Raspberrry Pi OS) when that  installation method was originally supported.

Did you  meant me to run it in docker of homeassistant?   I can access hass within homeassistant container:
bash-5.0# hass --version
2020.12.2

Thank you,
Wojciech
