### ISSUE TITLE
Error: Failed to fetch" when restoring snapshot on fresh install

### ISSUE THREAD

**Issue by fyrmangeoff** [home-assistant/supervisor#2385]
HassOS release with the issue:

QCOW2
2020.12.1

Supervisor logs:

Journal logs:

Kernel logs:

Description of problem:

Reinstalled HassOS in the clean version of Proxmox using hassos_ova-5.9.qcow2 and attempted to upload a snapshot and received a "Fail to fetch" notice. I have re installed Proxmox several times as well as Hassio. It will allow a new set up.

**Comment by ludeeus** [comment]
This was fixed in core 2021.1.0
