### ISSUE TITLE
HA 2020.12.1 memory leak

### ISSUE THREAD

**Issue by cjramseyer** [home-assistant/supervisor#2387]
Using latest version of Home Assistant with common add-ins.
Node-Red, Glances, File Editor, DuckDNS, SSH, chrony, AppDaemon4, Samba, Mosquitto, and ESPHome

System runs great for about 24 hours, memory utilization steadily increasing over 24 hours when memory is exhausted system is unresponsive.  Takes approximately 24 hours.  Memory immediately following reboot and all components running is at 72%

![image](https://user-images.githubusercontent.com/48690692/103140775-d962f500-46b8-11eb-8d1b-cf7785bb488b.png)

**Comment by pvizeli** [comment]
I don't see an issue on this screenshot, also not for the supervisor.
