### ISSUE TITLE
Home Assistant Core 2020.12.1 Doesn't Install

### ISSUE THREAD

**Issue by grtessman** [home-assistant/supervisor#2388]
Home Assistant Core 2020.12.1
You are currently running version 0.118.4 

Update results in an error: 
Update failed.
Unknown error, see supervisor

All previous updates have worked for me, just not this one.

**Comment by pvizeli** [comment]
`request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Translated to non-technical English. You can't make a connection currently from your system because somethings on your local network, your ISP, or docker itself have an issue. Try it later again.

**Comment by KillahB33** [comment]
This should be reopened there is a full thread in the forums about all the people having this issue.
https://community.home-assistant.io/t/cant-install-homeassistant-2020-12-0/256131/58

If it is in fact an issue with docker there should be an option in supervisor to do a docker login (is there a way for me to submit an RFC on this? as I only see devs doing rfcs)
