### ISSUE TITLE
Can't update to Home Assistant Core 2020.12.2

### ISSUE THREAD

**Issue by md-reddevil** [home-assistant/supervisor#2395]
### Describe the issue
I'm not able to update the Home Assistant to version Core 2020.12.2 from version 0.118.4 with the error "Unknown error, see supervisor".

### Steps to reproduce

1. Go to HA UI -> Supervisor
2. Click Update
3. see the error, Update failed
4. In the System tab I can see error/warning message: "You are running an unsupported installation." / "Your installtion is running in an unhealthy state."

### Enviroment details

- **Operating System:**:  N/A HASSIO on Raspberry Pi 3b
- **Supervisor version:**: 2020.12.7
- **Home Assistant version**:  0.118.4

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
21-01-03 13:32:00 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-03 13:32:00 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-03 13:32:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-01-03 14:17:13 WARNING (MainThread) [supervisor.jobs] 'HomeAssistantCore.update' blocked from execution, system is not healthy
21-01-03 14:23:24 WARNING (MainThread) [supervisor.jobs] 'HomeAssistantCore.update' blocked from execution, system is not healthy

```

</details>

### System Information

<details>
<summary>System Information</summary>

```
➜  ~ ha info                         
arch: armv7
channel: stable
docker: 17.06.0-dev
features: []
hassos: null
homeassistant: 0.118.4
hostname: null
logging: info
machine: raspberrypi3
operating_system: null
supervisor: 2020.12.7
supported: false
supported_arch:
- armv7
- armhf
timezone:

```

</details>

**Comment by ludeeus** [comment]
You are using the old images based on resinOS, you want to migrate to HAOS <https://www.home-assistant.io/blog/2018/07/11/hassio-images/>

1) Create full snapshot
2) Download that snapshot to another computer
3) Folow the instructions to install HAOS <https://www.home-assistant.io/getting-started/>
4) Upload and restore the snapshot on the new installation.
