### ISSUE TITLE
When Supervisor thinks OS in not fully supported, I do not see information why

### ISSUE THREAD

**Issue by wojciechczyz** [home-assistant/supervisor#2396]
When Supervisor thinks OS in not fully supported, I wish we would see what exact requirement is missing.
This seems to be my case, I have Debian 10 buster as a base, yet I see dreaded:

You are running an unsupported installation. Learn more

Then I can see:

You are running an unsupported installation
Below is a list of issues found with your installation, click on the links to learn how you can resolve the issues.

Operating System

But no details are given. I would like to see what exactly is missing or better said what supervisor thinks is missing.

---------
I was asked by frenck what "ha info" displays.
On my host:

bash-5.0# ha
bash: ha: command not found

I have it installed on OMV5 (installed in turn on Debian 10 Buster) when that  installation method was originally supported.

Did you  meant me to run it in docker of homeassistant?   I can access hass within homeassistant container:
bash-5.0# hass --version
2020.12.2

Thank you,
Wojciech

_Originally posted by @wojciechczyz in https://github.com/home-assistant/supervisor/issues/2374#issuecomment-753677495_

**Comment by frenck** [comment]
The `ha` command needs to be run from one of the SSH/Terminal add-ons. These have the CLI available

**Comment by wojciechczyz** [comment]
Thank you,
Including output as image:

**Comment by frenck** [comment]
You are running Raspbian, which is not a supported OS.

For more information and details see: <https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>
