### ISSUE TITLE
Supervisor wrongly assumes 401 means "expired access token" when the hassio component meant "invalid credentials"

### ISSUE THREAD

**Issue by zeehio** [home-assistant/supervisor#2408]
### Describe the issue

When an addon tries to use http://supervisor/auth with an invalid password, it gets an error `{"result": "error", "message": "Unknown error, see supervisor"}` instead of a 401 response.

The [Home Assistant hassio component](https://github.com/home-assistant/core/blob/ac3a6aaa8cdb005b3c900f9d9671e5a859351060/homeassistant/components/hassio/auth.py#L75) returns 401 if the given credentials are invalid (that's the standard and expected response), but that response is interpreted by [`make_request`](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/homeassistant/api.py#L90-L93) as if the access token had expired, raising a `HomeAssistantApiError` instead of returning the expected 401 response to successfully deny access.

### Steps to reproduce

1. An addon with `auth_api: true` uses a request with an invalid password like:

        curl -X POST -H "X-Supervisor-Token: ${SUPERVISOR_TOKEN}" http://valid_user:invalid_password@supervisor/auth

2. The [auth endpoint](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/api/auth.py#L66) calls [_process_basic](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/api/auth.py#L36) that forwards credentials to [check_login](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/auth.py#L64).

3. `check_login` [calls](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/auth.py#L87) [_backend_login](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/auth.py#L92) which [makes a request](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/auth.py#L95). The [make_request](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/homeassistant/api.py#L58) function verifies the token and [retrieves the response from home assistant `api/hassio_auth`](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/homeassistant/api.py#L89).

4. [Then](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/homeassistant/api.py#L90-L93), if it gets a 401 response, it assumes the access token has expired. If that happens twice, `make_response` raises a `HomeAssistantApiError`.

And *there is the error*: The [Home Assistant hassio component](https://github.com/home-assistant/core/blob/ac3a6aaa8cdb005b3c900f9d9671e5a859351060/homeassistant/components/hassio/auth.py#L75) also returns 401 if the given credentials are invalid (that's the standard and expected response), but that response is interpreted by [`make_request`](https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/homeassistant/api.py#L90-L93) as if the access token had expired, raising a `HomeAssistantApiError` instead of returning the 401 response that `_backend_login` expects to successfully deny access.

### Enviroment details

- **Operating System:**: Home Assistant OS 5.9
- **Supervisor version:**: 2020.12.7
- **Home Assistant version**: 2020.12.1

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
21-01-07 15:53:39 INFO (MainThread) [__main__] Initializing Supervisor setup
21-01-07 15:53:39 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
21-01-07 15:53:39 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: raspberrypi4-64
21-01-07 15:53:39 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/aarch64-hassio-supervisor with version 2020.12.7
21-01-07 15:53:39 INFO (SyncWorker_0) [supervisor.docker.supervisor] Connecting Supervisor to hassio-network
21-01-07 15:53:40 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
21-01-07 15:53:40 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-01-07 15:53:40 INFO (MainThread) [__main__] Setting up Supervisor
21-01-07 15:53:40 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
21-01-07 15:53:41 INFO (MainThread) [supervisor.host.info] Updating local host information
21-01-07 15:53:41 INFO (MainThread) [supervisor.host.services] Updating service information
21-01-07 15:53:41 INFO (MainThread) [supervisor.host.network] Updating local network information
21-01-07 15:53:44 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-01-07 15:53:44 INFO (MainThread) [supervisor.host] Host information reload completed
21-01-07 15:53:44 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
21-01-07 15:53:44 INFO (MainThread) [supervisor.host.services] Reloading local service hassos-apparmor.service
21-01-07 15:53:44 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-dns with version 2020.11.0
21-01-07 15:53:44 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
...
21-01-07 15:54:24 INFO (MainThread) [supervisor.auth] Auth request from '3884e67d_radicale' for 'zeehio'
21-01-07 15:54:25 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-01-07 15:54:25 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-01-07 15:54:26 ERROR (MainThread) [supervisor.auth] Can't request auth on Home Assistant!
21-01-07 15:54:26 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-690' coro=<Auth._backend_login() done, defined at /usr/src/supervisor/supervisor/auth.py:92> exception=AuthError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/auth.py", line 118, in _backend_login
    raise AuthError()
supervisor.exceptions.AuthError

```

</details>

### System Information

<details>
<summary>System Information</summary>

```
arch: aarch64
channel: stable
docker: 19.03.13
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "5.9"
homeassistant: 2020.12.1
hostname: homeassistant
logging: info
machine: raspberrypi4-64
operating_system: Home Assistant OS 5.9
supervisor: 2020.12.7
supported: true
supported_arch:
- aarch64
- armv7
- armhf
timezone: Europe/Berlin


```

</details>

**Comment by zeehio** [comment]
On a second thought, home assistant core returns 401 for both the invalid token and the invalid credentials, so it's impossible for the supervisor to tell the difference.

I guess some coordination with https://github.com/home-assistant/core will be needed so core reports different 401 errors (using an `HTTPUnauthorized(reason="invalid-user-password")` vs `HTTPUnauthorized(reason="expired-token")`, maybe?) and then changing the supervisor as well so it can filter the response accordingly

**Comment by frenck** [comment]
> On a second thought, home assistant core returns 401 for both the invalid token and the invalid credentials, so it's impossible for the supervisor to tell the difference.

But that doesn't matter. The result is the same?

**Comment by zeehio** [comment]
Close as a fix was merged https://github.com/home-assistant/core/pull/44940
