### ISSUE TITLE
Supervisor shutting itself down

### ISSUE THREAD

**Issue by kebel87** [home-assistant/supervisor#2430]
### Describe the issue

Since yesterday, the supervisor is shutting down by itself and logs show no error. Supervisor is then unaccessible from Home Assistant, throwing the following error : Unable to load the panel source: /api/hassio/app/entrypoint.js.

### Steps to reproduce

1. Honestly, it appears to be random, without human interaction of any kind.
2. ...
3. ...

### Enviroment details

- **Operating System:**: See system health below
- **Supervisor version:**: See system health below
- **Home Assistant version**: See system health below

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
ting system checks with state CoreState.RUNNING

21-01-13 11:16:52 INFO (MainThread) [supervisor.resolution.check] System checks complete


21-01-13 11:16:52 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json

21-01-13 11:17:42 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token

21-01-13 11:20:18 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup

21-01-13 11:21:52 INFO (MainThread) [supervisor.misc.tasks] Found new Supervisor version 2021.01.1, updating

21-01-13 11:21:52 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2021.01.1

21-01-13 11:21:52 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image homeassistant/amd64-hassio-supervisor with tag 2021.01.1.


21-01-13 11:22:04 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor.txt

21-01-13 11:22:04 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor

21-01-13 11:22:04 INFO (MainThread) [supervisor.misc.scheduler] Shutting down scheduled tasks

21-01-13 11:22:09 INFO (MainThread) [supervisor.api] Stopping API on 172.30.32.2

21-01-13 11:22:09 INFO (MainThread) [supervisor.misc.hwmon] Stopped Supervisor hardware monitor

21-01-13 11:22:09 INFO (MainThread) [supervisor.core] Supervisor is down - 0

21-01-13 11:22:09 INFO (MainThread) [__main__] Closing Supervisor

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL s

```

</details>

### System Information

<details>
<summary>System Information</summary>

```
## System Health

version | 2021.1.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.0-13-amd64
arch | x86_64
timezone | America/Toronto

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4929
Installed Version | 1.9.0
Stage | running
Available Repositories | 775
Installed Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | beta
supervisor_version | 2020.12.7
docker_version | 20.10.0
disk_total | 101.7 GB
disk_used | 12.4 GB
healthy | failed to load: Unhealthy
supported | failed to load: Unsupported
supervisor_api | failed to load: unreachable
version_api | ok
installed_addons | Grocy (0.9.2), Mosquitto broker (5.1), OpenZWave (0.8.0), Node-RED (7.2.11), UniFi Controller (0.19.3), Assistant Relay (0.7.4), File editor (5.2.0), AdGuard Home (2.6.1), Home Assistant Google Drive Backup (0.103.0), AirCast (2.4.1), Let's Encrypt (4.11.0), InfluxDB (3.7.9), Grafana (5.3.6)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | storage
views | 3
resources | 9

</details>

```

</details>

**Comment by ludeeus** [comment]
check the status of the `hassio-supervisor` service.

**Comment by kebel87** [comment]
> check the status of the `hassio-supervisor` service.

● hassio-supervisor.service - Hass.io supervisor
   Loaded: loaded (/etc/systemd/system/hassio-supervisor.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

**Comment by ludeeus** [comment]
ah, update docker, there is an issue with `20.10.0` which you have installed, once that is done reboot the host, and the problem is resolved :+1:

**Comment by kebel87** [comment]
> ah, update docker, there is an issue with `20.10.0` which you have installed, once that is done reboot the host, and the problem is resolved 👍

Updated docker, rebooted, and now I get this error on startup

● hassio-supervisor.service - Hass.io supervisor
   Loaded: loaded (/etc/systemd/system/hassio-supervisor.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2021-01-13 09:00:56 EST; 2s ago
  Process: 11218 ExecStartPre=/usr/bin/docker stop hassio_supervisor (code=exited, status=0/SUCCESS)
  Process: 11231 ExecStart=/usr/sbin/hassio-supervisor (code=exited, status=1/FAILURE)
 Main PID: 11231 (code=exited, status=1/FAILURE)

**Comment by ludeeus** [comment]
check the status logs and container logs for the hassio_supervisor container

**Comment by kebel87** [comment]
> check the status logs and container logs for the hassio_supervisor container

Thanks again for your help :)


Initialization scripts...
[cont-init.d] udev.sh: executing... 
[13:43:28] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:43:30] INFO: Starting local supervisor watchdog...
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[13:59:46] INFO: Update udev information
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[14:37:13] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.

**Comment by ludeeus** [comment]
There should be more, the init of the container is not complete at this point

**Comment by kebel87** [comment]
> There should be more, the init of the container is not complete at this point

The container come to a stop almost immediately after starting 


Status | Stopped for a few seconds with exit code 0
-- | --

[15:12:42] INFO: Update udev information
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by ludeeus** [comment]
Stop the service, remove the container, start the service again.

**Comment by kebel87** [comment]
> Stop the service, remove the container, start the service again.

Removed container, restarted hassio-supervisor using systemctl start hassio-supervisor

Then checked service status : 

● hassio-supervisor.service - Hass.io supervisor
   Loaded: loaded (/etc/systemd/system/hassio-supervisor.service; enabled; vendo
   Active: activating (auto-restart) (Result: exit-code) since Wed 2021-01-13 10
  Process: 4315 ExecStartPre=/usr/bin/docker stop hassio_supervisor (code=exited
  Process: 4328 ExecStart=/usr/sbin/hassio-supervisor (code=exited, status=1/FAI
 Main PID: 4328 (code=exited, status=1/FAILURE)

**Comment by ludeeus** [comment]
stop the service, run the installer again, then start the service

**Comment by kebel87** [comment]
Thanks for your help and patience, everything is running perfectly now. I'm very grateful for your time!
