### ISSUE TITLE
HomeAssistant reaching for Cloudflare DoH

### ISSUE THREAD

**Issue by rderensy** [home-assistant/supervisor#2437]
## The problem

My HomeAssistant is trying to reach cloudflare DNS over HTTPS Domain whereas there are already DNS provided by my DHCP

## Environment

- Home Assistant Core release with the issue: 2021.1.1
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): Home Assistant OS
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
My IDS throws an alert every 10 minutes and 1 second with `ET POLICY Observed Cloudflare DNS over HTTPS Domain (cloudflare-dns .com in TLS SNI)` coming from my HomeAssistant IP going to `1.1.1.1` and `1.0.0.1`. I am not using any cloud feature nor Cloudflare integration. I don't understand where it comes from since my DNS in HA look like this:
```
~ $ ha dns info
host: 172.30.32.3
locals:
- dns://192.168.50.254
servers:
- dns://192.168.50.254
update_available: false
version: 2020.12.0
version_latest: 2020.12.0
```
Is this an expected behavior? Can we disable or change the DoH?

**Comment by tescophil** [comment]
Its DoT not DoH, and I raised this issue back in October https://github.com/home-assistant/supervisor/issues/2139 

Its a 'Fallback' for unreliable upstream servers (even when they are not unreliable), but I believe its a **gross breach of privacy** and we should at least have the option to disable it.

**Comment by rderensy** [comment]
I saw "DNS over HTTPS" in the IDS so I thought it was DoH.

> I believe its a gross breach of privacy and we should at least have the option to disable it

Yes definitely! I'm self-hosting these kind of services so I don't depend on cloud stuff, but apparently we can't even trust them

**Comment by pvizeli** [comment]
That is not a bug. Please open a thread on https://community.home-assistant.io/c/feature-requests
