### ISSUE TITLE
Can't update to Home Assistant Core 2021.01.3 / Supervisor is not privileged

### ISSUE THREAD

**Issue by SoulSlayerPT** [home-assistant/supervisor#2440]
### Describe the issue
I'm not able to update the Home Assistant to version Core 2021.01.3 from version 0.116.4 with the error "'HomeAssistantCore.update' blocked from execution, system is not healthy"
Also i cannot update the addons.
Tried to run the supervisor installation script again, reboot but it got the same error.

### Steps to reproduce
1. Go to HA UI -> Supervisor -> System
2. Click Update
3. In the System tab I can see error/warning message: "You are running an unsupported installation." / "Your installtion is running in an unhealthy state."
 
### Enviroment details
* **Operating System:**:  Ubuntu 20.04.1 LTS
* **Supervisor version:**: 2021.01.4
* **Home Assistant version**:  0.116.4
 
### Supervisor logs
```
WARNING (MainThread) [supervisor.jobs] 'HomeAssistantCore.update' blocked from execution, system is not healthy
CRITICAL (MainThread) [supervisor.misc.hwmon] Not privileged to run udev monitor!
```

**Comment by frenck** [comment]
Ubuntu 20.04.1 LTS is not a support system by the Home Assistant project.

Sometimes restarting helps, whatever the case is, your system does not grant the Supervisor the access it needs.
