### ISSUE TITLE
supervisor not running priviliged while priviliged tag is set

### ISSUE THREAD

**Issue by Sloth-on-meth** [home-assistant/supervisor#2447]
```docker run --name hassio_supervisor \
        --privileged \
        --security-opt apparmor=hassio-supervisor \
        --security-opt seccomp=unconfined \
        -v /run/docker.sock:/run/docker.sock \
        -v /run/dbus:/run/dbus \
        -v /etc/machine-id:/etc/machine-id:ro \
        -v "${HASSIO_DATA}":/data:rw \
        -e SUPERVISOR_SHARE="${HASSIO_DATA}" \
        -e SUPERVISOR_NAME=hassio_supervisor \
        -e SUPERVISOR_MACHINE="${MACHINE}" \
        "${SUPERVISOR}"```
        
        container is not running priviliged, i am unable to update. i need to update ASAP bc of the security issue

**Comment by agners** [comment]
With `--privileged` you are running privileged. What is the issue exaclty? What type of installation?

**Comment by Sloth-on-meth** [comment]
Supervised. It's giving me unhealthy errors because it is not privileged while the flag is there.

Ubuntu 20.04

**Comment by pvizeli** [comment]
Not supported system

**Comment by Sloth-on-meth** [comment]
Nahh mate. I installed this with the hassio_install script years ago and it's worked fine forever. You're gonna tell me you're not even gonna like, check? At all?

**Comment by Sloth-on-meth** [comment]
I have like 20 other things on this machine, how on earth can it suddenly be "unsupported"

**Comment by Sloth-on-meth** [comment]
Ya know what, I'm running debian. It was a typo. Please reopen.

**Comment by jsiemek** [comment]
If it's Ubuntu, just temporary solution. Go to console/terminal and do:
sudo systemctl restart Hawaii-supervisor.service

After that it will start in true privileged mode and you will be able to update.

**Comment by Sloth-on-meth** [comment]
> If it's Ubuntu, just temporary solution. Go to console/terminal and do:
> sudo systemctl restart hassio-supervisor.service
> 
> After that it will start in true privileged mode and you will be able to update.

Thanks!

Sadly this did not work

**Comment by Sloth-on-meth** [comment]
@pvizeli care to explain why this is not supported while this is exactly how HA tutorial told me to install ages ago? I cant just switch my entire home server over to debian. There's a security bulletin and i need to update

**Comment by declanshanaghy** [comment]
Same issue for me. I just came across the documentation about Ubuntu being on the way to becoming an unsupported distro today (posted December 2020). In another location i saw that the deprecation was postponed. Honestly I'm not sure what the deprecation state of ubuntu is at this stage.

Here's the thing though.....I pay attention to all the release notes. I always read the breaking changes before upgrading. Since this was touted in the last few days as an update for an imminent security issue. I put my trust in the team and just went ahead. Now my system in a hosed state. 😠 

I've seen the attention that the HA team pays to release notes and visibility of breaking changes but I didn't expect to be bitten this badly by it. The discord channel is full of people with this issue.

**Comment by Sloth-on-meth** [comment]
According to this it's supported https://community.home-assistant.io/t/installation-methods-community-guides-wiki/199545

**Comment by Raul-7-7** [comment]
I am having same issue Ubuntu 20.04, working fine up until now with no issue. Everytime Supervisor updated itself (I really wish there was a way to disable auto-update) anyway, I had to run the script here: https://github.com/home-assistant/supervised-installer and it fixed the issue.

Starting from the latest Supervisor update, when running the script and then rebooting the host, the system does become HEALTHY again, however for only 24 hours or so, then its unhealthy, and I have to re-run the script!

**Comment by Sloth-on-meth** [comment]
https://community.home-assistant.io/t/i-feel-screwed-over-ubuntu-suddenly-dropped-all-github-issues-being-closed-and-im-stuck-with-a-broken-setup-and-no-way-to-fx/272104?u=sloth-on-meth

**Comment by NickTechonomy** [comment]
I had the same issue and bypassed it by running
```ha jobs options --ignore-conditions healthy```
This ignores the unhealthy state in the supervisor, and will allow for updates etc.

**Comment by Sloth-on-meth** [comment]
quite ridiculous how i was told to take it to the forum, posted it on the forum. linked it here and got banned for 7 days
