### ISSUE TITLE
Issues with privileged mode 

### ISSUE THREAD

**Issue by Sloth-on-meth** [home-assistant/supervisor#2450]
#2447 

According to HA's own documentation, ubuntu is supported. There are multiple users reporting these issues on discord and github. Please investigate and do not instant close because i will pull my hair out.

I'm looking to automate my home and keep. It. Working.

There's a security update that we HAVE to install ASAP but when we run ubuntu (a install method that is perfectly supported according to documentation) we're shit out of luck?

https://community.home-assistant.io/t/installation-methods-community-guides-wiki/199545

**Comment by pvizeli** [comment]
This is not officially supported, you need to ask the community for help. We don't have ubuntu developers which work to fix bugs there. Please look into:

- https://github.com/home-assistant/architecture/blob/master/adr/0012-define-supported-installation-method.md
- https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md

**Comment by Sloth-on-meth** [comment]
Great. So this method was supported and in December suddenly dropped. Fuck

**Comment by Sloth-on-meth** [comment]
@pvizeli  maybe next time dont drop a  supported OS with no prior warning. jesus christ. i still cant fucking update to fix the stupid security issue

**Comment by Sloth-on-meth** [comment]
https://community.home-assistant.io/t/i-feel-screwed-over-ubuntu-suddenly-dropped-all-github-issues-being-closed-and-im-stuck-with-a-broken-setup-and-no-way-to-fx/272104?u=sloth-on-meth
