### ISSUE TITLE
Supervisor is not updating Home Assistant to the latest version

### ISSUE THREAD

**Issue by metrix78** [home-assistant/supervisor#2456]
A new version of Home Assistant is out, but Supervisor is not updating to latest version.  I think the issue problem is that home assistant doesn't understand what 'amd64'

21-01-21 16:34:06 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-01-21 16:34:06 WARNING (MainThread) [supervisor.updater] Can't process version data: 'amd64'
21-01-21 16:34:06 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/qemux86-64-homeassistant with version 2020.12.0
21-01-21 16:34:06 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 1 Home Assistant secrets
21-01-21 16:34:06 WARNING (MainThread) [supervisor.arch] Can't detect the machine type!

my config in my /etc/hassio.json file:
{
    "supervisor": "homeassistant/amd64-hassio-supervisor",
    "machine": "qemux86-64",
    "data": "/usr/share/hassio"
}

The latest successful upgrade is to 2020.12.0

Brandon

**Comment by metrix78** [comment]
After doing some research, I _think_ this issue started after commit #2392 in file updater.py, but I don't understand Awesomeversion enough to do further research.

**Comment by pvizeli** [comment]
`21-01-21 16:34:06 WARNING (MainThread) [supervisor.arch] Can't detect the machine type!` look like your installation is broken. Rerun the Debian installer and it should be fixed.
