### ISSUE TITLE
Supervisor UI will Prompt to Downgrade if Updated via CLI

### ISSUE THREAD

**Issue by qJake** [home-assistant/supervisor#2459]
### Describe the issue

The Supervisor UI will prompt a user to "downgrade" (Update to a lower version) if they are on a version that is *greater than* (and not equal to) the current running version.

![image](https://user-images.githubusercontent.com/652006/105615539-147b4580-5d97-11eb-9843-cbb3a844a73a.png)

#### Reccomendation

Use *semantic versioning comparison* to check that the target version is newer, instead of not equal to.

SemVer comparison reference question for Python here: https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python (Apologies, I am a developer, but not a Python dev! 😁 So I know what to fix, but not how to fix it!)

### Steps to reproduce

*Note: These steps are generalized/arbitrary just so you can get the idea.*

1. Update HA Core to "Version 6"
2. Release "Version 7" publicly
3. Ensure the Supervisor does not alert on, or fetch the "Version 7" notice yet
4. Update via the CLI manually (1ha core update --version=7`)
5. Browse to the Supervisor tab after HA Core restarts.

### Enviroment details

- **Operating System:**: Home Assistant OS 5.10 (*Virtual Machine Host: VirtualBox running on Windows 10*)
- **Supervisor version:**: supervisor-2021.01.5
- **Home Assistant version**: core-2021.1.5

### Supervisor logs

```
21-01-23 22:10:29 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-01-23 22:10:29 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-01-23 22:10:30 INFO (MainThread) [supervisor.api.security] /core/update access from core_ssh
21-01-23 22:10:30 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2021.1.5
21-01-23 22:10:30 INFO (SyncWorker_4) [supervisor.docker.interface] Updating image homeassistant/qemux86-64-homeassistant:2021.1.4 to homeassistant/qemux86-64-homeassistant:2021.1.5
21-01-23 22:10:30 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image homeassistant/qemux86-64-homeassistant with tag 2021.1.5.
21-01-23 22:11:22 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping homeassistant application
21-01-23 22:11:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
21-01-23 22:11:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-01-23 22:11:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
21-01-23 22:11:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-01-23 22:12:02 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning homeassistant application
21-01-23 22:12:02 INFO (MainThread) [supervisor.homeassistant] Update pulse/client.config: /data/tmp/homeassistant_pulse
21-01-23 22:12:02 INFO (SyncWorker_1) [supervisor.docker.homeassistant] Starting Home Assistant homeassistant/qemux86-64-homeassistant with version 2021.1.5
21-01-23 22:12:02 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-01-23 22:16:48 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-01-23 22:16:48 INFO (MainThread) [supervisor.homeassistant.core] Successful started Home Assistant 2021.1.5
21-01-23 22:16:48 INFO (SyncWorker_4) [supervisor.docker.interface] Cleanup images: ['homeassistant/qemux86-64-homeassistant:2021.1.4']
```

### System Information

```
arch: amd64
channel: stable
docker: 19.03.13
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "5.10"
homeassistant: 2021.1.5
hostname: hassio
logging: info
machine: qemux86-64
operating_system: Home Assistant OS 5.10
supervisor: 2021.01.5
supported: true
supported_arch:
- amd64
- i386
timezone: America/Chicago
```

**Comment by frenck** [comment]
That is because the update hasn't received yet. You can manually force the Supervisor to get its state by reloading it. You can reload the supervisor by going into the Supervisor panel -> System tab -> and click the reload button on the Supervisor card.

After that, it should be solved. Please note, using the CLI is an override. The Supervisor gives you the option to downgrade, as you are on the stable channel. According to his data, the stable channel is on 2021.1.4, so a downgrade is expected and correct.

**Comment by qJake** [comment]
Perhaps there still is a bug though... what would happen if I pressed "Update"? Would it actually revert to 2021.1.4 successfully? Is that a supported scenario?

If so... I would debate that the button text then should read "Downgrade" and not "Update", since well... you're not going "Up". 😉 Just to give the user a visual clue before they click it.

**Comment by frenck** [comment]
It is not a bug. It can update to another version. I use this scenario myself quite a bit (when switching between the different release/stability channels).
