### ISSUE TITLE
WARNING (MainThread) [supervisor.homeassistant.core] Version 2021.2.0b0 is already installed

### ISSUE THREAD

**Issue by baerrs** [home-assistant/supervisor#2479]
## The problem
The system is telling me I have an update to install.  When i try, nothing happens and i see this in the log file.  :
WARNING (MainThread) [supervisor.homeassistant.core] Version 2021.2.0b0 is already installed
Core Version  core-2021.2.0
Newest Version core-2021.2.0b0

## Environment

Core
Version
core-2021.2.0
Newest Version
core-2021.2.0b0

Host Operating System | Home Assistant OS 5.10
-- | --
Update Channel | beta
Version | supervisor-2021.01.8
Docker Version | 19.03.13
Disk Total | 28.6 GB
Disk Used | 6.1 GB
Healthy | true
Supported | true
Board | rpi4-64
Supervisor API | ok
Version API | ok
Installed Add-ons | File editor (5.1.0), Visual Studio Code (2.8.2), WireGuard (0.4.0), TasmoAdmin (0.13.1), ZeroTier One (0.8.0), Terminal & SSH (8.10.0)

- Home Assistant Core release with the issue: core-2021.2.0b0
- Last working Home Assistant Core release (if known): core-2021.2.0
- Operating environment (OS/Container/Supervised/Core): supervisor-2021.01.8,Home Assistant OS 5.10
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: mqtt
    name: "Inside Temperature"
    state_topic: "v1/devices/me/telemetry/temperature"
    unit_of_measurement: '°F'
    value_template: "{{ value_json.temperature }}"
  - platform: mqtt
    name: "Inside Humididty"
    state_topic: "v1/devices/me/telemetry/humidity"
    unit_of_measurement: '%'
    value_template: "{{ value_json.humidity }}"
  - platform: mqtt
    name: "Outside Temperature"
    state_topic: "v1/devices/me/telemetry/OWM_temperature"
    unit_of_measurement: '°F'
    value_template: "{{ value_json.OWM_temperature }}"
  - platform: mqtt
    name: "Outside Huymidity"
    state_topic: "v1/devices/me/telemetry/OWM_humidity"
    unit_of_measurement: '%'
    value_template: "{{ value_json.OWM_humidity }}"


```

## Traceback/Error logs

```
21-01-28 21:24:35 WARNING (MainThread) [supervisor.homeassistant.core] Version 2021.2.0b0 is already installed

```

## Additional information
I have rebooted the HA.

**Comment by bouwew** [comment]
I have a similar issue when trying to update to v2021.2.0b1.
Apparently v2021.2.0b0 installed itself as v2021.2.0:
![image](https://user-images.githubusercontent.com/11290930/106317292-65df7500-626e-11eb-9fe9-01cb9b8a3b22.png)

**Comment by paarak** [comment]
Supervisor goes bananas uses lots of memory! tries to leave the beta channel, but nothing happens


![skjermbilde](https://user-images.githubusercontent.com/56606692/106357117-6fb3b780-6304-11eb-9aa3-a37ec2d0db47.png)

**Comment by ludeeus** [comment]
Fixed in https://github.com/home-assistant/supervisor/pull/2481

**Comment by bouwew** [comment]
@ludeeus Great!

But how do we achieve updating now? Any beta and the final 2021.2.0 version will not install due to the wrong version-number.
Or is there a work-around available?

**Comment by bouwew** [comment]
@ludeeus Is there a way to force-update Core to a certain version via CLI? I tried updating to v2021.2.0b1 via CLI but it says it's already installed but when I previously performed the installation I'm pretty sure it did not update (to ...b1).

**Comment by ludeeus** [comment]
Restart SU first

**Comment by bouwew** [comment]
Yes I did, ah now the update message is gone, apparently v...b1 did installl correctly.
Thanks!

**Comment by baerrs** [comment]
Thanks for the update, "Restart Supervisor" and it now looks good.
