### ISSUE TITLE
Update 2021.1.5 failed

### ISSUE THREAD

**Issue by Koksinhell** [home-assistant/supervisor#2480]
## The problem

Th update failed each time, from the 2020.12.0 to 2021.1.5

## Environment

- Home Assistant Core release with the issue: core-2021.1.5
- Last working Home Assistant Core release (if known): core-2020.12.0
- Operating environment (OS/Container/Supervised/Core): I beleive supervised installation
- Integration causing this issue: none
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

ERROR (SyncWorker_7) [supervisor.docker.interface] Can't install homeassistant/raspberrypi4-homeassistant:2021.1.5 -> 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/raspberrypi4-homeassistant:2021.1.5/json: Not Found ("no such image: homeassistant/raspberrypi4-homeassistant:2021.1.5: No such image: homeassistant/raspberrypi4-homeassistant:2021.1.5").

```txt

```

## Additional information
I read that it could be a free space issue, but I am not sure , please find here my df -h result
![IMG_4709](https://user-images.githubusercontent.com/25154358/106037350-dbb0d880-60d6-11eb-99fd-c2cecdba555f.jpg)

**Comment by ludeeus** [comment]
Closing this as it's an unsupported way to run Home Assistant Supervised.
You should consider using Home Assistant Operating System instead <https://www.home-assistant.io/hassio/installation/>.
Or try asking on the [forums](https://community.home-assistant.io/)

**Comment by Koksinhell** [comment]
OK, thank you for your advise.
