### ISSUE TITLE
Option to exclude "home-assistant_v2.db" file from shapshot.

### ISSUE THREAD

**Issue by kdelios** [home-assistant/supervisor#2487]
Not an issue, just a suggestion:

On snapshot settings, add a selection to include "home-assistant_v2.db" file or not.
Since this is the biggest file in size, and probably it has to be deleted after a snapshot restore (in order history start working again), we could exclude it from the snapshot in order to make snapshot significantly smaller in size .

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
