### ISSUE TITLE
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'.

### ISSUE THREAD

**Issue by bobo522487** [home-assistant/supervisor#2533]
### Describe the issue
Add-on config 'auto_uart' is deprecated, use 'uart'.

### Steps to reproduce

1. ...upgrate supervisor-2021.02.5
2. ...
3. ...

### Enviroment details

- **Operating System:**: core-2021.2.1
- **Supervisor version:**: supervisor-2021.02.5
- **Home Assistant version**: 5.10

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
Paste supervisor logs here

```
21-02-08 10:55:56 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
21-02-08 10:55:56 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: qemux86-64
21-02-08 10:55:56 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/amd64-hassio-supervisor with version 2021.02.5
21-02-08 10:55:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
21-02-08 10:55:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-02-08 10:55:56 INFO (MainThread) [__main__] Setting up Supervisor
21-02-08 10:55:56 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
21-02-08 10:55:56 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
21-02-08 10:55:56 INFO (MainThread) [supervisor.host.info] Updating local host information
21-02-08 10:55:56 INFO (MainThread) [supervisor.host.services] Updating service information
21-02-08 10:55:57 INFO (MainThread) [supervisor.host.network] Updating local network information
21-02-08 10:55:57 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-02-08 10:55:57 INFO (MainThread) [supervisor.host] Host information reload completed
21-02-08 10:55:57 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
21-02-08 10:55:57 INFO (MainThread) [supervisor.host.services] Reloading local service hassos-apparmor.service
21-02-08 10:55:57 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-dns with version 2021.01.0
21-02-08 10:55:57 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
21-02-08 10:55:57 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-audio with version 17
21-02-08 10:55:57 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-cli with version 2020.11.1
21-02-08 10:55:57 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-observer with version 2020.10.1
21-02-08 10:55:57 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-multicast with version 3
21-02-08 10:55:57 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-02-08 10:55:58 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/qemux86-64-homeassistant with version 2021.2.1
21-02-08 10:55:58 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 18 Home Assistant secrets
21-02-08 10:55:58 INFO (MainThread) [supervisor.hassos] Detect HassOS 5.10 / BootSlot A
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Terminal & SSH
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of OpenZWave
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of HomeMatic CCU
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of TellStick
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of deCONZ
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of SSH & Web Terminal
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of SSH & Web Terminal
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave to MQTT
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Visual Studio Code
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of AppDaemon 4
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Network UPS Tools
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Network UPS Tools
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of WireGuard
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of ZeroTier One
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Node-RED
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Node-RED
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS to MQTT
21-02-08 10:55:58 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
21-02-08 10:55:58 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Terminal & SSH
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of OpenZWave
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of HomeMatic CCU
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of TellStick
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of deCONZ
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of SSH & Web Terminal
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of SSH & Web Terminal
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave to MQTT
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Visual Studio Code
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of AppDaemon 4
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Network UPS Tools
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Network UPS Tools
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of WireGuard
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of ZeroTier One
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Node-RED
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Node-RED
21-02-08 10:55:58 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS to MQTT
21-02-08 10:55:58 INFO (MainThread) [supervisor.store] Loading add-ons from store: 65 all - 65 new - 0 remove
21-02-08 10:55:58 INFO (MainThread) [supervisor.addons] Found 2 installed add-ons
21-02-08 10:55:58 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-configurator with version 5.2.0
21-02-08 10:55:58 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-samba with version 9.3.0
21-02-08 10:55:58 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-02-08 10:55:58 INFO (MainThread) [supervisor.discovery] Loaded 0 messages
21-02-08 10:55:58 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
21-02-08 10:55:58 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-02-08 10:55:58 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-02-08 10:55:58 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-02-08 10:55:58 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-02-08 10:55:58 INFO (MainThread) [__main__] Running Supervisor
21-02-08 10:55:58 INFO (MainThread) [supervisor.hassos] Rauc: A - marked slot kernel.0 as good
21-02-08 10:55:58 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
21-02-08 10:55:58 INFO (MainThread) [supervisor.core] Supervisor reboot detected
21-02-08 10:55:58 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
21-02-08 10:55:58 INFO (MainThread) [supervisor.core] Supervisor is up and running
21-02-08 10:55:58 INFO (MainThread) [supervisor.host.info] Updating local host information
21-02-08 10:55:58 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-02-08 10:55:58 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-02-08 10:55:58 INFO (MainThread) [supervisor.host.services] Updating service information
21-02-08 10:55:58 INFO (MainThread) [supervisor.host.network] Updating local network information
21-02-08 10:55:59 INFO (MainThread) [supervisor.host] Host information reload completed
21-02-08 11:01:36 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files

</details>

### System Information

<details>
<summary>System Information</summary>

```
Paste system info here

```
System Health

version: core-2021.2.1
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.7
os_name: Linux
os_version: 5.4.86
arch: x86_64
timezone: Asia/Shanghai

GitHub API: ok
Github API Calls Remaining: 4937
Installed Version: 1.11.0
Stage: running
Available Repositories: 720
Installed Repositories: 5

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Home Assistant OS 5.10
update_channel: stable
supervisor_version: supervisor-2021.02.5
docker_version: 19.03.13
disk_total: 30.8 GB
disk_used: 3.1 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: ok
installed_addons: File editor (5.2.0), Samba share (9.3.0)

dashboards: 2
resources: 1
views: 3
error: /config/floorplan/home/home.yaml not found
mode: storage

</details>

**Comment by frenck** [comment]
See the log messages:

`Please report this to the maintainer of X` (where X is the add-on).

Thanks 👍
