### ISSUE TITLE
Home assistant fails to fully start resulting in snapshot not working and Zwave not working

### ISSUE THREAD

**Issue by fabianpk** [home-assistant/supervisor#2534]
### Describe the issue

I upgraded this morning to Home assistant 2021.2.1. Prior to this my installation was working really well (aside from some IKEA tradfri issues). I noticed zwave components weren't added to the UI, and it turns out they were not discovered at all. I found Openzwave was deprecated, so I deactivated it and installed Zwave JS instead. The addon does not indicate any errors as far as I can tell, but it still wont add zwave components to my system. It ends with:

14:57:10.182 CNTRLR   [Node 007] Interview stage completed: Neighbors
14:57:10.182 CNTRLR   [Node 007] Interview completed

 I tried to rewind the installation to my previous version by using the snapshot I have, but it fails to work. I'm not sure if the issue is with Zwave JS, or something else with my system. 

### Steps to reproduce

1. Startup my system by rebooting my machine (sudo reboot now)
2. Try to create a snapshot or restore from snapshot

I have tried to deactivate all addons except duckdns. 

## System Health

version | core-2021.2.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.0-13-amd64
arch | x86_64
timezone | Europe/Stockholm

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4999
Installed Version | 1.11.0
Stage | running
Available Repositories | 778
Installed Repositories | 4

</details>

<details><summary>Hass.io</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.5
docker_version | 20.10.1
disk_total | 108.1 GB
disk_used | 70.5 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon 4 (0.4.2), Mosquitto broker (5.1), Plejd (0.5.1), File editor (5.2.0), OpenZWave (0.9.0), Check Home Assistant configuration (3.6.0), Grafana (6.1.0), InfluxDB (4.0.1), Duck DNS (1.12.4), Dnsmasq (1.3), Z-Wave JS (0.1.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 5
mode | storage

</details>

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
21-02-08 12:34:26 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-02-08 12:34:26 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_audio application
21-02-08 12:34:27 INFO (SyncWorker_0) [supervisor.docker.audio] Starting Audio homeassistant/amd64-hassio-audio with version 17 - 172.30.32.4
21-02-08 12:34:27 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-cli with version 2020.11.1
21-02-08 12:34:27 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
21-02-08 12:34:27 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_cli application
21-02-08 12:34:27 INFO (SyncWorker_0) [supervisor.docker.cli] Starting CLI homeassistant/amd64-hassio-cli with version 2020.11.1 - 172.30.32.5
21-02-08 12:34:27 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-observer with version 2020.10.1
21-02-08 12:34:27 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-hassio-multicast with version 3
21-02-08 12:34:27 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin
21-02-08 12:34:27 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_multicast application
21-02-08 12:34:28 INFO (SyncWorker_0) [supervisor.docker.multicast] Starting Multicast homeassistant/amd64-hassio-multicast with version 3 - Host
21-02-08 12:34:28 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-02-08 12:34:28 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/qemux86-64-homeassistant with version 2021.2.1
21-02-08 12:34:28 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 6 Home Assistant secrets
21-02-08 12:34:28 INFO (MainThread) [supervisor.hassos] No Home Assistant Operating System found
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Terminal & SSH
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of TellStick
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of OpenZWave
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of HomeMatic CCU
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of deCONZ
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of SSH & Web Terminal
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of SSH & Web Terminal
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Visual Studio Code
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Node-RED
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Node-RED
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave to MQTT
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of WireGuard
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS to MQTT
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Network UPS Tools
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Network UPS Tools
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of AppDaemon 4
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of ZeroTier One
21-02-08 12:34:28 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/4cb18a39 repository
21-02-08 12:34:28 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
21-02-08 12:34:28 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Terminal & SSH
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of TellStick
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of OpenZWave
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of HomeMatic CCU
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of deCONZ
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of SSH & Web Terminal
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of SSH & Web Terminal
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Visual Studio Code
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Node-RED
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Node-RED
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave to MQTT
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of WireGuard
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS to MQTT
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Network UPS Tools
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Network UPS Tools
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of AppDaemon 4
21-02-08 12:34:28 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of ZeroTier One
21-02-08 12:34:28 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 66 new - 0 remove
21-02-08 12:34:28 INFO (MainThread) [supervisor.addons] Found 11 installed add-ons
21-02-08 12:34:28 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-duckdns with version 1.12.4
21-02-08 12:34:28 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-dnsmasq with version 1.3
21-02-08 12:34:28 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-check_config with version 3.6.0
21-02-08 12:34:28 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/appdaemon/amd64 with version 0.4.2
21-02-08 12:34:29 INFO (SyncWorker_7) [supervisor.docker.interface] Attaching to 4cb18a39/amd64-addon-plejd with version 0.5.1
21-02-08 12:34:29 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-configurator with version 5.2.0
21-02-08 12:34:29 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-zwave with version 0.9.0
21-02-08 12:34:29 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/grafana/amd64 with version 6.1.0
21-02-08 12:34:29 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/influxdb/amd64 with version 4.0.1
21-02-08 12:34:29 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-zwave_js with version 0.1.4
21-02-08 12:34:29 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-mosquitto with version 5.1
21-02-08 12:34:29 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-02-08 12:34:29 INFO (MainThread) [supervisor.discovery] Loaded 3 messages
21-02-08 12:34:29 INFO (MainThread) [supervisor.ingress] Loaded 2 ingress sessions
21-02-08 12:34:29 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-02-08 12:34:29 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-02-08 12:34:29 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-02-08 12:34:29 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-02-08 12:34:29 INFO (MainThread) [__main__] Running Supervisor
21-02-08 12:34:29 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
21-02-08 12:34:29 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 1 add-ons
21-02-08 12:34:29 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_core_dnsmasq application
21-02-08 12:34:29 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-dnsmasq with version 1.3
21-02-08 12:34:34 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 1 add-ons
21-02-08 12:34:34 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_duckdns application
21-02-08 12:34:35 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-duckdns with version 1.12.4
21-02-08 12:34:40 INFO (MainThread) [supervisor.core] Start Home Assistant Core
21-02-08 12:34:40 INFO (SyncWorker_5) [supervisor.docker.interface] Starting homeassistant
21-02-08 12:34:40 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-02-08 12:35:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-02-08 12:55:18 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-02-08 12:55:22 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running - CoreState.STARTUP
21-02-08 13:05:11 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-02-08 13:35:12 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-02-08 13:53:04 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-02-08 13:53:06 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running - CoreState.STARTUP
21-02-08 13:55:39 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-zwave_js with version 0.1.4
21-02-08 14:01:13 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-02-08 14:01:15 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_full' blocked from execution, system is not running - CoreState.STARTUP

```

</details>

### System Information

<details>
<summary>System Information</summary>

```
arch: amd64
channel: stable
docker: 20.10.1
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 2021.2.1
hostname: goldboard
logging: info
machine: qemux86-64
operating_system: Debian GNU/Linux 10 (buster)
supervisor: 2021.02.5
supported: true
supported_arch:
- amd64
- i386
timezone: Europe/Stockholm


```

</details>

**Comment by C-R-o-s-s** [comment]
I am having similar issues, though I am not trying to create any snapshots, I keep getting the following errors in my log:
21-02-08 14:39:16 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-02-08 14:39:16 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-02-08 14:40:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-02-08 14:40:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of AppDaemon 4
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of WireGuard
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of ZeroTier One
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Visual Studio Code
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave to MQTT
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Node-RED
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Node-RED
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS to MQTT
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Network UPS Tools
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Network UPS Tools
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of SSH & Web Terminal
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of SSH & Web Terminal
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of AppDaemon 4
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of WireGuard
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of ZeroTier One
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Visual Studio Code
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave to MQTT
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Node-RED
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Node-RED
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS to MQTT
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Network UPS Tools
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Network UPS Tools
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of SSH & Web Terminal
21-02-08 14:40:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of SSH & Web Terminal
21-02-08 14:40:02 INFO (MainThread) [supervisor.store] Loading add-ons from store: 65 all - 0 new - 0 remove
21-02-08 14:40:02 INFO (MainThread) [supervisor.store] Loading add-ons from store: 65 all - 0 new - 0 remove
21-02-08 15:01:47 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token

**Comment by Beiri22** [comment]
Maybe similar to https://github.com/home-assistant/core/issues/46153

**Comment by donkawechico** [comment]
@fabianpk by any chance, are you using any homekit devices/integrations?

**Comment by fabianpk** [comment]
@donkawechico Yes, I am using alot of homekit devices. I have an Apple TV, Homepod Mini etc. I'm exporting my homeassistant lights to homekit, but I'm not importing any lights from homekit to homeassistant.

**Comment by fabianpk** [comment]
Snapshot tells me I can now update to 2021.2.2, but when I try to update it says:
21-02-09 08:17:48 ERROR (MainThread) [supervisor.utils] Can't execute wrapper while a task is in progress

**Comment by Beiri22** [comment]
In my case removing the openzwave addon and integration helped -- but I did not really use it, so it was no big deal.

**Comment by fabianpk** [comment]
> In my case removing the openzwave addon and integration helped -- but I did not really use it, so it was no big deal.

I am dependent on Zwave (but not specifically openzwave), but uninstalling it doesn't change anything.

**Comment by Beiri22** [comment]
I am also dependent on it, but was actively using the old zwave integration. But had installed ozw - so these two interferred in some way.

**Comment by fabianpk** [comment]
It seems it does start working when I remove the INTEGRATION OpenZwave. It's very confusing there's an integration named OpenZwave and an addon in supervisor named the same thing (almost). This could be made clearer in the documentation.

**Comment by fabianpk** [comment]
It started working when I removed the INTEGRATION OpenZwave as mentioned above. Strongly recommend better documentation on this.
