### ISSUE TITLE
PAI - Paradox Alarm Interface

### ISSUE THREAD

**Issue by dpoposki79** [home-assistant/supervisor#2547]
**Describe the issue you are experiencing**

After upgrade on version supervisor-2021.02.6, PAI stop work. 
Error is below.
2021-02-09 18:06:12,233 - ERROR    - PAI.paradox.connections.serial_connection - Failed to update file /dev/ttyS1 permissions
2021-02-09 18:06:12,234 - ERROR    - PAI.paradox.paradox - Failed to connect to interface
2021-02-09 18:06:12,234 - ERROR    - PAI - Unable to connect to alarm
2021-02-09 18:06:42,258 - INFO     - PAI - Starting...
2021-02-09 18:06:42,259 - INFO     - PAI.paradox.paradox - Disconnecting from the Alarm Panel
2021-02-09 18:06:42,260 - INFO     - PAI.paradox.paradox - Clean Session
2021-02-09 18:06:42,261 - INFO     - PAI.paradox.paradox - Connecting to interface
2021-02-09 18:06:42,261 - INFO     - PAI.paradox.connections.serial_connection - Connecting to serial port /dev/ttyS1
2021-02-09 18:06:42,262 - INFO     - PAI.paradox.connections.serial_connection - /dev/ttyS1 is not readable/writable. Trying to fix...
2021-02-09 18:06:42,263 - ERROR    - PAI.paradox.connections.serial_connection - Failed to update file /dev/ttyS1 permissions
2021-02-09 18:06:42,264 - ERROR    - PAI.paradox.paradox - Failed to connect to interface
2021-02-09 18:06:42,265 - ERROR    - PAI - Unable to connect to alarm

**What is the used version of the Supervisor?**

supervisor-2021.02.6

**What type of installation are you running?**

Home Assistant OS

**Which operating system are you running on?**

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

**What is the version of your installed operating system?**

5.11

**What version of Home Assistant Core is installed?**

core-2021.2.2

**Steps to reproduce the issue**

1.Issue start after upgrade of Supervisor
2.
3.
...

**Anything in the Supervisor logs that might be useful for us?**

```txt
# Put your logs below this line
21-02-09 14:27:41 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_e92a3241_paradox_alarm_interface application
21-02-09 14:27:52 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_e92a3241_paradox_alarm_interface application
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options LOGGING_FILE
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options LOGGING_LEVEL_CONSOLE
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options LOGGING_LEVEL_FILE
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options LOGGING_DUMP_PACKETS
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options LOGGING_DUMP_MESSAGES
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options LOGGING_DUMP_STATUS
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options LOGGING_DUMP_EVENTS
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options CONNECTION_TYPE
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options SERIAL_PORT
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options SERIAL_BAUD
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options IP_CONNECTION_HOST
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options IP_CONNECTION_PORT
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options IP_CONNECTION_PASSWORD
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options IP_CONNECTION_SITEID
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options IP_CONNECTION_EMAIL
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options IP_CONNECTION_PANEL_SERIAL
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options IP_CONNECTION_BARE
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options LIMITS
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options SYNC_TIME
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options PASSWORD
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options MQTT_ENABLE
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options MQTT_HOST
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options MQTT_PORT
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options MQTT_USERNAME
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options MQTT_PASSWORD
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options MQTT_RETAIN
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options MQTT_BIND_ADDRESS
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options MQTT_BIND_PORT
21-02-09 14:27:52 WARNING (MainThread) [supervisor.addons.options] Unknown options MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE
21-02-09 14:27:55 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on paradoxalarminterface/pai with version None
```

**Comment by Rick-Shepherd** [comment]
I have exactly same problem

**Comment by voltage84** [comment]
+1

**Comment by dikeylimit** [comment]
+1

**Comment by yozik04** [comment]
#2540 They already closed my report with won't fix.

**Comment by dikeylimit** [comment]
So is there a way to use pai with home assistant?

**Comment by voltage84** [comment]
Thanks a lot @yozik04 ! The version 2.3.0 release today solved my issue. I had to reset my config to default (after saving my old config), write back the necessary values, mainly authentication (panel code and MQTT stuff) and it came back to life! I really like this addon and use it daily, best place for a donation.

**Comment by dikeylimit** [comment]
Works great again! Thank you :)

**Comment by pvizeli** [comment]
The add-on need use `uart: true` or inside schema set an option which handle device access as type `device(subsystem=tty)`
