### ISSUE TITLE
Possible Spelling mistake in addon.py

### ISSUE THREAD

**Issue by jgoakley** [home-assistant/supervisor#2550]
**Describe the issue you are experiencing**

Line 427 in addon.py might have a spelling mistake. I think envoirement should be environment:

_LOGGER.error("Invalid build envoirement, can't build this add-on!")

I'm not sure how to make a pull request to fix it so I just wanted to let you know 🙂

**What is the used version of the Supervisor?**

supervisor-2021.02.6

**What type of installation are you running?**

Home Assistant OS

**Which operating system are you running on?**

Home Assistant Operating System

**What is the version of your installed operating system?**

5.11

**What version of Home Assistant Core is installed?**

core-2021.2.2

**Steps to reproduce the issue**

1. Tried to use an unsupported build environment for an Add On
2. Received the misspelled error message in the supervisor log

**Anything in the Supervisor logs that might be useful for us?**

```txt
# Put your logs below this line
21-02-09 21:25:27 ERROR (SyncWorker_0) [supervisor.docker.addon] Invalid build envoirement, can't build this add-on!
```

Thanks for all of the work you do for this amazing software!

**Comment by pvizeli** [comment]
Thanks for reporting it but we don't need an issue for track a spell check :)
