### ISSUE TITLE
Validation does not support deeply nested objects

### ISSUE THREAD

**Issue by mKeRix** [home-assistant/supervisor#2560]
**Describe the issue you are experiencing**

After the recent schema change I talked to frenck on Discord, who suggested that the nested depth limitation in the docs isn't an actual limitation and just a recommendation. I tried writing a schema for this and was met with errors. Take this sample schema:

```json
{
  "logger": {
    "elasticsearch": {
      "enabled": "bool?",
      "node": "str?",
      "auth": {
        "username": "str?",
        "password": "str?",
        "apiKey": "str?"
      },
      "indexPrefix": "str?"
    }
  }
}
```

Adding this into an add-on will cause it to fail to load (see supervisor logs below). The same happens for nested arrays, e.g.:

```json
{
  "gpio": {
    "binarySensors": [
      {
        "name": "str"
      }
    ]
  }
}
```

I would expect any level of nesting to work, especially since there are no other options left for configuration.

**What is the used version of the Supervisor?**

supervisor-2021.02.6

**What type of installation are you running?**

Home Assistant Supervised

**Which operating system are you running on?**

Debian

**What is the version of your installed operating system?**

9.13

**What version of Home Assistant Core is installed?**

core-2021.2.1

**Steps to reproduce the issue**

1. Create a local add-on and configure the schema as shown above. You can use the [room-assistant add-on](https://github.com/mKeRix/hassio-repo/blob/master/room_assistant/config.json) as template.
2. Hit the reload button in the add-on store.
3. Observe the add-on not being loaded and warnings in the logs.
...

**Anything in the Supervisor logs that might be useful for us?**

```txt
# Log for nested objects
21-02-10 19:46:27 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/local/room_assistant/config.json: expected string or buffer for dictionary value @ data['schema']['logger']['elasticsearch']. Got {'enabled': 'bool?', 'node': 'str?', 'auth': {'username': 'str?', 'password': 'str?', 'apiKey': 'str?'}, 'indexPrefix': 'str?'}

# Log for nested array
21-02-10 20:58:12 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/local/room_assistant/config.json: expected string or buffer @ data['schema']['gpio']['binarySensors'][0]. Got {'name': 'str'}
```

This issue is aftermath of #2540, more info for this specific add-on can be found at mKeRix/room-assistant#501. This problem is preventing me from restoring the same functionality that my add-on had before the schema change.

**Comment by Poeschl** [comment]
Can confirm that the depth limit of 2 exists since last year. I rewrote my json configs with jq to be able to get all settings for a addon (https://github.com/Poeschl/Hassio-Addons/commit/ccfd9e620ee8885d298cb64365a8775b89460b46).

**Comment by Wh1terat** [comment]
```json
  "options": {
    "tunnels": [],
    "log_level": "info"
  },
  "schema": {
    "tunnels": [
      {
        "enabled":"bool",
        "credentials": {
          "AccountTag":"str",
          "TunnelSecret": "str",
          "TunnelID":"str",
          "TunnelName": "str"
        },
        "ingress": [
          {
            "hostname":"str?",
            "service":"str?",
            "path":"str?"
          }
        ]
      }
    ],
    "log_level": "list(trace|debug|info|warn|error|fatal|panic)"
  }
```

Argh. Just written my first addon and found this exact issue with regard to deep nesting. (which lets be fair, in the grand scheme of things is hardly "deep").

Should really be fixed; the limitation feels unnatural and unnecessary. 
I'm loathed to flatten everything, move to blobs - or standalone config files mapped over.

**Comment by casperklein** [comment]
You should open a new issue. Closed issues are not recognized in my experience.
