### ISSUE TITLE
Mount Access Removed from Next Generation Hardware

### ISSUE THREAD

**Issue by adamoutler** [home-assistant/supervisor#2562]
**Describe the issue you are experiencing**

The changes which deprecated access method devices:["remote:local:rw"] in favor of devices:["remote"], appear to have removed the ability to mount a drive without disabling protection mode. 

I found a related pull here.  https://github.com/home-assistant/supervisor/pull/2429#issue-553605434

In the event a user wishes to mount a drive, there certainly must be a way to do so from an addon without disabling protection mode. 

**What is the used version of the Supervisor?**

supervisor-2021.02.06

**What type of installation are you running?**

Home Assistant OS

**Which operating system are you running on?**

Home Assistant Operating System

**What is the version of your installed operating system?**

5.11

**What version of Home Assistant Core is installed?**

2021.02.03

**Steps to reproduce the issue**

1. Create and add-on with `SYS_ADMIN` permission
2. Add /dev/sda1 to config devices  (replace with mmcblk0p1 if required)
3. Disable AppArmor, or add permissions to /dev/sda1
4. Start the addon
5. `docker exec -it .... bash` into the addon
6. Execute `mkdir /tmp/1; mount /dev/sda1 /tmp/1;`
7.  Observe error message "are you root?"

Under old device, step 7 executes silently.  Under next generation hardware, it fails.  

**Anything in the Supervisor logs that might be useful for us?**

```txt
# Put your logs below this line

```

**Comment by frenck** [comment]
>  appear to have removed the ability to mount a drive without disabling protection mode.

I think that is totally correct and a wished-for situation.

**Comment by adamoutler** [comment]
This represents a source of extreme frustration.  This feature should be documented in the add-ons page. I think it's a good idea from a security standpoint, but bad from a usability standpoint.

To compensate for lowered usability, there should be some workaround to allow mounting of devices within one container, and sharing to another.  Eg. 
I want to mount my USB to /media in an unsecure container and make it usable within Home Assistant container, securely. Or, I want to mount my NAS to an unsecure container and make it usable within HomeHome Assistant.

Is there a preferred way to handle this or is this just deprecating a feature and causing the need for a red banner at the top of Add-ons which perform mundane tasks like mounting?  Has there been documented problems which required this change?

**Comment by frenck** [comment]
Yes, there are lots of device problems documented throughout the years. Just search the repo. Instead of old magic, there is now a more native solution towards device management and passthrough, which opens up a lot of possibilities and solves a lot of problems.

>  I think it's a good idea from a security standpoint, but bad from a usability standpoint.

Well, then we agree this is the correct solution.

**Comment by pvizeli** [comment]
Right, it need check if the devices from list need a `c` or `b` for generate the cgroup rules

**Comment by adamoutler** [comment]
I do not agree. This brings up issues with docker container compatibility and existing use cases.  Requiring Protection Mode disabled is a bad idea.  Certainly there is a solution which mitigates the risk

Security is always 1/2 of a  balancing act between itself and usability.   The most secure system is powered off and sealed in concrete at the bottom of the Marianas trench, but that is not usable.  

Android's permission system is an example of a way to keep the user informed while allowing risky behavior from an app.   I think protection mode is a bad concept and while it serves a development purpose, it doesn't address any concerns outside the mainstream model, thus containerizing the potential for out of the box thinking and growth of the ecosystem. 

Real-time permissions requests will not work here, but we could parse AppArmor directives to determine risky behavior and ask the user to confirm at first start of an addon, or to confirm upgrade.

**Comment by pvizeli** [comment]
> Real-time permissions requests will not work here, but we could parse AppArmor directives to determine risky behavior and ask the user to confirm at first start of an addon, or to confirm upgrade.

Nice idea with AppArmor patching. Would love to see an PR for that

**Comment by adamoutler** [comment]
@pvizeli I've never taken on a development project for HA aside from my own personal Addons published in the forums.  However, I do have several Linux certs and have knowledge on the various items contained within AppArmor and the Linux system itself.   I'm not scared of researching and writing a lookup table or parser class. I'm pretty familiar with back-end work. But I would like to chat and/or work with someone more skilled at HA Supervisor entry point, data, and display issues.   There are some questions I have about items like the current state of AppArmor post-installation-processing as well as formatting and displaying to the user.   

I think I could send a PR within a month, I think, but I need some basic questions answered first.  If interested, my email is public on my github.

**Comment by pvizeli** [comment]
That is opensource, everything is public :) You can write an ADR or RFC and there is a place for discussion before work can start. You can also pick up exists RFC and start to implement this for getting more feeling of how the Supervisor work. Or fix issues

**Comment by adamoutler** [comment]
Collaboration never hurts any project.  Is there an existing attempt or something I should start with?

**Comment by pvizeli** [comment]
I think a good start would be, that we can manage profiles directly from the container with the parser and the external service only use for initial compiling

**Comment by adamoutler** [comment]
Parsing add-ons AppArmor to determine permissions.  I did some initial work to lay out the initial creation here.   https://community.home-assistant.io/t/add-on-permissions-system-coming-soon/282544
@pvizeli
