### ISSUE TITLE
WARNING (MainThread)

### ISSUE THREAD

**Issue by hellresistor** [home-assistant/supervisor#2566]
**Describe the issue you are experiencing**

A warning on Supervisor About ESPHome.
I am not using ESPHome and not have installed it.

**What is the used version of the Supervisor?**

supervisor-2021.02.9

**What type of installation are you running?**

Home Assistant OS

**Which operating system are you running on?**

Home Assistant Operating System

**What is the version of your installed operating system?**

5.11

**What version of Home Assistant Core is installed?**

core-2021.2.3

**Steps to reproduce the issue**

1. Just Reboot

**Anything in the Supervisor logs that might be useful for us?**

```txt
21-02-14 13:08:33 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

```

**Comment by ludeeus** [comment]
This is expected, please report this to the maintainer of ESPHome like the warning says :+1:

**Comment by hellresistor** [comment]
https://github.com/esphome/issues/issues/1837

Done!
