### ISSUE TITLE
Incorrectly detected type of tty devices

### ISSUE THREAD

**Issue by adeepn** [home-assistant/supervisor#2574]
**Describe the issue you are experiencing**

In Hassos basic system:
# ls -la /dev/ttyA*
crw--w----    1 root     tty       243,   0 Feb 16 07:46 /dev/ttyAML0
crw-rw----    1 root     dialout   243,   2 Feb 16 07:23 /dev/ttyAML2
# ls -la /dev/ttyU*
crw-rw----    1 root     dialout   188,   0 Feb 16 06:41 /dev/ttyUSB0
crw-rw----    1 root     dialout   188,   1 Feb 16 06:41 /dev/ttyUSB1

# docker exec -it 4e0c7a19f477 bash  # homeassistant/aarch64-hassio-supervisor:latest
bash-5.1# ls -la /dev/ttyA*
crw--w----    1 root     tty       243,   0 Feb 16 06:42 /dev/ttyAML0
crw-rw----    1 root     audio     243,   2 Feb 16 06:42 /dev/ttyAML2
bash-5.1# ls -la /dev/ttyU*
crw-rw----    1 root     audio     188,   0 Feb 16 06:42 /dev/ttyUSB0
crw-rw----    1 root     audio     188,   1 Feb 16 06:42 /dev/ttyUSB1

# docker exec -it e867486a6f98 bash # homeassistant/odroid-c2-homeassistant:2021.2.3
bash-5.0# ls -la /dev/ttyA*
crw--w----    1 root     tty       243,   0 Feb 16 07:48 /dev/ttyAML0
crw-rw----    1 root     audio     243,   2 Feb 16 07:23 /dev/ttyAML2
bash-5.0# ls -la /dev/ttyU*
crw-rw----    1 root     audio     188,   0 Feb 16 06:41 /dev/ttyUSB0
crw-rw----    1 root     audio     188,   1 Feb 16 06:41 /dev/ttyUSB1

docker exec -it 3f4794387daf  bash  # zigbee2mqtt/zigbee2mqtt-aarch64:1.17.1-4
bash-5.1# ls -la /dev/ttyU*
crw-rw----    1 root     audio     188,   0 Feb 16 09:41 /dev/ttyUSB0
crw-rw----    1 root     audio     188,   1 Feb 16 09:41 /dev/ttyUSB1
bash-5.1# ls -la /dev/ttyA*
crw--w----    1 root     tty       243,   0 Feb 16 10:50 /dev/ttyAML0
crw-rw----    1 root     audio     243,   2 Feb 16 10:23 /dev/ttyAML2

And this devices not allowed for addons with uart:true config option.

**What is the used version of the Supervisor?**

supervisor-2021.02.9

**What type of installation are you running?**

Home Assistant OS

**Which operating system are you running on?**

Home Assistant Operating System

**What is the version of your installed operating system?**

Home Assistant OS 6.0.dev20210215

**What version of Home Assistant Core is installed?**

core-2021.2.3

**Steps to reproduce the issue**

1. PowerUp
2. You got it.

**Anything in the Supervisor logs that might be useful for us?**

```txt
# Put your logs below this line
journalctl |grep tty
Feb 02 17:18:11 homeassistant kernel: ff803000.serial: ttyAML0 at MMIO 0xff803000 (irq = 14, base_baud = 1500000) is a meson_uart                                                          
Feb 02 17:18:11 homeassistant kernel: printk: console [ttyAML0] enabled                                                                                                                    
Feb 02 17:18:11 homeassistant kernel: ff804000.serial: ttyAML2 at MMIO 0xff804000 (irq = 15, base_baud = 1500000) is a meson_uart                                                          
Feb 02 17:18:11 homeassistant kernel: ffd23000.serial: ttyAML1 at MMIO 0xffd23000 (irq = 19, base_baud = 1500000) is a meson_uart                                                          
Feb 02 17:18:11 homeassistant kernel: serial serial0: tty port ttyAML1 registered                                                                                                          
Feb 02 17:18:11 homeassistant systemd[1]: Created slice system-getty.slice.                                                                                                                
Feb 02 17:18:11 homeassistant systemd[1]: Created slice system-serial\x2dgetty.slice.                                                                                                      
Feb 02 17:18:11 homeassistant kernel: usb 1-1.1: cp210x converter now attached to ttyUSB0                                                                                                  
Feb 02 17:18:11 homeassistant kernel: usb 1-1.2: cp210x converter now attached to ttyUSB1                                                                                                  
Feb 02 17:18:12 homeassistant systemd[1]: Found device /dev/ttyAML0.                                                                                                                       
Feb 16 06:42:55 homeassistant systemd[1]: Started Getty on tty1.                                                                                                                           
Feb 16 06:42:55 homeassistant systemd[1]: Started Serial Getty on ttyAML0.                                                                                                                 

```

**Comment by adeepn** [comment]
In zigbree2mqtt I have error:
Feb 16 07:22:07 homeassistant 2fe940c7422a[498]: Zigbee2MQTT:error 2021-02-16 10:22:07: Error: Error while opening serialport 'Error: Error: Operation not permitted, cannot open /dev/ttyAML2'

But if add devices : [ '/dev/ttyAML2' ] to addon config error disapears.

**Comment by pvizeli** [comment]
@adeepn please post:
````
ha info
ha hardware info
```

**Comment by pvizeli** [comment]
```
Feb 02 17:18:12 homeassistant systemd[1]: Found device /dev/ttyAML0.                                                                                                                       
Feb 16 06:42:55 homeassistant systemd[1]: Started Getty on tty1.                                                                                                                           
Feb 16 06:42:55 homeassistant systemd[1]: Started Serial Getty on ttyAML0.  
```

Is bad, means you have a real console there, did you modify the boot args?

**Comment by adeepn** [comment]
#ha info

```
arch: aarch64
channel: stable
docker: 19.03.13
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: 6.0.dev20210215
homeassistant: 2021.2.3
hostname: homeassistant
logging: info
machine: odroid-c2
operating_system: Home Assistant OS 6.0.dev20210215
state: startup
supervisor: 2021.02.11
supported: true
supported_arch:
- aarch64
- armv7
- armhf
timezone: Europe/Moscow
```

ha hardware info (full [ha.hardware.txt](https://github.com/home-assistant/supervisor/files/6021685/ha.hardware.txt) )

```
- attributes:
    DEVNAME: /dev/ttyAML0
    DEVPATH: /devices/platform/soc/ff800000.bus/ff803000.serial/tty/ttyAML0
    MAJOR: "243"
    MINOR: "0"
    SUBSYSTEM: tty
    TAGS: ':systemd:'
    USEC_INITIALIZED: "8091503"
  by_id: null
  dev_path: /dev/ttyAML0
  name: ttyAML0
  subsystem: tty
  sysfs: /sys/devices/platform/soc/ff800000.bus/ff803000.serial/tty/ttyAML0
- attributes:
    DEVNAME: /dev/ttyAML2
    DEVPATH: /devices/platform/soc/ff800000.bus/ff804000.serial/tty/ttyAML2
    MAJOR: "243"
    MINOR: "2"
    SUBSYSTEM: tty
    TAGS: ':systemd:'
    USEC_INITIALIZED: "8108826"
  by_id: null
  dev_path: /dev/ttyAML2
  name: ttyAML2
  subsystem: tty
  sysfs: /sys/devices/platform/soc/ff800000.bus/ff804000.serial/tty/ttyAML2
```

cat /proc/devices
```
...
239 hidraw
240 rpmb
241 vfio
242 nvme
243 ttyAML
...
```

Seems that problem in major number. Supervisor wants 244, but kernel assign 243.
For example hidraw driver got major number 239, but supervisor wants 243.

**Comment by adeepn** [comment]
> ```
> Feb 02 17:18:12 homeassistant systemd[1]: Found device /dev/ttyAML0.                                                                                                                       
> Feb 16 06:42:55 homeassistant systemd[1]: Started Getty on tty1.                                                                                                                           
> Feb 16 06:42:55 homeassistant systemd[1]: Started Serial Getty on ttyAML0.  
> ```
> 
> Is bad, means you have a real console there, did you modify the boot args?

`bootargs "rootfstype=squashfs ro rootwait console=ttyAML0,115200n8 console=serial no_console_suspend consoleblank=0 ...`

Work in progress :) What could I have forgotten in the configuration?

**Comment by pvizeli** [comment]
Interesting, we can theoretically generate this group on runtime based on the device info. I just not have the time this or next week I guess for looking into that. But I keep it open.

**Comment by adeepn** [comment]
> Interesting, we can theoretically generate this group on runtime based on the device info. I just not have the time this or next week I guess for looking into that. But I keep it open.

These numbers are generally assigned dynamically. From https://www.kernel.org/doc/Documentation/admin-guide/devices.txt:
234-254	char	RESERVED FOR DYNAMIC ASSIGNMENT

**Comment by pvizeli** [comment]
Yeah, we need as additional use the fixed group + look if there are some at runtime
