### ISSUE TITLE
Warnings re vlc & ESPHome

### ISSUE THREAD

**Issue by PierreScerri** [home-assistant/supervisor#2582]
**Describe the issue you are experiencing**

I am getting the errors listed below.

Don't know where to direct this query.

**What is the used version of the Supervisor?**

supervisor-2021.02.9

**What type of installation are you running?**

Home Assistant OS

**Which operating system are you running on?**

Home Assistant Operating System

**What is the version of your installed operating system?**

5.11

**What version of Home Assistant Core is installed?**

supervisor-2021.02.9

**Steps to reproduce the issue**

1.
2.
3.
...

**Anything in the Supervisor logs that might be useful for us?**

```txt
# Put your logs below this line
21-02-17 12:37:43 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/vlc/config.json: Service vlc_telnet not found @ data['discovery'][0]. Got 'vlc_telnet'
21-02-17 12:37:44 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-17 12:37:44 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/vlc/config.json: Service vlc_telnet not found @ data['discovery'][0]. Got 'vlc_telnet'
21-02-17 12:37:44 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

```

**Comment by pvizeli** [comment]
going away in next couble of days
