### ISSUE TITLE
Unable to update to 2021.02.9

### ISSUE THREAD

**Issue by xpoh1980** [home-assistant/supervisor#2584]
**Describe the issue you are experiencing**

Can't update supervisor to 2021.02.9 running on docker.
When i do:
  docker pull homeassistant/armv7-hassio-supervisor:2021.02.9

i got error:
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/cdfe85eb8fe3f068446751cfee678037b72d0c0b35dd6ffd870551dabf99a0b6/merged: too many levels of symbolic links

But i can  pull  all prior versions without any problem? Please tell help me what is wrong?

**What is the used version of the Supervisor?**

2021.02.9

**What type of installation are you running?**

Home Assistant Supervised

**Which operating system are you running on?**

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

**What is the version of your installed operating system?**

Ubuntu 19.10

**What version of Home Assistant Core is installed?**

2021.02.3

**Steps to reproduce the issue**

Update the supervisor from HA or from console

**Anything in the Supervisor logs that might be useful for us?**

```txt
# Put your logs below this line

```

**Comment by frenck** [comment]
> Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

Is not a supported system.

You could try running `ha supervisor repair`, that might help.
