### ISSUE TITLE
Snapshot - Unknown error, see supervisor logs - but *no* errors in the logs

### ISSUE THREAD

**Issue by brianacox** [home-assistant/supervisor#2624]
**Describe the issue you are experiencing**

Hi, I've been getting the widely reported 'Unknown error, see supervisor logs' error, but unlike many others the logs don't reveal any problems - see logs.
 
21-02-25 14:04:16 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-02-25 14:04:16 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-02-25 14:06:06 INFO (MainThread) [supervisor.snapshots] Found 9 snapshot files
21-02-25 14:06:13 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug b39e0a2e
21-02-25 14:06:13 INFO (MainThread) [supervisor.snapshots] Snapshotting b39e0a2e store Add-ons
21-02-25 14:06:13 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_vscode
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_vscode
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 7ad98f9c_zigbee2mqtt
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 7ad98f9c_zigbee2mqtt
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_portainer
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_portainer
21-02-25 14:06:21 INFO (MainThread) [supervisor.snapshots] Snapshotting b39e0a2e store folders
21-02-25 14:06:21 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
21-02-25 14:08:06 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
21-02-25 14:08:06 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder share
21-02-25 14:08:06 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder share done
21-02-25 14:08:06 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder ssl
21-02-25 14:08:06 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder ssl done
21-02-25 14:08:06 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder addons/local
21-02-25 14:08:06 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
21-02-25 14:08:06 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder media
21-02-25 14:08:06 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder media done
21-02-25 14:08:07 INFO (MainThread) [supervisor.snapshots] Creating full-snapshot with slug b39e0a2e completed

**What is the used version of the Supervisor?**

supervisor-2021.02.11

**What type of installation are you running?**

Home Assistant OS

**Which operating system are you running on?**

Home Assistant Operating System

**What is the version of your installed operating system?**

5.12

**What version of Home Assistant Core is installed?**

core-2021.2.3

**Steps to reproduce the issue**

1.Create Snapshot (e.g. Test)
2.
3.
...

**Anything in the Supervisor logs that might be useful for us?**

21-02-25 13:04:16 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-02-25 13:04:16 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-02-25 13:09:47 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-02-25 13:09:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-02-25 13:09:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-02-25 13:09:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/danielwelch/hassio-zigbee2mqtt repository
21-02-25 13:09:54 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
21-02-25 13:09:54 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
21-02-25 14:04:16 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-02-25 14:04:16 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-02-25 14:06:06 INFO (MainThread) [supervisor.snapshots] Found 9 snapshot files
21-02-25 14:06:13 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug b39e0a2e
21-02-25 14:06:13 INFO (MainThread) [supervisor.snapshots] Snapshotting b39e0a2e store Add-ons
21-02-25 14:06:13 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_vscode
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_vscode
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 7ad98f9c_zigbee2mqtt
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 7ad98f9c_zigbee2mqtt
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_portainer
21-02-25 14:06:21 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_portainer
21-02-25 14:06:21 INFO (MainThread) [supervisor.snapshots] Snapshotting b39e0a2e store folders
21-02-25 14:06:21 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
21-02-25 14:08:06 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
21-02-25 14:08:06 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder share
21-02-25 14:08:06 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder share done
21-02-25 14:08:06 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder ssl
21-02-25 14:08:06 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder ssl done
21-02-25 14:08:06 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder addons/local
21-02-25 14:08:06 INFO (SyncWorker_1) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
21-02-25 14:08:06 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder media
21-02-25 14:08:06 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder media done
21-02-25 14:08:07 INFO (MainThread) [supervisor.snapshots] Creating full-snapshot with slug b39e0a2e completed
21-02-25 14:09:54 INFO (MainThread) [supervisor.host.info] Updating local host information
21-02-25 14:09:55 INFO (MainThread) [supervisor.host.services] Updating service information
21-02-25 14:09:55 INFO (MainThread) [supervisor.host.network] Updating local network information
21-02-25 14:09:56 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-02-25 14:09:56 INFO (MainThread) [supervisor.host] Host information reload completed
21-02-25 14:14:52 INFO (MainThread) [supervisor.snapshots] Found 10 snapshot files
21-02-25 14:15:03 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug c0bc9b29
21-02-25 14:15:03 INFO (MainThread) [supervisor.snapshots] Snapshotting c0bc9b29 store Add-ons
21-02-25 14:15:03 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_vscode
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_vscode
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 7ad98f9c_zigbee2mqtt
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 7ad98f9c_zigbee2mqtt
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_portainer
21-02-25 14:15:07 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_portainer
21-02-25 14:15:07 INFO (MainThread) [supervisor.snapshots] Snapshotting c0bc9b29 store folders
21-02-25 14:15:07 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
21-02-25 14:16:43 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
21-02-25 14:16:43 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder share
21-02-25 14:16:43 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder share done
21-02-25 14:16:43 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder ssl
21-02-25 14:16:43 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder ssl done
21-02-25 14:16:43 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local
21-02-25 14:16:43 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
21-02-25 14:16:43 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder media
21-02-25 14:16:43 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder media done
21-02-25 14:16:44 INFO (MainThread) [supervisor.snapshots] Creating full-snapshot with slug c0bc9b29 completed
21-02-25 14:18:30 INFO (MainThread) [supervisor.snapshots] Found 11 snapshot files

**Comment by ludeeus** [comment]
Fixed in supervisor-2021.02.11, it's was a timeout
