### ISSUE TITLE
Auto update add-ons does not work

### ISSUE THREAD

**Issue by nelbs** [home-assistant/supervisor#2643]
**Describe the issue you are experiencing**

My addons are not automatically updated even though I have enabled auto update. I don’t remember it working at all. In the logs I do not see any messages indicating an error. Manual update however works flawless.

**What is the used version of the Supervisor?**

supervisor-2021.02.11

**What type of installation are you running?**

Home Assistant Supervised

**Which operating system are you running on?**

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

**What is the version of your installed operating system?**

Raspbian GNU/Linux 10 (buster) docker version 20.10.2

**What version of Home Assistant Core is installed?**

core-2021.2.3

**Steps to reproduce the issue**

1.
2.
3.
...

**Anything in the Supervisor logs that might be useful for us?**

```txt
# Put your logs below this line

```

**Comment by ludeeus** [comment]
The task to auto-update runs every 16h after startup. most likely you did not give it enough time.
However you are running an unsupported environment, so closing this issue.
<https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>
