### ISSUE TITLE
ESPHome HA Addon 1.16.2 missing configuration section

### ISSUE THREAD

**Issue by pcartwright81** [home-assistant/supervisor#2653]
**Describe the issue you are experiencing**

I hit reset on the configuration section, now it is missing in the UI.  Was told it was a supervisor issue that is currently in beta testing, and I think I am on a version that should have it.

**What is the used version of the Supervisor?**

supervisor-2021.02.dev2801

**What type of installation are you running?**

Home Assistant OS

**Which operating system are you running on?**

Home Assistant Operating System

**What is the version of your installed operating system?**

5.12

**What version of Home Assistant Core is installed?**

core-2021.4.0.dev20210228

**Steps to reproduce the issue**

Go to Supervisor=>EspHome=>Config

**Anything in the Supervisor logs that might be useful for us?**

```txt
# Put your logs below this line

```

**Comment by ludeeus** [comment]
It was fixed here  <https://github.com/home-assistant/frontend/pull/8487>
