### ISSUE TITLE
Cannot mount /dev/sda1 inside my own addon with privileged mode enabled

### ISSUE THREAD

**Issue by quarcko** [home-assistant/supervisor#2677]
### Describe the issue you are experiencing

I use my own custom modified addon version of MariaDB
(please keep in mind this is not a problem with addon itself)

So i run it with protection mode disabled, and i mount external USB drive
to offload files to it, so microSD card is not wearing much.

I was always updating Supervisor whenever possible, and all was running
smoothly well, until i updated OS to 5.12 (which obviously caused reboot)
and problem started. I tried to fill a report in here:
https://github.com/home-assistant/operating-system/issues/1259
but was informed, that most probably it is not OS, its Supervisor change
that is causing it.

I tried logging into addon console with portainer, and trying to do:

bash-5.0# mount /dev/sda1 /share/usb
mount: permission denied (are you root?)
bash-5.0# whoami
root

What has changed? How can i again mount my USB drive and use it inside my addon?
Also - USB drive is healthy, i tried it on my PC and it mounts RW okay.
file system check also did not find any errors on it.
File system on it is EXT4 if this matters.

Are there any new permissions needed to mount external drive to addon?

### What is the used version of the Supervisor?

supervisor-2021.03.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.2.3

### Steps to reproduce the issue

1. Create addon with privileged permissions
2. Try to mount /dev/sdXX device
3. mount fails
...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line
Nothing is seend in supervisor while trying to do mount.
```

**Comment by quarcko** [comment]
BUMP, anyone?
I really need this feature back working!
running with no recorder for almost 2 weeks is no fun...

**Comment by mdegat01** [comment]
I just noticed in the #devs_supervisor chat in discord that AdamOutler said this which seems related:
![Screen Shot 2021-03-17 at 12 45 08 AM](https://user-images.githubusercontent.com/2037026/111416358-25bb4100-86ba-11eb-9d1b-bfc23cb4e214.png)

Based on that comment it sounds like you can only remount `/dev/sda1` if your addon has full access and devices access. Supervisor is going to yell at you in the logs if you do that apparently but sounds like it might give you a workaround?

**Comment by quarcko** [comment]
@mdegat01 - thank you for your comment, but i always had in my config both device access and full access.
And as well i had this warning in supervisor some month ago or so - and it was working alright back then
like AdamOutler says.

But after some update of supervisor (most probably) - having device access and full access is not enough anymore.
i even tried disabling apparmor of the addon as well - no difference, cannot mount.

supervisor devs - is there anything else needs to be done do access external storage devices?

**Comment by quarcko** [comment]
@mdegat01 - Thank you this time for real!
i looked into AdamOutler's github at his addons configs and found all the options needed so supervisor is allowing
access to /dev/sda1 !!!!

For anybody who will search in the future:
"apparmor": false,
"privileged": ["SYS_ADMIN"],
"devices": ["/dev/sda1"],
"full_access": true

with exactly this combination i am able to mount /dev/sda1 again :)

Anyway, why it is so hard to access simple flash drive for my own purposes is still mystery for me,
like, i am not trying to initiate launch of SpaceX rocket, it is just a USB disk....

closing.
