### ISSUE TITLE
Watchdog found a problem with PulseAudio plugin!

### ISSUE THREAD

**Issue by mrbluebrett** [home-assistant/supervisor#2688]
### Describe the issue you are experiencing

I have a Bootloop of the audio plugin that I don't know how to stop. It is consuming some CPU in my system.
21-03-05 10:04:39 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-03-05 10:04:40 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning hassio_audio application
21-03-05 10:04:41 INFO (SyncWorker_1) [supervisor.docker.audio] Starting Audio homeassistant/amd64-hassio-audio with version 2021.02.1 - 172.30.32.4
21-03-05 10:05:41 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with PulseAudio plugin!
21-03-05 10:05:41 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-03-05 10:05:41 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning hassio_audio application
21-03-05 10:05:42 INFO (SyncWorker_4) [supervisor.docker.audio] Starting Audio homeassistant/amd64-hassio-audio with version 2021.02.1 - 172.30.32.4

### What is the used version of the Supervisor?

supervisor-2021.03.4

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.3.1

### Steps to reproduce the issue

I saw a bit of high CPU usage and i found the Supervisor log in an etern loop of trying to boot Audio plugin, failing and starting again...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line

21-03-05 10:08:44 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-03-05 10:08:44 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning hassio_audio application
21-03-05 10:08:46 INFO (SyncWorker_4) [supervisor.docker.audio] Starting Audio homeassistant/amd64-hassio-audio with version 2021.02.1 - 172.30.32.4
21-03-05 10:09:46 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with PulseAudio plugin!
21-03-05 10:09:46 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-03-05 10:09:46 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning hassio_audio application
21-03-05 10:09:47 INFO (SyncWorker_4) [supervisor.docker.audio] Starting Audio homeassistant/amd64-hassio-audio with version 2021.02.1 - 172.30.32.4
21-03-05 10:10:47 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with PulseAudio plugin!
21-03-05 10:10:47 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-03-05 10:10:47 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning hassio_audio application
21-03-05 10:10:49 INFO (SyncWorker_4) [supervisor.docker.audio] Starting Audio homeassistant/amd64-hassio-audio with version 2021.02.1 - 172.30.32.4

**Comment by mrbluebrett** [comment]
I leave the Audio log too:
Error relocating /lib/libkmod.so.2: ZSTD_freeDStream: symbol not found
Error relocating /lib/libkmod.so.2: ZSTD_getErrorName: symbol not found
Error relocating /lib/libkmod.so.2: ZSTD_DStreamOutSize: symbol not found
Error relocating /lib/libkmod.so.2: ZSTD_initDStream: symbol not found
Error relocating /usr/bin/pulseaudio: pa_memtrap_install: symbol not found
Error relocating /usr/bin/pulseaudio: pa_pipe_cloexec: symbol not found
Error relocating /usr/bin/pulseaudio: pa_set_env: symbol not found
Error relocating /usr/bin/pulseaudio: pa_log_parse_target: symbol not found
Error relocating /usr/bin/pulseaudio: pa_strlist_free: symbol not found
Error relocating /usr/bin/pulseaudio: pa_realpath: symbol not found
Error relocating /usr/bin/pulseaudio: pa_nullify_stdfds: symbol not found
Error relocating /usr/bin/pulseaudio: pa_find_config_file: symbol not found
Error relocating /usr/bin/pulseaudio: pa_log_set_ident: symbol not found
Error relocating /usr/bin/pulseaudio: pa_ncpus: symbol not found
Error relocating /usr/bin/pulseaudio: pa_open_config_file: symbol not found
Error relocating /usr/bin/pulseaudio: pa_client_conf_free: symbol not found
Error relocating /usr/bin/pulseaudio: pa_strlist_parse: symbol not found
Error relocating /usr/bin/pulseaudio: pa_log_target_to_string: symbol not found
Error relocating /usr/bin/pulseaudio: pa_unset_env_recorded: symbol not found
Error relocating /usr/bin/pulseaudio: pa_runtime_path: symbol not found
Error relocating /usr/bin/pulseaudio: pa_cpu_init: symbol not found
Error relocating /usr/bin/pulseaudio: pa_machine_id: symbol not found
Error relocating /usr/bin/pulseaudio: pa_random_seed: symbol not found
Error relocating /usr/bin/pulseaudio: pa_startswith: symbol not found
Error relocating /usr/bin/pulseaudio: pa_autospawn_lock_done: symbol not found
Error relocating /usr/bin/pulseaudio: pa_module_load: symbol not found
Error relocating /usr/bin/pulseaudio: pa_strbuf_free: symbol not found
Error relocating /usr/bin/pulseaudio: pa_reset_sigs: symbol not found
Error relocating /usr/bin/pulseaudio: pa_cstrerror: symbol not found
Error relocating /usr/bin/pulseaudio: pa_log_set_level: symbol not found
Error relocating /usr/bin/pulseaudio: pa_pid_file_remove: symbol not found
Error relocating /usr/bin/pulseaudio: pa_run_from_build_tree: symbol not found
Error relocating /usr/bin/pulseaudio: pa_unblock_sigs: symbol not found
Error relocating /usr/bin/pulseaudio: pa_modinfo_free: symbol not found
Error relocating /usr/bin/pulseaudio: pa_loop_write: symbol not found
Error relocating /usr/bin/pulseaudio: pa_make_secure_dir: symbol not found
Error relocating /usr/bin/pulseaudio: pa_make_fd_nonblock: symbol not found
Error relocating /usr/bin/pulseaudio: pa_pid_file_kill: symbol not found
Error relocating /usr/bin/pulseaudio: pa_read: symbol not found
Error relocating /usr/bin/pulseaudio: pa_close_pipe: symbol not found
Error relocating /usr/bin/pulseaudio: pa_cli_command_execute_file_stream: symbol not found
Error relocating /usr/bin/pulseaudio: pa_close_allv: symbol not found
Error relocating /usr/bin/pulseaudio: pa_client_conf_load: symbol not found
Error relocating /usr/bin/pulseaudio: pa_disable_sigpipe: symbol not found
Error relocating /usr/bin/pulseaudio: pa_client_conf_new: symbol not found
Error relocating /usr/bin/pulseaudio: pa_write: symbol not found
Error relocating /usr/bin/pulseaudio: pa_dbus_bus_get: symbol not found
Error relocating /usr/bin/pulseaudio: pa_get_state_dir: symbol not found
Error relocating /usr/bin/pulseaudio: pa_atoi: symbol not found
Error relocating /usr/bin/pulseaudio: pa_atou: symbol not found
Error relocating /usr/bin/pulseaudio: pa_idxset_size: symbol not found
Error relocating /usr/bin/pulseaudio: pa_log_level_meta: symbol not found
Error relocating /usr/bin/pulseaudio: pa_resample_method_supported: symbol not found
Error relocating /usr/bin/pulseaudio: pa_strbuf_puts: symbol not found
Error relocating /usr/bin/pulseaudio: pa_get_dbus_address_from_server_type: symbol not found
Error relocating /usr/bin/pulseaudio: pa_in_system_mode: symbol not found
Error relocating /usr/bin/pulseaudio: pa_log_set_show_backtrace: symbol not found
Error relocating /usr/bin/pulseaudio: pa_parse_boolean: symbol not found
Error relocating /usr/bin/pulseaudio: pa_log_set_target: symbol not found
Error relocating /usr/bin/pulseaudio: pa_strbuf_new: symbol not found
Error relocating /usr/bin/pulseaudio: pa_reset_personality: symbol not found
Error relocating /usr/bin/pulseaudio: pa_pid_file_create: symbol not found
Error relocating /usr/bin/pulseaudio: pa_full_status_string: symbol not found
Error relocating /usr/bin/pulseaudio: pa_session_id: symbol not found
Error relocating /usr/bin/pulseaudio: pa_parse_resample_method: symbol not found
Error relocating /usr/bin/pulseaudio: pa_autospawn_lock_release: symbol not found
Error relocating /usr/bin/pulseaudio: pa_object_unref: symbol not found
Error relocating /usr/bin/pulseaudio: pa_stdio_acquire: symbol not found
Error relocating /usr/bin/pulseaudio: pa_fopen_cloexec: symbol not found
Error relocating /usr/bin/pulseaudio: pa_core_check_idle: symbol not found
Error relocating /usr/bin/pulseaudio: pa_rtclock_hrtimer: symbol not found
Error relocating /usr/bin/pulseaudio: pa_get_runtime_dir: symbol not found
Error relocating /usr/bin/pulseaudio: pa_page_size: symbol not found
Error relocating /usr/bin/pulseaudio: pa_raise_priority: symbol not found
Error relocating /usr/bin/pulseaudio: pa_uname_string: symbol not found
Error relocating /usr/bin/pulseaudio: pa_readlink: symbol not found
Error relocating /usr/bin/pulseaudio: pa_init_i18n: symbol not found
Error relocating /usr/bin/pulseaudio: pa_strbuf_printf: symbol not found
Error relocating /usr/bin/pulseaudio: pa_cli_command_execute: symbol not found
Error relocating /usr/bin/pulseaudio: pa_log_target_free: symbol not found
Error relocating /usr/bin/pulseaudio: pa_pid_file_check_running: symbol not found
Error relocating /usr/bin/pulseaudio: pa_modinfo_get_by_name: symbol not found
Error relocating /usr/bin/pulseaudio: pa_set_env_and_record: symbol not found
Error relocating /usr/bin/pulseaudio: pa_rtclock_hrtimer_enable: symbol not found
Error relocating /usr/bin/pulseaudio: pa_config_parse: symbol not found
Error relocating /usr/bin/pulseaudio: pa_loop_read: symbol not found
Error relocating /usr/bin/pulseaudio: pa_log_set_flags: symbol not found
Error relocating /usr/bin/pulseaudio: pa_running_in_vm: symbol not found
Error relocating /usr/bin/pulseaudio: pa_close: symbol not found
Error relocating /usr/bin/pulseaudio: pa_config_parse_int: symbol not found
Error relocating /usr/bin/pulseaudio: pa_config_parse_string: symbol not found
Error relocating /usr/bin/pulseaudio: pa_config_parse_bool: symbol not found
Error relocating /usr/bin/pulseaudio: pa_config_parse_not_bool: symbol not found
Error relocating /usr/bin/pulseaudio: pa_config_parse_size: symbol not found
Error relocating /usr/bin/pulseaudio: pa_config_parse_unsigned: symbol not found
Error relocating /usr/bin/pulseaudio: pa_object_type_id: symbol not found
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by JJFourie** [comment]
It does not look related, but just to cover that possibility.. do you perhaps suffer from the problem explained in this [Home Assistant forum topic](https://community.home-assistant.io/t/solved-hassio-audio-is-in-boot-loop-and-spams-my-syslog-with-errors/282538/93?u=jofie), and does it help?
