### ISSUE TITLE
Supervisor Disconnections / Fails to start

### ISSUE THREAD

**Issue by MickPBduece** [home-assistant/supervisor#2705]
### Describe the issue you are experiencing

Supervisor does not start after a reboot, fails while system is running and is unable to complete an upgrade

### What is the used version of the Supervisor?

supervisor-2021.03.4

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Raspbian GNU/Linux 10 (buster) Linux ha 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

### What version of Home Assistant Core is installed?

core-2021.2.3

### Steps to reproduce the issue

1.Reboot and 
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line

```

**Comment by ludeeus** [comment]
Update docker.
Closing this issue as it's an unsupported installation

**Comment by MickPBduece** [comment]
My apologies for the misunderstanding but what in my install is not
supported?
I want to correct this but thought I was in compliance per
https://www.home-assistant.io/more-info/unsupported/os/

Thanks

**Comment by MickPBduece** [comment]
I'd prefer to rebuild a supported version.   I thought Debian 10 was supported per https://www.home-assistant.io/more-info/unsupported/os/.  Docker was already updated to 20.10.5 and HA install script re-run before raising this
