### ISSUE TITLE
Zwavejs2MQTT connection error after Core reboot

### ISSUE THREAD

**Issue by degrashopper** [home-assistant/supervisor#2710]
### Describe the issue you are experiencing

After rebooting Core (while the zwavejs2mqtt addon is still running) The following error is shown in the supervisor log

ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://<IP>:<port>/socket.io/?EIO=4&transport=websocket&sid=oC-UaJlAltRuDEJnAAAe')

### What is the used version of the Supervisor?

supervisor-2021.03.4

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 10 (buster) latest patch

### What version of Home Assistant Core is installed?

core-2021.3.3

### Steps to reproduce the issue

1. restart HA (while zwave2mqtt addon is running)
2. Check supervisor log
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line

ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://<IP>:<port>/socket.io/?EIO=4&transport=websocket&sid=oC-UaJlAltRuDEJnAAAe')

**Comment by frenck** [comment]
This is expected and normal behavior, as Ingress becomes temporary unavailable in that case.
