### ISSUE TITLE
Unable to Get Snapshot since last update

### ISSUE THREAD

**Issue by tagz1979** [home-assistant/supervisor#2736]
### Describe the issue you are experiencing

Since the last update I am unable to get a snapshot of system

### What is the used version of the Supervisor?

2021.03.6

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.3.4

### Steps to reproduce the issue

1.Got to snapshots
2.Click Create full snapshot
3.
...

### Anything in the Supervisor logs that might be useful for us?

21-03-19 21:41:57 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-356086' coro=<HomeAssistantWebSocket.async_supervisor_update_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:133> exception=TypeError('Received message 257:None is not str')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 138, in async_supervisor_update_event
    await self.async_send_command(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 129, in async_send_command
    return await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 46, in async_send_command
    response = await self.client.receive_json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_ws.py", line 291, in receive_json
    data = await self.receive_str(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_ws.py", line 276, in receive_str
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not str")
TypeError: Received message 257:None is not str

**Comment by ludeeus** [comment]
Please post the output of the entire supervisor log when you do this

**Comment by tagz1979** [comment]
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:106
Integration: Hass.io (documentation, issues)
First occurred: March 19, 2021, 5:46:57 PM (2 occurrences)
Last logged: 10:04:29 AM

Failed to to call /snapshots/new/full -

**Comment by tagz1979** [comment]
Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:206
Integration: Hass.io (documentation, issues)
First occurred: March 19, 2021, 5:46:57 PM (2 occurrences)
Last logged: 10:04:29 AM

Timeout on /snapshots/new/full request

**Comment by tagz1979** [comment]
21-03-20 11:06:14 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-03-20 11:06:14 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-03-20 11:07:27 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 11:07:28 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-03-20 11:11:22 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-20 11:19:42 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-03-20 11:41:28 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-20 12:06:14 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-20 12:06:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-03-20 12:06:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-03-20 12:06:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-03-20 12:06:14 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-20 12:06:14 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-03-20 12:06:14 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-03-20 12:07:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
21-03-20 12:07:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-03-20 12:07:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/hassio repository
21-03-20 12:07:34 INFO (MainThread) [supervisor.store] Loading add-ons from store: 27 all - 0 new - 0 remove
21-03-20 12:07:34 INFO (MainThread) [supervisor.store] Loading add-ons from store: 27 all - 0 new - 0 remove
21-03-20 12:11:35 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-20 12:13:38 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 12:13:53 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot 8eae2264
21-03-20 12:14:36 INFO (MainThread) [supervisor.host.info] Updating local host information
21-03-20 12:14:37 INFO (MainThread) [supervisor.host.services] Updating service information
21-03-20 12:14:37 INFO (MainThread) [supervisor.host.network] Updating local network information
21-03-20 12:14:40 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-03-20 12:14:40 INFO (MainThread) [supervisor.host] Host information reload completed
21-03-20 12:19:43 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-03-20 12:41:42 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-03-20 13:07:28 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-03-20 13:11:48 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-20 13:19:44 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-03-20 13:41:55 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-20 13:59:19 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 13:59:28 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug bb0fe563
21-03-20 13:59:28 INFO (MainThread) [supervisor.snapshots] Snapshotting bb0fe563 store Add-ons
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_duckdns
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_duckdns
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_ssh
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_ssh
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_zwavejs2mqtt
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_zwavejs2mqtt
21-03-20 13:59:29 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on cebe7a76_hassio_google_drive_backup
21-03-20 13:59:29 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon cebe7a76_hassio_google_drive_backup
21-03-20 13:59:29 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 15ef4d2f_esphome
21-03-20 13:59:39 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 15ef4d2f_esphome
21-03-20 13:59:39 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mariadb
21-03-20 14:04:56 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:05:00 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:06:34 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files

**Comment by ludeeus** [comment]
It has not failed in those logs, it's still creating bathe snapshot

**Comment by tagz1979** [comment]
Here is another log, The error I keep getting  is unkown error

21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-03-20 13:06:14 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-03-20 13:07:28 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-03-20 13:11:48 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-20 13:19:44 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-03-20 13:41:55 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-20 13:59:19 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 13:59:28 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug bb0fe563
21-03-20 13:59:28 INFO (MainThread) [supervisor.snapshots] Snapshotting bb0fe563 store Add-ons
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_duckdns
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_duckdns
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_ssh
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_ssh
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_zwavejs2mqtt
21-03-20 13:59:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_zwavejs2mqtt
21-03-20 13:59:29 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on cebe7a76_hassio_google_drive_backup
21-03-20 13:59:29 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon cebe7a76_hassio_google_drive_backup
21-03-20 13:59:29 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 15ef4d2f_esphome
21-03-20 13:59:39 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 15ef4d2f_esphome
21-03-20 13:59:39 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mariadb
21-03-20 14:04:56 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:05:00 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:06:34 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:07:15 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:08:53 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:08:58 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:09:07 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:10:11 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mariadb
21-03-20 14:10:11 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_zwave_js
21-03-20 14:10:11 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_zwave_js
21-03-20 14:10:11 INFO (MainThread) [supervisor.snapshots] Snapshotting bb0fe563 store folders
21-03-20 14:10:11 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder share
21-03-20 14:10:11 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder share done
21-03-20 14:10:11 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder addons/local
21-03-20 14:10:11 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
21-03-20 14:10:11 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder ssl
21-03-20 14:10:11 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder ssl done
21-03-20 14:10:11 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
21-03-20 14:10:14 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
21-03-20 14:10:14 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder media
21-03-20 14:10:14 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder media done
21-03-20 14:10:20 INFO (MainThread) [supervisor.snapshots] Creating full-snapshot with slug bb0fe563 completed
21-03-20 14:10:25 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-03-20 14:10:25 INFO (MainThread) [supervisor.api.security] /snapshots/bb0fe563/info access from cebe7a76_hassio_google_drive_backup
21-03-20 14:10:26 INFO (MainThread) [supervisor.api.security] /snapshots/ff05dcf6/remove access from cebe7a76_hassio_google_drive_backup
21-03-20 14:10:26 INFO (MainThread) [supervisor.snapshots] Removed snapshot file ff05dcf6
21-03-20 14:10:26 INFO (MainThread) [supervisor.api.security] /snapshots/bb0fe563/download access from cebe7a76_hassio_google_drive_backup
21-03-20 14:10:26 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot bb0fe563
21-03-20 14:11:34 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:12:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-20 14:12:13 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:13:15 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-03-20 14:13:17 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug 6503092d
21-03-20 14:13:17 INFO (MainThread) [supervisor.snapshots] Snapshotting 6503092d store Add-ons
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_duckdns
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_duckdns
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_ssh
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_ssh
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_zwavejs2mqtt
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_zwavejs2mqtt
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on cebe7a76_hassio_google_drive_backup
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon cebe7a76_hassio_google_drive_backup
21-03-20 14:13:17 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 15ef4d2f_esphome
21-03-20 14:13:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 15ef4d2f_esphome
21-03-20 14:13:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mariadb

**Comment by ludeeus** [comment]
It has not failed in those logs, it's still creating the snapshot

**Comment by ludeeus** [comment]
Do you have logs that show that it fails? or does it eventually complete the snapshot?

**Comment by tagz1979** [comment]
It looks like it eventually completes, However I don't know if it will work. I never tried to restore after it errored out

**Comment by ludeeus** [comment]
Nothing here indicates that it "errored out", the error in your first post is not related to the snapshot process

**Comment by lukas947** [comment]
At least for me it errors (or times) -out in GUI, referring to supervisor logs. I can see same behavior as OP, but snapshots are taking very long time since the update which introduced dialog with partial snapshots before upgrading add-ons / core. I also noticed i cannot "git add" or "git commit" directly from the config folder due to error "Out of memory", which might be related, or not... Looks like a memory issue to me.

**Comment by ludeeus** [comment]
Timeout in the UI has been fixed in core, and will be a part of the next release first Wednesday of April.

**Comment by lukas947** [comment]
I see. Thank you! :)

But is it normal the snapshots are taking much longer time now? Mine has been running for over 1,5h (approx 5GB tar).

**Comment by tagz1979** [comment]
I guess I'll wait till next release thank you for the information

**Comment by tagz1979** [comment]
This can be closed
