### ISSUE TITLE
Supervisor Update impossible 500 Server Error

### ISSUE THREAD

**Issue by Tat234** [home-assistant/supervisor#2737]
### Describe the issue you are experiencing

Update impossible for Home-assistant supervisor.

### What is the used version of the Supervisor?

supervisor-2021.03.dev1901

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.3.4

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line

```

21-03-20 10:36:17 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-03-20 10:36:17 INFO (MainThread) [__main__] Running Supervisor
21-03-20 10:36:17 INFO (MainThread) [supervisor.hassos] Rauc: A - marked slot kernel.0 as good
21-03-20 10:36:17 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor.txt
21-03-20 10:36:17 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
21-03-20 10:36:17 INFO (MainThread) [supervisor.host.services] Reloading local service hassos-apparmor.service
21-03-20 10:36:18 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2021.03.6
21-03-20 10:36:18 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-hassio-supervisor with tag 2021.03.6.
21-03-20 10:36:19 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install homeassistant/aarch64-hassio-supervisor:2021.03.6 -> 500 Server Error for http+docker://localhost/v1.40/images/homeassistant/aarch64-hassio-supervisor:2021.03.6/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument").
21-03-20 10:36:19 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed!
21-03-20 10:36:19 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.UPDATE_FAILED - ContextType.SUPERVISOR / None
21-03-20 10:36:19 CRITICAL (MainThread) [supervisor.core] Can't update Supervisor! This will break some Add-ons or affect future versions of Home Assistant!

Hello everybody, 

I'm beginning with GitHub and Home-assistant, and I have 2 problems with the supervisor :

First, I cannot add any repositories it just doesn't work, and this may be linked to my second problem, I cannot update my supervisor. I did not find the exact same subject on the internet, maybe I didn't searched well, but nothing helped me and I don't truly understand everything so excuse me by advance for my mistakes and hopefully we will find a solution all together.

Thanks for your help !

**Comment by pvizeli** [comment]
`Can't install homeassistant/aarch64-hassio-supervisor:2021.03.6 -> 500 Server Error for http+docker://localhost/v1.40/images/homeassistant/aarch64-hassio-supervisor:2021.03.6/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument").`

Your file system is corrupt. You need run `ha su repair`
