### ISSUE TITLE
Supervisor Cannot import configuration via USB drive

### ISSUE THREAD

**Issue by AI-Cube** [home-assistant/supervisor#2748]
### Describe the issue you are experiencing

Supervisor Cannot import configuration via USB drive。There is no problem under version 2011.02.11, but an error occurs under version 2011.03.1 After choosing"Import from USB", it will report "Filed to import from USB, Unknown error, see supervisor logs", but there is no output from logs.It should be that an error occurred in fronted and the service could not be called correctly。

### What is the used version of the Supervisor?

supervisor-2021.02.11/supervisor-2021.03.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.3.3

### Steps to reproduce the issue

1.
2.
3.

### Anything in the Supervisor logs that might be useful for us?

```txt
21-03-24 00:00:39 INFO (MainThread) [supervisor.api.security] /host/logs access from core_ssh
21-03-24 00:13:29 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD usb hardware /dev/bus/usb/001/003
```
ps.There is no information about import errors in the log。

I use the same USB drive  under version 2021.02.11 and it worked well.

**Comment by rsaffi** [comment]
Honest question: why was this closed?

I am myself facing this right now. I just moved my hass.io installation on my RPi4 from a MicroSD Card to a USB SSD (using the Argon ONE M.2) and everything went very smooth up until the point when I wanted to import my `authorized_keys` file via the procedure described [here](https://developers.home-assistant.io/docs/operating-system/debugging/#home-assistant-operating-system) (which I am familiar with from doing a few times before), but I keep getting the aforementioned `"Failed to import from USB, Unknown error, see supervisor logs"`.

This is probably related to the fact that my main OS is also now on the USB, and it's the first one recognized by the RPi (`sda`, whereas my flash drive is on `sdb`).
