### ISSUE TITLE
Parsing systemd service descriptions fails when (valid) single quote is in unit.description

### ISSUE THREAD

**Issue by yaleman** [home-assistant/supervisor#2760]
### Describe the issue you are experiencing

I'm attempting to update supervisor from supervisor-2021.03.4 to supervisor-2021.03.6 and it's throwing an error while trying to parse host system service information.

### What is the used version of the Supervisor?

supervisor-2021.03.4

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2021.3.3

### Steps to reproduce the issue

1. Have the Splunk Forwarder installed on the host system, or have a ' mark in a systemd service file in the description line (this is valid)
2. Browse to Supervisor -> System tab
3. Click update in the Supervisor block

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line
' - Expecting ',' delimiter: line 1 column 14455 (char 14454)
21-03-27 09:34:21 WARNING (MainThread) [supervisor.host.services] Can't update host service information
```

The line where it throws an error is this, at the misplaced quote just before `splunk enable boot-start`:
```
["SplunkForwarder.service", "Systemd service file for Splunk, generated by "splunk enable boot-start"", "loaded", "active", "running", "", "/org/freedesktop/systemd1/unit/SplunkForwarder_2eservice", 0, "", "/"]
```

It's erroring because `'splunk enable boot-start'` from the systemd unit file (which has single quotes) has been converted to double quotes at some point in Home Assistant's handling of things.

The relevant part of the original systemd unit file:
```
$ cat /etc/systemd/system/SplunkForwarder.service
[Unit]
Description=Systemd service file for Splunk, generated by 'splunk enable boot-start'
After=network.target

[Service]
Type=simple
Restart=always
<snip>
```

SImilar output from the command line:
```
$ systemctl status SplunkForwarder.service
* SplunkForwarder.service - Systemd service file for Splunk, generated by 'splunk enable boot-start'
   Loaded: loaded (/etc/systemd/system/SplunkForwarder.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-03-22 13:22:26 AEST; 5 days ago
```

**Comment by yaleman** [comment]
Issue is still occurring with 2021.04.03

**Comment by yaleman** [comment]
This is still a problem.

**Comment by ludeeus** [comment]
Hi there @yaleman :wave: 

Installing additional software on the host for supervised installations is not supported and this is not considered a bug with the supervisor.

<https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>
> No additional software, outside of the Home Assistant ecosystem, is installed.

I suggest you;
a) Remove it
b) Manually adjust the service file
