### ISSUE TITLE
HA fails to import ssh authorization

### ISSUE THREAD

**Issue by zolstarym** [home-assistant/supervisor#2761]
### The problem

When following the instructions at https://developers.home-assistant.io/docs/operating-system/debugging/
 for enabling ssh access, HA fails to import authorized_keys file from the usb drive. The drive is name CONFIG and is ext4

### What is version of Home Assistant Core has the issue?

core-2021.3.4

### What was the last working version of Home Assistant Core?

n/a

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
_No response_
```

### Anything in the logs that might be useful for us?

```txt
21-03-27 00:49:51 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD usb hardware /dev/bus/usb/001/005
Nothing else in the supervisor logs at the time the issue occurs.
```

**Comment by pvizeli** [comment]
That is fix on beta and next RL
