### ISSUE TITLE
Can't get the supported version

### ISSUE THREAD

**Issue by dogmads** [home-assistant/supervisor#2763]
### Describe the issue you are experiencing

Hello, I've been trying to get rid of running unsupported error message for a bit now. I asked in the home assistant community but no one seems to have an answer for it. 
I installed home assistant supervised following the guidelines in debian 10. 
I added the parts of code into the proper conf file to make network-manager manager but it doesn't seems to get rid of the problem.

This the code I put into 
/etc/NetworkManager/NetworkManager.conf:

[main]
dns=default
plugins=keyfile
autoconnect-retries-default=0
rc-manager=file

[keyfile]
unmanaged-devices=type:bridge;type:tun;type:veth

[logging]
backend=journal

and into 
/etc/NetworkManager/system-connections/default:

[connection]
id=Supervisor default
uuid=b653440a-544a-4e4f-aef5-6c443171c4f8
type=802-3-ethernet
llmnr=2
mdns=2

[ipv4]
method=auto

[ipv6]
addr-gen-mode=stable-privacy
method=auto

and into
/etc/network/interfaces:

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

### What is the used version of the Supervisor?

supervisor-2021.03.6

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2021.3.4

### Steps to reproduce the issue

1. Just starting home assistant you get it as not supported.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line
21-03-28 22:59:10 WARNING (MainThread) [supervisor.core] System running in a unsupported environment!
21-03-28 22:59:10 WARNING (MainThread) [supervisor.resolution.evaluations.base] NetworkManager is not correctly configured (more-info: https://www.home-assistant.io/more-info/unsupported/network_manager)
21-03-28 22:58:55 WARNING (MainThread) [supervisor.dbus.network] No Network Manager support on the host. Local network functions have been disabled.
21-03-28 22:59:00 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
```

I connected my raspberry pi4 with wifi using iwd, following some instructions to connect it to wifi but it wasn't working and ended up disabling and reenabling network-manager.

I tried restarting my raspberry with and without the ethernet cable connected but I get same result.

I configured wpa_supplicant at some point as well.

Other than that I can't think of anything else that may have affected the installation to not be supported.

Thanks in advance,
Francisco

**Comment by pvizeli** [comment]
According ADR, you are responsible for the OS and host system if you not use our OS

**Comment by dogmads** [comment]
Hey pvizeli, I did follow the instructions on home assistant website to install it as they say with Debian 10 and all that.
