### ISSUE TITLE
AM6548：<jemalloc>: Unsupported system page size

### ISSUE THREAD

**Issue by tiandeyu** [home-assistant/supervisor#2770]
### Describe the issue you are experiencing

Device: Siemens IOT2050
SOC: Texas Instruments ARM AM6548 A53
HA: Hassio
When I install hassio, start supervisor throw error like this:

<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
Fatal Python error: _PyRuntimeState_Init_impl: Can't initialize threads for interpreter
Python runtime state: unknown

### What is the used version of the Supervisor?

homeassistant/aarch64-hassio-supervisor:2021.03.6

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Linux iot2050-debian 4.19.59+ #1 SMP PREEMPT Wed May 13 05:10:10 UTC 2020 aarch64 GNU/Linux

### What version of Home Assistant Core is installed?

homeassistant/qemuarm-64-homeassistant:2021.3.4

### Steps to reproduce the issue

1. install hassio
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[09:10:30] INFO: Using udev information from host
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:10:31] INFO: Starting local supervisor watchdog...
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
Fatal Python error: _PyRuntimeState_Init_impl: Can't initialize threads for interpreter
Python runtime state: unknown

[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.


```

**Comment by pvizeli** [comment]
Unsupported

**Comment by tiandeyu** [comment]
Hi, @pvizeli 
I was able to run supervisor by comment export LD_PRELOAD="/usr/local/lib/libjemalloc.so.2" in /etc/services.d/supervisor/run
Is there a way to disable jemalloc like homeassistant core: https://www.home-assistant.io/installation/raspberrypi/#optimizations by add a environment variable
