### ISSUE TITLE
Automatic updates cannot be disabled and break integrations

### ISSUE THREAD

**Issue by benjaminlecouteux** [home-assistant/supervisor#2771]
### Describe the issue you are experiencing

Regularly, automatic updates break some integrations. This is problematic because homeassistant can handle critical systems. The update should be done manually.

### What is the used version of the Supervisor?

supervisor-2021.03.9

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.3.4

### Steps to reproduce the issue

1. The update of the supervisor breaks the velux integration for example.

### Anything in the Supervisor logs that might be useful for us?

no

**Comment by pvizeli** [comment]
Feature request to forum
