### ISSUE TITLE
Issue for github repository

### ISSUE THREAD

**Issue by AI-Cube** [home-assistant/supervisor#2778]
### Describe the issue you are experiencing

Clone the repository under windows, you will get an error。
$ git clone https://github.com/home-assistant/supervisor.git
Cloning into 'supervisor'...
remote: Enumerating objects: 219, done.
remote: Counting objects: 100% (219/219), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 20156 (delta 95), reused 111 (delta 51), pack-reused 19937
Receiving objects: 100% (20156/20156), 80.93 MiB | 5.27 MiB/s, done.
Resolving deltas: 100% (13581/13581), done.
error: invalid path 'tests/fixtures/org_freedesktop_NetworkManager_AccessPoint_*.xml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### What is the used version of the Supervisor?

supervisor-2021.03.9

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-1

### Steps to reproduce the issue

1.1
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line

```

**Comment by pvizeli** [comment]
Please open an bug on git
