### ISSUE TITLE
Addon could access nrf24l01 chip

### ISSUE THREAD

**Issue by tomcatGu** [home-assistant/supervisor#2794]
### Describe the issue you are experiencing

I connect a nrf24l01 chip to raspberryPi which has installed hassio.I wrote an addon for using nrf24l01 that works well after turning on "full_access" and disabling protection mode.Recently the addon couldn't work after update HA to latest version.
I observed that the program is unresponsive at writing data to the register of the nrf24l01 chip.How could I resolve this?

### What is the used version of the Supervisor?

supervisor-2021.03.9

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Raspbian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2021.4.1

### Steps to reproduce the issue

config.json:
{
  "name": "nRF24Mesh",
  "version": "0.1.16",
  "slug": "nrf24mesh",
  "description": "nrf24l01+ Mesh add-on!",
  "startup": "application",
  "arch": [ "armhf" ],
  "boot": "auto",
  "options": {
...
  },
  "schema": {
...
  },
  "full_access": true,
  "apparmor": false,
  "kernel_modules":  true,
  "privileged": ["NET_ADMIN","SYS_ADMIN","SYS_RAWIO","SYS_TIME","SYS_NICE","SYS_RESOURCE","SYS_PTRACE","SYS_MODULE","DAC_READ_SEARCH"]
  
}

### Anything in the Supervisor logs that might be useful for us?

my debug log:

Starting nrf24l01+ newwork...!
<RF24.RF24 object at 0x766e3690>
write_register(00,0c)

**Comment by ludeeus** [comment]
Map the specific device with the `devices` option, or use full access with protection disabled.

https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
