### ISSUE TITLE
Unable to edit Add-On Config in fresh VM install

### ISSUE THREAD

**Issue by feueru** [home-assistant/supervisor#2822]
**Hardware Environment**

ESXi 7.0.1

**Home Assistant OS release:**
https://github.com/home-assistant/operating-system/releases/download/5.13/hassos_ova-5.13.ova

**Description of problem:**

1. Create a new VM using default settings in ESXi 7.0.1 using https://github.com/home-assistant/operating-system/releases/download/5.13/hassos_ova-5.13.ova, with all default settings
2. When VM starts complete initial setup and install an Add On such as Duck DNS
3. Edit Add On Configuration in yaml mode using the supervisor frontend web ui on any web browser of your choosing
4. When configuration is saved, it reverts to default settings

I've  been able to re-create this multiple times with mutable Add Ons with multiple fresh VMs 
but some Add Ons work as expected such as Terminal & SSH

**Comment by ludeeus** [comment]
For DuckDNS token and domains needs to be filled out, for zwavejs, you need to add network_key, when all required options are added, you should be able to save.
