### ISSUE TITLE
reboot raspberry pi home assistant

### ISSUE THREAD

**Issue by foxroman** [home-assistant/supervisor#2824]
### Describe the issue you are experiencing

Constant reboot of the program. This can be 10-15 times a day.
At the same time, the raspberry itself works stably

### What is the used version of the Supervisor?

supervisor-2021.04.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Raspbian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2021.4.4

### Steps to reproduce the issue

Automatic system reboot

### Anything in the Supervisor logs that might be useful for us?

21-04-19 05:06:26 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-04-19 05:07:57 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-04-19 05:17:13 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-04-19 05:25:33 INFO (MainThread) [supervisor.host.info] Updating local host information
21-04-19 05:25:34 INFO (MainThread) [supervisor.host.services] Updating service information
21-04-19 05:25:34 INFO (MainThread) [supervisor.host.network] Updating local network information
21-04-19 05:25:37 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-04-19 05:25:37 INFO (MainThread) [supervisor.host] Host information reload completed
21-04-19 05:47:14 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-04-19 06:02:23 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-04-19 06:06:26 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-04-19 06:06:26 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-04-19 06:06:26 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-04-19 06:06:26 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-04-19 06:06:26 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-04-19 06:06:26 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-04-19 06:06:26 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-04-19 06:17:16 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-04-19 06:45:44 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-04-19 06:45:44 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-04-19 06:48:37 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-04-19 07:02:25 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-04-19 07:06:26 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-04-19 07:06:26 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-04-19 07:06:26 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-04-19 07:06:26 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-04-19 07:06:26 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-04-19 07:06:26 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-04-19 07:06:26 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-04-19 07:07:39 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
21-04-19 07:07:57 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-04-19 07:10:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-04-19 07:10:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/yllibed/hassio repository
21-04-19 07:10:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
21-04-19 07:10:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/danielwelch/hassio-zigbee2mqtt repository
21-04-19 07:10:23 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-04-19 07:10:26 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
21-04-19 07:10:26 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
21-04-19 07:18:39 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-04-19 07:32:18 INFO (MainThread) [supervisor.host.info] Updating local host information
21-04-19 07:32:18 INFO (MainThread) [supervisor.host.services] Updating service information
21-04-19 07:32:18 INFO (MainThread) [supervisor.host.network] Updating local network information
21-04-19 07:32:22 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-04-19 07:32:22 INFO (MainThread) [supervisor.host] Host information reload completed
21-04-19 07:48:41 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-04-19 08:02:26 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-04-19 08:06:26 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-04-19 08:06:26 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-04-19 08:06:26 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-04-19 08:06:26 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-04-19 08:06:26 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-04-19 08:06:26 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-04-19 08:06:26 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-04-19 08:06:26 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-04-19 08:18:42 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-04-19 08:26:32 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-04-19 08:26:32 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete

**Comment by ludeeus** [comment]
Running a Supervised installation on Raspbian is not supported <https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>.

If you need help with troubleshooting your installation, try seeking help on the [forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e) :+1:
