### ISSUE TITLE
Supervisor Host card won't update new disk size

### ISSUE THREAD

**Issue by TheGabeMan** [home-assistant/supervisor#2833]
### Describe the issue you are experiencing

After getting a warning that my HA was almost out of space, I shutdown the VM, resized the disk from 20GB to 32GB and powered on the VM again. Checking the supervisor -> system -> HOST card, the progress bar was still showing 90% disk usage. And when hovering over the 90% indicator, it still says "17.1/19GB".

However, when I login to the HA VM, fdisk tells me /dev/sda is now 32GB and df -h shows  /dev/sda8 31GB with 17GB usage. So it seems only the card is not updated.

### What is the used version of the Supervisor?

supervisor-2021.04.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.13

### What version of Home Assistant Core is installed?

core-2021.4.3

### Steps to reproduce the issue

1. receive message about less than 1GB free disk space
2. supervisor - system - shutdown host
3. vmware - VM - resize disk 20GB to 32GB
4. poweron VM
5. check supervisor - system - host card. Still old value.
6. Reboot again to see if reboot changes anything, it doesn't.

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line

```

**Comment by ludeeus** [comment]
What does `ha host info` tell you about the size?

**Comment by TheGabeMan** [comment]
> What does `ha host info` tell you about the size?

disk_free = 12.1
disk_life_time = null
disk_total = 30.8
disk_used = 17.3

**Comment by ludeeus** [comment]
That's the same API as the frontend uses, try clearing your browser cache.

**Comment by TheGabeMan** [comment]
Well, that is embarrassing.... clearing cache did it. Sorry about this. Can we delete this whole thread? ;-)
