### ISSUE TITLE
Restart of HomeAssistant via the WebUI not possible

### ISSUE THREAD

**Issue by Baggerfahrer** [home-assistant/supervisor#2889]
### Describe the issue you are experiencing

Hi!

Whenever i want to restart the HomeAssistant instance via Settings-> ServerControl -> Restart 
![image](https://user-images.githubusercontent.com/25987294/118348351-ebe7a900-b549-11eb-94ba-49958d4b6fc6.png)

i get the following error message from the logs:
`2021-05-15 06:48:04 ERROR (MainThread) [homeassistant.components.hassio] Component error: resources - Integration 'resources' not found.`

After a full restart of HomeAssistant Supervisor i see the following entries in the logs:
`2021-05-15 06:58:40 ERROR (MainThread) [homeassistant.setup] Setup failed for resources: Integration not found.`

Nothing happens afterwards, meaning a restart is not performed.

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 5.13

### What version of Home Assistant Core is installed?

core-2021.5.4

### Steps to reproduce the issue

No more steps needed to reproduce the issue. See above for explanation.

### Anything in the Supervisor logs that might be useful for us?

```txt
2021-05-15 06:48:04 ERROR (MainThread) [homeassistant.components.hassio] Component error: resources - Integration 'resources' not found.
```

**Comment by ludeeus** [comment]
This is fully expected, `resources` is not an integration, but a configuration key for the `frontend` integration.

**Comment by Baggerfahrer** [comment]
Hi @ludeeus 

thanks for your reply!

Then this error log is not relevant for this issue.

But the issue still exists, meaning i can not restart HomeAssistant via the button "restart".
Any hints where the issue can come from in this case?

**Comment by ludeeus** [comment]
That is not an issue, it check the config.
If that check failed, it does not restart
