### ISSUE TITLE
Piface inputs don't work

### ISSUE THREAD

**Issue by roland1970** [home-assistant/supervisor#2898]
### Describe the issue you are experiencing

The inputs from the piface don't work correctly.
If I push the button then I can't see the state of the input.
If I push the button and I restart HA the I see the state is changed , If I release the button the state stay's the same.

### What is the used version of the Supervisor?

2021.04.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Docker 20.10.6

### What version of Home Assistant Core is installed?

5-4

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
There are no errors in the log
```

**Comment by pvizeli** [comment]
Missing information. Please report next time the output of `ha info`
