### ISSUE TITLE
supervisor-2021.04.3 [asyncio] Task exception was never retrieved scheduler.py

### ISSUE THREAD

**Issue by shirou93** [home-assistant/supervisor#2906]
### Describe the issue you are experiencing

Error in logs `21-05-20 06:15:25 ERROR (MainThread) [asyncio] Task exception was never retrieved`

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian 10

### What version of Home Assistant Core is installed?

core-2021.5.5

### Steps to reproduce the issue

1. Check logs on supervisor-2021.04.3 in HA Core core-2021.5.5
2. Logs should be appeared also after reboot host.

### Anything in the Supervisor logs that might be useful for us?

```txt
`21-05-20 06:15:25 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1291' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)`
```

**Comment by wernerhp** [comment]
Same for me.
core-2021.5.5
supervisor-2021.04.3
Home Assistant OS 5.13

```
future: <Task finished name='Task-2015292' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
```

**Comment by ludeeus** [comment]
Fixed in https://github.com/home-assistant/supervisor/pull/2903

**Comment by tylersprice84** [comment]
I implemented the 'fix' and still get the same errors, doesnt matter if i even remove the type hinting it still errors out.

What can a person do? It seems to affect my CPU usage as soonas HA starts throwomg these errors the CPU usage spikes and keeps climbing tio 100%

**Comment by sotavov** [comment]
мне помогло:

```
docker exec -it hassio_supervisor /bin/bash
bash-5.1# find /  -name "addon.py"
/usr/src/supervisor/supervisor/docker/addon.py
/usr/src/supervisor/supervisor/store/addon.py
/usr/src/supervisor/supervisor/addons/addon.py
bash-5.1# vi /usr/src/supervisor/supervisor/addons/addon.py
```

jumping to line 456

changing it to a string (adding int and parentheses)
Was
`t_port = application.group("t_port") `
became
`t_port = int(application.group("t_port")) 
`
supervisor restart and no more error
there is a warning

`21-05-28 11:40:52 WARNING (MainThread) [supervisor.resolution.evaluations.base] System detect unauthorized source code modifications. (more-info: https://www.home-assistant.io/more-info/unsupported/source_mods)`

**Comment by ripp2003** [comment]
Got same problem : each file in container were changed but, even after completely restart, errors always appear....

**Comment by Salvora** [comment]
I am just curious. I am suffering from the same problem with Home Assistant OS 5.13, supervisor-2021.04.3, and core-2021.5.5. The latest version for supervisor on github is 2021.05.4. But the update notification doesn't show up on my hassos. Is something wrong with my setup or this is normal?

**Comment by ludeeus** [comment]
Completly normal <https://version.home-assistant.io/stable.json>
Newer versions of the Supervisor has currently only been pushed to dev/beta
