### ISSUE TITLE
не работает Bridge интерфейс

### ISSUE THREAD

**Issue by dixanl** [home-assistant/supervisor#2917]
### Describe the issue you are experiencing

через Network Manager настроен brige0 с 3  eth  все работает 
после установки через скрипт  curl -Lo installer.sh https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh

все ставится и работает до перезагрузки!!
после перезагрузки не поднимается brige0 если его снести и настроить eth то работает!

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

10.9

### What version of Home Assistant Core is installed?

core-2021.5.5

### Steps to reproduce the issue

1.curl -Lo installer.sh https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh
2.reboot
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
нет
```

**Comment by frenck** [comment]
English only. Thanks 👍
