### ISSUE TITLE
Bridge interface does not work

### ISSUE THREAD

**Issue by dixanl** [home-assistant/supervisor#2919]
### Describe the issue you are experiencing

via Network Manager brige0 is configured with 3 eth everything works
after installation via curl -Lo installer.sh script https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh

everything is installed and works until reboot !!
after reboot, brige0 does not rise if you demolish it and configure eth then it works!

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

10.9

### What version of Home Assistant Core is installed?

core-2021.5.5

### Steps to reproduce the issue

1.curl -Lo installer.sh https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh
2.reboot

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

**Comment by dixanl** [comment]
мая 28 14:50:13 debian d425f993bb4c[590]: Traceback (most recent call last):
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
мая 28 14:50:13 debian d425f993bb4c[590]:     resp = await self._request_handler(request)
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle
мая 28 14:50:13 debian d425f993bb4c[590]:     reraise(*_capture_exception(hub))
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
мая 28 14:50:13 debian d425f993bb4c[590]:     raise value
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle
мая 28 14:50:13 debian d425f993bb4c[590]:     response = await old_handle(self, request)
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
мая 28 14:50:13 debian d425f993bb4c[590]:     resp = await handler(request)
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
мая 28 14:50:13 debian d425f993bb4c[590]:     return await handler(request)
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/src/supervisor/supervisor/api/security.py", line 135, in system_validation
мая 28 14:50:13 debian d425f993bb4c[590]:     return await handler(request)
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/src/supervisor/supervisor/api/security.py", line 197, in token_validation
мая 28 14:50:13 debian d425f993bb4c[590]:     return await handler(request)
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/src/supervisor/supervisor/api/utils.py", line 65, in wrap_api
мая 28 14:50:13 debian d425f993bb4c[590]:     answer = await method(api, *args, **kwargs)
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/src/supervisor/supervisor/api/network.py", line 166, in info
мая 28 14:50:13 debian d425f993bb4c[590]:     for interface in self.sys_host.network.interfaces
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/src/supervisor/supervisor/host/network.py", line 65, in interfaces
мая 28 14:50:13 debian d425f993bb4c[590]:     interfaces.append(Interface.from_dbus_interface(inet))
мая 28 14:50:13 debian d425f993bb4c[590]:   File "/usr/src/supervisor/supervisor/host/network.py", line 292, in from_dbus_interface
мая 28 14:50:13 debian d425f993bb4c[590]:     Interface._map_nm_method(inet.settings.ipv4.method),
мая 28 14:50:13 debian d425f993bb4c[590]: AttributeError: 'NoneType' object has no attribute 'method'
мая 28 14:50:13 debian 55e02be4a310[590]: 2021-05-28 14:50:13 ERROR (MainThread) [homeassistant.components.hassio.handler] /network/info return code 500
мая 28 14:50:13 debian 55e02be4a310[590]: 2021-05-28 14:50:13 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /network/info -
мая 28 14:50:15 debian d425f993bb4c[590]: 21-05-28 09:50:15 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
мая 28 14:50:15 debian d425f993bb4c[590]: 21-05-28 09:50:15 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 1 add-ons

**Comment by dixanl** [comment]
but if you write in the / etc / network interface
allow-hotplug eth0
iface eth0 inet dhcp
debian receives a second address and the supervisor works fine

**Comment by pvizeli** [comment]
Right, we don't support a bridge interface. This is a feature request which needs to go into the forum. This is for bug tracking only
