### ISSUE TITLE
Cannot restart supervisor

### ISSUE THREAD

**Issue by dedepene** [home-assistant/supervisor#2927]
### Describe the issue you are experiencing

When I hit the "restart supervisor" from the HA GUI I get an error and nothing happens:

`'Supervisor.restart' blocked from execution, system is not running - CoreState.FREEZE`

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2021.5.5

### Steps to reproduce the issue

1. Go to Supervisor
2. Slect system tab
3. restart supervisor
...

### Anything in the Supervisor logs that might be useful for us?

```txt
I'm not sure where this comes from:

21-06-01 09:14:54 WARNING (MainThread) [supervisor.auth] Unauthorized login for 'xxxuserxxx'
```

**Comment by ludeeus** [comment]
This is the expected behavior, many operations (including restart) are blocked while the system is not running.
The FREEZE state means that it's creating/restoring a snapshot, or already in a restart sequence.

Give it some time and it will allow restarting.
