### ISSUE TITLE
404 client error when openening armv7-hassio-supervisor:2021.05.4

### ISSUE THREAD

**Issue by JBerg60** [home-assistant/supervisor#2932]
### Describe the issue you are experiencing

Updating to armv7-hassio-supervisor:2021.05.4 fails with a 404 http error

### What is the used version of the Supervisor?

supervisor-2021.04.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Raspbian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2021.5.5

### Steps to reproduce the issue

Tried updating via the Supervisor in HA, and manual cli update with same error

### Anything in the Supervisor logs that might be useful for us?

```txt
21-06-03 09:22:35 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image homeassistant/armv7-hassio-supervisor with tag 2021.05.4.
21-06-03 09:22:43 ERROR (SyncWorker_4) [supervisor.docker.interface] Can't install homeassistant/armv7-hassio-supervisor:2021.05.4 -> 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/armv7-hassio-supervisor:2021.05.4/json: Not Found ("no such image: homeassistant/armv7-hassio-supervisor:2021.05.4: No such image: homeassistant/armv7-hassio-supervisor:2021.05.4").
21-06-03 09:22:43 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed:
root@r2d2:/usr/share/hassio/homeassistant#
```

**Comment by ludeeus** [comment]
Raspbian is not a supported OS for a supervised installation. https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md

https://www.home-assistant.io/faq#404-client-error-not-found-no-such-image-homeassistant Might help, if not try asking 
on the [forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e)
