### ISSUE TITLE
image homeassistant/odroid-c2-homeassistant:landingpage failed on content-trust verification

### ISSUE THREAD

**Issue by adeepn** [home-assistant/supervisor#2938]
### Describe the issue you are experiencing

First install on device via supervised script gives:

Pulled image homeassistant/odroid-c2-homeassistant:landingpage failed on content-trust verification!

Seems, that all images on docker hub updated today, but this images last pushed 3 months ago.

### What is the used version of the Supervisor?

latest

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

none

### What version of Home Assistant Core is installed?

none

### Steps to reproduce the issue

1. run supervied install script
2. see journalctl
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Jun 07 14:45:06 jethub-j80 hassio-supervisor[3488]: 21-06-07 11:45:06 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image homeassistant/odroid-c2-homeassistant with tag landingpage.
Jun 07 14:45:06 jethub-j80 68ff466d8ddd[2749]: 21-06-07 11:45:06 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image homeassistant/odroid-c2-homeassistant with tag landingpage.
Jun 07 14:45:31 jethub-j80 hassio-supervisor[3488]: 21-06-07 11:45:31 CRITICAL (SyncWorker_1) [supervisor.docker.interface] Pulled image homeassistant/odroid-c2-homeassistant:landingpage failed on content-trust verification!
Jun 07 14:45:31 jethub-j80 68ff466d8ddd[2749]: 21-06-07 11:45:31 CRITICAL (SyncWorker_1) [supervisor.docker.interface] Pulled image homeassistant/odroid-c2-homeassistant:landingpage failed on content-trust verification!
Jun 07 14:45:31 jethub-j80 68ff466d8ddd[2749]: 21-06-07 11:45:31 WARNING (MainThread) [supervisor.homeassistant.core] Fails install landingpage, retry after 30sec
```

### Additional information

root# docker pull homeassistant/odroid-c2-homeassistant:landingpage
Error: remote trust data does not exist for docker.io/homeassistant/odroid-c2-homeassistant: notary.docker.io does not have trust data for docker.io/homeassistant/odroid-c2-homeassistant
root# export DOCKER_CONTENT_TRUST=0
root# docker pull homeassistant/odroid-c2-homeassistant:landingpage
landingpage: Pulling from homeassistant/odroid-c2-homeassistant
2914792bc417: Pull complete 
358a8046aca8: Pull complete 
9fe356f779cd: Pull complete 
19e91d2c6384: Pull complete 
913ee2987739: Pull complete 
528c4f1beac5: Pull complete 
Digest: sha256:0aa16fe93a5a113f073ef2bdb9d82f12d477a23f5841804328da6bd851473392
Status: Downloaded newer image for homeassistant/odroid-c2-homeassistant:landingpage
docker.io/homeassistant/odroid-c2-homeassistant:landingpage

**Comment by pvizeli** [comment]
solved
