### ISSUE TITLE
Large file uploads via ingress fail with "Maximum request body size 16777216 exceeded"

### ISSUE THREAD

**Issue by jens-maus** [home-assistant/supervisor#2950]
### Describe the issue you are experiencing

First of all: I am sorry if this might be the wrong HA repository for this bug report as I am not sure if this is an issue in the supervisor or frontend, but I am trying to file it here first.

As said in the subject of this issue, large file uploads of files > 16MB are currently not possible if they are routed via ingress. In fact, third party add-ons like [RaspberryMatic](https://github.com/jens-maus/RaspberryMatic/) or OctoPrint, etc. already faced this issue because their web interfaces have file upload capabilities to allow to upload files (e.g. backups, data, etc.), but as soon as their web interfaces are accessed via ingress these requests fail with common `413 Request Entity is too large` responses to their POST requests.

See here:
https://github.com/jens-maus/RaspberryMatic/issues/1294
https://community.home-assistant.io/t/repository-octoprint/22883/101

As soon as the web server of these addons are directly accessed outside the common home assistant web interface (e.g. by using direct port mapping in the add-on settings), thus without ingress routing these requests, file upload succeed correctly for file sizes > 16MB.

However, it still is highly desirable to allow for POST requests (e.g. file uploads) via ingress to succeed even for sizes > 16MB. E.g., for the RaspberryMatic addon users have to upload backup data which could easily succeed sizes > 500MB, thus would prevent any ingress use. 

### What is the used version of the Supervisor?

supervisor-2021.05.4

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.0

### What version of Home Assistant Core is installed?

core-2021.6.3

### Steps to reproduce the issue

1. Install one of the third-party HA add-ons (RaspberryMatic, OctoPrint)
2. Use their file upload capabilities to try to upload files > 16MB in size
3. Note that POST requests with sizes > 16Mb fail with a `413 Request Entity is too large` request status
4. Note that the response of the request is cancelled with a `Maximum request body size 16777216 exceeded, actual body size 16778032` message by ingress.

### Anything in the Supervisor logs that might be useful for us?

```txt
no error/warnings logged upon the error event.
```

**Comment by jens-maus** [comment]
Ok, after some more research on that matter I found the following PR by @pvizeli which at that time already bumped the max size from 1 MB to 16MB:

cf. https://github.com/home-assistant/supervisor/pull/1423

However, as outlined above, even 16MB is not really enough for lengthy file uploads like consistent backups that the logic of an add-on might require. I would therefore like to propose to even further increase it to something like 16GB to cover all large file upload cases which shouldn't be an issue if performed from a local network connection.

**Comment by pvizeli** [comment]
We can just use somethings like this on ingress: https://github.com/home-assistant/core/blob/dev/homeassistant/components/hassio/http.py#L91

However, my task list is completely full for this year. maybe @ludeeus will look into that.

**Comment by gstrauss** [comment]
>>   further increase it to something like 16GB to cover all large file

> The issue with that is, it need also so much memory. Not all requests can be streamed.

lighttpd buffers large request bodies to disk, so that should not be an issue with lighttpd.  lighttpd can also be configured to stream the request body to a backend, with minimal buffering to disk (to clear kernel recv socket buffers): `server.stream-request-body = 2`.  lighttpd can be configured with `server.max-request-size` (in kb) to have lighttpd enforce a limit on request size.

Is the hassio/http.py python script in front of lighttpd or behind lighttpd?  lighttpd is more powerful when lighttpd is in front of less resource-friendly applications.

**Comment by ludeeus** [comment]
We use aiohttp

**Comment by jens-maus** [comment]
@gstrauss 
> Is the hassio/http.py python script in front of lighttpd or behind lighttpd? lighttpd is more powerful when lighttpd is in front of less resource-friendly applications.

AFAIK lighttpd is not used at all in HomeAssistant directly. However, it is used by the RaspberryMatic HA add-on I am maintaining (https://github.com/jens-maus/RaspberryMatic). Thus, it is used behind the python http stuff. And in fact, within this addon we are already using sufficient lighttpd options to provide enough room for large file uploads. Thus, lighttpd is not the issue here, it is the pytjon http that is currently setup to be limited in max request body size too much.

**Comment by jens-maus** [comment]
> We can just use something like this on ingress: https://github.com/home-assistant/core/blob/dev/homeassistant/components/hassio/http.py#L91

That would mean 1GB of max. request body size (`MAX_UPLOAD_SIZE = 1024 * 1024 * 1024`) right? That would be at least better than the currently limited 16MB. However, as said before, I would propose to make it 16GB or as a compromise 4GB max, which almost all modern hardware should perfectly serve these days.

> However, my task list is completely full for this year. maybe @ludeeus will look into that.

I can also perfectly provide a PR based on your previous PR on that matter, if that would help.

> > further increase it to something like 16GB to cover all large file
> 
> The issue with that is, it need also so much memory. Not all requests can be streamed.

Is it really that aiohttp would completly cache the request in RAM? For example, lighttpd (as said by @gstrauss) can also buffer to disk. Something like that should be possible with aiohttp as well, isn't it?

**Comment by pvizeli** [comment]
Not all requests are chunked. Browser sending the hole file mostly once which kills nice HTTP features that allow to stream content without need fill buffers or using the local disk. We try to ignore that on the first entry and using chunks for future processing, however, on the entry point it gets almost into memory

**Comment by pvizeli** [comment]
The only solution is https://github.com/home-assistant/core/blob/dev/homeassistant/components/hassio/http.py#L91 - we can not make HA support more than 16MB and this solution would be unlimited files for ingress

**Comment by jens-maus** [comment]
> The only solution is https://github.com/home-assistant/core/blob/dev/homeassistant/components/hassio/http.py#L91 - we can not make HA support more than 16MB and this solution would be unlimited files for ingress. But means it need an PR on core and a PR on the supervisor.

Sorry, can't follow your thoughts?!? In that file (http.py) the `MAX_UPLOAD_SIZE` is already set to 1GB (https://github.com/home-assistant/core/blob/dev/homeassistant/components/hassio/http.py#L23). so what would be the actual solution you have in mind so that add-ons can upload more data than currently 16MB?

**Comment by jens-maus** [comment]
@pvizeli
Sorry to bother you once more. I looked at your suggested link and tried to think about what you possibly meant. So you mean one has to add a similar block like https://github.com/home-assistant/core/blob/dev/homeassistant/components/hassio/http.py#L84-L94 to http.py (in an else if block underneath?) but then catch for a `path == '/api/hassio_ingress/'`, right? And then set `request._client_max_size` to something like 2-3 GB in max size instead of raising the limit in `hassio/api/__init__.py` like you did before in your previous PR?

If that's what you meant I could try to prepare a PR on that. If not, please advice.

**Comment by ludeeus** [comment]
On the core side, it's 1GB only for snapshot uploads, which has to be extended to include POST to ingress as well.
And the same logic needs to be implemented in the ingress handler on the supervisor side (with a maximum of 1GB)

**Comment by jens-maus** [comment]
Understood. However I probably have less insight into the whole dependencies here. So would you (@ludeeus) do this or you link me to the supervisor sources and I could try it as well

**Comment by ludeeus** [comment]
https://github.com/home-assistant/supervisor/blob/main/supervisor/api/ingress.py#L160

**Comment by jens-maus** [comment]
Thanks @ludeeus and @pvizeli for having implemented this yourself. While I was already slowly at the task myself in trying to implement it similar like you did, I am quite happy that you finally did it now yourself because this is certainly a more consistent and faster implementation. So in which supervisor/core version release is this planned to be integrated so that I can test it accordingly?

**Comment by ludeeus** [comment]
core-2021.7.0, su-2021.06.7

**Comment by jens-maus** [comment]
Thanks @ludeeus for clarification. I actually looked at your final PRs to supervisor+core and wondered a bit because I cannot spot any increased request max size there?!? Does the removed timeout alone mean there is no request limit anymore?

**Comment by ludeeus** [comment]
not needed <https://twitter.com/ludeeus/status/1408482177600397318>

**Comment by jens-maus** [comment]
Thanks again! This is an awesome improvement and very welcome for ingress routed webuis of addons like the RaspberryMatic Addon is using.

**Comment by jens-maus** [comment]
Sorry @ludeeus and @pvizeli to bothering you once again with this ticket, but I just updated to core-2021.7.0 and also having su-2021.06.8 installed and my add-on still raises the same `Request Entity Too Large`, i.e. `Maximum request body size 16777216 exceeded` message when trying to upload more than 16MB of data via its ingress routed WebUI. See here:

![Bildschirmfoto 2021-07-08 um 08 35 57](https://user-images.githubusercontent.com/5887769/124874046-86eb8500-dfc7-11eb-8518-e255a4382767.png)

So to me this looks like large file uploads (>16MB) still don't work as expected. So did I miss something here or is there something my add-on has to do different now to allow such large file uploads via ingress?

**Comment by jens-maus** [comment]
BTW: I just recognized that the following error is logged in the Supervisor log output when trying to upload > 16MB of data:

```
21-07-08 08:39:47 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid character in chunk size header'
```

Perhaps this helps already to get this issue finally fixed.

**Comment by ludeeus** [comment]
We had to revert that because it broke the File Editor add-on.
We added a `ìngress_streaming` key to the add-on configuration to enable this, so set that to `True` in add-ons that needs large payloads.

**Comment by jens-maus** [comment]
@ludeeus Thanks for the hint. However, after adding `ingress_stream: true` to my add-on config I think I run into the same/similar issues like the file editor add-on:

![Bildschirmfoto 2021-07-08 um 09 33 36](https://user-images.githubusercontent.com/5887769/124882157-63790800-dfd0-11eb-9c11-15ed1f2966aa.png)

So with `ingress_stream` set to true I can't even access the very basic things within the WebUI of my addon because of these `411 Length Required` error messages and the fact that the WebUI havily relies on general use of POST requests. Any idea where this comes from and how to solve it or how to get large file uploads >16MB still going even without using this config option?

**Comment by ludeeus** [comment]
That would not be possible, to allow that you need to be streaming requests (with ingress_stream).
But that needs the webserver to be able to receive those requests.
In most cases, adding an NGINX proxy in front of the webserver inside the add-on will help, NGINX does support streaming.

**Comment by jens-maus** [comment]
Well, this really complicates this whole matter IMHO. Within the addon I already have `lighttpd` as a quite capable webserver running in there and I really don't want to add another one (nginx) in front of it just for get this ingress proxying handled correctly for large file uploads. IMHO that's an unnecessary additional layer I would have to add. Sorry, to bother you once more, but I really currently don't (technically) know which options I would have to tune in lighttpd to correctly process these new `ingress_stream` requests correctly which you just added. In the beginning I thought all this would have been handles completly transparent for an addon.

And honestly. I really still don't get why you can't simply increase the maximum 16MB limit without the ingress_stream option to something more sensible like 1GB or so?!? Why is this not possible?

**Comment by ludeeus** [comment]
I don't know `lighttpd`, but you might be able to tune that one to accept chunked/streaming requests. 
We tried 1GB as well, but that was not good enough and had a negative impact on resource usage, with stream, there are no limits, and no impact on resource usage.

**Comment by jens-maus** [comment]
> I don't know `lighttpd`, but you might be able to tune that one to accept chunked/streaming requests.

Well, the problem with this approach would then probably be, that while I could probably tune the `lighttpd` settings for chunked/streaming requests this would possibly break the non-ingress webservice the addon also usually serves for theirs users. E.g. we still allow to access the webserver via port 8080 and then it would probably only accept these chunked/streaming requests.

> We tried 1GB as well, but that was not good enough and had a negative impact on resource usage, with stream, there are no limits, and no impact on resource usage.

What exactly was "not good enough" and what where the negative impact on resource usage in a general case without any large file uploads? I can understand that it might be more efficient to accept/use streamed requests. But as you can see here, there are bordercases where it is not immediately possible to use chunked/streaming requests and that there it would still be desireable for an addon to be able to receive POST requests/uploads larger than 16MB in the traditional, even thought it might take longer or might temporarily use more resources.

**Comment by jens-maus** [comment]
Ok, after fiddling around I think I have found a conditional lighttpd config statements which will allow to use the new `ingress_stream` addon config option (cf. https://redmine.lighttpd.net/issues/2156):

```
$REQUEST_HEADER["Content-Length"] == "" { server.stream-request-body = 0 }
```

Nevertheless, I still believe it would be great/desirable to also allow to perform larger POST/PUT requests without the new `ingress_stream` option.

**Comment by pvizeli** [comment]
That will be not possible. If you want to transfer 1GB over 3 hops, you need 3GB memory. The chunked stream is the solution from HTTP consortium which solve such issues, but not all webserver have implemented that feature well which is of the curse, not our issue. I think also homematic would be improved to use a better HTTP server like the light way Nginx as the old httplightd

**Comment by jens-maus** [comment]
> That will be not possible. If you want to transfer 1GB over 3 hops, you need 3GB memory.

I understand, but would it not be possible to cache these things to disk? That's exactly what lighttpd is supporting internally. So uploading something will be cached by lighttpd to temporary files internally, thus does not require that much memory.

> I think also homematic would be improved to use a better HTTP server like the fast/simple/low-resouce Nginx as the old Lighttpd

Well, I am of course also a fan of nginx in principle, but lighttpd is not that bad and it is IMHO more lightweight than nginx. But more problematic is, that there are specific lighttpd modules which were developed for authentication which would have to be ported over to nginx first. And then the whole internal proxying would have to be first ported. So this won't be anything that can be quickly changed, I am afraid. However, with the above mentioned lighttpd option the ingress_stream option seems to work now. Nevertheless, I still wonder why there is no file-based caching mechanisms in aiohttp for large POST/PUT requests like this is done by lighttpd.

**Comment by gstrauss** [comment]
> I think also homematic would be improved to use a better HTTP server like the fast/simple/low-resouce Nginx as the old Lighttpd
@pvizeli I don't think you know what you're talking about here, or at the very least you have not provided any data to support your gross misstatements.  @jens-maus has already stated further above that lighttpd is uninvolved in the limitations being discussed in this issue.

lighttpd supports HTTP/1.1 chunked encoding for request body from client as well as for response body from backends.  lighttpd also allows you to control streaming.
[server.stream-request-body](https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_stream-request-bodyDetails)
[server.stream-response-body](https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_stream-response-bodyDetails)

In general, lighttpd has a smaller memory footprint than nginx, and is as fast or faster than nginx in many cases.  Source: I am a lighttpd developer that has tested both lighttpd and nginx is numerous scenarios, both 32-bit and 64-bit.  nginx is an excellent web server, and so is lighttpd.  I would appreciate if you avoided spreading ill-informed FUD about either.
