### ISSUE TITLE
Buttons missing + Cant open Addons after Update to supervisor-2021.06.3

### ISSUE THREAD

**Issue by FaserF** [home-assistant/supervisor#2963]
### Describe the issue you are experiencing

After updating to supervisor-2021.06.3 from supervisor-2021.06.0 I am unable to Update my HA Core (button wont work and wont be displayed), many many buttons are now not being displayed anymore and I cant open any of my addons anymore. 

What I have done trying to fix it:
Restarted the whole OS
Restarted HA
Cleared my Cache
Opended HA in an incognito Tab
Tried it on another device

### What is the used version of the Supervisor?

supervisor-2021.06.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.0

### What version of Home Assistant Core is installed?

core-2021.6.4

### Steps to reproduce the issue

Update Supervisor to supervisor-2021.06.3 from supervisor-2021.06.0
See the issue.

### Anything in the Supervisor logs that might be useful for us?

```txt
Supervisor Logs dont display anything related to this issue.
```

### Additional information

![image](https://user-images.githubusercontent.com/12374134/122247429-9e06ed80-cec7-11eb-8264-497cea407c50.png)
![image](https://user-images.githubusercontent.com/12374134/122247464-a5c69200-cec7-11eb-88a3-bc71f1223ea4.png)
![image](https://user-images.githubusercontent.com/12374134/122247491-a9f2af80-cec7-11eb-8f35-70f89083713b.png)

**Comment by ludeeus** [comment]
Please reopen this on the frontend repo <https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug,supervisor&template=bug_report.yml> thanks 👍

**Comment by FaserF** [comment]
Okay, sorry, I thought it has to be in the supervisor issues, as the issue appeared after the latest supervisor update.

**Comment by ludeeus** [comment]
the web/UI/frontend part of the supervisor is done in the frontend repo, and the issue template there are more suited for the information needed to troubleshoot it 👍
