### ISSUE TITLE
Snapshot mariadb error when addon is stopped

### ISSUE THREAD

**Issue by shirou93** [home-assistant/supervisor#2968]
### Describe the issue you are experiencing

When try try snaphost error in logs:

21-06-18 14:42:36 ERROR (MainThread) [supervisor.addons.addon] Failed running pre-/post-snapshot command /bin/s6-svc -wU -u /run/s6/services/mariadb-lock/: 
21-06-18 14:42:36 ERROR (MainThread) [supervisor.snapshots.snapshot] Can't create snapshot for core_mariadb

### What is the used version of the Supervisor?

supervisor-2021.06.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian 10

### What version of Home Assistant Core is installed?

core-2021.6.5

### Steps to reproduce the issue

1. Click full snaphost with mariadb addon
2. check logs in supervisor

### Anything in the Supervisor logs that might be useful for us?

```txt
21-06-18 14:42:36 ERROR (MainThread) [supervisor.addons.addon] Failed running pre-/post-snapshot command /bin/s6-svc -wU -u /run/s6/services/mariadb-lock/: 
21-06-18 14:42:36 ERROR (MainThread) [supervisor.snapshots.snapshot] Can't create snapshot for core_mariadb
```

**Comment by agners** [comment]
This seems to be related to this: https://github.com/home-assistant/addons/pull/2063

I wonder however why the pre-snapshot command fails. Can you post the log of the MariaDB add-on?

**Comment by shirou93** [comment]
> This seems to be related to this: https://github.com/home-assistant/addons/pull/2063
> 
> I wonder however why the pre-snapshot command fails. Can you post the log of the MariaDB add-on?

When Maria addon snaphost got without problems. When addon is stopped and try create full snapshot got error like this from previous post.

**Comment by agners** [comment]
Ah I see, yeah for now the add-on needs to be running for a snapshot. This will be fixed once https://github.com/home-assistant/supervisor/pull/2943 lands.
