### ISSUE TITLE
Supervisor Fails to update Error 404

### ISSUE THREAD

**Issue by hadikatranji** [home-assistant/supervisor#2972]
### Describe the issue you are experiencing

I'm currently facing this error while trying to update my unhealthy supervisor to the new version

### What is the used version of the Supervisor?

supervisor-2021.05.4

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 6.0

### What version of Home Assistant Core is installed?

core-2021.5.5

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-06-22 08:55:58 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install homeassistant/aarch64-hassio-supervisor:2021.06.3: 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/aarch64-hassio-supervisor:2021.06.3/json: Not Found ("no such image: homeassistant/aarch64-hassio-supervisor:2021.06.3: No such image: homeassistant/aarch64-hassio-supervisor:2021.06.3")
```

**Comment by pvizeli** [comment]
Yeah, the local image is corrupt. Currently is no function available to fix his own image, but I know some things which I can implement that can fix it. But I currently have no timeline for that
