### ISSUE TITLE
Cannot load repositories

### ISSUE THREAD

**Issue by echellst** [home-assistant/supervisor#2991]
### Describe the issue you are experiencing

Hello, I am on HASS OS6.1, supervisor 2021-06.6, core 2021 6.6. Evervy time that I try to load a custom repository, it gives me “Invalid Add-On Repository”. See the attached image.

### What is the used version of the Supervisor?

2021 - 6.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.1

### What version of Home Assistant Core is installed?

2021-6.1

### Steps to reproduce the issue

1. Click Add on store
2. Click the three dots menu in the upper right
3. Select Repository, and enter “ https://github.com/schmittx/home-assistant-eero” or “ https://github.com/schmittx/home-assistant-eero.git”
4. Wait a few moments and I get the error. This error happens with any repository, and only started aft upgrading to OS 6.1.
![44B85EEE-AAF3-439F-BA4B-5D2CE7D5A6B1](https://user-images.githubusercontent.com/73681025/124202841-8d926d80-da98-11eb-9000-12e7d6f53423.png)
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-07-01 17:58:35 ERROR (MainThread) [supervisor.store] https://github.com/schmittx/home-assistant-eero.git is not a valid add-on repository
21-07-01 17:58:35 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / 4385189d
21-07-01 17:58:35 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / 4385189d
21-07-01 17:58:36 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/4385189d
```

### Additional information

Again, this happens with any repository.

**Comment by frenck** [comment]
That is not an add-on repository, but a HACS custom integration repository.
