### ISSUE TITLE
Pressing start on an addon does nothing

### ISSUE THREAD

**Issue by Haarolean** [home-assistant/supervisor#3005]
### Describe the issue you are experiencing

Clicking start on addon tab does nothing. No js issues in browser console, no network requests.

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Ubuntu 20.04.2 LTS

### What version of Home Assistant Core is installed?

core-2021.7.1

### Steps to reproduce the issue

1. Click start

### Anything in the Supervisor logs that might be useful for us?

```txt
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.addon] 7ad98f9c_zigbee2mqtt is already running!
21-07-11 01:50:30 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
```

**Comment by ludeeus** [comment]
Your installation is not supported, try seeking help on discord or the forums

**Comment by Haarolean** [comment]
How come? I've used your official script to install it on bare metal.

**Comment by ludeeus** [comment]
https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md
Ubuntu is not supported
