### ISSUE TITLE
The logs of "core" and "supervisor" take really long to show up

### ISSUE THREAD

**Issue by carsten-h** [home-assistant/supervisor#3014]
### The problem

Since a few versions (I don’t know if it was Home Assistant Operating System, Home Assistant Core or Home Assistant Supervisor) it takes 10-20 seconds before a log is shown.
It is regardless which log it is. The logs at Supervisor/System/Supervisor and /Core are taking long and also the logs of Addons (AdGuard Home, AppDaemon 4, Duck DNS, File Editor, Mosquitto broker, Nginx Proxy Manager, Samba Backup, Samba share, TasmoAdmin, WireGuard) are taking long to display.

I am running a Raspberry Pi 4 4GB with a M.2 SSD as startup/work drive.

### What is version of Home Assistant Core has the issue?

core-2021.7.3

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
There is no error or something like that. Just showing the logs takes long.
```

**Comment by ludeeus** [comment]
How are you accessing the logs?
is it the same both for the UI and with `ha su logs`?

**Comment by carsten-h** [comment]
I am only viewing it with the UI.

**Comment by ludeeus** [comment]
Can you try the CLI?

**Comment by carsten-h** [comment]
Yes, I did. The first time it took long, then it was fast. Also „ha core logs“ was fast then.
Interestingly it is now also fast via the UI.
But the logs for the Addons are slow.

**Comment by ludeeus** [comment]
Sounds like your system is overloaded, do you only have add-ons or regular docker containers as well?
Can you paste the system health <https://www.home-assistant.io/more-info/system-health#github-issues>?

**Comment by carsten-h** [comment]
## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 907
Installed Repositories | 12

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 219.4 GB
disk_used | 17.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.1.6), AppDaemon 4 (0.6.2), Bitwarden (Vaultwarden) (0.12.0), Check Home Assistant configuration (3.8.0), Duck DNS (1.13.0), File editor (5.3.3), HDD Tools (0.50.1), MariaDB (2.4.0), Mosquitto broker (6.0.1), Nginx Proxy Manager (0.11.0), Samba share (9.5.1), TasmoAdmin (0.15.0), WireGuard (0.5.1), Visual Studio Code (3.6.0), SSH & Web Terminal (9.0.0), RPi Temp Monitor (0.4), ArgonOne Active Cooling (23.0), Samba Backup (4.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 9
views | 1
mode | yaml

</details>

**Comment by ludeeus** [comment]
Try again now with 2021.8 of Core

**Comment by carsten-h** [comment]
It is still the same.
The longest time is needed for core log and sometimes there is also a message that the core log can not be shown and I should look into supervisor log. But there is nothing to see.

**Comment by ludeeus** [comment]
Check your browser console for issues

**Comment by carsten-h** [comment]
Which browser console? I am using the App on iOS/iPadOS/macOS.

**Comment by ludeeus** [comment]
So it only happens in the app?

**Comment by carsten-h** [comment]
No, it is also visible in Safari, Chrome, Vivaldi, Opera and a standalone webapp on my Mac.

**Comment by ludeeus** [comment]
So get the logs from one of those :)

**Comment by carsten-h** [comment]
I am seeing this when I am going to Supervisor/System and there choose "Core":

![Bildschirmfoto 2021-08-09 um 18 48 28](https://user-images.githubusercontent.com/44360828/128743411-3eb68060-a83b-46ef-81eb-595c66ab14cb.png)

**Comment by ludeeus** [comment]
None of those are related, try with chrome

**Comment by carsten-h** [comment]
I did the same, and got the same reactions:

![Bildschirmfoto 2021-08-09 um 18 53 09](https://user-images.githubusercontent.com/44360828/128744037-5e4a3aa2-2bfe-4bd6-bd7f-c960b922d16e.png)

**Comment by ludeeus** [comment]
use `ha supervisor logs` and `ha core logs` on the CLI and see if those return anything

**Comment by carsten-h** [comment]
This is what I got first after 20 seconds:
![Bildschirmfoto 2021-08-10 um 11 29 17](https://user-images.githubusercontent.com/44360828/128843435-62f28d45-1190-403f-9909-f8b2a308df11.png)
The next time it was fast and showed the correct log.

For the supervisor log it is the same.

**Comment by ludeeus** [comment]
Try setting static DNS server to  `1.1.1.1` or `8.8.8.8`

**Comment by carsten-h** [comment]
Where should I set this? Home Assistant is using my router as the DNS Server and that is using AdGuard which is running on the Home Assistant Pi and that is already using 1.1.1.1 as the external DNS.

But I thought this is a local thing, as I am reaching the Home Assistant Pi from my local network.

**Comment by ludeeus** [comment]
In the Supervisor panel under "System", click "change" next to the IP

**Comment by carsten-h** [comment]
Ok, I did it, but it didn't changed anything.

**Comment by ludeeus** [comment]
You need to reboot after (power off -> power on), forgot to mention that.
If that does not help, then you have probably exhausted what a pi is capable of.

**Comment by carsten-h** [comment]
Ok, I did a reboot.
And it is still slow.

> then you have probably exhausted what a pi is capable of.

What? This was only some of the last Home Assistant Operating System or Home Assistant Core Updates. I have not installed any new Addons/Integrations in the meantime.
Before it was working fine and fast.

**Comment by carsten-h** [comment]
So I will have to live with this slow showing logfiles?

Is there really no one else that has this problems? Very strange!

**Comment by carsten-h** [comment]
Isn't someone other here that can tell me why logfiles are showing is so slow?

PLEASE HELP ME!

**Comment by ColoradoBills** [comment]
I just did a complete reinstall of HAOS. Nothing was restored from a backup. So far it is working as intended. 

Raspberry Pi 4 4GB with a 128GB SSD via a SATA to USB adapter. Also using stock power supply. 

I hope this fixes the issue with logs not populating at all in Supervisor and the log file under Configuration.

But I just noticed I am getting this error non-stop now:

2021-09-29 15:41:12 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-09-29 15:41:27 ERROR (MainThread) 

## System Health

version | core-2021.9.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | America/Denver

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 15, 2021, 7:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.4
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.6
docker_version | 20.10.7
disk_total | 109.3 GB
disk_used | 2.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | deCONZ (6.10.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

Also my Zigbee IKEA lights are having issues connecting to my DeCONZ adapter.

**Comment by bschatzow** [comment]
I am also seeing the logs very slow to load after updating agent to 1.1.1.  I have seen a couple of others in the forums with the same issue.  The only error I see in SU log is"
```
21-10-03 05:50:59 ERROR (MainThread) [supervisor.utils] Can't execute check_trust while a task is in progress
```

**Comment by Tamsy** [comment]
> I am also seeing the logs very slow to load after updating agent to 1.1.1. I have seen a couple of others in the forums with the same issue. The only error I see in SU log is"
> 
> ```
> 21-10-03 05:50:59 ERROR (MainThread) [supervisor.utils] Can't execute check_trust while a task is in progress
> ```

Experiencing exactly the same behavior (RPI4 4, Gebian 11, HA Supervised - core-2021.9.7 - supervisor-2021.09.6)

**Comment by wauswaus** [comment]
same here, also made an issue for it: https://github.com/home-assistant/supervisor/issues/3076

**Comment by Veldkornet** [comment]
I'm having the same problem, I made a post in the community [here](https://community.home-assistant.io/t/supervisor-logs-extremely-slow-to-open/344375) before finding this.

## System Health

version | core-2021.9.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4675
Installed Version | 1.15.2
Stage | running
Available Repositories | 898
Installed Repositories | 36

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 20 October 2021, 2:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.4
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.6
docker_version | 20.10.7
disk_total | 228.5 GB
disk_used | 12.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Node-RED (10.0.1), Log Viewer (0.12.0), SSH & Web Terminal (9.0.1), Portainer (2.0.0), Visual Studio Code (3.6.2), InfluxDB (4.2.1), Grafana (7.2.0), Syncthing (1.18.3), ESPHome (2021.9.2), Glances (0.13.0), chrony (2.2.0), Mosquitto broker (6.0.1), File editor (5.3.3), Duck DNS (1.14.0), ArgonOne Active Cooling (24.1), Vaultwarden (Bitwarden) (0.13.0), AdGuard Home (4.1.9), Z-Wave JS (0.1.45)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 17
views | 12
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

For the last month or 2/3, looking at any of the logs in Supervisor or the containers take EXTREMELY long, where they used to be instant. 

Anyone lese have this problem?

You can see here below that it took 1.2 minutes before the logs showed:
![image](https://user-images.githubusercontent.com/10297361/136176392-8e287335-6508-499b-9fff-0a0ee3299f30.png)

I do see some of these error messages in the console, unclear if it's related:

`entrypoint.b658878e.js:16479 Uncaught (in promise) {code: 'unknown_error', message: ''}`
![image](https://user-images.githubusercontent.com/10297361/136176348-43a37c2e-c6d3-4ada-9132-b7074924a2dc.png)

Full message:
```
content.js:4 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:4
content.js:5 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
(anonymous) @ content.js:5
app.f08a72d3.js:5264 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
55704 @ app.f08a72d3.js:5264
s @ app.f08a72d3.js:30632
53918 @ app.f08a72d3.js:1290
s @ app.f08a72d3.js:30632
(anonymous) @ app.f08a72d3.js:30632
(anonymous) @ app.f08a72d3.js:36741
(anonymous) @ app.f08a72d3.js:36741
entrypoint.b658878e.js:38000 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
5704 @ entrypoint.b658878e.js:38000
s @ entrypoint.b658878e.js:73826
4552 @ entrypoint.b658878e.js:65175
s @ entrypoint.b658878e.js:73826
1625 @ entrypoint.b658878e.js:72024
s @ entrypoint.b658878e.js:73826
7714 @ entrypoint.b658878e.js:6216
s @ entrypoint.b658878e.js:73826
(anonymous) @ entrypoint.b658878e.js:73826
(anonymous) @ entrypoint.b658878e.js:73826
entrypoint.b658878e.js:16479 Uncaught (in promise) {code: 'unknown_error', message: ''}
value @ entrypoint.b658878e.js:16479
async function (async)
value @ entrypoint.b658878e.js:16479
value @ entrypoint.b658878e.js:16479
_$AE @ entrypoint.b658878e.js:21033
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
o @ entrypoint.b658878e.js:21033
b @ entrypoint.b658878e.js:21033
p @ entrypoint.b658878e.js:38000
F @ entrypoint.b658878e.js:16233
p @ entrypoint.b658878e.js:38000
T @ entrypoint.b658878e.js:38000
_$AI @ entrypoint.b658878e.js:38000
I @ entrypoint.b658878e.js:38000
update @ entrypoint.b658878e.js:38000
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
o @ entrypoint.b658878e.js:21033
b @ entrypoint.b658878e.js:21033
p @ entrypoint.b658878e.js:38000
F @ entrypoint.b658878e.js:16971
value @ entrypoint.b658878e.js:72201
value @ entrypoint.b658878e.js:72201
value @ entrypoint.b658878e.js:72201
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
o @ entrypoint.b658878e.js:21033
b @ entrypoint.b658878e.js:21033
r @ entrypoint.b658878e.js:72201
F @ entrypoint.b658878e.js:17118
p @ entrypoint.b658878e.js:38000
T @ entrypoint.b658878e.js:38000
_$AI @ entrypoint.b658878e.js:38000
I @ entrypoint.b658878e.js:38000
update @ entrypoint.b658878e.js:38000
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
set @ entrypoint.b658878e.js:21033
value @ entrypoint.b658878e.js:17351
value @ entrypoint.b658878e.js:72201
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
set @ entrypoint.b658878e.js:21033
P @ entrypoint.b658878e.js:38000
_$AI @ entrypoint.b658878e.js:38000
m @ entrypoint.b658878e.js:38000
T @ entrypoint.b658878e.js:38000
_$AI @ entrypoint.b658878e.js:38000
I @ entrypoint.b658878e.js:38000
update @ entrypoint.b658878e.js:38000
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
set @ entrypoint.b658878e.js:21033
value @ entrypoint.b658878e.js:17351
(anonymous) @ entrypoint.b658878e.js:17351
r @ entrypoint.b658878e.js:38000
(anonymous) @ entrypoint.b658878e.js:38000
Promise.then (async)
l @ entrypoint.b658878e.js:38000
c @ entrypoint.b658878e.js:38000
subscribe @ entrypoint.b658878e.js:38000
value @ entrypoint.b658878e.js:17351
value @ entrypoint.b658878e.js:17351
_$AE @ entrypoint.b658878e.js:21033
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
o @ entrypoint.b658878e.js:21033
b @ entrypoint.b658878e.js:21033
p @ entrypoint.b658878e.js:38000
(anonymous) @ entrypoint.b658878e.js:17351
ws @ entrypoint.b658878e.js:17351
r @ entrypoint.b658878e.js:17351
r @ entrypoint.b658878e.js:17351
finisher @ entrypoint.b658878e.js:21033
runClassFinishers @ entrypoint.b658878e.js:17351
(anonymous) @ entrypoint.b658878e.js:17351
7714 @ entrypoint.b658878e.js:17351
s @ entrypoint.b658878e.js:73826
(anonymous) @ entrypoint.b658878e.js:73826
(anonymous) @ entrypoint.b658878e.js:73826
entrypoint.b658878e.js:15543 Uncaught (in promise) {code: 'unknown_error', message: ''}
value @ entrypoint.b658878e.js:15543
async function (async)
value @ entrypoint.b658878e.js:15543
value @ entrypoint.b658878e.js:15543
_$AE @ entrypoint.b658878e.js:21033
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
o @ entrypoint.b658878e.js:21033
b @ entrypoint.b658878e.js:21033
p @ entrypoint.b658878e.js:38000
F @ entrypoint.b658878e.js:15386
p @ entrypoint.b658878e.js:38000
T @ entrypoint.b658878e.js:38000
_$AI @ entrypoint.b658878e.js:38000
I @ entrypoint.b658878e.js:38000
update @ entrypoint.b658878e.js:38000
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
o @ entrypoint.b658878e.js:21033
b @ entrypoint.b658878e.js:21033
p @ entrypoint.b658878e.js:38000
F @ entrypoint.b658878e.js:16971
value @ entrypoint.b658878e.js:72201
value @ entrypoint.b658878e.js:72201
value @ entrypoint.b658878e.js:72201
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
o @ entrypoint.b658878e.js:21033
b @ entrypoint.b658878e.js:21033
r @ entrypoint.b658878e.js:72201
F @ entrypoint.b658878e.js:17118
p @ entrypoint.b658878e.js:38000
T @ entrypoint.b658878e.js:38000
_$AI @ entrypoint.b658878e.js:38000
I @ entrypoint.b658878e.js:38000
update @ entrypoint.b658878e.js:38000
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
set @ entrypoint.b658878e.js:21033
value @ entrypoint.b658878e.js:17351
value @ entrypoint.b658878e.js:72201
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
set @ entrypoint.b658878e.js:21033
P @ entrypoint.b658878e.js:38000
_$AI @ entrypoint.b658878e.js:38000
m @ entrypoint.b658878e.js:38000
T @ entrypoint.b658878e.js:38000
_$AI @ entrypoint.b658878e.js:38000
I @ entrypoint.b658878e.js:38000
update @ entrypoint.b658878e.js:38000
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
set @ entrypoint.b658878e.js:21033
value @ entrypoint.b658878e.js:17351
(anonymous) @ entrypoint.b658878e.js:17351
r @ entrypoint.b658878e.js:38000
(anonymous) @ entrypoint.b658878e.js:38000
Promise.then (async)
l @ entrypoint.b658878e.js:38000
c @ entrypoint.b658878e.js:38000
subscribe @ entrypoint.b658878e.js:38000
value @ entrypoint.b658878e.js:17351
value @ entrypoint.b658878e.js:17351
_$AE @ entrypoint.b658878e.js:21033
performUpdate @ entrypoint.b658878e.js:21033
_$EC @ entrypoint.b658878e.js:21033
async function (async)
_$EC @ entrypoint.b658878e.js:21033
requestUpdate @ entrypoint.b658878e.js:21033
o @ entrypoint.b658878e.js:21033
b @ entrypoint.b658878e.js:21033
p @ entrypoint.b658878e.js:38000
(anonymous) @ entrypoint.b658878e.js:17351
ws @ entrypoint.b658878e.js:17351
r @ entrypoint.b658878e.js:17351
r @ entrypoint.b658878e.js:17351
finisher @ entrypoint.b658878e.js:21033
runClassFinishers @ entrypoint.b658878e.js:17351
(anonymous) @ entrypoint.b658878e.js:17351
7714 @ entrypoint.b658878e.js:17351
s @ entrypoint.b658878e.js:73826
(anonymous) @ entrypoint.b658878e.js:73826
(anonymous) @ entrypoint.b658878e.js:73826
```

**Comment by jtregl** [comment]
Same problem, for some addons it takes seconds to show log for some addons it never shows up. HassOs with latest updates of all components. Don't know when it started. I didn't need to check logs for months until now.

**Comment by habitoti** [comment]
Same here. Saw it being blamed on SSD configuration issues (which might amplify this problem admittedly), however even with normal SSD performance, accessing logs of add-ons and supervisor is much slower these days than it used to be earlier.

**Comment by jtregl** [comment]
Issue still persist for me.
## System Health

version | core-2021.12.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v8
arch | aarch64
timezone | Europe/Prague

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.19.3
Stage | running
Available Repositories | 931
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 109.3 GB
disk_used | 14.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.105.2), deCONZ (6.11.1), Terminal & SSH (9.3.0), Mosquitto broker (6.0.1), Log Viewer (0.12.1), Samba share (9.5.1), Studio Code Server (4.0.0), Check Home Assistant configuration (3.9.0), Zigbee2mqtt (1.18.1-1), Frigate NVR (2.3), MariaDB (2.4.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 3
views | 9
mode | storage

</details>

**Comment by Veldkornet** [comment]
> Issue still persist for me.
> 

Have you tried [this](https://community.home-assistant.io/t/supervisor-logs-extremely-slow-to-open/344375/22?u=veldkornet)?

**Comment by jtregl** [comment]
> > Issue still persist for me.
> 
> Have you tried [this](https://community.home-assistant.io/t/supervisor-logs-extremely-slow-to-open/344375/22?u=veldkornet)?

I would like to try, but I ended up not able to enable SSH on 22222 port as described in the link in your referenced comment. The plugin for the 22222 port simply not did what it supposed to do. So I'm not able to open terminal to adapt the stuff related to usb device.
Anyway even this "techy workaround" would work, its really not an expected approach to solve the problem from my point of view. This slow log issue is an bug started by an former update. Experiments with such low level system setting on a live running HA is very risky.
I would expect some official solution in regular HA update or something like that.

**Comment by OneCyrus** [comment]
same issue here

with the cli it shows this: 
![image](https://user-images.githubusercontent.com/7747800/157400454-8cc96f5d-7536-4416-bcd2-66459e1d485d.png)

**Comment by Minims** [comment]
Hello,

I have the same issue with : 
 - RPi 4 2GB
 - Raspbian 11.3 64 bits (bullseye)
 - M2 SSD
 - supervisor-2022.05.0
 - core-2022.5.3
 - supervised installation

When I try to get logs from an addon in HA, the load is growing because the I/O are at 100%.
So it's only for Docker logs.
![HA](https://user-images.githubusercontent.com/1724785/167378222-cb034f4a-deee-4011-9225-a8d63d2c67e9.png)

But I can get logs without issue while doing this : 
```
sudo docker exec -it addon_<addon_name/id>  /bin/bash
```
and then tail th logs inside the docker.

I suspect an issue with the 64 bits or bullseye. The last time it works (6 month ago) I was in 32 bits on raspbian 10.

**Comment by jtregl** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates. Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment 👍 This issue has now been marked as stale and will be closed if no further activity occurs. Thank you for your contributions.

Issue still persists with latest updates.

Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6
Kernel version 5.10.103-v8
Agent version 1.2.1

**Comment by Minims** [comment]
> > Issue still persist for me.
> 
> Have you tried [this](https://community.home-assistant.io/t/supervisor-logs-extremely-slow-to-open/344375/22?u=veldkornet)?

it works for me. Thanks !

**Comment by carsten-h** [comment]
> it works for me.

This works here too. But now you are not using UASP any longer, so the SSD will be slower.
I tested to disable this with 2022.5.0 but the issue is still there!
With Raspberry Pi OS and the same USB-M.2-SATA Controller (Argon One M.2 case) there is no such problem. The SSD is running there with UASP and no problem.
So there has to be a problem with Home Assistant OS and UASP!

**Comment by Minims** [comment]
I'm running Raspberry Pi OS Bullseye 64 bits (not Home Assistant OS) and I have the issue.
I have aslo a Argon One M.2 case for my Pi 4.

**Comment by carsten-h** [comment]
> 64 bits

Maybe that is the difference. I am using the 32 bit version of Raspberry Pi OS Bullseye but the 64bit version auf Home Assistant OS.

**Comment by Minims** [comment]
> > 64 bits
> 
> Maybe that is the difference. I am using the 32 bit version of Raspberry Pi OS Bullseye but the 64bit version auf Home Assistant OS.

I think you are right.
My old version was a Raspberry Pi OS Buster 32bits, and everything was Ok.

**Comment by carsten-h** [comment]
> and everything was Ok.

The strange thing is that everything has been OK until Home Assistant OS 2021.6 or so. Then the problems started.

**Comment by Minims** [comment]
what about this ?  https://forums.raspberrypi.com/viewtopic.php?t=293326
