### ISSUE TITLE
Snapshot either fails or take a really long time

### ISSUE THREAD

**Issue by NVader2000** [home-assistant/supervisor#3015]
### The problem

When updating the core and allowing it to take a snapshot fails. I must run them separately which take an exceptionally long time, like 5-10 minutes. Also noticed that my used space is increasing by at least 1% per day.

Please advise

### What is version of Home Assistant Core has the issue?

2021.7.3

### What was the last working version of Home Assistant Core?

2021.6.0

### What type of installation are you running?

Home Assistant OS

**Comment by ludeeus** [comment]
There is nothing to go from in this issue, please reopen it and provide all the details requested in the issue template <https://github.com/home-assistant/supervisor/issues/new?assignees=&labels=bug&template=bug_report.yml>
