### ISSUE TITLE
Firefox: 401: Unauthorized / No valid ingress session None

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/supervisor#3021]
### Describe the issue you are experiencing

I am no longer able to display the Web UI of Add-Ons such as Node-Red, File Editor, Portainer, SQLite Web, etc.

Clicking "Open Web UI" results in this message:
```text
401: Unauthorized
```

Supervisor's log reports:
```text
21-07-21 15:31:24 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
```

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

2021.7.2

### Steps to reproduce the issue

Unknown.

### Anything in the Supervisor logs that might be useful for us?

```txt
21-07-21 15:31:24 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
```

### Additional information

I normally access Home Assistant via one of three devices (using the same admin-level account):

1. Android tablet with MS Edge. This device has displayed the `401: Unauthorized message` for a long time. I was never able to fix it but it didn't matter because the tablet was impractical for using Node-Red.

2. Ubuntu laptop with Firefox. This device is my daily driver for maintaining Home Assistant and now it cannot display the web UI of various Add-Ons, notably Node-Red, File Editor, Portainer, etc.

3. Windows desktop with MS Edge. This one is still able to display the web UI of Add-Ons.

I don't know what causes this problem so everything I have tried is a shot in the dark (and none of it has worked):
- Refresh browser page
- Delete refresh tokens
- Reboot host machine

**Comment by kekonn** [comment]
I have the same issue. It has started occurring for me since the release of FF90. I have tried FF on Windows 10, Windows 11 and Manjaro with the same result. I have tried deleting all cookies related to my domain.

It works on the apps though and also on Chrome and whatever out of the box browser Manjaro has.

**Comment by tdejneka** [comment]
I can confirm that I am also using Firefox 90.0 on Ubuntu. I know it was working recently with version 89.

I don't know if this is frontend issue but there's definitely an entry in Supervisor's log regarding "No valid ingress session None".

**Comment by kekonn** [comment]
I have switched OS on my pc and can confirm that it also happens with FireDragon and Firefox 90.0.2

**Comment by tdejneka** [comment]
FWIW, I installed Chromium on the Ubuntu laptop and, unlike Firefox 90, it permits access to the Web UI of Add-Ons.

```text
Chromium
Version 92.0.4515.107 (Official Build) snap (64-bit)
```
Not sure what is the difference between the way the two browsers access the URLs to the Add-Ons but Supervisor allows Chromium 92 whereas it reports "No valid ingress session None" for Firefox 90.

**Comment by casperklein** [comment]
I had to disable the tracking protection left to the address bar, to get _ingress_ working again:

![ff](https://user-images.githubusercontent.com/590174/126875756-563c83f4-6e23-475d-9a48-16f96eb355b0.png)

**Comment by tdejneka** [comment]
> disable the tracking protection

Thank you, that's very helpful.

I can confirm that disabling tracking protection in Firefox 90  allows it to display the Add-On's web UI. However, here are some interesting observations:

- Before disabling it, Firefox reported it found no trackers for that web page (hovering over the tracker icon displays the report).
- I disabled and then _re_-enabled tracking protection and the web UI continues to be accessible. In other words, it now works even with tracking protection enabled.

I don't understand the underlying mechanism responsible for this behavior but it seems to create a false-positive for Firefox's tracking detection.

**Comment by casperklein** [comment]
The only difference I see between enabled/disabled tracking protection:

- enabled: "Blocking third party cookies"
- disabled: "Allowing third party cookies"

**Comment by tdejneka** [comment]
Another observation: Disabling tracking prevention for MS Edge on Android has no effect; even when disabled, I still get `401: Unauthorized`. In contrast, on the same Android tablet, Chrome browser permits access to an Add-On's web UI (both share the same engine).

Based on that, I don't think the tracker feature alone (whether enabled or disabled) is entirely responsible for the issue.

There seems to be something specific about how a given web UI presents itself that causes it to be rejected in some cases.

**Comment by kekonn** [comment]
Can confirm that disabling tracking protection does make it work again.

**Comment by tdejneka** [comment]
Now _re_-enable it and see if it still works. It did for me. That implies it's a bit more complicated than merely the presence of tracking detection.

**Comment by casperklein** [comment]
> Now re-enable it and see if it still works. It did for me. 

Not for me.

**Comment by tdejneka** [comment]
The variability of what does/doesn't work suggests that disabling tracker protection isn't a panacea.
- It doesn't fix the issue for Edge on Android.
- It remained fixed even after I re-enabled tracker protection for Firefox 90 on Ubuntu (but not for you).

Hopefully the variability of these results provides clues for the developers to determine the root cause of the problem.

**Comment by kekonn** [comment]
I just did some extra testing. If you disable and then re-enable immediately, it doesn't seem to work. You have to be on a page that shows the error, disable the protection, wait for the page to reload and show the expected content, then re-enable tracking protection. Ingress will then keep working.

**Comment by kekonn** [comment]
In conclusion, it seems that something in Firefox tracking protection has changed so that some cookie that Ingress needs, cannot be set anymore.

**Comment by tdejneka** [comment]
The exception remains MS Edge on Android. Disabling "tracking prevention" (as it's called in Edge) doesn't eliminate the 401 error.

It would be helpful to know more about what is expected of the browser for establishing communications.

**Comment by balloob** [comment]
It looks like Firefox 90 has added extra protections to the "Strict" privacy profile that is currently incompatible with Ingress. We're looking into it.

**Comment by sim-san** [comment]
Should the information about the Firefox bug get an entry in the alerts?

**Comment by balloob** [comment]
https://github.com/home-assistant/core/pull/55673

**Comment by jamesmyatt** [comment]
I have this on Chrome 93 too now

**Comment by balloob** [comment]
@jamesmyatt open a new issue. This issue is for firefox.

**Comment by balloob** [comment]
Firefox 95 has been released and Ingress now works with strict mode. If you encounter an issue, please open a new issue.
