### ISSUE TITLE
I can't update my ha & hassio anymore

### ISSUE THREAD

**Issue by lovelylain** [home-assistant/supervisor#3025]
### Describe the issue you are experiencing

My last working ok versions are:
aarch64-hassio-supervisor:2021.06.0
qemuarm-64-homeassistant:2021.6.6
aarch64-hassio-dns:2021.04.0

After I update to latest version,
dns:2021.06.0 will make `nslookup 192.168.0.X` timeout, so I must downgrade dns to 2021.04.0 and block `version.home-assistant.io` to disable auto update. maybe related to issue #2955 
supervisor:2021.06.3 and later will restart HA automatically, so I must downgrade supervisor to 2021.06.0. maybe related to change #2958 
new version HA and old version supervisor are not compatible, addon ingress pages are blank. so I must downgrade core to 2021.6.6.
Could someone help me?

### What is the used version of the Supervisor?

supervisor-2021.06.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.7.10

### What version of Home Assistant Core is installed?

core-2021.6.6

### Steps to reproduce the issue

update to new version.

### Anything in the Supervisor logs that might be useful for us?

```txt
1. dns-2021.06.0
# docker exec -it hassio_cli ha dns logs
[INFO] 127.0.0.1:53491 - 4181 "PTR IN 197.0.168.192.in-addr.arpa. udp 55 true 2048" NOERROR - 0 26.580277463s
[ERROR] plugin/errors: 2 197.0.168.192.in-addr.arpa. PTR: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 127.0.0.1:35487 - 32969 "NS IN . udp 17 false 512" NOERROR - 0 30.00055437s
[ERROR] plugin/errors: 2 . NS: dial tcp 1.1.1.1:853: i/o timeout

2. supervisor-2021.06.0 and later
Watchdog found a problem with Home Assistant API!
```

**Comment by ludeeus** [comment]
Only Debian is supported as the host OS for a supervised installation
<https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>

You should reinstall with that or use Home Assistant Operating System
<https://www.home-assistant.io/installation/>
