### ISSUE TITLE
Invalid Add-On Repository  / DNS Issue?

### ISSUE THREAD

**Issue by hazenjaqdx3** [home-assistant/supervisor#3026]
### Describe the issue you are experiencing

Hello,

I cannot grasp the Background of this Issue and (in my beginner Opinion) Homeassistant doesnt really show me that much information so I am opening an Issue because I cannot really diagnose anything here. 

Basically every new repository I want to add I get the Error Message "Invalid Add-on repository!". This happens with some of the Repositories I tried in the last few weeks, for example:

https://github.com/jm-73/Indego
https://github.com/fondberg/spotcast
https://github.com/Apipa169/Assistant-Relay-for-Hassio

Weirdly enough, the last Link works. 

I have tried to restart the System (Host) then adding it, I have disabled my DuckDNS Access, I have tried to change the DNS Server over SSH (CLI) to 8.8.8.8 via "ha dns options --servers dns://8.8.8.8". Nothing changes. I have read some other posts that stated that DNS is falsely setup. My router uses the standard Telekom DNS.

Whats also interesting, although I dont know if that has anything to do with this issue, if I try to "Manually install" the addons by dragging them into the custom_components folder, they are not installed after I restart the host. 

### What is the used version of the Supervisor?

supervisor-2021.06.8 (beta)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 6.1

### What version of Home Assistant Core is installed?

core-2021.7.4

### Steps to reproduce the issue

1. Paste the Link in the HACS Repositories section 
2. Try to Add repository
3. Voila: "Invalid Add-on repository!"
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-07-25 15:24:54 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/jm-73/Indego repository
21-07-25 15:24:55 ERROR (MainThread) [supervisor.store] https://github.com/jm-73/Indego is not a valid add-on repository
21-07-25 15:24:55 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / b35b8ccd
21-07-25 15:24:55 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / b35b8ccd
21-07-25 15:24:55 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/b35b8ccd
21-07-25 15:24:56 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove
21-07-25 15:24:56 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: b35b8ccd
21-07-25 15:24:56 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/jm-73/Indego


Different Log Entry:
21-07-25 15:29:30 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/fondberg/spotcast repository
21-07-25 15:29:31 ERROR (MainThread) [supervisor.store] https://github.com/fondberg/spotcast is not a valid add-on repository
21-07-25 15:29:31 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / d27bc1c4
21-07-25 15:29:31 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / d27bc1c4
21-07-25 15:29:32 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/d27bc1c4
21-07-25 15:29:32 INFO (MainThread) [supervisor.store] Loading add-ons from store: 65 all - 0 new - 0 remove
21-07-25 15:29:32 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: d27bc1c4
21-07-25 15:29:32 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/fondberg/spotcast


Now I see that there are warnings/errors in the Logs, but neither Google happens to find concrete Information nor are there any Issues openend in the Projects for this Issue.
```

**Comment by frenck** [comment]
Those are integration repositories, not addons. Those are different things.
