### ISSUE TITLE
Could not load the Supervisor panel!

### ISSUE THREAD

**Issue by blaster452** [home-assistant/supervisor#3038]
### Describe the issue you are experiencing

After updating to 2021.8.0b2 - home assistant started up fine but I cannot access the Supervisor panel. I get error "Could not load the Supervisor panel!"

Installation type Home Assistant OS.
## System Health

version | core-2021.8.0b2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.53
arch | aarch64
timezone | America/Winnipeg

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 908
Installed Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 31 July 2021, 19:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | beta
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 113.9 GB
disk_used | 18.4 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), AirSonos (3.1.1), File editor (5.3.3), SSH & Web Terminal (9.0.0), IDE (2.2.0), TasmoBackup (1.04.17), Home Assistant Google Drive Backup (0.104.3), ESPHome (1.20.2), Visual Studio Code (3.6.0), ESPHome (dev) (dev), Zigbee2mqtt (1.18.1-1), Bitwarden (Vaultwarden) (0.12.0), Duck DNS (1.13.0), NGINX Home Assistant SSL proxy (3.0.2), Mosquitto broker (6.0.1), WireGuard (0.5.1), Node-RED (9.2.1), Z-Wave JS to MQTT (0.23.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 18
views | 20
mode | storage

</details>

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.10.53

### What version of Home Assistant Core is installed?

2021.8.0b2

### Steps to reproduce the issue

1. Upgraded to the latest beta 2021.8.0b2
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
cant open supervisor panel
```

**Comment by frenck** [comment]
This has been fixed in b3, which is currently building and should be available any moment now. As a workaround downgrade to b1.
