### ISSUE TITLE
Could not load the supervisor panel!

### ISSUE THREAD

**Issue by nickh66** [home-assistant/supervisor#3039]
### Describe the issue you are experiencing

This morning i updated from 2021.08.0b1 to beta2 and after the restart the supervisor panel & all the supervisor addon's don't load. The supervisor panel gives error "could not load the supervisor panel!" and all the individual addons that i choose to add to the sidebar (like snap shots, esphome, nodered, file editor etc) show the same error "Unable to load the panel source: /api/hassio/app/entrypoint.js."

I do have access to my most recent snapshot file that i just now downloaded from my google drive but i can't yet work out the syntax to perform a restore without access to the standard restore feature.  I'm looking for how to do that via the dev tools but no luck yet.

So far i have restarted the core & the host but the issue remains.
![Screenshot 2021-07-30 093714](https://user-images.githubusercontent.com/11672847/127580194-178bcfb4-f90f-419a-8e07-504963e8265a.png)
![Screenshot 2021-07-30 095619](https://user-images.githubusercontent.com/11672847/127580198-061c6ef9-9911-4953-8e34-1d1433c335ed.png)

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.2

### What version of Home Assistant Core is installed?

core-2021.8.0b2

### Steps to reproduce the issue

1. Upgrade to latest OS last night, v6.2 i believe
2. upgrade to latest beta

### Anything in the Supervisor logs that might be useful for us?

```txt
Cant access the logs.
```

**Comment by nickh66** [comment]
Thankfully this is my dev HA instance so i'm not too stressed about this so far.  Ideally if i can restore from backup then that's fine.  For now i'll wait & see if there might be some way to action a restore without having to re-image my SSD first.

**Comment by RaveGun** [comment]
I have the same behaviour as described but on a different installation configuration.

I switched last night to "beta" after reading this tweet: https://twitter.com/Frenck/status/1420499444945104896?s=20

The logs from docker are not showing anything special.

The hassio-supervisor.service is also running.

In don't know if there is a problem with the fact that the containers are mixed from ghcr.io and from docker hub.

**Comment by ludeeus** [comment]
This was fixed in Core 2021.8.0b3
Fix it on your system by running: `ha core update`

**Comment by nickh66** [comment]
Thanks. That worked a treat.
