### ISSUE TITLE
Misconfigured network after reconnecting

### ISSUE THREAD

**Issue by TeoTN** [home-assistant/supervisor#3043]
### Describe the issue you are experiencing

It seems that the way networks are configured, when device gets disconnected from wlan and reconnects, then the virtual network created for home assistant takes precedence as a gateway (has lower metric), resulting in no internet connection.

The solution (workaround?) for me was to manually add (in cron job) route with proper gateway and metric `=0` whenever wifi is reconnected:
```
/usr/sbin/route add -net default gw 192.168.50.1 netmask 0.0.0.0 dev wlan0 metric 0
```

Not sure what should be the proper/idiomatic solution but probably docker network created by home assistant probably should never become the default gateway for network connection.

I've added a few more debug details in the community thread [here](https://community.home-assistant.io/t/networkmanager-gets-connected-to-wifi-but-no-internet/326161/2)

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2021.7.4

### Steps to reproduce the issue

1. Shut down wifi router
2. Restart wifi
3. Wait for network manager to reconnect 
4. Observe that `ping -c4 8.8.8.8` results in `From 169.254.117.211 icmp_seq=1 Destination Host Unreachable`
5. See that `route -n` has the lowest metric value for `veth*` interface rather than `wlan`

### Anything in the Supervisor logs that might be useful for us?

```txt
Not applicable
```

**Comment by TeoTN** [comment]
The issue remains unresolved

**Comment by agners** [comment]
I can't see this behavior on Home Assistant OS, so I assume its somehow related with Debian. I wonder which container`veth5e60ad6` is associated with. Are you running containers besides Supervised/special Add-ons?
