### ISSUE TITLE
'AddonManager.install' blocked from execution, system is not healthy

### ISSUE THREAD

**Issue by aidan1010** [home-assistant/supervisor#3048]
### Describe the issue you are experiencing

Unable to install anything because of this error:
21-08-04 09:19:16 WARNING (MainThread) [supervisor.jobs] 'AddonManager.install' blocked from execution, system is not healthy
This happened after updating the core to version 2021.7.4
Supervisor version: 2021.06.8

I have not made in source code modifications. How do i fix this without a clean install?

### What is the used version of the Supervisor?

2021.06.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

6.2

### What version of Home Assistant Core is installed?

2021.7.4

### Steps to reproduce the issue

trying to install an add-on.

### Anything in the Supervisor logs that might be useful for us?

```txt
21-08-04 08:39:35 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy
21-08-04 09:09:11 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-08-04 09:19:16 WARNING (MainThread) [supervisor.jobs] 'AddonManager.install' blocked from execution, system is not healthy
21-08-04 09:19:31 INFO (MainThread) [supervisor.snapshots] Found 3 snapshot files
21-08-04 09:19:31 INFO (MainThread) [supervisor.snapshots] Found 3 snapshot files
```

**Comment by ludeeus** [comment]
If you go to the System tab, it will tell your what the problem is and how to solve it.

**Comment by aidan1010** [comment]
Yeah, done that, nothing changed. Hence my post here.

**Comment by ludeeus** [comment]
Done what?

**Comment by aidan1010** [comment]
https://www.home-assistant.io/more-info/unhealthy/untrusted

System detected untrusted content

The issue

Home Assistant detected untrusted code. It looks like someone/something tried to inject not signed images or code into your Home Assistant system. But don’t worry, we blocked this action and nothing was applied.

The solution

Please make sure your network is not affected by an intruder and try it again. To reset this status, you need to restart the Supervisor.

**Comment by ludeeus** [comment]
Paste the full log after a restart of the supervisor

**Comment by aidan1010** [comment]
21-08-04 09:31:34 INFO (MainThread) [supervisor.misc.scheduler] Shutting down scheduled tasks
21-08-04 09:31:34 INFO (MainThread) [supervisor.api] Stopping API on 172.30.32.2
21-08-04 09:31:34 INFO (MainThread) [supervisor.hardware.monitor] Stopped Supervisor hardware monitor
21-08-04 09:31:34 INFO (MainThread) [supervisor.core] Supervisor is down - 100
21-08-04 09:31:34 INFO (MainThread) [__main__] Closing Supervisor
21-08-04 07:31:43 INFO (MainThread) [__main__] Initializing Supervisor setup
21-08-04 07:31:44 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
21-08-04 09:31:44 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: raspberrypi3-64
21-08-04 09:31:44 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/aarch64-hassio-supervisor with version 2021.06.8
21-08-04 09:31:44 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-08-04 09:31:44 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
21-08-04 09:31:44 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-08-04 09:31:44 INFO (MainThread) [__main__] Setting up Supervisor
21-08-04 09:31:45 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
21-08-04 09:31:45 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
21-08-04 09:31:48 INFO (MainThread) [supervisor.host.info] Updating local host information
21-08-04 09:31:48 INFO (MainThread) [supervisor.host.services] Updating service information
21-08-04 09:31:49 INFO (MainThread) [supervisor.host.network] Updating local network information
21-08-04 09:31:53 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-08-04 09:31:53 INFO (MainThread) [supervisor.host] Host information reload completed
21-08-04 09:31:53 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
21-08-04 09:31:53 INFO (MainThread) [supervisor.host.services] Reloading local service hassos-apparmor.service
21-08-04 09:31:53 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-dns with version 2021.06.0
21-08-04 09:31:53 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
21-08-04 09:31:53 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-audio with version 2021.04.0
21-08-04 09:31:54 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-cli with version 2021.05.1
21-08-04 09:31:54 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-observer with version 2021.06.0
21-08-04 09:31:54 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-multicast with version 2021.04.0
21-08-04 09:31:54 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-08-04 09:31:58 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 1 Home Assistant secrets
21-08-04 09:31:58 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/raspberrypi3-64-homeassistant with version 2021.7.4
21-08-04 09:31:58 INFO (MainThread) [supervisor.hassos] Detect Home Assistant Operating System 6.2 / BootSlot B
21-08-04 09:32:01 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/cebe7a76 repository
21-08-04 09:32:01 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
21-08-04 09:32:01 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
21-08-04 09:32:04 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 63 new - 0 remove
21-08-04 09:32:04 INFO (MainThread) [supervisor.addons] Found 4 installed add-ons
21-08-04 09:32:04 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-ssh with version 9.1.3
21-08-04 09:32:04 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-samba with version 9.5.1
21-08-04 09:32:04 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-mosquitto with version 6.0.1
21-08-04 09:32:04 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-configurator with version 5.3.1
21-08-04 09:32:04 INFO (MainThread) [supervisor.snapshots] Found 3 snapshot files
21-08-04 09:32:04 INFO (MainThread) [supervisor.discovery] Loaded 1 messages
21-08-04 09:32:04 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
21-08-04 09:32:04 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-08-04 09:32:04 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-08-04 09:32:04 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-08-04 09:32:05 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-08-04 09:32:05 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
21-08-04 09:32:05 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-08-04 09:32:05 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-08-04 09:32:05 INFO (MainThread) [__main__] Running Supervisor
21-08-04 09:32:06 INFO (MainThread) [supervisor.hassos] Rauc: B - marked slot kernel.1 as good
21-08-04 09:32:06 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
21-08-04 09:32:06 INFO (MainThread) [supervisor.core] Supervisor reboot detected
21-08-04 09:32:06 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
21-08-04 09:32:10 INFO (MainThread) [supervisor.core] Supervisor is up and running
21-08-04 09:32:10 INFO (MainThread) [supervisor.host.info] Updating local host information
21-08-04 09:32:10 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-08-04 09:32:10 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-08-04 09:32:10 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-08-04 09:32:10 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-08-04 09:32:11 INFO (MainThread) [supervisor.host.services] Updating service information
21-08-04 09:32:11 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-08-04 09:32:11 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-08-04 09:32:11 INFO (MainThread) [supervisor.host.network] Updating local network information
21-08-04 09:32:16 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-08-04 09:32:16 INFO (MainThread) [supervisor.host] Host information reload completed
21-08-04 09:32:16 WARNING (MainThread) [supervisor.resolution.evaluations.base] System detect unauthorized source code modifications. (more-info: https://www.home-assistant.io/more-info/unsupported/source_mods)
21-08-04 09:32:16 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-08-04 09:32:16 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy

**Comment by ludeeus** [comment]
That is not the same as you posted.
You only get that one if someone/something has changed the supervisor code.

**Comment by aidan1010** [comment]
Okay, so the update changed the code, and now i have issues. How do i roll back the update, if that is even possible.

**Comment by ludeeus** [comment]
Updating the core does not change anything, and the core container itself does not have enough rights to change files inside the supervisor container.
Changing that requires physical access to the host, or an add-on with docker access.

**Comment by aidan1010** [comment]
Okay. I understand. So how do I fix this, as it's not letting me install anything.

**Comment by ludeeus** [comment]
Revert the change made inside the supervisor container and restart it

**Comment by aidan1010** [comment]
But i did not make any changes inside the supervisor container?

**Comment by pvizeli** [comment]
Then you should complete delete everything and start from scratch. Somethings hacked your system and modify code
