### ISSUE TITLE
Your installation is unhealthy

### ISSUE THREAD

**Issue by Haarolean** [home-assistant/supervisor#3067]
### Describe the issue you are experiencing

I just installed hassio-supervised via [supervised-installer](https://github.com/home-assistant/supervised-installer) and I already keep getting this:

![image](https://user-images.githubusercontent.com/1494347/130298915-c04755c9-0fa2-4a9e-aedb-6155e7112030.png)
```
$ docker ps -a | grep superv
624260f192dd   homeassistant/aarch64-hassio-supervisor                         "/init"                  31 minutes ago   Up 31 minutes                                           hassio_supervisor
```
```
$ docker inspect --format='{{.HostConfig.Privileged}}' 624
true
```

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

buster

### What version of Home Assistant Core is installed?

core-2021.8.8

### Steps to reproduce the issue

1. install it via the script
2. install HA (create an account)
3. profit

### Anything in the Supervisor logs that might be useful for us?

```txt
21-08-21 01:19:38 CRITICAL (MainThread) [supervisor.hardware.monitor] Not privileged to run udev monitor!
```

**Comment by ikifar2012** [comment]
Isn't this installed on a dedicated HA VM/server?

**Comment by Haarolean** [comment]
No it's not.

**Comment by ikifar2012** [comment]
Then you are in an unsupported config (https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md), we don't know what else is running on your computer and may have messed with udev, try running `ha su repair`, if that doesn't work you WILL have to reboot and keep in mind that you will need to upgrade to Debian Bullseye soon as we are going to stop supporting it soon

**Comment by Haarolean** [comment]
It's *supposed* to run other stuff in the future but atm it's a clean install.

I even keep getting the other red sign about supervisor not being priveleged.

So far I have:
1) let your "supervisor" (which can't even do its job) spread like a plague all across OS' FS (HA was supposed to be a run as a container, sigh)
2) changed the distro because SUDDENLY you decided that ubuntu (which is direct derivative from debian) is no more supported.

And now you even want a dedicated device. What next?

**Comment by ikifar2012** [comment]
If you don't like the supervisor taking control of your OS I highly recommend you switch to a Docker based install (https://www.home-assistant.io/installation/linux#install-home-assistant-container). 

The end goal of the supervisor is to make installing and maintaining home assistant as easy as possible for the average person, the supervisor is supposed to take care of everything so you don't have to think about it 



> And now you even want a dedicated device. What next?

What's next is the OS Agent:
https://github.com/home-assistant/os-agent

and 

An easy to install deb package for the supervisor:
https://developers.home-assistant.io/blog/2021/08/24/supervisor_update/#supervised-installation

**Comment by initd0** [comment]
I had this as well, running Ubuntu 20.04. Everything was fine until i upgraded to supervisor-2021.09.0 today, and even after many reboots, it would constantly give me that message.  This time though i rebooted via HASS and the message seems to have gone away.

Not sure why you guys keep saying Ubuntu is unsupported if its directly related to Debian. There are probably more HASS installations running on Ubuntu out there than Debian.

**Comment by Haarolean** [comment]
> If you don't like the supervisor taking control of your OS I highly recommend you switch to a Docker based install (https://www.home-assistant.io/installation/linux#install-home-assistant-container).
> 
> The end goal of the supervisor is to make installing and maintaining home assistant as easy as possible for the average person, the supervisor is supposed to take care of everything so you don't have to think about it
> 
> > And now you even want a dedicated device. What next?
> 
> What's next is the OS Agent:
> https://github.com/home-assistant/os-agent
> 
> and
> 
> An easy to install deb package for the supervisor:
> https://developers.home-assistant.io/blog/2021/08/24/supervisor_update/#supervised-installation

I see this is going the wrong way. I reported an issue and you're trying to impose upon installing more garbage on my host machine.

I respect the efforts trying to help, but I'd better wait for a reply from HA maintainers and will refrain from taking any advices from random people hijacking the thread, thanks.

**Comment by Haarolean** [comment]
> I had this as well, running Ubuntu 20.04. Everything was fine until i upgraded to supervisor-2021.09.0 today, and even after many reboots, it would constantly give me that message. This time though i rebooted via HASS and the message seems to have gone away.
> 
> Not sure why you guys keep saying Ubuntu is unsupported if its directly related to Debian. There are probably more HASS installations running on Ubuntu out there than Debian.

yep, originally same issue here. Was getting these both red messages on ubuntu. 
I'm struggling as well in finding the logic in their actions.
This supervisor was intended to keep things easier and it can't even do its job. Can't update the HA, it doesn't keep the plugins on with a watchdog, doesn't restart containers, yada yada

**Comment by ludeeus** [comment]
If the dbus service is running, check that your environment meets the requirements <https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#supported-operating-system-system-dependencies-and-versions>

If it does paste the output of `ha host info` `ha info` and `ha su info`

**Comment by initd0** [comment]
My response to OP was not off-topic so not sure why you marked it as such.

@Haarolean are you still experiencing the issue?
