### ISSUE TITLE
Loading log files of add-ons stopped working since updating to 2021.6

### ISSUE THREAD

**Issue by wauswaus** [home-assistant/supervisor#3076]
### The problem

When I navigate to the dashboard page in the supervisor, click on an installed add-on and select the logs tab, nothing showns anymore.
Also, when navigating to supervisor -> system and I select a log from the dropdown list, it takes up to 10s before it shows the selected log.

In the supervisor log I come across error log entries like:
`2021-06-22 16:44:34 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/a0d7b954_bitwarden/stats request
2021-06-22 16:44:34 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/a0d7b954_bitwarden/stats - 
2021-06-22 16:44:45 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /core/stats request
2021-06-22 16:44:45 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /core/stats - 
2021-06-22 16:44:45 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /supervisor/stats request
2021-06-22 16:44:45 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /supervisor/stats - `

I don't know exactly what 2021.6 update started causing this

### What is version of Home Assistant Core has the issue?

2021.6.6

### What was the last working version of Home Assistant Core?

2021.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

- Home Assistant Supervisor

**Comment by frenck** [comment]
This issue was created in an incorrect repository, I've moved the issues to the Supervisor repo.

**Comment by carsten-h** [comment]
> This issue was created in an incorrect repository, I've moved the issues to the Supervisor repo.

This seems to be the same issue as mine: https://github.com/home-assistant/supervisor/issues/3014

But there is no solution for this. It seems there are only two persons in the world that have it. :-(

**Comment by wauswaus** [comment]
For me the issue is completely back after doing a fresh install and restoring a backup

**Comment by bschatzow** [comment]
I have the same issue.  Pi4 4G Debian 11. First saw this after updating Agent to 1.1

**Comment by darksid3r** [comment]
I am having the same issue. Things I have tried:
1. Restore from backup.
2. Move to a different SSD setup. Install from scratch, restore snapshot. This seems to have alleviated the problem for a while, but now it is back.
I'm running Hassos on a raspberry pi 4 4GB. The Rpi resources do not seem to be the problem as running "ha core logs" on CLI makes little difference, with CPU / memory normal. 
What is really strange is that I am connecting via SSH to the host machine, when running "ha core logs", after a long time I get:
"Get "http://supervisor/core/logs": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**Comment by Veldkornet** [comment]
Follow [these](https://forums.raspberrypi.com/viewtopic.php?f=28&t=245931) steps to disable UAS, it's helped everyone who's tried it [here](https://community.home-assistant.io/t/supervisor-logs-extremely-slow-to-open/344375/19)

**Comment by RiderCrazy** [comment]
> Follow [these](https://forums.raspberrypi.com/viewtopic.php?f=28&t=245931) steps to disable UAS, it's helped everyone who's tried it [here](https://community.home-assistant.io/t/supervisor-logs-extremely-slow-to-open/344375/19)
Thanks !!

Sounds it solves the issue.
FYI my SSD is a Samsung T5 on RPI4. Struggle with that issue for a few weeks, works like a charm after a reboot (can access addon log)

**Comment by carsten-h** [comment]
> Follow [these](https://forums.raspberrypi.com/viewtopic.php?f=28&t=245931) steps to disable UAS, it's helped everyone who's tried it [here](https://community.home-assistant.io/t/supervisor-logs-extremely-slow-to-open/344375/19)

How did you edit the /boot/cmdline.txt? Is it possible from Home Assistant? Or can I edit it with my Mac?

**Comment by RiderCrazy** [comment]
> > Follow [these](https://forums.raspberrypi.com/viewtopic.php?f=28&t=245931) steps to disable UAS, it's helped everyone who's tried it [here](https://community.home-assistant.io/t/supervisor-logs-extremely-slow-to-open/344375/19)
> 
> How did you edit the /boot/cmdline.txt? Is it possible from Home Assistant? Or can I edit it with my Mac?

Stop rpi, remove you ssd, connect it on your pc/mac, open cmdline.txt, reconnect, power rpi, enjoy

**Comment by darksid3r** [comment]
Confirmed to be working so far, logs seem to instantly load now. Also tested SSD speed. Results:
With UAS enabled :  183178 kB/s
With UAS disabled:  199516 kB/s

**Comment by carsten-h** [comment]
> Stop rpi, remove you ssd, connect it on your pc/mac, open cmdline.txt, reconnect, power rpi, enjoy

That is too easy. :-)
And it works!

**Thank you very much! It was really annoying before!**

**Comment by RiderCrazy** [comment]
> > Stop rpi, remove you ssd, connect it on your pc/mac, open cmdline.txt, reconnect, power rpi, enjoy
> 
> That is too easy. :-) And it works!
> 
> **Thank you very much! It was really annoying before!**

Well, thanks at @Veldkornet for leading the way ;)

**Comment by carsten-h** [comment]
> Well, thanks at @Veldkornet for leading the way ;)

Yes correct!

**Comment by wauswaus** [comment]
How do I get the VID and PID of the SSD?

**Comment by wauswaus** [comment]
For all future readers, this is not a Home Assistant problem, but a hardware issue where the USB to SATA convertor does not implemented UAS correctly. When UAS is disabled on Home Assistant OS there are no issues anymore.
Steps to do this in Home Assistant: https://community.home-assistant.io/t/supervisor-logs-extremely-slow-to-open/344375/22

**Comment by carsten-h** [comment]
> this is not a Home Assistant problem, but a hardware issue where the USB to SATA convertor does not implemented UAS correctly. When UAS is disabled on Home Assistant OS there are no issues anymore.

No, this **IS** an Home Assistant problem!
With earlier version of Home Assistant OS 5.x (I think it was until 5.5 where it worked) there has been no problem. This problem was introduced by a newer Home Assistant OS version!
I have not changed anything with the USB SATA bridge since using it together with Home Assistant.
