### ISSUE TITLE
Trying to install add-ons fails with an error apparently relating to a time-out

### ISSUE THREAD

**Issue by felurx** [home-assistant/supervisor#3081]
### Describe the issue you are experiencing

When I try to install any add-ons from the "Add-on Store", the "Install" button remains on the loading animation. After a few seconds, there is a pop-up with an error message:
`
 Can't install homeassistant/aarch64-addon-ssh:9.1.3: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=9.1.3&fromImage=homeassistant%2Faarch64-addon-ssh: Internal Server Error ("error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"") 
`

The error also shows up in the logs. If I switch to another page, the error still shows up in the logs, but there is no pop-up.
My installation is a fresh install of the image linked on the install pages for RasPi 3 64bit.

### What is the used version of the Supervisor?

supervisor-2021.06.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.2

### What version of Home Assistant Core is installed?

core-2021.8.8

### Steps to reproduce the issue

0. (Install Home Assistant OS by flashing the Pi3 image on an SD card, inserting it and going through the onboarding process.)
1. Go to Supervisor -> Add-On Store, choose any add-on.
2. Click "Install".
3. Wait.
4. ???
5. Not Profit, look at pop-up. 

### Anything in the Supervisor logs that might be useful for us?

```txt
`
21-08-27 11:07:19 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/core_ssh
21-08-27 11:07:19 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-ssh with tag 9.1.3.
21-08-27 11:08:21 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install homeassistant/aarch64-addon-ssh:9.1.3: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=9.1.3&fromImage=homeassistant%2Faarch64-addon-ssh: Internal Server Error ("error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"")
21-08-27 11:19:08 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image esphome/esphome-hassio-aarch64 with tag 2021.8.2.
21-08-27 11:20:10 ERROR (SyncWorker_4) [supervisor.docker.interface] Can't install esphome/esphome-hassio-aarch64:2021.8.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2021.8.2&fromImage=esphome%2Fesphome-hassio-aarch64: Internal Server Error ("error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"")
`
```

### Additional information

Here a screenshot of the pop-up:
![image](https://user-images.githubusercontent.com/22506886/131104238-03f97f1f-bb8a-4ac8-96c3-e5da86a0e8d8.png)

Please note that this is an duplicate of #1933. I opened a new issue because it went stale and was closed, and because I wanted to provide all info.

If there is anything else I should provide or try I'd be glad if you told me so I can do that. Thank you very much in advance for your time.

**Comment by bigcspecv** [comment]
Update: For no aparent reason I am getting this error again today on my Armbian HA install. I will do some diagnostics and report back what I find.

**Comment by bigcspecv** [comment]
It appears that net.ipv4.tcp_mtu_probing defaulted back to 0. I added `net.ipv4.tcp_mtu_probing=1` to `/etc/sysctl.conf` and it appears to be working again.
