### ISSUE TITLE
Deletion of backups don't work

### ISSUE THREAD

**Issue by bussio** [home-assistant/supervisor#3085]
### Describe the issue you are experiencing

In the latest version core-2021.9.0b3 the deletion of individual backups no longer works under Supervisor/Backups.

### What is the used version of the Supervisor?

supervisor-2021.08.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Home Assistant OS 6.2

### What version of Home Assistant Core is installed?

core-2021.9.0b3

### Steps to reproduce the issue

1. The deletion of individual backups no longer works under Supervisor/Backups.

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:221 
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 14:25:20 (2 occurrences) 
Last logged: 14:26:11

/backups/0e5689df/remove return code 404


Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:109 
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 14:25:20 (2 occurrences) 
Last logged: 14:26:11

Failed to to call /backups/0e5689df/remove -
```

**Comment by ludeeus** [comment]
This was fixed in #3083 :+1:
