### ISSUE TITLE
Unable to open addon page: Error while loading page addon

### ISSUE THREAD

**Issue by RemCom** [home-assistant/supervisor#3089]
### Describe the issue you are experiencing

The installed addons and in the addon store if you click on a addon you get: Error while loading page addon. This issue appeared after de update to 2021.08.1

### What is the used version of the Supervisor?

supervisor-2021.08.1

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 11 

### What version of Home Assistant Core is installed?

core-2021.9.0b4

### Steps to reproduce the issue

1. Go to supervisor
2. Go to Dashboard or addon store
3. Click a addon

### Anything in the Supervisor logs that might be useful for us?

```txt
No errors or useful information visible
```

**Comment by ludeeus** [comment]
Clear your browser cache and it should work normally after.

**Comment by RemCom** [comment]
That fixes it. didn't try that. Thnx @ludeeus
