### ISSUE TITLE
addons pages won't load (404)

### ISSUE THREAD

**Issue by fishbone-git** [home-assistant/supervisor#3091]
### Describe the issue you are experiencing

Cannot load addon webui's or any config pages after the latest supervisor update.  I use an HA Blue, but accessing from a Unbuntu laptop with Chrome. Mobile app seems to still load ok.

### What is the used version of the Supervisor?

2021-08-1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.2

### What version of Home Assistant Core is installed?

2021.9.0b6

### Steps to reproduce the issue

1. Go into supervisor dashboard.
2.Try to get to addon config, eg Node Red, InfluDB etc
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-08-31 00:51:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-08-31 00:51:51 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
21-08-31 00:51:51 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
21-08-31 00:51:51 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
21-08-31 00:51:51 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
21-08-31 00:51:51 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-08-31 00:51:52 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-08-31 00:51:52 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
21-08-31 00:51:54 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-08-31 00:51:55 WARNING (MainThread) [supervisor.dbus.network] Can't process /org/freedesktop/NetworkManager/Devices/41: Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/Devices/41
```

### Additional information

Chrome console log (seems to be a 404)

entrypoint.7ca7c83a.js:5527 GET http://homeassistant.local:8123/api/hassio/app/frontend_latest/f2ea8216.js net::ERR_ABORTED 404 (Not Found)
s.l @ entrypoint.7ca7c83a.js:5527
s.f.j @ entrypoint.7ca7c83a.js:5527
(anonymous) @ entrypoint.7ca7c83a.js:5527
s.e @ entrypoint.7ca7c83a.js:5527
load @ entrypoint.7ca7c83a.js:2734
value @ entrypoint.7ca7c83a.js:5032
performUpdate @ entrypoint.7ca7c83a.js:2794
Πq @ entrypoint.7ca7c83a.js:2794
async function (async)
Πq @ entrypoint.7ca7c83a.js:2794
requestUpdate @ entrypoint.7ca7c83a.js:2794
set @ entrypoint.7ca7c83a.js:2794
W @ entrypoint.7ca7c83a.js:4181
I @ entrypoint.7ca7c83a.js:4181
v @ entrypoint.7ca7c83a.js:4181
_ @ entrypoint.7ca7c83a.js:4181
I @ entrypoint.7ca7c83a.js:4181
O @ entrypoint.7ca7c83a.js:4181
update @ entrypoint.7ca7c83a.js:4181
performUpdate @ entrypoint.7ca7c83a.js:2794
Πq @ entrypoint.7ca7c83a.js:2794
async function (async)
Πq @ entrypoint.7ca7c83a.js:2794
requestUpdate @ entrypoint.7ca7c83a.js:2794
set @ entrypoint.7ca7c83a.js:2794
(anonymous) @ custom-panel.b37826f4.js:1348
(anonymous) @ custom-panel.b37826f4.js:1348
p @ custom-panel.b37826f4.js:1348
value @ 6da8e7d0.js:1
performUpdate @ app.f08a72d3.js:1
_$EC @ app.f08a72d3.js:1
async function (async)
_$EC @ app.f08a72d3.js:1
requestUpdate @ app.f08a72d3.js:1
set @ app.f08a72d3.js:1
value @ app.f08a72d3.js:35925
value @ app.f08a72d3.js:29560
performUpdate @ app.f08a72d3.js:1
_$EC @ app.f08a72d3.js:1
async function (async)
_$EC @ app.f08a72d3.js:1
requestUpdate @ app.f08a72d3.js:1
set @ app.f08a72d3.js:1
P @ app.f08a72d3.js:5264
_$AI @ app.f08a72d3.js:5264
m @ app.f08a72d3.js:5264
T @ app.f08a72d3.js:5264
_$AI @ app.f08a72d3.js:5264
O @ app.f08a72d3.js:5264
update @ app.f08a72d3.js:5264
performUpdate @ app.f08a72d3.js:1
_$EC @ app.f08a72d3.js:1
async function (async)
_$EC @ app.f08a72d3.js:1
requestUpdate @ app.f08a72d3.js:1
set @ app.f08a72d3.js:1
P @ app.f08a72d3.js:5264
_$AI @ app.f08a72d3.js:5264
m @ app.f08a72d3.js:5264
T @ app.f08a72d3.js:5264
_$AI @ app.f08a72d3.js:5264
O @ app.f08a72d3.js:5264
update @ app.f08a72d3.js:5264
performUpdate @ app.f08a72d3.js:1
_$EC @ app.f08a72d3.js:1
async function (async)
_$EC @ app.f08a72d3.js:1
requestUpdate @ app.f08a72d3.js:1
set @ app.f08a72d3.js:1
t @ app.f08a72d3.js:36741
(anonymous) @ app.f08a72d3.js:36741
r @ entrypoint.7ca7c83a.js:4181
n @ entrypoint.7ca7c83a.js:4181
value @ entrypoint.7ca7c83a.js:1177
handleEvent @ entrypoint.7ca7c83a.js:4181
entrypoint.7ca7c83a.js:5032 Error loading page addon ChunkLoadError: Loading chunk 841 failed.
(error: http://homeassistant.local:8123/api/hassio/app/frontend_latest/f2ea8216.js)
    at Object.s.f.j (entrypoint.7ca7c83a.js:5527)
    at entrypoint.7ca7c83a.js:5527
    at Array.reduce (<anonymous>)
    at Function.s.e (entrypoint.7ca7c83a.js:5527)
    at Object.load (entrypoint.7ca7c83a.js:2734)
    at HTMLElement.value (entrypoint.7ca7c83a.js:5032)
    at HTMLElement.performUpdate (entrypoint.7ca7c83a.js:2794)
    at HTMLElement.Πq (entrypoint.7ca7c83a.js:2794)

**Comment by fishbone-git** [comment]
oddly, rebooting laptop cleared the issue (for now at least). I'll leave open in case there is something to be learned from the console data.  Feel free to close if not.

**Comment by ludeeus** [comment]
It's requesting old files for some reason, restarting or clearing browser cache solves that.
