### ISSUE TITLE
Error with 2021.08.1 Timeout while processing CodeNotary

### ISSUE THREAD

**Issue by Salvora** [home-assistant/supervisor#3098]
### Describe the issue you are experiencing

I am getting 2 types of errors on the supervisor logs constantly specifically after restarting HA.

### What is the used version of the Supervisor?

supervisor-2021.08.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.2

### What version of Home Assistant Core is installed?

core-2021.9.0

### Steps to reproduce the issue

1. Restart Host or Core
2. Errors are printed on the supervisor logs.

### Anything in the Supervisor logs that might be useful for us?

```txt
21-09-02 02:33:26 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-09-02 02:33:56 ERROR (MainThread) [supervisor.homeassistant.api] Error on call https://172.30.32.1:8123/api/config: 
21-09-02 02:34:32 ERROR (MainThread) [supervisor.homeassistant.api] Error on call https://172.30.32.1:8123/api/config:
.
.
.
.
.
21-09-02 02:35:34 INFO (MainThread) [supervisor.api.backups] Downloading backup 7a10ddf5
21-09-02 02:35:38 INFO (MainThread) [supervisor.api.middleware.security] /dns/info access from a0d7b954_nginxproxymanager
21-09-02 02:35:44 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
21-09-02 02:35:53 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-09-02 02:35:53 INFO (MainThread) [supervisor.host.manager] Host information reload completed
21-09-02 02:35:54 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
21-09-02 02:36:04 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
21-09-02 02:36:14 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
21-09-02 02:36:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
21-09-02 02:36:24 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
21-09-02 02:36:24 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
.
.
.
.
.
.
21-09-02 02:55:03 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2918' coro=<HomeAssistantWebSocket.async_send_command() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:106> exception=TypeError('Received message 257:None is not str')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 134, in async_send_command
    return await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 46, in async_send_command
    response = await self.client.receive_json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 291, in receive_json
    data = await self.receive_str(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 276, in receive_str
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not str")
TypeError: Received message 257:None is not str
```

### Additional information
I am not sure what they do so I would like to report them just in case.
_No response_

**Comment by ludeeus** [comment]
The first one is expected, it can't reach HA while it's restarting.

The second one (codenotary) that can happen if codenotary has issues or when you have network issues.
Codenotary is used to validate the integrity of our data files and images <https://www.home-assistant.io/blog/2021/05/05/release-20215/#docker-images-now-signed-and-available-on-the-github-container-registry>

Unless that issue persists, there is no need to worry about it.

**Comment by Salvora** [comment]
@ludeeus thanks for the explanation. Then the third one error should also be the result of the internet connection loss and this is not an issue at all. It is just that when users like me who is not really knowledgeable see these errors and warnings when there is actually no issue, panic  takes over. If the error printed like this, "Error on call https://172.30.32.1:8123/api/config: Home Assistant is not available" or something along those lines like "Cannot connect to the remote codenotary server to validate the integrity of files.", it would have been much better :). If there is nothing else, we can close this issue.
