### ISSUE TITLE
Translation Error: The intl string context variable "naam" was not provided to the string "Back-up maken van {naam}"

### ISSUE THREAD

**Issue by NetWitch** [home-assistant/supervisor#3115]
### Describe the issue you are experiencing

In the Dutch version, whenever I update this error pops up in the text of the popup. Has happened since the last two or three updates. Does not seem to have any consequences for updating, just annoying.

### What is the used version of the Supervisor?

supervisor-2021.09.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 6.3

### What version of Home Assistant Core is installed?

core-2021.9.5

### Steps to reproduce the issue

1. Switch to Dutch translation
2. Update to core-2021.9.5
3. Error is in the popup

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

**Comment by ludeeus** [comment]
This is not a bug in the supervisor, someone has translated wrong
We use localize for translations, you can join the frontend team here to correct it <https://developers.home-assistant.io/docs/translations> or wait for someone else to correct that translation
