### ISSUE TITLE
[supervisor.docker.addon] keeps reloading / removing (while addon is not installed anymore)

### ISSUE THREAD

**Issue by p3tAbyte** [home-assistant/supervisor#3119]
### Describe the issue you are experiencing

Hi,

I've found this in my logs;

21-09-13 15:09:07 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_bitwarden!
21-09-13 15:09:07 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_a0d7b954_bitwarden application
21-09-13 15:09:10 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/bitwarden/armv7 with version 0.13.0
21-09-13 15:09:40 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_bitwarden!
21-09-13 15:09:40 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_a0d7b954_bitwarden application
21-09-13 15:09:43 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/bitwarden/armv7 with version 0.13.0
21-09-13 15:09:43 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-09-13 15:10:13 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_bitwarden!
21-09-13 15:10:13 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_a0d7b954_bitwarden application
21-09-13 15:10:15 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/bitwarden/armv7 with version 0.13.0
21-09-13 15:10:46 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_bitwarden!
21-09-13 15:10:46 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_a0d7b954_bitwarden application
21-09-13 15:10:48 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/bitwarden/armv7 with version 0.13.0
21-09-13 15:11:18 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_bitwarden!
21-09-13 15:11:19 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_a0d7b954_bitwarden application
21-09-13 15:11:25 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/bitwarden/armv7 with version 0.13.0

### What is the used version of the Supervisor?

supervisor-2021.09.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Home Assistant OS 6.4

### What version of Home Assistant Core is installed?

core-2021.9.6

### Steps to reproduce the issue

Don't know... it's just there

### Anything in the Supervisor logs that might be useful for us?

```txt
21-09-13 15:12:28 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_bitwarden!
21-09-13 15:12:28 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_a0d7b954_bitwarden application
21-09-13 15:12:30 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/bitwarden/armv7 with version 0.13.0
21-09-13 15:13:00 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_bitwarden!
21-09-13 15:13:01 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_a0d7b954_bitwarden application
21-09-13 15:13:03 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/bitwarden/armv7 with version 0.13.0
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-09-13 15:13:06 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-09-13 15:13:33 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_bitwarden!
21-09-13 15:13:33 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_a0d7b954_bitwarden application
21-09-13 15:13:36 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/bitwarden/armv7 with version 0.13.0
```

**Comment by ludeeus** [comment]
post a screenshot of the "Dashboard" tab, and the output of `ha su info`

**Comment by p3tAbyte** [comment]
Dangit... had a different addon than the official one... my bad
