### ISSUE TITLE
Supervisor error after update

### ISSUE THREAD

**Issue by tescophil** [home-assistant/supervisor#3126]
### Describe the issue you are experiencing

Supervisor throws error after update

### What is the used version of the Supervisor?

supervisor-2021.09.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 6.4

### What version of Home Assistant Core is installed?

core-2021.9.6

### Steps to reproduce the issue

1. Run a core / supervisor / OS update
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-5757' coro=<HomeAssistantWebSocket.async_supervisor_update_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:138> exception=TypeError('Received message 257:None is not str')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 143, in async_supervisor_update_event
    await self.async_send_command(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 134, in async_send_command
    return await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 46, in async_send_command
    response = await self.client.receive_json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 291, in receive_json
    data = await self.receive_str(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 276, in receive_str
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not str")
TypeError: Received message 257:None is not str
```
```


### Additional information

_No response_

**Comment by johanudden** [comment]
I have the same problem after I upgraded. Does it help to reinstall from the beginning and load a back up or is it just waiting for a fix?

**Comment by ludeeus** [comment]
Ignore and wait
Reinstalling does not help at all, so don't do that

**Comment by wallaroo** [comment]
i have similar issue: https://github.com/home-assistant/core/issues/55810#issuecomment-929543464

**Comment by ludeeus** [comment]
That is not relevant or similar @wallaroo
