### ISSUE TITLE
can't restore esphome add-on from backup

### ISSUE THREAD

**Issue by paulius2k** [home-assistant/supervisor#3143]
### Describe the issue you are experiencing

When updating the esphome add-on to a new version 2021.9.1, I made a backup of it as suggested by the Supervisor.

I am attempting to restore that backup (2021.8.2), but process fails, see logs.

PS: I can successfully restore other addon (e.g. Terminal & SSH "core-ssh").

### What is the used version of the Supervisor?

supervisor-2021.09.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.4

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

1. Update ESPHOME addon via the Supervisor Dashboard.
2. Supervisor suggests to make a backup of the old esphome version. Choose yes.
3. Try to restore the backup via Supervisor Backups.
4. Get error in Supervisor System logs
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-09-24 14:35:20 INFO (MainThread) [supervisor.addons.addon] Restore config for addon a0d7b954_esphome
21-09-24 14:35:20 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon a0d7b954_esphome
21-09-24 14:35:20 ERROR (MainThread) [supervisor.jobs] Unhandled exception: [Errno 2] No such file or directory: '/data/tmp/tmpxzszliap/data'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 358, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 853, in restore
    await self.sys_run_in_executor(_restore_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 847, in _restore_data
    shutil.copytree(Path(temp, "data"), self.path_data, symlinks=True)
  File "/usr/local/lib/python3.9/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/data/tmp/tmpxzszliap/data'
21-09-24 14:35:20 WARNING (MainThread) [supervisor.backups.backup] Can't restore Add-on a0d7b954_esphome: 
21-09-24 14:35:20 INFO (MainThread) [supervisor.backups.manager] Partial-Restore 59101d40 done
```
```


### Additional information

In the Supervisor Dashboard esphome does show with an older version:
```
ESPHome 2021.9.1 is available
You are currently running version 2021.8.2
```
but when trying to start the service, it throws error: 
```
Failed to start add-on
Unknown error, see supervisor
```

**Comment by ludeeus** [comment]
Please report that to the author of that add-on. Thanks :+1:
