### ISSUE TITLE
Just upgraded Buster to Bulleye. Supervisor still shows Debian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by jsiemek** [home-assistant/supervisor#3144]
### Describe the issue you are experiencing

I' just upgraded Debian Buster to Bullseye.

```

$ cat /etc/debian_version
11.0
$ uname -a
Linux ha 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
$ sudo lsb_release  -a
No LSB modules are available.
Distributor ID:Debian
Description:Debian GNU/Linux 11 (bullseye)
Release:11
Codename:bullseye
````

But in supervisor panel/ system tab it still shows:
Operating System Debian GNU/Linux 10 (buster) 

### What is the used version of the Supervisor?

supervisor-2021.09.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

11

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

1. Successfully upgrade to Bullseye
2. Check OS version in supervisor panel/system tab
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

**Comment by ludeeus** [comment]
Reboot the server after upgrading it

**Comment by jsiemek** [comment]
Running kernel version 5.10.0-8-amd64 strongly suggest thst I already did it.

**Comment by ludeeus** [comment]
supervisor not populated with new info strongly suggest otherwise

**Comment by jsiemek** [comment]
It's even more funny, after second reboot:
![sv1](https://user-images.githubusercontent.com/36767404/134700410-05d167b7-5348-4ff7-9049-9d3159e8d6be.png)
![sv2](https://user-images.githubusercontent.com/36767404/134700466-e891c237-b173-487c-b2e7-01a86eccd308.png)

but still:

**Comment by ludeeus** [comment]
Clear browser cache
