### ISSUE TITLE
Use new format for logging exceptions

### ISSUE THREAD

**Issue by ludeeus** [home-assistant/supervisor#3156]
A while back we changed the base exception that is used in the supervisor to allow for passing a log handler.
When doing this the exception will print the log entry and have the context of the message.

This is great for API clients like our UI and CLI, since that message will also be returned to the client, instead of the generic "Unknown error, see supervisor log."

Several places have already been converted to the new format, but there are still some places left to migrate to this new format.

This applies to situations where the code raises an exception right after logging it.

Example of old format:

```python
_LOGGER.warning("The reason %s is not active", reason)
raise ResolutionError()
```

Example with the new format:

```python
raise ResolutionError(f"The reason {reason} is not active", _LOGGER.warning)
```

If you during this year's hacktoberfest want to help out migrating the remaining places, please keep the PR contained to a single file.

This new format can only be used for our custom exceptions that are defined in [./supervisor/exceptions.py](./supervisor/exceptions.py)

**Comment by F1nnM** [comment]
Hi, I'd like to work on this issue. As far as I can see, only one file (resolution/module.py) using the old format is left. Would you assign me to this issue?
I will submit my PR on the 1st of October, so that it counts for Hacktoberfest.

**Comment by ludeeus** [comment]
Those exact lines is from that file, that is correct, it was used as an example, but there are many similar structures that should be changed.

No reason to assign anyone to this, that will limit the people that want to help with it.

**Comment by F1nnM** [comment]
I couldn't find any other ResolutionErrors, so I assume it extends to all kinds of errors then?

**Comment by ludeeus** [comment]
That is correct, anywhere when an empty exception is raised after logging

**Comment by balamurugan1603** [comment]
> That is correct, anywhere when an empty exception is raised after logging

yes. I can see many such files. I would also like to contribute. So, we have to change wherever _LOGGER.warning(...) and raise(...) are used simultaneously to raise(...) ryt?

**Comment by ludeeus** [comment]
```python
_LOGGER.xxxxxx("logged text with %". variable)
raise SomeExceptionError()
```
Anything that looks like that, should be changed to:
```python
raise SomeExceptionError(f"logged text with {variable}", _LOGGER.xxxxxx)
```

- The "xxxxxx" after `_LOGGER` can be "warning", "error" or "critical".
- There can also be a ` from None` or ` from err` after the raise line
- The logged message does not need to contain variables, but if it does that should change from lazy format `("text  %s", variable)` to formated string `f"text {variable}"` for the exception argument.
- When we add text to the exception, we also add the log handler that should be used to log it as a second argument to that exception.

**Comment by balamurugan1603** [comment]
Fine. Got it.

**Comment by ludeeus** [comment]
If you need help with that, please reach out on discord.

**Comment by F1nnM** [comment]
To help everyone out a little:
Files containing the old pattern can be found with the linux-command: `grep -HrPzl 'LOGGER[^\n]*\s+raise' .`
The following files currently contain the pattern:
```
./supervisor/addons/addon.py
./supervisor/addons/__init__.py
./supervisor/api/ingress.py
./supervisor/api/middleware/security.py
./supervisor/api/proxy.py
./supervisor/auth.py
./supervisor/dbus/network/__init__.py
./supervisor/discovery/__init__.py
./supervisor/docker/addon.py
./supervisor/docker/interface.py
./supervisor/docker/network.py
./supervisor/docker/supervisor.py
./supervisor/docker/__init__.py
./supervisor/homeassistant/api.py
./supervisor/host/apparmor.py
./supervisor/host/info.py
./supervisor/host/network.py
./supervisor/host/services.py
./supervisor/host/sound.py
./supervisor/plugins/audio.py
./supervisor/plugins/cli.py
./supervisor/plugins/dns.py
./supervisor/plugins/multicast.py
./supervisor/plugins/observer.py
./supervisor/resolution/module.py
./supervisor/services/modules/mqtt.py
./supervisor/services/modules/mysql.py
./supervisor/store/repository.py
./supervisor/utils/apparmor.py
./supervisor/utils/gdbus.py
```

Maybe other files contain a more complex pattern that needs changing, but those are more difficult to find, if they exist.

**Comment by F1nnM** [comment]
Also a regex that gets you started with the transformation. It still requires some fix-up, but it does some of the work for you.
Find: `\s+(_LOGGER\.[^\(]+)\(([^\n)]+)\)(\s+raise[^\)]+)(\))`
Replace with: `$3$2$1)`

**Comment by ludeeus** [comment]
The new format only applies to our custom exceptions (That are defined in ./supervisor/exceptions.py)

**Comment by ludeeus** [comment]
Thanks everyone for helping out during Hacktoberfest, see you again next year :tada:
