### ISSUE TITLE
OS-Agent broken after upgrade

### ISSUE THREAD

**Issue by ch4d1** [home-assistant/supervisor#3157]
### Describe the issue you are experiencing

Supervisor running seems to have issues with OS-Agent after upgrading to version supervisor-2021.09.4

OS: Pi-OS 64 Beta

### What is the used version of the Supervisor?

supervisor-2021.09.4

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.10.60-v8+

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

1. upgrade Supervisor to supervisor-2021.09.4 from supervisor-2021.09.0

### Anything in the Supervisor logs that might be useful for us?

```txt
21-09-27 19:08:31 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-09-27 19:08:31 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-09-27 19:08:31 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-09-27 19:08:31 WARNING (MainThread) [supervisor.resolution.evaluations.base] OS-Agent is not correctly working (more-info: https://www.home-assistant.io/more-info/unsupported/os_agent)
21-09-27 19:08:31 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-09-27 19:08:31 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
21-09-27 19:08:31 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-09-27 19:08:32 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-09-27 19:08:32 INFO (MainThread) [__main__] Running Supervisor
21-09-27 19:08:32 WARNING (MainThread) [supervisor.core] System running in a unsupported environment!
21-09-27 19:08:32 INFO (MainThread) [supervisor.jobs] 'OSManager.mark_healthy' blocked from execution, no Home Assistant OS available
```

**Comment by ludeeus** [comment]
Pi-OS is not supported.

**Comment by ch4d1** [comment]
@ludeeus So instead of the Pi-OS Debian 10 fork, I should use Debian 11? Just to make clear it worked without any issue for the past 9 months.

**Comment by ludeeus** [comment]
Debian 11 or Home Assistant Operating System <https://www.home-assistant.io/more-info/unsupported/os>

**Comment by pssc** [comment]
@ch4d1 os-agent installed and latest version on the os? it just works for me on the rpi os

**Comment by ch4d1** [comment]
@pssc yeah. But I guess we will never know what has caused the issue. Switching to Debian 11 now^^
