### ISSUE TITLE
Device access changed in addon

### ISSUE THREAD

**Issue by McGiverGim** [home-assistant/supervisor#3194]
### Describe the issue you are experiencing

I don't know if this is a bug, or something that has changed in the latest version.

I'm one of the developers of HDD Tools, an addon that looks at the smart data of the disk. Basically it executes a `smartctl` command and sends this info as sensor. More info: https://github.com/Draggon/hassio-hdd-tools/

Until now, I had this options in the ```config.json``` of the addon (this is only the relevant part):
```json
{
  "name": "HDD Tools",
...
  "privileged": ["SYS_ADMIN", "SYS_RAWIO"],
...
  "options": {
      "hdd_path": "/dev/sda",
...
  },
  "schema": {
      "hdd_path": "device(subsystem=block)",
...
    }
}
```

With this, it seemed that Home Assistant added permisions for the hdd `/dev/XXXXX` selected by the user in the config without problem. But now, I don't know since when this does not work anymore, more info here: https://github.com/Draggon/hassio-hdd-tools/issues/35 

I know that adding a `full_access: true` fixes the issue, but the score of the addon goes down to 1 and it seems more clean to me like it was until now. 

This is a bug or simply this way of doing the things has changed and I need to ask for `full_access` in a mandatory way?

### What is the used version of the Supervisor?

supervisor-2021.09.6

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.4

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

1. Install the HDD Tools addon
2. Execute it
3. Look at the logs

### Anything in the Supervisor logs that might be useful for us?

```txt
21-10-04 09:32:29 ERROR (SyncWorker_5) [supervisor.docker.addon] Add-on HDD Tools try to access to blocked device sda!
```

### Additional information

I don't know if this is an issue of the supervisor or it belongs to other part.

**Comment by ludeeus** [comment]
You can use full_access or the devices directive in your add-on configuration.
See `devices` here <https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config>

**Comment by McGiverGim** [comment]
I know this. In the text I talk about the `full_access` , but my question is what changed in the latest days to break the old behavior, it is was intended or it was a bug. It was far better in the old way :(

**Comment by ludeeus** [comment]
The old way was a bug, that bug was fixed many months ago.

**Comment by McGiverGim** [comment]
Ok. Thanks for the explanation. But it has worked until only some days ago. Confirmed by me and other users.
It seemed more a feature: if a user selected a device in the configuration, add it as device automatically.
Thanks for your answer!
