### ISSUE TITLE
I get a deprecated, 'backup' problem, but I do not have these integrations installed. They were deleted a few weeks ago.

### ISSUE THREAD

**Issue by Ace0510** [home-assistant/supervisor#3199]
### Describe the issue you are experiencing

I get a deprecated, 'backup' problem, but I do not have these integrations installed. They were deleted a few weeks ago.

21-10-04 09:03:00 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller
21-10-04 09:03:01 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home
21-10-04 09:03:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller
21-10-04 09:03:03 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home

### What is the used version of the Supervisor?

supervisor-2021.09.6

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

2021.09.6

### What version of Home Assistant Core is installed?

core- 2021.9.6

### Steps to reproduce the issue

1.None
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-10-04 09:03:00 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller
21-10-04 09:03:01 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home
21-10-04 09:03:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot' is deprecated, 'backup' should be used instead. Please report this to the maintainer of UniFi Controller
21-10-04 09:03:03 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home
```

**Comment by frenck** [comment]
They are still in the add-on store. This should not be reported here, but reported at the add-on repository, not the supervisor.
