### ISSUE TITLE
Locally built addons updates leave previous images (same as #160 from 2017)

### ISSUE THREAD

**Issue by alexbelgium** [home-assistant/supervisor#3223]
### Describe the issue you are experiencing

When an addon builds locally on HA, it does not removes previously built images. This can accumulates to many Go over time. The only way is to remove them manually with "docker image prune -a", but this also deletes images of non running but still relevant containers.

Here are several examples : 
- https://github.com/alexbelgium/hassio-addons/issues/58
- https://community.home-assistant.io/t/unused-containers-images-not-deleted-by-hass-io/23866
- https://community.home-assistant.io/t/disk-almost-full/121023

This was addressed here but is still occurring : https://github.com/home-assistant/supervisor/issues/160

### What is the used version of the Supervisor?

supervisor-2021.10.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.4

### What version of Home Assistant Core is installed?

2021.10.0

### Steps to reproduce the issue

1. Install a locally built addon
2. Update this addon to a new version
3. Check with portainer or any docker tool that the previous image was not removed

When running this way for several months, I gave several gigaoctets of unused images.

### Anything in the Supervisor logs that might be useful for us?

```txt
No relevant info
```

![C555FE06-12D7-47F2-92C2-F3ADF318CFAD](https://user-images.githubusercontent.com/44178713/136652238-fe1c0bb5-ff14-484f-b1a8-7bb90a9793c2.png)

**Comment by alexbelgium** [comment]
This is still valid... And existing for several years!

**Comment by ludeeus** [comment]
It is not the add-on images, that is what you use as a base.
Locally building add-ons are intended for development and testing only, in those situations you are expected to be able to manage this.

Publish your add-ons as prebuilt images as stated in the documentation.
<https://developers.home-assistant.io/docs/add-ons/publishing#locally-build-containers>
> Use this option when you are playing with add-ons and seeing if someone is interested in your work. Once you're an established repository, please migrate to pushing builds to Docker Hub as it greatly improves the user experience. In the future we will mark locally built add-ons in the add-on store to warn users.

The GitHub action used in the [Example add-on repository](https://github.com/home-assistant/addons-example/blob/main/.github/workflows/builder.yaml) can help you get started with that.
