### ISSUE TITLE
floats can't be negative in schema

### ISSUE THREAD

**Issue by jagibson** [home-assistant/supervisor#3226]
### Describe the issue you are experiencing

If you define an addon parameter as a float in config.json under schema, you are unable to change the value in the UI to a negative number.

If you set the default value of a parameter to a negative number you will get an error trying to load the plugin.

Integers seem to handle negative numbers just fine.

I am trying to add a negative float for a geographical coordinate.

### What is the used version of the Supervisor?

supervisor-2021.10.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.4

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

Scenario one - cannot have a negative number when creating the add-on.
1. Create a new addon with an option set to a negative value.
2. In the schema try to specify a negative number as the min. for the option.
3. Try to load the addon.  You should get an error.

Scenario two - cannot change a number defined as a float to a negative value.
1. Define a float in the schema without min/max values.
2. Start the addon.  Try to enter a negative number in the Configuration screen for the addon.  You will be unable to type in the "-" symbol.

### Anything in the Supervisor logs that might be useful for us?

```txt
Text is gone now, but there was something about matching a regular expression string.
```

### Additional information

Scenario two is easy to reproduce.  Scenario one was bugging me for days but I can't reproduce it any longer.

**Comment by jagibson** [comment]
It looks like the regex check is here -  https://github.com/home-assistant/supervisor/blob/dafc2cfec27777c3f4c68a2eb4c5cd5d58fda4c2/supervisor/addons/options.py#L40 .  If I can detangle it enough I can try to submit a PR.  

If there is a reason why floats can't be negative please let me know.

**Comment by jagibson** [comment]
I think I have the right regex just need to do the PR

**Comment by montjoy** [comment]
OK - I using a different account now.
I've got the code ready in my [fork ](https://github.com/montjoy/supervisor/commit/56bd9b8d0d2d300011796000b60192d1dce66c59) but I need to run the tests on it still before creating a PR.
