### ISSUE TITLE
401: Unauthorized / No valid ingress session None

### ISSUE THREAD

**Issue by R5fan** [home-assistant/supervisor#3235]
### Describe the issue you are experiencing

I have the exact same issue described here: https://github.com/home-assistant/supervisor/issues/3021 But with Brave browser (chrome based). 

I am no longer able to display the Web UI of Add-Ons such as Node-Red, Frigate, Portainer,..
The issue only seems to occur when I use HTTP to my local IP, I dont see it when using HTTPS

Clicking "Open Web UI" results in this message:

`401: Unauthorized
`
Supervisor's log reports:

```
21-10-16 12:59:26 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
21-10-16 13:00:29 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
21-10-16 13:00:36 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
```

Disabling brave privacy shield makes no difference.

Im using nginx reverse proxy if that makes a difference.

### What is the used version of the Supervisor?

supervisor-2021.10.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.4

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

1. Open brave
2. Navigate to HA dashboard using HTTP
3. Open a web UI from an addon.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-10-16 13:00:36 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
```

**Comment by R5fan** [comment]
Managed to "fix" it (temporarily?) by going to settings
brave://settings/siteData
then search for the IP of HA, and delete the ingress session. If it helps, this is what it contains now:
```
Name
ingress_session
Content
***redacted no idea if this is sensitive data ****
Domain
192.168.1.10
Path
/api/hassio_ingress/
Send for
Same-site connections only
Accessible to script
Yes
Created
Saturday, October 16, 2021 at 9:35:28 PM
Expires
When the browsing session ends
```

**Comment by balloob** [comment]
Firefox 95 has been released and Ingress now works with strict mode. If you encounter an issue, please open a new issue.
