### ISSUE TITLE
Can't start hassio_observer: 500 Server Error ... Bind for 0.0.0.0:4357 failed: port is already allocated

### ISSUE THREAD

**Issue by tobifanger** [home-assistant/supervisor#3276]
### Describe the issue you are experiencing

Since last night I get the following error message every minute at the supervisor log:

21-10-31 08:51:30 WARNING (MainThread) [supervisor.misc.tasks] Watchdog/Docker found a problem with observer plugin!
21-10-31 08:51:30 INFO (MainThread) [supervisor.plugins.observer] Starting observer plugin
21-10-31 08:51:30 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning hassio_observer application
21-10-31 08:51:31 ERROR (SyncWorker_2) [supervisor.docker] Can't start hassio_observer: 500 Server Error for http+docker://localhost/v1.41/containers/29dcf1bd189b269d77afaf3e6eeb9207be8edd4c7158dd5757331c2486de25a7/start: Internal Server Error ("driver failed programming external connectivity on endpoint hassio_observer (0a88cff743e65ae5baf75cb018c3bbb57943d9cb3ee52841decf3f294e8339a1): Bind for 0.0.0.0:4357 failed: port is already allocated")
21-10-31 08:51:31 ERROR (MainThread) [supervisor.plugins.observer] Can't start observer plugin
21-10-31 08:51:31 ERROR (MainThread) [supervisor.misc.tasks] Observer watchdog reanimation failed!

No addon or update was installed yesterday. When I woke up today morning the HA-Server was down. After a hardware reset/restart the system comes up and now I get those error messages. I found and try the following commands:
SSH from remote ... 
- ha supervisor repair
- ha core rebuild
- ha su repair

Nothing changes. 

[core-ssh ~]$ sudo netstnetstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:35637        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      477/sshd -D -e [lis
tcp        0      0 0.0.0.0:8099            0.0.0.0:*               LISTEN      476/ttyd
tcp        0      0 :::22                   :::*                    LISTEN      477/sshd -D -e [lis
udp        0      0 127.0.0.11:37190        0.0.0.0:*                           -

What can I do? Has anyone an idea?

### What is the used version of the Supervisor?

supervisor-2021.10.6

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.5

### What version of Home Assistant Core is installed?

core-2021.10.6

### Steps to reproduce the issue

Start the System an the following error messages comes up

### Anything in the Supervisor logs that might be useful for us?

```txt
21-10-31 08:51:30 WARNING (MainThread) [supervisor.misc.tasks] Watchdog/Docker found a problem with observer plugin!
21-10-31 08:51:30 INFO (MainThread) [supervisor.plugins.observer] Starting observer plugin
21-10-31 08:51:30 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning hassio_observer application
21-10-31 08:51:31 ERROR (SyncWorker_2) [supervisor.docker] Can't start hassio_observer: 500 Server Error for http+docker://localhost/v1.41/containers/29dcf1bd189b269d77afaf3e6eeb9207be8edd4c7158dd5757331c2486de25a7/start: Internal Server Error ("driver failed programming external connectivity on endpoint hassio_observer (0a88cff743e65ae5baf75cb018c3bbb57943d9cb3ee52841decf3f294e8339a1): Bind for 0.0.0.0:4357 failed: port is already allocated")
21-10-31 08:51:31 ERROR (MainThread) [supervisor.plugins.observer] Can't start observer plugin
21-10-31 08:51:31 ERROR (MainThread) [supervisor.misc.tasks] Observer watchdog reanimation failed!
```

### Additional information

I tried the following commands from remote (ssh) and nothing changed:

ha supervisor repair
ha core rebuild
ha su repair

**Comment by zuzuman** [comment]
Same issue here

**Comment by lukbsk** [comment]
Same here

**Comment by horstefan** [comment]
same

**Comment by Dendrowen** [comment]
Same
