### ISSUE TITLE
Supervisor/Observer do not detect/restart unresponsive Core

### ISSUE THREAD

**Issue by OrbitingOcelot** [home-assistant/supervisor#3283]
### Describe the issue you are experiencing

**Observed Behaviour:** HA core becomes unreachable over the network, but observer says system is healthy, supervisor does not restart the core
**Expected Behaviour:** A HA installation that does not correctly respond on its https port should be marked as failed by the observer, and restarted by the supervisor

A few days ago, my HA installation GUI became completely unreachable over the network. I could not connect locally using browser or android app, nor via the nabu casa cloud.

I connected to the observer and gotthis information:
Home Assistant observer
Supervisor:	Connected
Supported:	Supported
Healthy:	Healthy

I am running hass-os in a VM with 1.5 GB RAM assigned. System has been running smoothly for about a year before this issue. Connecting to the VM showed the following console message:

ha > Out of memory: killed process xxxxx (python3) total-vm:3322064KB

I was able to restart the core manually via the command line.

### What is the used version of the Supervisor?

supervisor-2021.10.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.5

### What version of Home Assistant Core is installed?

core-2021.10.6

### Steps to reproduce the issue

I cannot reproduce the issue. It probably could be done by killing HA core processes manually and checking how the supervisor reacts, but I dont want to break my production environment.

### Anything in the Supervisor logs that might be useful for us?

```txt
I could not find any log entries that could be related/helpful
```

**Comment by andriej** [comment]
It was probably due to DST timeozne error (fixed in 10.7) but I totally agree, that Supervisor/Observer did not do anything useful as I know installations with problem like yours.

**Comment by OrbitingOcelot** [comment]
> It was probably due to DST timeozne error (fixed in 10.7) but I totally agree, that Supervisor/Observer did not do anything useful as I know installations with problem like yours.

You are probably right regarding the root cause, I was also suspecting this might be the issue.

However I decided to focus my report only on the fact that the hung instance was not restarted or at least spotted as unresponsive by the observer, as this could become relevant again in the future with other bugs, broken configs etc., and my hope is that this can be handled more gracefully/automatically, for example when Im not around to restart the VM.

**Comment by ludeeus** [comment]
The observer does currently only check the supervisor status.

**Comment by RenfoJu1** [comment]
Happens to me too every now and then and every time it happens, i know there is a new version of home assistant available. The only thing that helps is a hard boot. For this reason i have my raspi running the hassio plugged through a hue switch, that i can restart also remotely. I wish this was fixed, since it happens way too often.
