### ISSUE TITLE
Debian 11.1 update breaks Supervisor

### ISSUE THREAD

**Issue by andriej** [home-assistant/supervisor#3284]
### Describe the issue you are experiencing

After typical upgrade of Debian (11.0 to 11.1) Supervisor were not able to perform anything useful anymore.
It kept restarting itself and issue was with:
`Nov  2 16:18:12 bx NetworkManager[512]: <warn>  [1635866292.9493] keyfile: load: "/etc/NetworkManager/system-connections/default": failed to load connection: File permissions (100644) are insecure`

After changing those permissions to 'a+r' (all read) and pulling supervisor's image once again, system was able to start.
During debugging I also downgraded docker back to 20.10.10

### What is the used version of the Supervisor?

supervisor-2021.10.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

11.1

### What version of Home Assistant Core is installed?

core-2021.10.7

### Steps to reproduce the issue

1. Have running and healthy installation
2. apt-get update && apt-get upgrade
3. Reboot (or not, doesn't matter)

### Anything in the Supervisor logs that might be useful for us?

```txt
n/a
```

**Comment by ludeeus** [comment]
The supervisor does not control this, you do.
Closing as an issue indicates an issue with the host OS and not the Supervisor.

**Comment by andriej** [comment]
Supervisor did change to NetworkManager files, I didn't.
Debian (stable) upgrade broke OS, not me.

I'm just indicating what will soon be major issue as more people will upgrade their base OS (which are still compliant, as I did not install nor interfere with supervisor anyhow).

**Comment by frenck** [comment]
The Supervisor doesn't change files on the OS, it communicates with DBus.
Your conclusion is incorrect.

**Comment by andriej** [comment]
OS-Agent does? 
If I didn't change anything in meanwhile (basically, not touching pure stable OS) and upgrade did break HA (as whole),
Maybe someone else will come with more details what did happend and why installation was broken.

Maybe it was just warn and it was purely new docker version that broke setup.

**Comment by frenck** [comment]
> OS-Agent does?
This is not the OS-Agent repository.

**Comment by andriej** [comment]
Right.
Then, if there's a docker-version issue I can just guess at which moment it breaks.
Just wanted to indicate, that I know 2 separate, broken-by-update installations - problably more to come.

Based on my knowledge I can't judge what has happened - for me, supervisor didn't start after typical OS maintenance and that's why I chose this repo.

I will sit and wait for others to come and put same issue, maybe with more details.
If someone else have this issue and read this post: downgrade with `apt-get install -y docker-ce=5:20.10.8~3-0~debian-buster` and it may work.
