### ISSUE TITLE
Unable to upgrade to Home Assistant Core v2021.11.1

### ISSUE THREAD

**Issue by ahaverty** [home-assistant/supervisor#3290]
### Describe the issue you are experiencing

Unable to upgrade to the latest Home Assistant Core on Home Assistant Blue.

### What is the used version of the Supervisor?

supervisor-2021.10.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.6

### What version of Home Assistant Core is installed?

core-2021.10.6

### Steps to reproduce the issue

1. Under "Update Pending" > Home Assistant Core > Click "Update"

The update starts, but doesn't finish, so far I've left it for 45 minutes, but the install doesn't complete.
I've tried restarting host and supervisor and trying again, but I see the same issue.

I was discussing this on the Core repository, but was suggested to move to here:
https://github.com/home-assistant/core/issues/59077

### Anything in the Supervisor logs that might be useful for us?

```txt
21-11-05 08:18:50 INFO (MainThread) [supervisor.host.manager] Host information reload completed
21-11-05 08:18:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
21-11-05 08:18:51 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-11-05 08:18:51 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-11-05 08:18:51 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-05 08:18:51 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-11-05 08:18:51 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-11-05 08:18:57 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2021.11.1
21-11-05 08:18:57 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/odroid-n2-homeassistant:2021.10.6 to ghcr.io/home-assistant/odroid-n2-homeassistant:2021.11.1
21-11-05 08:18:57 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/odroid-n2-homeassistant with tag 2021.11.1.
21-11-05 08:48:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

### Additional information

I was having a slightly different issue with not finding the image, but have since resolved this by restating the host.
More details here on the core repo issue, potentially relevant: https://github.com/home-assistant/core/issues/59077

**Comment by ahaverty** [comment]
The update seems to still think it's downloading, and is preventing other tasks from running.
Regardless of what's causing my issue here, perhaps update jobs should come with a timeout?

```
21-11-05 09:27:39 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-05 09:27:39 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-11-05 09:27:39 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-11-05 09:57:14 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2021.11.1
21-11-05 09:57:14 INFO (SyncWorker_8) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/odroid-n2-homeassistant:2021.10.6 to ghcr.io/home-assistant/odroid-n2-homeassistant:2021.11.1
21-11-05 09:57:14 INFO (SyncWorker_8) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/odroid-n2-homeassistant with tag 2021.11.1.
21-11-05 09:57:39 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-11-05 10:18:51 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
21-11-05 10:18:51 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
21-11-05 10:27:37 ERROR (MainThread) [supervisor.utils] Can't execute check_trust while a task is in progress
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-11-05 10:27:37 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-11-05 10:27:43 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

**Comment by ludeeus** [comment]
If it thinks it's still running, then it's still running.
It will run until complete or failure, the network speed, the storage speed/remaining space, and the resource usage on the host will impact the time this takes.

Because of these points jobs can't have a set timeout, if you live in a place with low internet speed running on a pi3 with bad SD card we still want this to finish even if that takes a while.

**Comment by ahaverty** [comment]
Fair enough @ludeeus 👌 

In this case, I believe there's an issue with the update that's not being output to Supervisor logs.
My Home Assistant Blue is on a 250mb connection, and has over 100GB of storage space available.
I've only had it a couple of months, but previous updates seemed to take seconds/minutes at most.

Any tips on how I can debug further?

**Comment by ludeeus** [comment]
the docker client lib we use is infamous for blowing up on any little issue so I doubt you have issues (other than it's taking it's sweet time)
Since you have tried host reboot, try stopping some add-ons to free up resources

**Comment by ahaverty** [comment]
@ludeeus am I right in thinking an odroid core OS docker image is around 300mb?

I restarted the host again with network sensors enabled this time, and shortly started another update after it rebooted. I can see the uptick in network in, but it's still going well past 300mb (I know this includes other network out, but from before starting the update, I could see this was negligible compared to the image download).

I'll leave it running for another while maybe.

Am I right in thinking stopping add-ons would only be worthwhile if my CPU was higher than it is? I don't have anything intensive ever running, just zha and a few wifi bulbs etc.

Thanks for suggestions.

![Screenshot_20211105-122658.jpg](https://user-images.githubusercontent.com/2920947/140510069-ee8291ab-cd37-4106-adc4-e5f4c48a8f49.jpg)![Screenshot_20211105-122637.jpg](https://user-images.githubusercontent.com/2920947/140510080-ca6be298-b2ff-4639-883f-acf21346560b.jpg)

**Comment by ahaverty** [comment]
@ludeeus I'm now over 1GB of incoming network, no signs of it stopping.
Would you know the path where Core OS downloads are sent off the top of your head?
Maybe I could do some digging around in terminal to even see the status of the download.

**Comment by ahaverty** [comment]
@ludeeus tested by running `docker pull ghcr.io/home-assistant/odroid-n2-homeassistant:2021.11.0`, and it looks like you're right about it still going.
Seems to be extremely slow from ghcr's side. There's an issue recently closed on docker speed here: https://github.com/docker/hub-feedback/issues/1675

I'll let it run some more and see what happens.

<img src="https://user-images.githubusercontent.com/2920947/140519858-a51e0b4f-0ebb-4885-aa7d-32ba73d591d8.png" width="500">

**Comment by ahaverty** [comment]
Sorry for the constant comments here, but I just watched it for a minute and noticed one of the downloads, at least, fails and starts again: 
![image](https://user-images.githubusercontent.com/2920947/140520733-13566b6b-3802-4cd0-8839-133696603410.png)

Perhaps it's stuck in some loop on that file? It still seems to be very slow regardless. This might not even be a Supervisor/Home Assistant related issue anymore, but please let me know if you have any other suggestions 😄

**Comment by ludeeus** [comment]
I suggest looking at your firewall if you have any and/or asking your ISP

**Comment by ahaverty** [comment]
Latest update, it slowly downloads a few mb of the final part of the image, but regularly restarts.
![image](https://user-images.githubusercontent.com/2920947/140528631-79407c3a-99dd-47b3-80d5-31f6f2bc4376.png)

@ludeeus No firewall here unfortunately. I'm on the most popular ISP over here in Ireland (Virgin Media), so if it is an issue there, there may be a few Irish HA users incoming soon 😬 
I don't suppose there's any mirrors of ghcr home assistant images that I could try? Or any way I could workaround ghcr.io?

**Comment by ahaverty** [comment]
I do see recent comments specifically mentioning slow pulls when routing through Ireland, so perhaps there is some ongoing regional issues with ghcr.io

https://github.com/docker/hub-feedback/issues/1675#issuecomment-920851902

**Comment by ahaverty** [comment]
@ludeeus Just reading through some more issues, I don't seem to be alone lately on slow/stalled pulls.
I've added my details to the latest re-opened issue over here: https://github.com/docker/hub-feedback/issues/2161#issuecomment-961960199

Issue seems to be out of HA/Supervisor's control.

Thanks for assistance so far 👍

**Comment by ludeeus** [comment]
Yeah I agree, let's close this one for now :+1:

**Comment by ahaverty** [comment]
It eventually finished the download and installed, cheers @ludeeus 🙌
