### ISSUE TITLE
RFC: New Logs API endpoint

### ISSUE THREAD

**Issue by agners** [home-assistant/supervisor#3295]
## Context

Today logs are mainly provided from the Containers directly, logs are retrieved through the Docker daemon's API  (Core, Supervisor as well as Plugins and Add-ons). Linux kernel (host) logs are directly read from kernel log buffer via `dmesg`. Currently the length of the log is limited and only logs since last restart are available.

With https://github.com/home-assistant/operating-system/pull/1627 the Supervisor can now tap into the logs from `systemd-journald` through the [`systemd-journal-gatewayd` HTTP API](https://www.freedesktop.org/software/systemd/man/systemd-journal-gatewayd.service.html). The API allows to get continuous logs (through long running HTTP connections), logs from previous boots, supports cursors and allows to specify the range of entities to be returned.

This RFC aims to specify a new API which allows to expose this new capabilities. The new API should support this specific use case but still be reasonable generic.

## Solution

Introduce new endpoint under `/host/logs/`. The location under `/host/` fits well since it will be possible to also expose `systemd-journal-gatwayd` socket in Supervised installation. Detecting availability of the socket is straight forward, we can use the host feature abstraction.

### Logs

Log entries can be retrieved through multiple endpoints. All of them support the same headers and query strings. 

#### Request

_Endpoints_

```
/host/logs/all/entries
/host/logs/{identifier}/entries
/host/logs/boot/{bootid}/all/entries
/host/logs/boot/{bootid}/{identifier}/entries
```

_URI parameters_

- `{identifier}`: To get logs for a specific subsystem identifiers are used. The same identifiers can be used to get all stored log entries, or just log entries for a specific boot id. For systemd-journald we can use the `{identifier}` to filter logs by SYSLOG_IDENTIFIER (e.g. for systemd services the service name `systemd-timesyncd`, for containers it can be configured.
- `{bootid}`: Boot identifier. Either the 32 hexadecimal identifier or just the boot index (e.g. `0` for the last boot)

_URI query string_

- `follow`: If specified the API doesn't close the HTTP connection and continuous to pass new log entries to the client.

_Header_

* `Accept`: `text/plain` or `*/*`
* `Range`: `entries=:num_skip:num_entries`: Allows to select a number of log entries. Negative numbers for `num_skip` allow to select from the end of the log.

Note: In future extensions we can use `Accept`: `application/json` to return log records more structured. This would allow to include a severity or other structured information.

#### Response

_Header_

* `Content-Type`: `text/plain`
* `Transfer-Encoding`: `chunked` (typically used since it allows to stream log entries directly)

_Body_

Log entries are "free form" single line text (e.g. in this example the way systemd-journald formats it). The plain text format intentionally does not mandate any specific log format.

```text
Nov 05 15:42:13 homeassistant kernel: usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.10
Nov 05 15:42:13 homeassistant kernel: usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
Nov 05 15:42:13 homeassistant kernel: usb usb1: Product: xHCI Host Controller
Nov 05 15:42:13 homeassistant kernel: usb usb1: Manufacturer: Linux 5.10.70 xhci-hcd
Nov 05 15:42:13 homeassistant kernel: usb usb1: SerialNumber: 0000:00:14.0
```

### Boots

To filter logs by a particular boot, a list of boot id's is available. The boot ID is a 32 character hexadecimal string (e.g. `e33d691902f84b0babc0e41c33241070`). It is the same ID as [exposed by the Linux kernel](https://www.kernel.org/doc/html/latest/admin-guide/sysctl/kernel.html#random).

#### Request

```
/host/logs/boot/list
```
_Header_

* `Accept`: `application/json` or `*/*`

#### Response

_Header_

`Content-Type`: `application/json`

_Body_

```json
{
    -2: "e33d691902f84b0babc0e41c33241070"
    -1: "acc6c25c506f414aa92dd05260d383a2"
    0: "8b9d8f190a934f1c98fba775f302e571"
}
```

**Comment by deviantintegral** [comment]
Is there a reason why this needs to be bespoke, instead of following or extending the (admittedly thin) API specified by the gatewayd service? Presumably there's already plugins and extractors for systems like Graylog for gatewayd.

https://www.freedesktop.org/software/systemd/man/systemd-journal-gatewayd.service.html

**Comment by agners** [comment]
Well, it does largely follow the API, we just only support a subset of options. In the end we try to abstract the backend to some degree, so we could change the logging backend if necessary.

Even if we follow the API 1:1, since Supervisor needs authentication, and the endpoint will be in a sub-path, any user of the API would need to adjust its code anyways.

If someone is interested in the full systemd-gatewayd API, we can also consider opening it for add-ons via config option.
