### ISSUE TITLE
DNS servers config empty after reboot

### ISSUE THREAD

**Issue by LukaszP2** [home-assistant/supervisor#3302]
### The problem

DNS servers config IPv4 is empty after every reboot. 

### What version of Home Assistant Core has the issue?

2021.11.3 but it was before

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

hassio

**Comment by mib1185** [comment]
Did you exactly follow the [Install Home Assistant Supervised](https://www.home-assistant.io/installation/linux#install-home-assistant-supervised) instructions?
