### ISSUE TITLE
RFC: Extend Logging to allow Selecting/Limiting entries and Follow mode

### ISSUE THREAD

**Issue by agners** [home-assistant/supervisor#3309]
## Context

Currently log endpoints return a fixed amount of logs (or all available logs in the kernel buffer in the case of the host logs). Sometimes more logs should be returned, or users want to browse older logs. Also it often convenient to observe logs while they are being generated. Linux tools typically have a follow mode (`-f`). This RFC aims to specify how these features can be exposed through he API.

### Selecting/Limiting entries

To select certain entries or limit the amount of entries some type of selection should be possible. This is also often called paging, where a start number and item count is passed (e.g. via query parameters `start=20&count=50`).

Entries in the context of logs today are typically log lines.

In RESTful API's often query parameters are used for pagination. There is also the option of using the [Range header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range). Since with RESTful API's one tries to use HTTP features as much as possible, it seems a very good fit for this use case:

_Header_

* `Range`: `entries=:num_skip:num_entries`: Allows to select a number of log entries. Negative numbers for `num_skip` allow to select from the end of the log.

If the `Range` header is not present, the same behavior as implemented today would apply (100 log entries).

Note: This idea is taken directly from [systemd-journal-gatewayd's Header support](https://www.freedesktop.org/software/systemd/man/systemd-journal-gatewayd.service.html#Range%20header). However, it is generic enough that it can be implemented for other log sources easily.

## Follow mode

Continuous logging can be archived by keeping the HTTP connection open and pass new logs as they come in from the log source. This can be implemented using [aiohttp's Streaming API](https://docs.aiohttp.org/en/stable/streams.html).

To keep backwards compatibility, the following/streaming mode should be explicitly enabled. I'd suggest

_URI query string_

- `follow`: If specified the API doesn't close the HTTP connection and continuous to pass new log entries to the client.

When the query string is set, the API endpoint continuously return logs as they come in. With HTTP 1.1 `Transfer-Encoding` `Chunked` is being used.

**Comment by pvizeli** [comment]
I think we can use `Range: lines:num_skip:num_entries` and if we want stream then `Range: stream:num_skip:num_entries`. I really do not like to use queries. Today if we need params, then we use POST

**Comment by ludeeus** [comment]
query params and headers are currently not passed from core to SU when initiated from the frontend, so if we use those it would only work if the user has a core version newer than when that get's implemented.
We could use the request body and have the options as JSON on the request, AFAIK we support that already for both GET and POST.
For the stream, I think that should be a different endpoint as that would require an entirely different connection.

**Comment by pvizeli** [comment]
> For the stream, I think that should be a different endpoint as that would require an entirely different connection.

So we append `/stream` to each endpoint to get streaming? Yeah, would like that

**Comment by ludeeus** [comment]
Exactly :+1:

**Comment by agners** [comment]
Oh, somehow didn't notice the discussion here, sorry for the delay.

> query params and headers are currently not passed from core to SU when initiated from the frontend, so if we use those it would only work if the user has a core version newer than when that get's implemented.

If its the right way to do things, I'd live with that limitation. Can we make the SU frontend behave depending on Core version?

> We could use the request body and have the options as JSON on the request, AFAIK we support that already for both GET and POST.

It seems that using the body of a `GET` request is somewhat controversial from a standard point of view (see https://stackoverflow.com/a/983458/184207). `POST` seems the wrong verb to "get" logs...

Can we agree on using the `Range` header? By default we would behave like today and return a fixed amount of logs. That would allow to use the new endpoints in the frontend unconditionally, and just make paging a feature which depends on the Core version.

> For the stream, I think that should be a different endpoint as that would require an entirely different connection.

A different query string requires a different connection as well. IMHO, using the same URI makes sense as it is the same "resource" from a RESTful perspective. Streaming is just an "option" how to get the data.

That said, I prefer using a separate endpoint and use `GET` over passing a "stream" option via request body and using `GET` or `POST`. So appending `/stream` works for me :+1: .

**Comment by ludeeus** [comment]
> Can we make the SU frontend behave depending on Core version?

Yes, we do that a lot allready
