### ISSUE TITLE
Volumio Intergration Bug, unable to install 2 Volumios 

### ISSUE THREAD

**Issue by comet424** [home-assistant/supervisor#3312]
### Describe the issue you are experiencing

guess i posted in wrong area  on home assistant site and not here

hi i used to be able to detect in intergrations notifications my 2 Volumios i was doing some renaming and such so i decided to delete both from the notifications… and when i do a restart core

it only can find 1. it can find them with the uid number in developer but i cant add media player option like before…
if i try doing Add type volume and then enter my host ip it says its already configured… but its not

notifications does find both DLNA for both volumio but not i can not get 2 devices/Entitys under Volumio

im running 11.4 HA

### What is the used version of the Supervisor?

supervisor-2021.10.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 6.6

### What version of Home Assistant Core is installed?

core-2021.11.4

### Steps to reproduce the issue

1.
2.
3.
...
1.  have 2 volumio vms running
2.  reboot hA
3.  notifications only shows 1  it randomly chooses 1 or other.. but finds both  DNLA volumio  servers. but cant find 2 Volumio entitys..  if you add one..  and try to add the 2nd one ip  in add intergrations  then says its already added

### Anything in the Supervisor logs that might be useful for us?

```txt
i dont think so?  but i not sure what to look for
```

### Additional information

if you need more info ask  or pictures etc

**Comment by ludeeus** [comment]
Please raise this issue in the correct repo. :+1: 
<https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc>

**Comment by comet424** [comment]
thought i was  im running HA Supervisor    not HA Core.. but ill post there too
