### ISSUE TITLE
Supervisor is misinterpreting my addon's version as a number

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/supervisor#3314]
### Describe the issue you are experiencing

Edge versions of my addons use the commit hash as their version since I follow the model established by Home Assistant Community Add-ons. The last commit hash of my addon is `58899e0`. Supervisor appears to be treating this as a number and thinks the version of my addon is `58899.0`. Because of this I can't update since it fails to find my image.

### What is the used version of the Supervisor?

supervisor-2021.10.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.6

### What version of Home Assistant Core is installed?

core-2021.11.4

### Steps to reproduce the issue

1. Install an addon
2. Update its config file to have version `58899e0`
3. Try to update it

### Anything in the Supervisor logs that might be useful for us?

```txt
21-11-17 23:47:02 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image ghcr.io/mdegat01/amridm2mqtt/aarch64:bd9a3b0 to ghcr.io/mdegat01/amridm2mqtt/aarch64:58899.0
21-11-17 23:47:02 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image ghcr.io/mdegat01/amridm2mqtt/aarch64 with tag 58899.0.
21-11-17 23:47:02 ERROR (SyncWorker_5) [supervisor.docker.interface] Can't install ghcr.io/mdegat01/amridm2mqtt/aarch64:58899.0: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=58899.0&fromImage=ghcr.io%2Fmdegat01%2Famridm2mqtt%2Faarch64: Internal Server Error ("manifest unknown")21-11-17 23:47:02 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image ghcr.io/mdegat01/amridm2mqtt/aarch64:bd9a3b0 to ghcr.io/mdegat01/amridm2mqtt/aarch64:58899.0
21-11-17 23:47:02 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image ghcr.io/mdegat01/amridm2mqtt/aarch64 with tag 58899.0.
21-11-17 23:47:02 ERROR (SyncWorker_5) [supervisor.docker.interface] Can't install ghcr.io/mdegat01/amridm2mqtt/aarch64:58899.0: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=58899.0&fromImage=ghcr.io%2Fmdegat01%2Famridm2mqtt%2Faarch64: Internal Server Error ("manifest unknown")
```

### Additional information

Actual config file of my addon at the time I submitted this can be found [here](https://github.com/mdegat01/hassio-addons-edge/blob/53cb7d3bcb61e11963a3644449c11a9bdbf45668/amridm2mqtt/config.yaml). Here's what I saw in supervisor:
<img width="460" alt="Screen Shot 2021-11-17 at 11 48 00 PM" src="https://user-images.githubusercontent.com/2037026/142354741-8ab6c80e-d01b-4bf5-9413-22460c9c0b45.png">
<img width="605" alt="Screen Shot 2021-11-17 at 11 52 52 PM" src="https://user-images.githubusercontent.com/2037026/142354752-e030135b-03a4-439d-a818-3a62f330c306.png">

**Comment by ludeeus** [comment]
`58899e0` is `58899.0`, that is actually a correct handled notation.
You need to quote your version to make it a string.
`version: 58899e0` -> `version: "58899e0"` then it will use `"58899e0"`

**Comment by mdegat01** [comment]
That makes sense. This file was generated by [repository-updater](https://github.com/hassio-addons/repository-updater) so I'll refile over there in that case.

**Comment by mdegat01** [comment]
Actually @ludeeus was discussing with Frenck in the repository-updater repo and I think this might be a supervisor issue. According to the [YAML spec's definition of floating point numbers](https://yaml.org/spec/1.2.2/#10214-floating-point), `58899e0` isn't a valid number. To be a valid floating point number in scientific notation the value must match this regex:
```
-? [1-9] ( \. [0-9]* [1-9] )? ( e [-+] [1-9] [0-9]* )?
```
`58899e0` does not since if there is an `e` it must be followed by either a `+` or `-` sign then a non-zero number according to that regex:
![Screen Shot 2021-11-18 at 10 39 42 AM](https://user-images.githubusercontent.com/2037026/142448938-3ef40243-b645-4d6a-ae18-6871085fc3e0.png)

I imagine this is why PyYAML does not see the need to quote it when dumping it out and treats it as a string when parsing it back:
```
>>> import yaml
>>> config = {}
>>> config["version"] = '58899e0'
>>> yaml.dump(config, default_flow_style=False)
'version: 58899e0\n'
>>> test = yaml.dump(config, default_flow_style=False)
>>> test_config = yaml.load(test, Loader=yaml.CLoader)
>>> test_config['version']
'58899e0'
```
I think perhaps this should be re-opened.

**Comment by ludeeus** [comment]
YAML parsers does not really matter here, this happens when it's turned into a string (which is needed) in python.
```python
>>> str(58899e0)
'58899.0'
>>> str("58899e0")
'58899e0'
```

**Comment by frenck** [comment]
```py
import yaml  # pyyaml==6.0, Home Assistant Core, Repository Updater
import ruamel.yaml as ryaml  # ruamel.yaml==0.15.100, Supervisor

file_data = """
version: 58899e0
"""

yaml_data = yaml.safe_load(file_data)
ryaml_data = ryaml.load(file_data, Loader=ryaml.Loader)

print("PyYAML:")
print(yaml_data)
print(type(yaml_data["version"]))

print("ruamel.yaml:")
print(ryaml_data)
print(type(ryaml_data["version"]))
```

Output:

```
PyYAML:
{'version': '58899e0'}
<class 'str'>
ruamel.yaml:
{'version': 58899.0}
<class 'float'>
```

```sh
# echo "version: 58899e0" | yq e '.version' -       
58899e0
```

**Comment by frenck** [comment]
It gets worse:

```sh
# echo "version: 58899e0" | yq e -o=json '.' -       
{
  "version": 58899
}
```

So yq can do both 😄

**Comment by frenck** [comment]
So I'm lost on the truth here.

My first impression is that PyYAML is handling it incorrectly (which write the file that caused this).

Anyways, I'll go back to JSON. Problem solved.
