### ISSUE TITLE
404 not found installer.sh

### ISSUE THREAD

**Issue by Honzys** [home-assistant/supervisor#3321]
### Describe the issue you are experiencing

Page https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh Response with 404 Not found.

This further causes issues when installing home assistant supervised.

### What is the used version of the Supervisor?

supervisor-

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.11

### What version of Home Assistant Core is installed?

core-

### Steps to reproduce the issue

Try to get page https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh

### Anything in the Supervisor logs that might be useful for us?

```txt
Only the page doesn't work.
```

**Comment by ludeeus** [comment]
That file has been removed, see the README for instructions.
