### ISSUE TITLE
Supervisor not showing up in control panel

### ISSUE THREAD

**Issue by jbouwh** [home-assistant/supervisor#3343]
### Describe the issue you are experiencing

The supervisor is not showing up in de menu any more, but `ha supervisor logs` shows the supervisor is up and running.

System info:

Frontend-versie: 20211206.0 - latest

arch: aarch64
channel: beta
docker: 20.10.9
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- os_agent
- haos
hassos: "7.0"
homeassistant: 2021.12.0b2
hostname: homeassistant
logging: info
machine: raspberrypi4-64
operating_system: Home Assistant OS 7.0
state: running
supervisor: 2021.12.0
supported: false
supported_arch:
- aarch64
- armv7
- armhf
timezone: Europe/Amsterdam

### What is the used version of the Supervisor?

supervisor-2021.12.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

7.0

### What version of Home Assistant Core is installed?

2021.12.0b2

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
What I already tried:
- Rebooting the host
- Repairing the supervisor
- Updating the supervisor
```

**Comment by ludeeus** [comment]
This is expected, please read the beta release notes <https://rc.home-assistant.io/blog/2021/12/03/release-202112/#brand-new-configuration-menu>
