### ISSUE TITLE
Update 2021.12.1 not available

### ISSUE THREAD

**Issue by canedje** [home-assistant/supervisor#3350]
### Describe the issue you are experiencing

I do get a warning for update supervisor from 2021.10.8 to 2021.12.1.
After starting update I do receive an error:
![image](https://user-images.githubusercontent.com/23150947/145582141-4cfaab42-fa7a-4b58-b49c-f43a8583aacc.png)

### What is the used version of the Supervisor?

supervisor- 2021.10.8

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant 2021.11.5

### What version of Home Assistant Core is installed?

core-2021.11.5

### Steps to reproduce the issue

1.Push the update button
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:109
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 14:27:51 (3 occurrences)
Last logged: 14:33:55

Failed to to call /supervisor/info -
Failed to to call /supervisor/update - No supervisor update available - 2021.12.1
```

### Additional information

I do run a VM under Unraid

**Comment by canedje** [comment]
EDIT:

I did return to my HA site after a while.
It is showing the new supervisor, without extra interaction from my site???

![image](https://user-images.githubusercontent.com/23150947/145584614-17e3cc25-7dc3-47c9-8262-23fdde7e42be.png)

**Comment by truglodite** [comment]
Same thing here with hassos on pi4... upgrade appears to fail silently, but wait a few minutes and everything seems to have gone OK. 

Seems now supervisor updates are not followed up by rotating "processing animation", or the server restarting. Maybe this report and any similar confusion could have been avoided by simply mentioning these changes in the way HA behaves during a supervisor update with 12.1... one sentence in the release notes would have been effective for me.
