### ISSUE TITLE
Addon installation broken

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/supervisor#3354]
### Describe the issue you are experiencing

The latest version (installed from scratch) does not allow the installation of addon

![Warning](https://user-images.githubusercontent.com/74879713/145713031-74b4e136-29e4-4654-98c1-4942ef64bcf6.png)

### What is the used version of the Supervisor?

supervisor-2021.12.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 7.0

### What version of Home Assistant Core is installed?

core-2021.12.0

### Steps to reproduce the issue

1. I select the addon I want to install
2. I click on install
3. the installation does not start and the warning appears
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-10-12 18:09:41 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install homeassistant/aarch64-addon-configurator:5.3.3: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=5.3.3&fromImage=homeassistant%2Faarch64-addon-configurator: Internal Server Error ("Get "https://registry-1.docker.io/v2/": x509: certificate has expired or is not yet valid: current time 2021-10-12T16:09:41Z is before 2021-11-30T00:00:00Z")
```

### Additional information

Sistem log

![Warning 2](https://user-images.githubusercontent.com/74879713/145713463-c521c42a-b2fc-4e76-8199-c8f3be611c49.png)

**Comment by agners** [comment]
It seems your device date/time is not valid. The OS makes sure that on bootup it synchronizes the time with NTP services. Does the problem persist when making sure Internet connectivity is present on boot?

**Comment by WRoss7** [comment]
Is this all related to bug # 3289 I reported on November 4th? I asked for an explanation but didn't get an answer. Maybe you missed it because you closed the bug?
I also made several attempts to activate the Raspberry WiFi connection during boot, and use the mobile phone in Tethering during installation (copying a configuration file found on the internet, appropriately modified with user and password), but without success. After all, not everyone has the availability of an ethernet connection.
In my opinion, you should allow the user to configure the internet connection after booting and entering user data, like any other operating system.
Keep in mind that not everyone is a computer expert.

However, only now I was able to install again: now the boot is performed, but the kernel does not synchronize with the time (90 seconds pass).

Yesterday I opened two more reports:
# 3356 in the supervisor
# 10887 in the frontend
Is everything connected?

HasOS "runs" on a Raspberry Pi 4 (version with 4GByte) connected to a FritzBox 7530 router via an ethernet cable which in turn is connected to the optical fiber modem.

I hope you don't leave me with the system unusable for another two months like last time.

Sorry for the outburst and my bad English.

**Comment by WRoss7** [comment]
@agners can you please tell me if the bugs I have reported relate to time synchronization? Is there anything I can do? My system is shut down since early November.
I have tried several times to open all ports of the modem during installation, including UDP 123, but without success. This sync problem seems widespread, and it's not good advertisement for a new user...

![Immagine](https://user-images.githubusercontent.com/74879713/146201747-ae89daf6-6392-4fb4-9a4c-27026e7eb7fe.png)

Here I read: "Reached target System Time Sinchronized" but the system did not synchronize.

**Comment by agners** [comment]
> @agners can you please tell me if the bugs I have reported relate to time synchronization? 

Yeah, I'd say https://github.com/home-assistant/frontend/issues/10887 is related (its not just two hours, the month seems wrong too).

It seems that your FritzBox 7530 or provider doesn't allow NTP. Since you did open ports I'd guess its your provider which blocks the NTP service. This is a bit unusual, but my best explanation at that time.

Can you access the OS shell using a keyboard connected to the system and by typing `login`?

From the OS shell, can you try the following command:

```
systemctl status systemd-timesyncd
```

**Comment by WRoss7** [comment]
@agners 
> I also made several attempts to activate the Raspberry WiFi connection during boot, and use the mobile phone in Tethering during installation (copying a configuration file found on the internet, appropriately modified with user and password), but without success.

Below is the file, (saved without extension) and copied to a USB key formatted FAT32 called CONFIG, connected to the Raspberry and then booted

[connection]
id=my-network
uuid=72111c67-4a5d-4d5c-925e-f8ee26efb3c3
type=802-11-wireless

[802-11-wireless]
mode=infrastructure
ssid= ******* nome rete *******
#Uncomment below if your SSID is not broadcasted
#hidden=true

[802-11-wireless-security]
auth-alg=open
key-mgmt=wpa-psk
psk= ******* Password *******

[ipv4]
method=auto

[ipv6]
addr-gen-mode=stable-privacy
method=auto

What am I doing wrong?


> After all, not everyone has the availability of an ethernet connection. In my opinion, you should allow the user to configure the internet connection after booting and entering user data, like any other operating system.

What do you think?

My provider does not apply any filters, but I found that it uses NAT 2. It seems to me that it is blocking time synchronization. I am waiting for them to give me clarification.
Could this be the cause?

Oh, I ordered a usb keyboard, it will arrive tomorrow...

Thank you

**Comment by WRoss7** [comment]
@agners here is the output of the command you asked me for


![Timesync](https://user-images.githubusercontent.com/74879713/146575932-20b83095-eed9-4480-9bb2-2172dd60f5b5.png)


Thank yo

**Comment by WRoss7** [comment]
@agners @pvizeli  I confirm that the problem concerns NTP synchronization: the provider (Open Fiber), by far the largest in Italy, blocks some sites for synchronization.
From the tests carried out:

< Working >
time.windows.com
time.google.com - time1.google.com - time2.google.com - time3.google.com - time4.google.com
ntp1.inrim.it - ntp2.inrim.it - time.inrim.it

< Not working >
time.cloudflare.com
pool.ntp.org
0.europe.pool.ntp.org - 1.europe.pool.ntp.org - 2.europe.pool.ntp.org - 3.europe.pool.ntp.org
0.it.pool.ntp.org - 1.it.pool.ntp.org - 2.it.pool.ntp.org - 3.it.pool.ntp.org
0.android.pool.ntp.org - 1.android.pool.ntp.org - 2.android.pool.ntp.org - 3.android.pool.ntp.org
time.nist.gov - ...
time.apple.com - ...
time.facebook.com - ...
stratum1.net - ...

After a lot of time lost (and system unusable) I found rather hidden on the Home Assistant site the trick to solve it however not for everyone: by editing the file timesyncd.conf.

Could you please insert in the file present in HAOS, also under "FallbackNTP" the various NTP sites that are not blocked (or better still all), so that other users do not run into the problem?

Sorry for my bad English.

**Comment by agners** [comment]
Since HA OS sets `NTP=`, `FallbackNTP` won't have any effect. From [the documentation](https://www.freedesktop.org/software/systemd/man/timesyncd.conf.html#FallbackNTP=):

> [...] Any per-interface NTP servers obtained from [systemd-networkd.service(8)](https://www.freedesktop.org/software/systemd/man/systemd-networkd.service.html#) take precedence over this setting, as do any servers set via NTP= above. This setting is hence **only relevant** if no other NTP server information is known. [...]

I am not opposed to add Google's time servers to the list `NTP=`.

**Comment by agners** [comment]
Also, tell your provider to not block NTP :D

**Comment by WRoss7** [comment]
> Also, tell your provider to not block NTP :D

Already tried with no results!

> I am not opposed to add Google's time servers to the list `NTP=`.

It would solve all problems and avoid them to others

**Comment by pvizeli** [comment]
`ha su repair` did not fixed it?

**Comment by Niptoc** [comment]
I have an installation on Raspberry pi os + docker. Do you have an equivalent for this command?

**Comment by Niptoc** [comment]
Hello again, 

I tried to update manually through docker using the command: `docker pull ghcr.io/home-assistant/armv7-hassio-supervisor:2022.03.4`

and I get an other error message: `failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/xxxxxxxx/merged: too many levels of symbolic links`

I don't know if this is related to the message I get when trying to update through the UI

**Comment by rr19-hub** [comment]
I had the exact same problem with the success of new installations not completing on new disks. The log (browser) had a completely wrong date and time. At first I suspected DNS and therefore took out the pi-hole as DNS server. But that did not help. Then I read that for NTP also the **UDP protocol** is needed and that was then the error: in my Fritzbox new devices may only 'surf and mail'. After I deleted this restriction for the new Raspberry, everything worked!

**Comment by agners** [comment]
You can now pass a custom NTP server via DHCP (option 42). I am not sure if Fritz!Box supports this configuration, but maybe enabling NTP support on Fritz!Box enables that option automatically? 

https://en.avm.de/service/knowledge-base/dok/FRITZ-Box-7530/336_Configuring-time-synchronization-NTP-for-FRITZ-Box-and-network-devices/

Make sure to restart your Home Assistant OS installation after setting the configuration.

**Comment by WRoss7** [comment]
It works thanks 🎉
even if it is not a method within the reach of users not familiar with technology.
I also don't think all modems offer this service.
Do I have to close the report?

**Comment by WRoss7** [comment]
As written above: I also don't think all modems offer this service.
should i still close the report?

**Comment by WRoss7** [comment]
See above. Should I close this report?

**Comment by WRoss7** [comment]
See above. Should I close this report?

**Comment by WRoss7** [comment]
As written above I do not believe that all modems offer this service.
Should I still terminate the report?
