### ISSUE TITLE
WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with d4868bb1_pulseaudio_fix_dev!

### ISSUE THREAD

**Issue by wbravin** [home-assistant/supervisor#3355]
### Describe the issue you are experiencing

Hello all I have the following issue arising  every day just about.

I am running HA supervisor on a dedicated HP elitebook with debian 11 os installed.
( I read the post on the same issue however a participant said that the infrastructure was not supported)

just a note i also have almond installed

I restart HA core and reload supervisor and i get the above warning. to no avail

I then go to the addon dashboard and restart both alsa 
 & pulseaudio fix and Alsa&pulseaudio fix dev version and restart HA core and supervisor. all works fine .... great.

unfortunately the next day i get the same issue and i go through the same procedure.

what can i do to resolve this issue?

thank you for your help
   

### What is the used version of the Supervisor?

2021.12.1

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

5.11

### What version of Home Assistant Core is installed?

2021.12.0

### Steps to reproduce the issue

1. restart core
2. restart supervisor 
3. start alsa &pulse audio fix
4. start asla & pulseaudio fix dev version
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-12-12 16:16:05 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with d4868bb1_pulseaudio_fix!
21-12-12 16:16:05 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_d4868bb1_pulseaudio_fix application
21-12-12 16:16:06 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on d4868bb1/amd64-addon-pulseaudio_fix with version 3.4
21-12-12 16:16:09 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_d4868bb1_pulseaudio_fix_dev application
21-12-12 16:16:10 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on d4868bb1/amd64-addon-pulseaudio_fix_dev with version 3.5
21-12-12 16:16:36 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with d4868bb1_pulseaudio_fix_dev!
21-12-12 16:16:36 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_d4868bb1_pulseaudio_fix_dev application
21-12-12 16:16:36 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on d4868bb1/amd64-addon-pulseaudio_fix_dev with version 3.5
21-12-12 16:16:36 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with d4868bb1_pulseaudio_fix!
21-12-12 16:16:36 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_d4868bb1_pulseaudio_fix application
21-12-12 16:16:37 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on d4868bb1/amd64-addon-pulseaudio_fix with version 3.4
21-12-12 16:17:07 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with d4868bb1_pulseaudio_fix_dev!
21-12-12 16:17:07 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_d4868bb1_pulseaudio_fix_dev application
21-12-12 16:17:08 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on d4868bb1/amd64-addon-pulseaudio_fix_dev with version 3.5
21-12-12 16:17:08 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with d4868bb1_pulseaudio_fix!
21-12-12 16:17:08 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_d4868bb1_pulseaudio_fix application
21-12-12 16:17:09 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on d4868bb1/amd64-addon-pulseaudio_fix with version 3.4
```

### Additional information

everything works fine until next day

**Comment by ludeeus** [comment]
Report that to the author of that addon.
