### ISSUE TITLE
Data partition migration broken

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/supervisor#3356]
### Describe the issue you are experiencing

I tried twice (with fresh install) to migrate the data partition with no success 😤

### What is the used version of the Supervisor?

supervisor-2021.12.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 7.0

### What version of Home Assistant Core is installed?

core-2021.12.0

### Steps to reproduce the issue

1. I connect a new Kingshark sata3 ssd to a usb 3 socket - formatted fat 32 - tested on Windows 10
2. in the Supervisor system screen I click on the hamburger menu (the three dots) and then on (I don't remember well) move the data partition
3. I choose dev / sda and follow the procedure
4. I'm waiting...
...

### Anything in the Supervisor logs that might be useful for us?

```txt
I cannot access it
```

**Comment by agners** [comment]
What board are you using? Does a screen connected to the devices showing something?

**Comment by WRoss7** [comment]
Raspberry Pi 4 (version with 4GByte) connected to a FritzBox 7530 router via an ethernet cable which in turn is connected to the optical fiber modem and a KingShark ssd sata 3 in a Sabrent case connected via usb 3 to the Raspberry.
See #3354

**Comment by WRoss7** [comment]
Depend on #10887
