### ISSUE TITLE
Can't update Home Assistant 2021.12

### ISSUE THREAD

**Issue by rrlevy** [home-assistant/supervisor#3358]
### Describe the issue you are experiencing

Since a few months ago, my Home Assistant updates were having a small issue when doing updates: after clicking to make backup before update, the system would complete the backup but wouldn't update. I had to come back later and click to update without backup, event though I had the latest backup made.

Since last version (2021.11) it now requires to do the backup and update at the same time, and now I can no longer update.

After doing the backup and coming back to the update screen, I get the following Supervisor error:

```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:109
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 01:08:46 (15 occurrences)
Last logged: 01:11:11

Failed to to call /backups/new/partial - Unknown error, see supervisor
```

And the update button is "disabled".

The supervisor logs shows:

`21-12-14 01:18:57 INFO (MainThread) [supervisor.jobs] 'BackupManager.do_backup_partial' blocked from execution, system is not running - CoreState.FREEZE`

### What is the used version of the Supervisor?

supervisor-2021.12.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.6

### What version of Home Assistant Core is installed?

core-2021.11.5

### Steps to reproduce the issue

1. Reboot Home Assistant. Acessing the Supervisor > System I see this:

![image](https://user-images.githubusercontent.com/14061585/145932721-b2ea5e26-a331-438b-9e9f-ed93ceec4bff.png)

2. I click Show on OS:

![image](https://user-images.githubusercontent.com/14061585/145932791-5c6064c1-fd7f-4587-8ca0-2fc75063b740.png)

Notice the Update button disabled
(the translation error is common to happen)

3. I click the Update button

![image](https://user-images.githubusercontent.com/14061585/145932849-17dac3f9-7054-46b1-9e20-e61280eddf01.png)

4. Supervisor logs:

```
21-12-14 01:25:27 INFO (SyncWorker_3) [supervisor.backups.backup] Backup folder homeassistant done
21-12-14 01:25:36 INFO (MainThread) [supervisor.jobs] 'BackupManager.do_backup_partial' blocked from execution, system is not running - CoreState.FREEZE
```` 

### Anything in the Supervisor logs that might be useful for us?

```txt
21-12-14 01:21:46 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-12-14 01:21:57 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.FREEZE
21-12-14 01:21:57 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-12-14 01:22:27 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-12-14 01:22:29 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-12-14 01:22:29 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-12-14 01:22:29 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-12-14 01:22:29 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-12-14 01:22:44 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-12-14 01:22:44 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
21-12-14 01:22:51 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-12-14 01:22:51 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-12-14 01:22:52 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-12-14 01:25:27 INFO (SyncWorker_3) [supervisor.backups.backup] Backup folder homeassistant done
21-12-14 01:25:36 INFO (MainThread) [supervisor.jobs] 'BackupManager.do_backup_partial' blocked from execution, system is not running - CoreState.FREEZE
```

**Comment by Swiftnesses** [comment]
I also have this issue.

**Comment by ludeeus** [comment]
A backup or restore process is already running.
Wait for it to finish and hit the button again.

**Comment by LeoWinterDE** [comment]
Same bug here.
