### ISSUE TITLE
Can't start supervisor if symbolic link to media on other partition is present

### ISSUE THREAD

**Issue by jkmf** [home-assistant/supervisor#3367]
### Describe the issue you are experiencing

I need a symbolic link to "media" folder in order to some other local addon to work.
It used to work fine in previous version of supervisor 2021.11.x. 
After update to 2021.12.1 or 2021.12.2 it's not running any more.

### What is the used version of the Supervisor?

supervisor-2021.12.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 10 (buster), raspberrypi 4b 8gb

### What version of Home Assistant Core is installed?

core-2021.12.1

### Steps to reproduce the issue

1. cd /usr/share/hassio
2. sudo rm -rf media
3. sudo ln -s WHATEVER media
4. docker restart hassio_supervisor

### Anything in the Supervisor logs that might be useful for us?

```txt
[11:41:10] INFO: Starting local supervisor watchdog...
21-12-15 11:41:11 INFO (MainThread) [__main__] Initializing Supervisor setup
21-12-15 11:41:12 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 41, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 92, in initialize_coresys
    initialize_system(coresys)
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 204, in initialize_system
    config.path_media.mkdir()
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/data/media'
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by agners** [comment]
I don't think there changed something. However, the Supervisor is checking `/data/media` is a directory. That works if its a symlink **and** the symlink points to an **existing** directory. Can you check if your symlink is indeed valid and points to a directory?

**Comment by jkmf** [comment]
Obviously my symbolic link is valid, but I've found something strange:
My hard drive has few partitions, here are some of them:
```
pi@raspberrypi ➜  ~ df -h
Filesystem             Size  Used Avail Use% Mounted on
/dev/root               29G   12G   16G  41% /
devtmpfs               3.7G     0  3.7G   0% /dev
tmpfs                  3.9G     0  3.9G   0% /dev/shm
tmpfs                  3.9G  212M  3.7G   6% /run
tmpfs                  5.0M  4.0K  5.0M   1% /run/lock
tmpfs                  3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda7               30G   28G  801M  98% /mnt/cam
/dev/sda6               30G  6.8G   22G  25% /mnt/docker
/dev/sda5               30G  1.1G   27G   4% /home
...
```

If my symbolic link points to anything what is on root partition, hassio_supervisor works fine. 
If it points to directory at any other partition ("/mnt/cam" in my case), supervisor didn't work (FileExistsError: [Errno 17] File exists: '/data/media')

I've said before, that supervisor used to work on 2021.11.x version, but this might be misleading. Befor upgrading supervisor from 2021.11.x to 2021.12.x my installation was pretty old (older than 2 years). As far as I remember, the method I've used to install hassio has been described as 'deprecated', but it worked for me for a while.
What I'm trying to say is that maybe the problem is not with hassio_supervisor itself, but with current supervised installation method.

**Comment by jkmf** [comment]
The issue still occurs. 
core-2022.2.6
supervisor-2022.01.1
