### ISSUE TITLE
ESPhome add-on will not update due to typo

### ISSUE THREAD

**Issue by unw1red** [home-assistant/supervisor#3370]
### Describe the issue you are experiencing

ESPhome alerts to a new update, but it will not load due to typo in image name. It has aarch instead of arch in the architecture portion of the url.

Can't install esphome/esphome-hassio-aarch64:2021.12.1: 404 Client Error for http+docker://localhost/v1.41/images/esphome/esphome-hassio-aarch64:2021.12.1/json: Not Found ("no such image: esphome/esphome-hassio-aarch64:2021.12.1: No such image: esphome/esphome-hassio-aarch64:2021.12.1")

### What is the used version of the Supervisor?

supervisor-2021.12.2

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.10.83

### What version of Home Assistant Core is installed?

core-2021.12.2

### Steps to reproduce the issue

1. Update ESPhome add-on

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

**Comment by ludeeus** [comment]
That is not a typo, and not controlled by the Supervisor anyway.
<https://hub.docker.com/r/esphome/esphome-hassio-aarch64>

That message usually means that you have no space left <https://www.home-assistant.io/faq#404-client-error-not-found-no-such-image-homeassistant>

**Comment by unw1red** [comment]
Incorrect.

Home Assistant Supervisor
Host Operating System	Home Assistant OS 7.0
Update Channel	stable
Supervisor Version	supervisor-2021.12.2
Docker Version	20.10.9
Disk Total	113.9 GB
Disk Used	11.6 GB
Healthy	true
Supported	true
Board	odroid-n2
Supervisor API	ok
Version API	ok
Installed Add-ons	Mosquitto broker (6.0.1), ESPHome (2021.12.0), Glances (0.14.0), Terminal & SSH (9.2.1), MariaDB (2.4.0), InfluxDB (4.3.0), Grafana (7.4.0), Home Assistant Google Drive Backup (0.105.2), Acurite to Home Assistant (0.3.9b), Studio Code Server (3.7.0), Samba share (9.5.1), TasmoAdmin (0.16.0)
