### ISSUE TITLE
mfa totp config fails after upgrade to Home Assistant 2021.12.0 and Home Assistant 2021.12.1

### ISSUE THREAD

**Issue by msex67** [home-assistant/supervisor#3371]
### Describe the issue you are experiencing

[140454192928896] The system cannot restart because the configuration is not valid: expected a dictionary @ data['auth_mfa_modules'][1]
06:53:52 – (ERROR) Home Assistant WebSocket API
The system cannot restart because the configuration is not valid: expected a dictionary @ data['auth_mfa_modules'][1]
06:53:52 – (ERROR) Home Assistant Supervisor

If i remove the entries from configuration.yaml, it works again.

### What is the used version of the Supervisor?

	supervisor-2021.12.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

	Home Assistant OS 7.0

### What version of Home Assistant Core is installed?

	core-2021.12.1

### Steps to reproduce the issue

1. upgraded to latest version.
2. restart of server.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
[140454192928896] The system cannot restart because the configuration is not valid: expected a dictionary @ data['auth_mfa_modules'][1]
06:53:52 – (ERROR) Home Assistant WebSocket API
The system cannot restart because the configuration is not valid: expected a dictionary @ data['auth_mfa_modules'][1]
06:53:52 – (ERROR) Home Assistant Supervisor
```

### Additional information

i usualy upgrade to latest version within a week or so, from release date.

**Comment by ludeeus** [comment]
Please open issue in the core repo <https://github.com/home-assistant/core/issues>
