### ISSUE TITLE
Supervisor menu just disappeared after migrating to version Home Assistant 2021.12.3

### ISSUE THREAD

**Issue by marcgarciamarti** [home-assistant/supervisor#3372]
### Describe the issue you are experiencing

Supervisor menu was working fine but right after upgrading to Home Assistant 2021.12.3, it is no longer visible. I can however access the Supervisor if I use the direct link

### What is the used version of the Supervisor?

supervisor-2021.12.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

11

### What version of Home Assistant Core is installed?

core-2021.12.3

### Steps to reproduce the issue

1. Upgrade to version core-2021.12.3
2. Supervisor menu is gone

### Anything in the Supervisor logs that might be useful for us?

```txt
Supervisor menu works if accessed directly using URL/hassio/system but it is not working smoothly at all.
```

**Comment by frenck** [comment]
Hi there @marcgarciamarti 👋 

It has been moved, please make sure to read the release notes before updating.

https://www.home-assistant.io/blog/2021/12/11/release-202112/

Thanks!

../Frenck

**Comment by marcgarciamarti** [comment]
Thanks a million @frenck ! my bad!
