### ISSUE TITLE
Can’t read supervisor data

### ISSUE THREAD

**Issue by MNLFDF** [home-assistant/supervisor#3383]
### The problem

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:559 
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 04:44:57 (3 occurrences) 
Last logged: 05:20:53

Can't read Supervisor data:

### What version of Home Assistant Core has the issue?

2021.12.3

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:237 
Integration: Home Assistant Supervisor (documentation, issues) 
First occurred: 04:44:57 (24 occurrences) 
Last logged: 05:20:54

Timeout on /addons/core_mariadb/stats request
Timeout on /addons/core_mosquitto/stats request
Timeout on /addons/core_samba/stats request
Timeout on /addons/core_configurator/stats request
Timeout on /addons/45df7312_zigbee2mqtt/stats request

===============
And
===============

Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405 
First occurred: 00:08:55 (3 occurrences) 
Last logged: 07:55:57

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

### Additional information

I have this error frequently. Also on previous versions. Results in not showing the Supervisor page in previous versions. Solution was a turning off Raspberry Pi and turn it on again. (I still can access the supervisor page in the December versions).

**Comment by malosaa** [comment]
im getting this 

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405
First occurred: 12:43:06 (1249 occurrences)
Last logged: 12:43:08

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```


```

Version | core-2021.12.7

Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.83
CPU Architecture | x86_64
Timezone | Europe/Amsterdam

```

**Comment by MNLFDF** [comment]
Still having this problem with version 2021.12.7

**Comment by spoof54** [comment]
Hi, Same problem here !
I have a HomeAssistant OS installation on a VM Virtualbox, always updated.

Just made a new VM from scratch. Get this too from a fresh install with no config !

```
2022-01-03 08:46:45 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-01-03 08:46:48 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from Z-Fold3-de-Steven.home (192.168.1.76). (Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-F926B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/16.0 Chrome/92.0.4515.166 Mobile Safari/537.36)
```

This happened from Samsung Internet on my Fold3, Safari on my iPad.
But the connection is ok when I'm using Firefox on my PC or the Android HomeAssistant App..

**Comment by isibizi** [comment]
same problem on my system

supervisor-2021.12.2
Home Assistant OS 7.1
core-2021.12.7

`Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405
First occurred: 01:48:01 (1 occurrences)
Last logged: 01:48:01

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"`

**Comment by spoof54** [comment]
I managed to fix the problem by installing https access with the Nginx Proxy Manager addon.
It now works from my Samsung with Samsung Internet not my old iPad but it looks like it's another problem (I cannot enter the password correctly, it takes just 1 on 2 character).

**Comment by ludeeus** [comment]
Closing this as it's becoming a catch-all issue.
The issue displayed in the issue description is the integration not getting data from the supervisor before it times out.
What happens if the system is busy and/or is updating/restarting.

If that (timeouts) persist over time please open a new issue in the core repository.
