### ISSUE TITLE
docker image tag scheme differs from HA tag scheme

### ISSUE THREAD

**Issue by martinhoess** [home-assistant/supervisor#3385]
### Describe the issue you are experiencing

Unlike HA, the supervisor does not have a stable tag for the Docker images (and no dev/rc). This means that with a fresh installation (docker compose / docker stack) you might get a develop version (tag latest) which you never want to have in a productive environment. 

So for the supervisor the same tag scheme should be used as it is for HA (latest, dev, stable ...)

### What is the used version of the Supervisor?

supervisor-2021.12.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

0

### What version of Home Assistant Core is installed?

core-2021.12.6

### Steps to reproduce the issue

Docker supervisor (https://hub.docker.com/r/homeassistant/amd64-hassio-supervisor/tags)
homeassistant/amd64-hassio-supervisor:latest -> supervisor-2021.12.dev2804 **should be :2021.12.2**
homeassistant/amd64-hassio-supervisor:dev -> does not exist **should be supervisor-2021.12.dev2804**
homeassistant/amd64-hassio-supervisor:stable -> does not exists **should be :2021.12.2**

Docker HA (https://hub.docker.com/r/homeassistant/home-assistant/tags)
homeassistant/home-assistant:latest -> qemux86-64-homeassistant:2021.12.6	<- stable
homeassistant/home-assistant:dev -> qemux86-64-homeassistant:2022.2.0.dev20211229 <- develop
homeassistant/home-assistant:stable -> qemux86-64-homeassistant:2021.12.6	<- stable

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

**Comment by ludeeus** [comment]
No that should not exist, and running it that way is not supported.
