### ISSUE TITLE
 CRITICAL log message "Content-Trust is broken for the version file fetch!" , what does it mean?

### ISSUE THREAD

**Issue by edwineve** [home-assistant/supervisor#3395]
### Describe the issue you are experiencing

CRITICAL (MainThread) [supervisor.updater] Content-Trust is broken for the version file fetch!

I see this after restoring from a backup

### What is the used version of the Supervisor?

supervisor-2021.09.4

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.4

### What version of Home Assistant Core is installed?

core-2021.9.7

### Steps to reproduce the issue

1.restart supervisor
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-01-07 11:00:37 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
22-01-07 11:00:39 INFO (SyncWorker_1) [supervisor.docker.cli] Starting CLI ghcr.io/home-assistant/aarch64-hassio-cli with version 2021.09.0 - 172.30.32.5
22-01-07 11:00:39 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-observer with version 2021.06.0
22-01-07 11:00:39 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-multicast with version 2021.04.0
22-01-07 11:00:39 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin
22-01-07 11:00:39 INFO (SyncWorker_0) [supervisor.docker.multicast] Starting Multicast ghcr.io/home-assistant/aarch64-hassio-multicast with version 2021.04.0 - Host
22-01-07 11:00:39 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-01-07 11:00:42 CRITICAL (MainThread) [supervisor.updater] Content-Trust is broken for the version file fetch!
```

**Comment by ludeeus** [comment]
Your supervisor is too old, update it.

**Comment by edwineve** [comment]
I don't see any update available in the ui...

Version
supervisor-2021.09.4
Newest version
supervisor-2021.09.4

**Comment by ludeeus** [comment]
Then someone/something has broken your installation completly.
You need to reinstall and restore a backup (created by the supervisor).

**Comment by edwineve** [comment]
I got this message after a restore from a backup created by the supervisor!

**Comment by ludeeus** [comment]
No you did not, a backup does not contain supervisor versions.
This has been like this for months on your installation.

**Comment by edwineve** [comment]
ok, so the supervisor version on the image that was installed was somehow suddenly not upgradable... weird and very annoying... I will reinstall
