### ISSUE TITLE
Failed to create backup during install of 2022.01.0

### ISSUE THREAD

**Issue by OhioSpyderman** [home-assistant/supervisor#3426]
### Describe the issue you are experiencing

No backup of older version was created.
Failed to create backup message found in logs.

### What is the used version of the Supervisor?

2022.01.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

7.

### What version of Home Assistant Core is installed?

2021.12.10

### Steps to reproduce the issue

1.Said yes to new version, 2022.01.0
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Other than the error message (which was deleted when I restarted HA), no.
```

**Comment by KillahB33** [comment]
In a similar situation, can't seem to update HA Core or supervisor

**Comment by OhioSpyderman** [comment]
Mine updated just fine.
Just didn't create a backup of the old Supervisor version.
Potentially a BIG deal...

Bob.

**Comment by ludeeus** [comment]
This was fixed in https://github.com/home-assistant/frontend/pull/10886

**Comment by OhioSpyderman** [comment]
Well, it's unfixed now....

**Comment by OhioSpyderman** [comment]
Oh, wait, it wasn't SUPPOSED to do a backup of the older version supervisor?
I thought I read it would auto backup and not even ask you?

**Comment by ludeeus** [comment]
It should never have tried.

**Comment by OhioSpyderman** [comment]
Sorry, I mis-understood.
Please ignore my ignorance, lol.
