### ISSUE TITLE
Backups never ending

### ISSUE THREAD

**Issue by NVader2000** [home-assistant/supervisor#3428]
### Describe the issue you are experiencing

It appears that backups are taking, welll forever.

### What is the used version of the Supervisor?

supervisor-2022.01.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Home Assistant OS 7.2

### What version of Home Assistant Core is installed?

core-2021.12.10

### Steps to reproduce the issue

1. Configuration
2. Supervisor
3. Backups
4. Create Full backup.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
n/a
```

### Additional information

After a period of time the Backup dialog disappears but no backup was created. When I attempt to try and create another backup, I get the following message.

"Creating a backup is not possible right now because the system is in freeze state."

It stays in this state forever until I reboot the host. I am a fairly lite user and do not have anything complex with my setup. Just basic usage and keep pretty much within the defautls with HA.

**Comment by mdegat01** [comment]
What size are your backups? If you've updated to `2022.1` then you should be able to see the size of backups in the backup panel. If you haven't updated yet then go to `/backups` from whatever tool you use to edit the YAML config to see the size of the files.

I know you say you just use the defaults but by default that means some potentially huge things are included like the entire recorded database. That can get quite huge even under the defaults.

This isn't to say it should be breaking, just trying to get an understanding of the setup. If your backups are huge perhaps something is timing out. If not then likely something else.

**Comment by NVader2000** [comment]
Backups are around 2-3GiB each. However, the most recent one is about twice that size. I do not auto backup, only when I am updating to a newer version of HA and I do purge on a FIFO once I hit 7 backups. It is just odd that after sitting idle at around 4-5% for months HA just decided to fill up my drive. I can see that the 'home-assistant_v2.db' file is about 18.5GiB in size.

**Comment by mdegat01** [comment]
If you have not adjusted [recorder](https://www.home-assistant.io/integrations/recorder/) at all then you will be recording every state change of every entity in the DB. So perhaps a new integration you enabled recently came with one or more entities changing rapidly? Or even if you haven't changed the config at all perhaps an update to an existing integration as part of an HA update added some new entities which change rapidly and are filling your database.

I put these on the other issue but I would take a look at the community guides [here](https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795) and [here](https://community.home-assistant.io/t/how-to-reduce-your-database-size-and-extend-the-life-of-your-sd-card/205299). They should help you track down what's causing your DB to grow exponentially. Then you can exclude those from recorder to get it under control.

Once its under control and you've identified the source of the massive increase in database size can revisit with the particular integration that created that problem. Perhaps a way to ratelimit or slow down the information tide is warranted. Or an entity should be created as disabled by default so you aren't automatically recording state changes for it.

**Comment by mdegat01** [comment]
Although realizing I lost track of the issue for a moment there, given the size of your DB and backups, is it actually never ending? Or is it just extremely long running? Like how long did you wait before restarting the host typically?

Also is there anything in the [supervisor logs](https://my.home-assistant.io/redirect/supervisor_logs/)? If the backup process had timed out or crashed behind the scenes there should be something there about it.

**Comment by TheRealWaldo** [comment]
I see the same thing; it's as though the backup stalls in the background at a certain point, like a phantom timeout.

My database is in the MariaDB, and the backup of that add-on completes according to the supervisor log.  It takes a while, but it finishes—about 6 minutes.

It proceeds through several other add-ons and stops in the middle of one, seemingly randomly, as it isn't always the same one.  

It remains in a frozen state, but hours later, there is still no sign of a backup.

Backup is being performed on an i7 NUC w/ SSD, so unlikely to be hardware performance.
