### ISSUE TITLE
Used space issues again.

### ISSUE THREAD

**Issue by NVader2000** [home-assistant/supervisor#3429]
### Describe the issue you are experiencing

Just two days ago my used space was about 4-5%. Today it is now 25% and growing. It grew about 3% in the last few hours and continues to do so. I had this issue once before but know could figure it out. I ended up starting from scratch with my HA.

### What is the used version of the Supervisor?

supervisor-2022.01.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

Home Assistant OS 7.2

### What version of Home Assistant Core is installed?

core-2021.12.10

### Steps to reproduce the issue

1. Jsut sit back watch space being consumed.
2.  Another 1% consumed since I start this bug request.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
n/a
```

### Additional information

I have another bug request in in regards to backups, Could be related no?

**Comment by mdegat01** [comment]
> I have another bug request in in regards to backups, Could be related no?
Right, [this one](https://github.com/home-assistant/supervisor/issues/3428).

So I mean there isn't that many things that can grow at this kind of rate. You basically need rapidly streaming events being stuffed into a file on disk. In a typical HA setup that likely means one of the following:

1. Recorder's database (most likely culprit). See [here](https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795) and [here](https://community.home-assistant.io/t/how-to-reduce-your-database-size-and-extend-the-life-of-your-sd-card/205299) for some guides on determining your DB size and keeping that size under control.
2. Logs. If something is rapid fire dumping errors continuously then this can start to fill up quickly. Note that I'm not just talking about home assistant's logs, all logs from the machine makes it way to the system journal which is stored on disk. So check [HA's logs](https://my.home-assistant.io/redirect/logs/), [Supervisor's logs](https://my.home-assistant.io/redirect/supervisor_logs/) (and all the other log providers listed on that page) and the logs of each addon you use to see if anything is dumping out a continuous stream of errors.
3. Some addon you're using that collects messages streamed at it from others. Like the MQTT addon for example. This is significantly less likely then the other two but if it is the culprit then easiest way to figure it out is check your backups. If your backups are huge but your database is not (after digging into # 1 above) then an addon is the likely culprit.
