### ISSUE TITLE
Add docker enviroment variable DISABLE_JEMALLOC to disable jemalloc

### ISSUE THREAD

**Issue by schentuu** [home-assistant/supervisor#3449]
### Describe the issue you are experiencing

Some host devices running docker have problms with jemalloc due to an unsupported system page size.

`starting version 3.2.10
[20:39:59] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:39:59] INFO: Starting local supervisor watchdog...
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
Fatal Python error: _PyRuntimeState_Init_impl: Can't initialize threads for interpreter
Python runtime state: unknown

[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

This issue has allready been solved for the core docker image https://hub.docker.com/r/homeassistant/home-assistant by adding the docker enviroment variable `docker run ... -e "DISABLE_JEMALLOC=true" ...` as described at https://www.home-assistant.io/installation/linux#optimizations

But when running the image `homeassistant/armv7-hassio-supervisor:latest` this enviroment variable has no effect, yet.
Starting home-assistant/supervisor results in the output listed above, even with "DISABLE_JEMALLOC=true".

So please add this functionality to disable jemalloc on the supervisor image as well as you did for the core image.

### What is the used version of the Supervisor?

3.2.10

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

QNAP Firmware 5.0.0.1932 running ContainerStation 2.4.3.208

### What version of Home Assistant Core is installed?

failed before installing any core

### Steps to reproduce the issue

Enviroment:
Running docker image homeassistant/armv7-hassio-supervisor:latest (ID =  7d135c8fa3f0)
with QNAP Container station 2.4.3.208

loading the image  homeassistant/armv7-hassio-supervisor:latest 

Enviroment Variables:

DISABLE_JEMALLOC=true
TZ=Europe/Berlin

### Anything in the Supervisor logs that might be useful for us?

```txt
Container did not come up to a point where i could access any logs.
The issue is Known: Host systems Page size is 32K, which is not supported by jemalloc.
Workarround is known: disable jemalloc.
This is possible with home assistant core, bot not wuth the supervisor image, yet.
```

**Comment by pvizeli** [comment]
Unsupported system
