### ISSUE TITLE
Hassio-DNS continually crashing

### ISSUE THREAD

**Issue by babecassis** [home-assistant/supervisor#3475]
### Describe the issue you are experiencing

Not sure if it is a coincidence or not, but updated to 2022.3.0b5 from 2022.3.0b4. Supervisor also updated to 2022.02.0 and suddenly hassio-dns keeps on crashing. I have tried
`
ha supervisor repair
`
`
ha dns restart
`
`
ha dns restore
`

### What is the used version of the Supervisor?

2022.02.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Ubuntu 18.04.3 LTS

### What version of Home Assistant Core is installed?

2022.3.0b5

### Steps to reproduce the issue

Try and run home assistant :D

### Anything in the Supervisor logs that might be useful for us?

```txt
`
root@skywarp:~# docker logs 966b26cc5182 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] corefile.sh: executing... 
[cont-init.d] corefile.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
plugin/mdns: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
`
```

**Comment by babecassis** [comment]
I am guessing #3459 is the cause of this

**Comment by KHouse75** [comment]
Checked hassio_dns logs and I had the same AppArmor mdns message.  I'm running Ubuntu 20.04.  Quick solution was to disable apparmor.  Rebooted and all is working again.  Will very hesitantly investigate moving to debian.

**Comment by mdegat01** [comment]
Ok good to know. For the record I am looking into it. It may be an unsupported system but I realize this is pretty catastrophic. Trying to see what I can do to make this a smoother upgrade.

**Comment by babecassis** [comment]
Yea, I had to uninstall apparmor as well; however, for me now the supervisor won't start. Coincidence?

**Comment by djtimca** [comment]
> Checked hassio_dns logs and I had the same AppArmor mdns message. I'm running Ubuntu 20.04. Quick solution was to disable apparmor. Rebooted and all is working again. Will very hesitantly investigate moving to debian.

How did you manage to disable AppArmor and keep everything else working? I can not get AppArmor to disable for some reason.

**Comment by scooper1** [comment]
are you saying that the full release for March does not have this problem or the next update of the supervisor  or something different  
by temporarily  uninstalling AppArmor  we can move on and install updates

**Comment by scooper1** [comment]
> > Checked hassio_dns logs and I had the same AppArmor mdns message. I'm running Ubuntu 20.04. Quick solution was to disable apparmor. Rebooted and all is working again. Will very hesitantly investigate moving to debian.
> 
> How did you manage to disable AppArmor and keep everything else working? I can not get AppArmor to disable for some reason.

sudo apt remove --assume-yes --purge apparmor
but doing this will leave system more open to attack

**Comment by djtimca** [comment]
I wound up having to rebuild on Debiann and restore from back up. Took me a lot less time than what I spent trying to troubleshoot the problem.

**Comment by KHouse75** [comment]
> > Checked hassio_dns logs and I had the same AppArmor mdns message. I'm running Ubuntu 20.04. Quick solution was to disable apparmor. Rebooted and all is working again. Will very hesitantly investigate moving to debian.
> 
> How did you manage to disable AppArmor and keep everything else working? I can not get AppArmor to disable for some reason.

I ended up uninstalling AppArmor to permanently "disable" it.

**Comment by babecassis** [comment]
> I wound up having to rebuild on Debiann and restore from back up. Took me a lot less time than what I spent trying to troubleshoot the problem.

Same here. One time annoyance to move to a supported path. I honestly didnt know that Ubuntu wasnt supported, or I likely would have made this move earlier. Nothing like some pressure from the family when nothing in the house works to get this done :P

**Comment by mdegat01** [comment]
I did put a fix together [here](https://github.com/home-assistant/plugin-dns/pull/79). We'll get it out into a new release of DNS soon.

What will happen is the DNS plugin will still start up if the systemd resolver is unavailable it just won't be able to resolve MDNS or LLMNR names on the network. Which is more or less how it works today since it was only inconsistently able to resolve MDNS names and not able to resolve LLMNR ones. But all other names will still work as normal. Containers will be able to talk to each other and external URLs will be passed to the configured DNS server.

That being said, actually updating is a bit tricky since currently supervisor can't get to the API it uses to check for new versions. The two options seem to be reinstalling and restoring from backup or following the tips above to disable apparmor.

Note that in either option you should use the stable channel until you see the release number increase [here](https://github.com/home-assistant/version/blob/master/beta.json#L44). Otherwise you'll end up in the same situation.

**Comment by glebml** [comment]
I have downgrade dns plugin and it's help me 
```
$ ha dns downgrade --version 2021.06.0
Command completed successfully.
```
