### ISSUE TITLE
Unable to update to 2022.3.3

### ISSUE THREAD

**Issue by jackyaz** [home-assistant/supervisor#3496]
### Describe the issue you are experiencing

Update fails with unknown error

### What is the used version of the Supervisor?

supervisor-2022.03.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian GNU/Linux 11 (bullseye)

### What version of Home Assistant Core is installed?

core-2022.3.2

### Steps to reproduce the issue

1. Attempt update from WebUI

### Anything in the Supervisor logs that might be useful for us?

```txt
Mar 09 20:22:42 BorkBorkPi 84a98dfdccf2[611]: 22-03-09 20:22:42 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
Mar 09 20:22:42 BorkBorkPi hassio-supervisor[1339]: 22-03-09 20:22:42 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
Mar 09 20:22:42 BorkBorkPi 84a98dfdccf2[611]: 22-03-09 20:22:42 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 3028718e completed
Mar 09 20:22:42 BorkBorkPi hassio-supervisor[1339]: 22-03-09 20:22:42 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 3028718e completed
Mar 09 20:22:42 BorkBorkPi 84a98dfdccf2[611]: 22-03-09 20:22:42 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2022.3.3
Mar 09 20:22:42 BorkBorkPi hassio-supervisor[1339]: 22-03-09 20:22:42 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2022.3.3
Mar 09 20:22:42 BorkBorkPi 84a98dfdccf2[611]: 22-03-09 20:22:42 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2022.3.2 to ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2022.3.3
Mar 09 20:22:42 BorkBorkPi hassio-supervisor[1339]: 22-03-09 20:22:42 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2022.3.2 to ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2022.3.3
Mar 09 20:22:42 BorkBorkPi 84a98dfdccf2[611]: 22-03-09 20:22:42 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/raspberrypi4-64-homeassistant with tag 2022.3.3.
Mar 09 20:22:42 BorkBorkPi hassio-supervisor[1339]: 22-03-09 20:22:42 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/raspberrypi4-64-homeassistant with tag 2022.3.3.
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]: 22-03-09 20:23:03 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]: Traceback (most recent call last):
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]: 22-03-09 20:23:03 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]: Traceback (most recent call last):
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]:   File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]:     return await self._method(*args, **kwargs)
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]:   File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 229, in update
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]:     await _update(version)
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]:   File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 207, in _update
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]:     await self.instance.update(
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]:   File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]:     return await method(api, *args, **kwargs)
Mar 09 20:23:03 BorkBorkPi hassio-supervisor[1339]: asyncio.exceptions.TimeoutError
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]:   File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]:     return await self._method(*args, **kwargs)
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]:   File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 229, in update
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]:     await _update(version)
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]:   File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 207, in _update
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]:     await self.instance.update(
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]:   File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]:     return await method(api, *args, **kwargs)
Mar 09 20:23:03 BorkBorkPi 84a98dfdccf2[611]: asyncio.exceptions.TimeoutError
Mar 09 20:23:03 BorkBorkPi fbdf77f7c15f[611]: 2022-03-09 20:23:03 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /core/update - Unknown error, see supervisor
Mar 09 20:23:13 BorkBorkPi 84a98dfdccf2[611]: 22-03-09 20:23:13 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
Mar 09 20:23:13 BorkBorkPi hassio-supervisor[1339]: 22-03-09 20:23:13 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
```

**Comment by jurekmff** [comment]
Similar issue for me with exactly the same error logs in supervisor. Running on Home Assistant OS 7.4 though

**Comment by ColinGski** [comment]
Similar issue but with OS 7.4 and trying to update to supervisor 2022.3.3 from 2022.2.9

```
22-03-10 00:04:30 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2022.3.3
22-03-10 00:04:30 INFO (SyncWorker_0) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/qemux86-64-homeassistant:2022.2.9 to ghcr.io/home-assistant/qemux86-64-homeassistant:2022.3.3
22-03-10 00:04:30 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/qemux86-64-homeassistant with tag 2022.3.3.
22-03-10 00:04:51 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 229, in update
    await _update(version)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 207, in _update
    await self.instance.update(
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
asyncio.exceptions.TimeoutError
22-03-10 00:05:01 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
```

**Comment by kalanda** [comment]
same here: 
2022.2.9 installed trrying to update to version 2022.3.3

**Comment by richterdc** [comment]
Same Issue as well

2022.2.9 -> 2022.3.3

supervisor-2022.03.2
Home Assistant OS 7.4

`22-03-09 17:53:47 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug c5bdd352
22-03-09 17:53:47 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
22-03-09 17:55:05 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
22-03-09 17:55:06 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug c5bdd352 completed
22-03-09 17:55:06 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2022.3.3
22-03-09 17:55:06 INFO (SyncWorker_0) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/odroid-n2-homeassistant:2022.2.9 to ghcr.io/home-assistant/odroid-n2-homeassistant:2022.3.3
22-03-09 17:55:06 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/odroid-n2-homeassistant with tag 2022.3.3.
22-03-09 17:55:29 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 229, in update
    await _update(version)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 207, in _update
    await self.instance.update(
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
asyncio.exceptions.TimeoutError
22-03-09 17:55:39 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary`

**Comment by gokou340** [comment]
Same issue here. 

2021.12.10 > 2022.3.3
Home Assistant OS 7.4

Tried installing previous releases too. Same error

**Comment by oldercodergithub** [comment]
Same issue here
 2022.2.9 >  2022.3.3
Operating System Home Assistant OS 7.4 
 supervisor-2022.03.2

**Comment by egroen** [comment]
Same from 2022.2.5 to 2022.3.3

supervisor-2022.03.2
core-2022.2.5
Home Assistant Supervised @ Raspbian GNU/Linux 10 (buster) (PI 4, 4GB ram, 32 bit)
Docker 20.10.8

**Comment by tlpbu** [comment]
Same here in case of minor version upgrade 2022.3.2 → 2022.3.3
Signalling problem is in upgrade itself not locall installation.

Home Assistant OS 7.4 on RPi3

**Comment by egroen** [comment]
Been checking some stuff

It fails to connect to 35.168.17.115:443
When I try to go there myself I get an certification error
Cert should become active today, saying 6am, but do not know what timezone that it relevant to

Ignoring the cert I get an 404, but I do not know the complete URL so that doesn't have to be an issue

If it is the ssl cert is should become available in a few hours

ps: Just a random guy trying to sniff the problem

**Comment by kristofferbj** [comment]
Same issue here.

**Comment by mvereecken** [comment]
Same issue here.

**Comment by TyzzyT** [comment]
I'm having the same problem. Core 2022.2.9 -> 2022.3.3 update isn't working.

**Comment by frenck** [comment]
Closing this issue in favor of: <https://github.com/home-assistant/supervisor/issues/3495>

As it is the same issue.
