### ISSUE TITLE
HassOS_rpi4-64-7.4

### ISSUE THREAD

**Issue by kuca171** [home-assistant/supervisor#3498]
### Describe the issue you are experiencing

22-03-10 07:54:37 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-03-10 07:54:55 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 07:54:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-03-10 07:55:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
22-03-10 07:55:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
22-03-10 07:55:15 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 07:55:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-03-10 07:55:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-03-10 07:55:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-03-10 07:55:15 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 35.168.17.115:443: i/o timeout"
22-03-10 07:55:35 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 07:55:35 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-03-10 07:55:35 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-03-10 07:55:35 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 35.168.17.115:443: i/o timeout"
22-03-10 07:56:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary

### What is the used version of the Supervisor?

supervisor-2022.03.2

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 7.4

### What version of Home Assistant Core is installed?

core-2022.3.3

### Steps to reproduce the issue

Every hour is in log supervisor:

22-03-10 07:54:55 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 07:54:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-03-10 07:55:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
22-03-10 07:55:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
22-03-10 07:55:15 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 07:55:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-03-10 07:55:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-03-10 07:55:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-03-10 07:55:15 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 35.168.17.115:443: i/o timeout"
22-03-10 07:55:35 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 07:55:35 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-03-10 07:55:35 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-03-10 07:55:35 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 35.168.17.115:443: i/o timeout"
22-03-10 07:56:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
22-03-10 07:56:05 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-10 07:56:05 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING

### Anything in the Supervisor logs that might be useful for us?

```txt
22-03-10 07:54:55 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 07:54:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-03-10 07:55:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
22-03-10 07:55:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
22-03-10 07:55:15 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 07:55:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-03-10 07:55:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-03-10 07:55:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-03-10 07:55:15 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 35.168.17.115:443: i/o timeout"
22-03-10 07:55:35 ERROR (MainThread) [supervisor.resolution.check] Error during processing IssueType.TRUST: 
22-03-10 07:55:35 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-03-10 07:55:35 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-03-10 07:55:35 WARNING (MainThread) [supervisor.utils.codenotary] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 35.168.17.115:443: i/o timeout"
22-03-10 07:56:05 ERROR (MainThread) [supervisor.utils.codenotary] Timeout while processing CodeNotary
22-03-10 07:56:05 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-10 07:56:05 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
```

**Comment by pvizeli** [comment]
It's not a bug, only a warning. They work to get it fixed and it will gone
