### ISSUE TITLE
[supervisor.homeassistant.api] Error

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/supervisor#3518]
### Describe the issue you are experiencing

The system constantly looses connection/reloads (up to every few minutes, and sometimes it restarts without reason), especially when editing or reloading automations. 
This makes a propper work flow nearly impossible.

Since core version 2022.3.3 the cpu usage jumped from ca. 20% to over 50%.

Example log below.

My system:

Home Assistant Supervised
Core version 2022.3.7
Supervisor version 2022.03.5
Debian 11 Bullseye on an old Acer netbook
Python 3.9.9
Docker version 20.10.12

### What is the used version of the Supervisor?

supervisor-2022.03.5

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian 11 (Bullseye)

### What version of Home Assistant Core is installed?

core-2022.3.4

### Steps to reproduce the issue

If I'd know… but it especially occurs when automations are reloaded via config/server_control

### Anything in the Supervisor logs that might be useful for us?

```txt
22-03-13 16:25:53 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config: 
22-03-13 16:25:53 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant

22-03-15 18:21:56 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config: 
22-03-15 18:21:57 ERROR (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Home Assistant API!

22-03-17 12:34:59 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config: 
22-03-17 12:34:59 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant
22-03-17 12:37:30 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config: 
22-03-17 12:37:30 ERROR (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Home Assistant API!

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:125 
Integration: HTTP (documentation, issues) 
First occurred: 08:54:37 (1 occurrences) 
Last logged: 08:54:37

Login attempt or request with invalid authentication from supervisor (172.30.32.2). (HomeAssistantSupervisor/2022.03.5 aiohttp/3.8.1 Python/3.9)

```

**Comment by damiano75** [comment]
Same problem, also with versions before 2022.03.2, with supervisor 2022.03.2 all worked fine, now I have again the issue:

Get "http://supervisor/core/logs": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

when I run "ha core logs" in a terminal, supervisor dashboard in the fontend is empty, after a while ha restarts without any reason.
I tried to downgrade to 2022.03.2 but "ha su update --version 2022.03.2" says the system is already at the last version

**Comment by damiano75** [comment]
HA restarts about every two hours, in home-assistant.log.1:

```
2022-03-17 10:34:16 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /core/stats request
2022-03-17 10:34:16 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /core/stats - 
2022-03-17 10:34:16 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /supervisor/stats request
2022-03-17 10:34:16 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /supervisor/stats - 
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_ssh/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_configurator/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/a0d7b954_nginxproxymanager/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/cebe7a76_hassio_google_drive_backup/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_duckdns/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_samba/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/a0d7b954_logviewer/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_mariadb/stats request
2022-03-17 10:34:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/a0d7b954_nut/stats request
2022-03-17 10:34:46 WARNING (MainThread) [homeassistant.components.hassio] Can't read Supervisor data: 
2022-03-17 10:35:00 ERROR (MainThread) [homeassistant.components.nut] Error fetching NUT resource status data: Error fetching UPS state
```

In the SU logs:
```
22-03-17 10:33:41 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-03-17 10:34:47 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-03-17 10:34:55 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-03-17 10:34:58 WARNING (MainThread) [supervisor.updater] Can't fetch versions from https://version.home-assistant.io/stable.json: Timeout
22-03-17 10:35:00 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-03-17 10:35:05 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
22-03-17 10:35:23 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-03-17 10:35:23 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-03-17 10:35:33 INFO (MainThread) [supervisor.api.middleware.security] /core/logs access from core_ssh
22-03-17 10:35:54 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-03-17 10:35:54 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-03-17 10:36:02 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Home Assistant Docker!
22-03-17 10:36:02 INFO (SyncWorker_7) [supervisor.docker.interface] Starting homeassistant
22-03-17 10:36:03 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-03-17 10:36:37 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-03-17 10:36:38 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-17 10:38:15 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
```

I upgrade the SO to 7.5 but issue is still present.
It is very annoying, also because it is difficult to debug it.
I tried to stop NUT addon, but it is not the cause.

Could you please help us?

**Comment by damiano75** [comment]
In my case (Raspberry Pi 3B+ 1G RAM) I found a workaround: I installed the 32bit image instead of 64bit, even if this one is recommended, and now HA and Supervisor are very stable

**Comment by johndoe0815** [comment]
> In my case (Raspberry Pi 3B+ 1G RAM) I found a workaround: I installed the 32bit image instead of 64bit, even if this one is recommended, and now HA and Supervisor are very stable

That did it for me, thanks!
I was also haunted by this problem since a few days with more and more restarts that I could not find a reason for. The RAM utilization was always around 90% for me, which did not cause any issues in the months before.
I had already done two resets with fresh images on new sd cards and my previous backup, but no change.
Then after this hint I also tried the 32 bit image (which I never did before, as 64 bit was recommended). Now RAM utilization only 60%, lovelace frontend performs MUCH better (way less loading times of e.g. the sensor cards), and at least in the first 24 hours not a single restart anymore.
I think with 1GB RAM definitely the 64 bit image should NOT be recommended, but rather 32 bit, if the performance difference is that big.
