### ISSUE TITLE
Unable to upgrade supervisor after switching to dev branch and back to stable

### ISSUE THREAD

**Issue by johnlento** [home-assistant/supervisor#3532]
### Describe the issue you are experiencing

I had to change my supervisor branch to the development branch in order to recover my home assistant installation due to a previous bug. I am now on supervisor-2022.03.dev1102 but switching to either the stable or beta channels never actually updates from supervisor-2022.03.dev1102.

### What is the used version of the Supervisor?

supervisor-2022.03.dev1102

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

7.5

### What version of Home Assistant Core is installed?

core-2022.3.7

### Steps to reproduce the issue

From stable:
1. ha supervisor options --channel dev
2. ha supervisor reload
3. ha core update

Let it update to dev.

From dev:
1. ha supervisor options --channel stable
2. ha supervisor reload
3. ha core update

Core will update but supervisor will stay on dev.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No, but running "ha supervisor update" just states I am on the latest supervisor-2022.03.dev1102.
```

**Comment by lstrong2k** [comment]
Same issue for me.  Switched supervisor to dev due to a backup/restore bug on a previous release (and downgrading isn't possible).  I can't seem to get back to a stable or beta version.  It believes my current dev version is the latest (1102)

I'm wondering if this might fix itself when the first 2022.4.x version comes out since '2022.4' is > '2022.3' but I don't know.  I haven't tried to update to a later dev version.

**Comment by lstrong2k** [comment]
Update - supervisor-2022.04.0 (beta) was released today and I was able to upgrade successfully.  I did it in the UI.  Looks like a workaround for this issue is just to wait for the next month's first supervisor update.

**Comment by ludeeus** [comment]
You can not downgrade the supervisor, if you are switching back between channels you have to wait for a new update to that channel before getting an update.
