### ISSUE TITLE
Too many errors after update 2022.4 

### ISSUE THREAD

**Issue by KaportsevIA** [home-assistant/supervisor#3552]
### Describe the issue you are experiencing

After update 2022.4 in log too many errors detected (in integration/automation/helpers etc)

### What is the used version of the Supervisor?

supervisor-2022.03.5

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.13.0-39-generic

### What version of Home Assistant Core is installed?

core-2022.4.0

### Steps to reproduce the issue

[635...d01] Connect to 192.168.79.158 failed
20:27:48 – (ОШИБКА) LocalTuya integration (кастомная интеграция) - первое сообщение получено 20:15:26 и повторялось 15 раз
[140205325279776] Disconnected: Did not receive auth message within 10 seconds
20:26:30 – (ПРЕДУПРЕЖДЕНИЕ) Home Assistant WebSocket API - первое сообщение получено 18:23:09 и повторялось 113 раз
Управление светом в зале: Already running
20:21:29 – (ПРЕДУПРЕЖДЕНИЕ) Автоматизация - первое сообщение получено 19:23:25 и повторялось 2 раз
Error doing job: Task exception was never retrieved
20:20:52 – (ОШИБКА) LocalTuya integration (кастомная интеграция) - первое сообщение получено 19:41:16 и повторялось 6 раз
Автовыключение света на улице: Already running
20:06:46 – (ПРЕДУПРЕЖДЕНИЕ) Автоматизация - первое сообщение получено 19:10:41 и повторялось 6 раз
[Телевизор в спальне(192.168.79.31):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.79.31', 8009)), retrying in 5.0s
20:02:52 – (ОШИБКА) /usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py
Failed to determine cast type (<urlopen error _ssl.c:1112: The handshake operation timed out>)
20:02:33 – (ПРЕДУПРЕЖДЕНИЕ) /usr/local/lib/python3.9/site-packages/pychromecast/dial.py
[Телевизор в спальне(192.168.79.31):8009] Heartbeat timeout, resetting connection
20:02:22 – (ПРЕДУПРЕЖДЕНИЕ) /usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py
[031...d1c] Entity light.lampa_1_zal is requesting unknown DPS index 24
20:02:03 – (ПРЕДУПРЕЖДЕНИЕ) LocalTuya integration (кастомная интеграция) - первое сообщение получено 18:49:31 и повторялось 37 раз
Управление светом в спальне: Already running
20:02:02 – (ПРЕДУПРЕЖДЕНИЕ) Автоматизация - первое сообщение получено 20:02:02 и повторялось 2 раз
[635...43e] Connect to 192.168.79.153 failed
19:46:46 – (ОШИБКА) LocalTuya integration (кастомная интеграция) - первое сообщение получено 18:10:46 и повторялось 369 раз
Кубик в зале (Синий против часов, 21:00): Error executing script. Unexpected error for call_service at pos 1: object of type 'NoneType' has no len()
19:23:14 – (ОШИБКА) Автоматизация (кастомная интеграция) - первое сообщение получено 19:22:37 и повторялось 12 раз
Update for camera.chuangmi_026c02_2124_camera_control fails
18:32:58 – (ОШИБКА) Xiaomi Miot Auto (кастомная интеграция)
Update of camera.chuangmi_026c02_2124_camera_control is taking over 10 seconds
18:32:58 – (ПРЕДУПРЕЖДЕНИЕ) helpers/entity.py
error while get mqtt config
18:28:50 – (ОШИБКА) /usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py

### Anything in the Supervisor logs that might be useful for us?

```txt
22-04-07 20:22:37 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:22:37 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:22:37 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:22:37 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:22:37 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:22:37 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:22:37 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:22:37 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:22:37 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-04-07 20:27:36 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-04-07 20:27:37 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-04-07 20:27:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-04-07 20:27:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/ repository
22-04-07 20:27:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-04-07 20:27:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-04-07 20:27:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
22-04-07 20:27:37 INFO (MainThread) [supervisor.store.git] Update add-on http://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-04-07 20:27:39 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 0 new - 0 remove
22-04-07 20:27:39 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 0 new - 0 remove
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:27:41 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:28:32 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-04-07 20:28:39 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-04-07 20:32:41 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-04-07 20:32:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-04-07 20:32:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/ repository
22-04-07 20:32:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-04-07 20:32:41 INFO (MainThread) [supervisor.store.git] Update add-on http://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-04-07 20:32:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-04-07 20:32:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
22-04-07 20:32:42 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 0 new - 0 remove
22-04-07 20:32:42 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 0 new - 0 remove
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (9336c2b0_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-07 20:32:45 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
```

**Comment by m0t0rh3ad** [comment]
I've got the same issue
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-04-08 08:04:20 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)

**Comment by Albruaje** [comment]
Same situation

**Comment by priest1111** [comment]
Same situation!

**Comment by KaportsevIA** [comment]
I found trouble
 You must change config Zigbee2MQTT in Configuration - Addons - Zigbee2MQTT as is:
`
data_path: /config/zigbee2mqtt_snf (or YOUR_PREVIOUS_DATA_PATH)
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt: {}
serial:
  port: /dev/ttyUSB0 (or YOU_PREVIOUS_IP_OR_SERIAL)`

Example:
`data_path: /config/zigbee2mqtt_gw3
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt: {}
serial:
  port: tcp://192.168.79.212:8888
  adapter: ezsp`

**Comment by mdegat01** [comment]
All the errors you are showing are from Zigbee2MQTT. It's because in the [latest release](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/releases/tag/v1.25.0-1) they removed all options for configuring the addon via the configuration tab and instead direct users to make those changes in the addon's UI. You need to fix your addon's configuration.
