### ISSUE TITLE
Configurations lost after re-install

### ISSUE THREAD

**Issue by gkgeorgiev** [home-assistant/supervisor#3555]
### Describe the issue you are experiencing

Hi All,
I'll try to make my story as short as I could...
1. I was trying to upgrade a supervised HASSIO through the UI (it was 2022.01 or .02 don't remember), but I was constantly getting an error that the system is in unhealthy state. 
2. Then I tried to restart HASSIO via the UI and it didn't help
3. Then I was thinking to restart the docker containers ... but I couldn't find them anymore
4. I did an upgrade of my kernel and a bunch of packages that I've been procrastinating 
5. I did partial Supervised install (just downloaded the latest DEB package and installed it)
6. The containers came back ... but when I tried to access HASSIO UI ... I got the onboarding screen.
7. I Checked and I am still able to find some old files and backups in /usr/share/hassio/
8. Then I tried to do a full restore from the onboarding screen with a backup archive (unfortunately not having my last known good setup), but nothing happened and I still keep getting the onboarding screen
9. checked journalctl and I found a frequent error:
`
Apr 09 17:07:14 barcelona hassio-supervisor[32882]: 22-04-09 17:07:14 ERROR (MainThread) [supervisor.plugins.observer] Can't start observer plugin
Apr 09 17:07:14 barcelona hassio-supervisor[32882]: 22-04-09 17:07:14 ERROR (SyncWorker_3) [supervisor.docker] Can't start hassio_observer: 500 Server Error for http+docker://localhost/v1.41/containers/85b9d43988de>
Apr 09 17:07:14 barcelona docker.dockerd[1640]: time="2022-04-09T17:07:14.224874143+02:00" level=error msg="Handler for POST /v1.41/containers/85b9d43988deb5e51765ea2a78c47f6230ab97a0b13bb0e109de3eb8c6216b4d/start >
Apr 09 17:07:14 barcelona docker.dockerd[1640]: time="2022-04-09T17:07:14.224818641+02:00" level=error msg="85b9d43988deb5e51765ea2a78c47f6230ab97a0b13bb0e109de3eb8c6216b4d cleanup: failed to delete container from >
`

So now I really have no clue how to restore everything. 

BTW this is the 3rd time containers disappear, unfortunately this time I forgot that a work-around is to re-install docker-ce instead :/

### What is the used version of the Supervisor?

2022.03.5

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.4.0-107-generic #121-Ubuntu

### What version of Home Assistant Core is installed?

2022.4.1

### Steps to reproduce the issue

1. I was trying to upgrade a supervised HASSIO through the UI (it was 2022.01 or .02 don't remember), but I was constantly getting an error that the system is in unhealthy state. 
2. Then I tried to restart HASSIO via the UI and it didn't help
3. Then I was thinking to restart the docker containers ... but I couldn't find them anymore
4. I did an upgrade of my kernel and a bunch of packages that I've been procrastinating 
5. I did partial Supervised install (just downloaded the latest DEB package and installed it)
6. The containers came back ... but when I tried to access HASSIO UI ... I got the onboarding screen.

### Anything in the Supervisor logs that might be useful for us?

```txt
22-04-09 18:12:34 WARNING (MainThread) [supervisor.misc.tasks] Watchdog/Docker found a problem with observer plugin!
22-04-09 18:12:34 INFO (MainThread) [supervisor.plugins.observer] Starting observer plugin
22-04-09 18:12:34 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning hassio_observer application
22-04-09 18:12:34 ERROR (SyncWorker_1) [supervisor.docker] Can't start hassio_observer: 500 Server Error for http+docker://localhost/v1.41/containers/403139cfc2de083924d1d48670675ccfcf929fe4babb443e41b8fb04386e09b4/start: Internal Server Error ("driver failed programming external connectivity on endpoint hassio_observer (3202e14b1be2d9ef8893f6fee65b42a6be44f211436bed81d33717c41ab5656e): Error starting userland proxy: listen tcp4 0.0.0.0:4357: bind: address already in use")
22-04-09 18:12:34 ERROR (MainThread) [supervisor.plugins.observer] Can't start observer plugin
22-04-09 18:12:34 ERROR (MainThread) [supervisor.misc.tasks] Observer watchdog reanimation failed!
root@barcelona:~# netstat -tulpn | grep 4357
tcp        0      0 0.0.0.0:4357            0.0.0.0:*               LISTEN      4451/docker-proxy   
tcp6       0      0 :::4357                 :::*                    LISTEN      4468/docker-proxy   
root@barcelona:~# ps -ef | grep 4451
root        4451    3784  0 18:05 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 4357 -container-ip 172.30.32.6 -container-port 80

```

**Comment by mdegat01** [comment]
Ubuntu is not a supported operating system for a supervised installation. The only supported operating system is `Debian Linux Debian 11 aka Bullseye (no derivatives)`. The full list of requirements for a Home Assistant Supervised installation is [here](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md).

If you want to do a supervised installation then you'll need to switch your operating system from Ubuntu to Debian. Otherwise you should look into one of the [supported installation methods](https://www.home-assistant.io/installation/).
