### ISSUE TITLE
Static routing broken after 2022.4.2 update

### ISSUE THREAD

**Issue by andrewbeetee** [home-assistant/supervisor#3566]
### Describe the issue you are experiencing

Hi

Apologies in advance - I'm not entirely sure what is handling the networking portions of HAOS. I would gather it is the OS, but docker may have it's own network namespaces that I'm not seeing, or a separate routing table I can't see?

After the 2022.4.2 update - Static routes that I configured via nmcli, ceased to work.

I added them again, and it does not address the problem, and I'm completely stumped at this point.

~~Traffic initated from HAOS routes correctly, traffic initated from another system (say, my monitoring server, or the reverse proxy), results in HAOS default routing the traffic.  It appears like there is two routing tables?~~
_(Above is incorrect, Firewall (device on default route) is sending icmp redirects to HAOS VM. Other way doesn't work because it's seeing one half of the traffic and dropping it due firewall not seeing the initial session initation)_

I rebooted, and I found that, despite telling nmcli to make the routes permanent, they were not. 

HAOS is running inside a esxi VM.  

_ip_ gives me nothing when doing an _"ip r(oute)"_ 

Happy to provide further information, but my  go-to network tools are providing me with little - and what documentation I can find doesn't really describe what's going on under the hood with HAOS & docker 

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

5.10.108

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Upgrade Core to 2022.4.2
2. Add Static routes
3. Watch your static routes not work

### Anything in the Supervisor logs that might be useful for us?

```txt
n/a
```

### Anything in the Host logs that might be useful for us?

```txt
n/a
```

### System Health information

No issues

**Comment by VikeDragon** [comment]
Here is the source of the problem :
https://github.com/home-assistant/supervisor/pull/3528

The new functionality includes correction of default settings. A clone of the connection settings is created, only the minimum is not taken into account, and thus routing settings and other additional settings that the user can make for his network configuration are lost.

**Comment by andrewbeetee** [comment]
@agners - That's what I'm making the changes on .

_print ipv4_ shows the route, but it's not being used - I see the default route being used instead. 

@VikeDragon - Even adding the routes on the new connection setting sees them ignored

**Comment by VikeDragon** [comment]
> @agners - That's what I'm making the changes on .
> 
> _print ipv4_ (when in _nmcli_ ) shows the route, but it's not being used - I see the default route being used instead.
> 
> @VikeDragon - Even adding the routes on the new connection setting sees them ignored

I see. Great. And before the Supervisor 2022.4.0 update, everything worked

I had to make a crutch :
After installing the package, the home assistant is supervised.deb
We make sure that the booted manager has redone the connections and after that

Go to cd /etc/NetworkManager/
we already see 2 files
NetworkManager.conf - generated Supervisor
NetworkManager.real - old NetworkManager.conf

and added to both files in
sections 
connection and
connection-wifi-wlan0
 what I needed was both metrics and routes.
After that, everything worked as it should.

But why make it so that people are limited in their abilities?

**Comment by mdegat01** [comment]
So you're right, this was an unintended consequence of #3528 . Supervisor's API has had options for updating network details for a while, you can see them [here](https://developers.home-assistant.io/docs/api/supervisor/endpoints#network). Essentially all that PR did was resubmit all current details for each interface as if it was done via the API on startup. This was to correct issues such as [this one](https://github.com/home-assistant/operating-system/issues/1687#issuecomment-1002085354) where OS & Supervised users had out of date network configurations created by OS/Supervisor in prior releases that needed to be updated to the current recommended settings. Submitting a network update via the API gives us a chance to correct these configurations.

What we did not realize was that submitting an update to network settings via the API blows away all customizations done to network manager outside of the API. The intent was simply to reapply defaults and make sure everyone had a stable UUID, not to blow away advanced things like static routes. I tested and it appears this would've happened in any prior release of supervisor if the network options were updated via the API (or CLI or UI), it was just exacerbated by running this on startup.

I am working on a PR now to merge the supported options with the unsupported options so we don't unintentionally blow away customizations like this. That being said I do have to emphasize that the only supported means of adjusting network manager configuration in a system with supervisor is by doing so by one of these three mechanisms:

1. [Supervisor's API](https://developers.home-assistant.io/docs/api/supervisor/endpoints#network)
2. The CLI (`ha network <interface name> update <options>`)
3. [The UI](https://my.home-assistant.io/redirect/supervisor_info/)

If an option you want from `nmcli` isn't there consider submitting a [feature request](https://community.home-assistant.io/c/feature-requests/13) for it to get it supported. If you can't get your system working at all without dropping to `nmcli` to make a change we recommend switching to a either a [container or core](https://www.home-assistant.io/installation/#compare-installation-methods) type installation.

The supervised and HAOS installation methods do not support advanced customization options, including those done through `nmcli`. After my PR you will be able to get your systems working but I can't guarantee what you're doing will continue to work in the future. We only guarantee support for options available in the 3 places I listed above.
