### ISSUE TITLE
Supervisor reports "ERROR (MainThread) [asyncio] Task exception was never retrieved"

### ISSUE THREAD

**Issue by ClearlyDazed** [home-assistant/supervisor#3577]
### The problem

The Supervisor log continually reports the same error as shown below.

### What version of Home Assistant Core has the issue?

core-2022.4.3

### What was the last working version of Home Assistant Core?

core-2022.4.2

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
22-04-13 17:20:36 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-04-13 17:20:36 INFO (MainThread) [supervisor.store.git] Update add-on http://github.com/danmed/TasmoBackupV1 repository
22-04-13 17:20:36 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/allenporter/stream-addons repository
22-04-13 17:20:36 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/pssc/ha-addon-lms/ repository
22-04-13 17:20:36 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-04-13 17:20:36 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/ikifar2012/ha-addons repository
22-04-13 17:20:36 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-04-13 17:20:54 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 0 new - 0 remove
22-04-13 17:20:54 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 0 new - 0 remove
22-04-13 17:21:40 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-130136' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 417, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 473, in watchdog_application
    port = self.ports.get(f"{t_port}/tcp", t_port)
AttributeError: 'NoneType' object has no attribute 'get'
```

### Additional information

 Unsure when this started, either when upgrading or installed an add-on.

**Comment by mdegat01** [comment]
Hrm. @dgomes what addons do you run? Also what version of supervisor do you have?

**Comment by mdegat01** [comment]
@ClearlyDazed what addons do you run? And what version of supervisor do you have?

**Comment by ClearlyDazed** [comment]
@mdegat01 I'm running Supervisor 2022.04.0 and have the following addons running:
Check Home Assistant configuration(3.10.0)
Duck DNS(1.14.0)
Glances(0.15.0)
Mosquitto broker(6.0.1)
NGINX Home Assistant SSL proxy(3.1.1)
RTSPtoWeb - WebRTC(1.2.1)
Remote Backup(2022.1.1)
TasmoAdmin(0.17.0)
Terminal & SSH(9.3.0)
chrony(2.3.0)

**Comment by mdegat01** [comment]
I believe it's coming from this one `RTSPtoWeb - WebRTC(1.2.1)`. Just to confirm (since that's not in one of the standard repos), that addon is the one [here](https://github.com/allenporter/stream-addons/tree/main/rtsp-to-web) right?

It looks like that addon is misconfigured. It lists a watchdog url of `http://[HOST]:[PORT:8083]/`. But as you can see in its [config.yaml](https://github.com/allenporter/stream-addons/blob/main/rtsp-to-web/config.yaml) there is no listed `ports`. In fact it looks like there's an issue for it in that addon's repo already [here](https://github.com/allenporter/stream-addons/issues/47). The addon developer will have to fix this.

**Comment by ClearlyDazed** [comment]
@mdegat01 Thank you for your assistance
