### ISSUE TITLE
Dotless hostnames for local network fail to resolve

### ISSUE THREAD

**Issue by KevinCathcart** [home-assistant/supervisor#3581]
### Describe the issue you are experiencing

Supervised installations of home assistant cannot resolve bare dotless hostnames for the local network. 

This happens despite my router hosting a DNS server that can resolve the local hostnames, including specifying the correct DNS search path in the DHCP response.

This has been a long standing issue with the supervisor/OS, and it is probably worth fixing it. A full analysis of what is happening and possible ways to fix it can be found in the additional information section.

Obviously there are workarounds (like specifying the hosts fully qualified names) but it is still annoying.

### What is the used version of the Supervisor?

supervisor-2022.04

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

7.6

### What version of Home Assistant Core is installed?

core-2022.4.5

### Steps to reproduce the issue

1. Attempt to use a dotless hostname for a system on your network (without making it a FQDN by appending a dot at the end), in home assistant proper or any plugin, when running on HA OS.
2. Notice that the host fails to resolve.

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Additional information

The home-assistant OS host environment (if accessed via debug ssh) actually can resolve these names correctly. But the home-assistant container and add-on containers cannot.

Why can't they? Well supervisor makes docker run them with customized DNS settings that specify the DNS plugin as the DNS server and "local.hass.io" as the dns search path. Since DNS only supports lookup of fully qualified names, glibc, musl, and friends will only try to resolve bare hostnames using the search path, so `myhost` is only passed to the dns plugin as `myhost.local.hass.io`. 

The DNS plugin is configured to resolve `.local.hass.io.` names from a set of mappings supplied by the supervisor, which only include the docker containers. It is also configured to resolve `.local.` mdns queries by forwarding them to the host's systemd-resolved.

For all other queries, the net effect of supervisor code and the DNSplugin code is that it forwards them to whatever the host's NetworkManager had written out in /etc/resolv.conf at the time that the DNS plugin container was started.

While home-assistant/plugin-dns#73 claims to make LLMNR resolution work, it only works if coredns were to receive a single label name. And the only way that is going to happen is if I specify the name as fully qualified in commands via appending a trailing dot (e.g. `ping myhost.` instead of `ping myhost`).  Which nobody does, and has downsides like such queries potentially 
leaking out to public dns, where they become root zone lookups. However, the appending a dot not only fixes LLMNR, but makes any other local hostname work, since the host's systemd-resolved handles them correctly.

Now there are at least three ways that I can see to fix this, although all will require fixing a bug in the DNS plugin to work.

1. Append the search prefixes from the host's resolv.conf to the `local.hass.io` suffix passed to docker. This works, but does have limitations, and would not make LLMNR work.
2.  Change the search path given to docker to be `local.hass.io .`. Thus when calling `ping myhost`, if `myhost.local.hass.io` cannot be found `myhost.` is checked. This would cause the mdns plugin to pass any such dotless domains to the host's systemd-resolved service which will resolve them properly. This works fine, but does potentially run the risk of accidentally forwarding such hostnames to external dns. 
3. Create a new dns suffix like `external.hass.io`, which the dns plugin's mdns could process by stripping it off, and passing to the host resolved. Then the supervisor could be updated to include this as a second domain in the search suffix list. This is probably overengineered, and the second fix is probably better, but I though I would mention this one too. This could be configured to NXDomain inside core-dns after the mdns plugin to ensure no leakage to public dns servers.

Now I mentioned a bug in the dns plugin that would need to be fixed first. That bug is home-assistant/plugin-dns#85, which makes failed lookups for `.local.hass.io` subdomains return SERVFAIL, which at least for alpine containers, prevents the rest of the dns search path from being tried. Yet obviously it is critical that `local.hass.io` remain the first entry in the search path, as otherwise a local machine name could shadow one of the containers, which would really cause things to break.

**Comment by mdegat01** [comment]
Hm good find! I have a dev system on my network which has a hostname `odroid-dev`. If I go into the homeassistant container in that box here's what happens:
```
bash-5.1# nslookup odroid-dev
Server:		172.30.32.3
Address:	172.30.32.3#53

** server can't find odroid-dev.local.hass.io: SERVFAIL
```
I can also confirm that solution 2 fixes it. I tested it by tweaking the corefile of the dns plugin on that system with the following addition:
```
   template ANY A odroid-dev.local.hass.io {
        rcode NXDOMAIN
    }
```
I then modified `/etc/resolv.conf` in the homeassistant container on that machine as the author suggested. Afterwards this is what I got:
```
bash-5.1# nslookup odroid-dev
Server:		172.30.32.3
Address:	172.30.32.3#53

Name:	odroid-dev
Address: 172.30.32.1
Name:	odroid-dev
Address: 192.168.1.18
Name:	odroid-dev
Address: 172.17.0.1
```

So yea I agree, this needs to be fixed. And seriously thanks for all the solution research, really helpful!

> This works fine, but does potentially run the risk of accidentally forwarding such hostnames to external dns.

If I changed it so the MDNS plug-in was the final stop for such hostnames that would solve this right? Since the MDNS plugin asks `systemd-resolved` for the answer there it will get an answer as long as the host is capable of resolving that hostname. So passing the hostname on to the `forward` plugin seems redundant anyway and unlikely to be productive. And certainly no good can come of handing it off to the `fallback` plugin after that.

**Comment by KevinCathcart** [comment]
If you stop resolving single label hostnames after mdns, I would agree that there is no possible leakage of them, as systemd-resolved absolutely refuses to forward such requests on unicast dns (unless you set a discouraged and non-default config file option), and all forms of multi-cast dns are inherently local. With that taken into account it removes that caveat from option 2, and does make it my preferred approach too. 

There are a few minor caveats:

1. Only A and AAAA requests should be stopped. Non-address resource records should be forwarded to public dns, so diagnostic tools like `dig +trace` can do recursive resolving of TLDs. This (blocking unicast single label A or AAAA, but forwarding the rest) is exactly [the same logic as systemd-resolved uses](https://github.com/systemd/systemd/blob/2afb2f4a9d6a497dfbe1983fbe1bac297a8dc52b/src/resolve/resolved-dns-scope.c#L797-L813). 

2. I have not personally tested if that glibc based containers work correctly in this scenario. I have no reason to expect they would not work, but I know musl and glibc have some slight differences in how they handle resolv.conf. I just don't know off the top of my head of any glibc based supervisor add-on and could not be bothered writing one, or setting up the equivalent docker command line to check.

3. If somebody is running a supervised install, without systemd-resolved enabled on the host (which is not supported), and they happen to be specifying hostnames with a trailing dot, and they have a local router that serves up such hosts as top level domains (the one from my ISP does) then we could theoretically be breaking those people. This is already an unsupported configuration, and supervisor would warn as such, and it would not even make recovery difficult, so I don't think this is actually a problem, but thought it was worth mentioning.

**Comment by mdegat01** [comment]
1 & 3 - Both describe how the mdns plugin works already actually. If the type of request is not A or AAAA the mdns plugin simply [passes it on](https://github.com/home-assistant/plugin-dns/blob/master/plugins/mdns/mdns.go#L90-L92). Same if [systemd-resolved couldn't be found](https://github.com/home-assistant/plugin-dns/blob/master/plugins/mdns/mdns.go#L72-L74)

2 - Interestingly glibc based containers don't have this issue at all. Even if literally no changes are done glibc containers work fine. I'm couldn't tell you exactly why but here's how I tested it:

1. Install the [vscode addon](https://my.home-assistant.io/redirect/supervisor_addon/?addon=a0d7b954_vscode) from the community add-ons repo. It uses a [debian base](https://github.com/hassio-addons/addon-vscode/blob/main/vscode/build.yaml#L3) for its container.
2. Using the [terminal & ssh addon](https://my.home-assistant.io/redirect/supervisor_addon/?addon=a0d7b954_ssh) (also from community add-ons repo) with protection mode turned off do `docker exec -it addon_a0d7b954_vscode bash` to enter the vscode container
3. With *no other changes* here's the ping results from within that container:
```
root@a0d7b954-vscode:/# ping odroid-dev
PING odroid-dev (192.168.1.18) 56(84) bytes of data.
64 bytes from odroid-dev-ha (192.168.1.18): icmp_seq=1 ttl=63 time=3.06 ms
64 bytes from odroid-dev-ha (192.168.1.18): icmp_seq=2 ttl=63 time=2.92 ms
64 bytes from odroid-dev-ha (192.168.1.18): icmp_seq=3 ttl=63 time=3.20 ms
```
4. And here's `nslookup` (had to be installed first):
```
root@a0d7b954-vscode:/# apt-get update && apt-get install dnsutils -y
... irrelevant output
root@a0d7b954-vscode:/# nslookup odroid-dev
Server:		127.0.0.11
Address:	127.0.0.11#53

Name:	odroid-dev
Address: 192.168.1.18
```

So I'm pretty certain glibc containers are fine but will be sure to test after the change as well 👍

**Comment by KevinCathcart** [comment]
Ah, for 1 and 3, I was imagining this being handled in the corefile, where these would be concerns, handling it by tweaking the plugin does about them.

For number 2, it turns out that without a special resolv.conf directive (no_tld_query), after finishing with the search path, [it will always try the name as-is, unless it already did so as part of the search path](https://github.com/bminor/glibc/blob/f7fbb99652eceb1b6b55e4be931649df5946497c/resolv/res_query.c#L492).

The net effect is basically of appending `.` to the end of the search path.

This makes sense for dotted domains as when ndots is set, but it is also applied to dotless domains, and musk does not do this. There is a reasonable argument that musl is more correct here, but does not really matter.

**Comment by mdegat01** [comment]
@KevinCathcart so I'm not opposed to the change suggested here but I do have to note things seem to be working correctly for me now without it. After the change to eliminate the SERVFAIL here's what I see when I go into the homeassistant container, the same place I was seeing errors in the posts above:
```
bash-5.1# dig odroid-dev

; <<>> DiG 9.16.20 <<>> odroid-dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53852
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: b00311b243a5840e (echoed)
;; QUESTION SECTION:
;odroid-dev.			IN	A

;; ANSWER SECTION:
odroid-dev.		60	IN	A	192.168.1.18

;; Query time: 144 msec
;; SERVER: 172.30.32.3#53(172.30.32.3)
;; WHEN: Wed Apr 27 13:06:19 EDT 2022
;; MSG SIZE  rcvd: 77

bash-5.1# nslookup odroid-dev
Server:		172.30.32.3
Address:	172.30.32.3#53

Name:	odroid-dev
Address: 192.168.1.18

bash-5.1# ping odroid-dev
PING odroid-dev (192.168.1.18): 56 data bytes
64 bytes from 192.168.1.18: seq=0 ttl=64 time=3.178 ms
64 bytes from 192.168.1.18: seq=1 ttl=64 time=2.638 ms
^C
--- odroid-dev ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 2.638/2.908/3.178 ms
bash-5.1# cat /etc/resolv.conf
search local.hass.io
nameserver 172.30.32.3
```
Are you on the beta channel by any chance? If so is this what you see as well? I'm thinking perhaps this should be closed as it appears to have been completely resolved by the change to the DNS plugin.

**Comment by KevinCathcart** [comment]
Looking into this again, it turns out that musl does also try the name as-is after it finishes searching the path. So the path change is not needed.

Closing this as fixed by https://github.com/home-assistant/plugin-dns/pull/86
