### ISSUE TITLE
Frontend change for mobile click accessibility not working

### ISSUE THREAD

**Issue by steverep** [home-assistant/supervisor#3583]
### Describe the issue you are experiencing

The change home-assistant/frontend#11915 fixed an issue where mobile clicks with screen readers were being ignored.  It looks like this made it into the latest supervisor via #3559, but for some reason there is still no affect on the supervisor panels.  It worked just fine when testing in development.

Any ideas why it's not working in production?

### What is the used version of the Supervisor?

2022.04.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

7.6

### What version of Home Assistant Core is installed?

2022.4.6

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

**Comment by ludeeus** [comment]
The change is not a part of the version that is on stable (2022.04.0), this was included in 2022.04.1 which only made it to the beta channel, currently 2022.04.2 is being tested on the beta channel, once a new version is promoted to the stable channel it will include this.

**Comment by steverep** [comment]
My mistake - I must have been looking at the wrong release tag.  Thanks.
