### ISSUE TITLE
System autofix trying to remove core

### ISSUE THREAD

**Issue by jum0n** [home-assistant/supervisor#3589]
### Describe the issue you are experiencing

I see the following in my logs every hour where the system autofix is trying to remove "core" and failing.  I have not noticed any issues due to this but want to see if its a bug.

22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: core
22-04-22 07:27:43 ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!
22-04-22 07:27:43 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete

### What is the used version of the Supervisor?

supervisor-2022.04.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.10.103-v8

### What version of Home Assistant Core is installed?

core-2022.4.6

### Steps to reproduce the issue

Examine supervisor logs.

### Anything in the Supervisor logs that might be useful for us?

```txt
Yes, the entries posted in the description.
```

**Comment by jum0n** [comment]
Doesnt seem like this is getting assigned or looked at.

**Comment by jum0n** [comment]
Here is what that returns:

➜  ~ ha resolution info
checks:
- enabled: true
  slug: core_security
- enabled: true
  slug: addon_pwned
- enabled: true
  slug: dns_server_failure
- enabled: true
  slug: supervisor_trust
- enabled: true
  slug: dns_server_ipv6_error
- enabled: true
  slug: free_space
issues: []
suggestions: []
unhealthy: []
unsupported: []

**Comment by mdegat01** [comment]
In supervisor v2022.06.2 I added logic to never remove built-in repositories that should hopefully fix this. Give it a shot to see if you can still reproduce it or if this can be closed.

**Comment by jum0n** [comment]
Yes, these appear to have cleared from the logs.  Thank you so much!!
