### ISSUE TITLE
cant install/ update any addon

### ISSUE THREAD

**Issue by alamoudimoh** [home-assistant/supervisor#3609]
### Describe the issue you are experiencing

NOTE: THIS APPLIES 9NPY TO OFFICIAL ADDONS, AND TWO USERS FROM SAUDI HAVE REPROTED THIS.

i am running home assistatnt and i cannot update any of the add-ons running it on Pi4 64gb of sd card and used is just 8%

fresh installed it in virtualbox yet the same issue remains

2022-04-29 20:43:35 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_configurator/install - Can't install homeassistant/amd64-addon-configurator:5.3.3: 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/amd64-addon-configurator:5.3.3/json: Not Found ("no such image: homeassistant/amd64-addon-configurator:5.3.3: No such image: homeassistant/amd64-addon-configurator:5.3.3")

another addon trial:

2022-04-29 20:44:52 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_duckdns/install - Can't install homeassistant/amd64-addon-duckdns:1.14.0: 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/amd64-addon-duckdns:1.14.0/json: Not Found ("no such image: homeassistant/amd64-addon-duckdns:1.14.0: No such image: homeassistant/amd64-addon-duckdns:1.14.0")
 

### What is the used version of the Supervisor?

supervisor-2022.04.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.10.108

### What version of Home Assistant Core is installed?

core-2022.4.7

### Steps to reproduce the issue

1.fresh install
2.install any add-on
3.or update any existing add on
...
2022-04-29 20:43:35 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_configurator/install - Can't install homeassistant/amd64-addon-configurator:5.3.3: 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/amd64-addon-configurator:5.3.3/json: Not Found ("no such image: homeassistant/amd64-addon-configurator:5.3.3: No such image: homeassistant/amd64-addon-configurator:5.3.3")
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2022-04-29 20:43:35 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_configurator/install - Can't install homeassistant/amd64-addon-configurator:5.3.3: 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/amd64-addon-configurator:5.3.3/json: Not Found ("no such image: homeassistant/amd64-addon-configurator:5.3.3: No such image: homeassistant/amd64-addon-configurator:5.3.3")
```

**Comment by mdegat01** [comment]
Can you share your system health information? You can get to that from the [info panel](https://my.home-assistant.io/redirect/info/). Please follow [these directions](https://www.home-assistant.io//more-info/system-health#github-issues) for easy github sharing.

**Comment by alamoudimoh** [comment]
> Can you share your system health information? You can get to that from the [info panel](https://my.home-assistant.io/redirect/info/). Please follow [these directions](https://www.home-assistant.io//more-info/system-health#github-issues) for easy github sharing.

here you go

## System Health

version | core-2022.4.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | x86_64
timezone | Asia/Riyadh

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 31.3 GB
disk_used | 2.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

**Comment by mdegat01** [comment]
Hm so that all looks ok. I found [this post](https://community.home-assistant.io/t/home-assistant-in-a-vm-gives-404-on-docker/255937) while searching which sounds pretty similar. What does it say in the network information for you and if you try changing the network settings from there does that help?

**Comment by alamoudimoh** [comment]
> Hm so that all looks ok. I found [this post](https://community.home-assistant.io/t/home-assistant-in-a-vm-gives-404-on-docker/255937) while searching which sounds pretty similar. What does it say in the network information for you and if you try changing the network settings from there does that help?

already my IP is static in both Pi and virtual machine. nothing works

**Comment by alamoudimoh** [comment]
> Hm so that all looks ok. I found [this post](https://community.home-assistant.io/t/home-assistant-in-a-vm-gives-404-on-docker/255937) while searching which sounds pretty similar. What does it say in the network information for you and if you try changing the network settings from there does that help?

Home Assistant for me became useless, i cannot do anything, tried setting up different dns, different platforms, Pi, VM with no luck.


tried even setting up on Pi connected to my mobile hotspot which is on different service provider, yet same issue

'''
22-05-01 11:33:20 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/core_samba
22-05-01 11:33:20 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image homeassistant/amd64-addon-samba with tag 9.6.1.
22-05-01 11:33:34 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install homeassistant/amd64-addon-samba:9.6.1: 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/amd64-addon-samba:9.6.1/json: Not Found ("no such image: homeassistant/amd64-addon-samba:9.6.1: No such image: homeassistant/amd64-addon-samba:9.6.1")
'''

**Comment by alamoudimoh** [comment]
> Hm so that all looks ok. I found [this post](https://community.home-assistant.io/t/home-assistant-in-a-vm-gives-404-on-docker/255937) while searching which sounds pretty similar. What does it say in the network information for you and if you try changing the network settings from there does that help?

i have done the following

1. reset my router Huawei 
2. reset my switch and APs (UniFI)
3. formatted my computer (which has nothing)
4. deleted my backups (which yet have nothing to do with this)
5. formatted my Pi4
6. cleaned my disk


the error is not clear, i am tried of spending days not (even though i just reported it two days ago) all my time on this.

with due respect to all, i am not getting any support except from @mdegat01 where is the community

**Comment by DesertNomadBear** [comment]
Hi, I have the exact same configuration, raspberry pi 4, 4GB RAM, 128GB SD card. Running raspbian 5.15, Home Assistant Supervised.

I first noticed the error 2 days ago, I was notified of a deCONZ add-on update, which I couldn't install (same 404 error). Unfortunately I uninstalled the add-on, thinking I could re-install, using the latest version. But I am unable to re-install the add-on since.

Initially I thought it was a deCONZ issue, but yesterday and today I tried installing any random add-on from the official store, and all fail with same error:

Can't install homeassistant/armv7-addon-mosquitto:6.0.2: 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/armv7-addon-mosquitto:6.0.2/json: Not Found ("no such image: homeassistant/armv7-addon-mosquitto:6.0.2: No such image: homeassistant/armv7-addon-mosquitto:6.0.2")

Even after joining the beta channel and installing the 2022.5 version, I still face the same issue.

P.S.: this bug has completely disabled my home automations, since I can no longer use deCONZ raspbee 2 to control my zigbee devices, so an urgent fix is required.

**Comment by alamoudimoh** [comment]
> Hi, I have the exact same configuration, raspberry pi 4, 4GB RAM, 128GB SD card. Running raspbian 5.15, Home Assistant Supervised.
> 
> I first noticed the error 2 days ago, I was notified of a deCONZ add-on update, which I couldn't install (same 404 error). Unfortunately I uninstalled the add-on, thinking I could re-install, using the latest version. But I am unable to re-install the add-on since.
> 
> Initially I thought it was a deCONZ issue, but yesterday and today I tried installing any random add-on from the official store, and all fail with same error:
> 
> Can't install homeassistant/armv7-addon-mosquitto:6.0.2: 404 Client Error for http+docker://localhost/v1.41/images/homeassistant/armv7-addon-mosquitto:6.0.2/json: Not Found ("no such image: homeassistant/armv7-addon-mosquitto:6.0.2: No such image: homeassistant/armv7-addon-mosquitto:6.0.2")
> 
> Even after joining the beta channel and installing the 2022.5 version, I still face the same issue.
> 
> P.S.: this bug has completely disabled my home automations, since I can no longer use deCONZ raspbee 2 to control my zigbee devices, so an urgent fix is required.
> 
> Not sure if/how this matters, but I'm also based in Saudi Arabia.

Good, another one (specifically from Saudi) we are in the way of knowing what could be the issue.

What is ur ISP mine is Zain 5G, yours?

At least to eliminate any blockage from ISPs?

**Comment by DesertNomadBear** [comment]
Zain's 5G as well, but I have tried stc's 5G and same issue. 

Also I just noticed something: the issue affects ONLY addons from home assistant official store.

I am able to install community addons without any issues (just did) from the same UI. At least this narrows down the problem somehow.

**Comment by alamoudimoh** [comment]
> Zain's 5G as well, but I have tried stc's 5G and same issue.
> 
> Also I just noticed something: the issue affects ONLY addons from home assistant official store.
> 
> I am able to install community addons without any issues (just did) from the same UI. At least this narrows down the problem somehow.

it does, honestly speaking I am waiting to hear a complain from Saudi users (as no complains came from the US which has the major users there), and lucky me you showed up and now it is good you added a new good fact that narrows the problem, only official addon @mdegat01 >> this is a valuable info.


i will try to VPN my VM and install addons, but this is not the solution, it will miss up the entire geolocation :(

**Comment by alamoudimoh** [comment]
> > Zain's 5G as well, but I have tried stc's 5G and same issue.
> > Also I just noticed something: the issue affects ONLY addons from home assistant official store.
> > I am able to install community addons without any issues (just did) from the same UI. At least this narrows down the problem somehow.
> 
> it does, honestly speaking I am waiting to hear a complain from Saudi users (as no complains came from the US which has the major users there), and lucky me you showed up and now it is good you added a new good fact that narrows the problem, only official addon @mdegat01 >> this is a valuable info.
> 
> i will try to VPN my VM and install addons, but this is not the solution, it will miss up the entire geolocation :(

did not work with VPN

**Comment by DesertNomadBear** [comment]
Tried installing the addon from cli, using "ha addons install deconz", and I'm getting "Error: Addon deconz with version latest does not exist in the store"

@mdegat01 any thoughts?

**Comment by alamoudimoh** [comment]
> Tried installing the addon from cli, using "ha addons install deconz", and I'm getting "Error: Addon deconz with version latest does not exist in the store"
> 
> @mdegat01 any thoughts?

Can you please check this
https://www.reddit.com/r/homeassistant/comments/ufyskm/cant_install_update_any_addon/i6ygixk?utm_medium=android_app&utm_source=share&context=3

**Comment by alamoudimoh** [comment]
> Tried installing the addon from cli, using "ha addons install deconz", and I'm getting "Error: Addon deconz with version latest does not exist in the store"
> 
> @mdegat01 any thoughts?

Hi,


How good qre you with networking? I know nothing and the guy from reddit who is helping out is asking questions I can not answer

**Comment by DesertNomadBear** [comment]
Just wanted to update:
- I've used nmcli to set the IPv4 status address and google DNS (8.8.8.8)
- I've also confirmed from HA UI that google DNS is in fact set, and I can ping google.com
- I tried using sudo docker pull home assistant/armhf-addon-deconz, and I get:
Using default tag: latest
32f2a8514580: Retrying in 1 second
779cfa977fab: Retrying in 1 second
d1c421d55869: Retrying in 1 second
0c4a3209309e: Waiting
a8073c1f874c: Waiting
error pulling image configuration: download failed after attempts=6: read tcp 192.168.x.x:56534->104.18.122.25:443: read: connection reset by peer

Will post this to Reddit also

**Comment by alamoudimoh** [comment]
@pvizeli help please

**Comment by mdegat01** [comment]
Ok this is very strange. So one key difference between the community add-ons repo and official add-ons repo is the community add-ons repo hosts its images on github's container repository (ghcr.io) whereas the official add-ons repo hosts its images on dockerhub. Are you able to reach https://hub.docker.com/ from your network and pull other images from it? Not necessarily addon ones, just try pulling [golang](https://hub.docker.com/_/golang) or [alpine](https://hub.docker.com/_/alpine) or something. Are you able to do that or do those give errors as well?

**Comment by alamoudimoh** [comment]
> Ok this is very strange. So one key difference I can think of between the community add-ons repo and official add-ons repo is the community add-ons repo hosts its images on github's container repository (ghcr.io) whereas the official add-ons repo hosts its images on dockerhub.
> 
> Are you able to reach https://hub.docker.com/ from your network and pull other images from it? Not necessarily addon ones, just try pulling [golang](https://hub.docker.com/_/golang) or [alpine](https://hub.docker.com/_/alpine) or something. Are you able to do that or do those give errors as well?

apologies for this, but when you say pulling, does this involve terminal apt kinda of coding, i am not that guy, but i will try, or is it download (like the old school, right click, save file as)

**Comment by DesertNomadBear** [comment]
@mdegat01 i tried pulling alpine and I'm getting the same error.

@alamoudimoh just open a terminal, and type "docker pull alpine" and see what happens.

**Comment by alamoudimoh** [comment]
> @mdegat01 i tried pulling alpine and I'm getting the same error.
> 
> @alamoudimoh just open a terminal, and type "docker pull alpine" and see what happens.

Question, what router are you using?

The zain locked?

**Comment by DesertNomadBear** [comment]
Nokia FastMile 5G, unlocked

**Comment by alamoudimoh** [comment]
> Nokia FastMile 5G, unlocked

it just worked, can you try now, just installed an addon

@mdegat01 i honestly do appreciated every single second you put in this, whether it worked or not, but what the support you have shown will never be forgotten, i cant thank you enough

**Comment by alamoudimoh** [comment]
Lol 

back again :(

**Comment by DesertNomadBear** [comment]
I did a fresh install of HA, on a new card, and... still the same issue.

So I decided to get an stc prepaid sim, and install it in the 5G router, and surprise: everything works. Which means either Zain is blocking access to docker hub, or docker hub is somehow blacklisting our IPs.

I guess using my phone as an AP to test stc the first time wasn't the best solution and threw us off the troubleshooting.

**Comment by alamoudimoh** [comment]
> I did a fresh install of HA, on a new card, and... still the same issue.
> 
> So I decided to get an stc prepaid sim, and install it in the 5G router, and surprise: everything works. Which means either Zain is blocking access to docker hub, or docker hub is somehow blacklisting our IPs.
> 
> I guess using my phone as an AP to test stc the first time wasn't the best solution and threw us off the troubleshooting.

So are u saying to get a sim card to be used just for home assistant addons installation?

**Comment by alamoudimoh** [comment]
> I did a fresh install of HA, on a new card, and... still the same issue.
> 
> So I decided to get an stc prepaid sim, and install it in the 5G router, and surprise: everything works. Which means either Zain is blocking access to docker hub, or docker hub is somehow blacklisting our IPs.
> 
> I guess using my phone as an AP to test stc the first time wasn't the best solution and threw us off the troubleshooting.

Can you please send a print screen of the error you receive when you pull image.

I am raising it to Zain and if u can do the same

**Comment by alamoudimoh** [comment]
> > @mdegat01 i tried pulling alpine and I'm getting the same error.
> 
> So it's sounding like docker hub is being blocked. I mean that is a very basic test, alpine is the base image of countless images across dockerhub and every other container registry. If you are getting the same error pulling that then something is very wrong outside of Home Assistant.
> 
> Since you still seem to be able to access github then I guess you have some options available. The simplest one is likely to to fork the official addons repo. In your fork open the config.yaml for the addons you use and find the [image option](https://github.com/home-assistant/addons/blob/master/mariadb/config.yaml#L15) (linked to the one for mariadb as an example). Remove it. Then add your fork as an addon repository and use your versions of those addons. Removing the `image` field will force supervisor to build the addons locally instead of trying to pull the image from dockerhub (which appears to be destined for failure).
> 
> Alternatively you can clone the addons repo locally and copy out the folders for the addons you use into your `/addons` folder. Again make sure to remove `image` from the config.yaml. It's basically the same solution just a different approach.
> 
> I want to be clear, neither of these is a good solution. In both cases you will then have to keep your fork or your local copy up to date manually. And there's not a way to migrate the data/config from the official addon to this new one. You'll have to manually migrate the config and likely start from scratch for data (you can manually migrate the data via the docker cli but its quite difficult and you should avoid it if possible).
> 
> I wish I had a better solution but I really don't if dockerhub is blocked. Hopefully whatever is happening gets cleared up soon so you don't have to maintain these forks long-term and can return to the official addons.

hi me again,


there is something very strange and crazy,

so i run everything on a proxmox and i have installed my development home assistant, everything works normally, i told myself let install another vm, it did not work, so he is the crazy part, there seems to be something, how come two instances connected at the same time, using the same isp, one works and the other 2 dont

**Comment by mdegat01** [comment]
Honestly I don't know. It seems like something outside of HA's control but what it could be I really am not sure. The usual culprits for strange issues like this are:
1) DNS - What's DNS server does HA use? Do you run a local one or use a public one? If you ask it to resolve `hub.docker.com` does it give an answer (try `dig @<ip of dns server> hub.docker.com`)?
2) LAN/Network - When you run `ha network info` does everything you see make sense? Do you see random connection issues in the log? Is your network stable overall or do you have performance issues/drops?
3) ISP - Are there any outages? If you try other random machines that are otherwise working perfectly do they have issues getting to `hub.docker.com` or pulling images? Are there any notifications or messages in your account? Have you tried contacting them to ask?

HA doesn't really have any special logic around docker hub vs other images repositories. If you said "all addons are broken" then I might be inclined to think HA. But since we narrowed it down to "images cannot be pulled from dockerhub on this machine but there are no issues with images hosted on `ghcr.io`" then I'm inclined to look outside HA.

**Comment by M1Sandy** [comment]
same issue here
