### ISSUE TITLE
Failed to change network settings

### ISSUE THREAD

**Issue by tjorim** [home-assistant/supervisor#3610]
### Describe the issue you are experiencing

Trying to change the IPv4 network interface from DHCP to static I get the following pop-up:
`Can't update config on enp4s0: ipv4.addresses: this property cannot be empty for 'method=manual'`

### What is the used version of the Supervisor?

supervisor-2022.04.4

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

8.0.rc3

### What version of Home Assistant Core is installed?

core-2022.5.0b1

### Steps to reproduce the issue

1. Go to Configuration -> System -> Network
2. Expand IPv4 under Configure network interfaces.
3. Select Static instead of DHCP and try to save.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 2:25:38 AM (1 occurrences)
Last logged: 2:25:38 AM

Failed to to call /network/interface/enp4s0/update - Can't update config on enp4s0: ipv4.addresses: this property cannot be empty for 'method=manual'
```

**Comment by mdegat01** [comment]
Sounds like you didn't fill in the other required fields. Did you fill in the other fields below like this or did you just click "static"?
![Screen Shot 2022-04-30 at 12 03 05 AM](https://user-images.githubusercontent.com/2037026/166089861-18a862b1-2d9b-4817-b772-ee851ef2b896.png)

This is the information normally provided by DHCP. If you choose static then you must provide this information yourself.

**Comment by tjorim** [comment]
I filled in all the fields but it does not let me save. I manually changed the settings through nmcli and they are now reflected correctly in the UI.

**Comment by mdegat01** [comment]
Hm that's odd. I'm glad its working for you now but would like more info on what you mean by "it does not let me save" as that sounds like a bug. Do you mean the button to save was disabled? Or you saved but you got an error? If it's the latter I would like to see that error if you can reproduce it.

**Comment by jasonmacdonald** [comment]
I'm having the exact same issue. I get the same error message as @tjorim when I try to hit save. It's also strange that it says it's set to DHCP originally, but it's not using the static IP assigned by my router either, hence the need to change it to static.

![Screenshot 2022-05-03 152247](https://user-images.githubusercontent.com/5718527/166545160-ebc6575a-0128-4ebb-b02e-851deac1461a.png)

![Screenshot 2022-05-03 152536](https://user-images.githubusercontent.com/5718527/166546478-7d7c7b3a-b6d8-4ad6-ae70-c41faf0eb4f8.png)

**Comment by jasonmacdonald** [comment]
I just did another install with` 7.6` instead of "latest" `8.0.0rc3` and everything is working properly now. So, I have to assume something related to HA OS is not playing nicely.

**Comment by devachnid** [comment]
I'm also getting same error when trying to set static IPv4
![image](https://user-images.githubusercontent.com/553647/167210242-b35898cb-7a07-4f92-9421-0b5fd8887fbd.png)
![image](https://user-images.githubusercontent.com/553647/167210267-c7d0d7fb-671b-4f0a-9f61-b10c3c16244a.png)
![image](https://user-images.githubusercontent.com/553647/167210157-31127811-d193-416b-9a2d-ff2df1e7d5be.png)

**Comment by iamandymcinnes** [comment]
I'm seeing the same thing, on debian 11 supported supervisor install with 2022.5.2.

**Comment by adifelice-godaddy** [comment]
It might be at the OS level:
```shell
$ ha network update eth0 --ipv4-method=static --ipv4-address=192.168.1.4/24
Error: Can't update config on eth0: ipv4.addresses: this property cannot be empty for 'method=manual'
```

**Comment by mdegat01** [comment]
@adifelice-godaddy your issue is unrelated. Your command is incorrect, it should be this:
```
ha network update eth0 --ipv4-method static --ipv4-address 192.168.1.4/24
```
When specified correctly this works fine for me, please try again with the correct syntax.

**Comment by adifelice-godaddy** [comment]
@mdegat01  I tried that syntax too before, same error:
```
[core-ssh ~]$ ha network update eth0 --ipv4-address 192.168.1.4/24 --ipv4-method static
Error: Can't update config on eth0: ipv4.addresses: this property cannot be empty for 'method=manual'

[core-ssh ~]$ ha network update eth0 --ipv4-method static --ipv4-address 192.168.1.4
Error: Can't update config on eth0: ipv4.addresses: this property cannot be empty for 'method=manual'

[core-ssh ~]$ ha network update eth0 --ipv4-method static --ipv4-address 192.168.1.4/24
Error: Can't update config on eth0: ipv4.addresses: this property cannot be empty for 'method=manual'
```

**Comment by mdegat01** [comment]
@adifelice-godaddy you're right, that is the same issue now.

So for everyone on here I'm at a bit of a loss. I am unable to reproduce this on any of my systems and I've asked around in the Nabu Casa group and haven't found others seeing this either. So I guess lets start with info collection. Please go to [system health](https://my.home-assistant.io/redirect/system_health/) and click the copy/share button at the top to copy that info for github and share it here. Also for anyone trying this from the CLI please share which addon you are (community or core) using and the version of it.

A few other things that could help, when trying to update network info from the CLI add `--log-level debug` to the command and share the output. Although please scrub the API token first, it should appear in the output twice (`apiToken=<token>` and `Authorization:[Bearer <token>]`).

Additionally it would help if you could execute the following command before trying to update network info:
```
ha supervisor options --logging debug
```
And then share the logs you see when trying to do the update.

**Comment by mdegat01** [comment]
@adifelice-godaddy Please also share system health and supervisor debug logs as well. That looks right so must be something going wrong processing the request.

**Comment by agners** [comment]
@mdegat01 I can reproduce this on a Intel NUC Gen 11. This is the capture of the D-Bus communication on HAOS using `busctl monitor`

[HASupervisorNMDBusCapture.txt](https://github.com/home-assistant/supervisor/files/8653929/HASupervisorNMDBusCapture.txt)

**Comment by mdegat01** [comment]
Thanks @agners . Ok I got a root cause. Unwelcome side effect of #3570 . Putting in a fix now.

**Comment by mdegat01** [comment]
FYI for all following updates here, I put a fix in and published a new release. Which means you should see this working correctly very soon if you are on the dev or beta channels for supervisor. Assuming now issues are reported we will update stable shortly after. If those on here could confirm this works without issue for them on the latest on dev or beta I would appreciate it.

The versions that have the fix are:
Dev - `2022.05.dev0901`
Beta - `2022.05.1`

**Comment by adifelice-godaddy** [comment]
Thank you so much @mdegat01 🎉
