### ISSUE TITLE
Unable to install two instances of Zigbee2MQTT

### ISSUE THREAD

**Issue by NikitaKorneev** [home-assistant/supervisor#3622]
### The problem

Before 2022.05.0 I was able to add two repositories of Zigbee2MQTT and launch two instances Z2M by just adding extra / to the URL of https://github.com/zigbee2mqtt/hassio-zigbee2mqtt, making it https://github.com/zigbee2mqtt/hassio-zigbee2mqtt**/**

I used this to have two zigbee networks in two houses that share the same LAN.

Since the update none of the Z2M is up, when I stop one instance - both stop, when I launch both - both start, but do not work.

When I removed the second Z2M instance and restarted remaining - everything works.

Is there any way I can launch two Z2M addons while using HassOS?

### What version of Home Assistant Core has the issue?

core-2022.5.0b7

### What was the last working version of Home Assistant Core?

core-2022.4.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Addons

## System Health

version | core-2022.5.0b7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.5
Stage | running
Available Repositories | 1030
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.0.rc3
-- | --
update_channel | beta
supervisor_version | supervisor-2022.05.0
docker_version | 20.10.14
disk_total | 58.0 GB
disk_used | 30.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Home Assistant Google Drive Backup (0.107.1), Mosquitto broker (6.1.1), Samba share (9.6.1), AdGuard Home (4.5.1), chrony (2.3.0), Terminal & SSH (9.4.0), room-assistant (2.20.0), Hello ma Nword (0.3), MariaDB (2.4.0), Duck DNS (1.14.0), ESPHome (2022.4.0), Genie (3.0.0), Zigbee2mqtt (1.25.1-1), Grafana (7.5.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 0
views | 17
mode | storage

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.6.2
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: May 4, 2022, 11:22:54 PM (3 occurrences)
Last logged: 2:56:24 PM

Failed to to call /supervisor/options - contains duplicate items: ['https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/'] for dictionary value @ data['addons_repositories']. Got ['https://github.com/esphome/home-assistant-addon', 'https://github.com/mKeRix/hassio-repo', 'https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/', 'https://github.com/hassio-addons/repository', 'https://github.com/sabeechen/hassio-google-drive-backup', 'https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/']
```

**Comment by frenck** [comment]
> Before 2022.05.0 I was able to add two repositories of Zigbee2MQTT and launch two instances Z2M by just adding extra / to the URL of [zigbee2mqtt/hassio-zigbee2mqtt](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt), making it [zigbee2mqtt/hassio-zigbee2mqtt**](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt**/)**

Honestly, the fact that that previously worked is actually a bug and not a feature. IMHO, this is fixed and now working as intended.

**Comment by NikitaKorneev** [comment]
> 

Are there ways to accomplish what I want?

**Comment by NikitaKorneev** [comment]
> Not with a single repository.

I have found a way. I am not sure if i need to tell you....))))

removing the s from https does the job... but do i understand correctly that this workaround is a bug that you will fix? Because i really need that multi-addon capability...

**Comment by NikitaKorneev** [comment]
> You need to create a second add-on

How do I do that? Do I manually import z2m files to _local_ addons folder?

**Comment by mdegat01** [comment]
Or fork it and then add your fork as an addon repo. Or you can install the edge and stable versions of the addon (both in the same repo) and use them both side by side.

But yea as frenck notes there shouldn't be a way to run the exact same addon twice. If you've found a way then you found a bug not a solution.

**Comment by NikitaKorneev** [comment]
> fork the addon repo and then add your fork as a new addon repo

Thank you for solutions, kind stranger!
Do I understand correctly that whenever update arrives I just merge repos and update **my** addon?

**Comment by mdegat01** [comment]
Yep. Fortunately the z2m addon really only updates once a month, it's extremely regular. So every first of the month rebase yours from the upstream and you should be good.

**Comment by NikitaKorneev** [comment]
This is it then. Thx for everyone!
