### ISSUE TITLE
System Unhealth after Update 2022.05.2

### ISSUE THREAD

**Issue by KaportsevIA** [home-assistant/supervisor#3641]
### Describe the issue you are experiencing

After Update Supervisor to 2022.05.2 HA reported about "System not Health - privileged"

### What is the used version of the Supervisor?

supervisor-2022.05.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### What is the version of your installed operating system?

5.13.0-40-generic

### What version of Home Assistant Core is installed?

core-2022.5.4

### Steps to reproduce the issue

Just Update to 2022.05.2

### Anything in the Supervisor logs that might be useful for us?

```txt
Failed to to call /supervisor/stats - System is not ready with state: setup
12:57:47 – (ОШИБКА) Home Assistant Supervisor - первое сообщение получено 12:56:14 и повторялось 29 раз
Can't read Supervisor data: System is not ready with state: setup
12:57:08 – (ПРЕДУПРЕЖДЕНИЕ) Home Assistant Supervisor
Error fetching hassio data: Error on Supervisor API: System is not ready with state: setup
12:57:01 – (ОШИБКА) Home Assistant Supervisor
[140313093363024] Error updating Home Assistant Supervisor: System is not ready with state: setup
12:56:03 – (ОШИБКА) Home Assistant WebSocket API
```

**Comment by KaportsevIA** [comment]
Supervisor log
`  File "/usr/local/lib/python3.9/site-packages/dbus_next/aio/message_bus.py", line 216, in introspect
    return await asyncio.wait_for(future, timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/dbus_next/message_bus.py", line 195, in reply_notify
    BaseMessageBus._check_method_return(reply, err, 's')
  File "/usr/local/lib/python3.9/site-packages/dbus_next/message_bus.py", line 611, in _check_method_return
    raise err
  File "/usr/local/lib/python3.9/site-packages/dbus_next/aio/message_bus.py", line 365, in _message_reader
    if self._unmarshaller.unmarshall():
  File "/usr/local/lib/python3.9/site-packages/dbus_next/_private/unmarshaller.py", line 304, in unmarshall
    self._unmarshall()
  File "/usr/local/lib/python3.9/site-packages/dbus_next/_private/unmarshaller.py", line 243, in _unmarshall
    self.read(16, prefetch=True)
  File "/usr/local/lib/python3.9/site-packages/dbus_next/_private/unmarshaller.py", line 91, in read
    raise EOFError()
EOFError
22-05-16 12:59:17 ERROR (SyncWorker_2) [asyncio] Future exception was never retrieved
future: <Future finished exception=BrokenPipeError(32, 'Broken pipe')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dbus_next/aio/message_bus.py", line 63, in write_callback
    self.offset += self.sock.send(self.buf[self.offset:])
BrokenPipeError: [Errno 32] Broken pipe
22-05-16 12:59:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/9336c2b0 repository
22-05-16 12:59:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
22-05-16 12:59:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/0ecac1d7 repository
22-05-16 12:59:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/cebe7a76 repository
22-05-16 12:59:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/45df7312 repository
22-05-16 12:59:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/8c77aaed repository
22-05-16 12:59:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
22-05-16 12:59:18 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 70 new - 0 remove
22-05-16 12:59:18 INFO (MainThread) [supervisor.addons] Found 9 installed add-ons
22-05-16 12:59:18 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to zigbee2mqtt/zigbee2mqtt-amd64 with version 1.25.0-1
22-05-16 12:59:18 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-configurator with version 5.3.3
22-05-16 12:59:18 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-mosquitto with version 6.1.2
22-05-16 12:59:18 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to sabeechen/hassio-google-drive-backup-amd64 with version 0.107.2
22-05-16 12:59:18 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-samba with version 9.6.1
22-05-16 12:59:18 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to zigbee2mqtt/zigbee2mqtt-amd64 with version 1.25.0-1
22-05-16 12:59:18 INFO (SyncWorker_7) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-check_config with version 3.10.0
22-05-16 12:59:18 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-ssh with version 9.4.0
22-05-16 12:59:18 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/ssh/amd64 with version 10.1.3
22-05-16 12:59:18 INFO (MainThread) [supervisor.backups.manager] Found 7 backup files
22-05-16 12:59:18 INFO (MainThread) [supervisor.discovery] Loaded 1 messages
22-05-16 12:59:18 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
22-05-16 12:59:18 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
22-05-16 12:59:18 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-05-16 12:59:18 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
22-05-16 12:59:18 WARNING (MainThread) [supervisor.resolution.evaluations.base] OS-Agent is not correctly working (more-info: https://www.home-assistant.io/more-info/unsupported/os_agent)
22-05-16 12:59:18 WARNING (MainThread) [supervisor.resolution.evaluations.base] Systemd is not correctly working (more-info: https://www.home-assistant.io/more-info/unsupported/systemd)
22-05-16 12:59:18 WARNING (MainThread) [supervisor.resolution.evaluations.base] Systemd-Resolved is required for DNS in Home Assistant. (more-info: https://www.home-assistant.io/more-info/unsupported/systemd_resolved)
22-05-16 12:59:18 WARNING (MainThread) [supervisor.resolution.evaluations.base] Detected unsupported OS: None (more-info: https://www.home-assistant.io/more-info/unsupported/os)
22-05-16 12:59:18 WARNING (MainThread) [supervisor.resolution.evaluations.base] NetworkManager is not correctly configured (more-info: https://www.home-assistant.io/more-info/unsupported/network_manager)
22-05-16 12:59:18 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-05-16 12:59:18 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy
22-05-16 12:59:18 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
22-05-16 12:59:18 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-05-16 12:59:18 INFO (MainThread) [__main__] Running Supervisor
22-05-16 12:59:18 WARNING (MainThread) [supervisor.core] System running in a unsupported environment!
22-05-16 12:59:18 CRITICAL (MainThread) [supervisor.core] System is running in an unhealthy state and needs manual intervention!
22-05-16 12:59:18 INFO (MainThread) [supervisor.jobs] 'OSManager.mark_healthy' blocked from execution, no Home Assistant OS available
22-05-16 12:59:18 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
22-05-16 12:59:18 INFO (MainThread) [supervisor.core] Supervisor reboot detected
22-05-16 12:59:18 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
22-05-16 12:59:18 INFO (MainThread) [supervisor.core] Supervisor is up and running
22-05-16 12:59:18 INFO (MainThread) [supervisor.host.info] Updating local host information
22-05-16 12:59:18 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-05-16 12:59:18 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-05-16 12:59:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-05-16 12:59:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-05-16 12:59:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-05-16 12:59:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-05-16 12:59:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-05-16 12:59:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-05-16 12:59:19 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-05-16 12:59:19 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-05-16 12:59:19 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found unsupported images: {'portainer/portainer'} (more-info: https://www.home-assistant.io/more-info/unsupported/software)
22-05-16 12:59:20 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-05-16 12:59:20 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy
22-05-16 13:05:03 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-05-16 13:05:03 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-05-16 13:08:52 INFO (SyncWorker_6) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant
22-05-16 13:09:12 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-05-16 13:09:17 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-05-16 13:09:17 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-05-16 13:09:17 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-05-16 13:09:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
22-05-16 13:09:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/ repository
22-05-16 13:09:17 INFO (MainThread) [supervisor.store.git] Update add-on http://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-05-16 13:09:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-05-16 13:09:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/CoolKit-Technologies/ha-addon/ repository
22-05-16 13:09:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-05-16 13:09:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-05-16 13:09:19 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 0 new - 0 remove
22-05-16 13:09:19 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 0 new - 0 remove
22-05-16 13:09:34 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-05-16 13:13:43 INFO (MainThread) [supervisor.backups.manager] Found 7 backup files
22-05-16 13:13:43 INFO (MainThread) [supervisor.backups.manager] Found 7 backup files`

**Comment by frenck** [comment]
> Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

If you had to choose this option, it means you are running a system we don't support.
We only support running Home Assistant Supervised on Debian 11.

**Comment by KaportsevIA** [comment]
OS is Ubuntu 20.04 LTS (same as Debian 11).
