### ISSUE TITLE
`ha os import` states that import was successful, even when no usb stick is connected

### ISSUE THREAD

**Issue by FlorianLudwig** [home-assistant/supervisor#3658]
### Describe the issue you are experiencing

I am having an issue that `ha os import` is not importing my config.

While trying to debug i noticed that `ha os import` always prints `Command completed successfully.` no matter what.

### What is the used version of the Supervisor?

2022.05.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

8.1

### What version of Home Assistant Core is installed?

2022.5.5

### Steps to reproduce the issue

1. have no usb stick connect or have a usb stick with unsupported filesystem connected, ..
2. run `ha os import`

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Additional information

It would be great if the command would be more talkative in general and mention which configs, if any, were imported. Or that no configs were found / imported.

Or maybe a `-v` flag.

**Comment by maxandersen** [comment]
having exact same issue. no idea if import command worked or not.

**Comment by JJFourie** [comment]
Have the same issue.
Running HASSOS v9.0

**Comment by rbwtz** [comment]
请问一下，Linux系统下的的Home Assistant Supervisor，如何在线更新，操作步骤是怎样的？
