### ISSUE TITLE
Supervisor not available, Supervisor Retry Setup: Error on Supervisor API:

### ISSUE THREAD

**Issue by Br3b** [home-assistant/supervisor#3661]
### Describe the issue you are experiencing

Hi there,
I am running Home Assistant in a VM under Proxmox, successfully for a few years.
Suddenly my Supervisor seems stopped working.
I already tried to reboot the host but had no success...
I also tried to reload, restart or repair the supervisor with no success...
![image](https://user-images.githubusercontent.com/49213470/171290897-958fcba4-13ec-4db9-97b6-220e37fb9c3e.png)

For information, I updated my Proxmox Host to the newest version but I am not sure if the problem was already there before.

several weird errors occur:

under settings -> integrations:
![image](https://user-images.githubusercontent.com/49213470/171288357-425846ee-71c4-43d9-a937-6763a85d682d.png)

under settings -> Add-ons:
![image](https://user-images.githubusercontent.com/49213470/171288585-ec345e6c-e593-40bb-8e1c-cd1f856811bb.png)

under settings -> system -> Logs: (Home Assistant Code)
![image](https://user-images.githubusercontent.com/49213470/171288887-ad6750c0-8e08-491a-b175-fc4e39a1f75f.png)
![image](https://user-images.githubusercontent.com/49213470/171288912-4928b56b-e272-472a-8ba4-d62d60bb1d3b.png)
![image](https://user-images.githubusercontent.com/49213470/171288957-fa17be65-430d-46dd-8389-d5e2b4ac2f28.png)

under settings -> system -> Logs: (SUPERVISOR or any other Logs)
![image](https://user-images.githubusercontent.com/49213470/171289068-27a26d4b-f194-4abc-9b5c-15b852a16da7.png)

under settings -> system -> backups:
![image](https://user-images.githubusercontent.com/49213470/171289146-cf5349d6-f2b9-4454-a022-a40e991c329e.png)

under settings -> system -> network:
![image](https://user-images.githubusercontent.com/49213470/171289317-a0afbcd6-013c-4a68-8316-7d4164761eee.png)

under settings -> system -> storage: (same under hardware)
![image](https://user-images.githubusercontent.com/49213470/171289354-b4b689ff-1d95-434f-9a4e-5fb175dcec64.png)

under settings -> system -> system state:
![image](https://user-images.githubusercontent.com/49213470/171289632-327d5a6e-7e34-45f9-a011-34999dbe4f7e.png)

Home Assistant observer:
![image](https://user-images.githubusercontent.com/49213470/171289188-dc2978f4-06dd-4bfb-8939-9643c7cd30cd.png)

I never had any problems like that and my whole setup was running stable over years, therefor I really appreciate any help.
Thanks in advance ;)

### What is the used version of the Supervisor?

![image](https://user-images.githubusercontent.com/49213470/171291486-f52171eb-53c6-4067-828f-4c94b8d9906b.png)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant OS 8.1

### What version of Home Assistant Core is installed?

2022.5.5

### Steps to reproduce the issue

1. start the host
2. problem occurs
3. restart the host
4. problem still occurs

### Anything in the Supervisor logs that might be useful for us?

```txt
see description
```

**Comment by Br3b** [comment]
could get into the system with ssh and read the supervisor logs,
this error is repeating:

``22-06-01 00:28:36 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /info
22-06-01 00:28:36 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /core/info
22-06-01 00:28:36 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /supervisor/info
22-06-01 00:28:36 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /os/info
22-06-01 00:29:20 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /info
22-06-01 00:29:20 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /host/info
22-06-01 00:29:20 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /store
22-06-01 00:29:20 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /core/info
22-06-01 00:29:20 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /supervisor/info
22-06-01 00:29:20 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /os/info
22-06-01 00:29:56 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /refresh_updates
22-06-01 00:29:56 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /info``

**Comment by keesschollaart81** [comment]
@Br3b were you able to recover from this / any workaround perhaps? (I'm facing the same)

**Comment by traindriverrev** [comment]
> @Br3b were you able to recover from this / any workaround perhaps? (I'm facing the same)

I am too!

**Comment by Br3b** [comment]
@keesschollaart81 @traindriverrev 
Hi there, i somehow managed to get it working again but not stable.
Right now I do have the same problem again. Additional with this:
![image](https://user-images.githubusercontent.com/49213470/175140084-6020db0d-039b-4474-a96c-3c7dfada378d.png)

Already rebooted the Host, tried to restart/repair/reload supervisor via console...

**Comment by keesschollaart81** [comment]
I spend some more time trying recovering from this, first I tried updating as now there was a new version of the supervisor available: no luck.

My last resort before doing a clean install was restoring a backup. I was lucky to have a (partial) backup that included homeassistant. So:
- connect via ssh 
- ha backups
- find the most recent backup that includes `homeassistant: true`, note the slug, eg: `f9247a50`
- run ` ha backups restore f9247a50 --homeassistant`

**Comment by mwesten** [comment]
Had the same problems.
Restarted the system.
Now the hassio_supervisor docker instance keeps starting and halting after about 7 seconds, to try to restart again, to halt again, etc. The whole HA is unavailable, so a restore from ha backup is not an option.

a `sudo docker logs hassio_supervisor` gives me the following log:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/udev.sh
[20:32:33] INFO: Using udev information from host
cont-init: info: /etc/cont-init.d/udev.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun supervisor (no readiness notification)
services-up: info: copying legacy longrun watchdog (no readiness notification)
s6-rc: info: service legacy-services successfully started
[20:32:33] INFO: Starting local supervisor watchdog...
22-07-06 20:32:36 INFO (MainThread) [__main__] Initializing Supervisor setup
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 41, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 63, in initialize_coresys
    coresys = CoreSys()
  File "/usr/src/supervisor/supervisor/coresys.py", line 66, in __init__
    self._docker: DockerAPI = DockerAPI()
  File "/usr/src/supervisor/supervisor/docker/__init__.py", line 106, in __init__
    self._info: DockerInfo = DockerInfo.new(self.docker.info())
  File "/usr/src/supervisor/supervisor/docker/__init__.py", line 62, in new
    data["CgroupVersion"],
KeyError: 'CgroupVersion'
22-07-06 20:32:36 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4020253d30>
[20:32:36] WARNING: Halt Supervisor
s6-rc: info: service legacy-services: stopping
[20:32:36] INFO: Supervisor restart after closing
[20:32:36] INFO: Supervisor restart after closing
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
[20:32:36] INFO: Watchdog restart after closing
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

```

Really no clue as to what might have caused it (no changes in the last days) and it seemed to 'just' happen....

**Comment by apfelflo89** [comment]
try updating your docker, that should help! see: https://community.home-assistant.io/t/latest-supervisor-wont-start/437311

**Comment by mwesten** [comment]
Thanks for pushing me in the right direction @apfelflo89 

I indeed was running an old version of docker (v 19.03.15) on Debian buster.
I assumed that it got updated with an apt update and upgrade, but it didn't; and I didn't check....

Of course this was a typical case of PEBKAC ;)

I've upgraded the Debian system from Stretch to Buster, but forgot to check the `etc/apt/sources.list.d/docker.list` file for the version that should be used... this still pointed to the Strech sources. changing that and updating docker inded solved this problem.

Thanks again !

**Comment by netphantm** [comment]
I have the same problems, running on focal:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
...
even after an 'apt upgrade'. Restart from the hassio GUI doesn't work either.
Home Assistant 2022.8.3 Frontend 20220802.0 - latest, on Ubuntu, so not really supported ;)
