### ISSUE TITLE
服务器防火墙关闭8123端口，用nginx代理转发，客户端无法操作重启homeassistant

### ISSUE THREAD

**Issue by installH** [home-assistant/supervisor#3667]
### Describe the issue you are experiencing

1. 防火墙关闭8123端口，用nginx代理转发，客户端点击重新启动按钮无响应。安装新版本homeassistant的点击安装按钮点击也是无法响应
2. 问题：docker版是否支持修改默认运行端口

### What is the used version of the Supervisor?

supervisor-2022.05.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Raspbian GNU/Linux 10 (buster)

### What version of Home Assistant Core is installed?

core-2022.6.1

### Steps to reproduce the issue

1.配置
2.系统
3.重新启动
...

### Anything in the Supervisor logs that might be useful for us?

```txt
没有错误日志
```

**Comment by frenck** [comment]
We only communicate in the English language. Please recreate this issue.

Thanks 👍 

../Frenck
