### ISSUE TITLE
Latest Update 2022.06.0 Not Starting

### ISSUE THREAD

**Issue by Swiftnesses** [home-assistant/supervisor#3692]
### Describe the issue you are experiencing

The supervisor fails to start. Logs attached.

### What is the used version of the Supervisor?

2022.06.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

10

### What version of Home Assistant Core is installed?

2022.6

### Steps to reproduce the issue

Not really - I guess it auto updated and broke.

### Anything in the Supervisor logs that might be useful for us?

```txt
Attached.
```

### Additional information

[_hassio_supervisor_logs.txt](https://github.com/home-assistant/supervisor/files/8970861/_hassio_supervisor_logs.txt)

**Comment by Swiftnesses** [comment]
My mistake, I'm running Debian 11, not 10.

**Comment by frenck** [comment]
Have you installed the latest installer package? It corrects/fixes cgroups configuration (which seems to be part of the issue in your logs).

**Comment by Swiftnesses** [comment]
I don't believe so, can you point me in the direction of what I need to do? Thanks, HA currently down :(

**Comment by frenck** [comment]
<https://www.home-assistant.io/installation/linux#install-home-assistant-supervised>

**Comment by Swiftnesses** [comment]
Fixed.

**Comment by frenck** [comment]
Good! Glad you got it resolved 👍 

../Frenck

**Comment by frelev** [comment]
Not sure if you want me to open a new issue but I have the same/similar problem with 2022.06.0 crashing and restarting.
Running in docker on Debian 20.04.

If the solution is similar as for Swiftnesses can you please provide some more details on the packages that needs to be updated?
Of if/how I can revert back to 2022.5.3


Log:
```
[22:06:51] INFO: Supervisor restart after closing
[22:06:51] INFO: Watchdog restart after closing
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/udev.sh
[22:07:01] INFO: Setup udev backend inside container
[22:07:01] INFO: Update udev information
cont-init: info: /etc/cont-init.d/udev.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun supervisor (no readiness notification)
services-up: info: copying legacy longrun watchdog (no readiness notification)
s6-rc: info: service legacy-services successfully started
[22:07:01] INFO: Starting local supervisor watchdog...
22-06-23 22:07:03 INFO (MainThread) [supervisor.bootstrap] Use the old homeassistant repository for machine extraction
22-06-23 22:07:03 INFO (MainThread) [__main__] Initializing Supervisor setup
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 41, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 63, in initialize_coresys
    coresys = CoreSys()
  File "/usr/src/supervisor/supervisor/coresys.py", line 66, in __init__
    self._docker: DockerAPI = DockerAPI()
  File "/usr/src/supervisor/supervisor/docker/__init__.py", line 106, in __init__
    self._info: DockerInfo = DockerInfo.new(self.docker.info())
  File "/usr/src/supervisor/supervisor/docker/__init__.py", line 62, in new
    data["CgroupVersion"],
KeyError: 'CgroupVersion'
22-06-23 22:07:03 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f550eda0c40>
[22:07:03] WARNING: Halt Supervisor
s6-rc: info: service legacy-services: stopping
[22:07:03] INFO: Supervisor restart after closing
[22:07:03] INFO: Supervisor restart after closing
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
```

Thanks!

**Comment by frenck** [comment]
You have the exact same issue.

Please, if cgroups don't ring a bell, you should consider not using this installation method. It is an advanced installation method that requires extensive Linux knowledge (including Docker, networking, and everything that comes with administering a Linux server). 

Don't get me wrong, I'm not trying to bully or pester.

../Frenck

**Comment by frelev** [comment]
Point taken, I´ve been running this setup for quite some time rock solid (almost) so it´s been a while since I tampered with it.
Was hoping for a hint in the right direction.

**Comment by Swiftnesses** [comment]
@frelev I also ran this for years, without issue.

I believe a Docker upgrade resolved the issue for me. I hope it helps.

**Comment by frelev** [comment]
@Swiftnesses glad you got it sorted out.
So you didn't rerun with the latest installer package? 
I both tried to update docker and pull the latest image for supervisor, unfortunately it did not do the trick for me on Ubuntu. 
Not sure if a 2022.06.1 will fix it or something else needs to be done. 
I can see in the community that more users have the same problem so I would like to post the solution there.

**Comment by N3rdix** [comment]
I experienced the same issue and was able to resolve it by updating docker-ce (although it was >=19.03 as stated in the prerequisites) and rebooted the host once.
I'm still afraid I was not able to forsee this downtime and the reason for it...

**Comment by mykola-dev** [comment]
i have the same issue. it was working for years (i guess from 2018). and now suddenly stopped working. the supervisor docker container failed to start

**Comment by agners** [comment]
> I experienced the same issue and was able to resolve it by updating docker-ce (although it was >=19.03 as stated in the prerequisites) and rebooted the host once.

Where is that prerequisite documented? That would be wrong at this point I guess.
