### ISSUE TITLE
NetworkManager auto connect disabled 

### ISSUE THREAD

**Issue by ikifar2012** [home-assistant/supervisor#3730]
### Describe the issue you are experiencing

I have noticed some issues with NetworkManager on Home Assistant supervised, I began looking into this today and created the supervised installer PR https://github.com/home-assistant/supervised-installer/pull/224 which brings the supervised installer up to date with the Home Assistant OS PR https://github.com/home-assistant/operating-system/pull/1813 which solves part of the issue

However the new config file that is generated by the supervisor does not have the auto connect option enabled, meaning that on reboot the network connection is lost.

The current work around which works for me and others appears to be to enable the auto connect option manually using `nmcli` or `nmtui` as per issue https://github.com/home-assistant/supervised-installer/issues/217

### What is the used version of the Supervisor?

Supervisor 2022.07.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

5.10.0-16-amd64

### What version of Home Assistant Core is installed?

core-2022.7.3

### Steps to reproduce the issue

1. Install Home Assistant Supervised
2. Reboot
3. Attempt to ping anything, you will not have network connectivity until you enable auto connect 

### Anything in the Supervisor logs that might be useful for us?

```txt
Jul 11 22:29:43 ha-su-deb 63dcfc3cc0bf[1103]: 22-07-11 22:29:43 INFO (MainThread) [supervisor.host.network] Updating local network information
```

### Additional information
Upon reboot
![image](https://user-images.githubusercontent.com/20800434/178397985-fe2545d6-9010-4496-b7a4-10d54118332d.png)

**Comment by mdegat01** [comment]
The supervised installer sets this in the network manager config:
https://github.com/home-assistant/supervised-installer/blob/168d844b330b86c0c9b98828bc5d6c1ca6acb930/homeassistant-supervised/etc/NetworkManager/NetworkManager.conf#L4

As does operating system:
https://github.com/home-assistant/operating-system/blob/86cee444bef552e1633fd5bb8029111f1d0365bc/buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf#L4

Is that the autoconnect option you're referring to, `autoconnect-retries-default`? If so what are you suggesting it be changed to?

**Comment by ikifar2012** [comment]
> The supervised installer sets this in the network manager config: https://github.com/home-assistant/supervised-installer/blob/168d844b330b86c0c9b98828bc5d6c1ca6acb930/homeassistant-supervised/etc/NetworkManager/NetworkManager.conf#L4
> 
> As does operating system: https://github.com/home-assistant/operating-system/blob/86cee444bef552e1633fd5bb8029111f1d0365bc/buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf#L4
> 
> Is that the autoconnect option you're referring to, `autoconnect-retries-default`? If so what are you suggesting it be changed to?

It seems the supervisor creates a file in system-connections with the name Supervisor (Interface Name) with the autoconnect parameter set to false thus causing the interface not to connect
![image](https://user-images.githubusercontent.com/20800434/179853138-8cd73b5b-b03a-499b-b8a4-bafbb8298198.png)

**Comment by pssc** [comment]
Yes just been bitten by this tends noto to rear it head untill the host has
been rebooted

**Comment by mdegat01** [comment]
I guess you're going to have to tell me more about steps to reproduce. I have 3 systems running HAOS here and this is what I see in `/etc/system-connections/Supervisor eth0.nmconnection` for each under `[connection]`:
```
[connection]
id=Supervisor eth0
uuid=<uuid>
type=ethernet
interface-name=eth0
llmnr=2
mdns=2
permissions=
timestamp=1657931016
```
```
[connection]
id=Supervisor eth0
uuid=<UUID>
type=ethernet
autoconnect-priority=-999
interface-name=eth0
llmnr=2
mdns=2
permissions=
timestamp=1658515654
```
```
[connection]
id=Supervisor eth0
uuid=<UUID>
type=ethernet
interface-name=eth0
llmnr=2
mdns=2
permissions=
timestamp=1658515634
```
I'm a bit curious how `autoconnect-priority=-999` got into one since I didn't set anything like that but either way no `autoconnect=false`.

Now I realize these are all HAOS but there's no difference in how Supervisor sets the connection details for HAOS vs. Supervised. In fact truth be told Supervisor doesn't set most of those. The only fields from Network Manager supervisor actually sets are in [here](https://github.com/home-assistant/supervisor/blob/main/supervisor/dbus/network/setting/generate.py). For everything else Supervisor just keeps whatever changes you've made to your network configuration via `nmcli` or whatever.

So if your OS is putting that in there then Supervisor won't change it. But Supervisor isn't doing anything to set or modify the `autoconnect` value.

**Comment by ikifar2012** [comment]
This is really strange, I as well as others have been able to recreate this on clean Debian installs, I will do some more testing to see if I can figure out why this is happening, one possibility is the fact that the NetworkManager version on HAOS is more up to date then Debian 
![image](https://user-images.githubusercontent.com/20800434/180519151-4f747e83-fd88-47cf-a828-a9c35153a4ac.png)
![image](https://user-images.githubusercontent.com/20800434/180519204-a492ba52-9e6c-47da-af9e-ecb060604df5.png)

**Comment by mdegat01** [comment]
Can you walk me through it? Like you did a clean debian install and then I assume ran the [supervised installer](https://github.com/home-assistant/supervised-installer). Do you see it in there at that point? Or immediately after starting HA? After modifying the network config using the supervisor UI or CLI? After the next restart of supervisor or reboot of the host? Just take me through to what point it appears for you.

I can probably change supervisor to set `autoconnect=true`, assuming NetworkManager's dbus interface supports it. Although I worry a bit about the impact of that on users with more complex setups potentially with multiple interfaces configured. We have to be careful about changing how supervisor configures the interface as there are so many different permutations out there in user systems. It's very likely any change is going to make someone unhappy somewhere. If it makes sense we'll do it just have to think through the possible consequences.

**Comment by ikifar2012** [comment]
After further testing I can have been able to confirm the fix in https://github.com/home-assistant/supervised-installer/pull/224 does in fact work on a fresh install, although on upgrade or reinstall of the supervised installer it seems to sometimes cause auto connect to be set to false, although I am not 100% certain as to what the issue is, I believe as @mdegat01 has said since the supervisor is not directly causing the issue I don't think adding another parameter to the config is worth the risk if there is a chance it could mess up someone else's config. 

As for now I will close this issue and merge https://github.com/home-assistant/supervised-installer/pull/224 as that seems to mostly solve the issue and doesn't appear to introduce any new bugs
