### ISSUE TITLE
Community add-ons are not visible in the HA frontend, but cannot be added as the repo is already stored

### ISSUE THREAD

**Issue by RosemaryOrchard** [home-assistant/supervisor#3754]
### Describe the issue you are experiencing

I hope I am placing this bug in the right place, but it might be a HA OS issue.

Last week I experienced an issue where the community add-ons were not visible in the HA frontend, but if I tried to add the community repo I received an error telling me that the repo was already added. 

I ended up resolving the issue by editing `/mnt/data/supervisor/store.json` and removing the `https://github.com/hassio-addons/repository` entry and then rebooting the host. After that, I was able to add and use the community addons. 

I assumed this was down to my error or poor connectivity. But numerous HA reboots (including rebooting the host) did not resolve it until I edited the file. And then today in the Home Assistant Discord another user encountered the same issue, hence raising a bug report.

### What is the used version of the Supervisor?

supervisor-2022.07.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.11

### What version of Home Assistant Core is installed?

Home Assistant OS 8.2

### Steps to reproduce the issue

Unfortunately, I don't know what caused this. But I have some things that may be useful to know:

I set HA up in May, and then it was offline until last week, when I updated to the latest releases of HA OS, Supervisor, and Core on 2022-07-18.

I did have issues with GitHub repeatedly being "unavailable" which appeared to be the device/network being banned from the GitHub API for overwhelming it with requests (I installed HACS on 2022-07-18 too).

### Anything in the Supervisor logs that might be useful for us?

```txt
Unfortunately not.
```

**Comment by abertolin** [comment]
I have a similar problem, taked with Rosemary on Discord about it, but also if i remove https://github.com/hassio-addons/repository from /mnt/data/supervisor/store.json and reboot the host, I receive the error "Can't add https://github.com/hassio-addons/repository, already in the store" when i try to "re-add" the repository.
Regards

**Comment by abertolin** [comment]
I have the log of the error:

22-07-29 14:30:38 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-07-29 14:30:38 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/addons repo: Reference at 'HEAD' does not exist.
22-07-29 14:30:38 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-5801' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:105> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 130, in pull
    branch = self.repo.active_branch.name
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 797, in active_branch
    return self.head.reference
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 292, in _get_reference
    sha, target_ref_path = self._get_ref_info(self.repo, self.path)
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 201, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 184, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'HEAD' does not exist
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 109, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 174, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
22-07-29 14:30:38 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 23 remove
22-07-29 14:30:38 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove

After this I lost Core and Community repository

**Comment by TheMMstick** [comment]
I have the same problem with a three days old fresh install of the Home Assistant OS version on a Pi 4. 
Home Assistant 2022.9.5 
Supervisor 2022.09.1 
Operating System 9.0 
Frontend 20220907.2 - latest 

I found several threads regarding this problem in the forum, but no one seemed to be able to find what is causing this problem. As a new HA user it is hard enough to get my head around the system itself, and a bug hindering me to use the extensibility of the system is really hindering.
Please help!

**Comment by gurdeepsembi** [comment]
I have the same issue, when I try to add this repo:
https://github.com/hassio-addons/repository

I get this error:
Can't add https://github.com/hassio-addons/repository, already in the store

**Versions:**
Home Assistant 2022.10.4
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

**Comment by smashmirrorcardboardface** [comment]
I've still got no add ons in the store - just a blank window.
running hassbian on a raspi3b+

any ideas on fixing this?

**Comment by firstchair** [comment]
Same issue here, also not found a solution yet

**Comment by pdubucq** [comment]
Had the same issue. What I did was to add the repository URL changing HTTPS to HTTP and then it worked.

**Comment by abertolin** [comment]
> If you try doing an `ha supervisor repair` in the CLI, does it work after that? Sounds like the clone of the repository repo on disk may have gotten corrupted, that should clear it out and re-clone it.

I did "ha supervisor repair" many time, but nothing change :( .. How can I clear the clone ??

**Comment by MrTango** [comment]
I have the same issue, i don't see the community addon and can not add the repository. But in the terminal i found something like this:
with the command: ha stores:

![grafik](https://user-images.githubusercontent.com/1113628/214789814-0f628759-62d8-4af8-9ac0-f90bc1bf1af7.png)

maybe it's because of the missing name, that community addons don't show up. But since it is a core repository and can not delete it with: ha store delete ...
And i don't find the config files to do it by hand if thats possible.
