### ISSUE TITLE
nodered says via the web interface that it is not running but the automations are all running

### ISSUE THREAD

**Issue by compujunk** [home-assistant/supervisor#3761]
### Describe the issue you are experiencing

When I open the web interface of nodered I get the message: Add-on is not running. please start first.
If I then click ok I get to the addon screen of nodered and then I can click on start whatever I want but nothing changes. When I then look in the logs I see that nodered has just started, which also shows that the automations that I have made in nodered just work. However, I can't get into the web interface.

### What is the used version of the Supervisor?

Supervisor 2022.07.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Operating System 8.4

### What version of Home Assistant Core is installed?

core-2022.7.7

### Steps to reproduce the issue

I have no idea how to repoduce this.
I've done my updates every time but haven't been working on nodered for a while. So I can't say when this first occurred. I did try to restore a backup from a week ago but it didn't work either.
I even removed the addon completely and reinstalled it, but that also had no effect.

### Anything in the Supervisor logs that might be useful for us?

```txt
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.
removed 3 packages, and audited 598 packages in 1s
87 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
cont-init: info: /etc/cont-init.d/customizations.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/node-red.sh
patching file nodes/ui_base.html
Hunk #1 succeeded at 1164 (offset 633 lines).
up to date, audited 1401 packages in 19s
45 packages are looking for funding
  run `npm fund` for details
75 vulnerabilities (26 moderate, 32 high, 17 critical)
To address issues that do not require attention, run:
  npm audit fix
To address all issues possible (including breaking changes), run:
  npm audit fix --force
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
cont-init: info: /etc/cont-init.d/node-red.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun nodered (no readiness notification)
s6-rc: info: service legacy-services successfully started
[14:13:28] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
1 Aug 14:13:29 - [info] 
Welcome to Node-RED
===================
1 Aug 14:13:29 - [info] Node-RED version: v3.0.1
1 Aug 14:13:29 - [info] Node.js  version: v16.16.0
1 Aug 14:13:29 - [info] Linux 5.15.55 x64 LE
1 Aug 14:13:29 - [info] Loading palette nodes
Mon, 01 Aug 2022 12:13:30 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at node:internal/modules/cjs/loader:1105:14
1 Aug 14:13:31 - [info] Dashboard version 3.1.0 started at /endpoint/ui
1 Aug 14:13:32 - [warn] ------------------------------------------------------
1 Aug 14:13:32 - [warn] [node-red-contrib-samsung-tv-control/Samsung-TV] 'samsung-tv-isalive' already registered by module node-red-contrib-samsung-tv
1 Aug 14:13:32 - [warn] [node-red-contrib-samsung-tv-mk/Samsung-TV] 'samsung-tv-isalive' already registered by module node-red-contrib-samsung-tv
1 Aug 14:13:32 - [warn] [node-red-contrib-telegrambot-home/bot] 'telegrambot-config' already registered by module @danielnguyen/node-red-contrib-telegrambot-home
1 Aug 14:13:32 - [warn] [node-red-contrib-telegrambot-home/command] 'telegrambot-command' already registered by module @danielnguyen/node-red-contrib-telegrambot-home
1 Aug 14:13:32 - [warn] [node-red-contrib-telegrambot-home/switch] 'telegrambot-switch' already registered by module @danielnguyen/node-red-contrib-telegrambot-home
1 Aug 14:13:32 - [warn] [node-red-contrib-telegrambot-home/notify] 'telegrambot-notify' already registered by module @danielnguyen/node-red-contrib-telegrambot-home
1 Aug 14:13:32 - [warn] [node-red-contrib-telegrambot-home/payload] 'telegrambot-payload' already registered by module @danielnguyen/node-red-contrib-telegrambot-home
1 Aug 14:13:32 - [warn] [node-red-contrib-wled3/wled2] 'wled2' already registered by module node-red-contrib-wled2
1 Aug 14:13:32 - [warn] ------------------------------------------------------
1 Aug 14:13:32 - [info] Settings file  : /etc/node-red/config.js
1 Aug 14:13:32 - [info] Context store  : 'default' [module=memory]
1 Aug 14:13:32 - [info] User directory : /config/node-red/
1 Aug 14:13:32 - [warn] Projects disabled : editorTheme.projects.enabled=false
1 Aug 14:13:32 - [info] Flows file     : /config/node-red/flows.json
1 Aug 14:13:32 - [info] Server now running at http://127.0.0.1:46836/
1 Aug 14:13:32 - [info] Starting flows
fileServer listening on ip 192.168.178.7 and port 8089
[14:13:32] INFO: Starting NGinx...
1 Aug 14:13:32 - [info] Started flows
1 Aug 14:13:33 - [info] [zigbee2mqtt-server:Homeasisstant Z2M] MQTT Connected
1 Aug 14:13:33 - [info] [zigbee2mqtt-server:Homeasisstant Z2M] Refreshing devices
1 Aug 14:13:33 - [info] [mqtt-broker:6ecffe12.79bf3] Connected to broker: mqtt://192.168.178.7:1883
1 Aug 14:13:33 - [info] [zigbee2mqtt-server:Homeasisstant Z2M] MQTT Subscribed to: "zigbee2mqtt/#
1 Aug 14:13:33 - [info] [zigbee2mqtt-server:Homeasisstant Z2M] Refreshing devices
1 Aug 14:13:37 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:13:37 - [info] [server:Home Assistant] Connected to http://supervisor/core
1 Aug 14:37:31 - [info] [server:Home Assistant] Connection closed to http://supervisor/core
1 Aug 14:37:36 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:37:41 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:37:46 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:37:51 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:37:56 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:01 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:06 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:11 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:16 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:21 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:27 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:33 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:38 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:43 - [info] [server:Home Assistant] Connecting to http://supervisor/core
1 Aug 14:38:43 - [info] [server:Home Assistant] Connected to http://supervisor/core
```

### Additional information

![image](https://user-images.githubusercontent.com/50024099/182229876-f431837a-5731-4149-8c5a-fee084b11b42.png)
![image](https://user-images.githubusercontent.com/50024099/182229925-5e28ba22-4842-4cc1-82bd-89b8ac0fcd4d.png)

**Comment by mdegat01** [comment]
Can you share your supervisor logs?

**Comment by compujunk** [comment]
22-08-03 11:27:15 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 11:32:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-08-03 11:32:19 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 11:37:23 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 11:42:27 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 11:47:30 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 11:52:33 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-08-03 11:55:44 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-08-03 11:57:36 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:02:15 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-08-03 12:02:39 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:05:02 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-08-03 12:05:02 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-08-03 12:07:42 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:12:46 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:17:50 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:22:54 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:27:58 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:32:20 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-08-03 12:33:02 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:33:36 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:33:36 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:33:36 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:33:36 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:33:38 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:33:55 INFO (SyncWorker_5) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/generic-x86-64-homeassistant
22-08-03 12:33:55 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
22-08-03 12:33:55 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-08-03 12:34:30 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-08-03 12:34:32 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-08-03 12:34:32 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-08-03 12:34:33 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-08-03 12:34:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/net-daemon/homeassistant-addon repository
22-08-03 12:34:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-08-03 12:34:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-08-03 12:34:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-08-03 12:34:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
22-08-03 12:34:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/marcelveldt/hassio-addons-repo repository
22-08-03 12:34:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-08-03 12:34:34 WARNING (SyncWorker_5) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS Server DEVELOPMENT
22-08-03 12:34:34 WARNING (SyncWorker_5) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Google Assistant Webserver
22-08-03 12:34:34 WARNING (SyncWorker_1) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS Server DEVELOPMENT
22-08-03 12:34:34 WARNING (SyncWorker_1) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Google Assistant Webserver
22-08-03 12:34:34 INFO (MainThread) [supervisor.store] Loading add-ons from store: 80 all - 0 new - 0 remove
22-08-03 12:34:34 INFO (MainThread) [supervisor.store] Loading add-ons from store: 80 all - 0 new - 0 remove
22-08-03 12:34:38 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:34:40 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt-admin'
22-08-03 12:34:41 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
22-08-03 12:34:44 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:34:44 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:34:44 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:34:44 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:34:47 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:35:13 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
22-08-03 12:35:13 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-08-03 12:35:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-08-03 12:35:14 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-08-03 12:35:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-08-03 12:36:35 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:35 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:35 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:35 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:37 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:50 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:50 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:50 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:57 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:57 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_nodered is already running!
22-08-03 12:36:57 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:57 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:59 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:59 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_nodered is already running!
22-08-03 12:36:59 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-08-03 12:36:59 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)

**Comment by compujunk** [comment]
and this is my NR config
certfile: fullchain.pem
credential_secret: <My secret>
http_node:
  password: <My secret>
  username: <My secret>
http_static:
  password: <My secret>
  username: <My secret>
init_commands: []
keyfile: privkey.pem
npm_packages:
  - node-red-admin
ssl: true
system_packages: []
theme: midnight-red
require_ssl: true

**Comment by mdegat01** [comment]
Reproduced on mine and located the issue. Fix is in, expect an update soon

**Comment by Scags104** [comment]
issue still persists on 2022.8.1

**Comment by gieljnssns** [comment]
https://github.com/hassio-addons/addon-adguard-home/issues/331#issuecomment-1204937856

**Comment by Scags104** [comment]
> issue still persists on 2022.8.1

cancel this - began working about 1 hour after hard reboot.... timing is odd. but working is working.

**Comment by compujunk** [comment]
> 

Yes this works

**Comment by compujunk** [comment]
> Also having this issue too, for me it was fine last night. Today I can't get to the UI due to this issue. Same logs etc
> 
> @compujunk If you go to `<homeassistantip>:1880` and login with your Home Assistant login, you can get to the instance. This is just a Supervisor issue

Yes this works
