### ISSUE TITLE
https client traffic not directed to NGINX Home Assistant SSL proxy

### ISSUE THREAD

**Issue by mvaneijken** [home-assistant/supervisor#3805]
### Describe the issue you are experiencing

Not sure if this a supervisor issue or something in the add-on, but since last night my Home Assistant instance was not accessible over port 443 which should direct to the NGINX Home Assistant SSL proxy add-on. 

When running a tcpdump network trace I saw that the IP where https traffic was heading to belonged to the Visual Studio Code add-on. 

I was able to recover from this by doing this:
1. Stop both the Visual Studio Code add-on and NGINX Home Assistant SSL proxy add-on 
2. Start the NGINX Home Assistant SSL proxy add-on first 
3. Start the Visual Studio Code add-on 

I do not know how this could hapen, only I saw that there was an update for the Visual Studio Code add-on and that this particular container was restarted last night. I does not explain for me why it had port 443 directed to that container. As far as I see it does not doe anything with that port.

### What is the used version of the Supervisor?

supervisor-2022.08.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

11.4

### What version of Home Assistant Core is installed?

20220802.0

### Steps to reproduce the issue

I cannot reproduce.

### Anything in the Supervisor logs that might be useful for us?

```txt
None
```

**Comment by mdegat01** [comment]
That's strange. I have a reverse proxy addon and the vscode addon in a similar setup and didn't see any issues after updating vscode. If you restart the host is it reproducible? Like will it get back into this state if you don't specifically order the startups like you did?

**Comment by mvaneijken** [comment]
I wasn't able to reproduce until I had a power outage today. After the reboot it pas pointing to the grafana addon. When I stopped that addon and restarted the observer and supervisor addons it was pointing to the maradb addon. It seems to be a random thing. What stands out is that the port mapping is pointing to the same IP 172.30.33.8 (but with different containers behind it). I'm still trying to figuring out how this mapping is controlled.

**Comment by mvaneijken** [comment]
When I lookup the iptables output it shows this (which is interesting because most ports are displayed twice, including port 443. Port 443 forwarding on IP 172.30.33.9/32 is actually the correct one, but is not taking precense):

root@homeassistant:~# iptables -S
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o hassio -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o hassio -j DOCKER
-A FORWARD -i hassio ! -o hassio -j ACCEPT
-A FORWARD -i hassio -o hassio -j ACCEPT
-A DOCKER -d 172.30.32.6/32 ! -i hassio -o hassio -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.30.33.0/32 ! -i hassio -o hassio -p tcp -m tcp --dport 9541 -j ACCEPT
-A DOCKER -d 172.30.33.1/32 ! -i hassio -o hassio -p tcp -m tcp --dport 3306 -j ACCEPT
-A DOCKER -d 172.30.33.2/32 ! -i hassio -o hassio -p tcp -m tcp --dport 8884 -j ACCEPT
-A DOCKER -d 172.30.33.2/32 ! -i hassio -o hassio -p tcp -m tcp --dport 8883 -j ACCEPT
-A DOCKER -d 172.30.33.2/32 ! -i hassio -o hassio -p tcp -m tcp --dport 1884 -j ACCEPT
-A DOCKER -d 172.30.33.2/32 ! -i hassio -o hassio -p tcp -m tcp --dport 1883 -j ACCEPT
-A DOCKER -d 172.30.33.5/32 ! -i hassio -o hassio -p tcp -m tcp --dport 8000 -j ACCEPT
-A DOCKER -d 172.30.33.7/32 ! -i hassio -o hassio -p tcp -m tcp --dport 8086 -j ACCEPT
-A DOCKER -d 172.30.33.8/32 ! -i hassio -o hassio -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.30.33.8/32 ! -i hassio -o hassio -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.30.33.14/32 ! -i hassio -o hassio -p tcp -m tcp --dport 8485 -j ACCEPT
-A DOCKER -d 172.30.33.0/32 ! -i hassio -o hassio -p tcp -m tcp --dport 8884 -j ACCEPT
-A DOCKER -d 172.30.33.0/32 ! -i hassio -o hassio -p tcp -m tcp --dport 8883 -j ACCEPT
-A DOCKER -d 172.30.33.0/32 ! -i hassio -o hassio -p tcp -m tcp --dport 1884 -j ACCEPT
-A DOCKER -d 172.30.33.0/32 ! -i hassio -o hassio -p tcp -m tcp --dport 1883 -j ACCEPT
-A DOCKER -d 172.30.33.3/32 ! -i hassio -o hassio -p tcp -m tcp --dport 9541 -j ACCEPT
-A DOCKER -d 172.30.33.5/32 ! -i hassio -o hassio -p tcp -m tcp --dport 3306 -j ACCEPT
-A DOCKER -d 172.30.33.8/32 ! -i hassio -o hassio -p tcp -m tcp --dport 8485 -j ACCEPT
-A DOCKER -d 172.30.33.9/32 ! -i hassio -o hassio -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.30.33.9/32 ! -i hassio -o hassio -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i hassio ! -o hassio -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o hassio -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN

First I will try to remove the duplicate lines to see if that helps.

**Comment by mvaneijken** [comment]
This is clearly not a bug as I found out after quite some digging that somehow there was a iptables configuration saved back in October 2021 and that config was loaded at every reboot. From the moment I removed that it all worked as it should.
