### ISSUE TITLE
Unable to update from Supervisor 2022.08.3 to 2022.08.5

### ISSUE THREAD

**Issue by mattlward** [home-assistant/supervisor#3831]
### Describe the issue you are experiencing

I am getting the following error in the supervisor log when I try to update to the latest version.
```
22-08-29 21:13:17 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.08.5: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.08.5&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io on 192.168.1.1:53: read udp 192.168.1.6:36087->192.168.1.1:53: read: connection refused")
22-08-29 21:13:17 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.08.5: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.08.5&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io on 192.168.1.1:53: read udp 192.168.1.6:36087->192.168.1.1:53: read: connection refused")
```

### What is the used version of the Supervisor?

supervisor-2022.08.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

5.10.0-16-amd64 ehci_hcd

### What version of Home Assistant Core is installed?

2022.8.7

### Steps to reproduce the issue

1.Attempt to update supervisor
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-08-29 21:13:17 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.08.5: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.08.5&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io on 192.168.1.1:53: read udp 192.168.1.6:36087->192.168.1.1:53: read: connection refused")
22-08-29 21:13:17 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/amd64-hassio-supervisor:2022.08.5: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2022.08.5&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-supervisor&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io on 192.168.1.1:53: read udp 192.168.1.6:36087->192.168.1.1:53: read: connection refused")
```

**Comment by mattlward** [comment]
I was able to solve this issue... Not sure why it suddenly became an issue but I had to make a docker registry entry.

[https://www.home-assistant.io/more-info/dockerhub-rate-limit/](url)

**Comment by gnicita** [comment]
I also have the same problem, but how did you solve it?
Thank you Giu

**Comment by mattlward** [comment]
Please read the link I pasted earlier.  Not complex at all.

**Comment by mattlward** [comment]
I am sorry, the link is now broken!  So, I went into the Add On Store and clicked the 3 dots in the upper right corner and added a registry for hub.docker.com.

Please see the following: [https://www.home-assistant.io/more-info/dockerhub-rate-limit/](url)

Sorry I was a little snippy earlier.
