### ISSUE TITLE
Supervisor Unhealthy / Can't update

### ISSUE THREAD

**Issue by cilliankenny** [home-assistant/supervisor#3855]
### Describe the issue you are experiencing

Hello,

I'm having an issue in that I can't update HASS Core, OS, or Addons. These all point to an unhealthy error in Supervisor.

When I try to update the supervisor, I get a separate error. I'm not sure where the issue is coming from.

### What is the used version of the Supervisor?

Supervisor 2022.08.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

8.4

### What version of Home Assistant Core is installed?

Home Assistant 2022.8.6

### Steps to reproduce the issue

1. Try to update the supervisor

### Anything in the Supervisor logs that might be useful for us?

```txt
22-09-10 10:23:50 ERROR (MainThread) [supervisor.supervisor] Can't fetch AppArmor profile https://version.home-assistant.io/apparmor.txt: Cannot connect to host version.home-assistant.io:443 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)]
22-09-10 10:23:50 CRITICAL (MainThread) [supervisor.supervisor] Abort update because of an issue with AppArmor: Can't fetch AppArmor profile https://version.home-assistant.io/apparmor.txt: Cannot connect to host version.home-assistant.io:443 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)]
```

### Additional information

[546773096608] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, system is not healthy
[547016257024] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, system is not healthy
[546639950416] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, system is not healthy
[545432568496] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, system is not healthy

![image](https://user-images.githubusercontent.com/82086623/189478995-3d7e97aa-8c5e-49fd-a301-0fb5630e0b6d.png)
![image](https://user-images.githubusercontent.com/82086623/189479003-231933d9-d24b-4470-aa70-9e73abbe5131.png)
https://www.home-assistant.io/more-info/unhealthy/supervisor

**Comment by pvizeli** [comment]
Seems you have an firewall that make our TLS connection insecure: Abort update because of an issue with AppArmor: Can't fetch AppArmor profile https://version.home-assistant.io/apparmor.txt: Cannot connect to host version.home-assistant.io:443 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)]

Once you fixed that or by-pass the URL it should work
