### ISSUE TITLE
test_network.py includes cloudflare's 1.1.1.1

### ISSUE THREAD

**Issue by optimusprimespace** [home-assistant/supervisor#3859]
### Describe the issue you are experiencing

Why is the test_network.py communicating with cloudflare's Domain Name Servers? Does this also mean that it can overwrite a home networks internal dns service like (AdGuard Home, Pihole, etc.)? If so, why include cloudflare dns, when you can add the internal ip address of HA?

### What is the used version of the Supervisor?

NA

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

NA

### What version of Home Assistant Core is installed?

NA

### Steps to reproduce the issue

NA

### Anything in the Supervisor logs that might be useful for us?

```txt
NA
```

**Comment by pvizeli** [comment]
That is not a bug. Feature request to forum please

**Comment by mdegat01** [comment]
Please don't make a feature request either.

> Does this also mean that it can overwrite a home networks internal dns service like (AdGuard Home, Pihole, etc.)?

No. You are clearly confused.  This is test code, not production code. See my response here: <https://community.home-assistant.io/t/cloudflares-dns-hard-coded/460653/2>
