### ISSUE TITLE
Supervisor 2022.9.1 un-supported state

### ISSUE THREAD

**Issue by to4ko** [home-assistant/supervisor#3876]
### Describe the issue you are experiencing

Getting unsupported state after supervisor update to 2022.9.1

followed the link (connectivity check https://www.home-assistant.io/more-info/unsupported/connectivity_check) did ssh and run the mentioned command with no success.

host reboot - no changes

supervised installation script re-run - no changes. still un-supported

### What is the used version of the Supervisor?

supervisor-2022.09.1

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

	5.18.0-0.deb11.4-amd64

### What version of Home Assistant Core is installed?

core-2022.9.5

### Steps to reproduce the issue

update supervisor to 2022.9.1 at debian 11

### Anything in the Supervisor logs that might be useful for us?

```txt
only complains on connectivity check

22-09-19 19:01:01 WARNING (MainThread) [supervisor.resolution.evaluations.base] Connectivity checks are required for Home Assistant. (more-info: https://www.home-assistant.io/more-info/unsupported/connectivity_check)
```

**Comment by Caligo82** [comment]
Can confirm this issue on the same configuration. I might add that I updated the OS-Agent to 1.3.0 after the Supervisor 9.1 Update. Was running 1.2.2 beforehands. I only discovered they updated it during my search for clues why my installation was suddenly unhealthy.

**Comment by BebeMischa** [comment]
I'm running OS Agent 1.3.0 for a long time now. It has no influence on this bug.

**Comment by mdegat01** [comment]
Hm it seems to work for me turning it on and off. Maybe its a timing thing? We reload information from the host roughly every two hours. Supervisor can be forced to do that immediately by running this:
```
ha host reload
```
We also run the checks to see if the system is supported or not once an hour. Supervisor can be forced to do that immediately by running this:
```
ha resolution healthcheck
```
So in theory it could take up to 3 hours to go away but can speed that up with these two commands. At least until #3872 makes it to production, then it will be immediate.

If you still see it after running these two commands (or after several hours) then I guess I'll need more info. Please share the result of this after running the `busctl` command:
```
gdbus introspect --system --dest org.freedesktop.NetworkManager --object-path /org/freedesktop/NetworkManager
```
And also please share what's in your `NetworkManager.conf` file
```
cat /etc/NetworkManager/NetworkManager.conf
```

**Comment by to4ko** [comment]
> Hm it seems to work for me turning it on and off. Maybe its a timing thing? We reload information from the host roughly every two hours. Supervisor can be forced to do that immediately by running this:
> 

looks like it's not changing the flag
![image](https://user-images.githubusercontent.com/45161980/191102757-07b38498-a87b-42e0-a3e2-c41735595069.png)



[gdbus.txt](https://github.com/home-assistant/supervisor/files/9601920/gdbus.txt)
[nm.txt](https://github.com/home-assistant/supervisor/files/9601921/nm.txt)

**Comment by mdegat01** [comment]
Yea I see it. Neither of you have a `ConnectivityCheckUri` it appears. That should be set to `http://checkonline.home-assistant.io/online.txt`. I wonder why that's not set...

Supervisor cannot change that. You'll have to add this to your `NetworkManager.conf` file manually:
```
[connectivity]
uri=http://checkonline.home-assistant.io/online.txt
interval=600
```
I'll update the unsupported doc to mention this.

**Comment by BebeMischa** [comment]
But why this was not a problem until today's update?

**Comment by mdegat01** [comment]
Because there was never an unsupported check for this before. Supervisor just assumed it worked or had silent failures. Now it tells you there's something wrong.

**Comment by BebeMischa** [comment]
ok, i see. What is the correct path to NetworkManager.conf ? I have to go there with SSH...

**Comment by mdegat01** [comment]
`/etc/NetworkManager/NetworkManager.conf`. The same file you shared before.

**Comment by to4ko** [comment]
> `/etc/NetworkManager/NetworkManager.conf`. The same file you shared before.

thanks! it all fine aster network-manager restart

[supervisor.resolution.evaluations.base] Clearing UnsupportedReason.CONNECTIVITY_CHECK as reason for unsupported

**Comment by BebeMischa** [comment]
Maybe it's, because my install is already some years old and updated on the run? It may not been there two, three years ago... ;-)

**Comment by mdegat01** [comment]
Makes sense. I thought the supervised installer updated the NetworkManager.conf when re-run though. I guess it doesn't do that. Anyway glad it worked, putting in a PR for the doc change now.

**Comment by BebeMischa** [comment]
Confirm, edit done, reboot done, supported again. Thanks for your explanation! @mdegat01

**Comment by Madseason41** [comment]
I am running into issues as well. If I make the NetworkManager.conf changes and reboot, the connectivity check issue goes away but then I get unsupported due to systemjournal. If I run the update script, then the NetworkManager.conf change disappears.

Debian 11
Home Assistant 2022.11.1
Supervisor 2022.10.2
OS-agent 1.2.1
