### ISSUE TITLE
Use of constant on JobConditions eliminates job condition control

### ISSUE THREAD

**Issue by dcmartin** [home-assistant/supervisor#3900]
### Describe the issue you are experiencing

Use of the constant ADDON_UPDATE_CONDITIONS rather than explicit list of interpreted conditions eliminates ability to turn off job condition (e.g. "healthy").

Change:

diff --git a/supervisor/addons/__init__.py b/supervisor/addons/__init__.py
index 6efb4a52..04cdd08c 100644
--- a/supervisor/addons/__init__.py
+++ b/supervisor/addons/__init__.py
@@ -145,7 +145,13 @@ class AddonManager(CoreSysAttributes):
                 self.sys_capture_exception(err)
 
     @Job(
-        conditions=ADDON_UPDATE_CONDITIONS,
+        conditions=[
+    JobCondition.FREE_SPACE,
+    JobCondition.HEALTHY,
+    JobCondition.INTERNET_HOST,
+    JobCondition.PLUGINS_UPDATED,
+    JobCondition.SUPERVISOR_UPDATED,
+],
         on_condition=AddonsJobError,
     )
     async def install(self, slug: str) -> None:
@@ -243,7 +249,13 @@ class AddonManager(CoreSysAttributes):
         _LOGGER.info("Add-on '%s' successfully removed", slug)
 
     @Job(
-        conditions=ADDON_UPDATE_CONDITIONS,
+        [
+    JobCondition.FREE_SPACE,
+    JobCondition.HEALTHY,
+    JobCondition.INTERNET_HOST,
+    JobCondition.PLUGINS_UPDATED,
+    JobCondition.SUPERVISOR_UPDATED,
+],
         on_condition=AddonsJobError,
     )
     async def update(self, slug: str, backup: bool | None = False) -> None:

### What is the used version of the Supervisor?

2022.09.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

9.0

### What version of Home Assistant Core is installed?

2022.09.7

### Steps to reproduce the issue

Attempt to change job condition healthy to ignore; find that is it not ignored.

diff --git a/supervisor/addons/__init__.py b/supervisor/addons/__init__.py
index 6efb4a52..04cdd08c 100644
--- a/supervisor/addons/__init__.py
+++ b/supervisor/addons/__init__.py
@@ -145,7 +145,13 @@ class AddonManager(CoreSysAttributes):
                 self.sys_capture_exception(err)
 
     @Job(
-        conditions=ADDON_UPDATE_CONDITIONS,
+        conditions=[
+    JobCondition.FREE_SPACE,
+    JobCondition.HEALTHY,
+    JobCondition.INTERNET_HOST,
+    JobCondition.PLUGINS_UPDATED,
+    JobCondition.SUPERVISOR_UPDATED,
+],
         on_condition=AddonsJobError,
     )
     async def install(self, slug: str) -> None:
@@ -243,7 +249,13 @@ class AddonManager(CoreSysAttributes):
         _LOGGER.info("Add-on '%s' successfully removed", slug)
 
     @Job(
-        conditions=ADDON_UPDATE_CONDITIONS,
+        [
+    JobCondition.FREE_SPACE,
+    JobCondition.HEALTHY,
+    JobCondition.INTERNET_HOST,
+    JobCondition.PLUGINS_UPDATED,
+    JobCondition.SUPERVISOR_UPDATED,
+],
         on_condition=AddonsJobError,
     )
     async def update(self, slug: str, backup: bool | None = False) -> None:

### Anything in the Supervisor logs that might be useful for us?

```txt
Warning is emitted as expected, but condition is not ignored.
```

### Additional information

diff --git a/supervisor/addons/__init__.py b/supervisor/addons/__init__.py
index 6efb4a52..04cdd08c 100644
--- a/supervisor/addons/__init__.py
+++ b/supervisor/addons/__init__.py
@@ -145,7 +145,13 @@ class AddonManager(CoreSysAttributes):
                 self.sys_capture_exception(err)
 
     @Job(
-        conditions=ADDON_UPDATE_CONDITIONS,
+        conditions=[
+    JobCondition.FREE_SPACE,
+    JobCondition.HEALTHY,
+    JobCondition.INTERNET_HOST,
+    JobCondition.PLUGINS_UPDATED,
+    JobCondition.SUPERVISOR_UPDATED,
+],
         on_condition=AddonsJobError,
     )
     async def install(self, slug: str) -> None:
@@ -243,7 +249,13 @@ class AddonManager(CoreSysAttributes):
         _LOGGER.info("Add-on '%s' successfully removed", slug)
 
     @Job(
-        conditions=ADDON_UPDATE_CONDITIONS,
+        [
+    JobCondition.FREE_SPACE,
+    JobCondition.HEALTHY,
+    JobCondition.INTERNET_HOST,
+    JobCondition.PLUGINS_UPDATED,
+    JobCondition.SUPERVISOR_UPDATED,
+],
         on_condition=AddonsJobError,
     )
     async def update(self, slug: str, backup: bool | None = False) -> None:

**Comment by mdegat01** [comment]
No, that's not how this works. That list gets used here:
https://github.com/home-assistant/supervisor/blob/eb621f6a2cbd2da5f081d98e168269b70d9aa9d4/supervisor/jobs/decorator.py#L168-L171

As you can see, the first thing it does is build a list of `used_conditions` by taking that constant list and removing the ones you've ignored.

Please tell me what issue you're actually having rather then speculating on the root cause. There's nothing wrong with using a list of constants in the spot you're identifying, its been doing that since the Job annotation was created and the Job annotation is designed to work that way.

**Comment by dcmartin** [comment]
The use of constants appears to defeat the ability to ignore a job condition; system will not update an addon if 'healthy' is false, but ignored.

**Comment by mdegat01** [comment]
Please share the supervisor log after you try to update an addon with the job condition ignored.
