### ISSUE TITLE
Ghost addon

### ISSUE THREAD

**Issue by Dhy19971** [home-assistant/supervisor#3905]
### Describe the issue you are experiencing

All addons are displayed as not started. It is impossible to start them with the start button.

From the logs it is possible to see that in reality the addons are working (looking for the addon via local ip everything works correctly).

### What is the used version of the Supervisor?

Supervisor 2022.09.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

Home Assistant 2022.9.7

### What version of Home Assistant Core is installed?

Operating System 9.0

### Steps to reproduce the issue

1.Fresh installation of HA on raspberry via ISO
2.Previous back up restore to restore addons(whose integrity and status are known)
3.addons displayed and managed as inactive when they are active
4.All after last update

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

**Comment by mdegat01** [comment]
Yes there was an issue identified with restore. There's a new monitor which keeps track of the each addon's state by watching its docker container and it was not being attached after a restore from backup. A fix has been merged for it already https://github.com/home-assistant/supervisor/pull/3893

I also just cut a new beta for supervisor (`2022.09.2`) which includes the fix if you want to try it out.
