### ISSUE TITLE
Update of Supervisor failed: Can't fix start tag: 404 Client Error

### ISSUE THREAD

**Issue by beethu** [home-assistant/supervisor#3941]
### Describe the issue you are experiencing

When I want to update hassio supervisor from 2022.09.1 to 2022.10.1 I'm getting the following error:

homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't fix start tag: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0/json: Not Found ("no such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0: No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0")

System Info:
Home Assistant 2022.10.2
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221006.0 - latest

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:260
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:53:43 (1 occurrences)
Last logged: 10:53:43

[139975675406720] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't fix start tag: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0/json: Not Found ("no such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0: No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 258, in async_install
    await async_update_supervisor(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Update of Supervisor failed: Can't fix start tag: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0/json: Not Found ("no such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0: No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 260, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't fix start tag: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0/json: Not Found ("no such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0: No such image: ghcr.io/home-assistant/amd64-hassio-supervisor:2022.10.0")
```

### System Health information

Nothing in "Repairs" section.

### Supervisor diagnostics
[diagnostics.txt](https://github.com/home-assistant/supervisor/files/9758132/diagnostics.txt)

**Comment by mdegat01** [comment]
For future reference, please use the link in the issue template to get to system health information - https://my.home-assistant.io/redirect/system_health/. It is in repairs, its in the 3 dot menu in the top right. The link simply opens it for easy copy and paste though. Also as the template notes, drag and drop the diagnostics file *do not* copy the contents. Otherwise it makes the issue enormous.

**Comment by mdegat01** [comment]
AS for the actual issue at hand, that is quite strange. That image is definitely available. Can you share the result of `ha resolution info` and `ha network info` to see if there's any network issues that could be causing it?

**Comment by beethu** [comment]
Hi, sorry for that! I'll have it in mind in any next issue.

Here are the responses from those commands:

[core-ssh ~]$ ha resolution info                                                                                                                                                                                                                                      
checks:                                                                                                                                                                                                                                                               
- enabled: true                                                                                                                                                                                                                                                       
  slug: network_interface_ipv4                                                                                                                                                                                                                                        
- enabled: true                                                                                                                                                                                                                                                       
  slug: core_security                                                                                                                                                                                                                                                 
- enabled: true                                                                                                                                                                                                                                                       
  slug: free_space
- enabled: true
  slug: addon_pwned
- enabled: true
  slug: dns_server
- enabled: true
  slug: backups
- enabled: true
  slug: dns_server_ipv6
- enabled: true
  slug: supervisor_trust
issues:
- context: system
  reference: null
  type: no_current_backup
  uuid: 9239c09984ae438fa377016e425795ae
- context: supervisor
  reference: null
  type: update_failed
  uuid: 66dc41f7e5464b81857d076b17b03c66
suggestions:
- auto: false
  context: system
  reference: null
  type: create_full_backup
  uuid: 465f70c48a2f431d8f9c4b588e30e6d3
unhealthy: []
unsupported: []

[core-ssh ~]$ ha network info
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: true
interfaces:
- connected: true
  enabled: true
  interface: enp0s3
  ipv4:
    address:
    - 192.168.0.30/24
    gateway: 192.168.0.1
    method: auto
    nameservers:
    - 192.168.0.1
    ready: true
  ipv6:
    address:
    - fe80::2c0d:dc12:a0b2:64c/64
    gateway: null
    method: auto
    nameservers: []
    ready: false
  primary: true
  type: ethernet
  vlan: null
  wifi: null
supervisor_internet: true

**Comment by beethu** [comment]
After running that command it seems that now the "wrong" update notification was removed and I was able to update OS + Core! Everything is working normal now.
Thanks!
