### ISSUE TITLE
Backup - Unknown error, see supervisor logs

### ISSUE THREAD

**Issue by almico** [home-assistant/supervisor#3954]
### Describe the issue you are experiencing

I ask to create a full backup, and, after a few minutes, this is what I see on the screen:
![image](https://user-images.githubusercontent.com/15247405/195783918-bbaa33b2-e9f8-4447-9459-910dba8eefb4.png)

There is absolutely no error in the Supervisor Log.

I'm facing exactly the same issue as [this](https://github.com/home-assistant/supervisor/issues/2624).

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Create a full backup

### Anything in the Supervisor logs that might be useful for us?

```txt
22-10-14 08:50:28 INFO (MainThread) [supervisor.backups.manager] Creating new full backup with slug b124e315
22-10-14 08:50:28 INFO (MainThread) [supervisor.backups.manager] Backing up b124e315 store Add-ons
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_duckdns
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_duckdns
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_configurator
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_configurator
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_mosquitto
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_mosquitto
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_nginx_proxy
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_nginx_proxy
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_nut
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_nut
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_nodered
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_nodered
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_samba
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_samba
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_sonweb
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_sonweb
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_ssh
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_ssh
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_zerotier
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_zerotier
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_esphome
22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_esphome
22-10-14 08:50:38 INFO (SyncWorker_2) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-jackett_nas to /data/tmp/tmpgvq6ivjt/image.tar
22-10-14 08:50:40 INFO (SyncWorker_2) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-jackett_nas done
22-10-14 08:50:44 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_jackett_nas
22-10-14 08:51:45 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_jackett_nas
22-10-14 08:51:57 INFO (SyncWorker_7) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-sonarr_nas to /data/tmp/tmpu3afiy4b/image.tar
22-10-14 08:51:58 INFO (SyncWorker_7) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-sonarr_nas done
22-10-14 08:52:05 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_sonarr_nas
22-10-14 08:53:11 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_sonarr_nas
22-10-14 08:53:12 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on cebe7a76_hassio_google_drive_backup
22-10-14 08:53:12 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon cebe7a76_hassio_google_drive_backup
22-10-14 08:53:16 INFO (SyncWorker_7) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-radarr_nas to /data/tmp/tmpav__fd6_/image.tar
22-10-14 08:53:17 INFO (SyncWorker_7) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-radarr_nas done
22-10-14 08:53:21 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_radarr_nas
22-10-14 08:53:55 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_radarr_nas
22-10-14 08:53:55 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_portainer
22-10-14 08:53:55 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_portainer
22-10-14 08:54:01 INFO (SyncWorker_6) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-lidarr_nas to /data/tmp/tmp24jdigr3/image.tar
22-10-14 08:54:02 INFO (SyncWorker_6) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-lidarr_nas done
22-10-14 08:54:06 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_lidarr_nas
22-10-14 08:54:45 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_lidarr_nas
22-10-14 08:54:56 INFO (SyncWorker_1) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-bazarr_nas to /data/tmp/tmpg7dnsiuc/image.tar
22-10-14 08:54:57 INFO (SyncWorker_1) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-bazarr_nas done
22-10-14 08:55:01 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_bazarr_nas
22-10-14 08:55:06 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-10-14 08:56:09 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_bazarr_nas
22-10-14 08:56:09 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_mariadb
22-10-14 09:00:36 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_mariadb
22-10-14 09:00:43 INFO (SyncWorker_4) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-flaresolverr to /data/tmp/tmpos4nv06v/image.tar
22-10-14 09:00:45 INFO (SyncWorker_4) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-flaresolverr done
22-10-14 09:00:49 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_flaresolverr
22-10-14 09:01:43 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_flaresolverr
22-10-14 09:01:47 INFO (SyncWorker_6) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-qbittorrent to /data/tmp/tmphku1bivv/image.tar
22-10-14 09:01:48 INFO (SyncWorker_6) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-qbittorrent done
22-10-14 09:01:51 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_qbittorrent
22-10-14 09:02:32 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_qbittorrent
22-10-14 09:02:32 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_transmission_openvpn
22-10-14 09:02:32 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_transmission_openvpn
22-10-14 09:02:37 INFO (SyncWorker_1) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-prowlarr to /data/tmp/tmpsvorqzir/image.tar
22-10-14 09:02:37 INFO (SyncWorker_1) [supervisor.docker.addon] Export image db21ed7f/amd64-addon-prowlarr done
22-10-14 09:02:41 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_prowlarr
22-10-14 09:03:09 INFO (MainThread) [supervisor.backups.manager] Found 25 backup files
22-10-14 09:03:09 INFO (MainThread) [supervisor.backups.manager] Found 25 backup files
22-10-14 09:03:22 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_prowlarr
22-10-14 09:03:22 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
22-10-14 09:03:42 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
22-10-14 09:03:42 INFO (MainThread) [supervisor.backups.manager] Backing up b124e315 store folders
22-10-14 09:03:42 INFO (SyncWorker_5) [supervisor.backups.backup] Backing up folder share
22-10-14 09:03:42 INFO (SyncWorker_5) [supervisor.backups.backup] Backup folder share done
22-10-14 09:03:42 INFO (SyncWorker_0) [supervisor.backups.backup] Backing up folder addons/local
22-10-14 09:03:42 INFO (SyncWorker_0) [supervisor.backups.backup] Backup folder addons/local done
22-10-14 09:03:42 INFO (SyncWorker_6) [supervisor.backups.backup] Backing up folder ssl
22-10-14 09:03:42 INFO (SyncWorker_6) [supervisor.backups.backup] Backup folder ssl done
22-10-14 09:03:42 INFO (SyncWorker_2) [supervisor.backups.backup] Backing up folder media
22-10-14 09:03:42 INFO (SyncWorker_2) [supervisor.backups.backup] Backup folder media done
22-10-14 09:04:06 INFO (MainThread) [supervisor.backups.manager] Creating full backup with slug b124e315 completed
```

## System Information

version | core-2022.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.72
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4929
Installed Version | 1.28.0
Stage | running
Available Repositories | 1119
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 38.7 GB
disk_used | 19.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), File editor (5.4.1), Mosquitto broker (6.1.3), NGINX Home Assistant SSL proxy (3.1.5), Network UPS Tools (0.11.0), Node-RED (13.4.0), Samba share (10.0.0), TasmoAdmin (0.20.0), Terminal & SSH (9.6.1), ZeroTier One (0.15.1), ESPHome (2022.3.1), Jackett NAS (0.20.2098), Sonarr NAS (3.0.9.1549-2-bugfix), Home Assistant Google Drive Backup (0.108.4), Radarr NAS (4.2.4.6635), Portainer (2.0.0), Lidarr NAS (1.0.2.2592-ls98), Bazarr NAS (1.1.1-bugfix), MariaDB (2.5.1), FlareSolverr (2.2.9), Qbittorrent (4.4.5-r0-ls221-2), Transmission Openvpn (4.0-v24), Prowlarr NAS (nightly-0.4.7.2016-ls427)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22 September 2022 at 07:10
-- | --
current_recorder_run | 12 October 2022 at 08:50
estimated_db_size | 1393.34 MiB
database_engine | mysql
database_version | 10.6.8

</details>

**Comment by mdegat01** [comment]
It looks like you use the `NGINX Home Assistant SSL proxy` addon. When you were making this backup, were you using the external URL by any chance?

If so I'm pretty sure what happened is when supervisor started making a backup for the proxy addon the connection was cut off. Since your browser was actually talking to that addon and that was talking to supervisor. 

It looks like the backup actually did complete successfully according to your logs. Is that true? Can you see it in the list of backups?

If the backup didn't complete successfully then that's definitely a problem and we can iterate here to try and figure it out. But if the backup did complete successfully and I'm writing about you using the external URL then I don't think there's really much that can be done here. The proxy has to be backed up in the full addon and that means the connection has to be cut. And when that happens the frontend is going to show a generic error because there's no way for it to know why the connection was cut, just that it was cut unexpectedly.

If you make your backups via the internal URL or (obviously) the CLI then you shouldn't see anything like this. But if you use the external URL and the backup includes the proxy addon then you're going to have to expect this error unfortunately and check that the backup succeeded manually (via logs and/or the backup list).

**Comment by almico** [comment]
Thank you for looking into this 😃

> When you were making this backup, were you using the external URL by any chance?

Well... It depends on the definition of "using" in this context. I started the backup procedure using the internal URL (http://192.168.1.203:8123). I think it's totally possible that, during the backup, some sensor from my mobile phone generated a connection to the external URL.

> 22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_nginx_proxy
> 22-10-14 08:50:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_nginx_proxy

In the logs, as far as I understand, `core_nginx_proxy` was properly backed up. If the connection cut is to be considered an error, I think it should be clearly added to the logs.

> It looks like the backup actually did complete successfully according to your logs. Is that true? Can you see it in the list of backups?

That's what I was wondering 😃 How can I know whether the resulting backup was valid or not? According to what you say, if it appears in the list, then it would be valid (completely valid? valid, except `core_nginx_proxy`? valid, except some other addon?). But, then, there is something unclear: is the `Unknown error, see supervisor logs` a false error report? If not, where would the error be, if the resulting backup is fully valid?

> If you make your backups via the internal URL or (obviously) the CLI then you shouldn't see anything like this.

I make my backups via the internal URL.

**Comment by almico** [comment]
I don't know if it's a random success, or a fix, but, after having updated to "Home Assistant 2022.10.4", the full backup that, before the update, consistently reported the error didn't return it 😃

**Comment by almico** [comment]
I tried a full backup again, and the issue is no longer there.
If you think that something in 2022.10.4 could have fixed it, feel free to close this issue.
Should I hit it again, I will reopen with additional data.
Thank you, again, for looking into this.

**Comment by almico** [comment]
It worked today too.
Closing.

**Comment by almico** [comment]
It just rehappened again:

![image](https://user-images.githubusercontent.com/15247405/197721198-71b5876b-6830-4be2-aa63-9291d0a7d74d.png)

No error in Supervisor logs.

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

**Comment by mdegat01** [comment]
> According to what you say, if it appears in the list, then it would be valid (completely valid? valid, except core_nginx_proxy? valid, except some other addon?)

Completely valid. If not there would be errors in the supervisor logs.

This message is coming from the UI. It can basically happen in one of two ways:
1. The connection to the server was cut before it received a successful response. Timeout, network change, proxy being stopped, etc. This doesn't mean the backup failed, just that the UI wasn't able to hold a connection all the way until it finished.
2. Something went terribly wrong and supervisor returned a 5xx response. In this case the backup would not be in the list there would definitely be an error in supervisor's log.

Given what you're seeing I believe its the first one. The reason could be a number of things to be honest. The proxy was restarted, you changed from wifi to mobile network, you briefly lost network connection, etc. Doesn't mean anything went wrong at all just that the UI wasn't able to follow the process all the way through to completion.

If the backup is in the list and there's no errors in the supervisor log then this message on the screen is ignorable, everything went fine. I honestly would say just don't leave the UI up. Go do other stuff and then check back later to ensure there's a backup in the list if you're worried about it.

**Comment by almico** [comment]
> The reason could be a number of things to be honest

No restart, no network change. I will double-check "invisible" issues with the network (quite unlikely, being a direct wired connection).

> Go do other stuff and then check back later

I really love this suggestion 😃
I just wonder, then, if it makes sense to leave that window open. Shouldn't it close, suggesting to verify that everything went fine in the list of backups?
I'll leave this decision up to you. I will always close that window from now on 😄
