### ISSUE TITLE
Supervisor in devcontainer not discovering local add-ons

### ISSUE THREAD

**Issue by robinvalk** [home-assistant/supervisor#3976]
### Describe the issue you are experiencing

I cloned a fresh copy of the addons-example repository. After fixing some permissions issues in the dev container found in #3969 I managed to get home assistant running in the container with the vscode task. 

As the example repo comes with an example add-on I tried to find it in the add-on store. Unfortunately it doesn't show up as a local add-on, even though I enabled advanced mode on my profile. 

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

1. Clone a fresh copy of the example add-ons repository:
`git clone https://github.com/home-assistant/addons-example`
2. Open the directory in vscode but DO NOT open the window in the container as asked by the pop-up
3. Add `sudo -u root -g root ` to the `postStartCommand` property in `.devcontainer.json` and to the `command` property in `.vscode/tasks.json` to get the container and home assistant running:
    2.1. tasks.json
           ```
           "command": "sudo -u root -g root supervisor_run",
           ```
    2.2. .devcontainer.json
        ```
        "postStartCommand": "sudo -u root -g root bash devcontainer_bootstrap",
        ```
4. Now click on the option to open the window in the container and let it build
5. Run the Home Assistant task in vscode to start it
6. Setup home assistant
7. Turn on advanced mode in your home assistant profile
8. Go to the add-on store and check for updates
9. No local add-on shows up

### Anything in the Supervisor logs that might be useful for us?

```txt
22-10-27 11:48:10 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-10-27 11:48:10 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-10-27 11:48:10 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-10-27 11:48:12 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
22-10-27 11:48:12 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
```

## System Information

version | core-2022.12.0.dev20221027
-- | --
installation_type | Home Assistant Supervised
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.10.88-0-virt
arch | x86_64
timezone | UTC
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | null
-- | --
update_channel | dev
supervisor_version | supervisor-2022.10.dev2702
agent_version | 1.2.2
docker_version | 20.10.18
disk_total | 58.8 GB
disk_used | 29.9 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27 October 2022, 09:28
-- | --
current_recorder_run | 27 October 2022, 11:28
estimated_db_size | 0.18 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Supervisor diagnostics

[config_entry-hassio-c72303453e26912dc840481d9c82d4f2.json.txt](https://github.com/home-assistant/supervisor/files/9878176/config_entry-hassio-c72303453e26912dc840481d9c82d4f2.json.txt)

### Additional information

```shell
$ docker --version
Docker version 20.10.20, build 9fdeb9c3de
```

```shell
$ docker info
Client:
 Context:    colima
 Debug Mode: false

Server:
 Containers: 100
  Running: 3
  Paused: 0
  Stopped: 97
 Images: 98
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e5ef943eb76627a6d3b6de8cd1ef6537f393a71
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version:
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.88-0-virt
 Operating System: Alpine Linux v3.14
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.844GiB
 Name: colima
 ID: 43LX:AFMI:J2G2:HMU3:4XGB:EQL2:RZ4F:CTAT:BJZ6:DDBE:SIRI:JVFG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 ```

**Comment by mdegat01** [comment]
> Go to the add-on store and check for updates

After this step you have to refresh the window (like browser refresh). The UI doesn't seem to show new addons otherwise. I have to do that on all my systems when I do local addon dev. Did you do that?

**Comment by robinvalk** [comment]
I tried it just now, unfortunately it doesn't help. Still no local add-ons show up

**Comment by besanur** [comment]
same issue here, 5 months ago it worked. Now it doesn't work anymore

**Comment by besanur** [comment]
I finally found a solution after several attempts.. see #3967 after that the homeassistant example-addon worked

**Comment by robinvalk** [comment]
@besanur You're right, setting the user does work compared to using sudo. Thanks for unblocking me!
