### ISSUE TITLE
Unable to fix Unsupported Job Conditions

### ISSUE THREAD

**Issue by bacco007** [home-assistant/supervisor#3988]
### Describe the issue you are experiencing

I've followed the instructions from https://www.home-assistant.io/more-info/unsupported/job_conditions but once the supervisor restarts the ignore_conditions setting for jobs returns to "healthy"

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

```
➜  ~ ha jobs info
ignore_conditions:
- healthy
➜  ~ ha jobs reset
Processing... Done.

Command completed successfully.
➜  ~ ha jobs info
ignore_conditions: []
➜  ~ ha supervisor restart
Command completed successfully.
➜  ~ ha jobs info
ignore_conditions:
- healthy
```

### Anything in the Supervisor logs that might be useful for us?

```txt
22-11-05 14:40:19 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-11-05 14:40:19 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-11-05 14:40:19 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-11-05 14:40:19 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-11-05 14:40:19 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-11-05 14:40:19 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-11-05 14:40:19 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-11-05 14:40:19 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-11-05 14:40:20 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-11-05 14:40:20 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-11-05 14:40:20 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
22-11-05 14:40:20 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-11-05 14:40:21 INFO (MainThread) [supervisor.api.middleware.security] /jobs/info access from a0d7b954_ssh
22-11-05 14:40:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-11-05 14:40:22 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-11-05 14:40:22 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-11-05 14:40:23 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ba22da74/amd64-addon-gosungrow with version 2.2.1
22-11-05 14:40:24 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-05 14:40:24 CRITICAL (MainThread) [supervisor.jobs] The following job conditions are ignored and will make the system unstable when they occur: {<JobCondition.HEALTHY: 'healthy'>}
22-11-05 14:40:24 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-11-05 14:40:24 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
```

## System Information

version | core-2022.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4214
Installed Version | 1.28.3
Stage | running
Available Repositories | 1245
Downloaded Repositories | 119

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 15, 2022 at 11:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | beta
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 93.8 GB
disk_used | 44.7 GB
healthy | true
supported | failed to load: Unsupported
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.3), Samba share (10.0.0), SSH & Web Terminal (12.1.1), Home Assistant Google Drive Backup (0.108.4), JupyterLab (0.9.1), MariaDB (2.5.1), Node-RED (13.5.1), Portainer (2.0.0), Glances (0.16.0), phpMyAdmin (0.8.1), WeatherFlow to MQTT (3.1.3), Eufy Security Add-on (0.9.4), RTSP Simple Server Add-on (v0.17.6), Zigbee2MQTT (1.28.2-1), ESPHome (2022.10.2), GoSungrow (2.2.1), Home Assistant Git Exporter (1.13.0), Shortumation (v0.7.6), File editor (5.4.1), MQTT Explorer (browser-1.0.1), EMQX (0.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 56
views | 73
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 29, 2022 at 7:47 AM
-- | --
current_recorder_run | November 5, 2022 at 12:20 PM
estimated_db_size | 2858.45 MiB
database_engine | mysql
database_version | 10.6.8

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
remaining_requests | 46
rooftop_site_count | 1
polling_hours | 6 -> 20 and once at midnight

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Additional information

Forum discussion: https://community.home-assistant.io/t/fixing-unsupported-error-protections-disabled/483462

**Comment by BassMonkey** [comment]
I am having the same issue. The config reset doesn't seem to be made persistent so it is recovered on restart. I also tried to just manually give the "ignore-conditions" array an empty String or "none" but it only allows to set conditions, not to remove them:

```
ubuntu@ubuntu-rpi-4-1:/usr/share/hassio$ ha jobs options --ignore-conditions none
Error: expected JobCondition or one of 'auto_update', 'free_space', 'haos', 'healthy', 'host_network', 'internet_host', 'internet_system', 'os_agent', 'plugins_updated', 'running', 'supervisor_updated' @ data['ignore_conditions'][0]. Got 'none'
```

Does anyone know where those values are read from upon startup so we can manually edit that file as a workaround?
