### ISSUE TITLE
Supervisor 2022.11.0 fails to start 

### ISSUE THREAD

**Issue by jweston2112** [home-assistant/supervisor#3998]
### Describe the issue you are experiencing

I received a message that Supervisor 2022.11.0 was available for update (Also got a Repair message at the same time)
![image](https://user-images.githubusercontent.com/70152549/201775305-cfd3829b-99cb-4ad6-b19c-76562bc831aa.png)

I updated and Checked the log. 

I saw an error... but it started with "was ignored" 
 
had a couple issues with Addons  so I went to ha su restart and got a message that it could not be executed because Supervisor was not running ... something ,startup....

I rebooted the entiree machine and it has yet to come up

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

can reproduce the issue as it has not come back up.

### Anything in the Supervisor logs that might be useful for us?

```txt
22-11-14 16:07:26 INFO (MainThread) [__main__] Running Supervisor
TypeError: Expected unicode, got RaucState
Exception ignored in: 'dbus_fast._private.marshaller.Marshaller._write_single'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 103, in buffer_message
    msg._marshall(self.negotiate_unix_fd),
TypeError: Expected unicode, got RaucState
22-11-14 16:07:26 ERROR (MainThread) [supervisor.jobs] Unhandled exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/os/manager.py", line 232, in mark_healthy
    response = await self.sys_dbus.rauc.mark(RaucState.GOOD, "booted")
  File "/usr/src/supervisor/supervisor/dbus/rauc.py", line 98, in mark
    return await self.dbus.Installer.call_mark(state, slot_identifier)
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 100, in call_dbus
    return await getattr(proxy_interface, method)(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/proxy_object.py", line 90, in method_fn
    msg = await self.bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 370, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 24, in dbus_fast.aio.message_reader.build_message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 641, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 524, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 276, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
EOFError
22-11-14 16:07:26 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-480' coro=<Core.start() done, defined at /usr/src/supervisor/supervisor/core.py:171> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/os/manager.py", line 232, in mark_healthy
    response = await self.sys_dbus.rauc.mark(RaucState.GOOD, "booted")
  File "/usr/src/supervisor/supervisor/dbus/rauc.py", line 98, in mark
    return await self.dbus.Installer.call_mark(state, slot_identifier)
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 100, in call_dbus
    return await getattr(proxy_interface, method)(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/proxy_object.py", line 90, in method_fn
    msg = await self.bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 370, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 24, in dbus_fast.aio.message_reader.build_message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 641, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 524, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 276, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
EOFError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/core.py", line 184, in start
    await self.sys_os.mark_healthy()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 160, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException

```
```


### System Health information

![image](https://user-images.githubusercontent.com/70152549/201776274-332dd83c-d609-4329-99b8-0ae11caf78db.png)


the machine hasnt come back up to get the information

### Supervisor diagnostics



the machine is not up

### Additional information

_No response_

**Comment by jweston2112** [comment]
I guess I should also point out it is a Raspberry PI 4 8gb

**Comment by fbonelle** [comment]
Hello,

Same issue for me. 

Regards

**Comment by mdegat01** [comment]
So there is definitely a bug with the RaucState thing, you are right about that. The linked pr will fix that error in the logs.

However the dev systems I noticed it on continued starting up without any other issues and were running fine. Is there anything else in the logs? I don't understand how this could block startup and it certainly didn't for me.

**Comment by jweston2112** [comment]
Sorry I am afraid I could not get SSH'd back in nor did the web page every stop looping...the 60 second wait.... it obviously didnt stop the update... it was running after that... like I had said... I tried a ha su restart and it gave me an error... like it was still "starting" from the upgrade...  which I didnt write down... I did thatbecause I was having issues with a couple addons (VSCode mostly)

I have reinstalled and restored ... I guess I could always try it again when I get some more time.... and make better notes... this isnt the machine doing my main Home Automations... just one I use ro preview the betas and try new stuff... 

its good to test your backups once in awhile anyway... :)

**Comment by mdegat01** [comment]
Ok well there will be a new release shortly. This slipped in because it ended uncovering an unexpected breaking change in a dependency that has since been reverted in an update of that library. Once the linked pr is in and an update to that dependency youll see a new beta. Hopefully that gets everything working error free.

**Comment by jweston2112** [comment]
I have no doubt it'll all get worked out... Thanks for explaining... again...

**Comment by jweston2112** [comment]
Supervisor 2022.11.1 has resolved this for me.

*  No Type error
*  machine reboots in a timely fashion
*  added bonus cpu utilization 2-3% lower while idling

**Comment by sam43434** [comment]
> Supervisor 2022.11.1 has resolved this for me.
> 
> * No Type error
> * machine reboots in a timely fashion
> * added bonus cpu utilization 2-3% lower while idling

did you have to do anything to get it to install,  two intel Nucs  the update just keeps saying installing,  Been awhile

**Comment by jweston2112** [comment]
it did seem to take awhile ... but mine test/beat machine is a RPI 4 8gb not as fast as a NUC I did wait till it updated the latest version to match the installed version...

**Comment by sam43434** [comment]
> it did seem to take awhile ... but my test/beta machine is a RPI 4 8gb not as fast as a NUC I did wait till it updated the latest version to match the installed version...

mines been going for 1 hour and still nothing seems to of changed

**Comment by jweston2112** [comment]
I usually SSH in and start looking at Logs when it takes a long time.... I only have a few AddOns on this machine I think the more you have installed the longer it takes... but an hour seems like a very long time... I had to reinstall yesterday when trying  Supervisor 2022.11.0 so I upgraded directly from 10.2 to 11.1 ... I had an addon that needed /dev/i2c device and that hosed me for a while till i reinstalled... but I could only see that in the supervisor log.

**Comment by Mincka** [comment]
I had the same issue on my Home Assistant Blue (ODROID N2+).
The update error, the addons starting to fail, then the fatal OS reboot.

I followed these steps to flash it and restore my last backup:
https://www.home-assistant.io/installation/odroid/
https://www.home-assistant.io/common-tasks/os#flashing-an-odroid-n2

**Comment by jweston2112** [comment]
If it turns out to be an addon you could look for information on the Discord Server or create an Issue for the  Addon Creator..

I doubt its realated to *this* issue specifically 

I did a partial restore to exclude the addon that was failing to get mine back up and reinstalled per the creators instructions ... my issue was because I had to reinstall and wipe the filesystem... and wasnt related to this issue per se...

After observing my machine for a while and rebooting and restarting supervisor and core and other torture test this issue is thoroughly resolved for me -- Closing

**Comment by DogParty** [comment]
Same issue with my NUC. Rebooting the host actually broke HA and I had to connect it to a monitor to restart ha core from the console to get it to start again. Sitting at `ha core update` now :/
