### ISSUE TITLE
Can't connect to Wifi on Pi4 (Error: Connection activation failed: (7) Secrets were required, but not provided)

### ISSUE THREAD

**Issue by llluis** [home-assistant/supervisor#3999]
### Describe the issue you are experiencing

I can't for the life of me connect to wifi (while connected via ethernet). Several other devices are connected so it should not be a problem with the router.

If I try to use the UI interface, I can scan the network, select the SSID, put the password but when trying to save, I get:

```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 1:48:23 PM (1 occurrences)
Last logged: 1:48:23 PM

Failed to to call /network/interface/wlan0/update - Activating connection failed, check connection settings.
```

If I try to use the `ha network` command, I get the same error of when using the UI.

If I try to use the method on [this page](https://community.home-assistant.io/t/guide-connecting-pi-with-home-assistant-os-to-wifi-or-other-networking-changes/98768), I get:

```
Error: Connection activation failed: (7) Secrets were required, but not provided.
```

I'm sure the password is correct. Several nmcli commands all return OK, but it can't connect.
The directory `/etc/NetworkManager/system-connections` is always empty and gets overwritten at boot (all contents erased).

**The really odd part: if I use the CONFIG/network file on a USB stick during boot [described here](https://github.com/home-assistant/operating-system/blob/dev/Documentation/network.md), the connection works!!!** But it doesn't survive a reboot without the USB.

This all leds me to think it's something at the Supervisor level which handles all that.
`nmcli` shows me the 2 default connections setup at boot `Supervisor eth0` and `Supervisor wlan0` but I can't start the second.

My goal is to have ethernet and wlan0 connected at the same time. Ethernet for management and wlan0 to access devices.

It seems all documentation available are not updated to the latest version of HA OS and Supervisor.
Is there any lead I can follow on how all this works?

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

9.3

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Try to connect to wifi using the UI

or try to connect any other methods described above.

### Anything in the Supervisor logs that might be useful for us?

```txt
Nope
```

### Anything in the Host logs that might be useful for us?

```txt
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9630] device (wlan0): Activation: starting connection 'ssidwashere' (752bf93f-b125-4bf5-add3-964f0f67e906)
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9651] audit: op="connection-add-activate" uuid="752bf93f-b125-4bf5-add3-964f0f67e906" name="ssidwashere" pid=12562 uid=0 result="success"
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9671] device (wlan0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9690] device (wlan0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9705] device (wlan0): Activation: (wifi) access point 'ssidwashere' has security, but secrets are required.
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9717] device (wlan0): state change: config -> need-auth (reason 'none', sys-iface-state: 'managed')
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9789] device (wlan0): state change: need-auth -> prepare (reason 'none', sys-iface-state: 'managed')
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9797] device (wlan0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9810] device (wlan0): Activation: (wifi) connection 'ssidwashere' has security, and secrets exist.  No new secrets needed.
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9823] Config: added 'ssid' value 'ssidwashere'
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9827] Config: added 'scan_ssid' value '1'
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9828] Config: added 'bgscan' value 'simple:30:-70:86400'
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9831] Config: added 'key_mgmt' value 'WPA-PSK'
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9832] Config: added 'auth_alg' value 'OPEN'
Nov 14 19:05:54 homeassistant NetworkManager[371]: <info>  [1668452754.9832] Config: added 'psk' value '<hidden>'
Nov 14 19:05:55 homeassistant NetworkManager[371]: <info>  [1668452755.0255] device (wlan0): supplicant interface state: inactive -> scanning
Nov 14 19:05:57 homeassistant wpa_supplicant[393]: wlan0: Trying to associate with SSID 'ssidwashere'
Nov 14 19:05:57 homeassistant NetworkManager[371]: <info>  [1668452757.8579] device (wlan0): supplicant interface state: scanning -> associating
Nov 14 19:06:00 homeassistant wpa_supplicant[393]: wlan0: CTRL-EVENT-ASSOC-REJECT bssid=00:00:00:00:00:00 status_code=16
Nov 14 19:06:00 homeassistant wpa_supplicant[393]: wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="ssidwashere" auth_failures=1 duration=10 reason=CONN_FAILED
Nov 14 19:06:00 homeassistant NetworkManager[371]: <info>  [1668452760.6640] device (wlan0): supplicant interface state: associating -> disconnected
Nov 14 19:06:10 homeassistant NetworkManager[371]: <info>  [1668452770.6908] device (wlan0): supplicant interface state: disconnected -> scanning
Nov 14 19:06:13 homeassistant wpa_supplicant[393]: wlan0: CTRL-EVENT-SSID-REENABLED id=0 ssid="ssidwashere"
```

## System Information

version | core-2022.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | America/Toronto
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4932
Installed Version | 1.28.3
Stage | running
Available Repositories | 1140
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 109.3 GB
disk_used | 10.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | <redacted>

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 1
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 6, 2022 at 11:31 PM
-- | --
current_recorder_run | November 14, 2022 at 1:17 PM
estimated_db_size | 671.51 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Additional information

Odd enough, `nmcli radio` is different from the expected output from online tutorials (2 missing):

```
WIFI-HW  WIFI     WWAN-HW  WWAN
missing  enabled  missing  enabled
```

But as I said, I can scan networks and it works if configured at boot.

**Comment by Dylan700Manes** [comment]
Hello, same problem obviously with debian bullseyes
It's always a pleasure to use something and to have to find a hack to explain to the machine how to use this something.

In short, it's possible to scan the wifis, (I've been using netplan.io for 1 week) and then suddenly nothing. 
#Delete parameters
- nmcli con delete "netplan-wlan0-myssid"
#So the trick when it meets a password is:
- nmcli d wifi connect "myssid" password "pass";
-- Error: Connection activation failed: (7) Secrets were required, but not provided.
#And the novel when there is an open network is:
- nmcli d wifi connect "myopenssid";
-- Error: Connection activation failed: (11) 802.1X supplicant took too long to authenticate.

**Comment by Dylan700Manes** [comment]
Is there a hack to make the networking work?
The mode - raspi-config; #configuring the wifi traditionally and customarily does not work either. Despite having disabled:: - syatemctl stop NetworkManager; and verified that - apt install ifupdown;
This mode also does not work anymore and seems to have to be hacked
 be hacked ::
- nano /etc/network/interfaces.d/wlan0
- allow-hotplug wlan0
- iface wlan0 inet dhcp
- wpa-ssid myssid
- wpa-psk mypass
- service networking restart;
Or - nano /etc/wpa_supplicant/wpa_supplicant.conf;
- ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
- update_config=1
- country=FR
- 
- network={
- scan_ssid=1
- ssid="myssid"
- psk="mypass"
- }
- nano /etc/network/interfaces;
- allow hotplug wlan0
- iface wlan0 inet dhcp
- wpa_cli -i wlan0 reconfigure;

**Comment by Dylan700Manes** [comment]
•rfkill list
`0: phy0: Wireless LAN`
`        Soft blocked: no`
`        Hard blocked: no`
`1: hci0: Bluetooth`
`        Soft blocked: no`
`        Hard blocked: no`

**Comment by Dylan700Manes** [comment]
• systemctl list-unit-files --state=enabled
UNIT FILE                            STATE   VENDOR PRESET
apache2.service                      enabled enabled
avahi-daemon.service                 enabled enabled
bluetooth.service                    enabled enabled
console-setup.service                enabled enabled
cron.service                         enabled enabled
dhcpcd.service                       enabled enabled
dphys-swapfile.service               enabled enabled
e2scrub_reap.service                 enabled enabled
fake-hwclock.service                 enabled enabled
getty@.service                       enabled enabled
hciuart.service                      enabled enabled
keyboard-setup.service               enabled enabled
lightdm.service                      enabled enabled
ModemManager.service                 enabled enabled
NetworkManager-dispatcher.service    enabled enabled
NetworkManager-wait-online.service   enabled enabled
NetworkManager.service               enabled enabled
raspberrypi-net-mods.service         enabled enabled
rpi-display-backlight.service        enabled enabled
rpi-eeprom-update.service            enabled enabled
rsync.service                        enabled enabled
rsyslog.service                      enabled enabled
ssh.service                          enabled enabled
sshswitch.service                    enabled enabled
systemd-networkd-wait-online.service enabled disabled
systemd-networkd.service             enabled enabled
systemd-pstore.service               enabled enabled
systemd-timesyncd.service            enabled enabled
tor.service                          enabled enabled
triggerhappy.service                 enabled enabled
udisks2.service                      enabled enabled
wpa_supplicant.service               enabled enabled
avahi-daemon.socket                  enabled enabled
systemd-networkd.socket              enabled enabled
triggerhappy.socket                  enabled enabled
nfs-client.target                    enabled enabled
remote-fs.target                     enabled enabled
apt-daily-upgrade.timer              enabled enabled
apt-daily.timer                      enabled enabled
e2scrub_all.timer                    enabled enabled
fstrim.timer                         enabled enabled
logrotate.timer                      enabled enabled
man-db.timer                         enabled enabled

**Comment by Dylan700Manes** [comment]
Yellow humor / new novel
• nmcli dev wifi;
`IN-USE  BSSID SSID  MODE  CHAN RATE  SIGNAL  BARS`
`        D0:9C:7A:AC:30:44  alware  Infra  6     65 Mbit/s   100     ▂▄▆█  --`
`        2C:C5:D3:2D:F1:E8  Wifst  Infra  6     130 Mbit/s  84      ▂▄▆█  --`
`        2C:C5:D3:2D:F1:EC  Wifst  Infra  100   270 Mbit/s  69      ▂▄▆_  --`
•nmcli d wifi connect D0:9C:7A:AC:30:44;
Walt ... 
Walt ... 
••Error: Connection activation failed: (53) The Wi-Fi network could not be found.


---------------------------------------------------------------
• journalctl -u NetworkManager|tail -n60;

Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.3241] device (usb0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')                                                                     Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.3342] device (wlan0): driver supports Access Point (AP) mode                                  Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.3361] manager: (wlan0): new 802.11 Wi-Fi device (/org/freedesktop/NetworkManager/Devices/4)
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.3388] device (wlan0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')                                                                    Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8653] device (wlan0): set-hw-addr: set MAC address to 62:A4:E7:A5:30:E0 (scanning)
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <warn>  [1669173121.8731] Error: failed to open /run/network/ifstate                                              Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8801] modem-manager: ModemManager available                                                   Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8815] device (usb0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')                                                                      Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8838] policy: auto-activating connection 'netplan-usb0' (ea8e372f-c04d-3e0a-bd69-2a2e82cd1c26)Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8850] device (usb0): Activation: starting connection 'netplan-usb0' (ea8e372f-c04d-3e0a-bd69-2a2e82cd1c26)                                                                      Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8853] device (usb0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8860] manager: NetworkManager state is now CONNECTING
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8864] device (usb0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')                                                                                Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8877] device (usb0): state change: config -> ip-config (reason 'none', sys-iface-state: 'managed')                                                                              Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8895] dhcp4 (usb0): activation: beginning transaction (timeout in 45 seconds)                 Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.8995] dhcp4 (usb0): state changed unknown -> bound, address=192.168.42.252                    Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9033] device (usb0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'managed')
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9071] device (usb0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'managed')                                                                          Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9078] device (usb0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'managed')
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9089] manager: NetworkManager state is now CONNECTED_LOCAL
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9109] manager: NetworkManager state is now CONNECTED_SITE
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9112] policy: set 'netplan-usb0' (usb0) as default for IPv4 routing and DNS
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9121] dns-mgr: Writing DNS information to /sbin/resolvconf
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9826] device (usb0): Activation: successful, device activated.
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9842] manager: NetworkManager state is now CONNECTED_GLOBAL
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9937] device (wlan0): supplicant interface state: internal-starting -> disconnected
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9939] Wi-Fi P2P device controlled by interface wlan0 created
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9945] manager: (p2p-dev-wlan0): new 802.11 Wi-Fi P2P device (/org/freedesktop/NetworkManager/Devices/5)
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9952] device (p2p-dev-wlan0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <warn>  [1669173121.9968] sup-iface[273ca3fea52e7057,7,wlan0]: call-p2p-cancel: failed with P2P cancel failed
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9969] device (wlan0): state change: unavailable -> disconnected (reason 'supplicant-available', sys-iface-state: 'managed')
Nov 23 03:12:01 raspberrypi NetworkManager[1968]: <info>  [1669173121.9988] device (p2p-dev-wlan0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
Nov 23 03:12:08 raspberrypi NetworkManager[1968]: <info>  [1669173128.7472] manager: startup complete
Nov 23 03:12:45 raspberrypi NetworkManager[1968]: <info>  [1669173165.4993] audit: op="connection-delete" uuid="f9691b47-a229-3a16-9165-c3e33b0557c1" name="netplan-wlan0-Malware" pid=2101 uid=0 result="success"
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.0466] device (wlan0): Activation: starting connection 'Malware ' (638fe3e3-4cc7-4367-8b0b-0b0c41e8bfe5)
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.0479] audit: op="connection-add-activate" uuid="638fe3e3-4cc7-4367-8b0b-0b0c41e8bfe5" name="Malware " pid=2145 uid=0 result="success"
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.0497] device (wlan0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.5718] device (wlan0): set-hw-addr: reset MAC address to DC:A6:32:A8:F0:0B (preserve)
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.5813] device (wlan0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.5845] device (wlan0): Activation: (wifi) connection 'Malware ' requires no security.  No secrets needed.
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.5862] Config: added 'ssid' value 'Malware '
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.5864] Config: added 'scan_ssid' value '1'
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.5865] Config: added 'bgscan' value 'simple:30:-70:86400'
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.5866] Config: added 'key_mgmt' value 'NONE'
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.5945] device (wlan0): supplicant interface state: disconnected -> inactive
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.5946] device (p2p-dev-wlan0): supplicant management interface state: disconnected -> inactive
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.6235] device (wlan0): supplicant interface state: inactive -> scanning
Nov 23 03:15:02 raspberrypi NetworkManager[1968]: <info>  [1669173302.6246] device (p2p-dev-wlan0): supplicant management interface state: inactive -> scanning
Nov 23 03:15:28 raspberrypi NetworkManager[1968]: <warn>  [1669173328.1929] device (wlan0): Activation: (wifi) association took too long, failing activation
Nov 23 03:15:28 raspberrypi NetworkManager[1968]: <info>  [1669173328.1931] device (wlan0): state change: config -> failed (reason 'ssid-not-found', sys-iface-state: 'managed')
Nov 23 03:15:28 raspberrypi NetworkManager[1968]: <info>  [1669173328.7159] device (wlan0): set-hw-addr: set MAC address to 12:AC:40:12:38:46 (scanning)
Nov 23 03:15:28 raspberrypi NetworkManager[1968]: <warn>  [1669173328.7254] device (wlan0): Activation: failed for connection 'Malware '
Nov 23 03:15:28 raspberrypi NetworkManager[1968]: <info>  [1669173328.7261] device (wlan0): supplicant interface state: scanning -> disconnected
Nov 23 03:15:28 raspberrypi NetworkManager[1968]: <info>  [1669173328.7262] device (p2p-dev-wlan0): supplicant management interface state: scanning -> disconnected
Nov 23 03:15:28 raspberrypi NetworkManager[1968]: <info>  [1669173328.7310] device (wlan0): state change: failed -> disconnected (reason 'none', sys-iface-state: 'managed')
Nov 23 03:22:21 raspberrypi NetworkManager[1968]: <info>  [1669173741.7421] device (wlan0): set-hw-addr: set MAC address to 16:B9:70:9C:84:A8 (scanning)
Nov 23 03:22:21 raspberrypi NetworkManager[1968]: <info>  [1669173741.7567] device (wlan0): supplicant interface state: disconnected -> interface_disabled
Nov 23 03:22:21 raspberrypi NetworkManager[1968]: <info>  [1669173741.7569] device (p2p-dev-wlan0): supplicant management interface state: disconnected -> interface_disabled
Nov 23 03:22:21 raspberrypi NetworkManager[1968]: <info>  [1669173741.7574] device (wlan0): supplicant interface state: interface_disabled -> disconnected
Nov 23 03:22:21 raspberrypi NetworkManager[1968]: <info>  [1669173741.7575] device (p2p-dev-wlan0): supplicant management interface state: interface_disabled -> disconnected

**Comment by Dylan700Manes** [comment]
my config :: /etc/netplan/50-y_network.yaml; :: dependancy netplan.io;
`network:`
`  version: 2`
`  renderer: NetworkManager`
`  ethernets:`
`   usb0:`
`     dhcp4: true`
`     optional: true`
`     addresses: [192.168.42.15/24]`
`   wifis:`
`     addresses: [192.168.43.15/24,10.42.0.206/24]`
`     dhcp4: true`
`     optional: true`
`     access-points:`
`     "alware": {}`
----------------
/etc/NetworkManager/NetworkManager.conf
`[main]`
`plugins=ifupdown,keyfile`
`[ifupdown]`
`managed=false`

**Comment by Dylan700Manes** [comment]
Same problem on ubuntu 22.04 (updated)
It bothers me because the phone uses the 5GHz and 2.4GHz bands 
Randomly though it is tricked out, it is impossible for me to set these settings reliably. 
With this I could have used a basic external 2.4GHz wifi antenna
Since this thing is not able to use its own components...

I could go via bluetooth but for the project I want to lamcet the flow is much too restricted when going via USB .... Bah ... My goal is to have my hands free while this project is running.

Could someone please make the wifi work on raspberry pi 4b? Etc ...
I'm in Ubuntu 21.10 and I never knew it, I switched to pi os because
Some packages were there but since the connectivity was poorly managed I switched back to ubuntu 22.04 but after 1 day I was back at it 
It's not that I'm not interested in "explaining to the raspberry how to use its own wifi card" but ... I have something else to do?

Does anyone have a hack? Or a way for the system to reinstall automatically without losing its lightdm apache, ssh, tor etc.... configuration? Thanks
