### ISSUE TITLE
Move Datadisk didn't work correctly

### ISSUE THREAD

**Issue by cybernard** [home-assistant/supervisor#4006]
### The problem

 Home Assistant 2022.11.2 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221108.0 - latest 

First it should be noted that uncompressed by database is 25gb

I went to move my data disk to an NVME over USB option.  Samsung 980 evo
I started it and waited about 30 minutes until the LED on the external storage stopped blinking and seemed to be done.
Its a raspberry Pi 4 (no monitor attached) and there was no status bar so I have no idea what was happening.
Some kind of progress bar I could monitor, I would really be handy.

--------------

Any way I rebooted it and it started up the recorder had failed to start which caused everything else to fail.  I took many minutes to boot installed of near instant with my ssd so I knew here be the dragon.

----------

I though to my self I will restore yesterdays backup, (yay I had backups), and everything would be fine.
I discovered mariadb was in a bind and just wouldn't cooperate, so I re-installed.
It started recording history again, but the past data was gone.

First in firefox it would not accept my backup file, so I had to switch to chrome.
Chrome accepted my backup as valid and uploaded itself.

Waited, and I believe it rebooted.
Nope it was like the data was not imported.

So I manually extracted the database on another pc, and manually changed that version of mariadb to point its data directory at the backup.

So having a 25gb database might  caused issues.

connected and verified the data was fine.
did a mysqldump -u root -p homeassistant -c >homeassistant.sql
waited and waited and waited
mysql u root -p -h homeassistant.local 

After many hours it finally imported all the data.

### What version of Home Assistant Core has the issue?

 Home Assistant 2022.11.2 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221108.0 - latest 

### What was the last working version of Home Assistant Core?

don't know since it has been ages since I did a migrate

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

move datadisk

### Diagnostics information

The move datadisk doesnt really have diagnostic functions

### Anything in the logs that might be useful for us?

```txt
not really
```

**Comment by agners** [comment]
Wow, that is a whole slew of issues :sweat_smile:  Ideally you'd report them separately so they are actionable problems.

> I went to move my data disk to an NVME over USB option. Samsung 980 evo
I started it and waited about 30 minutes until the LED on the external storage stopped blinking and seemed to be done.
Its a raspberry Pi 4 (no monitor attached) and there was no status bar so I have no idea what was happening.
Some kind of progress bar I could monitor, I would really be handy.

After a successful data move, the RPi 4 will completely boot up (as in, the system should be reachable).

> Any way I rebooted it and it started up the recorder had failed to start which caused everything else to fail. I took many minutes to boot installed of near instant with my ssd so I knew here be the dragon.

How did you trigger this reboot? So things seem to be working (as in, HA started up and read from SSD?). To me that seems the move did complete successfully from a HAOS perspective.

The data disk move copies the data on a low level. So if the database was in a coherent state before, it should be so afterwards. My best guesses currently are that either the database was in a incoherent state before the move or that the reboot caused the recorder database to corrupt :cry: 


> First in firefox it would not accept my backup file, so I had to switch to chrome.
Chrome accepted my backup as valid and uploaded itself.

Probably related to this: https://github.com/home-assistant/frontend/issues/7258

> Waited, and I believe it rebooted.
Nope it was like the data was not imported.

That sounds like Supervisor triggered an out-of-memory situation. You are probably pushing the limits of what a RPi 4 can do :cold_sweat:

**Comment by cybernard** [comment]
#After a successful data move, the RPi 4 will completely boot up (as in, the HA frontend should become reachable).
======
I waited a long time, probably 20-30 mins after no visible signs of activity before using the power cord to reboot it.  My USB to SSD has a activity LED.  The migration process needs a visible percentage bar.

#You are probably pushing the limits of what a RPi 4 can do

Previously on the SSD I had no issues before the last couple weeks.  I have a RPi 4 with 8gb, and every time I check the system graphs, the CPU is rarely over 10%, and I have never seen the RAM even reach 1gb.

 I deleted the homeassistant database completely.
 So I extracted the database out of the backup manually.
connected to mysql on another PC.
 Did a mysqldump -u username -p homeassitant >home.sql
The dump succeeded.
I then I imported the home.sql file back into home assistant.

So the after that it still was having issues.

I have temporarily deleted the old sql database so I can record new data.  It seems to be recording the new data just fine.

**Comment by agners** [comment]
> I waited a long time, probably 20-30 mins after no visible signs of activity before using the power cord to reboot it. My USB to SSD has a activity LED. The migration process needs a visible percentage bar.

I assume you waited until the activity LED stopped? I'd say the progress bar would not have helped here.

The question is, why did the system did not become reachable after that... To figure that out, I'd have to be able reproduce it on my end.

> Previously on the SSD I had no issues before the last couple weeks. I have a RPi 4 with 8gb, and every time I check the system graphs, the CPU is rarely over 10%, and I have never seen the RAM even reach 1gb.

Hm, yeah that is surprising that you can exhaust 8GB of memory with just the upload. Is that reproducible with the same backup file?

**Comment by cybernard** [comment]
I could share the DB with you.  Google drive sharing or something, but it is 25gb.
It could be related to the fact I have a daily backup scheduled.  Although, I don't know when it runs.
