### ISSUE TITLE
Can't update to 2022.11.3 from .2

### ISSUE THREAD

**Issue by Swallowtail23** [home-assistant/supervisor#4012]
### Describe the issue you are experiencing

Update from Home Assistant Core 2022.11.2 to 2022.11.3 doesn't complete - it completes its backup, then sits with "Installing" and doesn't complete.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Attempt to upgrade to Core 2022.11.3
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
22-11-19 23:33:50 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug a36e4b92 completed
22-11-19 23:33:50 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2022.11.3
22-11-19 23:33:50 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/qemux86-64-homeassistant:2022.11.2 to ghcr.io/home-assistant/qemux86-64-homeassistant:2022.11.3
22-11-19 23:33:50 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/qemux86-64-homeassistant with tag 2022.11.3.
22-11-19 23:33:55 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-11-19 23:33:55 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-11-19 23:33:55 INFO (MainThread) [supervisor.api.middleware.security] /backups/a36e4b92/info access from cebe7a76_hassio_google_drive_backup
22-11-19 23:33:58 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-11-19 23:33:58 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-11-19 23:34:21 INFO (MainThread) [supervisor.backups.manager] Found 29 backup files
22-11-19 23:34:21 INFO (MainThread) [supervisor.backups.manager] Found 29 backup files
22-11-19 23:37:43 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
22-11-19 23:37:43 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
22-11-19 23:37:43 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh
22-11-19 23:37:43 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh
22-11-19 23:54:14 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

## System Information

version | core-2022.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | Australia/Brisbane
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4801
Installed Version | 1.28.3
Stage | running
Available Repositories | 1143
Downloaded Repositories | 31

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 40

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 15, 2022 at 10:00 AM
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 30.8 GB
disk_used | 15.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.4.2), Home Assistant Google Drive Backup (0.109.2), Z-Wave JS UI (1.3.0), Z-Wave JS (0.1.74), SSH & Web Terminal (12.1.3), Samba share (10.0.0), SQLite Web (3.6.1)

</details>

<details><summary>keymaster</summary>

zwave_integration | zwave_js
-- | --
network_status | on

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 22
views | 26
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 10, 2022 at 9:09 AM
-- | --
current_recorder_run | November 19, 2022 at 11:24 PM
estimated_db_size | 1603.09 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
remaining_requests | 44
rooftop_site_count | 2
polling_hours | 6 -> 19 and once at midnight

</details>

### Supervisor diagnostics

[config_entry-hassio-1ce68adfa65cbc471f5b43726bae1ee8.json.txt](https://github.com/home-assistant/supervisor/files/10047139/config_entry-hassio-1ce68adfa65cbc471f5b43726bae1ee8.json.txt)

### Additional information

![image](https://user-images.githubusercontent.com/8214128/202854277-b26ffdaa-7fe1-402c-87e9-88fb94511d29.png)

**Comment by mdegat01** [comment]
It says you have 15gb of used space. How much of that is the db file? The file at  `/config/home_assistant_v2.db`. The partial backup is going to make a copy of your entire config folder and then compress it. That could take a bit if you've got a 10-15gb of data in there. How long did you wait and did you do something to stop the process or did it eventually complete? Or is it still pending?

**Comment by Swallowtail23** [comment]
The db is 1.6Gb. 
The backup completed, 420Mb.
I update every time regularly, it typically does a point version upgrade in less than 5 minutes, it's fast hardware. 
I left for over an hour and a half without it completing. I rebooted, restored and tried again, same duration without completing.

**Comment by timbarnes** [comment]
I am experiencing the same problem. I was able to run a backup (which only took about a minute, or maybe less), but the upgrade will not complete, and I cannot restart home assistant (at least not without a reboot). I'm running inside a VirtualBox VM on Linux Mint on an Intel Mac mini. It's been in this state for more than a day.

**Comment by Swallowtail23** [comment]
I followed the same procedure and it eventually completed - although took an hour. Seems really strange when updates normally complete in a few minutes, but my HA is now on .3, so I will close this.
