### ISSUE TITLE
Bugfix #3747 not working

### ISSUE THREAD

**Issue by guenter-ms** [home-assistant/supervisor#4029]
### Describe the issue you are experiencing

I have installed supervisor 2022.11.2. Bugfix #3747 was included in supervisor 2022.7.1 

https://newreleases.io/project/github/home-assistant/supervisor/release/2022.07.1
https://github.com/home-assistant/supervisor/pull/3747

But I still get this message when using Grafana for influxes inquiry:

"Got more than 8190 bytes (8510) when reading Status line is too long"

![Bildschirmfoto 2022-11-28 um 09 39 25](https://user-images.githubusercontent.com/6253315/204231857-0eb8cc93-30ca-4963-8664-40ae2c34fbd6.jpg)

Is it necessary to configure a higher size of the Buffer?

Thank you! 
 
![Bildschirmfoto 2022-11-28 um 09 33 11](https://user-images.githubusercontent.com/6253315/204230712-eca6da9f-129d-4829-bf33-daed0458a8ad.jpg)

Installed on a raspi pi4

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Reproducing needs some effort. I can do everything for you, please advice.

1. Create a new grafana dashboard with any grafana panel 
2. configure any query against a database e.g. influxdb into the panel
3. configure several panel/settings/variables with long selection list using tags, see below
4.observe the red triangle and click it to see the error message 
...
![Bildschirmfoto 2022-11-28 um 10 45 28](https://user-images.githubusercontent.com/6253315/204245960-9f85f8df-f86e-43a4-8710-b0508fbb2a1b.jpg)
![Bildschirmfoto 2022-11-28 um 10 48 17](https://user-images.githubusercontent.com/6253315/204246709-1e9dcec2-fb55-4955-8176-18d7f14
![Bildschirmfoto 2022-11-28 um 10 49 23](https://user-images.githubusercontent.com/6253315/204246847-47341b30-f21e-4c36-ac66-566f0d1307c7.jpg)
06acf.jpg)

### Anything in the Supervisor logs that might be useful for us?

```txt
No, error message seems to be very clear
```

## System Information

version | core-2022.11.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4966
Installed Version | 1.28.4
Stage | running
Available Repositories | 1155
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 219.4 GB
disk_used | 29.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (13.4.0), File editor (5.4.1), Terminal & SSH (9.6.1), Samba share (10.0.0), InfluxDB (4.5.0), Grafana (8.1.0), Samba Backup (5.2.0), Studio Code Server (5.4.1), Log Viewer (0.14.0), Glances (0.17.1), eBUSd (22.3.1), Check Home Assistant configuration (3.11.0), RaspberryMatic CCU (3.65.11.20221005)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 3
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25. November 2022 um 09:58
-- | --
current_recorder_run | 27. November 2022 um 19:54
estimated_db_size | 229.41 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Supervisor diagnostics

[config_entry-hassio-303d17c610c50b683b6237ebfeee516e.json.txt](https://github.com/home-assistant/supervisor/files/10102548/config_entry-hassio-303d17c610c50b683b6237ebfeee516e.json.txt)

### Additional information

Thank you!

**Comment by jens-maus** [comment]
FYI: We at the RaspberryMatic project have identified the same (that the fix with #3747) seems to be not working (anymore) and the `Got more than 8190 bytes` error message still appears. See here for links to our project which brings an add-on for HomeAssistant and also needs to be able to submit URLs to ingress which are > 8190 bytes in size:

https://github.com/home-assistant/supervisor/issues/3137
https://github.com/jens-maus/RaspberryMatic/issues/1189

@mdegat01 @pvizeli Can you please have a look at that and see if you have missed something in your #3747 PR or if this might be a regression due to newer changes since the 2022.7.1 ?

**Comment by mdegat01** [comment]
@guenter-ms @jens-maus sorry was on leave for a bit. I didn't realize that an ingress request is actually proxied twice. First core receives it, then it hands it to supervisor, then supervisor hands it to the addon. So I only made half of the change it seems, I have to make the same change in core. Will make that change right away.
