### ISSUE TITLE
Addons missing

### ISSUE THREAD

**Issue by SimoneBos** [home-assistant/supervisor#4058]
### Describe the issue you are experiencing

Hi, I'm quite new user of home assistant, one year ago I installed home assistant os on my raspberry pi 4, but after few days the addons are gone. During this time I managed to go ahead with the addons I had installed even if I couldn't update them, today I tried reinstalling everything but the addons didn't reappear.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.install as instructed
2.the addons are not visible

### Anything in the Supervisor logs that might be useful for us?

```txt
22-12-20 21:50:44 INFO (SyncWorker_1) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-64-homeassistant
22-12-20 21:51:05 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
22-12-20 21:51:11 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-12-20 21:51:11 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-12-20 21:51:12 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons
22-12-20 21:51:12 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove
22-12-20 21:51:12 INFO (MainThread) [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove
22-12-20 21:51:12 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-12-20 21:51:48 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
```

## System Information

version | core-2022.12.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.4
Stage | running
Available Repositories | 1196
Downloaded Repositories | 37

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 2 gennaio 2023 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-4.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 109.3 GB
disk_used | 4.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.2.1), SSH & Web Terminal (12.0.1), File editor (5.3.3), Spotify Connect (0.12.1), Node-RED (12.0.2), Home Assistant Google Drive Backup (0.109.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 30
views | 26
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13 dicembre 2022 08:00
-- | --
current_recorder_run | 20 dicembre 2022 21:51
estimated_db_size | 102.80 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Supervisor diagnostics

[config_entry-hassio-be156aa404dfe70e5e474752d4acdbeb.json.txt](https://github.com/home-assistant/supervisor/files/10272632/config_entry-hassio-be156aa404dfe70e5e474752d4acdbeb.json.txt)

**Comment by SimoneBos** [comment]
![image](https://user-images.githubusercontent.com/78726354/208766070-56bda590-bcc6-4cf1-a800-ea4edeea0fb1.png)
![image](https://user-images.githubusercontent.com/78726354/208766290-55d7164c-99a9-44a9-8016-51c03dbc02de.png)
![image](https://user-images.githubusercontent.com/78726354/208766444-dd825e92-74ce-44c1-ab8d-371e9fca5dc6.png)


I leave some photos to help you understand what I see

**Comment by nagosuka** [comment]
I am having the same issue. Tried OS 64 install on both a RPI3b and RPI4.
