### ISSUE TITLE
Translation error Dutch

### ISSUE THREAD

**Issue by studioIngrid** [home-assistant/supervisor#4072]
### Describe the issue you are experiencing

When editing an entity, you can assign it to an area. You will get a dropdown with all configured area's, and an Add option.
In Dutch that options reads: "Voeg nieuwe ruimtetoe...", "ruimte" en "toe", should be 2 seperate words.

![image](https://user-images.githubusercontent.com/95082304/209855730-a18748db-decd-4bf7-aebe-1489dd65a80c.png)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Described above.

### Anything in the Supervisor logs that might be useful for us?

```txt
No.
```

### System Health information

Healty as a hass horse.

**Comment by frenck** [comment]
Hi there @studioIngrid 👋 

This is the issue tracker for the Home Assistant Supervisor, your issue report is not related to this project or issue tracker.

Nevertheless, you can adjust/help out with these translations of you want too, there is no programming involved in this. For more information see:

<https://developers.home-assistant.io/docs/translations>

Thanks! 👍 

../Frenck
