### ISSUE TITLE
No debug info and start inject node at NodeRed  after supervisor update to 2022.12.1

### ISSUE THREAD

**Issue by canedje** [home-assistant/supervisor#4075]
### Describe the issue you are experiencing

I think that after update to supervisor 22022.12.1 the nodered addon is missfunctioning.
Injection node is greyed out and no debug information comming up.
It is not possible to start the inject nodes.
No error log nothing changed myself
![image](https://user-images.githubusercontent.com/23150947/210071486-0e31a009-4be7-418f-abb5-c5f627f92343.png)

I tried to restore an old nodered addon version. No result.
The only thing I changed is upgrading the new supervisor version to 2022.12.1
The same issue is placed at the nodered github issue chapter:
https://github.com/hassio-addons/addon-node-red/issues/1530

Workaround is starting NodeRed by entering local: https://Home AssistantIP:1880
Then it is running oke.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

1. start nodered addon webui
2. all injection nodes are greyed out, no debug information (also greyed out)
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No errors in supervisor logs
```

## System Information

version | core-2022.12.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.80
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.29.0
Stage | running
Available Repositories | 1203
Downloaded Repositories | 34

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 48.5 GB
disk_used | 11.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.4.2), NGINX Home Assistant SSL proxy (3.2.0), Samba share (10.0.0), Terminal & SSH (9.6.1), Z-Wave JS (0.1.74), Samba Backup (5.2.0), Duck DNS (1.15.0), ESPHome (2022.12.3), Node-RED (14.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 22
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30 december 2022 om 13:42
-- | --
current_recorder_run | 3 januari 2023 om 07:24
estimated_db_size | 2956.77 MiB
database_engine | mysql
database_version | 10.6.10

</details>

### Additional information

I don't know it is the same issue, but Nodered is restarting all the time. Thats new also
I tried to rollback in CLI but is not working:
![image](https://user-images.githubusercontent.com/23150947/210075002-30490486-af59-4480-ba26-827dad55e607.png)

**Comment by canedje** [comment]
I just updated NodeRed to 14.0.1 still the same problems

**Comment by canedje** [comment]
I stopped using the addon because off this and switched to NodeRed as Docker.
There are no problems anymore, but indeed very slow reaction on flows. Sometimes more then 10 seconds.
It looks like the connection between docker and NodRed is very slow

**Comment by roybosch** [comment]
This is still a bug that needs to be fixed. Related to https://github.com/hassio-addons/addon-node-red/issues/1498#issuecomment-1424466026

We're still waiting for some kind of acknoledgement from the devs. It's been very silent around this issue.
