### ISSUE TITLE
home assistant unhealthy system - setup failed 

### ISSUE THREAD

**Issue by sonetonix-iot** [home-assistant/supervisor#4086]
### Describe the issue you are experiencing

I got below mentioned errors.

1.Failed to service update/install. Error updating home assistant operating system " OSmanager.update" blocked from execution, no supervisor internet connection.  

2. home assistant unhealthy system - setup failed 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. I tried to restart HA Supervisor 
2. Multiple time reboot the system 
3. Real time system not synchronized with  home assistant. Because whenever i recall scene ,it shows wrong date & time as triggered 

...

### Anything in the Supervisor logs that might be useful for us?

```txt
home assistant unhealthy system - setup failed
```

### System Health information

home assistant unhealthy system - setup failed 

### Additional information

Please provide any solution to solve this issue and suggest any guidelines to overcome this issue in future.

**Comment by mdegat01** [comment]
Please share the supervisor logs, system health info and diagnostics as requested in the issue template. Particularly the logs and system health info.

> Real time system not synchronized with home assistant. Because whenever i recall scene ,it shows wrong date & time as triggered

This sounds like an NTP issue. HAOS uses time.cloudflare.com by default, is the HA system having network issues or is that blocked on your network by any chance? If using that is a problem for you there is a way to change it [here](https://github.com/home-assistant/operating-system/blob/dev/Documentation/configuration.md)
