### ISSUE TITLE
Error on call http://172.30.32.1:8123/api/config

### ISSUE THREAD

**Issue by datvista** [home-assistant/supervisor#4097]
### Describe the issue you are experiencing

ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config:

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

## System Information

version | core-2023.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Asia/Ho_Chi_Minh
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.29.1
Stage | running
Available Repositories | 1198
Downloaded Repositories | 6

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 109.3 GB
disk_used | 6.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), File editor (5.4.2), Home Assistant Google Drive Backup (0.105.2), Mosquitto broker (6.1.3), NGINX Home Assistant SSL proxy (3.2.0), RTSPtoWeb - WebRTC (1.4.0), SSH & Web Terminal (13.0.0), WireGuard (0.7.1), Zigbee2MQTT (1.29.1-1), Let's Encrypt (4.12.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 3
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 05:59 9 tháng 1, 2023
-- | --
current_recorder_run | 12:30 10 tháng 1, 2023
estimated_db_size | 62.66 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Xiaomi Gateway 3</summary>

version | 3.0a1 (4a00563)
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-01-10 14:26:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-01-10 14:26:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-01-10 14:26:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-01-10 14:26:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-01-10 14:26:13 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-01-10 14:26:13 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-10 14:26:14 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-10 14:26:14 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-01-10 14:26:14 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-10 14:26:18 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config: 
23-01-10 14:26:44 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config: 
23-01-10 14:42:43 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config: 
23-01-10 14:55:28 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-10 14:59:10 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config:
```

## System Information

version | core-2023.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Asia/Ho_Chi_Minh
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.29.1
Stage | running
Available Repositories | 1198
Downloaded Repositories | 6

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 109.3 GB
disk_used | 6.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), File editor (5.4.2), Home Assistant Google Drive Backup (0.105.2), Mosquitto broker (6.1.3), NGINX Home Assistant SSL proxy (3.2.0), RTSPtoWeb - WebRTC (1.4.0), SSH & Web Terminal (13.0.0), WireGuard (0.7.1), Zigbee2MQTT (1.29.1-1), Let's Encrypt (4.12.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 3
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 05:59 9 tháng 1, 2023
-- | --
current_recorder_run | 12:30 10 tháng 1, 2023
estimated_db_size | 62.66 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Xiaomi Gateway 3</summary>

version | 3.0a1 (4a00563)
-- | --

</details>

**Comment by mdegat01** [comment]
Are you just reporting an error you saw in the log or is something broken for you? If something is not working for you can you please describe what that is?
