### ISSUE TITLE
[supervisor.dbus.agent] Can't connect to OS-Agent

### ISSUE THREAD

**Issue by olyashok** [home-assistant/supervisor#4102]
### Describe the issue you are experiencing

23-01-14 21:49:56 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor ghcr.io/home-assistant/amd64-hassio-supervisor with version 2022.12.1
23-01-14 21:49:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
23-01-14 21:49:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-14 21:49:56 INFO (MainThread) [__main__] Setting up Supervisor
23-01-14 21:49:56 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
23-01-14 21:49:56 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.manager] Connected to system D-Bus.
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.agent] Load dbus interface io.hass.os
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.hostname] Load dbus interface org.freedesktop.hostname1
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.logind] Load dbus interface org.freedesktop.login1
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.network] Load dbus interface org.freedesktop.NetworkManager
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.rauc] Load dbus interface de.pengutronix.rauc
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.resolved] Load dbus interface org.freedesktop.resolve1
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.systemd] Load dbus interface org.freedesktop.systemd1
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.timedate] Load dbus interface org.freedesktop.timedate1
23-01-14 21:49:56 WARNING (MainThread) [supervisor.dbus.agent] Can't connect to OS-Agent

I added some debug info to agent/__init__.py:101 and DBusError is 

23-01-14 22:00:58 INFO (MainThread) [supervisor.dbus.timedate] Load dbus interface org.freedesktop.timedate1
23-01-14 22:00:58 WARNING (MainThread) [supervisor.dbus.agent] Can't load dbus interface io.hass.os: Object does not implement the interface 'org.freedesktop.DBus.Properties'

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Run Supervisor 
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-01-14 21:49:56 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor ghcr.io/home-assistant/amd64-hassio-supervisor with version 2022.12.1
23-01-14 21:49:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
23-01-14 21:49:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-14 21:49:56 INFO (MainThread) [__main__] Setting up Supervisor
23-01-14 21:49:56 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
23-01-14 21:49:56 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.manager] Connected to system D-Bus.
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.agent] Load dbus interface io.hass.os
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.hostname] Load dbus interface org.freedesktop.hostname1
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.logind] Load dbus interface org.freedesktop.login1
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.network] Load dbus interface org.freedesktop.NetworkManager
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.rauc] Load dbus interface de.pengutronix.rauc
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.resolved] Load dbus interface org.freedesktop.resolve1
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.systemd] Load dbus interface org.freedesktop.systemd1
23-01-14 21:49:56 INFO (MainThread) [supervisor.dbus.timedate] Load dbus interface org.freedesktop.timedate1
23-01-14 21:49:56 WARNING (MainThread) [supervisor.dbus.agent] Can't connect to OS-Agent

I added some debug info to agent/__init__.py:101 and DBusError is 

23-01-14 22:00:58 INFO (MainThread) [supervisor.dbus.timedate] Load dbus interface org.freedesktop.timedate1
23-01-14 22:00:58 WARNING (MainThread) [supervisor.dbus.agent] Can't load dbus interface io.hass.os: Object does not implement the interface 'org.freedesktop.DBus.Properties'
```

### System Health information

No issues

**Comment by mdegat01** [comment]
Can you share your system health information as requested in the issue template? Click this and copy and paste from the pop-up:
[![Open your Home Assistant instance and show information about your system.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)

Also what version of OS are you running? I just tested on 9.4 as well as dev and am not seeing any issues like this. And the `io.hass.os` object clearly implements the properties interface:
```
# gdbus introspect --system --dest io.hass.os --object-path /io/hass/os
node /io/hass/os {
  interface org.freedesktop.DBus.Introspectable {
    methods:
      Introspect(out s out);
    signals:
    properties:
  };
  interface org.freedesktop.DBus.Properties {
    methods:
      Get(in  s interface,
          in  s property,
          out v value);
      GetAll(in  s interface,
             out a{sv} props);
      Set(in  s interface,
          in  s property,
          in  v value);
    signals:
      PropertiesChanged(s interface,
                        a{sv} changed_properties,
                        as invalidates_properties);
    properties:
  };
  interface io.hass.os {
    methods:
    signals:
    properties:
      @org.freedesktop.DBus.Property.EmitsChangedSignal("invalidates")
      readonly s Version = '1.4.1';
      @org.freedesktop.DBus.Property.EmitsChangedSignal("true")
      readwrite b Diagnostics = true;
  };
};
```

**Comment by olyashok** [comment]
Debian 11 supervised
In health I have a lot cause i am trying to clean it up after uprgade to debian 11:
- unsupported software - portainer
- source code modifiactions - cause i added debug below
- protections disabled - to be able to clean up 
- docker misconfigured - i have journal and overlay enabled and cgroup v1 not sure why this is complaining

i debugged the error i submitted and it fails  in connecting Supervised board in updating properties for org.freedesktop.NetworkManager /org/freedesktop/NetworkManager/Devices/3

on this line

https://github.com/home-assistant/supervisor/blob/0a753c55cabd9af41439ff243106ef06d9abd8a6/supervisor/dbus/interface.py#L92
