### ISSUE TITLE
DNS repeatedly breaking

### ISSUE THREAD

**Issue by Danger-Moose** [home-assistant/supervisor#4118]
### Describe the issue you are experiencing

Unable to resolve known hosts with wget, unable to ping by non-IP address.

ping google.com returns:
ping: bad address 'google.com'

I did ha dns downgrade - and ping and wget work for a non-specific amount of time... then goes back to not resolving or not being able to ping.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. ping google.com
2. wget
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Possibly, when attempting to install HACS:

Logger: custom_components.hacs
Source: custom_components/hacs/config_flow.py:49
Integration: HACS (documentation, issues)
First occurred: 2:08:12 PM (5 occurrences)
Last logged: 3:59:06 PM
Request exception for 'https://github.com/login/device/code' with - Cannot connect to host github.com:443 ssl:default [Try again]
```

### System Health information

There are currently no repairs available.

### Supervisor diagnostics

[config_entry-hassio-a3588387385804666d4671310506c032.json.txt](https://github.com/home-assistant/supervisor/files/10503721/config_entry-hassio-a3588387385804666d4671310506c032.json.txt)

**Comment by mdegat01** [comment]
That's not the supervisor log, you're showing the core logs. Can you check the supervisor logs to see if there's any useful in there? You can find it in the UI by going to [Settings -> System -> Logs](https://my.home-assistant.io/redirect/logs/) and then changing the dropdown to "Supervisor" in the top right corner. Or by entering `ha supervisor logs` in the CLI.

On that note can you share the results of `ha dns info` in the CLI?

**Comment by Danger-Moose** [comment]
Supervisor log for just now when I triggered a downgrade, was able to ping, and then the ping stopped working:

`23-01-26 08:15:45 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-01-26 08:15:46 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-26 08:15:47 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-26 08:22:25 INFO (MainThread) [supervisor.host.info] Updating local host information
23-01-26 08:22:26 INFO (MainThread) [supervisor.host.services] Updating service information
23-01-26 08:22:26 INFO (MainThread) [supervisor.host.network] Updating local network information
23-01-26 08:22:27 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-01-26 08:22:27 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-01-26 08:29:51 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
23-01-26 08:29:51 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
23-01-26 08:29:51 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh
23-01-26 08:29:51 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh
23-01-26 08:30:32 INFO (MainThread) [supervisor.api.middleware.security] /dns/update access from a0d7b954_ssh`

HA DNS INFO:
`fallback: true
host: 172.30.32.3
llmnr: true
locals:
- dns://8.8.8.8
mdns: true
servers:
- dns://8.8.8.8
update_available: false
version: 2022.04.1
version_latest: 2022.04.1`

Full supervisor log:
[supervisor_2023-01-26T13-38-16.669Z.log](https://github.com/home-assistant/supervisor/files/10509762/supervisor_2023-01-26T13-38-16.669Z.log)

**Comment by mdegat01** [comment]
When it happens again could you try running the following command and share the output:
```
nslookup google.com
```

**Comment by Danger-Moose** [comment]
I wound up reformating with Raspbian and just installing HA in a docker instance. It should be noted that I made no changes to my network or router and everything works perfectly now. Very weird problem.
