### ISSUE TITLE
HA OS stays unhealty setup (after reboot)

### ISSUE THREAD

**Issue by HumanGear322** [home-assistant/supervisor#4142]
### Describe the issue you are experiencing

I've tried all the suggestions on [this help page](https://www.home-assistant.io/more-info/unhealthy/setup/), but HA still reports an "unhealthy setup" error. Only problem in the list is "setup":

![image](https://user-images.githubusercontent.com/111016327/219032423-7e8a8e03-c6de-428c-add5-6893b9bc7807.png)

![image](https://user-images.githubusercontent.com/111016327/219032555-04b6f78c-25bb-4282-b5d2-fafb1e47253e.png)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-02-15 12:54:50 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy - setup
23-02-15 13:32:52 WARNING (MainThread) [supervisor.jobs] 'HomeAssistantCore.update' blocked from execution, system is not healthy - setup
```

### System Health information

![image](https://user-images.githubusercontent.com/111016327/219037945-2de7a958-7e69-4c43-a734-c5667f17d032.png)

### Supervisor diagnostics

[config_entry-hassio-aafe1aa7308c313a32f47c5d9c892e93.json.txt](https://github.com/home-assistant/supervisor/files/10743330/config_entry-hassio-aafe1aa7308c313a32f47c5d9c892e93.json.txt)

**Comment by pvizeli** [comment]
can you post the information from `ha res info`?

**Comment by HumanGear322** [comment]
I'm sorry, but I don't have SSH/CLI addons running. Is there another way to gather this information?

**Comment by pvizeli** [comment]
post "More information" on the red flag

**Comment by HumanGear322** [comment]
[supervisor_2023-02-15T20-10-03.138Z.log](https://github.com/home-assistant/supervisor/files/10747153/supervisor_2023-02-15T20-10-03.138Z.log)

**Comment by HumanGear322** [comment]
@pvizeli, Nothing useless in the logs?

**Comment by HumanGear322** [comment]
Flashed my SD card today and restored the latest full backup.
Was relatively easy and apparently it solved the problem.
