### ISSUE TITLE
Disk fills with uninstalled add-on images

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/supervisor#4148]
### The problem

I got the message that my automated backups failed, so I looked at the free disk space. It shows a full disk:

![Screenshot_2023-02-14-08-42-52-476-edit_io homeassistant companion android](https://user-images.githubusercontent.com/614929/219275546-a62ab3f2-d9b8-4943-aa72-84bdfaab1488.jpg)

This made no sense to me, as I haven't been adding a lot of data to any add-on or similar.

After logging in via SSH and looking around, seeing nothing obvious, I've looked via MySQL admin on the MariaDB server. The space requirements were within my expectations, too.

So I've installed Portainer as add-on and looked at the containers and images.

Looks like HA Core/HA Supervisor missed cleaning them up:

There are two add-on containers, which are not installed according to the Add-On page in HA, but exist in the list in Portainer and are shown as “exited”.

In addition, there are loads of images from add-ons which are also no longer installed – this is what in the end is using up my memory – 38 in total.

### What version of Home Assistant Core has the issue?

2023.2.3

### What was the last working version of Home Assistant Core?

unknown

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

unknown

### Link to integration documentation on our website

unknown

### Diagnostics information

unknown how to get this for the add-on control

**Comment by alexbelgium** [comment]
Hi, execute ‘ha su repair‘ in cli to clean all those images

**Comment by Sniperson2002** [comment]
Confirmed, 3.8 Gb recovered. I have been searching for a cure for this for a quite some time.  Thank you!
