### ISSUE TITLE
Unhealthy system - Setup failed

### ISSUE THREAD

**Issue by sergiizaskaleta** [home-assistant/supervisor#4156]
### Describe the issue you are experiencing

I get an error message "Unhealthy system - Setup failed".
```
System is currently unhealthy because setup failed to complete. There are a number of reasons this can occur, use the link to learn more and how to fix this.
Critical - 07/02/2023
```

following [learn more](https://www.home-assistant.io/more-info/unhealthy/setup) i can deduce that this is NOT a DBUS issue because there is no matching error.
Restart Supervisor does not help.
Reboot host does not help.
`ha supervisor repair` does not help.

Also it seems this is not an NTP issue as date sync fine.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Unsure. This started appearing around Home Assistant updates to versions starting 2023 and frequent power "flicks" of the HA device (thanks russia).

### Anything in the Supervisor logs that might be useful for us?

```txt
Everything is "green" starting from restart, till the moment when Supervisor decides it's unhealthy.


[13:17:59] INFO: Supervisor restart after closing
23-02-22 15:20:35 INFO (MainThread) [supervisor.docker.monitor] Started docker events monitor
23-02-22 15:20:35 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-cli with version 2022.11.0
23-02-22 15:20:35 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
23-02-22 15:20:36 INFO (SyncWorker_1) [supervisor.docker.cli] Starting CLI ghcr.io/home-assistant/aarch64-hassio-cli with version 2022.11.0 - 172.30.32.5
23-02-22 15:20:36 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-dns with version 2022.04.1
23-02-22 15:20:36 INFO (MainThread) [supervisor.plugins.dns] Starting CoreDNS plugin
23-02-22 15:20:38 INFO (SyncWorker_0) [supervisor.docker.dns] Starting DNS ghcr.io/home-assistant/aarch64-hassio-dns with version 2022.04.1 - 172.30.32.3
23-02-22 15:20:38 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
23-02-22 15:20:38 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-audio with version 2022.07.0
23-02-22 15:20:38 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
23-02-22 15:20:39 INFO (SyncWorker_1) [supervisor.docker.audio] Starting Audio ghcr.io/home-assistant/aarch64-hassio-audio with version 2022.07.0 - 172.30.32.4
23-02-22 15:20:39 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-observer with version 2021.10.0
23-02-22 15:20:39 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-multicast with version 2022.02.0
23-02-22 15:20:39 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin
23-02-22 15:20:41 INFO (SyncWorker_0) [supervisor.docker.multicast] Starting Multicast ghcr.io/home-assistant/aarch64-hassio-multicast with version 2022.02.0 - Host
23-02-22 15:20:41 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-02-22 15:20:42 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 2 Home Assistant secrets
23-02-22 15:20:42 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/raspberrypi4-64-homeassistant with version 2023.2.5
23-02-22 15:20:42 INFO (MainThread) [supervisor.os.manager] Detect Home Assistant Operating System 9.5 / BootSlot B
23-02-22 15:20:43 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
23-02-22 15:20:43 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/5c53de3b repository
23-02-22 15:20:43 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
23-02-22 15:20:44 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 68 new - 0 remove
23-02-22 15:20:44 INFO (MainThread) [supervisor.addons] Found 5 installed add-ons
23-02-22 15:20:44 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/vscode/aarch64 with version 5.5.2
23-02-22 15:20:44 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to ghcr.io/esphome/esphome-hassio with version 2023.2.3
23-02-22 15:20:44 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-ssh with version 9.6.1
23-02-22 15:20:44 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-mariadb with version 2.5.2
23-02-22 15:20:44 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-configurator with version 5.5.0
23-02-22 15:20:44 INFO (MainThread) [supervisor.backups.manager] Found 7 backup files
23-02-22 15:20:45 INFO (MainThread) [supervisor.discovery] Loaded 1 messages
23-02-22 15:20:45 INFO (MainThread) [supervisor.ingress] Loaded 47 ingress sessions
23-02-22 15:20:45 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
23-02-22 15:20:45 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-02-22 15:20:45 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
23-02-22 15:20:45 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-02-22 15:20:45 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy - setup
23-02-22 15:20:45 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
23-02-22 15:20:45 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-02-22 15:20:45 INFO (MainThread) [__main__] Running Supervisor
23-02-22 15:20:45 CRITICAL (MainThread) [supervisor.core] System is running in an unhealthy state and needs manual intervention!
```

## System Information

version | core-2023.2.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Kiev
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4952
Installed Version | 1.29.1
Stage | running
Available Repositories | 1215
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 116.5 GB
disk_used | 8.8 GB
healthy | failed to load: Unhealthy
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.2.3), Studio Code Server (5.5.2), Terminal & SSH (9.6.1), File editor (5.5.0), MariaDB (2.5.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13 July 2022 at 11:33
-- | --
current_recorder_run | 22 February 2023 at 15:21
estimated_db_size | 1048.38 MiB
database_engine | mysql
database_version | 10.6.10

</details>

### Supervisor diagnostics

[config_entry-hassio-dad083268b21ceb23e3b3ee23e425400.json.txt](https://github.com/home-assistant/supervisor/files/10804390/config_entry-hassio-dad083268b21ceb23e3b3ee23e425400.json.txt)

### Additional information

The issue is(was?) connected with intermitted breakages of History:
History tab says "No state history found" / and "Unable to load history: invalid start time" on the GUI dashboards with history widgets.
But History issue is intermittent and is not reproducing currently... Setup is Unhealthy persists.

**Comment by korenke** [comment]
I have the same problem. Started appearing at some point in the last few weeks. Blocks me from updating or installing anything else.

**Comment by pvizeli** [comment]
`ha su restart`
and right after that, post the full log of the supervisor:
`ha su logs`

**Comment by korenke** [comment]
My problem resolved with the latest restart. Thanks for offering help.
