### ISSUE TITLE
Can't load supervisor panel

### ISSUE THREAD

**Issue by Frenk121** [home-assistant/supervisor#4157]
### Describe the issue you are experiencing

When I go to Add-ons I get: Can't load supervisor panel.
When I reset the HA core host, it also need a lot of time to load, then it works.
After a while I come back and get the error Can't load supervisor panel in Add-ons

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:488
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 01:23:28 (162 occurrences)
Last logged: 15:17:59

Can't read Supervisor data:
-----------------------------------------------------------------------------------

Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:48
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 01:23:28 (1627 occurrences)
Last logged: 15:17:59

Timeout on /supervisor/info request
Timeout on /info request
Timeout on /core/info request
Timeout on /host/info request
Timeout on /store request

--------------------------------------------------------------------------------------
Logger: homeassistant.components.hassio
Source: helpers/update_coordinator.py:182
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 01:24:35 (1 occurrences)
Last logged: 01:24:35

Error fetching hassio data: Error on Supervisor API:

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Observer details:

Supervisor: | Connected
Supported: | Supported
Healthy: | Healthy

Home Assistant 2023.2.5

### Anything in the Supervisor logs that might be useful for us?

```txt
Ophalen supervisor-logs mislukt, 502: Bad Gateway
```

### System Health information

-

### Supervisor diagnostics

[config_entry-hassio-abe2c7c45ccf8d52a60ab1f11b5c8d11.json.txt](https://github.com/home-assistant/supervisor/files/10804826/config_entry-hassio-abe2c7c45ccf8d52a60ab1f11b5c8d11.json.txt)

**Comment by mattjukes** [comment]
This same issue appeared to be today when accessing Addons.

I also see the following when opening File Editor & Node Red: "Unable to load the panel source: /api/hassio/app/entrypoint.js."
