### ISSUE TITLE
HELP wanted: /ingress/validate_session return code 401 

### ISSUE THREAD

**Issue by guenter-ms** [home-assistant/supervisor#4183]
### Describe the issue you are experiencing

Hello,
since 2 weeks the core log is flooded with error message, see screenshot.
From my understanding there is an authorization issue with the supervisor, managing addons.
I have NO IDEA how to get closer to the problem. I disabled all addons , removed HACS, rebooted several times…
I created new user with admin rights, I checked CPU/MEM with glances on the r4 with 4GB mem, all OK.
using safari and chrome on different macOS clients, same problem.
Trying to show the supervisor log results in timeout: 502: Bad gateway. 
What can I do?
THANK YOU for any hint!

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

1. Restart
2. Login
3. wait some minutes
4. open Logs/core and supervisor
5. see messages in screenshot (above)

### Anything in the Supervisor logs that might be useful for us?

```txt
cannot access the log (timeout), how can I do that?
```

### System Health information

No repairs available
![Bildschirmfoto 2023-03-10 um 15 25 56](https://user-images.githubusercontent.com/6253315/224341061-f25b1586-64bd-4319-bff2-65e614d4fb4d.jpg)

### Supervisor diagnostics

[config_entry-hassio-303d17c610c50b683b6237ebfeee516e.json (2).txt](https://github.com/home-assistant/supervisor/files/10942921/config_entry-hassio-303d17c610c50b683b6237ebfeee516e.json.2.txt)

### Additional information

Thats all I have
Thank you

**Comment by guenter-ms** [comment]
Screenshots:

![Bildschirmfoto 2023-03-10 um 15 24 46](https://user-images.githubusercontent.com/6253315/224342011-bea73609-0e7e-4d45-ad2a-6c9447750e26.jpg)
![Bildschirmfoto 2023-03-10 um 12 20 37](https://user-images.githubusercontent.com/6253315/224342024-45214546-312a-4ae4-a01b-4379715a5f23.jpg)

**Comment by guenter-ms** [comment]
After disabling more and more in the integrations i got now this supervisor log:
[supervisor_2023-03-10T14-49-45.378Z.log](https://github.com/home-assistant/supervisor/files/10943174/supervisor_2023-03-10T14-49-45.378Z.log)

**Comment by dominiczedler** [comment]
Same issue here, I didn't find any other open issues like that but users of my app and myself have the same issue (patzly/grocy-android#670). 

After the latest (core?) update, I just cannot get ingress session tokens anymore - the `/api/hassio/ingress/session` always returns 401 unauthorised error. I wonder what the problem is, the ingress webpage of the addon is still working.

**Comment by marrobHD** [comment]
>That is correct behavior and not a bug. That endpoint is not meant for general usage. If you want to interact with an add-on, please do so, using their own native APIs.

>../Frenck

_Originally posted by @frenck in https://github.com/home-assistant/core/issues/89536#issuecomment-1464884824_

**Comment by guenter-ms** [comment]
SOLVED!

After a lot of investigation I found this: https://www.youtube.com/watch?v=fMlIV6kNzaA

Finally I installed a new SSD https://www.amazon.de/dp/B0742KXY2R?psc=1&ref=ppx_yo2ov_dt_b_product_details 
and checked that UASP was disabled by default = good. See last line in screenshot.

And now HA is running as fast as never before.

Take care.

![Bildschirmfoto 2023-03-11 um 14 23 06](https://user-images.githubusercontent.com/6253315/224487114-55d5e97e-0397-413b-9182-5a6247ee50ac.jpg)
