### ISSUE TITLE
Long-Lived Access Token keeps popping the same Token

### ISSUE THREAD

**Issue by MrSaatci** [home-assistant/supervisor#4184]
### Describe the issue you are experiencing

I’m trying to set up something and I’m force to type the long-lived access token into my app, the 1st I’ve got had too many “l” and “I” which made it a hell to type since it’s almost impossible to tell the capital “i” from lower case L, so I tried to generate another token.

To my surprise, no matter what I do or where I generate it (from the iOS app, or on my laptop) I keep getting the same token. And what’s even weirder, when I click “Create” I get a new token alright, but a couple of seconds later it magically turns in front of my eyes to the original horrible token, this also happens immeadiately if I generate QR code.

What could be possibly be the reason? I already clean cache and cookies.

Any ideas?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Create a Long-Lived Access Token
2. Save It
3. Create another Long-Lived Access Token
4.  Generate QR
...

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

## System Information

version | core-2023.2.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | America/Mexico_City
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.30.1
Stage | running
Available Repositories | 1247
Downloaded Repositories | 72

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 4, 2023 at 6:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-5.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 109.3 GB
disk_used | 53.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), File editor (5.5.0), Spotify Connect (0.12.2), Terminal & SSH (9.6.1), Log Viewer (0.14.0), SSH & Web Terminal (13.0.3), Squeezelite (0.12), Ring Livestream (1.35), MariaDB (2.5.2), Duck DNS (1.15.0), Nginx Proxy Manager (0.12.3), Logitech Media Server (0.0.53), Glances (0.17.2), Mosquitto broker (6.1.3), Home Panel (2.5.0), Studio Code Server (5.5.3), chrony (2.5.0), ESPHome (2023.2.4), AppDaemon (0.11.0), Dnsmasq (1.5.1), Let's Encrypt (4.12.8), TasmoAdmin (0.23.0), HassOS SSH port 22222 Configurator (0.9.1a), Ring-MQTT with Video Streaming (5.1.3), CEC Scanner (3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 63
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 4, 2023 at 1:33 AM
-- | --
current_recorder_run | March 8, 2023 at 10:05 PM
estimated_db_size | 247.60 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by ludeeus** [comment]
Are you sure it's the same?
It's JWT so the first parts of it look the same, but should not be possible if you do not have some custom code that interferes with your system.
This code is not meant to be typed, really.

When you generate it you see the 10-20 last part of it, but when the component repaint/refreshed, you see the beginning 10-20 (staring with ey (JWT format))
When you click generate QR it also shows the 10-20 first.

**Comment by MrSaatci** [comment]
Just tested, and I'm not sure what's going on

When I create the token and I copy it I get this:
q65qxwMZG0uEhX1UZkC9l1RXrESxMJN_KGuqhsuPY5E

When I generate the QR Code I get to see this;
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3Mi

If I copy it and paste it:
OiI3NTRlYWYwZjhjMWM0MmY0OTRjNTNlNTRlMTJjODVhNyIsImlhdCI6MTY3ODU2OTcwMiwiZXhwIjoxOTkzOTI5NzAyfQ.q65qxwMZG0uEhX1UZkC9l1RXrESxMJN_KGuqhsuPY5E

**Comment by ludeeus** [comment]
The text is bigger than the size of the field, you have to scroll to see it all.

> When I create the token and I copy it I get this:
q65qxwMZG0uEhX1UZkC9l1RXrESxMJN_KGuqhsuPY5E

That is the last part

> When I generate the QR Code I get to see this;
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3Mi

That is the first part

> If I copy it and paste it:

That is also the last part, but have more of the start, almost looks like you cut the part you pasted that starts with ey.

Better to mark all (ctrl+a) and copy to clipboard (ctrl+c).

But these are all the same, are you sure you always get a code that starts with `eyJhbGciOiJIUzI1NiIsInR...` and ends in `...uPY5E`?

**Comment by MrSaatci** [comment]
Oh I see!
So I must always click on Generate QR Code otherwise I'd be copying it incomplete, correct?

**Comment by ludeeus** [comment]
No.
Both have the whole code.

**Comment by MrSaatci** [comment]
This is the part that I always see when I generate QR Code:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3Mi

**Comment by ludeeus** [comment]
Right... but again, that is not the whole code, it will always start with that part.

**Comment by MrSaatci** [comment]
I get it now. Thank you. I was double-clicking on it and I assumed all was being selected.
