### ISSUE TITLE
Tuya devices not updating

### ISSUE THREAD

**Issue by hdupreez** [home-assistant/supervisor#4205]
### Describe the issue you are experiencing

After the last update, Tuya devices not updating. Local tuya devices are working fine

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:388 
First occurred: 23:44:18 (1 occurrences) 
Last logged: 23:44:18

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 158, in run
    self.__run_mqtt()
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 172, in __run_mqtt
    mqttc = self._start(mq_config)
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 192, in _start
    mqttc.connect(url.hostname, url.port)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
```

### System Health information

No repairs needed

### Supervisor diagnostics

>

**Comment by applegeeks** [comment]
Not seeing this error/s appear on my logs, however, I can confirm I am seeing the same issue after updating to Core update **2023.3.6**.
1. I even went as far as setting up a secondary HA setup.
2. Restored my main primary setup to a **2023.3.5** core backup and
3. Setup up secondary instance to the **2023.3.6** core update.

Can definitely see that the secondary setup running the **2023.3.6** core update stops reflecting the device state after a while despite the primary instance, still accurately reflecting the device states.

**Comment by hdupreez** [comment]
@applegeeks thanks for confirming this issue. I was also not able to find an error to confirm this. I am still running on 2023.3.6.

I have been monitoring the issue and have found that the Tuya devices do update after some time (in the excess of 10-30min plus). On the previous release, the update was instantaneous.  I really hope the issue will get resolved soon….

**Comment by kvshino** [comment]
Same here, with 2023.3.6 tuja does not work anymore :(

**Comment by applegeeks** [comment]
> @applegeeks thanks for confirming this issue. I was also not able to find an error to confirm this. I am still running on 2023.3.6.
> 
> I have been monitoring the issue and have found that the Tuya devices do update after some time (in the excess of 10-30min plus). On the previous release, the update was instantaneous. I really hope the issue will get resolved soon….

@hdupreez unfortunately for my case, the secondary instance (despite being a backup restore of the main instance except its running 2023.3.6, the states for the tuya devices never update unless the supervisor/integration is reloaded or the entire host is rebooted. :(

I agree, hope it gets fixed soon. The good thing about this incident is that I've now forced myself to implement a prod and test environment and will be testing the latest updates on the test environment first from now on before applying in my prod/main instance.

**Comment by XxAcielxX** [comment]
Same issue here as well since few weeks and it is getting worst day by day. Though I'm using docker version by LSIO.

**Comment by kvshino** [comment]
i'm using hass supervised on debian

**Comment by sniperkiki** [comment]
I did workaround to reload Tuya service on 10 minutes interval
https://github.com/home-assistant/core/issues/90333#issuecomment-1485365060

**Comment by hdupreez** [comment]
My Tuya devices is updating again, like on the previous update. I did absolutely nothing. Any of you experiencing the same thing?

**Comment by XxAcielxX** [comment]
Mine has been very much stable today. Which is a good thing.

**Comment by applegeeks** [comment]
> My Tuya devices is updating again, like on the previous update. I did absolutely nothing. Any of you experiencing the same thing?

have powered down my test instance running 2023.3.6 and have been running/reverted to 2023.3.5 on my main HA instance now.

will try and test it again but will most likely wait until the next version release to test again to be safe since 2023.3.6 doesnt really offer anything **new** that my currently setup needs to use/depend on.

**Comment by XxAcielxX** [comment]
For 2 days it worked good, but today it started again. It feels like this issue is coming from Tuya itself maybe.

**Comment by sniperkiki** [comment]
Today is killing me also... even tho I'm restarting service every 10 minutes.

This morning all my Tuya devices were removed from Home Assistant, had to reload everything manually :(

**Comment by hdupreez** [comment]
My Tuya devices is again not updating. I will have to implement the reloading code suggested.

**Comment by midadami** [comment]
Same problem. Some days it seems to work fine. Other days it doesn't work at all.

**Comment by Jamstam** [comment]
Same problem. I use a garage opener to open the gate. Very annoying if it does't have a correct state.
