### ISSUE TITLE
Supervisor Store Data Warning

### ISSUE THREAD

**Issue by malmaxx** [home-assistant/supervisor#4251]
### Describe the issue you are experiencing

This error started occurring at some point within the prior 24 hours but not sure when or why.

23-04-20 17:12:32 WARNING (SyncWorker_4) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-20 17:12:33 WARNING (SyncWorker_1) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

I do not know how to reproduce the error or what is causing it.

### Anything in the Supervisor logs that might be useful for us?

```txt
3-04-20 17:11:56 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/vscode/aarch64 with version 5.5.6
23-04-20 17:11:56 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-ssh with version 9.7.0
23-04-20 17:11:56 INFO (SyncWorker_7) [supervisor.docker.interface] Attaching to zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.30.3-1
23-04-20 17:11:56 INFO (MainThread) [supervisor.backups.manager] Found 36 backup files
23-04-20 17:11:56 INFO (MainThread) [supervisor.discovery] Loaded 2 messages
23-04-20 17:11:56 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
23-04-20 17:11:56 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
23-04-20 17:11:56 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-04-20 17:11:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
23-04-20 17:11:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-04-20 17:11:56 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
23-04-20 17:11:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
23-04-20 17:11:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-04-20 17:11:56 INFO (MainThread) [__main__] Running Supervisor
23-04-20 17:11:56 INFO (MainThread) [supervisor.os.manager] Rauc: A - marked slot kernel.0 as good
23-04-20 17:11:56 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
23-04-20 17:11:56 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 3 add-ons
23-04-20 17:11:57 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.2.0
23-04-20 17:11:59 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/zwave-js-ui/aarch64 with version 1.11.1
23-04-20 17:12:00 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mariadb with version 2.5.2
23-04-20 17:12:04 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
23-04-20 17:12:05 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 3 add-ons
23-04-20 17:12:05 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_duckdns application
23-04-20 17:12:07 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-duckdns with version 1.15.0
23-04-20 17:12:07 INFO (MainThread) [supervisor.services.modules.mysql] Set core_mariadb as service provider for MySQL
23-04-20 17:12:08 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/vscode/aarch64 with version 5.5.6
23-04-20 17:12:10 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ghcr.io/sharptools-io/sharptools-hass-addon-connector-aarch64 with version 1.0.7
23-04-20 17:12:15 INFO (MainThread) [supervisor.core] Start Home Assistant Core
23-04-20 17:12:15 INFO (SyncWorker_2) [supervisor.docker.interface] Starting homeassistant
23-04-20 17:12:16 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-04-20 17:12:22 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'svc_mosquitto'
23-04-20 17:12:22 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
23-04-20 17:12:27 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/ttyACM0 - /dev/serial/by-id/usb-0658_0200-if00
23-04-20 17:12:27 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/bus/usb/001/007 - None
23-04-20 17:12:30 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP
23-04-20 17:12:30 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-04-20 17:12:30 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/bus/usb/001/008 - None
23-04-20 17:12:30 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/ttyACM0 - /dev/serial/by-id/usb-0658_0200-if00
23-04-20 17:12:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-04-20 17:12:31 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-04-20 17:12:31 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sharptools-io/hass-addons.git repository
23-04-20 17:12:31 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-04-20 17:12:31 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-04-20 17:12:31 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
23-04-20 17:12:31 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-04-20 17:12:32 WARNING (SyncWorker_4) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-20 17:12:33 WARNING (SyncWorker_1) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-20 17:12:34 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove
23-04-20 17:12:34 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove
23-04-20 17:13:01 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-04-20 17:13:01 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 2 add-ons
23-04-20 17:13:02 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-aarch64 with version 1.30.3-1
23-04-20 17:13:04 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-nginx_proxy with version 3.4.0
23-04-20 17:13:06 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_nginx_proxy
23-04-20 17:13:08 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-04-20 17:13:08 INFO (MainThread) [supervisor.api.proxy] WebSocket access from 506c6dd7_sharptools_io
23-04-20 17:13:08 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-04-20 17:13:09 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
23-04-20 17:13:09 INFO (MainThread) [supervisor.core] Supervisor is up and running
23-04-20 17:13:09 INFO (MainThread) [supervisor.host.info] Updating local host information
23-04-20 17:13:09 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.CREATE_FULL_BACKUP - ContextType.SYSTEM / None
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.NO_CURRENT_BACKUP - ContextType.SYSTEM / None
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-04-20 17:13:09 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-04-20 17:13:10 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-04-20 17:13:10 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-04-20 17:13:10 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-04-20 17:13:10 INFO (MainThread) [supervisor.host.services] Updating service information
23-04-20 17:13:10 INFO (MainThread) [supervisor.host.network] Updating local network information
23-04-20 17:13:11 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-04-20 17:13:11 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-04-20 17:13:12 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from 506c6dd7_sharptools_io
23-04-20 17:13:12 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from 506c6dd7_sharptools_io
```

## System Information

version | core-2023.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4975
Installed Version | 1.32.1
Stage | running
Available Repositories | 1268
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.0
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 457.7 GB
disk_used | 12.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.0), Zigbee2MQTT (1.30.3-1), Terminal & SSH (9.7.0), Z-Wave JS UI (1.11.1), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.4.0), Studio Code Server (5.5.6), MariaDB (2.5.2), SharpTools.io (1.0.7), SSH & Web Terminal (13.1.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 23, 2023 at 10:33 PM
-- | --
current_recorder_run | April 20, 2023 at 5:12 PM
estimated_db_size | 436.05 MiB
database_engine | mysql
database_version | 10.6.10

</details>

### Supervisor diagnostics

[supervisor_2023-04-20T22-19-38.416Z.log](https://github.com/home-assistant/supervisor/files/11290867/supervisor_2023-04-20T22-19-38.416Z.log)

**Comment by RogerSelwyn** [comment]
I have also been getting this over the last 24 hours

**Comment by aes-alienrip** [comment]
23-04-21 19:21:30 WARNING (SyncWorker_5) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-21 19:21:30 WARNING (SyncWorker_5) [supervisor.store.data] Can't read /data/addons/core/piper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-21 19:21:31 WARNING (SyncWorker_0) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-21 19:21:32 WARNING (SyncWorker_0) [supervisor.store.data] Can't read /data/addons/core/piper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'

Got same warning messages

**Comment by AarvdH** [comment]
Hi, I have exactly the same issue. I think it is since 10.0.

**Comment by budswarez** [comment]
I have same problem
`23-04-21 15:30:05 WARNING (SyncWorker_7) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-21 15:30:05 WARNING (SyncWorker_7) [supervisor.store.data] Can't read /data/addons/core/piper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-21 15:30:06 WARNING (SyncWorker_5) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-21 15:30:06 WARNING (SyncWorker_5) [supervisor.store.data] Can't read /data/addons/core/piper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'`

**Comment by malmaxx** [comment]
I had to restart HA a moment ago and now seeing a new Warning line with "piper" along with the original reported.

3-04-21 15:12:54 WARNING (SyncWorker_6) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-21 15:12:54 WARNING (SyncWorker_6) [supervisor.store.data] Can't read /data/addons/core/**piper/**config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-21 15:12:54 WARNING (SyncWorker_5) [supervisor.store.data] Can't read /data/addons/core/whisper/config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'
23-04-21 15:12:54 WARNING (SyncWorker_5) [supervisor.store.data] Can't read /data/addons/core/**piper/**config.yaml: Service wyoming not found @ data['discovery'][0]. Got 'wyoming'

**Comment by ComputaBloke** [comment]
Can see this is due to inclusion of these additions as 'core' Add-ons to support:
 whisper for speech-to-text
 piper for text-to-speech
 
https://github.com/home-assistant/addons/blob/f0754645551b4b30389e16ba5a490fa0add424a8/whisper/config.yaml#L12
https://github.com/home-assistant/addons/blob/f0754645551b4b30389e16ba5a490fa0add424a8/piper/config.yaml#L12

Warnings occur whenever Supervisor Add-on does a 'Check for Updates'.
And due to the config error, whisper and piper are not shown in the add-on list.

I've left a comment against the recent tickets for dev to review.

**Comment by ludeeus** [comment]
This has now been resolved with <https://github.com/home-assistant/addons/pull/2999> and <https://github.com/home-assistant/addons/pull/3000>

**Comment by budswarez** [comment]
Thank you very much, so I have nothing to worry about, it was something related to the last updates
