### ISSUE TITLE
Failed to to call /store -  /store return code 500

### ISSUE THREAD

**Issue by Moosbrugger** [home-assistant/supervisor#4276]
### Describe the issue you are experiencing

Since installing Home Assistant 2023.4.6 -- & maybe before, whenever I restart HA I get the following error messages:

Failed to to call /store -

&

/store return code 500

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. restart HA
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
172.30.33.4:1337 ssl:default [Connect call failed ('172.30.33.4', 1337)]
23-05-02 13:19:17 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.4:1337 ssl:default [Connect call failed ('172.30.33.4', 1337)]
23-05-02 13:19:31 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.4:1337 ssl:default [Connect call failed ('172.30.33.4', 1337)]
23-05-02 13:19:45 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.4:1337 ssl:default [Connect call failed ('172.30.33.4', 1337)]
23-05-02 13:19:59 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.4:1337 ssl:default [Connect call failed ('172.30.33.4', 1337)]
23-05-02 13:20:13 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.4:1337 ssl:default [Connect call failed ('172.30.33.4', 1337)]
```

## System Information

version | core-2023.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4815
Installed Version | 1.32.1
Stage | running
Available Repositories | 1287
Downloaded Repositories | 29

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 3, 2024 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 110.0 GB
disk_used | 16.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.110.4), Samba share (10.0.1), AppDaemon (0.12.2), Z-Wave JS UI (1.11.2), MariaDB (2.5.2), Studio Code Server (5.5.7), Mosquitto broker (6.2.1), Zigbee2MQTT (1.30.4-1), Network UPS Tools (0.11.2), Advanced SSH & Web Terminal (14.0.0), ESPHome (2023.4.3), Grafana (8.2.2), InfluxDB (4.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 24
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 26, 2023 at 3:16 PM
-- | --
current_recorder_run | May 2, 2023 at 12:35 PM
estimated_db_size | 900.61 MiB
database_engine | mysql
database_version | 10.6.10

</details>

<details><summary>Sonoff</summary>

version | 3.5.1 (122751c)
-- | --
cloud_online | 0 / 0
local_online | 0 / 0

</details>

### Supervisor diagnostics

[config_entry-hassio-d6a07dd832f48f3574b1f912c13c5a0c.json.txt](https://github.com/home-assistant/supervisor/files/11376038/config_entry-hassio-d6a07dd832f48f3574b1f912c13c5a0c.json.txt)

**Comment by pimw1** [comment]
Hi, i've the same error. In my case, it did not happen during a reboot, but during normal operation. I've collected some logs:

Home Assistant Core logs:

> Logger: homeassistant.components.hassio.handler
> Source: components/hassio/handler.py:548
> Integration: Home Assistant Supervisor (documentation, issues)
> First occurred: 20:35:04 (9 occurrences)
> Last logged: 20:35:05
> 
> /addons/a0d7b954_glances/changelog return code 500
> /addons/7d80160c_mopidy/changelog return code 500
> /addons/a0d7b954_ssh/changelog return code 500
> /addons/ae9861ff_photons_interactor/changelog return code 500
> /addons/5c53de3b_esphome/changelog return code 500
> 
> 
> Logger: homeassistant.components.hassio
> Source: components/hassio/__init__.py:916
> Integration: Home Assistant Supervisor (documentation, issues)
> First occurred: 20:35:04 (9 occurrences)
> Last logged: 20:35:05
> 
> Could not fetch changelog for a0d7b954_glances:
> Could not fetch changelog for 7d80160c_mopidy:
> Could not fetch changelog for a0d7b954_ssh:
> Could not fetch changelog for ae9861ff_photons_interactor:
> Could not fetch changelog for 5c53de3b_esphome:

Part of the supervisor logs:

> 23-05-08 20:35:05 ERROR (MainThread) [aiohttp.server] Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
>     resp = await request_handler(request)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
>     return await handler(request)
>   File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
>     return await handler(request)
>   File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
>     return await handler(request)
>   File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
>     return await handler(request)
>   File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
>     return await handler(request)
>   File "/usr/src/supervisor/supervisor/api/utils.py", line 102, in wrap_api
>     msg_data = await method(api, *args, **kwargs)
>   File "/usr/src/supervisor/supervisor/api/store.py", line 248, in addons_addon_changelog
>     if not addon.with_changelog:
>   File "/usr/src/supervisor/supervisor/addons/model.py", line 499, in with_changelog
>     return self.path_changelog.exists()
>   File "/usr/src/supervisor/supervisor/addons/model.py", line 564, in path_changelog
>     return Path(self.path_location, "CHANGELOG.md")
>   File "/usr/src/supervisor/supervisor/addons/model.py", line 549, in path_location
>     return Path(self.data[ATTR_LOCATON])
>   File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
>     return self.sys_store.data.addons[self.slug]
> KeyError: '5c53de3b_esphome'
> 23-05-08 20:35:06 INFO (MainThread) [supervisor.store] Loading add-ons from store: 92 all - 0 new - 0 remove
> 23-05-08 20:35:06 INFO (MainThread) [supervisor.store] Loading add-ons from store: 92 all - 0 new - 0 remove
> 23-05-08 20:37:00 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token

**Comment by Biscotte31** [comment]
Hello Guys,
Same here, being.under HA OS 2023.05.4

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:916
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 04:16:52 (5 occurrences)
Last logged: 04:16:52

Could not fetch changelog for db21ed7f_nextcloud_ocr:
Could not fetch changelog for 45df7312_zigbee2mqtt:
Could not fetch changelog for db21ed7f_plex_nas:
Could not fetch changelog for db21ed7f_transmission_openvpn:
Could not fetch changelog for db21ed7f_jackett_nas:

If you have any clues I'm interested :) !
