### ISSUE TITLE
Problems using backup/restore on Raspberry Pi 3/4

### ISSUE THREAD

**Issue by Krotu** [home-assistant/supervisor#4293]
### Describe the issue you are experiencing

Whilst I have resolved this problem, one of the discord moderators said I should post the issues I had here.

The issue was likely exasperated by my database having grown to 10GB combined with using a raspberry pi 3.

The first issue is that the interface for making backups gives an error saying it has failed and to check the supervisor log after around 30 minutes. The supervisor log did not contain any information to suggest the backup had failed, only that it had started processing the home assist config folder. I was told this error was actually because my browser had timed out, I think the error could do with reflecting this information.

These backups never appeared later either though, maybe they were taking so long that the pi3 was being restarted before they finished? There is no progress indicator as far as I can tell.

I suspected the weak cpu in the pi3 might be struggling with compressing the 10GB backup and was told that compression could be turned off if the backup is ran from the developer section instead. I also ran iostat through a terminal addon to see if I could tell what was happening regarding the backup.

before any backup was run there was very little drive activity through iostat.
without compression the backup was running at around 5MB/s alternating between reading and writing(I guess the sd card write speed might be a bottleneck here).
I ran the same test using the normal backup options and I was only getting 0.5-1MB/s (this is with compression back on)
It's no wonder the backups were never appeared if its been trying to do 10GB at ~1MB/s.
Maybe the normal backup window needs the compression option with the suggestion to disable it for slower hardware.

Separate to this issue, the restore on the pi4 was unreliable too. I was able to transfer the 10GB tar file to the pi4, but the pre-onboarding restore would fail instantly after the transfer and would put the home assistant install into safe mode. Going through the onboarding and then trying to restore would cause the same issue. I am using a usb ssd if this makes any difference on how the restore would work.

I am not sure of the terminology for it, but connecting a screen/keyboard/mouse to the pi4 and running the restore through the terminal interface ("ha backup restore <slug>") worked and took about 20 minutes.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Have large dataset on slow hardware
2. Try to run a backup
3. Try to restore if you manage to get a large backup

### Anything in the Supervisor logs that might be useful for us?

```txt
for the backup, no errors since it was working but extremely slowly.
```

### System Health information

There are currently no repairs available

### Additional information

sd card in the pi3 is a new 128GB high endurance card, it had about 20gb saved to it so space was never an issue.

I still have the pi3 with the sd card intact from initiating the backup available if needed for more testing, but the pi4 is now working so unfortunately I do not have diagnostic information available for why the first 2 restore attempts were failing.

**Comment by jires** [comment]
I have exactly same issue on my RPi 4 installation.
Home Assistant 2023.5.4
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230503.3
