### ISSUE TITLE
Leave beta channel is not working anymore in 2023.6.0b1

### ISSUE THREAD

**Issue by smarthomejunkie** [home-assistant/supervisor#4331]
### Describe the issue you are experiencing

If you click the link to leave the beat channel, a supervisor error is shown

![image](https://github.com/home-assistant/supervisor/assets/67226335/7552dd49-0653-4c7c-8b29-07c4d67a1bc0)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Go to Settings
2. Go to System
3. Go to Updates
4. Click the three dots
5. Click Leave beta channel
6. This error is shown:

![image](https://github.com/home-assistant/supervisor/assets/67226335/15b42244-45d6-4102-8db8-cbe41bf0ff87)

7. Refresh the browser
8. You still left the beta channel

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-01 12:02:18 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/aiohttp.py", line 126, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/aiohttp.py", line 116, in sentry_app_handle
    response = await old_handle(self, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

## System Information

version | core-2023.6.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.3
os_name | Linux
os_version | 6.1.29
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4386
Installed Version | 1.32.1
Stage | running
Available Repositories | 1354
Downloaded Repositories | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 1, 2018 at 1:00 AM
relayer_connected | false
relayer_region | null
remote_enabled | true
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | null
certificate_status | null
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.05.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 113.9 GB
disk_used | 29.6 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.13.0), NGINX Home Assistant SSL proxy (3.5.0), Advanced SSH & Web Terminal (15.0.2), TasmoAdmin (0.24.4), Duck DNS (1.15.0), Grafana (8.3.0), InfluxDB (4.7.0), MariaDB (2.6.1), AdGuard Home (4.8.7), Portainer (2.0.0), Samba share (10.0.2), Glances (0.19.2), Dutch gas prices (2023.4.26.1), Mosquitto broker (6.2.1), Zigbee2MQTT (1.31.0-1), Zigbee2MQTT Edge (edge), Matter Server (4.5.1), Home Assistant Google Drive Backup (0.110.4), ESPHome (2023.5.5), File editor (5.6.0), Studio Code Server (5.6.1), Whisper (0.2.0), Piper (0.1.3), go2rtc (1.5.0), RTSPtoWeb - WebRTC (1.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 12
-- | --
resources | 29
views | 89
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 18, 2023 at 9:46 AM
-- | --
current_recorder_run | June 1, 2023 at 11:55 AM
estimated_db_size | 1112.62 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by mdegat01** [comment]
Ah. Looks like I missed an `asyncio.wait` call.

Yes you still left the beta channel. The UI actually makes two API calls to supervisor when you do that:
1. Leave the beta channel - this works without issue (same as doing `ha supervisor options --channel stable` in the CLI if you want to confirm)
2. Reload supervisor - this is what is breaking (same as doing `ha supervisor reload` in the CLI)

Put up a PR to fix the reload API.
