### ISSUE TITLE
[asyncio] Task exception was never retrieved future

### ISSUE THREAD

**Issue by tjorim** [home-assistant/supervisor#4337]
### Describe the issue you are experiencing

Getting some errors in the log.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Update supervisor and core to beta release?

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-02 12:30:19 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-25516' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 160, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
23-06-02 12:30:19 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Set of Tasks/Futures is empty.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
23-06-02 12:45:19 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-26730' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 160, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
23-06-02 12:45:19 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Set of Tasks/Futures is empty.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
```

## System Information

version | core-2023.6.0b2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.3
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1290
Downloaded Repositories | 58
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 26 April 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-7.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | beta
supervisor_version | supervisor-2023.06.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 458.4 GB
disk_used | 41.7 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | AirCast (3.5.3), Spotify Connect (0.12.4), Advanced SSH & Web Terminal (15.0.2), File editor (5.6.0), Studio Code Server (5.6.1), Zigbee2MQTT (1.31.0-1), Home Assistant Google Drive Backup (0.110.4), MariaDB (2.6.1), phpMyAdmin (0.8.6), The Lounge (0.18.0), Glances (0.19.2), Tailscale (0.11.1), ZeroTier One (0.16.3), Nginx Proxy Manager (0.12.3), Uptime Kuma (0.7.4), WireGuard (0.8.1), ESPHome (2023.5.5), Music Assistant BETA (2.0.0b32), Mosquitto broker (6.2.1), eBUSd (23.2.0), ankerctl (1.0.0-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 30
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 June 2022 at 07:18
-- | --
current_recorder_run | 2 June 2023 at 07:29
estimated_db_size | 7478.83 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Supervisor diagnostics

[config_entry-hassio-2eee5c74cb50bb97439a172678bc4817.json.txt](https://github.com/home-assistant/supervisor/files/11634588/config_entry-hassio-2eee5c74cb50bb97439a172678bc4817.json.txt)

**Comment by koemat** [comment]
Hi

I have the same errors in the supervisor log.
I run HA supervised on a x86_64 machine with Debian bullseye.

**Comment by johntdyer** [comment]
I think im getting the same error but on 2023.05.04 w/ supervisor 2023.06

sorry for the screenshot, not sure how to export logs in loki yet

<img width="1710" alt="image" src="https://github.com/home-assistant/supervisor/assets/58234/60cac920-cd1b-4b70-bf9c-9d460c0c57ea">

```
