### ISSUE TITLE
Password protected Backups not possible - OpenSSL 3.0's legacy provider failed to load

### ISSUE THREAD

**Issue by thatslolo** [home-assistant/supervisor#4339]
### Describe the issue you are experiencing

When triggering a backup (manual or via hassio google drive backup) I get the following error message:

`OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

start backup

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-04 23:21:59 INFO (MainThread) [supervisor.backups.manager] Found 31 backup files
23-06-04 23:21:59 INFO (MainThread) [supervisor.backups.manager] Found 31 backup files
23-06-04 23:22:11 ERROR (MainThread) [supervisor.jobs] Unhandled exception: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 234, in do_backup_full
    backup = self._create_backup(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 108, in _create_backup
    backup.new(slug, name, date_str, sys_type, password, compressed)
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 192, in new
    self._init_password(password)
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 212, in _init_password
    backend=default_backend(),
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/__init__.py", line 11, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 27, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 167, in <module>
    Binding.init_static_locks()
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 134, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 123, in _ensure_ffi_initialized
    _legacy_provider_error(cls._legacy_provider_loaded)
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _legacy_provider_error
    raise RuntimeError(
RuntimeError: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
23-06-04 23:22:16 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret pw_backups
```

## System Information

version | core-2023.6.0b4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.3
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4583
Installed Version | 1.32.1
Stage | running
Available Repositories | 1293
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | beta
supervisor_version | supervisor-2023.06.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 458.4 GB
disk_used | 32.5 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | AirCast (3.5.3), ESPHome (2023.5.5), Grafana (8.3.0), ICantBelieveItsNotValetudo (4.0.0), InfluxDB (4.7.0), Log Viewer (0.15.1), Mosquitto broker (6.2.1), Studio Code Server (5.6.1), Zigbee2MQTT (1.31.0-1), phpMyAdmin (0.8.6), MariaDB (2.6.1), Terminal & SSH (9.7.1), OpenThread Border Router (2.0.0), Matter Server (4.5.1), Samba share (10.0.2), Home Assistant Google Drive Backup (0.110.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 13
views | 8
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 0.1.13
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 May 2023 at 12:10
-- | --
current_recorder_run | 4 June 2023 at 23:19
estimated_db_size | 2082.27 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Supervisor diagnostics

[config_entry-hassio-f796edc0fe39a410c08014f4ae248f82.json-2.txt](https://github.com/home-assistant/supervisor/files/11646704/config_entry-hassio-f796edc0fe39a410c08014f4ae248f82.json-2.txt)

**Comment by thatslolo** [comment]
The issue seems to be the password protection. When creating a backup without pw it works.

**Comment by sli-cka** [comment]
Same issue here (running 2023.6.0b4)

Backup with password -> fails
Backup without password -> works
