### ISSUE TITLE
addon container capabilities problems

### ISSUE THREAD

**Issue by lfarkas** [home-assistant/supervisor#4343]
### Describe the issue you are experiencing

in the addon configuration the [docs](https://developers.home-assistant.io/docs/add-ons/configuration) said:
```
privileged	list		
Privilege for access to hardware/system. Available access: BPF, DAC_READ_SEARCH, IPC_LOCK, NET_ADMIN, NET_RAW, PERFMON, SYS_ADMIN, SYS_MODULE, SYS_NICE, SYS_PTRACE, SYS_RAWIO, SYS_RESOURCE or SYS_TIME.
```
while in my uptodate supervisor i see this in the log:
```
23-06-06 14:13:09 WARNING (SyncWorker_4) [supervisor.store.data] Can't read /data/addons/git/a3656363/netbird/config.yaml: expected Capabilities or one of 'DAC_READ_SEARCH', 'IPC_LOCK', 'NET_ADMIN', 'NET_RAW', 'SYS_ADMIN', 'SYS_MODULE', 'SYS_NICE', 'SYS_PTRACE', 'SYS_RAWIO', 'SYS_RESOURCE', 'SYS_TIME' @ data['privileged'][2]. Got 'BPF'
```
so it seems docs list:
- BPF
- PERFMON

but addon config do not except this while these docker capabilities are valid ones. so which is the valid the docs or what is the supervisor said?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. any addon with Privilege BPF
2. eve try to add the addon
3. can't find the addon
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-06 14:13:09 WARNING (SyncWorker_4) [supervisor.store.data] Can't read /data/addons/git/a3656363/netbird/config.yaml: expected Capabilities or one of 'DAC_READ_SEARCH', 'IPC_LOCK', 'NET_ADMIN', 'NET_RAW', 'SYS_ADMIN', 'SYS_MODULE', 'SYS_NICE', 'SYS_PTRACE', 'SYS_RAWIO', 'SYS_RESOURCE', 'SYS_TIME' @ data['privileged'][2]. Got 'BPF'
```

### System Health information

Jelenleg nincs szükség javításokra

### Additional information

https://github.com/home-assistant/home-assistant.io/issues/27666

**Comment by mdegat01** [comment]
Please share your [system health information](https://my.home-assistant.io/redirect/system_health/) as per the instructions in the issue template. Just click the click the link and then click the copy button in the pop-up that opens and paste in here.

I'm not entirely sure how to explain what you're seeing. I just went on my dev system and made a dummy addon with this in its config:
```yaml
privileged:
  - DAC_READ_SEARCH
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_NICE
  - SYS_PTRACE
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_TIME
  - BPF
  - PERFMON
```
It seems to have worked without issue. Then I added `JUNK` as a privilege at the bottom to test and got this in my log:
```
23-06-06 12:19:36 WARNING (SyncWorker_8) [supervisor.store.data] Can't read /data/addons/local/example/config.yaml: expected Capabilities or one of 'BPF', 'DAC_READ_SEARCH', 'IPC_LOCK', 'NET_ADMIN', 'NET_RAW', 'PERFMON', 'SYS_ADMIN', 'SYS_MODULE', 'SYS_NICE', 'SYS_PTRACE', 'SYS_RAWIO', 'SYS_RESOURCE', 'SYS_TIME' @ data['privileged'][13]. Got 'JUNK'
```
That log matches what you shared and like you my addon stopped appearing in the list after that.

So it seems to be working correctly in the latest dev builds. And nothing has changed here recently. I'll need a bit more info. Lets start with system health info and can you also share the details of your addon? So I can try with exactly the same config.

**Comment by mdegat01** [comment]
Ah nvm, I see what happened. There was a change in this space, `BPF` and `PERFMON` were introduced only two weeks ago in https://github.com/home-assistant/supervisor/pull/4259 . There has not been a stable release of supervisor since then so they currently only work on the latest beta and dev versions of supervisor, not stable.

There will be a new stable release of supervisor out shortly. This issue will be resolved after that version is released.
