### ISSUE TITLE
Network Storage Unsupported on Supervised Debian Install

### ISSUE THREAD

**Issue by gtxaspec** [home-assistant/supervisor#4347]
### Describe the issue you are experiencing

![image](https://github.com/home-assistant/supervisor/assets/12115272/22790dc0-6209-4476-a233-e7986dcb577b)

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

Boot the system, and error message is displayed.

### Anything in the Supervisor logs that might be useful for us?

```txt
n/a
```

### System Health information

n/a

### Additional information

What are the requirements for the host to support network storage? the kernel supports CIFS and NFS via the command line.  Mounting shares works manually

**Comment by frenck** [comment]
This cause is most likely a missing bind propagation on the Supervisor data folder. Please add it, or consider running the latest supervised installer again.

Closing the issue on this end, as it is a configuration issue on OS out of our control.

../Frenck
