### ISSUE TITLE
Network Share password starting with "," and/or containing "[" or "]" are not accepted

### ISSUE THREAD

**Issue by Vato9394** [home-assistant/supervisor#4352]
### Describe the issue you are experiencing

Passwords starting with "," and/or containing "[" or "]" are not accepted.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.create a samba user and give it a password starting with "," (Comma) and contain "[" or "]" somewhere.
2.try to add the samba share in home assistant
3.get following error: failed to to call /mounts - does not match regular expression ^[^,=]+$ for dictionary value @ data['password']. Got ',password'
...

### Anything in the Supervisor logs that might be useful for us?

```txt
failed to to call /mounts - does not match regular expression ^[^,=]+$ for dictionary value @ data['password']. Got ',pa[ssw]ord'
```

### System Health information

system is healty, There are currently no repairs available 

### Supervisor diagnostics

[config_entry-hassio-05c7dea0e236f17fe9b44daa4a29e849.json.txt](https://github.com/home-assistant/supervisor/files/11685066/config_entry-hassio-05c7dea0e236f17fe9b44daa4a29e849.json.txt)

**Comment by mdegat01** [comment]
It's actually just `,` and `=` that is restricted. `[` and `]` work fine.
