### ISSUE TITLE
http://supervisor/supervisor/info: dial tcp 172.30.32.2:80 connect: no route to host

### ISSUE THREAD

**Issue by homeautomaton** [home-assistant/supervisor#4354]
### Describe the issue you are experiencing

I was experiencing the "connect: no route to host" issue that has been described by others in some tickets that are closed as "unsupported," but in my case, I'm using a completely standard install. I downloaded the VM image years ago and have never had to re-install, stubbornly tracking down root causes when I hit an issue like this one.

```
http://supervisor/supervisor/info: dial tcp 172.30.32.2:80 connect: no route to host
```

In this case, the remedy was to run this in the console, BEFORE rebooting the host.

```
rm /mnt/data/docker/network/files/local-kv.db
```

So, in short, if the supervisor startup experiences the problem that showed up in the observer as
```
23-06-06 17:17:31 WARNING (SyncWorker_0) [supervisor.docker.network] Docker network is corrupt!
```
deleting the `local-kv.db` file would automate the recovery process.

If, at any point in the process, I attempted a `host reboot`, it resulted in a boot-loop, making it much harder to diagnose the root cause here. Fortunately, a recent VM snapshot contained the corrupt database, but HA was still up and running. This let me iterate on the problem for some long hours before I found a solution/work-around.

I know this is an issue with docker corrupting its own network db, not with home assistant itself, but it causes such a difficult to diagnose and remedy problem, automating a solution would be a big win. In my research I found other cases where people had to resort to reinstalling their entire Home Assistant system. There are probably many others that have experienced the problem without reporting it.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Run home assistant for years, without resorting to a complete re-install, so that DOCKER has a chance to soil itself.
2. Once DOCKER has corrupted its network database, observe the error trying to restart the supervisor.

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-06 22:17:31 INFO (MainThread) [__main__] Initializing Supervisor setup
23-06-06 17:17:31 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: qemux86-64
23-06-06 17:17:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-06-06 17:17:31 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor ghcr.io/home-assistant/amd64-hassio-supervisor with version 2023.06.1
23-06-06 17:17:31 WARNING (SyncWorker_0) [supervisor.docker.network] Docker network is corrupt! ep-bc6938d5209363befb3b105174af21ddd5f66732c9e5f2f70c3d373d75fd208c
23-06-06 17:17:31 INFO (SyncWorker_0) [supervisor.docker.supervisor] Connecting Supervisor to hassio-network
23-06-06 17:17:31 CRITICAL (MainThread) [supervisor.supervisor] Can't setup Supervisor Docker container!
23-06-06 17:17:31 INFO (SyncWorker_1) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/amd64-hassio-supervisor:2023.04.1']
23-06-06 17:17:33 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
23-06-06 17:17:33 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
```

## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.25
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1286
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 30.8 GB
disk_used | 16.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.1), Node-RED (14.1.5), File editor (5.6.0), Z-Wave JS (0.1.80), Advanced SSH & Web Terminal (14.1.0), Custom deps deployment (1.3.2), MariaDB (2.6.0), TasmoAdmin (0.24.1), Run On Startup.d (0.11a), Grocy (0.19.0), Terminal & SSH (9.7.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 21
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 9, 2023 at 11:55 AM
-- | --
current_recorder_run | June 7, 2023 at 6:47 PM
estimated_db_size | 2834.88 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

**Comment by cociweb** [comment]
in my unsupported installation somehow the network is reseted to bridge mode and left it's created network group. additionally you can force the requested ip for ipv4 address: 172.30.32.2. I cannot help to you in cli, because I resolved it via portainer.

**Comment by homeautomaton** [comment]
This still needs to be investigated.

**Comment by homeautomaton** [comment]
This still needs to be investigated.

**Comment by homeautomaton** [comment]
bump

**Comment by bartgrefte** [comment]
I'm running into this right know with an OVA-image, running in VMware Workstation.

I have a script that updates the SSL-certificates through SCP and then runs
 `source /etc/profile.d/homeassistant.sh ; ha core restart`

Worked fine until today, now I keep getting 
```
Welcome to the Home Assistant command line.

Waiting for Supervisor to startup...
System information
Get "http://supervisor/network/info": dial tcp 172.30.32.2:80: connect: no route to host
Processing... Done.

Post "http://supervisor/core/restart": dial tcp 172.30.32.2:80: connect: no route to host
Connection to 192.168.1.198 closed.

```
The web-interface is inaccessible and I can't seem to get past this error.

**Comment by agners** [comment]
This is unlikely a Supervisor issue. Check the virtual machine console and see what it is reporting (during startup etc). If this doesn't give a clue what is going wrong, you'd probably have to open an issue in the operating system repository at https://github.com/home-assistant/operating-system/.

**Comment by bartgrefte** [comment]
@agners So restarting the entire host, is that wise without knowing what's going on? I can still SSH in, so if a full restart results in the inability to boot...

**Comment by agners** [comment]
You SSH into using port 22 I assume? You only have limited visibility on what is going on in the system. Does `ha su logs` work? I assume it doesn't...

If you have local console access, you can login to the OS shell (using `login` command in the `ha >` prompt) and check things from there (e.g. using `docker ps` to check which containers are running).

**Comment by bartgrefte** [comment]
"You SSH into using port 22 I assume"
Different port, but yeah. Also have access to the system running VMware Workstation and the HASS VM where I can enter the commands directly.

"Does ha su logs work? "
First the message that leading "ha" is not necessary, followed by 
Get "http://supervisor/supervisor/logs": dial tcp 172.30.32.2:80: connect: no route to host.

"docker ps "
10 with status up 3 weeks, 1 with up 11 days and one up 30 seconds (hassio-observer).

While trying commands to restart parts of HA (instead of full host reboot) the invalid certificate error got replaced with an unable to connect (and 60s timer), now that hassio-observer is (re)started I tried the webinterface again and got the invalid certificate again, after having accepted the warning I can access the webinterface and see the logs there:

```
 Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:556
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 26 oktober 2023 21:40:48 (3298 occurrences)
Last logged: 10:14:51
Can't read Supervisor data: 
```

```

 Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:587
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 26 oktober 2023 21:40:00 (39570 occurrences)
Last logged: 10:09:48

    Client error on /host/info request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
    Client error on /store request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
    Client error on /core/info request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
    Client error on /supervisor/info request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
    Client error on /os/info request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]

```

Then some Telegram related errors, api.telegram.org has always been a pain in the ass, partly due to IPv6-related MTU issues.


Going a little further back, not sure if related:
```
 Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:268
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16 oktober 2023 15:23:58 (9 occurrences)
Last logged: 27 oktober 2023 20:14:14

    [139690435127360] Error handling message: Entity ID unmonitored is an invalid entity ID for dictionary value @ data['entity_id']. Got 'unmonitored' (invalid_format) Bart Grefte from 192.168.2.10 (Mozilla/5.0 (Linux; Android 13; SM-G781B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36 Home Assistant/2023.10.2-11484 (Android 13; SM-G781B))
    [139690493590208] Error handling message: Entity ID unmonitored is an invalid entity ID for dictionary value @ data['entity_id']. Got 'unmonitored' (invalid_format) Bart Grefte from 192.168.2.10 (Mozilla/5.0 (Linux; Android 13; SM-G781B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36 Home Assistant/2023.10.2-11484 (Android 13; SM-G781B))
    [139690450688832] Error handling message: Entity ID unmonitored is an invalid entity ID for dictionary value @ data['entity_id']. Got 'unmonitored' (invalid_format) Bart Grefte from 192.168.2.10 (Mozilla/5.0 (Linux; Android 13; SM-G781B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36 Home Assistant/2023.10.2-11484 (Android 13; SM-G781B))
    [139690491154368] Error handling message: Entity ID unmonitored is an invalid entity ID for dictionary value @ data['entity_id']. Got 'unmonitored' (invalid_format) Bart Grefte from 192.168.2.10 (Mozilla/5.0 (Linux; Android 13; SM-G781B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36 Home Assistant/2023.10.2-11484 (Android 13; SM-G781B))
    [139690491493440] Error handling message: Entity ID unmonitored is an invalid entity ID for dictionary value @ data['entity_id']. Got 'unmonitored' (invalid_format) Bart Grefte from 192.168.2.10 (Mozilla/5.0 (Linux; Android 13; SM-G781B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36 Home Assistant/2023.10.2-11484 (Android 13; SM-G781B))

```

```
Logger: homeassistant.components.version
Source: helpers/update_coordinator.py:322
Integration: Versie (documentation, issues)
First occurred: 24 oktober 2023 01:53:57 (2 occurrences)
Last logged: 27 oktober 2023 19:59:37
Error fetching version data: Timeout of 10 seconds was reached while fetching version for supervisor 
```

```
 Logger: homeassistant.components.hassio
Source: helpers/update_coordinator.py:322
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 26 oktober 2023 21:40:00 (1 occurrences)
Last logged: 26 oktober 2023 21:40:00
Error fetching hassio data: Error on Supervisor API: 
```

```
 Logger: homeassistant.components.hassio.issues
Source: components/hassio/issues.py:310
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 26 oktober 2023 21:39:26 (2 occurrences)
Last logged: 26 oktober 2023 21:39:27
Failed to update supervisor issues: HassioAPIError()

```

```
 Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:584
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 26 oktober 2023 21:39:26 (2 occurrences)
Last logged: 26 oktober 2023 21:39:27
Timeout on /resolution/info request
```

**Comment by agners** [comment]
Hm, interesting, it seems the Supervisor is busy restarting the observer for whatever reason and there is some Internet connectivity problem :thinking: 

Could it be that you have some type of IP address conflict? E.g. is maybe your network's IP address range conflicting with the one from Home Assistant?

Can you check `ip addr` to see if the hassio network is there?

**Comment by bartgrefte** [comment]
@agners At the same time you posted that reply, I added another edit:
docker restart hassio_supervisor solved it

**Comment by agners** [comment]
Yeah I saw it. Glad that this solved the issue. Interesting would be what type of state the system got itself into here, and why. I suspect that something was wrong with the internal `hassio` network.

**Comment by bartgrefte** [comment]
@agners All I know at this point is that the supervisor-docker was (re)started 11 days ago and if I recall correctly, that might be when I last installed updates: Supervisor 2023.10.1 and OS 11.0 to be precise.
