### ISSUE TITLE
VLC report : main decoder error: failed to create audio output

### ISSUE THREAD

**Issue by thanasiskalos** [home-assistant/supervisor#4355]
### Describe the issue you are experiencing

Hello

I opened the https://github.com/home-assistant/core/issues/94154 issue on Home assistant core , but seems that the bug is related to Home Assistant supervisor 2023.6.1

Please check the details on the issue 94154 as a seems that the issue is affecting a large number of users.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. play any media on Home assistant  with VLC Integration
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
[00007f9d5205fd50] main audio output error: module not functional
[00007f9d4cb67c90] main decoder error: failed to create audio output
[00007f9d5205fd50] vlcpulse audio output error: stream connection failure: No such entity
[00007f9d5205fd50] main audio output error: module not functional
[00007f9d4cb67c90] main decoder error: failed to create audio output
[00007f9d5205fd50] vlcpulse audio output error: stream connection failure: No such entity
[00007f9d5205fd50] main audio output error: module not functional
[00007f9d4cb67c90] main decoder error: failed to create audio output
[00007f9d5205fd50] vlcpulse audio output error: stream connection failure: No such entity
[00007f9d5205fd50] main audio output error: module not functional
```

### System Health information

System Information version | core-2023.5.4 -- | -- installation_type | Home Assistant OS dev | false hassio | true docker | true user | root virtualenv | false python_version | 3.10.11 os_name | Linux os_version | 6.1.29 arch | x86_64 timezone | Europe/Athens config_dir | /config
Home Assistant Community Store
Home Assistant Cloud
Home Assistant Supervisor
Dashboards
Recorder

**Comment by DieMetRik** [comment]
I have the same issue after install 2023.6

Installation:
Home Assistant 2023.6.0
Supervisor 2023.06.1

VLC
Current version: 0.2.0
Log:
```
vlcpulse audio output error: stream connection failure: No such entity
main audio output error: module not functional
main decoder error: failed to create audio output
```

Host: Debian VM + Proxmox
Installed: [pulseaudio fix](https://github.com/OPHoperHPO/hassio-addons/tree/master/pulseaudio_fix)

**Comment by DieMetRik** [comment]
I have the same issue after install 2023.6

Installation:
Home Assistant 2023.6.0
Supervisor 2023.06.1

VLC
Current version: 0.2.0
Log:
```
vlcpulse audio output error: stream connection failure: No such entity
main audio output error: module not functional
main decoder error: failed to create audio output
```

Host: Debian VM + Proxmox
Installed: [pulseaudio fix](https://github.com/OPHoperHPO/hassio-addons/tree/master/pulseaudio_fix)

**Comment by ktownsend-personal** [comment]
I'm having the same issue with MPD after installing Home Assistant 2023.6.1, so not just VLC affected.

**Comment by riddicc** [comment]
mplayer is not affected... and vlc plays about 50% of my TV recordings fine... but when vlc plays the others, there is this loud noise and it messes up power save settings (e. g.: i cannot turn off the mouse)...

**Comment by mib1185** [comment]
seems to be related to/caused by https://github.com/home-assistant/plugin-audio/issues/129
