### ISSUE TITLE
Network storage cannot be mounted at /data/mounts/<name> because it is not empty

### ISSUE THREAD

**Issue by Laho812** [home-assistant/supervisor#4358]
### The problem

Cannot mount HomeNAS_Backup at /data/mounts/HomeNAS_Backup because it is not empty.
This error message is not accurate because it can either be the mount point or the remote share. 
Due to the fact the remote share is empty, the mount point is meant. 
So: HomeAssistant keeps some data inside the mount point after deleting the network storage connection and there is no easy way to clear it by yourself. 

![grafik](https://github.com/home-assistant/core/assets/119891233/826ee0be-42a1-4a49-a27d-a7bf98ea4cc4)
![grafik](https://github.com/home-assistant/core/assets/119891233/7346493d-c467-4d1d-8fe2-251f8bd9dcc1)

To reproduce:
1. Connect a network storage
2. Select the network storage as a default backup path (Settings -> System -> Backup -> 3 dots -> select network storage)
3. Do a full backup
4. Delete the network storage connection
5. Try to connect the network storage using the same Name

### What version of Home Assistant Core has the issue?

2023.06

### What type of installation are you running?

Home Assistant OS

**Comment by JTP335d** [comment]
This worked for me by not creating the (named)folder on my NAS. "homeassistant" is the folder on my NAS. It did not create a new folder inside it call "backup", but files are created there when I do a backup. Not sure if that helps.


name: backup
server: ip.add.re.ss
remote share: homeassistant

**Comment by bendestras** [comment]
identical problem with server off

**Comment by wojo** [comment]
Also running into this after a network issue caused me to remove and add back in a CIFS mount with the same name as prior "Backups".

On the filesystem I don't see that folder it is trying to mount into. Not sure how to move forward to clean up what is left behind.

**Comment by Mouseskowitz** [comment]
I'm having the same issue with an NFS share. It says it's mounted, but I can't actually write a backup file to it. The backup fails silently, which is a huge issue. I made several changes with the backup box checked thinking I had backups, but I didn't. Good thing nothing broke. While I really appreciate the effort of adding an external backup option, this implementation seems dangerous since there is no check to see if the backup was actually made.

**Comment by asayler** [comment]
I encountered this same issue after my file server crashed, bringing down the backup samba share with it. It appears HA will silently write backups to the mount location even when nothing is mounted. To clean it up, I had to connect to the host system console (I have an HA Yellow, so I followed the serial console debugging directions at https://yellow.home-assistant.io/documentation/). It appears these mount points aren't exposed to the docker container that runs the terminal app, so connecting to the host system directly was the only way to access them. Once connected, I ran the following to move the misplaced backups to the local backup location and then reboot the host to allow it to cleanly remount the drive:

```
# mv /mnt/data/supervisor/mounts/<backup mount name>/*.tar /mnt/data/supervisor/backup/
# ha host reboot
```

So it seems like a few things need fixed here:
- HA needs logic to prevent writing backups to the network mount point when nothing is mounted (and this should raise an error to prevent silently failed backups).
- HA needs a simpler way to clean up a bad mount point in the case something like this occurs anyway.

**Comment by CAHutchins** [comment]
I'm having the same problem.  I'm not able to locate the mount point /data/mounts/backup anywhere.
I suspect that after a power outage, the backup ran without the network folder mounted and wrote a file to the folder.
Now I can't find that folder to delete the file.

**Comment by asayler** [comment]
@CAHutchins what kind of HA setup are you running? If you're using HAOS, you need the access the mount point from the underlying host itself at the path in my previous post.

**Comment by CAHutchins** [comment]
I'm running on a Raspberry Pi. I just found the command a few minutes ago to access the supervisor file system.
"docker exec -it $(docker ps -f name=supervisor -q) bash"
Once there, the path /data/mounts/ is correct and I was able to empty the backup folder as well as clean up some other folders that weren't used anymore.

**Comment by dedors** [comment]
> @asayler , I'm running on a Raspberry Pi. I just found the command a few minutes ago to access the supervisor file system. "docker exec -it $(docker ps -f name=supervisor -q) bash" Once there, the path /data/mounts/ is correct and there was a .tar file in there. I was able to empty the backup folder as well as clean up some other folders that weren't used anymore.
> 
> As you mentioned above, HA needs to prevent writing if the network path is not mounted. Would it help to set the mountpoint folder to read-only?

Thanks, this solved my issue (for now)

**Comment by Rodney-Smith** [comment]
I am experiencing the same issue on HAOS 10.4, Core 2023.8.1, Supervisor 2023.07.1 after a power outage. I can't get to the /data/mounts folder to troubleshoot further.

**Comment by Mouseskowitz** [comment]
@Rodney-Smith I never figure out how to get to the mount point, but a workaround I found is to remove the external storage and re add it. Same idea as adding it under a new name,  but then you don't have a stack of broken stuff.

**Comment by MattCheetham** [comment]
Having the same issue. HomeAssistant says my drive has failed to connect, if you press reload it says the issue is fixed, but then shortly throws the error again. Attempting to press reload throws the error mentioned above. Was working fine previously.

**Comment by VinzNL** [comment]
Same issue here. A combination of the Advanced SSH & Web Terminal Add-on running unprotected and the docker exec command above to get into the supervisor container allowed me to remove the offending back-ups by hand. Obviously it's easy to destroy stuff this way if you're not absolutely sure what you're doing, so proceed with caution.

**Comment by bart1970** [comment]
For me, this problem started with one of the  2023.8.x releases. Not sure which one.

**Comment by chriszuercher** [comment]
I face the same issue because my NAS was offline during backup and the file seems like to be written to the folder anyways. Is there no way on unmounting and deleting the folder on HAOS?

**Comment by adrianoamalfi** [comment]
same issue

**Comment by sigalou** [comment]
Même probleme

**Comment by davidmankin** [comment]
And while we're talking about this, the error message could be more clear.  It was really confusing whether it is the mount point that is not empty or the samba share that is not empty.  The discussion here makes it clear it's the mount point that's not empty, but I almost tried creating a new samba share on my NAS to fix it.

**Comment by Instigater** [comment]
Issue manifested also for me. I mount my Windows workstation to do backups. Workstations isn't permanently running therefore backup location isn't always available. Normally it can remount OK but today I got this dreaded "not empty" error! Please make backup location auto-retry mounting and also give us ability at least to clean up. System yellow - no sane procedure is available to cleanup manually.

**Comment by Dieter-GitHub** [comment]
Have the same problem using NFS and Synology as backup utility ...

**Comment by Laho812** [comment]
> And while we're talking about this, the error message could be more clear.  It was really confusing whether it is the mount point that is not empty or the samba share that is not empty.  The discussion here makes it clear it's the mount point that's not empty, but I almost tried creating a new samba share on my NAS to fix it.

Yeah, that's true. Using a different samba share but giving it the same "Name" (which will be the mount point) causes the error message.

**Comment by AoSpades** [comment]
Any news yet? I have this problem too.

**Comment by derkrasseleo** [comment]
Same problem here with Samba Backup to Synology Diskstation

**Comment by derkrasseleo** [comment]
I think I fixed it by removing the mount, and adding it back with another name

**Comment by Haraldvdh** [comment]
I have it working again, after having the same issue, 
- stop frigate addon, 
- deselect start addon on startup
- remove the network share
- REMOVE ALL FILES AND FOLDERS in the share
- go to your homeassistant device, got to media, DELETE the frigate folder!
- reboot entire system
- add network share 
- delete frigate db in homeassistant \config folder
- start frigate
- optional : delect start on startup 

Please comment if this worked for you.

**Comment by dbensmith** [comment]
> I encountered this same issue after my file server crashed, bringing down the backup samba share with it. It appears HA will silently write backups to the mount location even when nothing is mounted. To clean it up, I had to connect to the host system console (I have an HA Yellow, so I followed the serial console debugging directions at https://yellow.home-assistant.io/documentation/). It appears these mount points aren't exposed to the docker container that runs the terminal add-on, so connecting to the host system directly was the only way to access them. Once connected, I ran the following to move the misplaced backups to the local backup location and then reboot the host to allow it to cleanly remount the drive:
> 
> ```
> # mv /mnt/data/supervisor/mounts/<backup mount name>/*.tar /mnt/data/supervisor/backup/
> # ha host reboot
> ```
> 
> So it seems like a few things need fixed here:
> 
> * HA needs logic to prevent writing backups to the network mount point when nothing is mounted (and this should raise an error to prevent silently failed backups).
> * HA needs a simpler way to clean up a bad mount point in the case something like this occurs anyway.

Thanks for this, it's the proper workaround. Renaming mounts and re-adding doesn't clean up any previous mess.

**Comment by Laho812** [comment]
> I encountered this same issue after my file server crashed, bringing down the backup samba share with it. It appears HA will silently write backups to the mount location even when nothing is mounted. To clean it up, I had to connect to the host system console (I have an HA Yellow, so I followed the serial console debugging directions at https://yellow.home-assistant.io/documentation/). It appears these mount points aren't exposed to the docker container that runs the terminal add-on, so connecting to the host system directly was the only way to access them. Once connected, I ran the following to move the misplaced backups to the local backup location and then reboot the host to allow it to cleanly remount the drive:
> 
> ```
> # mv /mnt/data/supervisor/mounts/<backup mount name>/*.tar /mnt/data/supervisor/backup/
> # ha host reboot
> ```
> 
> So it seems like a few things need fixed here:
> - HA needs logic to prevent writing backups to the network mount point when nothing is mounted (and this should raise an error to prevent silently failed backups).
> - HA needs a simpler way to clean up a bad mount point in the case something like this occurs anyway.

It seems I missed that comment... Anyway. 
Thanks for finding the mount path and your workaround with moving the content to an accessible location. It's the same thing I observed. Mount points should be cleaned/moved to an accessible mount point after unmounting the remote storage. And, oc course, an error message should occur after a backup to the local mount path.

**Comment by msl2424** [comment]
> I encountered this same issue after my file server crashed, bringing down the backup samba share with it. It appears HA will silently write backups to the mount location even when nothing is mounted. To clean it up, I had to connect to the host system console (I have an HA Yellow, so I followed the serial console debugging directions at https://yellow.home-assistant.io/documentation/). It appears these mount points aren't exposed to the docker container that runs the terminal add-on, so connecting to the host system directly was the only way to access them. Once connected, I ran the following to move the misplaced backups to the local backup location and then reboot the host to allow it to cleanly remount the drive:
> 
> ```
> # mv /mnt/data/supervisor/mounts/<backup mount name>/*.tar /mnt/data/supervisor/backup/
> # ha host reboot
> ```
> 
> So it seems like a few things need fixed here:
> 
> * HA needs logic to prevent writing backups to the network mount point when nothing is mounted (and this should raise an error to prevent silently failed backups).
> * HA needs a simpler way to clean up a bad mount point in the case something like this occurs anyway.

For those of us running Raspberry Pi 4, do you know the steps we must take? For example, do we connect the Raspberry Pi directly to our laptop via USB? If so, what interface do we use to run the command that you suggested?

**Comment by derkrasseleo** [comment]
> > I encountered this same issue after my file server crashed, bringing down the backup samba share with it. It appears HA will silently write backups to the mount location even when nothing is mounted. To clean it up, I had to connect to the host system console (I have an HA Yellow, so I followed the serial console debugging directions at https://yellow.home-assistant.io/documentation/). It appears these mount points aren't exposed to the docker container that runs the terminal add-on, so connecting to the host system directly was the only way to access them. Once connected, I ran the following to move the misplaced backups to the local backup location and then reboot the host to allow it to cleanly remount the drive:
> > ```
> > # mv /mnt/data/supervisor/mounts/<backup mount name>/*.tar /mnt/data/supervisor/backup/
> > # ha host reboot
> > ```
> > 
> > 
> > So it seems like a few things need fixed here:
> > 
> > * HA needs logic to prevent writing backups to the network mount point when nothing is mounted (and this should raise an error to prevent silently failed backups).
> > * HA needs a simpler way to clean up a bad mount point in the case something like this occurs anyway.
> 
> For those of us running Raspberry Pi 4, do you know the steps we must take? For example, do we connect the Raspberry Pi directly to our laptop via USB? If so, what interface do we use to run the command that you suggested?

There's a addon called "Terminal & SSH", install it and then you can just run the commands in Web UI.

**Comment by msl2424** [comment]
> # ha host reboot

I've tried running the commands using Advanced SSH & Web Terminal with Protection Mode disabled and nothing happens, but the instructions from @asayler suggest you need to connect to the console or system directly. Unfamiliar with the steps to do this correctly, and I don't have a Yellow. I realize this may be intuitive to others.

**Comment by msl2424** [comment]
> > > I encountered this same issue after my file server crashed, bringing down the backup samba share with it. It appears HA will silently write backups to the mount location even when nothing is mounted. To clean it up, I had to connect to the host system console (I have an HA Yellow, so I followed the serial console debugging directions at https://yellow.home-assistant.io/documentation/). It appears these mount points aren't exposed to the docker container that runs the terminal add-on, so connecting to the host system directly was the only way to access them. Once connected, I ran the following to move the misplaced backups to the local backup location and then reboot the host to allow it to cleanly remount the drive:
> > > ```
> > > # mv /mnt/data/supervisor/mounts/<backup mount name>/*.tar /mnt/data/supervisor/backup/
> > > # ha host reboot
> > > ```
> > > 
> > > 
> > > So it seems like a few things need fixed here:
> > > 
> > > * HA needs logic to prevent writing backups to the network mount point when nothing is mounted (and this should raise an error to prevent silently failed backups).
> > > * HA needs a simpler way to clean up a bad mount point in the case something like this occurs anyway.
> > 
> > 
> > For those of us running Raspberry Pi 4, do you know the steps we must take? For example, do we connect the Raspberry Pi directly to our laptop via USB? If so, what interface do we use to run the command that you suggested?
> 
> There's a addon called "Terminal & SSH", install it and then you can just run the commands in Web UI.

I've tried running the commands using Advanced SSH & Web Terminal with Protection Mode disabled and nothing happens, but the instructions from @asayler suggest you need to connect to the console or system directly. Unfamiliar with the steps to do this correctly, and I don't have a Yellow. I realize this may be intuitive to others.

**Comment by Destarianon** [comment]
Same issue on my end as well. Had a NAS go down during a power outage and my HAOS install created a backup overnight into the disconnected mount dir that I cannot cleanup. Terminal via the Web UI does not have access to these mounts, so I am unsure how I would go about cleaning it.

**Comment by derkrasseleo** [comment]
> Same issue on my end as well. Had a NAS go down during a power outage and my HAOS install created a backup overnight into the disconnected mount dir that I cannot cleanup. Terminal via the Web UI does not have access to these mounts, so I am unsure how I would go about cleaning it.

I think I had the exact same case with NAS + Power outage, but in my case, removing the network storage in the settings and adding it with a different name fixed it.

**Comment by jmealo** [comment]
It looks like the check for this is pretty simple:
```
if ! df -h | grep -q '/your/mount/point'; then
    echo "Network mount is down or disconnected."
else
    echo "Network mount is connected."
fi
```

I guess the question is how error handling should work and whether the configuration should expose an alternative location.. and whether Home Assistant should try to copy backups over when the mount is restored? 🤔

**Comment by florezriascos** [comment]
Excuse my English, I use google translate.... change the name of the service, that is, instead of calling the service "Synology" put any other, since for me it worked to have changed it.... It seems that Hassio has conflicts with other services that bear the same name within the integration... Best regards

**Comment by cods4** [comment]
Same issue here. Hoping for a fix so I can shut my NAS down from time to time without any issues.

I managed to find the directory on HAOS on a NUC
From an ssh session (or from the terminal add-on):
docker exec -it $(docker ps -f name=supervisor -q) bash
cd /data/mounts/'your/mount/point'
verify that there are some files there that shouldn't be (i.e make sure you dont do this with your share mounted or you could delete your files from your backup directory on your NAS)
rm -rf *

**Comment by jmealo** [comment]
Where is the code in Home Assistant for this? I'd like to take a look.

**Comment by Knight1981** [comment]
Same problem with my QNAP NAS. Can not mount because /data/mounts/QNAP is not empty.

**Comment by jmealo** [comment]
I guess the real issue here is that home assistant doesn't check if the mount is a mount when it writes a file, and they we have a straggler. The question is what behavior is the safest/least surprising...

I'm thinking it'd make more sense to add UUID to the mount point and delete empty ones ... that way we don't remove any backups or rename them (and we'd never have the "not empty") error again...

**Comment by jmealo** [comment]
These are all related I think: https://github.com/home-assistant/supervisor/issues/4577 https://github.com/home-assistant/supervisor/issues/4357 https://github.com/home-assistant/supervisor/issues/4358

**Comment by mikeschmick** [comment]
Same issue here. Ended up giving up on network storage for backup

**Comment by Kjeldgaard** [comment]
!Perform below on your own risk!

So basically to fix this:

1. Install, configure, and start "Advanced SSH & Web Terminal". I think you have to disable protected mode.
2. Enter "docker exec -it $(docker ps -f name=supervisor -q) bash"
3. Navigate to "/data/mounts/YOUR_REMOTE_BACKUP_NAME"
4. Delete all .tar file in directory
5. Exit docker and terminal
6. Remount network storage from UI

**Comment by smoki3** [comment]
Same issue here since 2023.12

**Comment by alexboss** [comment]
Same issue here.
Error in the logfile:
```
23-12-11 10:53:31 INFO (MainThread) [supervisor.mounts.manager] Reloading mount: HetznerStorageBox
23-12-11 10:53:31 INFO (MainThread) [supervisor.mounts.mount] Mount HetznerStorageBox is not mounted, mounting instead of reloading
23-12-11 10:53:31 ERROR (MainThread) [supervisor.mounts.mount] Cannot mount HetznerStorageBox at /data/mounts/HetznerStorageBox because it is not empty
```
Once I reload the mount from the UI after clicking "Reload" in the notification received, it works again... until a couple of hours later when the error re-occurs.

**Comment by smoki3** [comment]
I am not able to mount any drive since the lastet update

**Comment by circa1665** [comment]
Same issue:
```
23-12-13 21:57:31 INFO (MainThread) [supervisor.mounts.manager] Reloading mount: Backups
23-12-13 21:57:31 INFO (MainThread) [supervisor.mounts.mount] Mount Backups is not mounted, mounting instead of reloading
23-12-13 21:57:31 ERROR (MainThread) [supervisor.mounts.mount] Cannot mount Backups at /data/mounts/Backups because it is not empty
```

**Comment by IvovanWilligen** [comment]
> !Perform below on your own risk!
> 
> So basically to fix this:
> 
> 1. Install, configure, and start "Advanced SSH & Web Terminal". I think you have to disable protected mode.
> 2. Enter "docker exec -it $(docker ps -f name=supervisor -q) bash"
> 3. Navigate to "/data/mounts/YOUR_REMOTE_BACKUP_NAME"
> 4. Delete all .tar file in directory
> 5. Exit docker and terminal
> 6. Remount network storage from UI

Hi @Kjeldgaard I'm trying to get your solution the work but I get stuck in step 3.
When I navigate to "/data/mounts/YOUR_REMOTE_BACKUP_NAME"  (of course using the name of my backup share) I get the response "bash: /data/mounts/HA_BACKUP: is a directory. 

I run HA on a raspberry PI 4 and the backup share is on a windows 10 PC. 

Do you have any solution for me?

**Comment by kdober** [comment]
> !Perform below on your own risk!
> 
> So basically to fix this:
> 
>     1. Install, configure, and start "Advanced SSH & Web Terminal". I think you have to disable protected mode.
> 
>     2. Enter "docker exec -it $(docker ps -f name=supervisor -q) bash"
> 
>     3. Navigate to "/data/mounts/YOUR_REMOTE_BACKUP_NAME"
> 
>     4. Delete all .tar file in directory
> 
>     5. Exit docker and terminal
> 
>     6. Remount network storage from UI

Hi!
I also started having issue with the connection after my NAS was turn off for a few days.
Now I cannot reconnect anymore.

I tried your suggestion and now I'm getting a different error. Any idea?:
![image](https://github.com/home-assistant/supervisor/assets/11008090/c45a232a-5c48-4049-8aaf-ddbfa185b8e7)
Thanks

**Comment by Kjeldgaard** [comment]
> > !Perform below on your own risk!
> > So basically to fix this:
> > 
> > 1. Install, configure, and start "Advanced SSH & Web Terminal". I think you have to disable protected mode.
> > 2. Enter "docker exec -it $(docker ps -f name=supervisor -q) bash"
> > 3. Navigate to "/data/mounts/YOUR_REMOTE_BACKUP_NAME"
> > 4. Delete all .tar file in directory
> > 5. Exit docker and terminal
> > 6. Remount network storage from UI
> 
> Hi @Kjeldgaard I'm trying to get your solution the work but I get stuck in step 3. When I navigate to "/data/mounts/YOUR_REMOTE_BACKUP_NAME" (of course using the name of my backup share) I get the response "bash: /data/mounts/HA_BACKUP: is a directory.
> 
> I run HA on a raspberry PI 4 and the backup share is on a windows 10 PC.
> 
> Do you have any solution for me?

From the error, I think you forgot "cd". Step 3 is:
`cd /data/mounts/YOUR_REMOTE_BACKUP_NAME
`

**Comment by davidmankin** [comment]
I finally worked through @Kjeldgaard 's suggested workaround today and made a more detailed walk through that worked for me. Hope it helps others facing this issue.

https://gist.github.com/davidmankin/d243f6b7fbc103d42cd73333c601896d

**Comment by albotroz** [comment]
Same problem with HomeAssistant 2024.1.3 on Raspberry 4 (somehow didn't surprise me at all).

**Comment by alexgorbatchev** [comment]
Same issue on 2024.1.2. My NFS mount was working fine before. Can't mount it now with the same error, however trying to `cd /data/mounts/...` fails for me because there is no `mounts` in `/data`, yet i still get this error.

**Comment by Kjeldgaard** [comment]
> Same issue on 2024.1.2. My NFS mount was working fine before. Can't mount it now with the same error, however trying to `cd /data/mounts/...` fails for me because there is no `mounts` in `/data`, yet i still get this error.

Did you run the docker command?

**Comment by awilliams84** [comment]
> !Perform below on your own risk!
> 
> So basically to fix this:
> 
> 1. Install, configure, and start "Advanced SSH & Web Terminal". I think you have to disable protected mode.
> 2. Enter "docker exec -it $(docker ps -f name=supervisor -q) bash"
> 3. Navigate to "/data/mounts/YOUR_REMOTE_BACKUP_NAME"
> 4. Delete all .tar file in directory
> 5. Exit docker and terminal
> 6. Remount network storage from UI

This worked! Thank you!

**Comment by IvovanWilligen** [comment]
And again a freshly add backup location gets this error. Very disappointing that no core developer seems to pick up this bug report...

**Comment by pfurrie** [comment]
@IvovanWilligen I agree.

Same problem here.  QNAP NAS, running HA Green.  Had added network share for backup about a week ago, and had a few good backups.  Then had to bring down the power on the house to do rewiring.  Shutdown NAS gracefully, and HA came down shortly after when the house power was cut.  When it came back online, I get the dreaded "Cannot mount HABackups at /data/mounts/HABackups because it is not empty."

![image](https://github.com/home-assistant/supervisor/assets/11449721/7fa245c8-dfe9-40ab-bbc0-6e2113f350ed)

Why does the backup routine even care about that location being empty (or not)?

**Comment by spants** [comment]
I am having the same problem with CIFS. I think if the network fails, the backup will be written to the mount point instead of the cifs drive. Subsequently, the drive cannot be mounted as the directory is not empty....

**Comment by davidmankin** [comment]
Yup, @spants that's exactly it.  I hope it gets fixed soon.  But if you
want to work around it, see the gist I posted:
https://gist.github.com/davidmankin/d243f6b7fbc103d42cd73333c601896d

It's a pain but at least it gets network backups working again.

**Comment by jmealo** [comment]
Architecture discussion on a proposed fixed to the Network Storage issues:
https://github.com/home-assistant/architecture/discussions/1033

**Comment by pfurrie** [comment]
Thanks.  Made sure my Home Assistant instance was fully updated...

![image](https://github.com/home-assistant/supervisor/assets/11449721/2d54aa7e-d76e-44dc-8b00-ea57adafda80)

Then tried (again) to setup storage for backups (again):

![image](https://github.com/home-assistant/supervisor/assets/11449721/633fcd71-2af8-403b-9de1-bce8c1e9dec6)

So, I have the latest version, and no, it didn't resolve the issue.

**Comment by MSavisoft** [comment]
I suddenly realised there had been no backups for about 2 months, and found i had this 'Not Empty' problem. Spent some time trying to diagnose ... found this thread. Tried fixes here, but failed to install Advanced Terminal as I could not understand how to generate SSH key.

Then tried adding share again, with different name. Changed backups to that, and all seemed ok.

Today noticed network storage share had vanished!
Managed to add another, which seems ok.

Suggestions:
1. Fix the 'Empty' problem, and need notification if backup fails.
2. Messages like 'Failed to to call /mounts - Mounting HomeAssist3 did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-HomeAssist3.mount for details' need improving. It meant little to me - tried systemd in Terminal, but it just said 'command not found'.
3. The  Backups list only shows their size, location and created date if the window (app or website) is VERY wide. I only found them by accident!
4. Authors should improve instructions for those not versed in linux. Eg  in https://github.com/hassio-addons/addon-ssh/tree/main for ssh authorized_keys. I gave up!

Just observations from a newish HA user!

**Comment by pfurrie** [comment]
### Is anybody with Home Assistant following this thread?

Not having an off-server backup is bad.  This problem isn't going away.

**Comment by Haraldvdh** [comment]
Frigate share is working for 2 updates now, homeassistant backup share still failing

**Comment by chriszuercher** [comment]
I hope this gets some developer attention. Also #4662 relates to this and is closed without fix?

**Comment by agners** [comment]
So there are a bit too many similar/related issue around, and unfortunately it is hard to gauge what the "me toos" in here reference exactly.


There are actually two things here:
1) Was an issue in detecting when mounts were down and protect the mount point. This is fixed with https://github.com/home-assistant/supervisor/pull/4872.
2) Is a symptom of 1). The system them wrote data to the point where the mount would go, which lead to the error "Cannot mount xy at /data/mounts/xy because it is not empty". 

Now 1) is fixed with https://github.com/home-assistant/supervisor/pull/4872. However, it might be that your particular installation still has data in that location. There are two possible fixes:

a) Use a new mount name
b) Manually clear the internal mount point

Unfortunately, b) is not quite straight forward. The directory is internally managed by Supervisor, and isn't exposed to the user. One option is to take a full backup and make a new installation, but that might be not worth the effort.

FWIW, I have tested with the current stable version of Supervisor `2024.02.1` (which contains the above fix), I was not able to create a backup even when the target host was down, or I've otherwise deleted. When trying to create a backup, the backup dialog reported an error along with this error message in the logs:

```
24-03-11 15:29:30 ERROR (MainThread) [supervisor.backups.manager] rpi3 is down, cannot back-up to it
```

Restarting the system correctly reported a not mountable target:

![image](https://github.com/home-assistant/supervisor/assets/34061/3e5caaf1-180e-414b-91d0-86acfbc46aae)

Trying a backup again, lead to the same error mentioned above.

Once the server was online again, using "Reload" on the repair caused it to mount again, and I was able to take a backup.

**Comment by bouyssic** [comment]
Hello @agners,

Thanks for the answer, and I agree with you there are two issues on this thread. The fix you mention indeed seems to solve problem 1. 

That being said, you mention
> Now 1) is fixed with #4872. However, it might be that your particular installation still has data in that location leading to 2) 😢 . There are two possible fixes:
> 
> a) Use a new mount name (e.g. for the original poster, simply use something other than `HomeNAS_Backup`). b) Manually clear the internal mount point.
> 
> Unfortunately, b) is not quite straight forward. The directory is internally managed by Supervisor, and isn't exposed to the user. 

Couldn't the repair in Home Assistant offer to delete the content of the mount path, to be prevent people from having to Terminal into the instance and manually delete things?
Since we already have "Remove" & "Reload" we could add a "Clean-up" option that would do it automatically since the Supervisor has access to this data.

Just a guess, not a requirement.

**Comment by agners** [comment]
> Couldn't the repair in Home Assistant offer to delete the content of the mount path, to be prevent people from having to Terminal into the instance and manually delete things? Since we already have "Remove" & "Reload" we could add a "Clean-up" option that would do it automatically since the Supervisor has access to this data.

We could add a repair which fixes that. However, the problem should never have happened in first place. Maybe we should have added a repair (or automatically fix) while implementing #4872, but since that is already a while ago I wonder if it is still worth the effort today :thinking: 

What we could do is automatically delete that internal folder when creating a mount. This way there would be an easier way out :thinking:

**Comment by pfurrie** [comment]
@agners, you had mentioned "use a new mount name."  I'm probably not understanding how you mean.  I've tested created a new SMB share name on our NAS (originally was "HABackups" and now is "TEST"), for a brand-new folder, but I get the same error.
Or maybe you are meaning something different.

When you wrote "When the network storage was down, things got written to a location where the mount would go," what is that other location?  Is that location not self-healing?  Meaning, if the network storage comes back online, this is detected and queued file transfer jobs are completed, or at least don't impede any new jobs?

Sorry for being so dense about this.

**Comment by dasfdlinux** [comment]
> > Couldn't the repair in Home Assistant offer to delete the content of the mount path, to be prevent people from having to Terminal into the instance and manually delete things? Since we already have "Remove" & "Reload" we could add a "Clean-up" option that would do it automatically since the Supervisor has access to this data.
> 
> We could add a repair which fixes that. However, the problem should never have happened in first place. Maybe we should have added a repair (or automatically fix) while implementing #4872, but since that is already a while ago I wonder if it is still worth the effort today 🤔
> 
> What we could do is automatically delete that internal folder when creating a mount. This way there would be an easier way out 🤔

I ran into this issue a while back and had to install the terminal plugin to fix it, but then promptly removed the plugin when completed. As a relatively new user I do wish there had been a fix available that was more integrated, but I would strongly recommend not "automatically deleting" any folders. If you want to warn the user that there is already data in the folder and offer to delete it for them that would be okay, but automatically deleting anything always leads to a problem.

**Comment by bouyssic** [comment]
I strongly agree with @dasfdlinux . Automatically dropping data without asking would be scary ^^

**Comment by pfurrie** [comment]
@agners Thanks for that info.
This seems like a backup system oversite.  The NAS could be down for a lot of different reasons, so is there a way to get HA to be graceful on how it handles this?
A good starting point might be to have a more meaningful error message.  I took it to mean that the NAS share wasn't empty... and I don't know where the mount location in HA is, and the error message doesn't communicate that.

**Comment by mwjones1971** [comment]
> @agners Thanks for that info. This seems like a backup system oversite. The NAS could be down for a lot of different reasons, so is there a way to get HA to be graceful on how it handles this? A good starting point might be to have a more meaningful error message. I took it to mean that the NAS share wasn't empty... and I don't know where the mount location in HA is, and the error message doesn't communicate that.

I've been watching this thread since the beginning, and there may be a simple (but effective) solution (I can't take the credit for the concept, a server where I work actually does this for its backups to a remote filesystem)

When creating the mount point to the remote filesystem, HA could write a zero byte file to the backup directory. The only thing relevant is that file exists and HA knows the name (might want to make the name unique to each HA instance in case the user has multiple HA instances backing up to the same remote filesystem directory).

When the backup process starts, it should look at the contents of the backup directory, specifically looking for that file. If that file doesn't exist (because say the remote filesystem is not mounted), it could attempt to mount the remote filesystem and then check again. If it fails to find the file after the second attempt, the backup fails and a repair notification is presented to the user. Otherwise the backup runs as intended.

Alas, I'm not a programmer just an IT engineer, so I'll let those that are programmers take the idea if they want to run with it and create an appropriate PR.

**Comment by mwjones1971** [comment]
Not stale, issue still occurs.

**Comment by gitandriu** [comment]
This happens also when creating a mountpoint from scratch, not even for backup but just to browse media. I have deleted all previous mountpoint attemps and tests, restarted the host, checked that there are no folders existing in the mountpoint, and when I try to add the network storage the error comes again with the mountpoint folder just created

**Comment by LeoCal** [comment]
I’m seeing the same issue with my mounted NAS via nfs since many months. In my case, the mount point is in place on the host OS, but when I try to access a file, it errors out. The fastest way to recover is a reboot of the entire system.. the problem is that I rely on my NAS for music, especially as my main alarm clock in the morning, and if that fails (like it often happens), it’s a problem for me. Given the time it’s taking to solve, I guess I should probably move to a safer solution for the alarm clock, playing local music instead of NAS.
