### ISSUE TITLE
Mounting to Network Share fails

### ISSUE THREAD

**Issue by jjvandenberg** [home-assistant/supervisor#4365]
### Describe the issue you are experiencing

It's not possible to mount a networkshare from a Synology NAS 918
NAS is up to date and working fine
share and user account used are both tested from windows and working
log isn't very helpful

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. fill in the details of the nas as asked
2. hit connect
3. error at top of screen
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-10 18:55:26 INFO (MainThread) [supervisor.mounts.manager] Creating or updating mount: SynoBackup
23-06-10 18:55:26 ERROR (MainThread) [supervisor.mounts.mount] Mounting SynoBackup did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-SynoBackup.mount for details.
```

### System Health information

<html>
<body>
<div>

Versie | core-2023.6.1
-- | --
Type installatie | Home Assistant OS
Ontwikkeling | false
Supervisor | true
Docker | true
Gebruiker | root
Virtuele omgeving | false
Python-versie | 3.11.3
Besturingssysteem | Linux
Versie van het besturingssysteem | 6.1.29
CPU-architectuur | x86_64
Tijdzone | Europe/Amsterdam
Configuratiemap | /config

</div><div><h3>Core-statistieken</h3><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 537px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding: 8px 16px 8px 0px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><span slot="heading">Processorgebruik</span></slot><div class="secondary" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; display: block; padding-top: 4px; font-family: var(--mdc-typography-body2-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size,.875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">0.1<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="0.1%"></rect></g></svg></ha-bar></div></slot></div></div></div><div class="content" style="display: var(--settings-row-content-display,flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 537px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding: 8px 16px 8px 0px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><span slot="heading">Geheugengebruik</span></slot><div class="secondary" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; display: block; padding-top: 4px; font-family: var(--mdc-typography-body2-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size,.875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">6.7<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="6.7%"></rect></g></svg></ha-bar></div></slot></div></div></div><div class="content" style="display: var(--settings-row-content-display,flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><h3>Supervisor-statistieken</h3><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 537px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding: 8px 16px 8px 0px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><span slot="heading">Processorgebruik</span></slot><div class="secondary" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; display: block; padding-top: 4px; font-family: var(--mdc-typography-body2-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size,.875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">0.2<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="0.2%"></rect></g></svg></ha-bar></div></slot></div></div></div><div class="content" style="display: var(--settings-row-content-display,flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 537px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display); color: rgb(225, 225, 225); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.4375px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><slot name="prefix"></slot><div class="body" two-line="" style="padding: 8px 16px 8px 0px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><span slot="heading">Geheugengebruik</span></slot><div class="secondary" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; display: block; padding-top: 4px; font-family: var(--mdc-typography-body2-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size,.875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">1.6<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="1.6%"></rect></g></svg></ha-bar></div></slot></div></div></div><br class="Apple-interchange-newline">
</body>
</html>

### Supervisor diagnostics

[config_entry-hassio-cdb5aaa3e800da7b6d0127f8ca31621f.json (1).txt](https://github.com/home-assistant/supervisor/files/11712944/config_entry-hassio-cdb5aaa3e800da7b6d0127f8ca31621f.json.1.txt)

### Additional information

![Screenshot 2023-06-10 191802](https://github.com/home-assistant/supervisor/assets/66120846/721c0436-f7b7-4807-8d92-de76e58913aa)

Supplying additional logging is no problem as long as I can get a hint which log and where to find it.

**Comment by nstrelow** [comment]
I have the same problem. My SMB version is version is 2.0.2. The actual error is:

```
Jun 12 10:19:13 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-616c823707e696a13a5bf21cda09ebbe55baefa36444bf384c4e0afa7310b3e6-runc.hQ2QNg.mount: Deactivated successfully.
Jun 12 10:19:33 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-616c823707e696a13a5bf21cda09ebbe55baefa36444bf384c4e0afa7310b3e6-runc.NCe1x5.mount: Deactivated successfully.
Jun 12 10:19:38 homeassistant systemd[1]: Mounting Supervisor cifs mount: testnas...
Jun 12 10:19:38 homeassistant kernel: cifs_smb3_do_mount: 20 callbacks suppressed
Jun 12 10:19:38 homeassistant kernel: CIFS: Attempting to mount \\192.168.1.1\USB_STORAGE
Jun 12 10:19:38 homeassistant kernel: cifs_smb3_do_mount: 18 callbacks suppressed
Jun 12 10:19:38 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -22
Jun 12 10:19:38 homeassistant mount[368112]: Password for root@//192.168.1.1/USB_STORAGE:
Jun 12 10:19:38 homeassistant mount[368111]: mount error(22): Invalid argument
Jun 12 10:19:38 homeassistant mount[368111]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Jun 12 10:19:38 homeassistant systemd[1]: mnt-data-supervisor-mounts-testnas.mount: Mount process exited, code=exited, status=32/n/a
Jun 12 10:19:38 homeassistant systemd[1]: mnt-data-supervisor-mounts-testnas.mount: Failed with result 'exit-code'.
Jun 12 10:19:38 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: testnas.
Jun 12 10:19:46 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-31a1d7fd277307ff6024cd5928fec51aa8e449a1538d477ffa8c21d5afea4969-runc.gPLrpr.mount: Deactivated successfully.
Jun 12 10:19:53 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-616c823707e696a13a5bf21cda09ebbe55baefa36444bf384c4e0afa7310b3e6-runc.HOTbMb.mount: Deactivated successfully.
Jun 12 10:19:55 homeassistant kernel: audit: type=1334 audit(1686565195.268:514): prog-id=115 op=LOAD
Jun 12 10:19:55 homeassistant systemd-timesyncd[559]: Network configuration changed, trying to establish connection.
Jun 12 10:19:55 homeassistant systemd-timesyncd[559]: Contacted time server 162.159.200.1:123 (time.cloudflare.com).
Jun 12 10:19:55 homeassistant systemd[1]: Started Journal Gateway Service.
Jun 12 10:19:55 homeassistant systemd-journal-gatewayd[368320]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
Jun 12 10:20:12 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-31a1d7fd277307ff6024cd5928fec51aa8e449a1538d477ffa8c21d5afea4969-runc.uWZUHG.mount: Deactivated successfully.
Jun 12 10:20:14 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-616c823707e696a13a5bf21cda09ebbe55baefa36444bf384c4e0afa7310b3e6-runc.X37GfW.mount: Deactivated successfully.
Jun 12 10:20:24 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-fdc6289599e0d599d0cfc235df92ee89ecce67e2ee01a122f17b029b1429c365-runc.atOp1X.mount: Deactivated successfully.
Jun 12 10:20:29 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-fdc6289599e0d599d0cfc235df92ee89ecce67e2ee01a122f17b029b1429c365-runc.Xkvpel.mount: Deactivated successfully.
Jun 12 10:20:31 homeassistant systemd[1]: Mounting Supervisor cifs mount: testnas...
Jun 12 10:20:31 homeassistant kernel: CIFS: Attempting to mount \\192.168.1.1\USB_STORAGE
Jun 12 10:20:31 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -22
Jun 12 10:20:31 homeassistant mount[368672]: Password for root@//192.168.1.1/USB_STORAGE:
Jun 12 10:20:31 homeassistant mount[368671]: mount error(22): Invalid argument
Jun 12 10:20:31 homeassistant mount[368671]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Jun 12 10:20:31 homeassistant systemd[1]: mnt-data-supervisor-mounts-testnas.mount: Mount process exited, code=exited, status=32/n/a
Jun 12 10:20:31 homeassistant systemd[1]: mnt-data-supervisor-mounts-testnas.mount: Failed with result 'exit-code'.
Jun 12 10:20:31 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: testnas.
Jun 12 10:20:34 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-616c823707e696a13a5bf21cda09ebbe55baefa36444bf384c4e0afa7310b3e6-runc.eepIM8.mount: Deactivated successfully.
Jun 12 10:20:34 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-fdc6289599e0d599d0cfc235df92ee89ecce67e2ee01a122f17b029b1429c365-runc.IHOfbV.mount: Deactivated successfully.
```

**Comment by jjvandenberg** [comment]
Due to the lack of meaningful feedback within the error message, it took some effort to find the issue. 

Synology has an option to set upper and lower SMB version limits. 
By default it it set to 2 and 1. Changed this to 3 and 1, now HA can connect
