### ISSUE TITLE
Network storage SMB configuration does not accept '='

### ISSUE THREAD

**Issue by maxhov** [home-assistant/supervisor#4373]
### The problem

I am trying to add an Azure File share as backup share with the new network storage feature. However it fails to accept the password. Azure generates a SMB user and secret which are not changeable. The secret is a base64 encoded string and is padded with a '=' character, which fails the regex applied. The following error message is displayed:

`does not match regular expression ^[^,=]+$ for dictionary value @ data['password']. Got '<some random base64 string padded with =>' required key not provided @ data['server']. Got None`

### What version of Home Assistant Core has the issue?

core-2023.6.1

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Network Storage

### Anything in the logs that might be useful for us?

```txt
ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /mounts - Mounting azure_blob_backup did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-azure_blob_backup.mount for details.
ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /mounts - does not match regular expression ^[^,=]+$ for dictionary value @ data['password']. Got '<base64 encoded password padded with = >'
```

### Additional information

I've looked in the host logs, but no error message is given. If you

**Comment by YewTreeWeb** [comment]
I am having the same issue when trying to add my  Synology nas
