### ISSUE TITLE
HUGE files in /usr/share/hassio/tmp/ until filling the disk

### ISSUE THREAD

**Issue by mishoboss** [home-assistant/supervisor#4386]
### Describe the issue you are experiencing

Home Assistant produces HUGE temp files for some reason:

<img width="447" alt="image" src="https://github.com/home-assistant/supervisor/assets/1629929/ff332a1f-22a1-469d-9ee5-acfb14cf6e1a">

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

1. Just having a pretty standard setup on pretty clean Debian
2. Do nothing, wait a few days until the disk gets full

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### System Health information

<img width="630" alt="image" src="https://github.com/home-assistant/supervisor/assets/1629929/868e6277-785e-4585-ac2f-dfb964c59afb">

### Supervisor diagnostics

[config_entry-hassio-050ca08eff668a0a79d9580874e574b6.json.txt](https://github.com/home-assistant/supervisor/files/11761808/config_entry-hassio-050ca08eff668a0a79d9580874e574b6.json.txt)

### Additional information

I believe the media folder is the reason. There's a Frigate instance that writes to the media folder.

<img width="764" alt="image" src="https://github.com/home-assistant/supervisor/assets/1629929/110bc303-38ee-4903-9f7d-3bd61e4cb165">

**Comment by mishoboss** [comment]
Anyone anything?

**Comment by mishoboss** [comment]
I constantly get this behaviour and periodically have to ssh and remove files under `/usr/share/hassio/tmp/`. Am I the only one?

**Comment by agners** [comment]
This is likely caused by backups. With the new behavior the temporary files for backups are stored at the same place as the final backup (see #4452). This should resolve your problem most likely.
