### ISSUE TITLE
[error] Debian GNU/Linux 12 (bookworm) is not supported!

### ISSUE THREAD

**Issue by Florida-Duke** [home-assistant/supervisor#4390]
### Describe the issue you are experiencing

I'm trying to setup Home Assistant on a fresh install of Debian 12 and I can only get so far and I can't continue due to error.

 [error] Debian GNU/Linux 12 (bookworm) is not supported!
dpkg: error processing archive homeassistant-supervised.deb (--install):
 new homeassistant-supervised package pre-installation script subprocess returned error exit status 1
[info] Undo divert on abort-install
No diversion 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised', none removed.
[info] Resetting debconf selections
[info] Removal complete, due to the complexity of this installation method,
[info] you will need to manually remove the containers created by the supervisor
Errors were encountered while processing:
 homeassistant-supervised.deb
root@debian:~# 

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

1. Do a fresh install of Debian 12
2. Try to install Home Assistant following the steps on your webpage. 
3.[error] Debian GNU/Linux 12 (bookworm) is not supported!

...

### Anything in the Supervisor logs that might be useful for us?

```txt
Have not completed the install.
```

### System Health information

Have not completed the install. 

### Supervisor diagnostics

Have not completed the install. 

### Additional information

Please see above...
Does not seem to work on Debian 12.

**Comment by Baxxy13** [comment]
supervised-installer 1.5.0 ("bookworm-ready") was released last week.

I had no problems setting up a supervised installation on Debian "Bookworm".
