### ISSUE TITLE
can't install latest update of bitwarden to 0.19.4 

### ISSUE THREAD

**Issue by jdumeez** [home-assistant/supervisor#4397]
### The problem

When trying to update from 0.19.3 to 0.19.4 for bitwarden an error is thrown:

Can't install ghcr.io/hassio-addons/bitwarden/amd64:0.19.4: 500 Server Error for http+docker://localhost/v1.42/images/ghcr.io/hassio-addons/bitwarden/amd64:0.19.4/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")

![image](https://github.com/home-assistant/core/assets/87583037/6efddbc1-c3b0-45f6-8451-24a308b4c670)

Currently on the vary latest version of home assistant running other official and community add-ons:
Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.2
Frontend 20230503.3 - latest

Initially reported under the bitwarden integration but requested by Frenck to move it here 
https://github.com/hassio-addons/addon-bitwarden/issues/267

### What version of Home Assistant Core has the issue?

10.3

### What was the last working version of Home Assistant Core?

-

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Bitwarden 

### Link to integration documentation on our website

https://community.home-assistant.io/t/home-assistant-community-add-on-bitwarden-rs/115573

**Comment by frenck** [comment]
Transferred the issue

**Comment by lucassant95** [comment]
Having the same issue here. I unistalled a previous version and after trying to install it again, this error appeared

**Comment by jdumeez** [comment]
This activity still persists on the very latest version
