### ISSUE TITLE
VXLAN interfaces are not considered by home-assistant

### ISSUE THREAD

**Issue by rany2** [home-assistant/supervisor#4411]
### Describe the issue you are experiencing

VXLAN interfaces should be allowed here: https://github.com/home-assistant/supervisor/blob/16e1f839d7aea5d7a5bdf99512ed8d6a6f6b0c62/supervisor/dbus/network/__init__.py#L203-L213

From https://developer-old.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMDeviceType: 

NM_DEVICE_TYPE_VXLAN | = 19 | a VXLAN interface 

It might be worth considering adding more interface exemptions to prevent this issue from popping up again for other device types.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

1. Create VXLAN interface using NetworkManager
2. Notice Home Assistant does not consider it

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### System Health information

N/A

**Comment by mdegat01** [comment]
That list is filtered to the types of network interfaces which can be created in the Home Assistant UI and CLI. Those are the only supported network interfaces. If you believe VXLAN interfaces should be supported then please submit a [feature request](https://community.home-assistant.io/c/feature-requests/13) with your use case and reasoning. Or if you are comfortable in code, submit a pull request here adding support for creating VXLAN interfaces in Supervisor.

However bear in mind you are running in an unsupported installation type (Supervised and not on Debian). So you would need to show that this applies to users running in a supported type of installation. No feature requests or bug reports are accepted for use cases on unsupported systems.

**Comment by rany2** [comment]
> However bear in mind you are running in an unsupported installation type (Supervised and not on Debian). So you would need to show that this applies to users running in a supported type of installation. No feature requests or bug reports are accepted for use cases on unsupported systems.

Well, it probably only applies to 0.001% of users that opted to use VXLAN instead of VLAN to isolate their IOT devices. I doubt it's a common configuration; at any rate, I ended up switching to regular Home Assistant without supervised. I prefer to do everything via a venv as it's more flexible and I could test patches easily that way.

> That list is filtered to the types of network interfaces which can be created in the Home Assistant UI and CLI

I see, that makes sense. I could submit a PR regardless, it's going to be a two line change; though seeing that these interfaces could not be created in a normal supported OS/configuration I guess it won't go through/be accepted.
