### ISSUE TITLE
Restart(s) required after update to latest 2023.06.4 (restarted 3 times)

### ISSUE THREAD

**Issue by vlad36N** [home-assistant/supervisor#4414]
### Describe the issue you are experiencing

Hello,
Restart(s) required after update to latest 2023.06.4 (HA restarted 3 times).

![error](https://github.com/home-assistant/supervisor/assets/30022288/298b4ae0-a428-4695-b156-f412d1f03804)

![error1](https://github.com/home-assistant/supervisor/assets/30022288/7974af13-d23d-4bcb-9404-aab21ad82dfa)

![error2](https://github.com/home-assistant/supervisor/assets/30022288/0059c9cd-97b3-407a-9df7-bad8fa0c9f75)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Restart(s) required after update to latest 2023.06.4 (HA restarted 3 times).

### Anything in the Supervisor logs that might be useful for us?

```txt
No entry in a log
```

### System Health information

![error](https://github.com/home-assistant/supervisor/assets/30022288/a82ac1ab-717d-48f7-b44b-39326ed7336b)

### Additional information

Restart(s) required after update to latest 2023.06.4 (HA restarted 3 times).

**After 2 more restarts "Restart(s) required" gone.**

**Comment by kmg454** [comment]
Same problem and we can't reach the add on page and backup page anymore

**Comment by q1t1** [comment]
I have the same problem.
It breaks my Aqara integrations, the logs say it can't connect to the gateways.

**Comment by rast76es** [comment]
same problem.

my mqtt integrations dont work, I am restoring, so that everything works again.

**Comment by q1t1** [comment]
Restoring right now too, hoping it will be back online.

Shame we can't see the status of the restore process...

**Comment by kmg454** [comment]
> same problem.
> 
> my mqtt integrations dont work, I am restoring, so that everything works again.

How do you restore I tried all the options but nothing seems to work

**Comment by q1t1** [comment]
From the System>Backups section

**Comment by kmg454** [comment]
> From the System>Backups section

That's my problem I can't open this section anymore, tried restore by terminal but it doesn't work

**Comment by rast76es** [comment]
I have finished restoring, but the supervisor its 2023.6.4, fail, my mqtt integration doesnt work $%$*

**Comment by q1t1** [comment]
Is it possible to downgrade it ?

> I have finished restoring, but the supervisor its 2023.6.4, fail, my mqtt integration doesnt work *

**Comment by kmg454** [comment]
Seems everyone has different problems with this update. My mqtt is working, but can reach the Addon section and backup section and my location can't be found from my phone.
Downgrade didn't work here

**Comment by kmg454** [comment]
Just found that they screw up the paths to the different sections, if you type the path by hand in your browser it worked.
But from the menu's you get Bad gateway

**Comment by q1t1** [comment]
Some of my addons work, like Nginx Proxy Manager but still can't have the login screen.

I will risk a reboot...

**Comment by ping-localhost** [comment]
Broke the VS Code integration for me. Everything else somehow works

**Comment by q1t1** [comment]
System is alive but my Aqara integration is still dead.
My mqtt broker seems in bad shape too...

**Comment by rast76es** [comment]
SmartThings integration broken too

**Comment by nickidw** [comment]
> I have finished restoring, but the supervisor its 2023.6.4, fail, my mqtt integration doesnt work *

So restoring an old backup does not restore supervisor? I don't recall it asking to make a backup when installing, and don't see one.

**Comment by holdestmade** [comment]
Having same issue here, had issue with Studio Code Server addon yesterday and today all my cloud integrations will not connect, ping 8.8.8.8 works fine though.

Also REST and Appdaemon will not start

**Comment by dharvey242** [comment]
Exactly the same issue here.  Seems to be a DNS issue.  please help team.

**Comment by Threesa** [comment]
Same...
Broke my entire installation.

Restore from partial back-up didn't work.
Restore from full back-up didn't work.

New clean installation and restore from full back-up strangely enough didn't work neither...

**Comment by nickidw** [comment]
> Same... Broke my entire installation.
> 
> Restore from partial back-up didn't work. Restore from full back-up didn't work.
> 
> New clean installation and restore from full back-up strangely enough didn't work neither...

From what I've read the Supervisor auto-upgrades and you can't stop it, so after restoring it probably upgraded itself

**Comment by Threesa** [comment]
> 

Looks like it... Now my entire house is down, which will cause quite some headaches...

**Comment by ashulgach** [comment]
> I used the following workaround to fix the DNS issues (as seen on the Discord channel):
> 
> ```
> ha su reload
> 
> ha dns update --version 2022.04.1
> 
> ha multicast update --version 2022.02.0
> ```

This worked, thank you!

**Comment by dharvey242** [comment]
> > I used the following workaround to fix the DNS issues (as seen on the Discord channel):
> > ```
> > ha su reload
> > 
> > ha dns update --version 2022.04.1
> > 
> > ha multicast update --version 2022.02.0
> > ```
> 
> This worked, thank you!

This worked for me too. Thanks 👍

**Comment by nickidw** [comment]
> I used the following workaround to fix the DNS issues (as seen on the Discord channel):
> 
> ```
> ha su reload
> 
> ha dns update --version 2022.04.1
> 
> ha multicast update --version 2022.02.0
> ```

Does this resolve the mqtt bridge issue, do you know?

**Comment by nickidw** [comment]
Tried it for my issue with mqtt bridge entities, made no difference.

**Comment by q1t1** [comment]
Had to reboot and my Aqara integrations are broken again...

**Comment by yuckypants** [comment]
My only issue is apexcharts - none of them will update.

**Comment by HarvsG** [comment]
Related: https://github.com/home-assistant/core/issues/95616

**Comment by nickidw** [comment]
Reloading Mosquitto Addon yet another time sorted my mqtt problem out, not sure why the previous restarts had no effect.

**Comment by mdegat01** [comment]
Are you clicking on the repair and clicking "fix issue" or are you just restarting HA? Because restarting HA does not fix the issue, HA is just one container and there are many. Supervisor needs to specifically restart and rebuild the containers of the things with that issue.

**Comment by nickidw** [comment]
I clicked on all the restart notifications that were presented, they went away, but the issue did not. Then did a few more restarts afterwards.
