### ISSUE TITLE
Tag 2023.06.4 is not released homeassistant/amd64-hassio-supervisor:2023.06.4

### ISSUE THREAD

**Issue by mariushosting** [home-assistant/supervisor#4415]
### Describe the issue you are experiencing

The tag :2023.06.4 for docker is not released yet.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

manifest unknown when try to download version :2023.06.4

### Anything in the Supervisor logs that might be useful for us?

```txt
nope
```

### System Health information

healthy

### Additional information

tag is not released

**Comment by ludeeus** [comment]
<https://github.com/home-assistant/supervisor/pkgs/container/amd64-hassio-supervisor/105057345?tag=2023.06.4>
