### ISSUE TITLE
Error updating blocked from execution, was unable to update plugin(s) cli, dns, audio, multicast and all plugins must be up to date first

### ISSUE THREAD

**Issue by BartKoopmans** [home-assistant/supervisor#4429]
### The problem

when trying to update from 2023.6.3 to 2023.7.1 I get following error:
[547849012880] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, was unable to update plugin(s) cli, dns, audio, multicast and all plugins must be up to date first

### What version of Home Assistant Core has the issue?

core-2023.6.3

### What was the last working version of Home Assistant Core?

core-2023.6.3

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:305
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:19:04 (4 occurrences)
Last logged: 12:28:29

[547849012880] Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, was unable to update plugin(s) cli, dns, audio, multicast and all plugins must be up to date first
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 303, in async_install
    await async_update_core(self.hass, version=version, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 52, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: 'HomeAssistantCore.update' blocked from execution, was unable to update plugin(s) cli, dns, audio, multicast and all plugins must be up to date first

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 305, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Core 'HomeAssistantCore.update' blocked from execution, was unable to update plugin(s) cli, dns, audio, multicast and all plugins must be up to date first

**Comment by frenck** [comment]
Hi @BartKoopmans 👋 

Could you share the output of the `ha info` command? (run it from a terminal)

../Frenck

**Comment by BartKoopmans** [comment]
[core-ssh ~]$ ha info
arch: aarch64
channel: stable
docker: 23.0.6
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- os_agent
- haos
- resolved
- journal
- disk
- mount
hassos: "10.3"
homeassistant: 2023.6.3
hostname: homeassistant
logging: info
machine: raspberrypi4-64
operating_system: Home Assistant OS 10.3
state: running
supervisor: 2023.07.1
supported: true
supported_arch:
- aarch64
- armv7
- armhf
timezone: Europe/Brussels

**Comment by BartKoopmans** [comment]
Nothing special for the rest @frenck in the logs...
Only thing maybe related could be this, however not sure if I saw this as well yesterday when I first tried:

_Logger: homeassistant.components.media_player
Source: runner.py:179
Integration: Mediaspeler ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 12:18:24 (2 occurrences)
Last logged: 12:18:24_

Setup of media_player platform dlna_dmr is taking over 10 seconds._

**Comment by mdegat01** [comment]
Can you take a look at your supervisor logs? Go to logs and change to supervisor at the top. Please share those from around the time this update failed.

**Comment by BartKoopmans** [comment]
New to HomeAssistant, apologies ;-)
Just tried to update again, this is logged:

23-07-07 18:10:37 ERROR (SyncWorker_5) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-dns:2023.06.2: 500 Server Error for http+docker://localhost/v1.42/images/ghcr.io/home-assistant/aarch64-hassio-dns:2023.06.2/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")
23-07-07 18:10:37 ERROR (MainThread) [supervisor.plugins.dns] CoreDNS update failed
23-07-07 18:10:37 ERROR (SyncWorker_2) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-cli:2023.06.0: 500 Server Error for http+docker://localhost/v1.42/images/ghcr.io/home-assistant/aarch64-hassio-cli:2023.06.0/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")
23-07-07 18:10:37 ERROR (MainThread) [supervisor.plugins.cli] CLI update failed
23-07-07 18:10:37 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-multicast:2023.06.2: 500 Server Error for http+docker://localhost/v1.42/images/ghcr.io/home-assistant/aarch64-hassio-multicast:2023.06.2/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")
23-07-07 18:10:37 ERROR (MainThread) [supervisor.plugins.multicast] Multicast update failed
23-07-07 18:10:37 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-audio:2023.06.0: 500 Server Error for http+docker://localhost/v1.42/images/ghcr.io/home-assistant/aarch64-hassio-audio:2023.06.0/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")
23-07-07 18:10:37 ERROR (MainThread) [supervisor.plugins.audio] Audio update failed
23-07-07 18:10:37 WARNING (MainThread) [supervisor.jobs] 'HomeAssistantCore.update' blocked from execution, was unable to update plugin(s) cli, dns, audio, multicast and all plugins must be up to date first

**Comment by frenck** [comment]
> Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument

Seems like your storage is having issue.

You could try to restart your machine and run `ha supervisor repair` from a terminal afterwards.

../Frenck

**Comment by BartKoopmans** [comment]
success, thanks!
I think I'll look for a SSD iso micro SD moving forward.

**Comment by BartKoopmans** [comment]
Problem solved, exploring further...
