### ISSUE TITLE
Energy & solar production table time of day problem.

### ISSUE THREAD

**Issue by Takymetri** [home-assistant/supervisor#4431]
### Describe the issue you are experiencing

The energy page/table time is 1-2 hours above. Local time 12:34, HA Energy table klo 13-14
How would I get the Energy display at the right time?
Changing the time zone has no effect, setting the time on your own clock has no effect.

I also tried on my phone with the HA app, Android environment and the same problem.
What is also surprising is that HA time is +2 hours more than GMT time. Helsinki should be GMT +2 (in summer +3), not -2 hours.

![HA_3](https://github.com/home-assistant/supervisor/assets/114580014/7f5cd13c-0afd-47cf-a9cb-8533eead32c6)
![HA_2](https://github.com/home-assistant/supervisor/assets/114580014/c13d4b5e-3ea7-481b-bedf-127e2d52e4bd)
![HA_1](https://github.com/home-assistant/supervisor/assets/114580014/ea44f251-2c0f-48f8-b97c-1df86a4cfb50)
![HA_4](https://github.com/home-assistant/supervisor/assets/114580014/f44721eb-3a0e-4b75-8080-4595eb3db6ce)
![HA_5](https://github.com/home-assistant/supervisor/assets/114580014/eb82bb1c-04f6-46b2-a38c-89a7288e467b)
![HA_6](https://github.com/home-assistant/supervisor/assets/114580014/bb2f4ac5-2f69-4bd3-84ef-009b0c58ec0a)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
I don't know.
```

### System Health information

All OK.

**Comment by pvizeli** [comment]
you need call `ha core rebuild` to change the time

**Comment by Takymetri** [comment]
OK.
That has to be done on the HA computer (PC) directly, not in the Terminal window?

**Comment by Takymetri** [comment]
**ha core rebuild....** no, it doesn't change anything, see the attached picture

![ha_core_rebuild](https://github.com/home-assistant/supervisor/assets/114580014/9f9aca73-c3c5-4ee9-a2fe-f994177b28a3)

**Comment by Takymetri** [comment]
The device where HA is installed is a PC and its BIOS clock is correct.

**Comment by Takymetri** [comment]
Heureka...!!!

Now is the right time for HA!

What did I do?
System time +2 (Helsinki)
User setting - use local time
ha core rebuild
system boot

![image](https://github.com/home-assistant/supervisor/assets/114580014/8bf95cb0-648b-4dc1-8877-12e978ab3d00)
![image](https://github.com/home-assistant/supervisor/assets/114580014/68d46178-fdb6-4e0d-8e75-a0fd8643b327)
