### ISSUE TITLE
HA shows new version for Supervisor 2023.07.1 but this version is not available on docker hub

### ISSUE THREAD

**Issue by mmattel** [home-assistant/supervisor#4437]
### Describe the issue you are experiencing

Maybe just forgotten to be exported, but HA shows new Supervisor version 2023.07.1 which is not available on docker hub.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

Running 2023.06.3 successfully you get the availability notice.

### Anything in the Supervisor logs that might be useful for us?

```txt
not relevant
```

### System Health information

not relevant

**Comment by pvizeli** [comment]
See release notes of 2023.07

**Comment by mmattel** [comment]
The linked [release notes](https://github.com/home-assistant/supervisor/releases/tag/2023.07.1) shown in HA (an also the one for [2023.07.0](https://github.com/home-assistant/supervisor/releases/tag/2023.07.0)) do not mention anything about not creating a docker image. So what do I have missed?
