### ISSUE TITLE
Supervisord crashes when a second network interface has no gateway

### ISSUE THREAD

**Issue by kiler129** [home-assistant/supervisor#4442]
### The problem

The problem is rather simple: Supervisord assumes that every network interface will have a set of an IP+CIDR and a gateway address. This is a flawed assumption, as with multiple network cards realistically only the primary one should have a default route gateway.

Attempting to save a config like following, with the `enp6s18` being set to DHCP:
![image](https://user-images.githubusercontent.com/1227834/216835715-b58f0c1a-9e4f-4fe2-9c70-66c764b85573.png)

Results in an error:
![Screenshot 2023-02-05 at 11 34 46](https://user-images.githubusercontent.com/1227834/216835736-a8f8e1a0-23a7-490c-bc80-5210c59fb44c.png)

### What version of Home Assistant Core has the issue?

2023.2.2

### What was the last working version of Home Assistant Core?

N/A

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Supervisord itself

### Anything in the logs that might be useful for us?

I isolated the problem to this exception, produced in the `supervisord` container:

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/1227834/216835814-d9c15d49-92cd-4167-adec-2412414969a3.png">

### Additional information

Putting a gateway on that second card seems to solve the issue. However, I'm not sure if it will not cause problems down the line as generally I don't want a gateway on that card.

**Comment by agners** [comment]
This is reproducible on Supervisor 2023.08.1. It seems that also the frontend behaves a bit weird: At times the settings cannot be saved even though changes have been made.

**Comment by anduchs** [comment]
Can confirm, still broken.
As a temporary workaround, I could set the gateway to the IP that I assigned to this interface; i.e. referring to itself as gateway.
AFAIK, this should work with the underlying logic of routing in Linux.
But it would be great if this could be fixed.
