### ISSUE TITLE
AIOHTTP Error in Log for Supervisor 2023.07.2 {BETA} 

### ISSUE THREAD

**Issue by jweston2112** [home-assistant/supervisor#4454]
### Describe the issue you are experiencing

I noticed an AIOHTTP Error in the log (See log message below... obfuscated due to Bearer Token information)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Look in the Log

### Anything in the Supervisor logs that might be useful for us?

```txt
23-07-24 02:50:15 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Invalid header value char:
    b'Authorization: Bearer *********************************************************************************************************410939e'
                                                                                                                                            ^
```
```


### System Health information

## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1273
Downloaded Repositories | 22
HACS Data | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | beta
supervisor_version | supervisor-2023.07.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 228.5 GB
disk_used | 13.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | HassOS I2C Configurator (0.13a), Node-RED (14.4.2), Advanced SSH & Web Terminal (15.0.5), Samba Backup (5.2.0), Samba share (10.0.2), ArgonOne Active Cooling (29c), Music Assistant BETA (2.0.0b60), ESPHome (beta) (2023.7.0), Piper (0.1.3), Whisper (0.2.1), Studio Code Server (5.9.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 15
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 20, 2023 at 5:51 PM
-- | --
current_recorder_run | July 24, 2023 at 2:48 AM
estimated_db_size | 58.86 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

[config_entry-hassio-b20a568cb4d1e3c68d96d3ee7f3f12f1.json.txt](https://github.com/home-assistant/supervisor/files/12142739/config_entry-hassio-b20a568cb4d1e3c68d96d3ee7f3f12f1.json.txt)


### Additional information

_No response_

**Comment by mdegat01** [comment]
I am not seeing this error on any of my systems. What are you doing to reproduce this? I've tried restarting supervisor and the host on these systems and it doesn't happen. I have debug logging turned on as well.

**Comment by pvizeli** [comment]
If you restart the add-on, will that change something? Because we generate a new token and it's unlike the new token will have invalid chars as well

**Comment by jweston2112** [comment]
It does get a new token but I still get the Error message.... I also realized that AIOHTTP was upgraded in 2023.07.2 and I wonder if that is the issue...

**Comment by mdegat01** [comment]
Based on the message and the location of the caret my guess would be a whitespace character is getting included. One that isn't showing up in the log (since there's a lot that don't render as anything readable) but is throwing off the parsing. I'm not exactly sure how to prove that or where that could be coming from though...

**Comment by mdegat01** [comment]
> It does get a new token but I still get the Error messages (it actually repeats 2X).... I also realized that AIOHTTP was upgraded in 2023.07.2 and I wonder if that is the issue...

@jweston2112 you're right. this is this issue. Since you mentioned the name of the addon I found it via googling (to confirm, it's [this one](https://github.com/adamoutler/HassOSArgonOneAddon) right?). I saw that it was making the call here: https://github.com/adamoutler/HassOSArgonOneAddon/blob/851bad19ff5f4fdd40219a07f2a523b00bff0ba4/argonOne/run.sh#L78-L84

I made a simple script to do the same thing like this aimed at my dev system:
```bash
HTTP/1.0 400 Bad Request
#!/bin/bash

SUPERVISOR_TOKEN=token_from_dev_addon
reqBody='{"state": "hi", "attributes": {"friendly_name": "argon test"}}'
nc -i 1 192.168.1.10 80 <<< unix2dos<<EOF
POST /homeassistant/api/states/sensor.test HTTP/1.1
Authorization: Bearer ${SUPERVISOR_TOKEN}
Content-Length: $( echo -ne "${reqBody}" | wc -c )

${reqBody}
EOF
```
This failed with the same error you see. After downgrading aiohttp to 3.8.4 inside the supervisor container and restarting, this succeeded.

I'm at a loss as to why but I will revert that PR until I can figure out why. Thanks for alerting me to this, sorry it took so long

**Comment by jweston2112** [comment]
@mdegat01 looks like the Supervisor release build bombed.... ☹️

**Comment by jweston2112** [comment]
Thats Ok... I was just trying to notify you (et. al.) before it rolled out to Production in case it was a larger issue.  The loss of that one sensor and the log entries ( while an affront to my OCD) were not "extremely" critical to me... so even if it resurfaces in the future no harm no foul ... as long as it is understood and not a massive issue ...

**Comment by mdegat01** [comment]
@jweston2112 just a heads up the aiohttp bump is in 2023.08.1. That was sooner then I expected it to be but we had a showstopper in #4459  that required an immediate new release.

If you want to buy some time before the addon stops working can switch the stable channel as that won't be updated until next week at some point.
