### ISSUE TITLE
failure to change network settings due to "unknown setting name"

### ISSUE THREAD

**Issue by spaceserpent** [home-assistant/supervisor#4459]
### Describe the issue you are experiencing

Describe the issue you are experiencing

received an error stating "Can't update config on enp1s0: device: unknown setting name" when attempting to cahnge network settings: IP, DNS, gateway, etc. Persist despite reboots, resets of network connections, etc.

Currently running HA OS on generic linux

![256684091-a77a7cae-72f1-417b-b9f1-41849a6a042a](https://github.com/home-assistant/supervisor/assets/113296162/f0c9a71a-96bb-4380-bcae-a3f9640e4b07)
![257000757-5331254b-cb8c-4d87-9f8b-833e79a93570](https://github.com/home-assistant/supervisor/assets/113296162/0c460e76-1a45-423f-8887-ddc3a06ddcb8)

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. have pre-existing network config
2. attempt to change network config of an interface
3. error recieved

### Anything in the Supervisor logs that might be useful for us?

```txt
23-07-29 13:47:19 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 13:48:18 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:00:25 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:00:47 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:00:47 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:06:34 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:06:34 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:07:00 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:07:00 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:07:13 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
23-07-29 14:07:16 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:07:16 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:08:24 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:08:24 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:08:29 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:08:36 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:08:36 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:09:06 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:09:06 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:09:12 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:09:12 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
23-07-29 14:09:17 INFO (MainThread) [supervisor.api.middleware.security] /network/interface/enp1s0/update access from core_ssh
23-07-29 14:09:17 ERROR (MainThread) [supervisor.host.network] Can't update config on enp1s0: device: unknown setting name
```

## System Information

version | core-2023.8.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1263
Downloaded Repositories | 30

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | beta
supervisor_version | supervisor-2023.07.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 916.2 GB
disk_used | 11.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Spotify Connect (0.12.4), AirCast (3.5.3), AdGuard Home (4.8.12), Network UPS Tools (0.12.0), Terminal & SSH (9.7.1), File editor (5.6.0), chrony (2.6.0), Studio Code Server (5.9.0), Nextcloud (27.0.1-7), motionEye (0.19.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 11
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 19, 2023 at 9:22 AM
-- | --
current_recorder_run | July 27, 2023 at 11:51 PM
estimated_db_size | 513.96 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by spaceserpent** [comment]
write a ticket in HA, asked to write one here, can close either if needed,, https://github.com/home-assistant/frontend/issues/17421

**Comment by Zver5** [comment]
i have the same problem
2023.8.0b1
2023.07.2

23-08-01 00:26:31 ERROR (MainThread) [supervisor.host.network] Can't update config on enp3s0: device: unknown setting name

**Comment by Chickenbreast0** [comment]
Same for me:

"Can't update config on enp2s0: device: unknown setting name"

2023.8.0

**Comment by michaeldvinci** [comment]
version: 2023.8.0

hardware: Home Assistant Yellow

Seeing the same functionality here as well when editing any network interface

**Comment by stofakiller** [comment]
Same problem her, also triede in terminal: ha network "apdaptername"...
Same error: device unknown setting name. and if i in terminal write ha network info, it gives me that adaptername, but cant be changed...

**Comment by kaesebrot1199** [comment]
Same for me:
"Can't update config on enp2s0: device: unknown setting name" (on VMware)
2023.8.0

**Comment by stofakiller** [comment]
> Same problem her, also triede in terminal: ha network "apdaptername"... Same error: device unknown setting name. and if i in terminal write ha network info, it gives me that adaptername, but cant be changed...

In terminal the adapter is "Supervisor name-of-adaptor", but i cant change the ipv4.dns, but even if i change all and save, the result is still the same...
And the added a wlan, and throug GUI, activated it and found my router, i couldnt save the data, so perhaps the same issue...

So now i have added the MAC to my router, and made that force the ip i want... And if you dont wanna wait, reboot HA...

**Comment by Chickenbreast0** [comment]
> > Same problem her, also triede in terminal: ha network "apdaptername"... Same error: device unknown setting name. and if i in terminal write ha network info, it gives me that adaptername, but cant be changed...
> 
> In terminal the adapter is "Supervisor name-of-adaptor", but i cant change the ipv4.dns, but even if i change all and save, the result is still the same... And the added a wlan, and throug GUI, activated it and found my router, i couldnt save the data, so perhaps the same issue...
> 
> So now i have added the MAC to my router, and made that force the ip i want... And if you dont wanna wait, reboot HA...

As I wrote I checked it with all 4 ethernet ports in my device. The main one has a static IP, which I wanted to change and the three others don´t. Even I tried it with static or dynamic settings there is no change to change that damn 1st Port.

**Comment by mdegat01** [comment]
Thank you for reporting this, I can definitely reproduce this. This is a result of #4416 . I was under the impression that the fields listed in https://developer-old.gnome.org/NetworkManager/stable/NetworkManager.conf.html#device-spec were usable in all connection profiles. It would seem they are only usable for global ones.

I will try and get this fixed and a new beta version of supervisor out as soon as possible fo ryou all. Sorry about that.
