### ISSUE TITLE
Cannot mount network drive after replacing NAS.

### ISSUE THREAD

**Issue by pb8771** [home-assistant/supervisor#4474]
### Describe the issue you are experiencing

Replaced my nas. I need a network mount named "frigate" as required for the addon. After swapping the nas, I can no longer create that drive.

Running Home Assistant OS on an intel NUC.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.Deleted existing mount
2.Created new mount as instructed.
3.Mount fails
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logs of a failed mount, and a successful with a different name.

Aug 02 18:54:32 homeassistant systemd[1]: Mounting Supervisor cifs mount: test...
Aug 02 18:54:32 homeassistant kernel: CIFS: Attempting to mount \192.168.3.128\Public
Aug 02 18:54:32 homeassistant systemd[1]: Mounted Supervisor cifs mount: test.
Aug 02 18:54:56 homeassistant systemd[1]: Mounting Supervisor bind mount: bind_test...
Aug 02 18:54:56 homeassistant systemd[1]: Mounted Supervisor bind mount: bind_test.

Aug 02 18:56:39 homeassistant mount[891253]: error 2 (No such file or directory) opening credential file /mnt/data/supervisor/.mounts_credentials/frigate
Aug 02 18:56:39 homeassistant systemd[1]: mnt-data-supervisor-mounts-frigate.mount: Mount process exited, code=exited, status=2/INVALIDARGUMENT
Aug 02 18:56:39 homeassistant systemd[1]: mnt-data-supervisor-mounts-frigate.mount: Failed with result 'exit-code'.
Aug 02 18:56:39 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: frigate.

23-08-03 13:59:59 INFO (MainThread) [supervisor.store] Loading add-ons from store: 94 all - 0 new - 0 remove
23-08-03 13:59:59 INFO (MainThread) [supervisor.store] Loading add-ons from store: 94 all - 0 new - 0 remove
23-08-03 14:00:03 INFO (MainThread) [supervisor.mounts.manager] Creating or updating mount: frigate
23-08-03 14:00:03 ERROR (MainThread) [supervisor.mounts.mount] Reloading frigate did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-frigate.mount for details.
```

## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1266
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 20, 2023 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-5.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 916.2 GB
disk_used | 417.5 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.111.1), File editor (5.6.0), Let's Encrypt (4.12.9), NGINX Home Assistant SSL proxy (3.5.0), Ring-MQTT with Video Streaming (5.5.1), Samba share (10.0.2), Studio Code Server (5.10.0), Terminal & SSH (9.7.1), amcrest2mqtt (2023.5.0), Mosquitto broker (6.2.1), Scrypted (18-jammy-full.s6-v0.41.0), Frigate (0.12.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 7
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 28, 2023 at 9:04 PM
-- | --
current_recorder_run | August 1, 2023 at 8:03 PM
estimated_db_size | 113.93 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

[config_entry-hassio-4404c15c2d80fa978db13bf57db533ab.json.txt](https://github.com/home-assistant/supervisor/files/12253724/config_entry-hassio-4404c15c2d80fa978db13bf57db533ab.json.txt)

**Comment by N3rdix** [comment]
Have you tried rebooting your host after deleting the old mount?
This helped me with a similar issue...

**Comment by pb8771** [comment]
Yep. Tried rebooting the system multiple times.

**Comment by tr4nt0r** [comment]
Had the same error. The only way i found how to fix this is by recreating the credentials file manually, write the credentials in the following format:

```
username=value
password=value
```

**Comment by xAcrosonicx** [comment]
> Had the same error. The only way i found how to fix this is by recreating the credentials file manually, write the credentials in the following format:
> 
> ```
> username=value
> password=value
> ```

I’m having this issue now, can you expand on the resolution please? What file is this? Where is it located?

**Comment by tr4nt0r** [comment]
You have to ssh into the host system ( as described [here](https://developers.home-assistant.io/docs/operating-system/debugging/), then it is located in /mnt/data/supervisor/.mounts_credentials/
