### ISSUE TITLE
Can't install raspberrymatic - 404 Client Error

### ISSUE THREAD

**Issue by bennySB** [home-assistant/supervisor#4507]
### Describe the issue you are experiencing

If i want to install the raspberrymatic Addon, i get the error message:

`Can't install ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626/json: Not Found ("No such image: ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626")`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Click Settings --> Add-ons --> Add-on Store
2. Add the Repo `https://github.com/jens-maus/RaspberryMatic`
3. Install the RasberryMatic CCU Addon
...

### Anything in the Supervisor logs that might be useful for us?

```txt
It only say´s

23-08-24 21:22:25 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626/json: Not Found ("No such image: ghcr.io/jens-maus/raspberrymatic:3.69.7.20230626")
```

## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.45
arch | armv7l
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1331
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 13.7 GB
disk_used | 10.4 GB
healthy | true
supported | true
board | tinker
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.11.0), File editor (5.6.0), Log Viewer (0.15.1), Node-RED (14.4.5), AdGuard Home (4.8.14), Advanced SSH & Web Terminal (15.0.7), Home Assistant Google Drive Backup (0.111.1), Grafana (9.0.3), ESPHome (2023.8.2), Mosquitto broker (6.2.1), Zigbee2MQTT (1.32.2-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15. August 2023 um 10:13
-- | --
current_recorder_run | 24. August 2023 um 20:00
estimated_db_size | 139.38 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

[config_entry-hassio-e0ab7aca3ac1d5f8ba8584b6e015a8e5.json.txt](https://github.com/home-assistant/supervisor/files/12433641/config_entry-hassio-e0ab7aca3ac1d5f8ba8584b6e015a8e5.json.txt)

### Additional information

The Installation is on a tinker board s, so i can´t switch to a 64-Bit installation.

**Comment by Baxxy13** [comment]
Just some additional Information:
I had tested this with a RaspberryPi 4B.

With HA-OS (32bit) i can't install RaspberryMatic and got the same error shown above.
With HA-OS (64bit) i had no problems installing RaspberryMatic.

So it seems that the architecture causes the problem.

**Comment by bennySB** [comment]
> Just some additional Information: I had tested this with a RaspberryPi 4B.
> 
> With HA-OS (32bit) i can't install RaspberryMatic and got the same error shown above. With HA-OS (64bit) i had no problems installing RaspberryMatic.
> 
> So it seems that the architecture causes the problem.

Thx for your test. It is a new problem, but don't now since what version. I know it because i already had it installed in my HA, but I must reinstall it and now have this Problem.
