### ISSUE TITLE
IPv6 NFS shares fail to start on HAOS boot

### ISSUE THREAD

**Issue by CRCinAU** [home-assistant/supervisor#4517]
### Describe the issue you are experiencing

When adding external storage to an IPv6 NFS share, when HAOS boots, the IPv6 share is not available.

Adding the same host with an IPv4 address, things work as expected.

I can only assume that the NFS share is attempted to be mounted before the IPv6 interface is configured correctly.

Both IPv4 and IPv6 configuration is static within HASS.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Add an external storage with NFS over IPv6.
2. Reboot HaOS

### Anything in the Supervisor logs that might be useful for us?

```txt
No errors in HA logs.
```

## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1272
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 11.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Let's Encrypt (4.12.9), NGINX Home Assistant SSL proxy (3.5.0), Advanced SSH & Web Terminal (15.0.7), Node-RED (14.4.5), MariaDB (2.6.1), Piper (1.3.2), ESPHome (2023.8.2), Home Assistant Google Drive Backup (0.111.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 3
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 2, 2023 at 11:48 PM
-- | --
current_recorder_run | September 1, 2023 at 11:35 AM
estimated_db_size | 417.66 MiB
database_engine | mysql
database_version | 10.6.12

</details>

**Comment by agners** [comment]
> I can only assume that the NFS share is attempted to be mounted before the IPv6 interface is configured correctly.

Both IP versions are actually handled by NetworkManager at operating system boot. Network configuration happens quite a lot before Supervisor gets even started. So this seems a bit weird.

What is the error reported in the Supervisor logs in that case?

Do you use an IPv6 address directly or a DNS name which resolves to one?

**Comment by CRCinAU** [comment]
I should also note - in the failure message presented in the HA UI - If you hit the `Reload` option, then the NFS shares will map correctly even with an IPv6 target....

So its not a case of it not working at all, but maybe a timing or failure that is being treated as non-recoverable unless its manually reloaded?

**Comment by CRCinAU** [comment]
So the only thing even mentioning storage in the logs says:
```
Sep 01 01:22:19 homeassistant systemd[1]: Mounted Supervisor nfs mount: Backups.
Sep 01 01:22:19 homeassistant systemd[1]: Mounted Supervisor nfs mount: Cameras.
```

And then later on, maybe when I hit the `Reload` button on the error stating they failed:
```
Sep 01 01:23:03 homeassistant systemd[1]: Reloading Supervisor nfs mount: Cameras...
Sep 01 01:23:03 homeassistant systemd[1]: Reloaded Supervisor nfs mount: Cameras.
Sep 01 01:23:03 homeassistant systemd[1]: Unmounting Supervisor bind mount: emergency_Cameras...
Sep 01 01:23:03 homeassistant systemd[1]: mnt-data-supervisor-media-Cameras.mount: Deactivated successfully.
Sep 01 01:23:03 homeassistant systemd[1]: Unmounted Supervisor bind mount: emergency_Cameras.
Sep 01 01:23:03 homeassistant systemd[1]: Mounting Supervisor bind mount: bind_Cameras...
Sep 01 01:23:03 homeassistant systemd[1]: Mounted Supervisor bind mount: bind_Cameras.
Sep 01 01:23:06 homeassistant systemd[1]: Reloading Supervisor nfs mount: Backups...
Sep 01 01:23:06 homeassistant systemd[1]: Reloaded Supervisor nfs mount: Backups.
```

**Comment by CRCinAU** [comment]
This is not stale.

**Comment by CRCinAU** [comment]
For what its worth, if you do the NFS shares on IPv6 using the fe80:: addresses, this problem doesn't occur.

As such, I think the problem is a race condition between starting the HA container, and the point where the static IPv6 address is assigned to the machines interface.

As the fe80:: address is there as soon as the system boots, this race condition doesn't present itself....
