### ISSUE TITLE
Home Assistant crashes in the morning

### ISSUE THREAD

**Issue by StefanW86** [home-assistant/supervisor#4526]
### Describe the issue you are experiencing

Hi,
i have the version 2023.8.4 running on home assistant os on raspberry pi 4. Sometimes, also with older versions, my home assistant core is crashing in the morning. 
I see it, because i integrate alexa and uses "good morging routine" to wake up, and this doesnt work. 
Before that, my node red trigered some scheduled actions.
In the log files of the core i dont see any issues with this crash.

Where can i look, to find the correct logs, to post it here?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.32.1
Stage | running
Available Repositories | 1283
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 219.4 GB
disk_used | 18.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.5.0), Terminal & SSH (9.7.1), Node-RED (14.4.5), File editor (5.6.0), UniFi Network Application (2.7.0), Let's Encrypt (4.12.9), AdGuard Home (4.8.14), Mosquitto broker (6.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 2
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25. August 2023 um 05:05
-- | --
current_recorder_run | 4. September 2023 um 06:18
estimated_db_size | 322.29 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
remaining_requests | 5
rooftop_site_count | 1
polling_hours | 6 -> 19 and once at midnight

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Supervisor diagnostics

-

**Comment by mdegat01** [comment]
If Home Assistant core is what is crashing you can get the logs from [Settings -> System -> Logs](https://my.home-assistant.io/redirect/logs/) (or just click the link and it'll take you there on your system).

It sounds like you're experiencing a core issue though, is something wrong with supervisor? Since this is the supervisor repo.

**Comment by agners** [comment]
@StefanW86 did you find what was causing this?

**Comment by StefanW86** [comment]
@agners at the moment, no. But it should be something with the core. as soon as the problem reoccures i will open a new bug in the core repo.
