### ISSUE TITLE
Mounted Media NAS volume not working - Frigate

### ISSUE THREAD

**Issue by Operations8** [home-assistant/supervisor#4536]
[logs-2.txt](https://github.com/home-assistant/supervisor/files/12562893/logs-2.txt)
[logs-2.txt](https://github.com/home-assistant/supervisor/files/12562896/logs-2.txt)
### Describe the issue you are experiencing

I am trying to get frigate to store the recordings on my NAS.

So i did this:

https://docs.frigate.video/guides/ha_network_storage/

But it doesn't work. Frigate keeps create the recording file in /media/frigate/recordings on local SSD.

I am a 100% sure it is being stored locally, i can see it happen when looking via SMB at the local folder + i can see the local SSD space decrease and last one i am not seeing any recording on my NAS.

The credentials are working and write/read access also works.

I created a topic at the Addon github, but he points at supervisor as being the problem. 

Github:

https://github.com/blakeblackshear/frigate/discussions/7604#discussioncomment-6847209

Any ideas?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Mounted a share as media
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Maybe this:

Logger: homeassistant.config_entries
Source: components/hassio/handler.py:540
First occurred: 12:42:40 (1 occurrences)
Last logged: 12:42:40

Error setting up entry Supervisor for hassio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 665, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 257, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 974, in _async_refresh
    await self.hassio.refresh_updates()
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 37, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 540, in send_command
    request = await self.websession.request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError: Global task timeout
```

## System Information

version | core-2023.9.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.32.1
Stage | running
Available Repositories | 1278
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 109.3 GB
disk_used | 81.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (15.0.7), Samba share (10.0.2), Silicon Labs Multiprotocol (2.3.2), AdGuard Home (4.8.14), Samba Backup (5.2.0), Home Assistant Google Drive Backup (0.111.1), Network UPS Tools (0.12.0), Grafana (9.0.3), Studio Code Server (5.10.1), Ring-MQTT with Video Streaming (5.6.2), Mosquitto broker (6.3.1), Frigate (0.12.1), OneDrive Backup (2.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 6
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 1 september 2023 om 21:43
-- | --
current_recorder_run | 7 september 2023 om 12:40
estimated_db_size | 256.68 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by mdegat01** [comment]
You shared core logs. Can you please share the supervisor logs? You can get to them at [Settings -> System -> Logs](https://my.home-assistant.io/redirect/logs/) but then you have to change the toggle in the top right to "Supervisor"

**Comment by Operations8** [comment]
> You shared core logs. Can you please share the supervisor logs? You can get to them at [Settings -> System -> Logs](https://my.home-assistant.io/redirect/logs/) but then you have to change the toggle in the top right to "Supervisor"

I apologize for the mistake. I have added a logfile.

**Comment by mdegat01** [comment]
Hm is that the end of the logs? It seems to end with supervisor attempting to make the initial folder for the mount. After that it has to make the folder in `/media` and symlink them which I believe should be logged too.

But more importantly there doesn't seem to be any errors so I'm not sure what is going wrong. Although it sounds like you already have a folder called `/media/frigate` and are trying to call your media mount `frigate`. Supervisor won't blow away an existing folder by mounting over top of it so I'm going to guess that's what's happening? It's not in the logs but they seem to stop short of the point where that would happen anyway.

Assuming I am correct that you want to call your folder frigate and `/media/frigate` already exists then try this:
1. Stop frigate
2. Rename `/media/frigate` to `/media/frigate2` or `/media/frigate_old`
3. Make your media mount
4. Move anything you want within the old frigate folder into the new frigate folder
5. Confirm you can see that from some other machine that can see that network drive
6. Restart frigate
