### ISSUE TITLE
OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

### ISSUE THREAD

**Issue by aperezva** [home-assistant/supervisor#4576]
[config_entry-hassio-62170ebbae0a1bcdfc50464c7f15fdda.json.txt](https://github.com/home-assistant/supervisor/files/12709131/config_entry-hassio-62170ebbae0a1bcdfc50464c7f15fdda.json.txt)
### Describe the issue you are experiencing

Randomly I have openssl connection errors with some addon, not always the same addon that I have installed in my HA OS

If I have this issue when I´m restarting Ha, the restarting process take 5-6 minutes and I have sometimes to restart again.

I´m having this issues for a 3 months ago, and nobody could help me in the way to lnow the reason.

Please I need a forum support to solve it. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.In Supervisor logs, 6-7 times per day, when checks the updates in addons.
2.When restart HA, and in this time this check update is failing.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-09-24 17:53:56 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/MikeJMcGuire/HASSAddons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/MikeJMcGuire/HASSAddons/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443'.
23-09-24 17:53:56 INFO (MainThread) [supervisor.resolution.module] Create new suggestion execute_reset - store / e4641267
23-09-24 17:53:56 INFO (MainThread) [supervisor.resolution.module] Create new issue corrupt_repository - store / e4641267
23-09-24 17:53:58 INFO (MainThread) [supervisor.store] Loading add-ons from store: 80 all - 0 new - 0 remove
23-09-24 17:53:58 INFO (MainThread) [supervisor.store] Loading add-ons from store: 80 all - 0 new - 0 remove
23-09-24 17:53:58 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2724639' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/MikeJMcGuire/HASSAddons/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 270, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 268, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
```

## System Information

version | core-2023.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4967
Installed Version | 1.32.1
Stage | running
Available Repositories | 1300
Downloaded Repositories | 83

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 9 de enero de 2024, 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-5.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 439.4 GB
disk_used | 20.2 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba share (10.0.2), Grafana (9.0.3), Advanced SSH & Web Terminal (15.0.8), SQLite Web (3.9.3), InfluxDB (4.7.0), Mosquitto broker (6.3.1), Studio Code Server (5.10.2), Terminal & SSH (9.7.1), Home Assistant Google Drive Backup (0.111.1), Blueriiot Blue Connect (2022.9.0), Node-RED (14.5.0), Zigbee2MQTT (1.33.0-1), Tailscale (0.11.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 64
views | 35
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 14 de septiembre de 2023, 05:11
-- | --
current_recorder_run | 24 de septiembre de 2023, 05:49
estimated_db_size | 1376.73 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

[config_entry-hacs-5e8819802b45ce40bc5c4eb31a088532.json.txt](https://github.com/home-assistant/supervisor/files/12709127/config_entry-hacs-5e8819802b45ce40bc5c4eb31a088532.json.txt)

**Comment by aperezva** [comment]
This is the second time I try to have support from the community and nobody is supporting.

**Comment by agners** [comment]
This is not a support forum but an issue tracker. It is meant for code issues in Supervisor. The community forums are at 
https://community.home-assistant.io/.

Since the issue appears sporadic, I am guessing you experience a network issue. It seems that a firewall (maybe your router or maybe your provider) causes SSL connections to fail, at least sometimes.

From Supervisor side we can't really do something against it, other than retry again... I'd recommend to check your internet connectivity.

**Comment by aperezva** [comment]
Thanks,

I will manage with my provider

BR

**Comment by ernan** [comment]
I got this twice today also
![image](https://github.com/home-assistant/supervisor/assets/44041/fb12b51c-23e0-4d0b-801d-1c74b7b53a07)
