### ISSUE TITLE
Cannot download large backup from Firefox 118

### ISSUE THREAD

**Issue by madbrain76** [home-assistant/supervisor#4592]
### Describe the issue you are experiencing

I just moved my HAOS installation from a Virtualbox VM to a Raspberry Pi 4B/8GB, on an external 128GB SSD (with a powered SATA dock).

Since then, I have noticed that HAOS backup tarballs cannot be downloaded successfully from Firefox 118 on Windows.

![image](https://github.com/home-assistant/supervisor/assets/57333073/5b268bd0-8b6b-4645-a97e-9275b77f33d3)

I used a new profile of Firefox for this test, so no caching issue is at play. This is 100% reproducible - I can't download the backup at all from Firefox, ever. The backup is about 550MB in size.

If I use Chrome as a browser, there is no problem downloading the tarball.

If I switch my HAOS back to Virtualbox VM on my PC, I can download large tarballs, even from this same Firefox installation.

So, it very strangely seems to be that the combination of HAOS on Pi 4B + Firefox on Windows + large backup tarball results in this problem.

Edit: it fail identically with Firefox 118 on Linux (Ubuntu 22 x64) .

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

1.install fresh HAOS on Raspberry Pi 4B
2.restore large backup tarball (500MB+)
3.wait about 30 minutes
4. login o HAOS from Firefox on Windows
5. go to settings/system/backup
6. click the one backup tarball
7. click vertical | menu
8. click "Download backup"
9. Wait until it fails.

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing relevant, unfortunately
```

## System Information

version | core-2023.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4788
Installed Version | 1.33.0
Stage | running
Available Repositories | 1301
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.7 GB
disk_used | 10.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), File editor (5.6.0), Samba Backup (5.2.0), Samba share (10.0.2), Z-Wave JS UI (2.0.1), Genie (3.0.0), ESPHome (2023.9.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 2
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 22, 2023 at 11:12
-- | --
current_recorder_run | October 1, 2023 at 02:31
estimated_db_size | 1386.27 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
used_requests | 8
rooftop_site_count | 2

</details>

### Supervisor diagnostics

N/A

**Comment by agners** [comment]
This is a known issue, it is tracked in the frontend by https://github.com/home-assistant/frontend/issues/7258.

Are you using https?

**Comment by madbrain76** [comment]
Sorry, didn't know it was a dupe. Yes, I'm using harpsichord. Unfortunate that this bug isn't getting more attention.

**Comment by agners** [comment]
Closing as this is tracked in the above mentioned frontend issue.
