### ISSUE TITLE
Home-assistant supervisor error -- StoreGitError() from err supervisor.exceptions.StoreGitError

### ISSUE THREAD

**Issue by jesse26wong** [home-assistant/supervisor#4611]
### Describe the issue you are experiencing

Recently the HA supervisor in the integrations always shows the "setting error", and don't know how to settle this error.  The issue can't settle by reboot HA. And here is the supervisor logs, looking for your advise:

Supervisor
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
23-10-09 11:27:14 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-807625' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'error: RPC failed; curl 55 Failed sending data to the peer
fatal: expected flush after ref listing'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 281, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 274, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

This problem occurs every time once the machine is restarted.

### Anything in the Supervisor logs that might be useful for us?

```txt
Supervisor
fatal: unable to access 'https://github.com/esphome/home-assistant-addon/': Failed to connect to github.com port 443 after 130706 ms: Couldn't connect to server
'.
23-10-09 11:29:48 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-10-09 11:36:35 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-10-09 11:43:43 INFO (SyncWorker_1) [supervisor.docker.manager] Restarting homeassistant
23-10-09 11:43:43 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
23-10-09 11:43:43 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-10-09 11:43:52 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-10-09 11:43:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-10-09 11:43:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-10-09 11:43:58 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-10-09 11:43:58 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-10-09 11:43:58 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-10-09 11:44:35 ERROR (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Home Assistant API!
23-10-09 11:44:35 ERROR (MainThread) [supervisor.misc.tasks] Home Assistant watchdog reanimation failed!
23-10-09 11:45:58 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/home-assistant/addons/': Failure when receiving data from the peer'.
23-10-09 11:45:58 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'error: RPC failed; curl 55 Failed sending data to the peer
fatal: expected flush after ref listing'.
23-10-09 11:45:59 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 0 new - 3 remove
23-10-09 11:45:59 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 0 new - 0 remove
23-10-09 11:45:59 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-810206' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/home-assistant/addons/': Failure when receiving data from the peer'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 281, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 274, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
23-10-09 11:45:59 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-810205' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'error: RPC failed; curl 55 Failed sending data to the peer
fatal: expected flush after ref listing'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 281, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 274, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
23-10-09 11:46:02 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'internal'
23-10-09 11:46:02 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
23-10-09 11:46:24 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-10-09 11:46:24 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-10-09 11:46:24 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-10-09 11:46:24 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

## System Information

version | core-2023.10.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Asia/Shanghai
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4667
Installed Version | 1.33.0
Stage | running
Available Repositories | 1307
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 6.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Samba share (10.0.2), File editor (5.6.0), Node-RED (14.6.1), NGINX Home Assistant SSL proxy (3.5.0), Mosquitto broker (6.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 14
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2023年10月3日 03:50
-- | --
current_recorder_run | 2023年10月9日 11:43
estimated_db_size | 256.34 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Xiaomi Gateway 3</summary>

version | 3.3.2 (4efeaee)
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.13
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 50

</details>

**Comment by mtanasiewicz** [comment]
Same here on HomeAssistant OS Generic

**Comment by agners** [comment]
Do you still observe such issues? It seems to me like some kind of communication issue, maybe this was a temporary outage? :thinking:
