### ISSUE TITLE
Addon Empty 

### ISSUE THREAD

**Issue by SabatoArdolino** [home-assistant/supervisor#4618]
### Describe the issue you are experiencing

From few days I can't see the official addon from additional component menu. 
Reading the logs from configuration - system - registry . supervisor I can see this logs (after restart of HA)

23-10-07 02:46:37 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-16074' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/esphome/home-assistant-addon/': Could not resolve host: github.com'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 281, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 274, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
23-10-07 02:46:37 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-16070' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/einschmidt/hassio-addons/': Could not resolve host: github.com'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 281, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 274, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
23-10-07 02:46:37 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-10-07 02:46:41 WARNING (MainThread) [supervisor.addons.options] Option 'alias' does not exist in the schema for Duck DNS (core_duckdns)
23-10-07 02:46:46 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant
23-10-07 02:47:06 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-10-07 02:47:06 INFO (MainThread) [supervisor.homeassistant.core] Successfully started Home Assistant 2023.10.1
23-10-07 02:47:06 INFO (SyncWorker_1) [supervisor.docker.manager] Cleanup images: ['ghcr.io/home-assistant/qemuarm-64-homeassistant:2023.10.0']

23-10-07 02:51:45 WARNING (MainThread) [supervisor.addons.options] Option 'alias' does not exist in the schema for Duck DNS (core_duckdns)
23-10-07 02:52:35 INFO (SyncWorker_4) [supervisor.docker.manager] Restarting homeassistant
23-10-07 02:52:46 ERROR (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Home Assistant API!
23-10-07 02:52:46 ERROR (MainThread) [supervisor.misc.tasks] Home Assistant watchdog reanimation failed!
23-10-07 02:52:52 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-10-07 02:52:52 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-10-07 02:52:53 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-10-07 02:52:53 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-10-07 02:52:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/einschmidt/hassio-addons repository
23-10-07 02:52:53 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons
23-10-07 02:52:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-10-07 02:52:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-10-07 02:52:54 INFO (MainThread) [supervisor.store] Loading add-ons from store: 8 all - 0 new - 0 remove
23-10-07 02:52:54 INFO (MainThread) [supervisor.store] Loading add-ons from store: 8 all - 0 new - 0 remove
23-10-07 02:52:58 WARNING (MainThread) [supervisor.addons.options] Option 'alias' does not exist in the schema for Duck DNS (core_duckdns)
23-10-07 02:53:08 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-10-07 02:55:35 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
23-10-07 02:55:35 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
23-10-07 02:55:35 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_ssh
23-10-07 02:55:35 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_ssh

23-10-07 02:56:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-10-07 02:58:02 WARNING (MainThread) [supervisor.addons.options] Option 'alias' does not exist in the schema for Duck DNS (core_duckdns)
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.info] Updating local host information
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.services] Updating service information
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.network] Updating local network information
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.manager] Host information reload completed

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

list is empty

### Steps to reproduce the issue

1. open setting
2. Addition component
3. Try to search one of the standard addon
...

## System Information

version | core-2023.10.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.0-11-arm64
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4622
Installed Version | 1.33.0
Stage | running
Available Repositories | 1303
Downloaded Repositories | 29

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 12 (bookworm)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.2.2
docker_version | 24.0.5
disk_total | 29.9 GB
disk_used | 9.3 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Duck DNS (1.15.0), Studio Code Server (5.10.2), Home Assistant Google Drive Backup (0.111.1), NGINX Home Assistant SSL proxy (3.5.0), PSA Car Controller (v3.0.12)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 19
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27 settembre 2023 alle ore 03:46
-- | --
current_recorder_run | 7 ottobre 2023 alle ore 02:52
estimated_db_size | 257.48 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
future: <Task finished name='Task-16074' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/esphome/home-assistant-addon/': Could not resolve host: github.com'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 281, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 274, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
23-10-07 02:46:37 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-16070' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/einschmidt/hassio-addons/': Could not resolve host: github.com'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 281, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 274, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
23-10-07 02:46:37 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-10-07 02:46:41 WARNING (MainThread) [supervisor.addons.options] Option 'alias' does not exist in the schema for Duck DNS (core_duckdns)
23-10-07 02:46:46 WARNING (MainThread) [supervisor.misc.tasks] Watchdog miss API response from Home Assistant
23-10-07 02:47:06 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-10-07 02:47:06 INFO (MainThread) [supervisor.homeassistant.core] Successfully started Home Assistant 2023.10.1
23-10-07 02:47:06 INFO (SyncWorker_1) [supervisor.docker.manager] Cleanup images: ['ghcr.io/home-assistant/qemuarm-64-homeassistant:2023.10.0']

23-10-07 02:51:45 WARNING (MainThread) [supervisor.addons.options] Option 'alias' does not exist in the schema for Duck DNS (core_duckdns)
23-10-07 02:52:35 INFO (SyncWorker_4) [supervisor.docker.manager] Restarting homeassistant
23-10-07 02:52:46 ERROR (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Home Assistant API!
23-10-07 02:52:46 ERROR (MainThread) [supervisor.misc.tasks] Home Assistant watchdog reanimation failed!
23-10-07 02:52:52 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-10-07 02:52:52 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-10-07 02:52:53 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-10-07 02:52:53 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-10-07 02:52:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/einschmidt/hassio-addons repository
23-10-07 02:52:53 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons
23-10-07 02:52:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-10-07 02:52:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-10-07 02:52:54 INFO (MainThread) [supervisor.store] Loading add-ons from store: 8 all - 0 new - 0 remove
23-10-07 02:52:54 INFO (MainThread) [supervisor.store] Loading add-ons from store: 8 all - 0 new - 0 remove
23-10-07 02:52:58 WARNING (MainThread) [supervisor.addons.options] Option 'alias' does not exist in the schema for Duck DNS (core_duckdns)
23-10-07 02:53:08 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-10-07 02:55:35 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
23-10-07 02:55:35 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
23-10-07 02:55:35 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_ssh
23-10-07 02:55:35 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_ssh

23-10-07 02:56:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-10-07 02:58:02 WARNING (MainThread) [supervisor.addons.options] Option 'alias' does not exist in the schema for Duck DNS (core_duckdns)
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.info] Updating local host information
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.services] Updating service information
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.network] Updating local network information
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-10-07 03:00:02 INFO (MainThread) [supervisor.host.manager] Host information reload completed

23-10-07 03:03:06 WARNING (MainThread) [supervisor.addons.options] Option 'alias' does not exist in the schema for Duck DNS (core_duckdns)
```

**Comment by ludeeus** [comment]
> stderr: 'fatal: unable to access 'https://github.com/einschmidt/hassio-addons/': Could not resolve host: github.com'

You are having DNS issues, check your network settings.

**Comment by SabatoArdolino** [comment]
The network connection is ok. If I try to check the link with "wget or curl" command I receive HTTP200
