### ISSUE TITLE
Unable to Add https://github.com/hassio-addons/repository, Already in the Store

### ISSUE THREAD

**Issue by Muddassar50** [home-assistant/supervisor#4622]
### Describe the issue you are experiencing

Hello,

I am encountering a situation where only "esphome" and official addons are visible in the Home Assistant store. Unfortunately, all the community addons from the repository at https://github.com/hassio-addons/repository are no longer being displayed. It seems like the community addons are being automatically removed. I'm uncertain if this issue arose after an update or due to another reason.

Any insights or assistance in resolving this matter would be highly appreciated.

Best regards,

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Anything in the Supervisor logs that might be useful for us?

```txt
23-10-12 10:28:45 INFO (SyncWorker_1) [supervisor.docker.manager] Starting homeassistant
23-10-12 10:28:46 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-10-12 10:28:47 WARNING (SyncWorker_1) [supervisor.store.data] No repository information exists at /data/addons/git/a0d7b954
23-10-12 10:28:47 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
23-10-12 10:28:47 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
23-10-12 10:28:47 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/5c53de3b repository
23-10-12 10:28:47 ERROR (MainThread) [supervisor.store] https://github.com/hassio-addons/repository is not a valid add-on repository
23-10-12 10:28:47 INFO (MainThread) [supervisor.resolution.module] Create new suggestion execute_remove - store / a0d7b954
23-10-12 10:28:47 INFO (MainThread) [supervisor.resolution.module] Create new issue corrupt_repository - store / a0d7b954
23-10-12 10:28:49 WARNING (SyncWorker_2) [supervisor.store.data] No repository information exists at /data/addons/git/a0d7b954
23-10-12 10:28:49 INFO (MainThread) [supervisor.store] Loading add-ons from store: 32 all - 32 new - 0 remove
23-10-12 10:28:49 INFO (MainThread) [supervisor.addons] Found 6 installed add-ons
23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/influxdb/aarch64 with version 4.5.0
23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/grafana/aarch64 with version 8.1.0
23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-configurator with version 5.6.0
23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-mosquitto with version 6.2.1
23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-ssh with version 9.6.1
23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-samba with version 10.0.2
23-10-12 10:28:50 INFO (MainThread) [supervisor.backups.manager] Found 6 backup files
```

### System Health information

There are currently no repairs available

**Comment by agners** [comment]
Are you still experience this problem?

```
23-10-12 10:28:47 INFO (MainThread) [supervisor.resolution.module] Create new suggestion execute_remove - store / a0d7b954
23-10-12 10:28:47 INFO (MainThread) [supervisor.resolution.module] Create new issue corrupt_repository - store / a0d7b954
```

It seems that Supervisor created issue/suggestions for this problem. Can you check `ha resolution info`?

**Comment by freitas666** [comment]
> ### Describe the issue you are experiencing
> Hello,
> 
> I am encountering a situation where only "esphome" and official addons are visible in the Home Assistant store. Unfortunately, all the community addons from the repository at https://github.com/hassio-addons/repository are no longer being displayed. It seems like the community addons are being automatically removed. I'm uncertain if this issue arose after an update or due to another reason.
> 
> Any insights or assistance in resolving this matter would be highly appreciated.
> 
> Best regards,
> 
> ### What type of installation are you running?
> Home Assistant OS
> 
> ### Which operating system are you running on?
> Home Assistant Operating System
> 
> ### Anything in the Supervisor logs that might be useful for us?
> ```
> 23-10-12 10:28:45 INFO (SyncWorker_1) [supervisor.docker.manager] Starting homeassistant
> 23-10-12 10:28:46 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
> 23-10-12 10:28:47 WARNING (SyncWorker_1) [supervisor.store.data] No repository information exists at /data/addons/git/a0d7b954
> 23-10-12 10:28:47 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
> 23-10-12 10:28:47 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
> 23-10-12 10:28:47 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/5c53de3b repository
> 23-10-12 10:28:47 ERROR (MainThread) [supervisor.store] https://github.com/hassio-addons/repository is not a valid add-on repository
> 23-10-12 10:28:47 INFO (MainThread) [supervisor.resolution.module] Create new suggestion execute_remove - store / a0d7b954
> 23-10-12 10:28:47 INFO (MainThread) [supervisor.resolution.module] Create new issue corrupt_repository - store / a0d7b954
> 23-10-12 10:28:49 WARNING (SyncWorker_2) [supervisor.store.data] No repository information exists at /data/addons/git/a0d7b954
> 23-10-12 10:28:49 INFO (MainThread) [supervisor.store] Loading add-ons from store: 32 all - 32 new - 0 remove
> 23-10-12 10:28:49 INFO (MainThread) [supervisor.addons] Found 6 installed add-ons
> 23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/influxdb/aarch64 with version 4.5.0
> 23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/grafana/aarch64 with version 8.1.0
> 23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-configurator with version 5.6.0
> 23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-mosquitto with version 6.2.1
> 23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-ssh with version 9.6.1
> 23-10-12 10:28:49 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-samba with version 10.0.2
> 23-10-12 10:28:50 INFO (MainThread) [supervisor.backups.manager] Found 6 backup files
> ```
> 
> ### System Health information
> There are currently no repairs available
> 
> ### Supervisor diagnostics
> _No response_
> 
> ### Additional information
> _No response_

Do u solve?

**Comment by dbarnett** [comment]
Hi, I'm seeing similar on a fresh install. I do _not_ see any repairs available. In Discord [someone suggested](https://discord.com/channels/330944238910963714/672220642099200000/1001907771463176303) manually deleting the repo from the config via developer SSH mode and rebooting (back in Feb). Is that advice still relevant?

**Comment by agners** [comment]
@dbarnett do you see any hints in the Supervisor logs? Ideally check the logs after a reboot, when Supervisor first starts.

**Comment by dbarnett** [comment]
Nothing in the logs… regardless of why it didn't load, would it be a reasonable feature request for it to show a notification and/or failure messages in Add-on Store UI when it can't load the main repo?

**Comment by dbarnett** [comment]
I eventually got unstuck by trying to add a munged duplicate entry "https://github.com/hassio-addons/./repository" and then troubleshooting from there.

In my case it for some reason couldn't resolve github.com, I did some stuff with my router, and eventually got it all unstuck.

**Comment by agners** [comment]
> Nothing in the logs… regardless of why it didn't load, would it be a reasonable feature request for it to show a notification and/or failure messages in Add-on Store UI when it can't load the main repo?

> In my case it for some reason couldn't resolve github.com, I did some stuff with my router, and eventually got it all unstuck.

There should have been something in the Supervisor logs at least, especially when it was a connectivity issue.

Glad you were able to resolve it :+1:
