### ISSUE TITLE
Received empty response for users

### ISSUE THREAD

**Issue by joostlek** [home-assistant/supervisor#4624]
### Describe the issue you are experiencing

While debugging https://github.com/home-assistant/core/issues/101893, Frenck got the log in his supervisor logs saying `23-10-13 00:12:29 WARNING (MainThread) [supervisor.jobs] Removing incomplete job home_assistant_get_users from job manager`. When I checked my logs I got
```
23-10-13 00:28:52 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 274, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 458, in get_users
    return [
           ^
TypeError: 'NoneType' object is not iterable
```

This is referring to https://github.com/home-assistant/supervisor/blob/a70f81aa0189bd7ccfc49dc7ff55e3bd3484b39b/supervisor/homeassistant/module.py#L488-L501

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

I actually only booted the system. Could be that the system is not ready (not sure if that also was the case for Frenck, but it does prove my system isn't the only one)

### Anything in the Supervisor logs that might be useful for us?

```txt
See above :)
```

## System Information

version | core-2023.10.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | UTC
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4986
Installed Version | 1.33.0
Stage | running
Available Repositories | 1310
Downloaded Repositories | 6
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 21, 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-11.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.8 GB
disk_used | 14.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Mosquitto broker (6.3.1), Zigbee2MQTT (1.33.1-1), Terminal & SSH (9.7.1), Node-RED (14.6.1), Samba share (10.0.2), InfluxDB (4.7.0), Grafana (9.0.3), AdGuard Home (4.8.15), ESPHome (2023.9.3), Whisper (1.0.0), Piper (1.4.0), Advanced SSH & Web Terminal (15.0.8)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 2
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 4, 2023 at 18:20
-- | --
current_recorder_run | October 13, 2023 at 01:15
estimated_db_size | 271.26 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by modem-man-gmx** [comment]
Exactly the same here with Raspi3. Nothing else to add.
Noticed it the 1st time after trying 2023.10.2 update, which apparently not succeeded (still shown as outstanding). System is unstable since, resulting in unresponsiveness for hours and CPU going to 70°C.

**Comment by modem-man-gmx** [comment]
Arg, got it!
just going to /config/helpers,
hit: + CREATE HELPER
select: {} Template
select: Template for Sensor
fill in:
  Name: BathtubWater
  Template: "{{ state_attr('water_heater.vicare_water', 'current_temperature') | replace('“', '') | float }}"
  Unit: °C
  DeviceClass: Temperature
  StateClass: Measurement
press "Send"
done.

**Comment by joostlek** [comment]
Euh what does this have to do with this issue?

**Comment by modem-man-gmx** [comment]
sorry, pasted into wrong session, removed it.

**Comment by modem-man-gmx** [comment]
regarding this topic:
I managed to update to HA Core Update 2023.10.3 in the meantime. My device did not restart after the update, so I pulled the plug after 3 hours or so. Then all came up fine here and CPU is below 50°C since more than 2 hours.
Perhaps I had a crashed update? Couldn't swear the error log has any relation with my other observations.

**Comment by CH1PSET1** [comment]
Exactly the same problem. I don’t know how critical it is, it appeared after the last update to 10.3
