### ISSUE TITLE
Supervisor logs warnings for add-on options that have been removed

### ISSUE THREAD

**Issue by shypike** [home-assistant/supervisor#4644]
### Describe the issue you are experiencing

I've upgraded the OneDrive Backup add-on (https://github.com/lavinir/hassio-onedrive-backup).
The latest versions have moved the options from the standard option page to its own ingress Web-UI.
The Supervisor still remembers the now obsolete options and complains about them.
I wonder what the purpose of these warnings is because they provide no useful information and it doesn't seem that the end-user or the add-on author have any means to address the problem.
I've been trying to help the author, but I cannot even find out where the Supervisor stores its add-on configuration data.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Restart the OneDrive Backup add-on
2. Inspect the Supervisor log

### Anything in the Supervisor logs that might be useful for us?

```txt
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'local_backup_num_to_keep' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)

And many more of these.
```

### System Health information

There are currently no repairs available

### Supervisor diagnostics

[config_entry-hassio-d13d6f1ec199024808a22a0f65ee035c.json.txt](https://github.com/home-assistant/supervisor/files/13063368/config_entry-hassio-d13d6f1ec199024808a22a0f65ee035c.json.txt)

**Comment by mdegat01** [comment]
> I wonder what the purpose of these warnings is because they provide no useful information and it doesn't seem that the end-user or the add-on author have any means to address the problem.

You can address these problems. Go to [Settings -> Addons -> OneDrive Backup](https://my.home-assistant.io/redirect/supervisor_addon/?addon=de91e161_hassio_onedrive_backup&repository_url=https%3A%2F%2Fgithub.com%2Flavinir%2Fhassio-onedrive-backup). Then go to the configuration tab. Switch to YAML mode at the top and remove any deprecated options.

**Comment by shypike** [comment]
Makes perfect sense and the YAML "trick" works.
My remaining issue is that this info is very hard to find for the less experienced :)
Thank you for your clear answer; I'll notify the author too.
Please, close the issue.
