### ISSUE TITLE
Network storage: Re-establishing the connection without restarting HomeAssistant

### ISSUE THREAD

**Issue by j3mu5** [home-assistant/supervisor#4662]
### Describe the issue you are experiencing

Hello everyone,

I experience the possibility of integrating network storage as very stable. However, there is a problem that arises from my user behaviour. At night, I shut down my network storage to save energy. HomeAssistant understandably brings up a warning about the loss of connection. Now I would like to automatically establish the connection from HomeAssistant to the network storage after it has booted up, without having to restart HomeAssistant. Currently, it looks to me like establishing the connection after it has been lost requires HomeAssistant to be restarted.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Add network storage in HomeAssistant
2. Shut down network storage
3. Start network storage
4. To reconnect HomeAssistant to the network storage, HomeAssistant must be restarted.

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

## System Information

version | core-2023.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.33.0
Stage | running
Available Repositories | 1330
Downloaded Repositories | 26
HACS Data | ok

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 44

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 9. Juni 2024 um 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-13.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.1
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 468.7 GB
disk_used | 62.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Zigbee2MQTT (1.33.1-1), Terminal & SSH (9.7.1), Mosquitto broker (6.3.1), AdGuard Home (4.8.17), Piper (1.4.0), RPC Shutdown (2.4), Samba Backup (5.2.0), Samba share (10.0.2), SMA Energy Meter (2021.9.2), SQLite Web (3.10.0), Studio Code Server (5.13.0), TasmoAdmin (0.25.1), Whisper (1.0.0), Ring-MQTT with Video Streaming (5.6.3), HDD Tools (1.1.0), Advanced SSH & Web Terminal (15.1.0), Frigate (0.12.1), Crowdsec (1.5.4), ESPHome (2023.10.5), openWakeWord (1.8.2), porcupine1 (1.0.3), Grocy (0.20.1), EMQX (0.2.12), Vaultwarden (Bitwarden) (0.20.1), Duck DNS (1.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 9
views | 69
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12. Oktober 2023 um 22:06
-- | --
current_recorder_run | 1. November 2023 um 14:56
estimated_db_size | 3632.52 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by jmealo** [comment]
These are all related I think: #4577 #4357 #4358

**Comment by jmealo** [comment]
:+1: Still an issue

**Comment by macbih** [comment]
> At night, I shut down my network storage to save energy.

That is exactly my use case, too! I would like to use the NAS for backup purposes and it is not needed to run it 24/7. Every morning, HA shows a warning that the connection to the NAS has been lost which has to be acknowledged by the user. In addition, HA has to be restarted to re-establish the connection again.

I would love to have a solution that can "heal" the connection loss once the NAS is available again. Of course I would prefer an automatic solution but if there is a possibility to run a scheduled automation to do so, I would be satisfied!

**Comment by agners** [comment]
> Architecture discussion on a proposed fixed to the Network Storage issues:
> [home-assistant/architecture#1033](https://github.com/home-assistant/architecture/discussions/1033)

The related issue in the Supervisor is at https://github.com/home-assistant/supervisor/issues/4856.

That particular issue is fixed with PR https://github.com/home-assistant/supervisor/pull/4872, so am marking this as fixed too.
