### ISSUE TITLE
Supervisor - ERROR (MainThread)

### ISSUE THREAD

**Issue by matomatusov** [home-assistant/supervisor#4668]
### Describe the issue you are experiencing

Hi,
this error started to appear in supervisor. HA is virtual machine Synology.
The error happened after the update Home Assistant core 2023.11.1
Studio code server cannot find the Home Assistant files.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

I think it came up with 
Home Assistant update Core-2023.11.1

### Anything in the Supervisor logs that might be useful for us?

```txt
23-11-04 22:13:21 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.2:1337//index.c708214f.css: Cannot write to closing transport
23-11-04 22:13:22 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.5:1337/public/build/226.6820fd439963e5465b6a.js: Cannot write to closing transport
23-11-04 22:13:23 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.5:1337/public/build/1486.9f5c58b5413b0650af69.js: Cannot write to closing transport
23-11-04 22:13:23 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.5:1337/public/build/app.5134ec4fafe46667d3cf.js: Cannot write to closing transport
23-11-04 23:23:33 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/config: Cannot connect to host 172.30.32.1:8123 ssl:False [Connect call failed ('172.30.32.1', 8123)]
```

![image](https://github.com/home-assistant/supervisor/assets/129114957/cb5d7d66-349b-4ecd-a638-14e2ec122d42)

![image](https://github.com/home-assistant/supervisor/assets/129114957/7356eeb7-e9fc-43a6-9c52-19ea32854bd7)

### System Health information

Version | core-2023.11.1
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.6
Operating System Family | Linux
Operating System Version | 6.1.59
CPU Architecture | x86_64
Timezone | Europe/Prague
Configuration Directory | /config

**Comment by agners** [comment]
This errors are related to the VS Code add-on, please report this at https://github.com/hassio-addons/addon-vscode/issues.
