### ISSUE TITLE
Unable to update from Yellow 2023.11.0 to 2023.11.1 - "No such image"

### ISSUE THREAD

**Issue by mrtnkhl** [home-assistant/supervisor#4669]
### Describe the issue you are experiencing

Updating a Yellow from 2023.11.0 to 2023.11.1 fails with image not being found

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Go to Settings
2. Click to update to 2023.11.1, activate backup option
3. Wait and see the update fail
4. Check logs, find logs listed below

### Anything in the Supervisor logs that might be useful for us?

```txt
23-11-05 10:53:56 INFO (MainThread) [supervisor.backups.manager] Found 60 backup files
23-11-05 10:53:57 INFO (MainThread) [supervisor.backups.manager] Found 60 backup files
23-11-05 10:54:04 INFO (MainThread) [supervisor.backups.manager] Backup 496c53b2 starting stage addon_repositories
23-11-05 10:54:04 INFO (MainThread) [supervisor.backups.manager] Backup 496c53b2 starting stage docker_config
23-11-05 10:54:04 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 496c53b2
23-11-05 10:54:04 INFO (MainThread) [supervisor.backups.manager] Backup 496c53b2 starting stage home_assistant
23-11-05 10:54:04 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
23-11-05 10:58:25 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
23-11-05 10:58:25 INFO (MainThread) [supervisor.backups.manager] Backup 496c53b2 starting stage finishing_file
23-11-05 10:58:27 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 496c53b2 completed
23-11-05 10:58:27 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2023.11.1
23-11-05 10:58:27 INFO (MainThread) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/yellow-homeassistant:2023.11.0 to ghcr.io/home-assistant/yellow-homeassistant:2023.11.1
23-11-05 10:58:27 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/yellow-homeassistant with tag 2023.11.1.
23-11-05 11:00:47 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/yellow-homeassistant:2023.11.1: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/yellow-homeassistant:2023.11.1/json: Not Found ("No such image: ghcr.io/home-assistant/yellow-homeassistant:2023.11.1")
23-11-05 11:00:47 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed
```

### System Health information

There are currently no repairs available

**Comment by agners** [comment]
Is this problem reproducible?

**Comment by mrtnkhl** [comment]
Tried again today, works now:

23-11-06 14:34:10 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance

23-11-06 14:41:32 INFO (MainThread) [supervisor.backups.manager] Backup 1fec074a starting stage addon_repositories
23-11-06 14:41:32 INFO (MainThread) [supervisor.backups.manager] Backup 1fec074a starting stage docker_config
23-11-06 14:41:32 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 1fec074a
23-11-06 14:41:32 INFO (MainThread) [supervisor.backups.manager] Backup 1fec074a starting stage home_assistant
23-11-06 14:41:32 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
23-11-06 14:45:44 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'watermeter'
23-11-06 14:45:44 INFO (MainThread) [supervisor.auth] Successful login for 'watermeter'
23-11-06 14:45:46 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
23-11-06 14:45:46 INFO (MainThread) [supervisor.backups.manager] Backup 1fec074a starting stage finishing_file
23-11-06 14:45:47 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 1fec074a completed
23-11-06 14:45:47 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2023.11.1
23-11-06 14:45:47 INFO (MainThread) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/yellow-homeassistant:2023.11.0 to ghcr.io/home-assistant/yellow-homeassistant:2023.11.1
23-11-06 14:45:47 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/yellow-homeassistant with tag 2023.11.1.

23-11-06 14:50:26 INFO (SyncWorker_0) [supervisor.docker.manager] Stopping homeassistant application
23-11-06 14:50:39 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning homeassistant application
23-11-06 14:50:39 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse
23-11-06 14:50:39 INFO (MainThread) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/yellow-homeassistant with version 2023.11.1
23-11-06 14:50:39 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-11-06 14:50:45 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
23-11-06 14:50:45 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-11-06 14:50:48 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-11-06 14:50:48 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-11-06 14:50:48 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-11-06 14:50:48 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-11-06 14:50:50 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'watermeter'
23-11-06 14:50:50 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
23-11-06 14:50:50 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-11-06 14:50:50 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-11-06 14:50:57 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt'
23-11-06 14:50:59 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
23-11-06 14:51:22 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-11-06 14:51:22 INFO (MainThread) [supervisor.homeassistant.core] Successfully started Home Assistant 2023.11.1
23-11-06 14:51:22 INFO (SyncWorker_1) [supervisor.docker.manager] Cleanup images: ['ghcr.io/home-assistant/yellow-homeassistant:2023.11.0']
