### ISSUE TITLE
Upload backup fails with "unsupported file format" under Firefox for Windows 

### ISSUE THREAD

**Issue by sdellysse** [home-assistant/supervisor#4712]
### Describe the issue you are experiencing

I am not able to restore a backup made by HomeAssistant on a new installation.

Clicking “Alternatively you can restore from a previous backup” and selecting a previous tar backup always results in a pop-up stating “Unsupported file format - Please choose a Home Assistant backup file (.tar)”.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Onboard using Firefox on windows
2. attempt to upload backup tarball
3. get error; do the same thing in edge and it works

### Anything in the Supervisor logs that might be useful for us?

```txt
n/a
```

### System Health information

n/a

### Supervisor diagnostics

n/a

### Additional information

This is a dupe of a closed issue https://github.com/home-assistant/supervisor/issues/3639

I'm filing this because it's still an issue

**Comment by agners** [comment]
Hm, I wonder if this is related to: https://github.com/home-assistant/frontend/issues/7258

Is the error appearing exactly after 30s?

**Comment by agners** [comment]
I am closing this one as duplicate and reopen #3639 as it has more information.
