### ISSUE TITLE
Can't update to Supervisor 2023.11.6

### ISSUE THREAD

**Issue by Daz42** [home-assistant/supervisor#4742]
### Describe the issue you are experiencing

Unable to update to Supervisor 2023.11.6.

DNS is solid and have tried 8.8.8.8, 8.8.4.4 and the ISP's DNS servers.

Any ideas as this is stopping me from updating or installing any new components?

D.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Rebooted
2. Tried other DNS servers
3. Tried https://ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6/ (working)

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:11:38 (4 occurrences)
Last logged: 12:19:56

[547227717312] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6")
[546803960640] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 258, in async_install
    await async_update_supervisor(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 260, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6")
```

### System Health information

There are currently no repairs available

### Supervisor diagnostics

[config_entry-hassio-2577e8451ff1a228dbffcad93a83c236.json.txt](https://github.com/home-assistant/supervisor/files/13560168/config_entry-hassio-2577e8451ff1a228dbffcad93a83c236.json.txt)

**Comment by DrDuc** [comment]
Ive got a similar error but different log entries....
HA System is "unhealthy" ; restore is blocked ; manual HA supervisoe update fails ... I run out of clues :(

SUPERVISOR LOGS: ------------------>
23-12-05 13:46:46 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-mosquitto with version 6.4.0
23-12-05 13:46:46 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/esphome/esphome-hassio with version 2023.11.6
23-12-05 13:46:46 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/influxdb/aarch64 with version 4.8.0
23-12-05 13:46:46 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/grafana/aarch64 with version 9.1.1
23-12-05 13:46:46 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-configurator with version 5.7.0
23-12-05 13:46:46 INFO (MainThread) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-ssh with version 9.8.1
23-12-05 13:46:46 INFO (MainThread) [supervisor.backups.manager] Found 6 backup files
23-12-05 13:46:46 INFO (MainThread) [supervisor.discovery] Loaded 2 messages
23-12-05 13:46:46 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
23-12-05 13:46:46 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state setup
23-12-05 13:46:46 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-12-05 13:46:46 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state setup
23-12-05 13:46:46 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-12-05 13:46:46 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - setup
23-12-05 13:46:46 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state setup
23-12-05 13:46:46 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-12-05 13:46:46 INFO (MainThread) [__main__] Running Supervisor
23-12-05 13:46:46 INFO (MainThread) [supervisor.os.manager] Rauc: A - marked slot kernel.0 as good
23-12-05 13:46:46 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor_stable.txt
23-12-05 13:46:46 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
23-12-05 13:46:47 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2023.11.6
23-12-05 13:46:47 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-supervisor with tag 2023.11.6.
23-12-05 13:46:48 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
23-12-05 13:46:48 INFO (MainThread) [supervisor.resolution.module] Create new issue update_failed - supervisor / None
23-12-05 13:46:48 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
23-12-05 13:46:48 CRITICAL (MainThread) [supervisor.core] Can't update Supervisor! This will break some Add-ons or affect future versions of Home Assistant!
23-12-05 13:46:48 INFO (MainThread) [supervisor.addons] Phase 'initialize' starting 0 add-ons
23-12-05 13:46:49 INFO (MainThread) [supervisor.addons] Phase 'system' starting 1 add-ons
23-12-05 13:46:49 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_core_mosquitto application
23-12-05 13:46:55 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.4.0
23-12-05 13:47:00 INFO (MainThread) [supervisor.addons] Phase 'services' starting 2 add-ons
.......
23-12-05 13:47:20 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-configurator with version 5.7.0
23-12-05 13:47:23 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state startup
23-12-05 13:47:23 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-12-05 13:47:25 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqu'
23-12-05 13:47:29 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqu'
23-12-05 13:47:31 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
23-12-05 13:47:32 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
23-12-05 13:47:32 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
23-12-05 13:47:33 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-12-05 13:47:33 WARNING (MainThread) [supervisor.jobs] 'StoreManager.reload' blocked from execution, supervisor needs to be updated first
23-12-05 13:47:36 INFO (MainThread) [supervisor.api.middleware.security] /dns/info access from a0d7b954_influxdb
23-12-05 13:47:50 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
23-12-05 13:47:50 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
23-12-05 13:47:50 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_ssh
23-12-05 13:47:50 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_ssh
........
23-12-05 13:53:13 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
23-12-05 13:53:14 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2023.11.6
23-12-05 13:53:14 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-supervisor with tag 2023.11.6.
23-12-05 13:53:18 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
23-12-05 13:53:18 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.11.6/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
23-12-05 13:53:52 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from core_ssh
23-12-05 14:01:53 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqu'
23-12-05 14:01:54 INFO (MainThread) [supervisor.auth] Successful login for 'mqu'
23-12-05 14:03:52 WARNING (MainThread) [supervisor.jobs] 'OSManager.update' blocked from execution, supervisor needs to be updated first
23-12-05 14:04:02 INFO (MainThread) [supervisor.backups.manager] Found 6 backup files
23-12-05 14:04:02 INFO (MainThread) [supervisor.backups.manager] Found 6 backup files
23-12-05 14:04:35 WARNING (MainThread) [supervisor.jobs] 'BackupManager.do_restore_partial' blocked from execution, system is not healthy - supervisor
23-12-05 14:04:51 WARNING (MainThread) [supervisor.jobs] 'BackupManager.do_restore_full' blocked from execution, system is not healthy - supervisor
23-12-05 14:04:55 WARNING (MainThread) [supervisor.jobs] 'BackupManager.do_restore_full' blocked from execution, system is not healthy - supervisor
23-12-05 14:17:04 WARNING (MainThread) [supervisor.jobs] 'OSManager.update' blocked from execution, supervisor needs to be updated first
23-12-05 14:17:22 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-12-05 14:22:34 INFO (MainThread) [supervisor.host.network] Updating local network information
23-12-05 14:23:06 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqu'

**Comment by agners** [comment]
This seems like a duplicate of #4709, and the case described in #4738.

Unfortunately, this seems to be caused by data corruption in the Docker storage backend :cry: The safest way out is to make a full backup, download it and reinstall your unit using HAOS 11.2. See also https://github.com/home-assistant/supervisor/issues/4738#issuecomment-1834627523.

**Comment by Daz42** [comment]
Thanks Agners,

So to be clear, I am running a full backup (I have an SD and SSD). Nuke the SD and SSD, install 11.2 then restore the backup?

**Comment by agners** [comment]
Correct. Don't forget to download the backup :smile:

**Comment by Daz42** [comment]
Will do, LOL!
