### ISSUE TITLE
Supervisor update failed due to DNS errors

### ISSUE THREAD

**Issue by talissonsouza** [home-assistant/supervisor#4768]
### Describe the issue you are experiencing

I managed to update the supervisor

The problem I found was DNS

I fixed it by setting the static IP

dns field, I put

1.1.1.1, 8.8.8.8

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...
1

### Anything in the Supervisor logs that might be useful for us?

```txt
1
```

### System Health information

1

### Supervisor diagnostics

1

### Additional information

1

**Comment by agners** [comment]
These two servers are fallback DNS server by default in HAOS. Is maybe your DNS provider blocking certain servers?
