### ISSUE TITLE
when restoring a backup from onboarding, the page "restore in progress" sticks forever, even if the restore process is complete

### ISSUE THREAD

**Issue by Baxxy13** [home-assistant/supervisor#4772]
### Describe the issue you are experiencing

Doing some backup/restore tests today for #4287 and experienced a problem with the page "restore in progress". 
This page sticks forever, even if the restore process is complete. Must hit F5 to reload and get into ha.
![HA_restore_in_progress_sticks_forever](https://github.com/home-assistant/supervisor/assets/54898249/e38a1a47-bb8b-45fd-b5a2-3b1afb28a6c1)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. set up a fresh system and upload a full backup at onboarding
2. wait "forever" that "upload in progress" completes
3. after enough waiting hit F5 to reload and get into ha
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Dec 14 21:09:24 homeassistant hassio_supervisor[559]: 23-12-14 22:09:24 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to NOT_RUNNING
Dec 14 21:09:24 homeassistant hassio_supervisor[559]: 23-12-14 22:09:24 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
Dec 14 21:09:30 homeassistant hassio_supervisor[559]: 23-12-14 22:09:30 INFO (MainThread) [supervisor.store] Loading add-ons from store: 74 all - 0 new - 0 remove
Dec 14 21:09:30 homeassistant hassio_supervisor[559]: 23-12-14 22:09:30 INFO (MainThread) [supervisor.store] Loading add-ons from store: 74 all - 0 new - 0 remove
Dec 14 21:10:19 homeassistant hassio_supervisor[559]: 23-12-14 22:10:19 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
Dec 14 21:10:19 homeassistant hassio_supervisor[559]: 23-12-14 22:10:19 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to RUNNING
Dec 14 21:10:19 homeassistant hassio_supervisor[559]: 23-12-14 22:10:19 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
Dec 14 21:10:19 homeassistant hassio_supervisor[559]: 23-12-14 22:10:19 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
Dec 14 21:10:19 homeassistant hassio_supervisor[559]: 23-12-14 22:10:19 INFO (MainThread) [supervisor.backups.manager] Full-Restore 5cabea88 done
Dec 14 21:10:20 homeassistant hassio_supervisor[559]: 23-12-14 22:10:20 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

### System Health information

not accessible in this stage

### Supervisor diagnostics

not accessible in this stage

### Additional information

I can see in the logs that restore is done.
`Dec 14 21:10:19 homeassistant hassio_supervisor[559]: 23-12-14 22:10:19 INFO (MainThread) [supervisor.backups.manager] Full-Restore 5cabea88 done`
Waited around an hour and then pressed F5 to refresh the page and get into HA.

**Comment by Baxxy13** [comment]
The problem persists with a fresh installation of ha-os 11.4.

**Comment by codyc1515** [comment]
This should be [fixed in the latest frontend](https://github.com/home-assistant/frontend/pull/19389).

**Comment by codyc1515** [comment]
This should be fixed now.

**Comment by Baxxy13** [comment]
I tested this today with a fresh virtual machine and imported a backup (700MB) of my testsystem.
After the restore process was completed, I was logged into HA.
So this works now and i close this issue.
Thanks!
