### ISSUE TITLE
After the update today to 2023.12, the modebusproxy addon no longer works

### ISSUE THREAD

**Issue by Vaszago** [home-assistant/supervisor#4782]
### Describe the issue you are experiencing

The addon can no longer be installed and this error message appears.

23-12-19 14:38:35 INFO (MainThread) [supervisor.docker.addon] Starting build for 81ab01ea/amd64-addon-modbus_proxy:1.0.15
23-12-19 14:38:38 ERROR (MainThread) [supervisor.docker.addon] Can't build 81ab01ea/amd64-addon-modbus_proxy:1.0.15: The command '/bin/ash -o pipefail -c pip install modbus-proxy' returned a non-zero code: 1
23-12-19 14:38:38 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/16 : ARG BUILD_FROM

Step 2/16 : FROM $BUILD_FROM

 ---> 75c2208b90c6

Step 3/16 : RUN   apk add --no-cache     python3 py3-pip py3-yaml

 ---> Using cache

 ---> 00cb6e652b92

Step 4/16 : RUN pip install modbus-proxy

 ---> Running in d08bd459b055

error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Removing intermediate container d08bd459b055

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
---> Running in d08bd459b055

[91merror: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
[0m
Removing intermediate container d08bd459b055
[0m
[32m23-12-19 14:39:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-12-19 14:39:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-12-19 14:39:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-12-19 14:39:53 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/Akulatraxas/ha-modbusproxy/ repository[0m
[32m23-12-19 14:39:54 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-12-19 14:39:55 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove[0m
[32m23-12-19 14:39:55 INFO (MainThread) [supervisor.store] Loading add-ons from store: 73 all - 0 new - 0 remove[0m
[33m23-12-19 14:39:55 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m23-12-19 14:39:55 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m23-12-19 14:44:54 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m23-12-19 14:44:54 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m23-12-19 14:49:54 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m23-12-19 14:49:54 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[32m23-12-19 14:53:26 INFO (MainThread) [supervisor.docker.addon] Starting build for 81ab01ea/amd64-addon-modbus_proxy:1.0.15[0m
[31m23-12-19 14:53:30 ERROR (MainThread) [supervisor.docker.addon] Can't build 81ab01ea/amd64-addon-modbus_proxy:1.0.15: The command '/bin/ash -o pipefail -c pip install modbus-proxy' returned a non-zero code: 1[0m
[31m23-12-19 14:53:30 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/16 : ARG BUILD_FROM


Step 2/16 : FROM $BUILD_FROM


 ---> 75c2208b90c6

Step 3/16 : RUN   apk add --no-cache     python3 py3-pip py3-yaml


 ---> Using cache

 ---> 00cb6e652b92

Step 4/16 : RUN pip install modbus-proxy


 ---> Running in 6867c79a7da4

[91merror: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
[0m
Removing intermediate container 6867c79a7da4
[0m
```

## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4004
Installed Version | 1.33.0
Stage | running
Available Repositories | 1425
Downloaded Repositories | 38

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 125.3 GB
disk_used | 34.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Node-RED (16.0.2), Grafana (9.1.1), AdGuard Home (5.0.1), MariaDB (2.6.1), File editor (5.7.0), Matter Server (5.0.1), Mosquitto broker (6.4.0), Terminal & SSH (9.8.1), InfluxDB (4.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 25
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9. Dezember 2023 um 08:41
-- | --
current_recorder_run | 19. Dezember 2023 um 14:31
estimated_db_size | 2948.85 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

[config_entry-hassio-80fae30518f370c8a3f8210c7a35c3ef.json.txt](https://github.com/home-assistant/supervisor/files/13716420/config_entry-hassio-80fae30518f370c8a3f8210c7a35c3ef.json.txt)

**Comment by agners** [comment]
The error is not an issue which got introduced by Supervisor.

The problem is likely that the base image of the container now disallows using pip without venv. You'll have to report this to the modbus proxy authors (I guess at https://github.com/Akulatraxas/ha-modbusproxy/issues).

**Comment by Vaszago** [comment]
Thanks for the tip. I posted it once in the repository. But since the developer hasn't been working for a long time, I don't have much hope that something will happen.

It would probably be a piece of cake for you to fix this version so that it can run again.

**Comment by agners** [comment]
The fix probably should include `python3 -m venv venv`, and then install and run it in that venv.

This fork seems more active, but I think that particular issue is not fixed either, but maybe the author is still interested in fixing it :thinking: 
https://github.com/jgarridoalcazar/ha-modbusproxy

**Comment by Akulatraxas** [comment]
Fixed the issue by switching to run in a venv
https://github.com/Akulatraxas/ha-modbusproxy/issues/20
