### ISSUE TITLE
Successful retry is not an error

### ISSUE THREAD

**Issue by AlexanderLanin** [home-assistant/supervisor#4787]
### Describe the issue you are experiencing

Installation "fails", although retry is successful.
As stated in #4783 retry is not fatal and there is nothing the user can/shall do about it.

Unless I'm very confused (I went through the install ~7 times today), the installation "fails" with that error (image 1).
And maybe I aborted too early in my previous attempts.
But when I simply ignore that error and reload after some more minutes the installation was successful.

---

![20231221_191742000_iOS](https://github.com/home-assistant/supervisor/assets/5074553/0a3210ea-1292-40e6-9955-f6741c70c899)

And some minutes later:

![20231221_193033000_iOS](https://github.com/home-assistant/supervisor/assets/5074553/dec4760b-dd45-441c-937e-7ba32efd8505)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Install in VirtualBox according to https://www.home-assistant.io/installation/linux#create-the-virtual-machine

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### System Health information

-

**Comment by agners** [comment]
Thanks for reporting the issue! The error detection on the landing page (that is the page your screenshot is showing, it is a minimal web server which shows something while the system downloads the latest version of Home Assistant Core) is currently rather rudimentary: We just parse the log for errors. Extending/improving the error reporting is on our todo list for next year.
