### ISSUE TITLE
Backups - change message, when a backup will be created

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/supervisor#4794]
### Describe the issue you are experiencing

I am not sure, if this is a CORE or a FRONTENT topic, but backups are part of Supervisor, afaik...

if you create a backup - and close the dialog shortly after executing the backup, you don't see that a backup job is currently running.
When you try to "restart" the backup, you only get an information, that tells you:

<img width="383" alt="image" src="https://github.com/home-assistant/supervisor/assets/26391061/c541a96f-2355-4184-b08e-8344e789b59f">

This message should be more meaningfull, and show the user, that a backup job is already running.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. start a backup task
2. close the dialog after the confirmation dialog
3. try to start another backup
...

### Anything in the Supervisor logs that might be useful for us?

```txt
no / maybe UI related
```

### System Health information

healthy

**Comment by codyc1515** [comment]
I'm not sure if there are other reasons that the system would be in freeze other than creating or restoring a backup. If there aren't, then the freezing message could certainly be rephrased.
