### ISSUE TITLE
Translations for add-ons ?

### ISSUE THREAD

**Issue by mat4444** [home-assistant/supervisor#4797]
### Describe the issue you are experiencing

Add-ons are a big part of Home Assistant, but currently, almost nothing is translated.
This isn't a criticism; I'm just curious about the reasons behind it. 
I noticed that most of the add-ons have a translation folder with only an `en.yaml` file. Is it possible to create additional language files to translate them ?
Translation is probably my main way of contributing to HA, so I am looking for a way to help.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Check System-->Add-ons: no translation

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### System Health information

N/A

**Comment by frenck** [comment]
The plan is to move them to Lokalise at some point. This has been on a "todo"-list for ages.
Someday...
