### ISSUE TITLE
Could not resolve host: fim.psoklahoma.com

### ISSUE THREAD

**Issue by tronikos** [home-assistant/supervisor#4798]
### Describe the issue you are experiencing

See https://github.com/home-assistant/core/issues/106989#issuecomment-1877662826
The new AEP utilities in the Opower integration don't work.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. `docker exec -it $(docker ps -f name=homeassistant -q) bash`
2. `curl -I fim.psoklahoma.com`
3. `curl: (6) Could not resolve host: fim.psoklahoma.com`

The same curl command outside the homeassistant docker works fine.

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1367
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.6 GB
disk_used | 13.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS UI (3.0.2), AdGuard Home (5.0.1), Advanced SSH & Web Terminal (17.0.1), Home Assistant Google Drive Backup (0.112.1), Samba share (12.2.0), File editor (5.7.0), Homebridge (0.1.7), ESPHome (2023.12.5), AirCast (4.0.1), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.6.0), Castsponsorskip (0.6.1), OpenSpeedTest (v2.0.3), Mosquitto broker (6.4.0), Whisper (1.0.0), MQTT Explorer (browser-1.0.3), SQLite Web (4.0.0), Music Assistant BETA (2.0.0b80), Piper (1.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 29, 2023 at 2:54 AM
-- | --
current_recorder_run | January 2, 2024 at 10:02 PM
estimated_db_size | 487.89 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
used_requests | 5
rooftop_site_count | 2

</details>

<details><summary>Sonoff</summary>

version | 3.5.3 (a8c6d45)
-- | --
cloud_online | 0 / 1
local_online | 1 / 1

</details>

**Comment by codyc1515** [comment]
This appears to be solved. If it is, please close this issue.
