### ISSUE TITLE
Cannot update ha-supervisor - image doesn't exists

### ISSUE THREAD

**Issue by Krandelbord** [home-assistant/supervisor#4823]
### Describe the issue you are experiencing

Automatic update of supervisor failed. 
So I tryied to update it from ssh-console.
When I do: 
```
ha supervisor update
```
I get
```
No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.12.1
```

How can I resolve that

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.ha supervisor update

### Anything in the Supervisor logs that might be useful for us?

```txt
[547643779008] Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.12.1: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.12.1/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2023.12.1")
10:06:20 – (ERROR) Home Assistant WebSocket API - message first occurred at 10:04:17 and shows up 3 times
```

### System Health information

System is currently unhealthy because an attempt to update Supervisor to the latest version has failed. Use the link to learn more and how to fix this.

![image](https://github.com/home-assistant/supervisor/assets/8105637/e76b23a0-2ca7-40bd-9b02-6af8e107384b)

**Comment by gastonmorixe** [comment]
I had a similar issue and it was related to my server's DNS not working properly. Even a ping to google.com was not resolving.

In my case it was an issue related with NextDNS conflicting with systemd-resolved on the same port (53), this solved it:

```
sudo systemctl disable systemd-resolved.service
sudo systemctl stop systemd-resolved.service
sudo nextdns restart
```

**Comment by Krandelbord** [comment]
Network in general works correctly. I can ping any service, I can fetch data using http from same ssh console.

**Comment by andrey170183** [comment]
same problem, but on debian GNU/linux 11
