### ISSUE TITLE
Trying to update multiple areas (such as HA Core & an add-on) at the same time with default checkbox for backup ticked generates non-user friendly toast exception

### ISSUE THREAD

**Issue by codyc1515** [home-assistant/supervisor#4867]
### Describe the issue you are experiencing

Trying to update an add-on, Scrypted (which had the backup tickbox enabled by default), received the following toast exception:

> "Failed to call service update/install. Error updating Scrypted: 'BackupManager.do_backup_partial' blocked from execution, system is not running - freeze"

This happened because I already had an update for HA Core running (which also had the backup tickbox enabled by default). The resulting message was a little confusing for me.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Two updates available - one for core and one for an add-on
2. Hit update on core (leave default tickbox enabled for backup)
3. Hit update on add-on (leave default tickbox enabled for backup)

### Anything in the Supervisor logs that might be useful for us?

```txt
24-02-02 08:53:38 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json
24-02-02 08:53:52 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
24-02-02 09:00:22 INFO (MainThread) [supervisor.backups.manager] Backup 19df45f2 starting stage addon_repositories
24-02-02 09:00:22 INFO (MainThread) [supervisor.backups.manager] Backup 19df45f2 starting stage docker_config
24-02-02 09:00:22 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 19df45f2
24-02-02 09:00:22 INFO (MainThread) [supervisor.backups.manager] Backup 19df45f2 starting stage home_assistant
24-02-02 09:00:22 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
24-02-02 09:00:24 WARNING (MainThread) [supervisor.jobs] 'BackupManager.do_backup_partial' blocked from execution, system is not running - freeze
24-02-02 09:00:33 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
24-02-02 09:00:33 INFO (MainThread) [supervisor.backups.manager] Backup 19df45f2 starting stage finishing_file
24-02-02 09:00:34 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 19df45f2 completed
24-02-02 09:00:34 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2024.2.0b1
24-02-02 09:00:34 INFO (MainThread) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2024.2.0b0 to ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2024.2.0b1
24-02-02 09:00:34 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/raspberrypi4-64-homeassistant with tag 2024.2.0b1.
24-02-02 09:04:13 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping homeassistant application
24-02-02 09:04:16 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
```

## System Information

version | core-2024.2.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1392
Downloaded Repositories | 21
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5.rc3
-- | --
update_channel | beta
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 109.3 GB
disk_used | 22.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.6.1), Calibre (7.4.0), ESPHome (2023.12.9), File editor (5.7.0), Node-RED (17.0.3), Samba share (12.2.0), Scrypted (18-jammy-full.s6-v0.91.6), Tailscale (0.14.0), Terminal & SSH (9.8.1), go2rtc (1.8.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 22, 2024 at 18:27
-- | --
current_recorder_run | February 2, 2024 at 09:04
estimated_db_size | 230.80 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.15
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 7

</details>

### Supervisor diagnostics

[supervisor_2024-02-01T20-08-14.707Z.log](https://github.com/home-assistant/supervisor/files/14130369/supervisor_2024-02-01T20-08-14.707Z.log)

### Additional information

Relevant supervisor code:

https://github.com/home-assistant/supervisor/blob/b1b913777f5915c094b281c0874b326b22a8dc8a/supervisor/jobs/decorator.py#L363

## Question
I imagine this scenario could happen quite commonly given that all updates refresh, and display, at the same time.

Is there appetite to add an additional case to this code to show a more user-friendly message in the event of this specific issue occuring?

This would look like something to effect of "Update (with Backup) could not start because another backup is already running. Wait for the other backup to complete, then try to update again.".

**Comment by codyc1515** [comment]
Interesting. Some more updates popped up. The order of operations is extremely specific.

Installing an add-on update, then another add-on update (both with backup enabled) is fine.
![image](https://github.com/home-assistant/supervisor/assets/50791984/f201a903-e589-4cc4-992c-f699187ce530)

Installing an add-on update, then a Core update (both with backup enabled) is fine too
![image](https://github.com/home-assistant/supervisor/assets/50791984/1d2f3b4a-c88f-4c34-8105-19cfe72dc4aa)

So it appears that the only scenario which is forbidden due to freezing is core update, then add-on update.

Why is that, considering that the reverse (both running concurrently) is fine?

**Comment by codyc1515** [comment]
Current.

**Comment by agners** [comment]
This is probably more a frontend issue than a Supervisor issue :thinking:
