### ISSUE TITLE
[supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8

### ISSUE THREAD

**Issue by TheBartoMan** [home-assistant/supervisor#4870]
### Describe the issue you are experiencing

Every so often, Node-Red nodes show as no connection on service nodes calling Home Assistant.

Restarting the Node-red flows fixes it.

The supervisor log shows as follows:-

24-02-02 09:07:29 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8
24-02-02 09:07:29 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
24-02-02 09:07:34 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
24-02-02 09:07:35 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
24-02-02 09:07:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
24-02-02 09:07:36 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8
24-02-02 09:07:36 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
24-02-02 09:07:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
24-02-02 09:07:47 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
24-02-02 09:07:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
24-02-02 09:07:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8
24-02-02 09:07:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

In Node-Red have a "Call Service" node that tries to trigger something in Home Assistant.

(Node-Red is an addon in Home Assistant and on the same server.

Works for a long time, then as some stage the node in node-red shows "no connection"

Looking at the supervisor logs you see the errors mentioned. Including "[supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8"

### Anything in the Supervisor logs that might be useful for us?

```txt
24-02-02 09:07:29 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8
24-02-02 09:07:29 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
24-02-02 09:07:34 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
24-02-02 09:07:35 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
24-02-02 09:07:35 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
24-02-02 09:07:36 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8
24-02-02 09:07:36 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8
24-02-02 09:07:41 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
24-02-02 09:07:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
24-02-02 09:07:47 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
24-02-02 09:07:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
24-02-02 09:07:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot proxy websocket message of unsupported type: 8
24-02-02 09:07:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
```

### System Health information

There are currently no repairs available

**Comment by johntdyer** [comment]
seeing the same on 2024.02.01

**Comment by agners** [comment]
The WebSocket messge type 8 is a simple close (see https://docs.aiohttp.org/en/stable/websocket_utilities.html#aiohttp.WSMsgType), so this simply means that one side of the connection closed. This should end up in a closed overall connection, and from my limited testing NodeRED automatically reopens the connection.

So, this message should really not be problematic.

Is the connection not automatically reestablished in your case? Can you reproduce this when manually restarting the Supervisor using:

```
ha supervisor restart
```

Or Core?
```
ha core restart
```
