### ISSUE TITLE
[supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...

### ISSUE THREAD

**Issue by khaisilk1910** [home-assistant/supervisor#4893]
### Describe the issue you are experiencing

24-02-16 06:44:24 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
24-02-16 06:44:28 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...

24-02-16 07:08:44 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call https://172.30.32.1:8123/api/core/state.
24-02-16 07:08:44 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missed an Home Assistant Core API response.
24-02-16 07:08:46 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call https://172.30.32.1:8123/api/core/state.
24-02-16 07:08:48 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
24-02-16 07:08:51 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
[supervisor_2024-02-16T01-23-25.876Z.log](https://github.com/home-assistant/supervisor/files/14304076/supervisor_2024-02-16T01-23-25.876Z.log)

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
24-02-16 06:39:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
24-02-16 06:44:24 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
24-02-16 06:44:28 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
24-02-16 06:44:28 INFO (SyncWorker_1) [supervisor.docker.manager] Starting homeassistant
24-02-16 06:44:28 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
24-02-16 06:44:42 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
24-02-16 06:44:42 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to NOT_RUNNING
24-02-16 06:44:42 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
24-02-16 06:45:04 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/allenporter/stream-addons repository
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/jakowenko/double-take-hassio-addons repository
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/CoolKit-Technologies/ha-addon.git repository
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/rhasspy/hassio-addons repository
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/AlexxIT/hassio-addons repository
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
24-02-16 06:45:04 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/FaserF/hassio-addons repository
24-02-16 06:45:08 INFO (MainThread) [supervisor.store] Loading add-ons from store: 118 all - 0 new - 0 remove
24-02-16 06:45:08 INFO (MainThread) [supervisor.store] Loading add-ons from store: 118 all - 0 new - 0 remove
24-02-16 06:45:58 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to RUNNING
24-02-16 06:45:58 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.check] System checks complete
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
24-02-16 07:04:37 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
24-02-16 07:07:02 INFO (MainThread) [supervisor.backups.manager] Found 0 backup files
24-02-16 07:07:04 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
24-02-16 07:08:44 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call https://172.30.32.1:8123/api/core/state.
24-02-16 07:08:44 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missed an Home Assistant Core API response.
24-02-16 07:08:46 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call https://172.30.32.1:8123/api/core/state.
24-02-16 07:08:48 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
24-02-16 07:08:51 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
24-02-16 07:08:51 INFO (SyncWorker_6) [supervisor.docker.manager] Starting homeassistant
24-02-16 07:08:52 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
```

### System Health information

There are currently no repairs available

### Supervisor diagnostics

[config_entry-hassio-4270d7abb7cc16e273f61d8de3932307.json](https://github.com/home-assistant/supervisor/files/14304095/config_entry-hassio-4270d7abb7cc16e273f61d8de3932307.json)

### Additional information

My HASS has a frequent reboot error

**Comment by khaisilk1910** [comment]
24-02-16 09:25:02 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
24-02-16 09:25:02 ERROR (MainThread) [supervisor.homeassistant.api] Error on call https://172.30.32.1:8123/api/core/state: Cannot connect to host 172.30.32.1:8123 ssl:False [Connection reset by peer]
24-02-16 09:25:02 ERROR (MainThread) [supervisor.homeassistant.api] Error on call https://172.30.32.1:8123/api/core/state: Cannot connect to host 172.30.32.1:8123 ssl:False [Connection reset by peer]
24-02-16 09:25:02 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missed an Home Assistant Core API response.
24-02-16 09:25:06 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...

**Comment by khaisilk1910** [comment]
![image](https://github.com/home-assistant/supervisor/assets/3167468/7681d631-7647-4fbc-b6df-5815775a7541)
Does the dimmer part represent actual CPU status?
I see my CPU is up to 100% with a light green part.
Is it a hardware problem?

**Comment by khaisilk1910** [comment]
![image](https://github.com/home-assistant/supervisor/assets/3167468/9c586924-911b-4eb3-a9f3-56af8d01186c)
Is the Intel NUC Celeron J3455 too weak to run HASS?

**Comment by khaisilk1910** [comment]
i just found cause my hass  auto rebooting  when i open Home Assistant on my phone.
This morning I used the web browser and hass didn't restart.
It rebooted as soon as I opened the home assistant app on my phone



24-02-16 09:25:02 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
24-02-16 09:25:02 ERROR (MainThread) [supervisor.homeassistant.api] Error on call https://172.30.32.1:8123/api/core/state: Cannot connect to host 172.30.32.1:8123 ssl:False [Connection reset by peer]
24-02-16 09:25:02 ERROR (MainThread) [supervisor.homeassistant.api] Error on call https://172.30.32.1:8123/api/core/state: Cannot connect to host 172.30.32.1:8123 ssl:False [Connection reset by peer]
24-02-16 09:25:02 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missed an Home Assistant Core API response.
24-02-16 09:25:06 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...

**Comment by khaisilk1910** [comment]
24-02-19 06:42:38 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
24-02-19 06:42:38 ERROR (MainThread) [supervisor.homeassistant.api] Error on call https://172.30.32.1:8123/api/services: Server disconnected
24-02-19 06:42:38 ERROR (MainThread) [supervisor.api.proxy] Error on API for request services
24-02-19 06:42:42 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
24-02-19 06:42:42 INFO (SyncWorker_1) [supervisor.docker.manager] Starting homeassistant
24-02-19 06:42:42 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
24-02-19 06:42:55 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
24-02-19 06:42:55 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to NOT_RUNNING
24-02-19 06:42:56 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
24-02-19 06:43:17 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
24-02-19 06:43:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
24-02-19 06:43:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
24-02-19 06:43:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/AlexxIT/hassio-addons repository
24-02-19 06:43:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/CoolKit-Technologies/ha-addon.git repository
24-02-19 06:43:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
24-02-19 06:43:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
24-02-19 06:43:19 INFO (MainThread) [supervisor.store] Loading add-ons from store: 85 all - 0 new - 0 remove
24-02-19 06:43:19 INFO (MainThread) [supervisor.store] Loading add-ons from store: 85 all - 0 new - 0 remove
24-02-19 06:43:53 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
24-02-19 06:44:08 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to RUNNING
24-02-19 06:44:08 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
24-02-19 06:48:08 WARNING (MainThread) [supervisor.homeassistant.websocket] Connection is closed
24-02-19 06:48:08 ERROR (MainThread) [supervisor.homeassistant.api] Error on call https://172.30.32.1:8123/api/core/state: Cannot connect to host 172.30.32.1:8123 ssl:False [Connection reset by peer]
24-02-19 06:48:08 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missed an Home Assistant Core API response.
24-02-19 06:48:11 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...

**Comment by Stefano201** [comment]
@khaisilk1910 Did you solve it? Did the new app update solve the problem for you? I also have the same error (Timeout API) with system freeze.
