### ISSUE TITLE
Addon auto update not working

### ISSUE THREAD

**Issue by peterjuras** [home-assistant/supervisor#4914]
### Describe the issue you are experiencing

Hi,

Addons that have auto updating enabled are currently not auto updating. I have the ESPHome addon installed which has a new update available since 2 days (as visible in the HA UI), but it has not been updated since. There are no logs related to this from the supervisor.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Install any addon
2. Ensure "auto update" is checked for the addon
3. Wait until an update is available
4. Addon will not be auto updated, not even after a couple of days
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No logs related to updating from the supervisor
```

## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4997
Installed Version | 1.34.0
Stage | running
Available Repositories | 1411
Downloaded Repositories | 5
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 109.3 GB
disk_used | 63.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.6.1), Nginx Proxy Manager (1.0.1), Node-RED (17.0.7), OneDrive Backup (2.3), Samba share (12.3.0), Advanced SSH & Web Terminal (17.1.0), Studio Code Server (5.15.0), Glances (0.21.0), ESPHome (2023.12.9), Plex Media Server (3.5.0), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.3-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 4
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 14 February 2024 at 05:59
-- | --
current_recorder_run | 21 February 2024 at 04:09
estimated_db_size | 237.70 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Supervisor diagnostics

[config_entry-hassio-120eecb2c940e27fd974d93f6551bdec.json](https://github.com/home-assistant/supervisor/files/14382082/config_entry-hassio-120eecb2c940e27fd974d93f6551bdec.json)

### Additional information

There appears to have been a recent issue related to this (#4896) which should have been fixed in [Supervisor 2024.02.0](https://github.com/home-assistant/supervisor/releases/tag/2024.02.0), but it is not auto updating for me.

**Comment by mateuszdrab** [comment]
I am experiencing the same - the error from my issue is no longer showing but add-ons are still not updated.

**Comment by djismgaming** [comment]
I also see this behavior. Add-ons, keep asking for updates. For some time now.
![image](https://github.com/home-assistant/supervisor/assets/25346053/29e03157-2e0a-4ad5-b7c0-869caa8aa3bb)

And auto update is enabled:
![image](https://github.com/home-assistant/supervisor/assets/25346053/4eee6ae9-a2bd-45a8-ba52-719fa935d8dd)

**Comment by dominikhoebert** [comment]
Same for me. I think its since 2024.2

**Comment by mateuszdrab** [comment]
@peterjuras @dominikhoebert 

With Supervisor 2024.3.0 which incorporates the fix - are the updates working for you?

For me, they're still not working - I have checked 5 independent HASS instances I manage and they all have updates pending (all have latest supervisor)

**Comment by peterjuras** [comment]
Hi @mdegat01 , @mateuszdrab 

same here. I have Supervisor 2024.03.0 since a couple of days and three pending updates for addons with Auto Update enabled.

I'd recommend to re-open the issue and only close it once a fix is released in public and verified.

**Comment by mateuszdrab** [comment]
@peterjuras 
It's actually working now - took more than 24h after the supervisor container updated for this to kick in as that's the added delay for new addon updates.
It seems the addon update availability timestamp is reset after container restart.

**Comment by peterjuras** [comment]
Yes, also worked for me now 👍 Thanks for the fix!
