### ISSUE TITLE
Restore after backup doesn't work

### ISSUE THREAD

**Issue by martusi61** [home-assistant/supervisor#4916]
### Describe the issue you are experiencing

After my SSD crashed I restored an old image and then used an updated backup Of this I chose the partial recovery, starting with the individual components first with success but once I moved to the core everything stopped, the restore procedure deleted almost all the contents of the config folder. I then solved it with a manual copy of the contents of the backup.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Steps to reproduce the issue

1. From the backup function I selected partial restore
2. Then I chose home assistant 
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

## System Information

version | core-2024.2.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 5.9.0-arm-64
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1398
Downloaded Repositories | 30

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.0
agent_version | 1.4.1
docker_version | 23.0.0
disk_total | 28.6 GB
disk_used | 20.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Home Assistant Google Drive Backup (0.112.1), Duck DNS (1.15.0), TasmoAdmin (0.29.1), DHCP server (1.3.1), Tailscale with features (0.16.0.0), Cloudflared (5.1.4), Piper (1.4.0), Whisper (1.0.2), openWakeWord (1.8.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 21
views | 33
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29 gennaio 2024 alle ore 22:33
-- | --
current_recorder_run | 23 febbraio 2024 alle ore 18:55
estimated_db_size | 1979.25 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Sonoff</summary>

version | 3.6.0 (8dd8af9)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

### Additional information

The only error I have had for years is related to the CGroup Version.
Your system is not supported because you are using the wrong version of Docker CGroup. Use the link to find out the correct version and how to fix the problem.

**Comment by agners** [comment]
This could be related to #4924.

Gist is, under some circumstances (if large files have been backed up) backups taken by Supervisor 2024.02.0 were not readable.

How old was the backup you've been trying to restore? Did your backup contain large files or folder?

**Comment by martusi61** [comment]
I first restored an image from September 2023, then I updated the image and the components to the latest versions, finally I reloaded a backup made 16 hours earlier, but on this system that is now updated.

**Comment by agners** [comment]
Ok, in that case it is most likely related to https://github.com/home-assistant/supervisor/issues/4924.

The issue is fixed, but currently on the beta channel for testing. I'll promote it to the stable channel today.

**Comment by martusi61** [comment]
Well, I don't know, the case is very different from my problem and in any case my compressed file is not damaged

**Comment by martusi61** [comment]
Yes exactly. For the log I can try to extract it.

**Comment by LordArrin** [comment]
same thing here
[supervisor_2024-03-07T15-44-47.671Z.log](https://github.com/home-assistant/supervisor/files/14526661/supervisor_2024-03-07T15-44-47.671Z.log)

**Comment by LordArrin** [comment]
Регистратор: homeassistant.setup
Источник: setup.py:266
Первое сообщение: 18:45:12 (1 сообщений)
Последнее сообщение: 18:45:12

Setup failed for custom integration 'tuya_local': Requirements for tuya_local not found: ['tinytuya==1.13.1'].

**Comment by LordArrin** [comment]
Регистратор: homeassistant.components.hassio.handler
Источник: components/hassio/handler.py:593
интеграция: Home Assistant Supervisor (документация, проблемы)
Первое сообщение: 20:53:53 (1 сообщений)
Последнее сообщение: 20:53:53

/refresh_updates return code 400
