### ISSUE TITLE
Backup page listing empty when MariaDB is included

### ISSUE THREAD

**Issue by IngmarVerheij** [home-assistant/supervisor#4932]
### Describe the issue you are experiencing

Backups created that contain the MariaDB add-on are no longer visible in the Backups page. This happens with Full backups or with Partial backups with only the MariaDB add-on (2.6.1).

Full back-ups made (either manual or via the OneDrive Backup add-on) are found in /backups (~10GB) but cannot be opened because it is corrupt.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Create a full backup including MariaDB 
2. Open Settings/System/Backups to see the list of backups
3. Verify the backup is not displayed

### Anything in the Supervisor logs that might be useful for us?

```txt
(none, which worries me)
```

### System Health information

_There are currently no repairs available_

### Supervisor diagnostics

[config_entry-hassio-86772d482c35c6fd93cd313c17525f2a.json](https://github.com/home-assistant/supervisor/files/14431333/config_entry-hassio-86772d482c35c6fd93cd313c17525f2a.json)

**Comment by agners** [comment]
Releated to https://github.com/home-assistant/supervisor/issues/4924.

The fixed version should soon appear on stable channel.
