### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by vespassassina** [home-assistant/supervisor#4960]
### Describe the issue you are experiencing

While setting up EventHubs integration, the setup is broken by a translation error.

language is English, running i docker container on Synology. 
Core: 2024.3.0
UI: 20240306.0

Translation Error: The intl string context variable "event_hub_instance_name" was not provided to the string "Please enter the connection string for: {event_hub_instance_name

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

1. Try to setup Event Hubs
2. Add EH name
3.  Fill Form
4. Press SUbmit
...

### Anything in the Supervisor logs that might be useful for us?

```txt
the error is not logged
```

### System Health information

There are currently no repairs available

### Supervisor diagnostics

no supervisor

**Comment by agners** [comment]
:wave: thanks for your report. This repository is about Home Assistant Supervisor. Please report the translation error to the Core repository at https://github.com/home-assistant/core.
