### ISSUE TITLE
Some issues after switching to Supervisor 2024.3

### ISSUE THREAD

**Issue by krzysztofnowak1972** [home-assistant/supervisor#4982]
### Describe the issue you are experiencing

This is the 3rd place where this problem is described. Described in Core, in MyUplink and now here - because I noticed that it breaks only after updating to Supervisor 2023.3. 
Maybe you will be able to find the cause

1. API from the standard MYUplink integration works intermittently - there is no data continuity - error Port 443 SSL

ERROR (MainThread) [homeassistant.components.myuplink.coordinator] Error requesting myuplink data: Cannot connect to host api.myuplink.com:443 ssl:default [Try again]

2. API from the standard Open meteo integration - sometimes it works, sometimes it doesn't

ERROR (MainThread) [homeassistant.components.open_meteo] Error fetching open_meteo_zone.dom data: Open-Meteo API communication error

3. API from standard Hydrawise integration - sometimes it works, sometimes it doesn't

ERROR (MainThread) [homeassistant.components.hydrawise] Error requesting hydrawise data: Cannot connect to host api.hydrawise.com:443 ssl:default [Try again]

4. Supervisor 2024.2 - CPU usage 10%, memory 51%, Supervisor 2024.3 - CPU - 73-80% Memory - 60-70%

5. MariaDB - Supervisor 2024.2 and CPU usage 0.5% and in Supervisor 2024.3 - 60%

I have been trying to control it for 3 weeks, but I gave up and went back to 2024.2 - on Supervisor 2024.2 everything works as it should, when I switch to 2024.3 and enable subsequent core and OS updates - it stops working smoothly. There are interruptions in operation, the server on Proxmox gets very hot.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. f
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
All errors in the log had a common thread - port 443 SSL:default
```

### System Health information

Its clean

### Supervisor diagnostics

Now I'm on 2024.2 and I don't have diagnostics - I have some diagnostics exactly from the time it didn't work - My Uplink integration

[config_entry-myuplink-654d0bd62e1d240b6aaa279cf5003785.json](https://github.com/home-assistant/supervisor/files/14761522/config_entry-myuplink-654d0bd62e1d240b6aaa279cf5003785.json)

And here is the log when it didn't work when I was on supervisor 2024.3

[home-assistant_myuplink_2024-03-24T19-27-33.654Z.log](https://github.com/home-assistant/supervisor/files/14761533/home-assistant_myuplink_2024-03-24T19-27-33.654Z.log)

**Comment by krzysztofnowak1972** [comment]
Thank you - now it's much much better

After upgrade supervisor 2024.03.1- CPU avg 10 % and RAM avg - 50 % 

Good job ;-)

**Comment by agners** [comment]
FWIW, it is not clear to me what could have caused that higher CPU load. Non of the introduced changes really explain the behavior. Most likely this is some interaction between Core and Supervisor, and now that the Supervisor got updated (and restarted) independently, things work again. I would not be surprised if that problem appears again.

If the problem does return, please share the Supervisor logs as well (you can choose them in the drop down on the top right in the logs view). Also try to restart the Supervisor manually (using `ha su restart`).

I am closing this for now, as it is resolved currently.
