### ISSUE TITLE
Container submounts in /dev are read-only with Docker 25+

### ISSUE THREAD

**Issue by sairon** [home-assistant/supervisor#4996]
### Describe the issue you are experiencing

Docker 25.0.0 [introduced a change](https://docs.docker.com/engine/release-notes/25.0/#2500) that makes recursive mounts read-only, unless explicitly specified otherwise. However, in many cases the add-ons and even the Home Assistant Core might rely on `/dev/pts` (for psedo-terminal allocation) and `/dev/shm` (for accessing shared memory) to be writable. It is possible to change it to make recursed mounts to be mounted writable to keep the old behavior, as suggested e.g. [here](https://github.com/moby/moby/issues/47158#issuecomment-1903975175).

The issue already manifested a while ago when Docker was upgraded on some Supervised installations but it was not pursued further and was likely incorrectly assumed to be a result of the other upstream Docker bug: https://github.com/home-assistant/supervisor/issues/4827#issuecomment-1908054215

With Docker bump in HAOS 12.2.rc1 the issue started to manifest on more places, e.g. for [InfluxDB](https://github.com/home-assistant/operating-system/issues/3282), [hdmi_cec](https://github.com/home-assistant/operating-system/issues/3277), both likely needing shared memory, or for the Advanced SSH add-on [failing to create PTY](https://github.com/home-assistant/operating-system/issues/3278).

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Update to HAOS 12.2.rc1 (or Docker 25.0.0+ on Supervised).
2. Install Advanced SSH & Web Terminal community add-on.
3. Connect using SSH client as a non-root user.
4. Connection fails on `exec sudo -i` in `.profile` with `sudo: unable to allocate pty: Read-only file system`.

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### System Health information

N/A

**Comment by agners** [comment]
The Home Assistant Core container is not recreated on restart. However, the bug fix needs a container creation to take effect. So for the InfluxDB '[Errno 30] Read-only file system' issue a `ha core rebuild` command is required.

**Comment by MattWestb** [comment]
@agners How to pull the 2024.4.0 (or .1) image and linking it to current suppressed HA like we was doing with Silabs multi protocol then i can finding the image (or the right path to it) ?
I have 3 system that have lost all sensor data in Influx for some weeks . . .  so like getting it upp and running  but i dont do beta on my production system.

**Comment by agners** [comment]
Currently, you'd need to update Supervisor 2024.04.0 specifically:

```
ha su options --channel beta
ha su reload
ha su info # check if a Supervisor update is available
ha su update
...
ha su options --channel stable
```

Other parts of the system (Core/Add-ons) won't get updated to the beta channel when you move right back to stable.

We most likely will promote Supervisor 2024.04.0 to stable next week.
