### ISSUE TITLE
Supervisor does not start: Exec format error

### ISSUE THREAD

**Issue by Lukeid** [home-assistant/supervisor#5004]
### Describe the issue you are experiencing

I had problems updating HA ([issue](https://github.com/home-assistant/core/issues/114935)) in one the tries I got an error about that could not connect to suppervisor and I rebooted to do a fresh test. But HA didn't start.

The CLI doesn't load I a go to Emergency console:
```
Waiting for the Home Assistant CLI to be ready...
[WARN] Home Assistant CLI not starting! Jump into emergency console...
```

I tried also to write "login" but same happens.

Docker is not running, but I can start homeassitant docket manually ("docker start homeassistant"). But supervisor is disconnected.

If I try to run iot manually ("docket start hassio_supervisor") it fails:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/udev.sh
[20:05:09] INFO: Using udev information from host
cont-init: info: /etc/cont-init.d/udev.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun supervisor (no readiness notification)
services-up: info: copying legacy longrun watchdog (no readiness notification)
s6-rc: info: service legacy-services successfully started
[20:05:09] INFO: Starting local supervisor watchdog...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/supervisor/supervisor/__main__.py", line 8, in <module>
    import zlib_fast
  File "/usr/local/lib/python3.12/site-packages/zlib_fast/__init__.py", line 3, in <module>
    import gzip as gzip_original
  File "/usr/local/lib/python3.12/gzip.py", line 9, in <module>
    import zlib
ImportError: Error loading shared library libz.so.1: Exec format error (needed by /usr/local/lib/python3.12/lib-dynload/zlib.cpython-312-arm-linux-musleabihf.so)
[20:05:11] WARNING: Halt Supervisor
[20:05:11] INFO: Supervisor restart after closing
s6-rc: info: service legacy-services: stopping
[20:05:11] INFO: Watchdog restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

This info about version were taken yesterday when HA worked:
```
docker: 24.0.7
hassos: "12.1"
homeassistant: 2024.2.5
machine: raspberrypi3
operating_system: Home Assistant OS 12.1
supervisor: 2024.03.1
```

Full info:  [info.txt](https://github.com/home-assistant/supervisor/files/14910627/info.txt)

I have a full HA backup from yesterday, is there any way to manually restore it? Or recover somehow the supervisor to restore the backup normally.

Thank you very much.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

Reboot

### Anything in the Supervisor logs that might be useful for us?

```txt
[20:05:09] INFO: Starting local supervisor watchdog...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/supervisor/supervisor/__main__.py", line 8, in <module>
    import zlib_fast
  File "/usr/local/lib/python3.12/site-packages/zlib_fast/__init__.py", line 3, in <module>
    import gzip as gzip_original
  File "/usr/local/lib/python3.12/gzip.py", line 9, in <module>
    import zlib
ImportError: Error loading shared library libz.so.1: Exec format error (needed by /usr/local/lib/python3.12/lib-dynload/zlib.cpython-312-arm-linux-musleabihf.so)
[20:05:11] WARNING: Halt Supervisor
```
```


### System Health information

Settings -> System -> Repairs is not working.

This is what I have: [info.txt](https://github.com/home-assistant/supervisor/files/14910627/info.txt)

### Supervisor diagnostics

_No response_

### Additional information

_No response_

**Comment by agners** [comment]
Most likely this is caused by corruption of the container image stored on locally. What type of storage is your Raspberry Pi running from?

Now it is a bit unfortunate that this seems to be the gzip library, which prevents even startup :cry:  Easiest is if you can setup Home Assistant from scratch (with a new SD card) and restore the latest backup.

Unfortunately, from what I know, Docker has no reliable way of re-downloading and rewriting an image (and *all* layers thereof). And even if so, this might also fail if the SD card is really dying :cry:

**Comment by Lukeid** [comment]
Thank you for your answer.

I have a SD card.
I'm not sure about being a physical corruption, I think maybe the reboot were done while doing a rollback from an unsuccessfull core update and something is inconsistent now.

In any case I have a what I think is a full backup from "/mnt/data/supervisor/backup", but is a .tar file with an id as filename. How could I restore it if I do a installation from scratch?

**Comment by agners** [comment]
> In any case I have a what I think is a full backup from "/mnt/data/supervisor/backup", but is a .tar file with an id as filename. How could I restore it if I do a installation from scratch?

Yes, the files from `/mnt/data/supervisor/backup` are the backups. You can upload the backup tar file on the on-boarding page of your new installation, simply choose "Restore from Backup" (see https://www.home-assistant.io/getting-started/onboarding/).

**Comment by Lukeid** [comment]
Ok, thank you.

Is there any option to do a reinstall without lossing all the backup files or from the raspberry itself? Or the only option is to re-flash the SD card with an image (https://www.home-assistant.io/installation/raspberrypi) in a PC?

One more doubt, should I install the same version of the backup (2024.2.3 in my case) or can I restore over latest version?

This is the main info of the backup:
```
    "version": 2,
    "name": "4 de abril de 2024",
    "date": "2024-04-04T18:27:07.339937+00:00",
    "type": "full",
    "supervisor_version": "2024.03.1",
    "homeassistant": {
        "version": "2024.2.3",
        "exclude_database": false,
        "size": 0.0
    },
```

**Comment by Lukeid** [comment]
Ok, I'll do it. The new SD Card will arrive tomorrow.

Should I donwgrade the application to backup version (2024.2.3)?

Thank you very much for all your support.

**Comment by Lukeid** [comment]
Hello finally I've restored the backup on top of a fresh installation (with new SD card), and now everything is working.

Thank you for the support.
