### ISSUE TITLE
[supervisor.api.ingress] No valid ingress session None

### ISSUE THREAD

**Issue by slavendam** [home-assistant/supervisor#5045]
### Describe the issue you are experiencing

Hi,
I've created add-on from web app. I want to display this app in card/panel of HA and displaying works, but...

This is config I use:
```
type: iframe
url: /api/hassio_ingress/Vp_6ov3A_ckt441nZWPlhgK2UoAjDL8VDzgWQkuhYXc/
```
This URL is iframe URL.
Problem is when I log in to HA on browser where I didn't logged in before. In that case **ingress_session** cookie is missing, it is still not generated. 
In that case I'm getting _"401 (Unauthorized)"_, and in Supervisor logs I get _"[supervisor.api.ingress] No valid ingress session None"_

If I open add-on with steps "Settings->Add-ons-> open add-on -> OPEN WEB UI" this ingress_session is generated and now everything works as expected in card/panel also.
If I delete cookie from browser cache it still works, so it seems that session is stored somewhere in backend and connected with hass_token?

### My question: 
**_is there a way on HA to generate ingress_session on login or with card initialization?_**
.

There is second option. If I use this config (with direct add-on URL):
```
type: iframe
url: /8e14ce16_glamos_klet3d/ingress
```
It works correctly (opens add-on/app), but than inside of card/panel I have additional HA sidebar. Is there a way to avoid this sidebar?
![image](https://github.com/home-assistant/supervisor/assets/19354024/d338db16-c080-4948-99a3-32085a4fe5d5)

Thanks!

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Install and setup add-on
2. Add add-on as iframe to card/panel
3. Login from incognito browser
4. It will return 401
5. Open add-on from Settings or sidebar
6. Now it works in card/panel also

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-04-26 09:21:05.659 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
```

## System Information

version | core-2024.4.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Zagreb
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 28.0 GB
disk_used | 4.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Homeway (1.1.6), GLAMOS Klet3D (1.0.108), File editor (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 22, 2024 at 4:06 PM
-- | --
current_recorder_run | April 25, 2024 at 10:20 PM
estimated_db_size | 0.80 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by mfin** [comment]
I'm having the same problem, @slavendam did you manage to get around this issue?

**Comment by slavendam** [comment]
> I'm having the same problem, @slavendam did you manage to get around this issue?

Unfortunatelly no. 
Only solution is to open add-on directly from add-on store (or sidebar), and when you get back to home it will work there (no more error 401).
I couldn't find a way to remove this additional sidebar if I use direct URL of add-on.
