### ISSUE TITLE
Client error on /addons/cebe7a76_hassio_google_drive_backup/changelog request 0

### ISSUE THREAD

**Issue by liamlain** [home-assistant/supervisor#5055]
### Describe the issue you are experiencing

showing error after upLogger: homeassistant.components.hassio.handler

Source: components/hassio/handler.py:612
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 9:54:38 AM (52 occurrences)
Last logged: 2:09:43 PM

Client error on /addons/cebe7a76_hassio_google_drive_backup/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/cebe7a76_hassio_google_drive_backup/changelog')dated to latest supervisor 2024.04.4

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Updated to 2024.04.4
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
supervisor not showing any error log
```

## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Asia/Kuala_Lumpur
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1486
Downloaded Repositories | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 30, 2024 at 8:00 AM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | ap-southeast-1-1.ui.nabu.casa
certificate_status | ready
instance_id | d07e5d25bf5942919571ba8aff9cdc5c
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 219.4 GB
disk_used | 17.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Home Assistant Google Drive Backup (0.106.2), Samba share (12.3.1), ArgonOne Active Cooling (30a), Mosquitto broker (6.4.0), ESPHome (2024.4.2), go2rtc (1.9.0), Spotify Connect (0.13.0), Frigate (0.13.2), Advanced SSH & Web Terminal (17.2.0), Studio Code Server (5.15.0), Zigbee2MQTT (1.36.1-1), MQTT Explorer (browser-1.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 33
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 30, 2024 at 8:46 PM
-- | --
current_recorder_run | May 3, 2024 at 9:54 AM
estimated_db_size | 181.09 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.18
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 2
total_devices | 10

</details>

**Comment by vin100ross** [comment]
My logs are filling up with this exact same error, so this is happening on at least 2 systems. Also on 2024.04.4. Home Assistant OS on a Pi 5.

**Comment by agners** [comment]
Fixed with #5064 in Supervisor 2024.05.0 (currently on beta channel).
