### ISSUE TITLE
_Preparing Home Assistant_ takes way more than 20 minutes!

### ISSUE THREAD

**Issue by brianjmurrell** [home-assistant/supervisor#5070]
### Describe the issue you are experiencing

I've installed HAOS on an x86_64 machine and booted it.  At http://homeassistant.local:8123/ I get the startup splash screen that says:

Preparing Home Assistant
This may take up to 20 minutes

with a pulsing _wait_ bar.

It's been way more than 20 minutes.  Hours in fact.

However, I can see that there is network activity from the host and that in `/mnt/data/docker/tmp/` there are a number of files that are growing:

```
-rw-------    1 root     root     320018294 May  8 21:49 GetImageBlob1450916838
-rw-------    1 root     root       1843950 May  8 19:27 GetImageBlob2224184623
-rw-------    1 root     root      20514959 May  8 19:25 GetImageBlob2678149892
-rw-------    1 root     root      18363980 May  8 19:28 GetImageBlob3062661846
-rw-------    1 root     root          1483 May  8 19:25 GetImageBlob3086642992
-rw-------    1 root     root            94 May  8 19:25 GetImageBlob4239163032
```

so it's clearly still _initializing_.

But the point is that it's **NOT** 20 minutes and there is no indication that even hours later that it's actually doing something.  Some kind of progress meter would be wonderful here.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A of course.
```

### System Health information

N/A of course.

### Supervisor diagnostics

N/A of course.

**Comment by brianjmurrell** [comment]
FWIW, it finally did complete and I am now using HA, so this really was just a case of serious lack of and mis-information.

**Comment by agners** [comment]
> It's been way more than 20 minutes. Hours in fact.

On initial startup of Home Assistant OS, we install the latest version of Home Assistant Core. How long this takes very much depends on your Internet speed and potentially the load on GitHub Container Registry which we use to distribute on Home Assistant.

The text currently makes it sound like this should never take longer than 20 minutes, where in fact we can't really say how long it takes :cry:  I've adjusted the message accordingly with https://github.com/home-assistant/landingpage/pull/116.

> Some kind of progress meter would be wonderful here.

I 100% agree! Ultimately, the Supervisor uses docker-py to download the images container images, and afaik there is no download progress reported :cry:  We do have ideas to improve the messaging though. The Supervisor also potentially downloads multiple images, but it is not shown in the frontend yet. Displaying more is a pending feature for the landing page (https://github.com/home-assistant/landingpage).

**Comment by brianjmurrell** [comment]
Indeed.  Even having that page say that a download is happening so that the user as some expectation that it could take a while.
