### ISSUE TITLE
Could not fetch changelog errors not fixed in 2024.05.1

### ISSUE THREAD

**Issue by vin100ross** [home-assistant/supervisor#5076]
### Describe the issue you are experiencing

The "Could not fetch changelog" warnings and associated "Attempt to decode JSON with unexpected mimetype" errors that were reported in #5053 and #5055 (now both closed), and were marked as fixed by #5064 are in fact not fixed. The errors still occur in the core logs every few minutes even after upgrading to 2024.05.1. For example:

> 2024-05-13 11:16:13.099 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /addons/cebe7a76_hassio_google_drive_backup/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/cebe7a76_hassio_google_drive_backup/changelog')
2024-05-13 11:16:13.100 WARNING (MainThread) [homeassistant.components.hassio.data] Could not fetch changelog for cebe7a76_hassio_google_drive_backup:

Also see issue [#116470](https://github.com/home-assistant/core/issues/116470) on the core side where this is still being discussed.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Upgrade to 2024.05.1 with an affected addon (ex Google Drive backup)
2. Wait a few minutes
3. Look at the core logs.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing significant in the supervisor logs. Errors and warnings are in the core logs but refer to the supervisor integration.
```

## System Information

version | core-2024.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 234.0 GB
disk_used | 9.7 GB
healthy | true
supported | true
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Samba share (12.3.1), Terminal & SSH (9.9.0), Advanced SSH & Web Terminal (17.2.0), Home Assistant Google Drive Backup (0.105.2), AdGuard Home (5.0.3), Victoria Metrics (1.9.1), Glances (0.21.1), Cloudflared (5.1.9), Let's Encrypt (5.0.18), Z-Wave JS (0.5.0), ESPHome (2024.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 8, 2024 at 1:15 PM
-- | --
current_recorder_run | May 12, 2024 at 11:21 PM
estimated_db_size | 57.68 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Supervisor diagnostics

[config_entry-hassio-7d1d4a0224dcebf765a4f90e58b40a06.json](https://github.com/home-assistant/supervisor/files/15296772/config_entry-hassio-7d1d4a0224dcebf765a4f90e58b40a06.json)

**Comment by mdegat01** [comment]
So I use this addon regularly and I don't see anything like this in my logs. I also took a dev system I have on the latest supervisor and core and installed the referenced addon yesterday. It's been almost 24 hours now and I still don't have this log line.

It's especially confusing because the addon you're referencing actually does have a changelog. The problematic addons previously where the ones without changelogs.

I'm kind of scratching my head here. Can you try restarting core and see if maybe there's something bad that is cached behind the scenes?

**Comment by mdegat01** [comment]
@vin100ross Ah I think I figured out what's going on. Looking at the diagnostic data you linked your system is missing the addon repository for the google drive backup addon.

Like if you remember when you first installed that addon you had to add this this repository to your list of addon repositories: https://github.com/sabeechen/hassio-google-drive-backup . And then you found the addon in your list and installed it. That repository is no longer listed in your list of addon repositories which means supervisor cannot find any information about it and is causing strange errors like this.

That also explains why your google drive backup addon is very out of date. That addon is currently on version `0.112.1`, you're running `0.105.2` which is I guess about 3 years old? Although its not actually listed on that repo so perhaps it was pulled for some reason, I'm not sure.

Can you try adding that repository to your list of addon repositories and see if that fixes it?

**Comment by vin100ross** [comment]
Great find @mdegat01! I added the repository back and the errors stopped. Very strange that the repo went missing, however... I'm certain I never removed it intentionally (I wouldn't know how).

Looking at the core issue I linked above, I am obviously not the only one with this problem. May I suggest a better diagnostic that detects that an addon repository is missing or no longer valid, and a more descriptive error message suggesting adding it back to the addon store? Just the fact that the repo _can_ go missing may be a bug in itself...

In any case, I am closing this issue since I consider this solved on my side. If you think it would be appropriate, I can file another issue for the confusing error message. If another repo mysteriously goes missing, I'll file an issue for that then.

**Comment by mdegat01** [comment]
That's a really good idea. We should have a rapair for that. I'll look into that 👍

**Comment by F30C-14F5** [comment]
Thanks' Work for me also

**Comment by iMiMx** [comment]
Just come across the same myself - google backup repo missing, pretty sure I didn't remove it :-/
