### ISSUE TITLE
Mounting SMB Share stopped working

### ISSUE THREAD

**Issue by corelanc0d3r** [home-assistant/supervisor#5077]
### Describe the issue you are experiencing

After the last update (and after doing 2 full reboots just to be sure), HA doesn’t seem to be able to properly mount my Samba/Windows network storage any more. (SMB share hosted on a Synology NAS)
The actual share/storage works and is accessible from other machines.

Observed behavior:
Settings - Storage still shows the network storage. (Sometimes the name of the volume is printed in orange)
When I edit the storage and enter the username & password again, and click “update”, I get

“Mounting Backup2NAS did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-Backup2NAS.mount for details.”

NAS storage was set as default backup location. List of backups is empty.
(and seems to fall back to local disk storage now?)

I am running HAOS on a Raspberry PI 4

Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Steps to reproduce the issue

Not sure how to reproduce the issue, but if there is anything I can do to support the troubleshooting, let me know.

### Anything in the Supervisor logs that might be useful for us?

```txt
I have removed the Network Storage and tried to recreate it:

2024-05-14 07:10:10.965 INFO (MainThread) [supervisor.mounts.manager] Creating or updating mount: Backup2NAS
2024-05-14 07:10:11.067 ERROR (MainThread) [supervisor.mounts.mount] Mounting Backup2NAS did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-Backup2NAS.mount for details.
```

### System Health information

"There are currently no repairs available"

### Supervisor diagnostics

[config_entry-hassio-e94a3251436b67e7e8725376b42ed7f3.json](https://github.com/home-assistant/supervisor/files/15303065/config_entry-hassio-e94a3251436b67e7e8725376b42ed7f3.json)

**Comment by corelanc0d3r** [comment]
Problem is on my side, you can disregard this issue

**Comment by agners** [comment]
Thanks for the update!

**Comment by CunningTomato64** [comment]
@corelanc0d3r, what was the solution? I started experiencing the exact same issue / error after 2024.5.3 update. I've removed the Network storage and am now unable to recreate.

**Comment by corelanc0d3r** [comment]
I recreated the useraccount on my Synology nas, changed the password to something else too, and then recreated the storage in home assistant.

My daily backups work again, the files appear in the shared folder.  (When I access the share from another machine, I can see the file has arrived)

However, when I open Settings - System - Backups, the view remains empty "You don't have any backups yet."
