### ISSUE TITLE
Issue with add-ons since HA 2024-7

### ISSUE THREAD

**Issue by BrianTomlinson** [home-assistant/supervisor#5180]
### Describe the issue you are experiencing

Some add-ons are showing as running but never start and some just won't start. 

On the esphome discord, a response was " That looks like an HA issue.  Especially the seg fault in dpkg."
Hence raising here.

 Below are the matter server, esphome and light wave logs

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Update to 2024.7
2. Run or start addons
3. Add-ons fail.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
#matter server logs
2024-07-09 19:14:39.087 ERROR (MainThread) [supervisor.docker.interface] Can't install homeassistant/amd64-addon-matter-server:6.2.1: 404 Client Error for http+docker://localhost/v1.45/images/homeassistant/amd64-addon-matter-server:6.2.1/json: Not Found ("No such image: homeassistant/amd64-addon-matter-server:6.2.1")

#esphome logs
[18:50:24] ERROR: Something went wrong contacting the API
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
[18:50:24] INFO: Configuring timezone (Europe/London)...
s6-rc: info: service fix-attrs successfully started
[18:50:24] ERROR: Something went wrong contacting the API
/package/admin/s6-overlay/etc/s6-rc/scripts/base-addon-timezone: line 12:    69 Segmentation fault      (core dumped) dpkg-reconfigure --frontend noninteractive tzdata 2> /dev/null
s6-rc: warning: unable to start service base-addon-timezone: command exited 128
s6-rc: info: service base-addon-log-level successfully started
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

#lightwave logs
Logger: lightwave.lightwave
Source: /usr/local/lib/python3.12/site-packages/lightwave/lightwave.py:237
First occurred: 18:55:10 (9 occurrences)
Last logged: 19:10:20

LW broker fail!
```

## System Information

version | core-2024.7.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4981
Installed Version | 1.34.0
Stage | running
Available Repositories | 1462
Downloaded Repositories | 55
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 13 July 2024 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
instance_id | 13d16c0dd911487faa1d3ee4d8ffe16f
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 38.7 GB
disk_used | 17.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Samba share (12.3.1), Studio Code Server (5.15.0), Node-RED (18.0.3), Portainer (2.20.1), Cloudflared (5.1.14), Castsponsorskip (0.7.4), ZigStar TI CC2652P/P7 FW Flasher (0.4.0), Tailscale (0.20.0), Music Assistant BETA (2.1.0b14), Zigbee2MQTT (1.39.0-1), Mosquitto broker (6.4.1), Home Assistant Google Drive Backup (0.112.1), Terminal & SSH (9.14.0), ESPHome (2024.6.6), Matter Server (5.5.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 41
views | 47
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 April 2024 at 20:03
-- | --
current_recorder_run | 9 July 2024 at 18:47
estimated_db_size | 461.25 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Additional information

Tried a restore from an old image that was working 2024.4 and updated and the issue persisted.
Have tried reinstalling add-ons but didn't work. 

It is causing havoc to become unstable, rebooting or freezing regularly.

**Comment by bordenit** [comment]
Same here. Addons wonky, and crashes. Going to revert to last stable version.
