### ISSUE TITLE
Warning in Supervisor logs after upgrade to 2024.08.0

### ISSUE THREAD

**Issue by vturekhanov** [home-assistant/supervisor#5226]
### Describe the issue you are experiencing

Found followings warnings after upgrading Supervisor to 2024.08.0.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Upgrade Supervisor to 2024.08.0.
2. Watch Supervisor logs.

### Anything in the Supervisor logs that might be useful for us?

```txt
_PUNC = "\!|\"|\;|\#|\$|\%|\&|\'|\(|\)|\+|\,|\/|\:|\<|\=|\>|\@|\[|\]|\^|\`|\{|\||\}|\~|\-"
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp2_3_fs.py:77: SyntaxWarning: invalid escape sequence '\{'
  _logical = "(\{0}|{1})".format(VALUE_ANY, VALUE_NA)
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp2_3_fs.py:78: SyntaxWarning: invalid escape sequence '\{'
  _quest = "\{0}".format(WILDCARD_ONE)
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp2_3_fs.py:79: SyntaxWarning: invalid escape sequence '\{'
  _asterisk = "\{0}".format(WILDCARD_MULTI)
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp_anyvalue.py:35: SyntaxWarning: invalid escape sequence '\*'
  """
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp1_1.py:57: SyntaxWarning: invalid escape sequence '\w'
  _STRING = "\w\.\-,\(\)@\#"
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp2_2.py:52: SyntaxWarning: invalid escape sequence '\d'
  _VALUE_PATTERN = "^([\d\w\._\-~%]+)$"
/usr/local/lib/python3.12/site-packages/cpe/cpe2_3_fs.py:97: SyntaxWarning: invalid escape sequence '\:'
  _parts_pattern = "^cpe:2.3:{0}\:{1}\:{2}\:{3}\:{4}\:{5}\:{6}\:{7}\:{8}\:{9}\:{10}$".format(
```

## System Information

version | core-2024.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Asia/Aqtau
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1392
Downloaded Repositories | 10
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 11.2 GB
disk_used | 7.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | parallels
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), Mosquitto broker (6.4.1), go2rtc (1.9.4), FTP (5.0.2), Terminal & SSH (9.14.0), Matter Server (6.4.0), MariaDB (2.7.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 3
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 29, 2024 at 08:07
-- | --
current_recorder_run | August 1, 2024 at 08:21
estimated_db_size | 518.45 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (2f05036)
-- | --
cloud_online | 2 / 3
local_online | 1 / 1

</details>

**Comment by agners** [comment]
Thanks for reporting! These are warnings, so should not have operational impact.

They seem to be related to this CPE issue: https://github.com/nilp0inter/cpe/pull/57. I wonder why we've not noticed them in beta channel :thinking:

I guess the best way forward is to suppress this warnings until there is a new CPE release.

@mdegat01 thoughts?

**Comment by Baxxy13** [comment]
I also saw this earlier during a new installation.
Since it was not declared as a warning or otherwise and there were no problems, I ignored it.

```
2024-08-06 10:55:36.347 INFO (MainThread) [supervisor.homeassistant.core] Starting HomeAssistant landingpage
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp1_1.py:57: SyntaxWarning: invalid escape sequence '\w'
  _STRING = "\w\.\-,\(\)@\#"
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp2_2.py:52: SyntaxWarning: invalid escape sequence '\d'
  _VALUE_PATTERN = "^([\d\w\._\-~%]+)$"
/usr/local/lib/python3.12/site-packages/cpe/cpe2_3_fs.py:97: SyntaxWarning: invalid escape sequence '\:'
  _parts_pattern = "^cpe:2.3:{0}\:{1}\:{2}\:{3}\:{4}\:{5}\:{6}\:{7}\:{8}\:{9}\:{10}$".format(
2024-08-06 10:55:36.467 INFO (MainThread) [supervisor.os.manager] Detect Home Assistant Operating System 12.4 / BootSlot A
```

**Comment by lorddaren** [comment]
I am getting the same error on my green, but I can't get my supervisor to come online or at least the Observer is stating:
```
Home Assistant observer
Supervisor: | Connected
-- | --
Supported: | Processing...
Healthy: | Processing...
```
Not sure if the issue is related.
