### ISSUE TITLE
2024.8.0: Updating addons resulted in "unsupported state" warning + "NetworkManager not correctly configured"

### ISSUE THREAD

**Issue by bcutter** [home-assistant/supervisor#5249]
### Describe the issue you are experiencing

I started an addon update and after few minutes I discovered nothing happened.
Reloaded supervisor, still nothing.
Restarted supervisor. Now in logs (truncated):

```
...
2024-08-14 20:38:34.938 WARNING (MainThread) [supervisor.resolution.evaluations.base] NetworkManager is not correctly configured (more-info: https://www.home-assistant.io/more-info/unsupported/network_manager)
...
2024-08-14 20:38:34.976 WARNING (MainThread) [supervisor.core] System running in a unsupported environment!
...
2024-08-14 20:38:36.777 WARNING (MainThread) [supervisor.host.services] Can't update host service information!
...
```

Now I get a not supported warning e. g. at `/hassio/system`:

![grafik](https://github.com/user-attachments/assets/eaf4cfd0-f6a6-4ee5-bb9e-40600b2f936a)

Following the warning leads to https://www.home-assistant.io/more-info/unsupported/network_manager

As I'm running HA OS I'm very sure I shouldn't do anything here on the network/host part.
It looks like somehow Supervisor got a bit out of operation. It's the first time I tried to update an addon since updating Supervisor from 2024.6.2 to 2024.8.0 on 2024-08-06.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

See initial issue description

### Anything in the Supervisor logs that might be useful for us?

```txt
See initial issue description
```

## System Information

version | core-2024.2.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1471
Downloaded Repositories | 86
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 57.8 GB
disk_used | 42.5 GB
healthy | true
supported | failed to load: Unsupported
board | rpi4-64
supervisor_api | ok
version_api | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 52
views | 79
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 31. Juli 2024 um 15:30
-- | --
current_recorder_run | 3. August 2024 um 16:22
estimated_db_size | 2756.52 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by bcutter** [comment]
Pardon, very likely not related to Supervisor. I restarted the host meanwhile and managed to update two addons, now monitoring it currently.

From a supervisor point of view I think this can be closed. From a personal view I'm interested in how to access host logs from before the last reboot to see what in HA OS ruined the NetworkManager part that much everything got massively affected by that - except HA itself which ran just fine until I hit the host restart button.

**Comment by mdegat01** [comment]
Actually we've put this in the HA CLI now:
```
# ha host logs -h

Allows you to look at the systemd journal on the host to see logs
across services and boots.

Usage:
  ha host logs [flags]
  ha host logs [command]

Aliases:
  logs, log, lg

Examples:

  ha host logs


Available Commands:
  boots       Show all boot IDs by offset
  identifiers Show all syslog identifiers

Flags:
  -b, --boot string         Logs of particular boot ID
  -f, --follow              Continuously print new log entries
  -h, --help                help for logs
  -t, --identifier string   Show entries with the specified syslog identifier
  -n, --lines uint32        Number of log entries to show
  -v, --verbose             Return logs in verbose format

Global Flags:
      --api-token string   Home Assistant Supervisor API token
      --config string      Optional config file (default is $HOME/.homeassistant.yaml)
      --endpoint string    Endpoint for Home Assistant Supervisor (default is 'supervisor')
      --log-level string   Log level (defaults to Warn)
      --no-progress        Disable the progress spinner
      --raw-json           Output raw JSON from the API

Use "ha host logs [command] --help" for more information about a command.
```
So you can just do `ha host logs -b 1` and it should work the same. The logs from the system journal are also available in the logs page now if you switch the toggle in the top right to "Host" but there are no filters available there currently.

**Comment by bcutter** [comment]
Thx, figured out "ha host logs -b-1 -n1000" meanwhile, unfortunately it gave "Logs only contain 1 boots".

So it seems I won't be able to track down the original issue due to a lack of pre-boot logs.

Anyway, I think not a Supervisor issue. Feel free to close.
