### ISSUE TITLE
SyntaxWarning on Supervisor startup

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/supervisor#5292]
### Describe the issue you are experiencing

Hello,

saw this log in supervisor, when updating to supervisor 2024.9.0

```
2024-09-05 06:03:07.687 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/generic-x86-64-homeassistant with version 2024.9.0
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp1_1.py:57: SyntaxWarning: invalid escape sequence '\w'
  _STRING = "\w\.\-,\(\)@\#"
/usr/local/lib/python3.12/site-packages/cpe/cpe2_3_fs.py:97: SyntaxWarning: invalid escape sequence '\:'
  _parts_pattern = "^cpe:2.3:{0}\:{1}\:{2}\:{3}\:{4}\:{5}\:{6}\:{7}\:{8}\:{9}\:{10}$".format(
  ```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Install Sup 2024.9.0
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
see message above
```

### System Health information

no repairs

**Comment by agners** [comment]
Hm, yeah this is addressed by this change upstream: https://github.com/nilp0inter/cpe/pull/63

But there is no release just yet. I guess we have to suppress this warning as well, similar to previous warnings (see #5227). It is not quite clear to me why this one only pops up now :thinking:

**Comment by Anto79-ops** [comment]
Ah, okay, it's possible that it's not related to 2024.9, and perhaps it's been there all that time, and I've only now started looking at supervisor logs.

I'm glad you're aware of it. I can definitely close this if you want.

**Comment by agners** [comment]
Just checked, yes it was already there in 2024.08.0:

```
2024-08-21 20:23:11.020 INFO (MainThread) [supervisor.docker.supervisor] Attaching to Supervisor ghcr.io/home-assistant/amd64-hassio-supervisor with version 2024.08.0
...
2024-08-21 20:23:19.288 INFO (MainThread) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/qemux86-64-homeassistant with version 2024.8.1
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp1_1.py:57: SyntaxWarning: invalid escape sequence '\w'
  _STRING = "\w\.\-,\(\)@\#"
/usr/local/lib/python3.12/site-packages/cpe/comp/cpecomp2_2.py:52: SyntaxWarning: invalid escape sequence '\d'
  _VALUE_PATTERN = "^([\d\w\._\-~%]+)$"
/usr/local/lib/python3.12/site-packages/cpe/cpe2_3_fs.py:97: SyntaxWarning: invalid escape sequence '\:'
  _parts_pattern = "^cpe:2.3:{0}\:{1}\:{2}\:{3}\:{4}\:{5}\:{6}\:{7}\:{8}\:{9}\:{10}$".format(
...
```
