### ISSUE TITLE
Supervisor failed to start with error "exec /init: exec format error"

### ISSUE THREAD

**Issue by DeminLi** [home-assistant/supervisor#5304]
### Describe the issue you are experiencing

I have run HA in RP4 for years but it is completely broken 6 days ago, it matched the time the supervior get upgraded. Seems the issue happened on version 2024.09.0 and above
The error "hassio_superviosr: exec /init: exec format error" is shown on `systemctl status docker.service`, and can be reproduced when running
`docker run docker pull ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.09.0`

Manually pulling 2024.08.0 image can bypass the error, however, looks like I lost everything, now my HA is empty.
I have backed up my sd files, so I can recover it all, no worries. Any suggestion about how to resolve the "exec format error" is welcome.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. restart my HA
2. check "systemctl status docker.service"
...

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### System Health information

N/A

### Supervisor diagnostics

N/A

**Comment by agners** [comment]
> I have run HA in RP4 for years but it is completely broken 6 days ago, it matched the time the supervior get upgraded. Seems the issue happened on version 2024.09.0 and above

2024.09.0 did not got released to stable. So most likely this was the upgrade to 2024.09.1.

> Manually pulling 2024.08.0 image can bypass the error, however, looks like I lost everything, now my HA is empty.

Sorry to hear that. :cry:  Supervisor doesn't deal with `/config` much, so this is unlikely caused by Supervisor itself. I'd guess this is a hardware failure. Do you use a SD card? They are known to fail hard suddenly. Probably the Supervisor upgrade caused some extra writes to the SD, which pushed it over the edge :cry:

**Comment by DeminLi** [comment]
It is actually failed on 2024.09.1, but I found that it also failed on 2024.09.0, until I see it succeed on 2024.08.0.
Yes, I am using sd card, and copying data to a new sd card doesn't resolve the issue.
Is there any way to reset supervisor or downgrade it without erasing my data?

**Comment by agners** [comment]
If you have a full backup, you can try to clear the Docker data storage. It is a bit a hack, a full backup and start over is always recommended. Here are the details on that approach: https://community.home-assistant.io/t/help-home-assistant-cannot-start-after-forced-reboot-audio-layer-cannot-be-installed/724463/11?u=agners
