### ISSUE TITLE
Missing translation for "Current Version:" in Add-on details etc.

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/supervisor#5362]
### Describe the issue you are experiencing

This is an updated cross-post from https://github.com/home-assistant/frontend/issues/22404 as requested.

While most of the Add-on details are translated and only those texts provided by the Add-on itself show up in English, the "Current version:" label has not been translated. Here with the German UI:

![377362594-9c84b393-fe3a-4934-89f8-cf4438a9f19e](https://github.com/user-attachments/assets/79e18fd2-d9e0-4c28-ac0b-eabcbb031ce8)

Especially as "Change log" is localized right next to it this should be fixed.

Note that "Core" is over-localized as "Kern" here, although this should remain "Core" in German, too.
I don't understand why this is the case because in Lokalise that string is correct since 2024-01-01.

There seems to be a longer standing issue with this string and probably more in that area as it's the same in other languages, here in Spanish:

![377599230-bbf03dec-5554-48e2-9fbc-5879ad3da727](https://github.com/user-attachments/assets/f1430cdb-ab1c-497d-b651-3726802f409e)

As you can see it says "Núcleo" in that place, but according to Lokalise this was also fixed to say "Core" in 2023, over a year ago.

While on this page this one could see a small improvement as well:

https://github.com/home-assistant/frontend/blob/6298534b9cb07a69ab0567711801ebb7af4870ed/src/translations/en.json#L7436-L7439

Should be "restart" or "relaunch" instead.

If you opt for "relaunch" also change this for consistency:

https://github.com/home-assistant/frontend/blob/6298534b9cb07a69ab0567711801ebb7af4870ed/src/translations/en.json#L7431-L7435

### What version of Home Assistant Core has the issue?

core-2024.10.3

### What type of installation are you running?

Home Assistant OS

**Comment by archita-a1903** [comment]
Hey, i want to work on this please assign me this project.

**Comment by silamon** [comment]
This issue has been fixed yesterday with https://github.com/home-assistant/supervisor/pull/5374.

**Comment by NoRi2909** [comment]
@silamon Confirmed, it works fine now. 😄
