### ISSUE TITLE
2024.11.2 installation

### ISSUE THREAD

**Issue by stain3565** [home-assistant/supervisor#5395]
### Describe the issue you are experiencing

Attempted to install. Fails every time.

My Home Assistant is a Home Assistant Yellow

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Simply click install
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-11-06 16:10:19.110 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-06 16:10:20.108 ERROR (MainThread) [supervisor.supervisor] Can't fetch AppArmor profile https://version.home-assistant.io/apparmor_stable.txt: Timeout
2024-11-06 16:10:20.109 CRITICAL (MainThread) [supervisor.supervisor] Abort update because of an issue with AppArmor: Can't fetch AppArmor profile https://version.home-assistant.io/apparmor_stable.txt: Timeout
2024-11-06 16:10:50.108 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-11-06 16:11:20.305 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-7716855' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1468> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1482, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
```

## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1476
Downloaded Repositories | 71

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 29 September 2025 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-9.ui.nabu.casa
certificate_status | ready
instance_id | 2334dad093c247fa8b69b2c522f4a8b0
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 469.4 GB
disk_used | 39.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | false
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (6.6.0), Terminal & SSH (9.15.0), MariaDB (2.7.1), Z-Wave JS UI (3.17.0), Studio Code Server (5.17.2), Mosquitto broker (6.4.1), Samba share (12.3.2), Grafana (10.1.3), InfluxDB (5.0.1), AppDaemon (0.16.7), Duck DNS (1.18.0), File editor (5.8.0), Z-Wave JS (0.9.0), Zigbee2MQTT (1.41.0-1), Ring-MQTT with Video Streaming (5.7.2), Samba NAS (12.2.0-nas2), TasmoAdmin (0.30.6), Ring Livestream (1.35), Samba Backup (5.2.0), Node-RED (18.1.1), ESPHome (2024.10.2), Piper (1.5.2), Whisper (2.2.0), openWakeWord (1.10.0), Git pull (7.14.1), JupyterLab (0.15.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 46
views | 71
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30 October 2024 at 12:57
-- | --
current_recorder_run | 6 November 2024 at 15:36
estimated_db_size | 2204.41 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

### Supervisor diagnostics

[config_entry-hassio-a1155c7fe5f57cf41caafd8ab6b2aec2.json](https://github.com/user-attachments/files/17650016/config_entry-hassio-a1155c7fe5f57cf41caafd8ab6b2aec2.json)

**Comment by Marinko67** [comment]
Just installed Supervisor 2024.11.2 -> Result: No Supervisor information viewable -> Just a blue circle
Switching to show Core Information resultes in "Failed to get core logs, e.callApiRaw is not a function"

**Comment by muhlpachr** [comment]
> Just installed Supervisor 2024.11.2 -> Result: No Supervisor information viewable -> Just a blue circle Switching to show Core Information resultes in "Failed to get core logs, e.callApiRaw is not a function"

Same for me, core-2024.10.4, Home Assistant OS 13.2

**Comment by Obicom** [comment]
Same for me ... 
![image](https://github.com/user-attachments/assets/f9fa5c7e-1d5b-4c01-892b-7e6e205ab783)
![image](https://github.com/user-attachments/assets/8adad962-6d4b-4d2f-bc47-d11d60789810)

**Comment by Arakon** [comment]
Same, still running core 2024.10.3, though.

**Comment by DanGarion** [comment]
I too am having the same issue after updating to Supervisor 11.2 this morning.

**Comment by cosminr86** [comment]
me too!

**Comment by thamow** [comment]
I experience the same issue from within the add on section, however I am able to see all logs via the Settings -> System -> Logs page. Can anyone check to see if this is true for you as well?

**Comment by DbilliT** [comment]
Just installed HA today, got the same issue for every add-on logs
![image](https://github.com/user-attachments/assets/7b06fe06-86e4-4cd2-bd8e-23e1f5f4450a)

**Comment by csdinos** [comment]
I have the same issue. 
Let me know if there are any system logs that might be helpful.

**Comment by cosminr86** [comment]
updating to core beta 2024.11.0b9 solved the issue

**Comment by fl0rian089** [comment]
i've got the same problem with my ha os vm. updated the supervisor and then e.callApiRaw

**Comment by thamow** [comment]
> I experience the same issue from within the add on section, however I am able to see all logs via the Settings -> System -> Logs page. Can anyone check to see if this is true for you as well?
@fl0rian089 could you check this real quick?

**Comment by fl0rian089** [comment]
yes i can confirm, that i can access all logs via settings -> system -> logs page :-)

**Comment by lcavalli** [comment]
Same here. Upgraded to 2024.11.0 right now, but the issue seems to be still present.

**Comment by nielsclavaux** [comment]
It have the same issue after updating.

**Comment by thorkseng** [comment]
Try to update the cache of the browser, I am using Edge, and with shift + F5 it works correctly and return the logs.

**Comment by DanGarion** [comment]
Appears logs have been "updated" with the release of core 11.0. Has anyone else noticed?

**Comment by fl0rian089** [comment]
just updated to core 2024.11.0, problem is gone.

**Comment by herkne** [comment]
In my installation it has the wrong architecture for the homassistant image:

REPOSITORY                                            TAG           IMAGE ID       CREATED         SIZE
ghcr.io/home-assistant/aarch64-hassio-supervisor      2024.11.2     f9f659d3d2e9   22 hours ago    396MB
ghcr.io/home-assistant/aarch64-hassio-supervisor      latest        f9f659d3d2e9   22 hours ago    396MB
**ghcr.io/home-assistant/generic-x86-64-homeassistant**   landingpage   f08e0e4de1e3   4 weeks ago     6.31MB
ghcr.io/home-assistant/aarch64-hassio-cli             2024.09.0     5ed35e87800b   5 weeks ago     64.2MB
ghcr.io/home-assistant/aarch64-hassio-dns             2024.04.0     e91be38e9ff1   7 months ago    67.7MB
ghcr.io/home-assistant/aarch64-hassio-multicast       2024.03.0     8becb27d9446   7 months ago    51.9MB
ghcr.io/home-assistant/aarch64-hassio-audio           2023.12.0     06eec6839c57   11 months ago   87.5MB
ghcr.io/home-assistant/aarch64-hassio-observer        2023.06.0     1b4771b44876   16 months ago   7.49MB

**Comment by agners** [comment]
Ugh I see, OP actually reported a different issue than the frontend issue everyone was chiming in :cry: 

@stain3565 sorry about that! Best is if you check if you can reproduce the problem still on the latest version, and if so open a new issue. Please use not (just) the version number as title so people don't start to add unrelated issues to your issue.

**Comment by gladiacHD** [comment]
> > Supervisor update 2024.11.3 is now on the stable channel, so add-on logs should be working again after that update, hence I am closing this issue.
> > For those who still see the issue after updating Core to 2024.11.0 or later, this should be resolved after a frontend reload. You might have to do this manually using F5 or Ctrl+F5.
> > @herkne your issue is not related to this issue. Please report a new issue.
> 
> I get an error wehn trying to install the supervisor 11.3: (Do I have to wait a while for it to be available everywhere?
> 
> Failed to perform the action update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

I've got the exact same error message when trying to update the supervisor...
Any updates on this case?

**Comment by clevermarketing** [comment]
i have the same issues 

![Bildschirmfoto 2024-11-11 um 12 10 52](https://github.com/user-attachments/assets/fbff6dc6-4ff5-4ec7-ac57-6b268657abd0)

**Comment by GeorgesVDR** [comment]
Same issue here :)

**Comment by wendevlin** [comment]
FYI, you can check your addon logs via the core logs. Settings/System/Logs and use the dropdown on the top right.

**Comment by FlavioRadice** [comment]
> updating to core beta 2024.11.0b9 solved the issue

Thanks! this is working !
