### ISSUE TITLE
Still on Supervisor 2024.11.2 - No update shown for 2024.11.4

### ISSUE THREAD

**Issue by gfn256** [home-assistant/supervisor#5431]
### Describe the issue you are experiencing

After the failed 11.3 update - I am stuck on 11.2 even though 11.4 shows as released on Github for 4 days.
In HA, I choose the search for updates in the GUI, but none are presented.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Search for updates

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing interesting
```

### System Health information

There are currently no repairs pending

**Comment by HaraldGithub** [comment]
I think it's no bug, because supervisor 2024.11.4 is still in beta-channel.

If you like to install 2024.11.4 (I've done so and there are no problems with supervisor or ha):
enable "beta-channel", update supervisor to 2024.11.4, disable "beta-channel"
ready!

**Comment by erkr** [comment]
I was wondered when we get the new version as well. Where can we lookup the status of such a release (e.g still beta)?

**Comment by gfn256** [comment]
Thanks - I wrongly assumed that "Releases" only contain stable ones.
Found this explanation in the HA [forums](https://community.home-assistant.io/t/latest-supervisor-version/448727).

**Comment by gfn256** [comment]
Solved
