### ISSUE TITLE
Unable to resolve mDNS machines on my LAN using HassIO installed on HassOS

### ISSUE THREAD

**Issue by DeviousPenguin** [home-assistant/supervisor#804]
When using HassIO installed on HassOS on my Raspberry Pi 3 I'm unable to access `*.local` machines on my network from the docker containers:

For example with MQTT in HomeAssistant I'm unable to access `mqtt_broker.local` but if I put in it's IP address directly eg. `192.168.1.99` then I'm able to connect, but then the Auth fails on my MQTT server as it's using TLS which only allows connections to `mqtt_broker.local`

It's not just HA container either, I tried out the NodeRED addon, v1.0.1, and faced the exact same issue, leading me to believe this is an issue with HassIO not HA.

I'm using the exact same config files that I used on a Raspbian install of HA under `VirtualEnv`, and connected without issue under Raspbian, but when using HassIO under HassOS if fails every time.

I'm logged in on port 22222 for testing, here's an nslookup from in the HA container:

```
$ docker container exec homeassistant ping -c1 mqtt_broker.local
ping: bad address 'mqtt_broker.local'
```

On Raspbian I'm able to resolve without issue:

```
$ ping -c1 mqtt_broker.local
PING mqtt_broker.local (192.168.1.99): 56 data bytes
1 packets transmitted, 1 packets received, 0.0% packet loss
```

**Comment by pvizeli** [comment]
maybe it need some things inside docker container?

**Comment by DeviousPenguin** [comment]
Hi, thanks, yes I've found that adding there packages: `avahi-daemon avahi-discover avahi-utils libnss-mdns` may help:

I tried out HassIO on Raspbian just to see if it was a HassOS issue but I get the same connection errors under Raspbian while running the HassIO docker containers. If I stop the Docker containers and load up HA in VirtualEnv it connects without issue.

After some research it seems that it is Docker that breaks mDNS on LAN which is a pain, many others with the same issue with Docker and not many workarounds.

I did manage to find a Docker container which has working mDNS here:

https://github.com/hausgold/docker-node

I spun it up and I was able to ping my 'mqtt_broker.local' and it resolves correctly. Looking at the `Dockerfile` it's using these extra packages:

`avahi-daemon avahi-discover avahi-utils libnss-mdns haproxy supervisor`

I'm going to see if I can get working with Node-RED added the above example first as it's easy to tweak the MQTT server settings, then if that works then I'll see if I can add the packages and configure them in the HA container.

**Comment by jesjimher** [comment]
That's not an actual solution, because IP might come from DHCP and not only be the same (that's the point of .local domains and mDNS). Home Assistant Docker container needs fixing in order to properly support mDNS resolution of .local names.
