### ISSUE TITLE
Unable to resolve mDNS machines on my LAN using HassIO installed on HassOS

### ISSUE THREAD

**Issue by olskar** [home-assistant/supervisor#884]
**Home Assistant release with the issue:**
0.85

**Operating environment (HassOS/Generic):**
HassOS 1.13

**Description of problem:**
When using HassIO installed on HassOS on my Raspberry Pi 3 I'm unable to access *.local machines on my network from the docker containers. On Hassbian this did work, I suspect its a problem in HassOS and related to Docker.

`
core-ssh:~# ping nas.local
ping: bad address 'nas.local'
`

**Comment by olskar** [comment]
This is same problem as #804 but since that is closed and problem persists, I open this.

**Comment by mmalina** [comment]
I'm having the issue (Home Assistant 0.88.2).

**Comment by olskar** [comment]
This is not fixed and should remain open

**Comment by robdejonge** [comment]
I'm having this same issue, running 0.94.1. 

mDNS is working just fine on the host OS, but it does not work either when I refer to `device.local` in `configuration.yaml` or when I log on to the community ssh add-on.

**Comment by austwhite** [comment]
I am currently having this issue.  Home Assistant version 0.97.1 running as Hassio.  
Hassio Supervisor 173.
HassOS 2.12
Production Version.

The issue seems to be HASSIO is picking up an IP V6 address, despite the fact my DNS server and all local machines are set to only use IPv4 on the local network.  
when I ping HASSIO.local, it pings to an IPv6 address, but this will not work when I go to http://hassio.local:8123.  If I go to the IPv4 address http://192.168.0.xxx:8123 I can access the interface fine.
mDNS is working, but for some reason it wont resolve to the IPv4 address, only to the IPv6 address which just does not work on the local network.
I can access remote via the Nabu Casa Cloud, but it is extremely slow trying to move between pages.

**Comment by DeviousPenguin** [comment]
You can do a workaround for this my editing the hosts file but it seems like a bit of a hack, I needed to do this in order to get MQTTS working

**Comment by tobozo** [comment]
Assigning LAN IPs manually somehow defeats the "automation" idea behind this project, mDNS situation labelled as wontfix by a stale bot after 10 months is also kinda (h)assy, could a maintainer specify what needs to be done to fix this strange situation ? 

Is that a docker issue ? a hassio issue ? both ?

**Comment by DeviousPenguin** [comment]
> Assigning LAN IPs manually somehow defeats the "automation" idea behind this project

I tried many things as I need MQTTs functionality one way or another, but I would not recommend that newer or less experienced users go in and edit the hosts file without knowing what they are doing. 

> Is that a docker issue ? a hassio issue ? both ?

I'm not entirely sure, I'm thinking it's more a HassIO issue as mDNS is functional under docker if port 5353 is exposed.

However I'm no longer using HassIO or docker so am unable to test fixes/worksarounds anymore.

**Comment by pvizeli** [comment]
That is an musl issue in which the resolution did not support mdns.

**Comment by olskar** [comment]
The issue is still present

**Comment by narfel** [comment]
This is strange. On a ubuntu server running docker the mdns answers with the ip of the docker0:  172.17.0.1 interface and it works. On my hassio server the answer is neither the docker0 172.17.0.1 nor the hassio 172.30.32.1, but a completely unknown 169.254.146.177 that is not accessible or defined anywhere inside or outside my network (_nmcli lan | grep 169_ is empty).

**Comment by triggerx** [comment]
Also having this issue... ugh.

**Comment by narfel** [comment]
Has someone looked at this? https://pythonspeed.com/articles/alpine-docker-python/ Not sure if i am allowed to post this here, i neither understand it completely nor do i know the relevance or if the hass team already knows this. But it suggests to not use alpine for image size use and build time by 2x respectively 50x times. That way we could get musl :)

**Comment by frenck** [comment]
@narfel, we build and distribute our own Python and pre-build Wheel packages and do not suffer from those issues mentioned in the blog post.

**Comment by pvizeli** [comment]
If we get a coredns crack on board, we can try to solve this on our DNS instance. I don't know why but I'm not affected by this bug on all my instance

**Comment by jschwalbe** [comment]
> However I'm no longer using HassIO or docker so am unable to test fixes/worksarounds anymore, but hopefully it will get fixed if it is an OS issue.

@DeviousPenguin slightly off-topic, but what are you using instead? I'm tired of these docker mDNS issues.

**Comment by pvizeli** [comment]
fix with s215

**Comment by jschwalbe** [comment]
@pvizeli sorry but what does s215 mean?

**Comment by narfel** [comment]
My guess is, he is refering to Supervisor version v215. We're on 217 now. However nothing changed in that problem for me.

**Comment by pvizeli** [comment]
In case of that, you have a network issue. You can try to debug what the Home Assistant device can see if you enable the debug logging on Supervisor, restart the DNS plugin and now you can monitor what come in. If you don't see the traffic from your NAS on multicast or dns plugin, maybe you need enable multicast on the switchport or need change firewall.

**Comment by jschwalbe** [comment]
For what it’s worth, I set up AdGuard on a raspberry pi and took it OFF my HA machine. That seemed to have solved my issues more than anything.

**Comment by mmalina** [comment]
I was affected by this from the beginning (since last summer), so I was curious if it's really fixed. I changed my yamaha receiver to use the local dns name (*.local) in Home Assistant and it works now! Great! (This didn't work before.)

@pvizeli do you have a link for the fix? Is it this one? https://github.com/home-assistant/supervisor/pull/1634

**Comment by frenck** [comment]
That is part of the fix, also part of addressing this:

https://github.com/home-assistant/plugin-multicast

And a whole bunch of changes to the Home Assistant DNS container.

**Comment by Mechazawa** [comment]
For me it still doesn't work unless I disable AdGuard
