### ISSUE TITLE
curl missing LDAP protocol

### ISSUE THREAD

**Issue by olbjan** [home-assistant/supervisor#940]
**Home Assistant release with the issue:**
0.88 and 0.89

**Operating environment (HassOS/Generic):**
HassOS 2.10 on Intel NUC

**Supervisor logs:**

**Description of problem:**
Trying to use the commandline auth provider against an LDAP server is currently not possible in Hass.io / HassOS installations as the provided curl does not support the LDAP protocol or ldapsearch.

This is required by the linked example script as linked in the HA documentation:
https://www.home-assistant.io/docs/authentication/providers/ -->
https://github.com/efficiosoft/ldap-auth-sh

**Comment by olbjan** [comment]
I checked that on hass.io Supervisor 162 and hassOS 2.11 curl still does not include LDAP support.

**Comment by frenck** [comment]
Our containers for Hass.io are based on Alpine Linux.

Alpine Linux does not ship CURL with LDAP support.
See also here: https://git.alpinelinux.org/aports/tree/main/curl/APKBUILD#n94

This isn't "fixable" from our end.

**Comment by nununo** [comment]
Hi @olbjan did you manage to integrate LDAP with Hassio? I've bumped into the same problem. I'm considering reinstalling Hassio on top of Debian to avoid these limitations but I'd like to avoid going through that trouble if I could. Did you find a workaround? Thanks

**Comment by olbjan** [comment]
@nununo Sorry, I've basically given up on this for the time being. LDAP auth is nice but not as important for me that I'm willing to roll my own OS below HA....

**Comment by nununo** [comment]
@olbjan makes sense. I already had in mind trying to install HA over Debian so I may still give it a try if I get to do it.

**Comment by Mystery-X** [comment]
I'm also trying, 
But since the curl is no option, i'm currently investigating the ldapsearch route.
installing the ldapsearch was easy : 

`core-ssh:~# apk add openldap-clients
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/armv7/APKINDEX.tar.gz
(1/4) Installing db (5.3.28-r1)
(2/4) Installing libsasl (2.1.27-r3)
(3/4) Installing libldap (2.4.48-r0)
(4/4) Installing openldap-clients (2.4.48-r0)
Executing busybox-1.30.1-r2.trigger
OK: 76 MiB in 67 packages`

**Comment by pvizeli** [comment]
curl work, we need only build our own version on the image

**Comment by nununo** [comment]
I finally managed to integrate LDAP with Hassio.
I had to perform some extra hacks to make it work:
- I followed this [this tip](https://community.home-assistant.io/t/new-home-assistant-alpine-docker-image-curl-ldaps-not-supported/134572/10) to install ldapsearch inside the Hassio image (although I had to tweak the command to `docker exec -t -i homeassistant apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/main --repository http://dl-cdn.alpinelinux.org/alpine/edge/community openldap-clients`;
- Since my LDAP server uses STARTTLS, I had to copy the LDAP server's certificate to the `config/ldap-auth-sh/` folder and configure /etc/openldap/ldap.conf to point to it;
- Edited the script to include the option -ZZ in the `common_opts`.

Most probably an upgrade will break something. I'll wait and see. Anyway, it's working ;)

**Comment by nununo** [comment]
It would be great, though, if LDAP integration would be easier to implement in Hassio...

**Comment by darootler** [comment]
I would also love to have LDAP authentication supported by Hass.io.

Regards
Richard

**Comment by mountainsandcode** [comment]
The suggestion posted by @nununo also works for me - but I fear it'll have to be run upon every pull of a docker image (i.e., every HA version update). Any chance we can package openldap-clients with the image while waiting for a compiled version of curl with ldap? Would be super!

**Comment by nununo** [comment]
Indeed @mountainsandcode, mine is already broken and I've been lazy to retweak it :-) Native LDAP support would be so great.

**Comment by mountainsandcode** [comment]
@pvizeli Would love to support somehow (e.g., with a PR) but not familiar at all with OS-level development. Any pointers or can we support somehow to get this implemented?

**Comment by pvizeli** [comment]
> curl work, we need only build our own version on the image

**Comment by darootler** [comment]
Hmm, still no ldap support for curl or am i missing something?

Regards
Richard

**Comment by Larx** [comment]
I'm interested, too.
(Should be mentioned in the docs, too. The way to get LDAP support as described in the docs does not work with the officially preferred way of installation ;-/ .)

**Comment by adamoutler** [comment]
The big problem here is the linked LDAP Auth script is all wrong for ldapsearch. Their BASEDN is used for BINDDN, and HOST isn't used at all.  I'm sure it would work if you already had LDAP Auth set up on your system, but as-is, it's all messed up and unusable.  I'm willing to bet the number of people using HASSIO ldap auth with the script is near-zero, and includes those who figured out how to install curl.

**Comment by Larx** [comment]
Anybody found a workaround yet?

**Comment by adamoutler** [comment]
Yeah.  Let me organize my notes...  It was frackin' rediculous what I had
to do.

**Comment by adamoutler** [comment]
> Anybody found a workaround yet?

I created a topic here for hassio.  It uses ssh to log into a remote computer with ldapsearch installed. It's messy but it works.  https://community.home-assistant.io/t/hassos-ldap-command-line-authentication-over-ssh/228852

**Comment by rjmidau** [comment]
> Anybody found a workaround yet?

There is currently an open PR to add LDAP as an authentication provider to Core: home-assistant/core#37645

**Comment by adamoutler** [comment]
Here's a workaround.   Use SSH to access a computer which has LDAP Search. https://community.home-assistant.io/t/hassos-ldap-command-line-authentication-over-ssh/228852

**Comment by samsam-rolon** [comment]
I'm intrested in also but still nothing in docker 2021.4.1

**Comment by samsam-rolon** [comment]
> 

But it's not working in Docker because you need to "custom" inside the container ...

**Comment by wez** [comment]
I was also disappointed by the example referenced in the docs not working, so I wrote a script to talk to an Authelia instance (backed by LDAP) using regular HTTPS rather than LDAP:

* https://github.com/authelia/authelia/discussions/4681

**Comment by adamoutler** [comment]
I set up a Basic Auth authentication method.   All you have to do is create any apache/nginx with a static page protected by Basic Auth and point the script at that site.  If that site provides an HTTP 200 response, then you will be able to login.   If you get an unauthorized or other error, it will prevent login.   I set up LDAP on my basic auth and it essentially works the same as managing from this script.   Please note, if your DNS is poisoned or the site is compromised, it will compromise the login for HA.  However, it's easier to set this up than to set up  LDAP on HA OS.

https://gist.github.com/adamoutler/c2dc2618de03ce26c9fefc7a40cf11af

**Comment by darootler** [comment]
> I set up a Basic Auth authentication method. All you have to do is create any apache/nginx with a static page protected by Basic Auth and point the script at that site. If that site provides an HTTP 200 response, then you will be able to login. If you get an unauthorized or other error, it will prevent login. I set up LDAP on my basic auth and it essentially works the same as managing from this script. Please note, if your DNS is poisoned or the site is compromised, it will compromise the login for HA. However, it's easier to set this up than to set up LDAP on HA OS.
> 
> https://gist.github.com/adamoutler/c2dc2618de03ce26c9fefc7a40cf11af

Thank you for sharing this, i'll give it a try.

It's really sad that the builtin curl version doesn't support ldap like every other curl does.

Regards
Richard

**Comment by darootler** [comment]
@adamoutler 

I was able to set everything up and authentication is working. But the user signed in was not mapped to Home Assistant user:

![image](https://user-images.githubusercontent.com/11849583/210418134-39043e70-d919-4592-9a8d-199393f2ecb1.png)
![image](https://user-images.githubusercontent.com/11849583/210418159-5b9e9b7e-5b54-4066-a440-d6e5bb0bd603.png)

I played around with echoing the user but without success. Do you had success with passing back the username to Home Assistant?

**Comment by adamoutler** [comment]
Echo only works for the first login. After that, you have to delete the user.

**Comment by darootler** [comment]
I was able to map the person to the new user (LDAP) and give the new user "owner" permissions. You have to edit the /config/.storage/auth and /config/.storage/person

Here is the updated script is use:

```
#! /bin/bash
# Basic Authentication login for Home Assistant.
# Adam Outler <homeassistant@adamoutler.com>
#
# To prevent vulnerability to DNS poisoning attack use HSTS on the serve in HOSTNAME,
# or specify a local IP address on your trusted LAN.
#
# Modify HOSTNAME to your site.

HOSTNAME="https://owncloud.marschik.biz/ocs/v1.php" #site to use for basic auth validation
response=$(curl -u"${username}:${password}" -I ${HOSTNAME} 2>/dev/null|head -n1|cut -d$' ' -f2 ); 
[ "${response}" == "200" ] && echo "name = ${username}"; exit 0;   #exit 0 if we get a 200 HTTP Status Code.
exit 187;   #exit with a non-zero response.
```

And here is the config is use:

```
homeassistant:
  auth_providers:
      - type: command_line
        command: /config/python_scripts/basic-auth.sh
        args: ["--username", "--password"]
        meta: true
```

Thanks for your input @adamoutler 

Regards
Richard

**Comment by adamoutler** [comment]
You made the script better.  I just changed my display name when I logged in the first time and forgot about it.

**Comment by Larx** [comment]
My solution currently is running webhookd (https://github.com/ncarlier/webhookd/) on the host system (easy to install, is a single binary). So you can use a modified ldap-auth.sh script with curl and/or ldapsearch on the host and only need a kind of "proxy" authentication script in the container (to call the webhook and to make authentication fail if the webhook does not return "name=xyz").
Is only suitable for local, trusted installs, probably, but the advantage is that webhookd can be used for lots of things from the homeassistant container to the host system.

**Comment by danielriddell21** [comment]
> I finally managed to integrate LDAP with Hassio. I had to perform some extra hacks to make it work:
> 
>     * I followed this [this tip](https://community.home-assistant.io/t/new-home-assistant-alpine-docker-image-curl-ldaps-not-supported/134572/10) to install ldapsearch inside the Hassio image (although I had to tweak the command to `docker exec -t -i homeassistant apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/main --repository http://dl-cdn.alpinelinux.org/alpine/edge/community openldap-clients`);
> 
>     * Since my LDAP server uses STARTTLS, I had to copy the LDAP server's certificate to the `config/ldap-auth-sh/` folder and `configure /etc/openldap/ldap.conf` to point to it;
> 
>     * Edited the script to include the option `-ZZ` in the `common_opts`.
> 
> 
> Most probably an upgrade will break something. I'll wait and see. Anyway, it's working ;)

Does this work between updates? 
Also I am still having issues after running your fix to alpine, it still doesn't want to authenticate

**Comment by nununo** [comment]
> @nununo Does this work between updates? Also I am still having issues after running your fix to alpine, it still doesn't want to authenticate

No it doesn't. I actually gave up on it because it stopped working after an update. I ended up giving up on this because it wasn't a priority. It's a shame, though.

**Comment by koliwbr** [comment]
I know this is an old topic, however, I found another solution - compile curl statically on another machine and move only curl with ldap support.
Here are the commands I used (on another machine) to compile curl, the finished file I moved to the HO configuration directory:
```bash
apt install build-essential wget
wget https://github.com/curl/curl/releases/download/curl-8_10_1/curl-8.10.1.tar.gz
cd curl-8.10.1/
 ./configure  --disable-http --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-proxy --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-mqtt --disable-manual --disable-docs --enable-ldaps --enable-ldap  --without-ssl --without-libpsl --disable-verbose --disable-shared --enable-static
make
cd ..
cp  curl-8.10.1/lib/curl .
```

**Comment by adamoutler** [comment]
Maybe contribute curl with all enabled to chaos?

**Comment by Ra72xx** [comment]
OK, as I don't really like my hacky solution above (https://github.com/home-assistant/supervisor/issues/940#issuecomment-1744219344), I tried another way: You can also use static ldapsearch binaries from this unfortunately very outdated repo https://github.com/home-assistant/supervisor/issues/940#issuecomment-1744219344 , as the ldap-auth.sh script also can use this command.

**Comment by koliwbr** [comment]
> On which Linux distro?
On Debian 12

Sorry, I wrote this post before I checked if curl works on Alpne (like HO) and it turned out that it does not.
I checked on another Debian-based system
As @Ra72xx mentioned I used statically compiled ldapsearch using musl (like Alpine).
Due to the size of the project the whole thing went much more smoothly and works :)

I will edit this post with the commands I used

**Comment by Ra72xx** [comment]
Thanks. Based on that a quick and very untested script to compile ldapsearch within the Alpine HA container:

```
#!/bin/sh

INSTALL=/config/local_ldap_auth/
BUILD=/tmp
cd $BUILD || exit 1
git clone https://git.openldap.org/openldap/openldap.git
cd openldap
apk --update add build-essentials musl-dev groff -y
./configure
make
test -f client/tools/ldapsearch || exit 1
test -f $INSTALL/ldapsearch && mv $INSTALL/ldapsearch $INSTALL/ldapsearch.old
mv client/tools/ldapsearch $INSTALL
```

**Comment by avbor** [comment]
Hi, I have built static openldap tools, works without problems on HA OS, you can get it here - https://github.com/avbor/HomeAssistantConfig/tree/master/ldap

**Comment by Techman** [comment]
Just a note to anyone using @avbor's [script](https://github.com/home-assistant/supervisor/issues/940#issuecomment-2482095032) with the hope of using this with Authentik's LDAP outpost:

1. Any use of `uid=` to match usernames needs to be changed to `cn=`, as the `uid` field contains a unique identifier.
2. `$SCOPE` needs to be `subtree`, not `base`. Using `base` will result in nothing returned.
3. Pass in group names as their full DN, e.g. `cn=homeassistant_user,ou=groups,ou=homeassistant,dc=ldap,dc=goauthentik,dc=io` if this was not clear enough already. (Base DN set in the Provider for this example: `ou=homeassistant,dc=ldap,dc=goauthentik,dc=io`)
4. Using `cn` as the first name for display name will be lowercase. Instead, add `givenName` to $ATTRS and change the `DISPLAY_NAME=` line towards the bottom to be `DISPLAY_NAME=$(echo $output | jq -jr '.[] | .givenName.[]," ",.sn.[]')`
5. This is not currently an issue, but if you ever need the search query to only return a single result when successful, change `FILTER` to `FILTER="(&(cn=$(ldap_dn_escape "$username"))(memberOf=${HA_USERS_GRP}))"` The default is to match all users in the specified Home Assistant users group.
6. If you want to know the result of what the computed display name and group membership tests will be, change the log line at the end of the script to `log "User '$username' with DN '$(echo $output | jq -r '.[].dn.[]')' authenticated successfully. [DISPLAY_NAME='$DISPLAY_NAME', IS_ADMIN='$IS_ADMIN', IS_LOCAL='$IS_LOCAL']"`.

It took me way too many hours to try and figure out what was going on. I uploaded my edits [here](https://gist.github.com/Techman/3114de12b2ef0e3502bf74c44e19d722) for the time being. I suppose a future enhancement would be the ability to specify the attribute used for usernames.
